drop table if exists `Account`;
CREATE TABLE `Account` (
 id varchar(64),
Account_Cvg_Cvg TEXT,
Account_Cvg_Priority TEXT,
Account_Dscrptn TEXT,
Account_Guarantor_OnHold TEXT,
Account_Guarantor_Party TEXT,
Account_Guarantor_Prd_End TEXT,
Account_Guarantor_Prd_Strt TEXT,
Account_Id_Assigner TEXT,
Account_Id_Prd_End TEXT,
Account_Id_Prd_Strt TEXT,
Account_Id_Sys TEXT,
Account_Id_Typ_Cdg_Cd TEXT,
Account_Id_Typ_Cdg_Dsply TEXT,
Account_Id_Typ_Cdg_Sys TEXT,
Account_Id_Typ_Cdg_UsrSltd TEXT,
Account_Id_Typ_Cdg_Vrsn TEXT,
Account_Id_Typ_Txt TEXT,
Account_Id_Use TEXT,
Account_Id_Vl TEXT,
Account_Nm TEXT,
Account_Owner TEXT,
Account_PartOf TEXT,
Account_SrvPrd_End TEXT,
Account_SrvPrd_Strt TEXT,
Account_Sts TEXT,
Account_Sbjct TEXT,
Account_Typ_Cdg_Cd TEXT,
Account_Typ_Cdg_Dsply TEXT,
Account_Typ_Cdg_Sys TEXT,
Account_Typ_Cdg_UsrSltd TEXT,
Account_Typ_Cdg_Vrsn TEXT,
Account_Typ_Txt TEXT,
PRIMARY KEY(id)) ENGINE=MyISAM
    ROW_FORMAT=COMPRESSED 
    KEY_BLOCK_SIZE=8;