drop table if exists `BodyStructure`;
CREATE TABLE `BodyStructure` (
 id varchar(64),
BodyStrctr_Active TEXT,
BodyStrctr_Dscrptn TEXT,
BodyStrctr_Id_Assigner TEXT,
BodyStrctr_Id_Prd_End TEXT,
BodyStrctr_Id_Prd_Strt TEXT,
BodyStrctr_Id_Sys TEXT,
BodyStrctr_Id_Typ_Cdg_Cd TEXT,
BodyStrctr_Id_Typ_Cdg_Dsply TEXT,
BodyStrctr_Id_Typ_Cdg_Sys TEXT,
BodyStrctr_Id_Typ_Cdg_UsrSltd TEXT,
BodyStrctr_Id_Typ_Cdg_Vrsn TEXT,
BodyStrctr_Id_Typ_Txt TEXT,
BodyStrctr_Id_Use TEXT,
BodyStrctr_Id_Vl TEXT,
BodyStrctr_Image_CntntTyp TEXT,
BodyStrctr_Image_Creation TEXT,
BodyStrctr_Image_Data TEXT,
BodyStrctr_Image_Hash TEXT,
BodyStrctr_Image_Lnguage TEXT,
BodyStrctr_Image_Sz TEXT,
BodyStrctr_Image_Ttl TEXT,
BodyStrctr_Image_Url TEXT,
BodyStrctr_Lctn_Cdg_Cd TEXT,
BodyStrctr_Lctn_Cdg_Dsply TEXT,
BodyStrctr_Lctn_Cdg_Sys TEXT,
BodyStrctr_Lctn_Cdg_UsrSltd TEXT,
BodyStrctr_Lctn_Cdg_Vrsn TEXT,
BodyStrctr_Lctn_Txt TEXT,
BodyStrctr_LctnQualifier_Cdg_Cd TEXT,
BodyStrctr_LctnQualifier_Cdg_Dsply TEXT,
BodyStrctr_LctnQualifier_Cdg_Sys TEXT,
BodyStrctr_LctnQualifier_Cdg_UsrSltd TEXT,
BodyStrctr_LctnQualifier_Cdg_Vrsn TEXT,
BodyStrctr_LctnQualifier_Txt TEXT,
BodyStrctr_Morphology_Cdg_Cd TEXT,
BodyStrctr_Morphology_Cdg_Dsply TEXT,
BodyStrctr_Morphology_Cdg_Sys TEXT,
BodyStrctr_Morphology_Cdg_UsrSltd TEXT,
BodyStrctr_Morphology_Cdg_Vrsn TEXT,
BodyStrctr_Morphology_Txt TEXT,
BodyStrctr_Pnt TEXT,
PRIMARY KEY(id)) ENGINE=MyISAM
    ROW_FORMAT=COMPRESSED 
    KEY_BLOCK_SIZE=8;