drop table if exists `CareTeam`;
CREATE TABLE `CareTeam` (
 id varchar(64),
CareTeam_Ctgry_Cdg_Cd TEXT,
CareTeam_Ctgry_Cdg_Dsply TEXT,
CareTeam_Ctgry_Cdg_Sys TEXT,
CareTeam_Ctgry_Cdg_UsrSltd TEXT,
CareTeam_Ctgry_Cdg_Vrsn TEXT,
CareTeam_Ctgry_Txt TEXT,
CareTeam_Enc TEXT,
CareTeam_Id_Assigner TEXT,
CareTeam_Id_Prd_End TEXT,
CareTeam_Id_Prd_Strt TEXT,
CareTeam_Id_Sys TEXT,
CareTeam_Id_Typ_Cdg_Cd TEXT,
CareTeam_Id_Typ_Cdg_Dsply TEXT,
CareTeam_Id_Typ_Cdg_Sys TEXT,
CareTeam_Id_Typ_Cdg_UsrSltd TEXT,
CareTeam_Id_Typ_Cdg_Vrsn TEXT,
CareTeam_Id_Typ_Txt TEXT,
CareTeam_Id_Use TEXT,
CareTeam_Id_Vl TEXT,
CareTeam_ManagingOrgnztn TEXT,
CareTeam_Nm TEXT,
CareTeam_Nt_AthrRfrnc TEXT,
CareTeam_Nt_AthrStrgTyp TEXT,
CareTeam_Nt_Txt TEXT,
CareTeam_Nt_Time TEXT,
CareTeam_Prtcpnt_Mmbr TEXT,
CareTeam_Prtcpnt_OnBehalfOf TEXT,
CareTeam_Prtcpnt_Prd_End TEXT,
CareTeam_Prtcpnt_Prd_Strt TEXT,
CareTeam_Prtcpnt_Role_Cdg_Cd TEXT,
CareTeam_Prtcpnt_Role_Cdg_Dsply TEXT,
CareTeam_Prtcpnt_Role_Cdg_Sys TEXT,
CareTeam_Prtcpnt_Role_Cdg_UsrSltd TEXT,
CareTeam_Prtcpnt_Role_Cdg_Vrsn TEXT,
CareTeam_Prtcpnt_Role_Txt TEXT,
CareTeam_Prd_End TEXT,
CareTeam_Prd_Strt TEXT,
CareTeam_RsnCd_Cdg_Cd TEXT,
CareTeam_RsnCd_Cdg_Dsply TEXT,
CareTeam_RsnCd_Cdg_Sys TEXT,
CareTeam_RsnCd_Cdg_UsrSltd TEXT,
CareTeam_RsnCd_Cdg_Vrsn TEXT,
CareTeam_RsnCd_Txt TEXT,
CareTeam_RsnRfrnc TEXT,
CareTeam_Sts TEXT,
CareTeam_Sbjct TEXT,
CareTeam_Tlcm_Prd_End TEXT,
CareTeam_Tlcm_Prd_Strt TEXT,
CareTeam_Tlcm_Rnk TEXT,
CareTeam_Tlcm_Sys TEXT,
CareTeam_Tlcm_Use TEXT,
CareTeam_Tlcm_Vl TEXT,
PRIMARY KEY(id)) ENGINE=MyISAM
    ROW_FORMAT=COMPRESSED 
    KEY_BLOCK_SIZE=8;