drop table if exists `DocumentManifest`;
CREATE TABLE `DocumentManifest` (
 id varchar(64),
DocManifest_Athr TEXT,
DocManifest_Cntnt TEXT,
DocManifest_Created TEXT,
DocManifest_Dscrptn TEXT,
DocManifest_Id_Assigner TEXT,
DocManifest_Id_Prd_End TEXT,
DocManifest_Id_Prd_Strt TEXT,
DocManifest_Id_Sys TEXT,
DocManifest_Id_Typ_Cdg_Cd TEXT,
DocManifest_Id_Typ_Cdg_Dsply TEXT,
DocManifest_Id_Typ_Cdg_Sys TEXT,
DocManifest_Id_Typ_Cdg_UsrSltd TEXT,
DocManifest_Id_Typ_Cdg_Vrsn TEXT,
DocManifest_Id_Typ_Txt TEXT,
DocManifest_Id_Use TEXT,
DocManifest_Id_Vl TEXT,
DocManifest_MasterId_Assigner TEXT,
DocManifest_MasterId_Prd_End TEXT,
DocManifest_MasterId_Prd_Strt TEXT,
DocManifest_MasterId_Sys TEXT,
DocManifest_MasterId_Typ_Cdg_Cd TEXT,
DocManifest_MasterId_Typ_Cdg_Dsply TEXT,
DocManifest_MasterId_Typ_Cdg_Sys TEXT,
DocManifest_MasterId_Typ_Cdg_UsrSltd TEXT,
DocManifest_MasterId_Typ_Cdg_Vrsn TEXT,
DocManifest_MasterId_Typ_Txt TEXT,
DocManifest_MasterId_Use TEXT,
DocManifest_MasterId_Vl TEXT,
DocManifest_Recipient TEXT,
DocManifest_Rlted_Id_Assigner TEXT,
DocManifest_Rlted_Id_Prd_End TEXT,
DocManifest_Rlted_Id_Prd_Strt TEXT,
DocManifest_Rlted_Id_Sys TEXT,
DocManifest_Rlted_Id_Typ_Cdg_Cd TEXT,
DocManifest_Rlted_Id_Typ_Cdg_Dsply TEXT,
DocManifest_Rlted_Id_Typ_Cdg_Sys TEXT,
DocManifest_Rlted_Id_Typ_Cdg_UsrSltd TEXT,
DocManifest_Rlted_Id_Typ_Cdg_Vrsn TEXT,
DocManifest_Rlted_Id_Typ_Txt TEXT,
DocManifest_Rlted_Id_Use TEXT,
DocManifest_Rlted_Id_Vl TEXT,
DocManifest_Rlted_Ref TEXT,
DocManifest_Src TEXT,
DocManifest_Sts TEXT,
DocManifest_Sbjct TEXT,
DocManifest_Typ_Cdg_Cd TEXT,
DocManifest_Typ_Cdg_Dsply TEXT,
DocManifest_Typ_Cdg_Sys TEXT,
DocManifest_Typ_Cdg_UsrSltd TEXT,
DocManifest_Typ_Cdg_Vrsn TEXT,
DocManifest_Typ_Txt TEXT,
PRIMARY KEY(id)) ENGINE=MyISAM
    ROW_FORMAT=COMPRESSED 
    KEY_BLOCK_SIZE=8;