drop table if exists `EpisodeOfCare`;
CREATE TABLE `EpisodeOfCare` (
 id varchar(64),
EpisodeOfCare_Account TEXT,
EpisodeOfCare_CareManager TEXT,
EpisodeOfCare_Dgnsis_Cndtn TEXT,
EpisodeOfCare_Dgnsis_Rnk TEXT,
EpisodeOfCare_Dgnsis_Role_Cdg_Cd TEXT,
EpisodeOfCare_Dgnsis_Role_Cdg_Dsply TEXT,
EpisodeOfCare_Dgnsis_Role_Cdg_Sys TEXT,
EpisodeOfCare_Dgnsis_Role_Cdg_UsrSltd TEXT,
EpisodeOfCare_Dgnsis_Role_Cdg_Vrsn TEXT,
EpisodeOfCare_Dgnsis_Role_Txt TEXT,
EpisodeOfCare_Id_Assigner TEXT,
EpisodeOfCare_Id_Prd_End TEXT,
EpisodeOfCare_Id_Prd_Strt TEXT,
EpisodeOfCare_Id_Sys TEXT,
EpisodeOfCare_Id_Typ_Cdg_Cd TEXT,
EpisodeOfCare_Id_Typ_Cdg_Dsply TEXT,
EpisodeOfCare_Id_Typ_Cdg_Sys TEXT,
EpisodeOfCare_Id_Typ_Cdg_UsrSltd TEXT,
EpisodeOfCare_Id_Typ_Cdg_Vrsn TEXT,
EpisodeOfCare_Id_Typ_Txt TEXT,
EpisodeOfCare_Id_Use TEXT,
EpisodeOfCare_Id_Vl TEXT,
EpisodeOfCare_ManagingOrgnztn TEXT,
EpisodeOfCare_Pnt TEXT,
EpisodeOfCare_Prd_End TEXT,
EpisodeOfCare_Prd_Strt TEXT,
EpisodeOfCare_ReferralRqst TEXT,
EpisodeOfCare_Sts TEXT,
EpisodeOfCare_StsHis_Prd_End TEXT,
EpisodeOfCare_StsHis_Prd_Strt TEXT,
EpisodeOfCare_StsHis_Sts TEXT,
EpisodeOfCare_Team TEXT,
EpisodeOfCare_Typ_Cdg_Cd TEXT,
EpisodeOfCare_Typ_Cdg_Dsply TEXT,
EpisodeOfCare_Typ_Cdg_Sys TEXT,
EpisodeOfCare_Typ_Cdg_UsrSltd TEXT,
EpisodeOfCare_Typ_Cdg_Vrsn TEXT,
EpisodeOfCare_Typ_Txt TEXT,
PRIMARY KEY(id)) ENGINE=MyISAM
    ROW_FORMAT=COMPRESSED 
    KEY_BLOCK_SIZE=8;