drop table if exists `Flag`;
CREATE TABLE `Flag` (
 id varchar(64),
Flag_Athr TEXT,
Flag_Ctgry_Cdg_Cd TEXT,
Flag_Ctgry_Cdg_Dsply TEXT,
Flag_Ctgry_Cdg_Sys TEXT,
Flag_Ctgry_Cdg_UsrSltd TEXT,
Flag_Ctgry_Cdg_Vrsn TEXT,
Flag_Ctgry_Txt TEXT,
Flag_Cd_Cdg_Cd TEXT,
Flag_Cd_Cdg_Dsply TEXT,
Flag_Cd_Cdg_Sys TEXT,
Flag_Cd_Cdg_UsrSltd TEXT,
Flag_Cd_Cdg_Vrsn TEXT,
Flag_Cd_Txt TEXT,
Flag_Enc TEXT,
Flag_Id_Assigner TEXT,
Flag_Id_Prd_End TEXT,
Flag_Id_Prd_Strt TEXT,
Flag_Id_Sys TEXT,
Flag_Id_Typ_Cdg_Cd TEXT,
Flag_Id_Typ_Cdg_Dsply TEXT,
Flag_Id_Typ_Cdg_Sys TEXT,
Flag_Id_Typ_Cdg_UsrSltd TEXT,
Flag_Id_Typ_Cdg_Vrsn TEXT,
Flag_Id_Typ_Txt TEXT,
Flag_Id_Use TEXT,
Flag_Id_Vl TEXT,
Flag_Prd_End TEXT,
Flag_Prd_Strt TEXT,
Flag_Sts TEXT,
Flag_Sbjct TEXT,
PRIMARY KEY(id)) ENGINE=MyISAM
    ROW_FORMAT=COMPRESSED 
    KEY_BLOCK_SIZE=8;