drop table if exists `Schedule`;
CREATE TABLE `Schedule` (
 id varchar(64),
Schdl_Active TEXT,
Schdl_Actor TEXT,
Schdl_Comment TEXT,
Schdl_Id_Assigner TEXT,
Schdl_Id_Prd_End TEXT,
Schdl_Id_Prd_Strt TEXT,
Schdl_Id_Sys TEXT,
Schdl_Id_Typ_Cdg_Cd TEXT,
Schdl_Id_Typ_Cdg_Dsply TEXT,
Schdl_Id_Typ_Cdg_Sys TEXT,
Schdl_Id_Typ_Cdg_UsrSltd TEXT,
Schdl_Id_Typ_Cdg_Vrsn TEXT,
Schdl_Id_Typ_Txt TEXT,
Schdl_Id_Use TEXT,
Schdl_Id_Vl TEXT,
Schdl_PlnningHorizon_End TEXT,
Schdl_PlnningHorizon_Strt TEXT,
Schdl_SrvCtgry_Cdg_Cd TEXT,
Schdl_SrvCtgry_Cdg_Dsply TEXT,
Schdl_SrvCtgry_Cdg_Sys TEXT,
Schdl_SrvCtgry_Cdg_UsrSltd TEXT,
Schdl_SrvCtgry_Cdg_Vrsn TEXT,
Schdl_SrvCtgry_Txt TEXT,
Schdl_SrvTyp_Cdg_Cd TEXT,
Schdl_SrvTyp_Cdg_Dsply TEXT,
Schdl_SrvTyp_Cdg_Sys TEXT,
Schdl_SrvTyp_Cdg_UsrSltd TEXT,
Schdl_SrvTyp_Cdg_Vrsn TEXT,
Schdl_SrvTyp_Txt TEXT,
Schdl_Spclty_Cdg_Cd TEXT,
Schdl_Spclty_Cdg_Dsply TEXT,
Schdl_Spclty_Cdg_Sys TEXT,
Schdl_Spclty_Cdg_UsrSltd TEXT,
Schdl_Spclty_Cdg_Vrsn TEXT,
Schdl_Spclty_Txt TEXT,
PRIMARY KEY(id)) ENGINE=MyISAM
    ROW_FORMAT=COMPRESSED 
    KEY_BLOCK_SIZE=8;