drop table if exists `TestReport`;
CREATE TABLE `TestReport` (
 id varchar(64),
TstRpt_Id_Assigner TEXT,
TstRpt_Id_Prd_End TEXT,
TstRpt_Id_Prd_Strt TEXT,
TstRpt_Id_Sys TEXT,
TstRpt_Id_Typ_Cdg_Cd TEXT,
TstRpt_Id_Typ_Cdg_Dsply TEXT,
TstRpt_Id_Typ_Cdg_Sys TEXT,
TstRpt_Id_Typ_Cdg_UsrSltd TEXT,
TstRpt_Id_Typ_Cdg_Vrsn TEXT,
TstRpt_Id_Typ_Txt TEXT,
TstRpt_Id_Use TEXT,
TstRpt_Id_Vl TEXT,
TstRpt_Issued TEXT,
TstRpt_Nm TEXT,
TstRpt_Prtcpnt_Dsply TEXT,
TstRpt_Prtcpnt_Typ TEXT,
TstRpt_Prtcpnt_Uri TEXT,
TstRpt_Rslt TEXT,
TstRpt_Score TEXT,
TstRpt_Stup_Actn_Assert_Dtl TEXT,
TstRpt_Stup_Actn_Assert_Msg TEXT,
TstRpt_Stup_Actn_Assert_Rslt TEXT,
TstRpt_Stup_Actn_Oprtn_Dtl TEXT,
TstRpt_Stup_Actn_Oprtn_Msg TEXT,
TstRpt_Stup_Actn_Oprtn_Rslt TEXT,
TstRpt_Sts TEXT,
TstRpt_Teardown_Actn_Oprtn_Dtl TEXT,
TstRpt_Teardown_Actn_Oprtn_Msg TEXT,
TstRpt_Teardown_Actn_Oprtn_Rslt TEXT,
TstRpt_Tst_Actn_Assert_Dtl TEXT,
TstRpt_Tst_Actn_Assert_Msg TEXT,
TstRpt_Tst_Actn_Assert_Rslt TEXT,
TstRpt_Tst_Actn_Oprtn_Dtl TEXT,
TstRpt_Tst_Actn_Oprtn_Msg TEXT,
TstRpt_Tst_Actn_Oprtn_Rslt TEXT,
TstRpt_Tst_Dscrptn TEXT,
TstRpt_Tst_Nm TEXT,
TstRpt_TstScrpt TEXT,
TstRpt_Tster TEXT,
PRIMARY KEY(id)) ENGINE=MyISAM
    ROW_FORMAT=COMPRESSED 
    KEY_BLOCK_SIZE=8;