package main.templateoutput.Conversions;
// Generated on Jan 28, 2022, 8:02:40 AM 


import org.hl7.fhir.r4.model.Patient;

/**
 *  object for conversion model class Activitydefinition.
 * @see .Activitydefinition
 * @author Paul Kovach
 */
import main.java.com.campfhir.service.conversion.HapiFHIRHelpers;

public class ActivitydefinitionConversion 
{
	public Patient Activitydefinitions(main.templateoutput.Model.Activitydefinition activitydefinition) 
	{
			Patient  Activitydefinitionobj = new Patient(); 

						Activitydefinitionobj.setUrl(HapiFHIRHelpers.createuri(activitydefinition.getActivityDefinitionUrlUri() /** { "tree" :"ActivityDefinition.url", "datatype" : "uri", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setUrl"} **/
						));
Activitydefinitionobj.addIdentifier(HapiFHIRHelpers.createIdentifier(activitydefinition.getActvtDfntnDntfrDntfrSe() /** { "tree" :"ActivityDefinition.identifier", "datatype" : "Identifier, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setUse"} **/
						, activitydefinition.getActvtDfntnDntfrDntfrTpCcCSstm() /** { "tree" :"ActivityDefinition.identifier", "datatype" : "Identifier, CodeableConcept, Coding, uri", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setType, addCoding, setSystem"} **/
						, activitydefinition.getActvtDfntnDntfrDntfrTpCcCVrsn() /** { "tree" :"ActivityDefinition.identifier", "datatype" : "Identifier, CodeableConcept, Coding, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setType, addCoding, setVersion"} **/
						, activitydefinition.getActvtDfntnDntfrDntfrTpCcCCde() /** { "tree" :"ActivityDefinition.identifier", "datatype" : "Identifier, CodeableConcept, Coding, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setType, addCoding, setCode"} **/
						, activitydefinition.getActvtDfntnDntfrDntfrTpCcCDsplay() /** { "tree" :"ActivityDefinition.identifier", "datatype" : "Identifier, CodeableConcept, Coding, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setType, addCoding, setDisplay"} **/
						, activitydefinition.getActvtDfntnDntfrDntfrTpCcCSrSlctd() /** { "tree" :"ActivityDefinition.identifier", "datatype" : "Identifier, CodeableConcept, Coding, boolean", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setType, addCoding, setUserSelected"} **/
						, activitydefinition.getActvtDfntnDntfrDntfrTpCcTxt() /** { "tree" :"ActivityDefinition.identifier", "datatype" : "Identifier, CodeableConcept, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setType, setText"} **/
						, activitydefinition.getActvtDfntnDntfrDntfrPrdPrdStrt() /** { "tree" :"ActivityDefinition.identifier", "datatype" : "Identifier, Period, dateTime", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setPeriod, setStart"} **/
						, activitydefinition.getActvtDfntnDntfrDntfrPrdPrdNd() /** { "tree" :"ActivityDefinition.identifier", "datatype" : "Identifier, Period, dateTime", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setPeriod, setEnd"} **/
						, activitydefinition.getActvtDfntnDntfrDntfrSsgnr() /** { "tree" :"ActivityDefinition.identifier", "datatype" : "Identifier, Reference", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setAssigner"} **/
						, activitydefinition.getActvtDfntnDntfrDntfrVlue() /** { "tree" :"ActivityDefinition.identifier", "datatype" : "Identifier, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setValue"} **/
						, activitydefinition.getActvtDfntnDntfrDntfrSstm() /** { "tree" :"ActivityDefinition.identifier", "datatype" : "Identifier, uri", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setSystem"} **/
						));
Activitydefinitionobj.setVersion(HapiFHIRHelpers.createstring(activitydefinition.getActivityDefinitionVersionString() /** { "tree" :"ActivityDefinition.version", "datatype" : "string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setVersion"} **/
						));
Activitydefinitionobj.setName(HapiFHIRHelpers.createstring(activitydefinition.getActivityDefinitionNameString() /** { "tree" :"ActivityDefinition.name", "datatype" : "string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setName"} **/
						));
Activitydefinitionobj.setTitle(HapiFHIRHelpers.createstring(activitydefinition.getActivityDefinitionTitleString() /** { "tree" :"ActivityDefinition.title", "datatype" : "string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setTitle"} **/
						));
Activitydefinitionobj.setSubtitle(HapiFHIRHelpers.createstring(activitydefinition.getActivityDefinitionSubtitleString() /** { "tree" :"ActivityDefinition.subtitle", "datatype" : "string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setSubtitle"} **/
						));
Activitydefinitionobj.setStatus(HapiFHIRHelpers.createcode(activitydefinition.getActivityDefinitionStatusCode() /** { "tree" :"ActivityDefinition.status", "datatype" : "code", "cardinality" : "Required", "elementtree" : [] , "methodName" : "setStatus"} **/
						));
Activitydefinitionobj.setExperimental(HapiFHIRHelpers.createboolean(activitydefinition.getActvtDfntnXprmntlBln() /** { "tree" :"ActivityDefinition.experimental", "datatype" : "boolean", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setExperimental"} **/
						));
Activitydefinitionobj.setSubjectCodeableconcept(HapiFHIRHelpers.createCodeableConcept(activitydefinition.getActvtDfntnSbjctCdblcncptCcCdngCSstm() /** { "tree" :"ActivityDefinition.subjectCodeableconcept", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setSubjectCodeableconcept, addCoding, setSystem"} **/
						, activitydefinition.getActvtDfntnSbjctCdblcncptCcCdngCVrsn() /** { "tree" :"ActivityDefinition.subjectCodeableconcept", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setSubjectCodeableconcept, addCoding, setVersion"} **/
						, activitydefinition.getActvtDfntnSbjctCdblcncptCcCdngCCde() /** { "tree" :"ActivityDefinition.subjectCodeableconcept", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setSubjectCodeableconcept, addCoding, setCode"} **/
						, activitydefinition.getActvtDfntnSbjctCdblcncptCcCdngCDsplay() /** { "tree" :"ActivityDefinition.subjectCodeableconcept", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setSubjectCodeableconcept, addCoding, setDisplay"} **/
						, activitydefinition.getActvtDfntnSbjctCdblcncptCcCdngCSrSlctd() /** { "tree" :"ActivityDefinition.subjectCodeableconcept", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setSubjectCodeableconcept, addCoding, setUserSelected"} **/
						, activitydefinition.getActvtDfntnSbjctCdblcncptCcTxt() /** { "tree" :"ActivityDefinition.subjectCodeableconcept", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setSubjectCodeableconcept, setText"} **/
						));
Activitydefinitionobj.setSubjectReference(group)(HapiFHIRHelpers.createReference(activitydefinition.getActvtDfntnSbjctRfrncRfrnce() /** { "tree" :"ActivityDefinition.subjectReference", "datatype" : "Reference", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setSubjectReference(group)"} **/
						));
Activitydefinitionobj.setDate(HapiFHIRHelpers.createdateTime(activitydefinition.getActivityDefinitionDateDateTime() /** { "tree" :"ActivityDefinition.date", "datatype" : "dateTime", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setDate"} **/
						));
Activitydefinitionobj.setPublisher(HapiFHIRHelpers.createstring(activitydefinition.getActvtDfntnPblshrStrng() /** { "tree" :"ActivityDefinition.publisher", "datatype" : "string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setPublisher"} **/
						));
Activitydefinitionobj.addContact(HapiFHIRHelpers.createContactDetail(activitydefinition.getActvtDfntnCntctCntctDtlTlcmCntctPntPrdStrt() /** { "tree" :"ActivityDefinition.contact", "datatype" : "ContactDetail, ContactPoint, Period, dateTime", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addContact, setTelecom, setPeriod, setStart"} **/
						, activitydefinition.getActvtDfntnCntctCntctDtlTlcmCntctPntPrdNd() /** { "tree" :"ActivityDefinition.contact", "datatype" : "ContactDetail, ContactPoint, Period, dateTime", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addContact, setTelecom, setPeriod, setEnd"} **/
						, activitydefinition.getActvtDfntnCntctCntctDtlTlcmCntctPntSstm() /** { "tree" :"ActivityDefinition.contact", "datatype" : "ContactDetail, ContactPoint, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addContact, setTelecom, setSystem"} **/
						, activitydefinition.getActvtDfntnCntctCntctDtlTlcmCntctPntVlue() /** { "tree" :"ActivityDefinition.contact", "datatype" : "ContactDetail, ContactPoint, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addContact, setTelecom, setValue"} **/
						, activitydefinition.getActvtDfntnCntctCntctDtlTlcmCntctPntSe() /** { "tree" :"ActivityDefinition.contact", "datatype" : "ContactDetail, ContactPoint, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addContact, setTelecom, setUse"} **/
						, activitydefinition.getActvtDfntnCntctCntctDtlTlcmCntctPntRnk() /** { "tree" :"ActivityDefinition.contact", "datatype" : "ContactDetail, ContactPoint, positiveInt", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addContact, setTelecom, setRank"} **/
						, activitydefinition.getActvtDfntnCntctCntctDtlNme() /** { "tree" :"ActivityDefinition.contact", "datatype" : "ContactDetail, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addContact, addName"} **/
						));
Activitydefinitionobj.setDescription(HapiFHIRHelpers.createmarkdown(activitydefinition.getActvtDfntnDscrptnMrkdwn() /** { "tree" :"ActivityDefinition.description", "datatype" : "markdown", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setDescription"} **/
						));
Activitydefinitionobj.addUseContext(HapiFHIRHelpers.createUsageContext(activitydefinition.getActvtDfntnSCntxtSgCntxtVlCcCcCSstm() /** { "tree" :"ActivityDefinition.useContext", "datatype" : "UsageContext, CodeableConcept, Coding, uri", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addUseContext, addValueCodeableConcept, addCoding, setSystem"} **/
						, activitydefinition.getActvtDfntnSCntxtSgCntxtVlCcCcCVrsn() /** { "tree" :"ActivityDefinition.useContext", "datatype" : "UsageContext, CodeableConcept, Coding, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addUseContext, addValueCodeableConcept, addCoding, setVersion"} **/
						, activitydefinition.getActvtDfntnSCntxtSgCntxtVlCcCcCCde() /** { "tree" :"ActivityDefinition.useContext", "datatype" : "UsageContext, CodeableConcept, Coding, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addUseContext, addValueCodeableConcept, addCoding, setCode"} **/
						, activitydefinition.getActvtDfntnSCntxtSgCntxtVlCcCcCDsplay() /** { "tree" :"ActivityDefinition.useContext", "datatype" : "UsageContext, CodeableConcept, Coding, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addUseContext, addValueCodeableConcept, addCoding, setDisplay"} **/
						, activitydefinition.getActvtDfntnSCntxtSgCntxtVlCcCcCSrSlctd() /** { "tree" :"ActivityDefinition.useContext", "datatype" : "UsageContext, CodeableConcept, Coding, boolean", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addUseContext, addValueCodeableConcept, addCoding, setUserSelected"} **/
						, activitydefinition.getActvtDfntnSCntxtSgCntxtVlCcCcTxt() /** { "tree" :"ActivityDefinition.useContext", "datatype" : "UsageContext, CodeableConcept, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addUseContext, addValueCodeableConcept, setText"} **/
						, activitydefinition.getActvtDfntnSCntxtSgCntxtCdCSstm() /** { "tree" :"ActivityDefinition.useContext", "datatype" : "UsageContext, Coding, uri", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addUseContext, addCode, setSystem"} **/
						, activitydefinition.getActvtDfntnSCntxtSgCntxtCdCVrsn() /** { "tree" :"ActivityDefinition.useContext", "datatype" : "UsageContext, Coding, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addUseContext, addCode, setVersion"} **/
						, activitydefinition.getActvtDfntnSCntxtSgCntxtCdCCde() /** { "tree" :"ActivityDefinition.useContext", "datatype" : "UsageContext, Coding, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addUseContext, addCode, setCode"} **/
						, activitydefinition.getActvtDfntnSCntxtSgCntxtCdCDsplay() /** { "tree" :"ActivityDefinition.useContext", "datatype" : "UsageContext, Coding, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addUseContext, addCode, setDisplay"} **/
						, activitydefinition.getActvtDfntnSCntxtSgCntxtCdCSrSlctd() /** { "tree" :"ActivityDefinition.useContext", "datatype" : "UsageContext, Coding, boolean", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addUseContext, addCode, setUserSelected"} **/
						, activitydefinition.getActvtDfntnSCntxtSgCntxtVlQnttQnttVlue() /** { "tree" :"ActivityDefinition.useContext", "datatype" : "UsageContext, Quantity, decimal", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addUseContext, addValueQuantity, setValue"} **/
						, activitydefinition.getActvtDfntnSCntxtSgCntxtVlQnttQnttCmprtr() /** { "tree" :"ActivityDefinition.useContext", "datatype" : "UsageContext, Quantity, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addUseContext, addValueQuantity, setComparator"} **/
						, activitydefinition.getActvtDfntnSCntxtSgCntxtVlQnttQnttNt() /** { "tree" :"ActivityDefinition.useContext", "datatype" : "UsageContext, Quantity, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addUseContext, addValueQuantity, setUnit"} **/
						, activitydefinition.getActvtDfntnSCntxtSgCntxtVlQnttQnttSstm() /** { "tree" :"ActivityDefinition.useContext", "datatype" : "UsageContext, Quantity, uri", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addUseContext, addValueQuantity, setSystem"} **/
						, activitydefinition.getActvtDfntnSCntxtSgCntxtVlQnttQnttCde() /** { "tree" :"ActivityDefinition.useContext", "datatype" : "UsageContext, Quantity, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addUseContext, addValueQuantity, setCode"} **/
						, activitydefinition.getActvtDfntnSCntxtSgCntxtVlRngRngLw() /** { "tree" :"ActivityDefinition.useContext", "datatype" : "UsageContext, Range, SimpleQuantity", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addUseContext, addValueRange, setLow"} **/
						, activitydefinition.getActvtDfntnSCntxtSgCntxtVlRngRngHgh() /** { "tree" :"ActivityDefinition.useContext", "datatype" : "UsageContext, Range, SimpleQuantity", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addUseContext, addValueRange, setHigh"} **/
						, activitydefinition.getActvtDfntnSCntxtSgCntxtVlRfrnce() /** { "tree" :"ActivityDefinition.useContext", "datatype" : "UsageContext, Reference", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addUseContext, addValueReference"} **/
						));
Activitydefinitionobj.addJurisdiction(HapiFHIRHelpers.createCodeableConcept(activitydefinition.getActvtDfntnJrsdctnCcCdngCSstm() /** { "tree" :"ActivityDefinition.jurisdiction", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addJurisdiction, addCoding, setSystem"} **/
						, activitydefinition.getActvtDfntnJrsdctnCcCdngCVrsn() /** { "tree" :"ActivityDefinition.jurisdiction", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addJurisdiction, addCoding, setVersion"} **/
						, activitydefinition.getActvtDfntnJrsdctnCcCdngCCde() /** { "tree" :"ActivityDefinition.jurisdiction", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addJurisdiction, addCoding, setCode"} **/
						, activitydefinition.getActvtDfntnJrsdctnCcCdngCDsplay() /** { "tree" :"ActivityDefinition.jurisdiction", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addJurisdiction, addCoding, setDisplay"} **/
						, activitydefinition.getActvtDfntnJrsdctnCcCdngCSrSlctd() /** { "tree" :"ActivityDefinition.jurisdiction", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addJurisdiction, addCoding, setUserSelected"} **/
						, activitydefinition.getActvtDfntnJrsdctnCcTxt() /** { "tree" :"ActivityDefinition.jurisdiction", "datatype" : "CodeableConcept, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addJurisdiction, setText"} **/
						));
Activitydefinitionobj.setPurpose(HapiFHIRHelpers.createmarkdown(activitydefinition.getActvtDfntnPrpsMrkdwn() /** { "tree" :"ActivityDefinition.purpose", "datatype" : "markdown", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setPurpose"} **/
						));
Activitydefinitionobj.setUsage(HapiFHIRHelpers.createstring(activitydefinition.getActivityDefinitionUsageString() /** { "tree" :"ActivityDefinition.usage", "datatype" : "string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setUsage"} **/
						));
Activitydefinitionobj.setCopyright(HapiFHIRHelpers.createmarkdown(activitydefinition.getActvtDfntnCprghtMrkdwn() /** { "tree" :"ActivityDefinition.copyright", "datatype" : "markdown", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setCopyright"} **/
						));
Activitydefinitionobj.setApprovalDate(HapiFHIRHelpers.createdate(activitydefinition.getActvtDfntnPprvlDtDte() /** { "tree" :"ActivityDefinition.approvalDate", "datatype" : "date", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setApprovalDate"} **/
						));
Activitydefinitionobj.setLastReviewDate(HapiFHIRHelpers.createdate(activitydefinition.getActvtDfntnLstRvwDtDte() /** { "tree" :"ActivityDefinition.lastReviewDate", "datatype" : "date", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setLastReviewDate"} **/
						));
Activitydefinitionobj.setEffectivePeriod(HapiFHIRHelpers.createPeriod(activitydefinition.getActvtDfntnFfctvPrdPrdStrt() /** { "tree" :"ActivityDefinition.effectivePeriod", "datatype" : "Period, dateTime", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setEffectivePeriod, setStart"} **/
						, activitydefinition.getActvtDfntnFfctvPrdPrdNd() /** { "tree" :"ActivityDefinition.effectivePeriod", "datatype" : "Period, dateTime", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setEffectivePeriod, setEnd"} **/
						));
Activitydefinitionobj.addTopic(HapiFHIRHelpers.createCodeableConcept(activitydefinition.getActvtDfntnTpcCcCdngCSstm() /** { "tree" :"ActivityDefinition.topic", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addTopic, addCoding, setSystem"} **/
						, activitydefinition.getActvtDfntnTpcCcCdngCVrsn() /** { "tree" :"ActivityDefinition.topic", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addTopic, addCoding, setVersion"} **/
						, activitydefinition.getActvtDfntnTpcCcCdngCCde() /** { "tree" :"ActivityDefinition.topic", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addTopic, addCoding, setCode"} **/
						, activitydefinition.getActvtDfntnTpcCcCdngCDsplay() /** { "tree" :"ActivityDefinition.topic", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addTopic, addCoding, setDisplay"} **/
						, activitydefinition.getActvtDfntnTpcCcCdngCSrSlctd() /** { "tree" :"ActivityDefinition.topic", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addTopic, addCoding, setUserSelected"} **/
						, activitydefinition.getActivityDefinitionTopicCcText() /** { "tree" :"ActivityDefinition.topic", "datatype" : "CodeableConcept, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addTopic, setText"} **/
						));
Activitydefinitionobj.addAuthor(HapiFHIRHelpers.createContactDetail(activitydefinition.getActvtDfntnThrCntctDtlTlcmCntctPntPrdStrt() /** { "tree" :"ActivityDefinition.author", "datatype" : "ContactDetail, ContactPoint, Period, dateTime", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addAuthor, setTelecom, setPeriod, setStart"} **/
						, activitydefinition.getActvtDfntnThrCntctDtlTlcmCntctPntPrdNd() /** { "tree" :"ActivityDefinition.author", "datatype" : "ContactDetail, ContactPoint, Period, dateTime", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addAuthor, setTelecom, setPeriod, setEnd"} **/
						, activitydefinition.getActvtDfntnThrCntctDtlTlcmCntctPntSstm() /** { "tree" :"ActivityDefinition.author", "datatype" : "ContactDetail, ContactPoint, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addAuthor, setTelecom, setSystem"} **/
						, activitydefinition.getActvtDfntnThrCntctDtlTlcmCntctPntVlue() /** { "tree" :"ActivityDefinition.author", "datatype" : "ContactDetail, ContactPoint, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addAuthor, setTelecom, setValue"} **/
						, activitydefinition.getActvtDfntnThrCntctDtlTlcmCntctPntSe() /** { "tree" :"ActivityDefinition.author", "datatype" : "ContactDetail, ContactPoint, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addAuthor, setTelecom, setUse"} **/
						, activitydefinition.getActvtDfntnThrCntctDtlTlcmCntctPntRnk() /** { "tree" :"ActivityDefinition.author", "datatype" : "ContactDetail, ContactPoint, positiveInt", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addAuthor, setTelecom, setRank"} **/
						, activitydefinition.getActvtDfntnThrCntctDtlNme() /** { "tree" :"ActivityDefinition.author", "datatype" : "ContactDetail, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addAuthor, addName"} **/
						));
Activitydefinitionobj.addEditor(HapiFHIRHelpers.createContactDetail(activitydefinition.getActvtDfntnDtrCntctDtlTlcmCntctPntPrdStrt() /** { "tree" :"ActivityDefinition.editor", "datatype" : "ContactDetail, ContactPoint, Period, dateTime", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addEditor, setTelecom, setPeriod, setStart"} **/
						, activitydefinition.getActvtDfntnDtrCntctDtlTlcmCntctPntPrdNd() /** { "tree" :"ActivityDefinition.editor", "datatype" : "ContactDetail, ContactPoint, Period, dateTime", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addEditor, setTelecom, setPeriod, setEnd"} **/
						, activitydefinition.getActvtDfntnDtrCntctDtlTlcmCntctPntSstm() /** { "tree" :"ActivityDefinition.editor", "datatype" : "ContactDetail, ContactPoint, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addEditor, setTelecom, setSystem"} **/
						, activitydefinition.getActvtDfntnDtrCntctDtlTlcmCntctPntVlue() /** { "tree" :"ActivityDefinition.editor", "datatype" : "ContactDetail, ContactPoint, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addEditor, setTelecom, setValue"} **/
						, activitydefinition.getActvtDfntnDtrCntctDtlTlcmCntctPntSe() /** { "tree" :"ActivityDefinition.editor", "datatype" : "ContactDetail, ContactPoint, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addEditor, setTelecom, setUse"} **/
						, activitydefinition.getActvtDfntnDtrCntctDtlTlcmCntctPntRnk() /** { "tree" :"ActivityDefinition.editor", "datatype" : "ContactDetail, ContactPoint, positiveInt", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addEditor, setTelecom, setRank"} **/
						, activitydefinition.getActvtDfntnDtrCntctDtlNme() /** { "tree" :"ActivityDefinition.editor", "datatype" : "ContactDetail, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addEditor, addName"} **/
						));
Activitydefinitionobj.addReviewer(HapiFHIRHelpers.createContactDetail(activitydefinition.getActvtDfntnRvwrCntctDtlTlcmCntctPntPrdStrt() /** { "tree" :"ActivityDefinition.reviewer", "datatype" : "ContactDetail, ContactPoint, Period, dateTime", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addReviewer, setTelecom, setPeriod, setStart"} **/
						, activitydefinition.getActvtDfntnRvwrCntctDtlTlcmCntctPntPrdNd() /** { "tree" :"ActivityDefinition.reviewer", "datatype" : "ContactDetail, ContactPoint, Period, dateTime", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addReviewer, setTelecom, setPeriod, setEnd"} **/
						, activitydefinition.getActvtDfntnRvwrCntctDtlTlcmCntctPntSstm() /** { "tree" :"ActivityDefinition.reviewer", "datatype" : "ContactDetail, ContactPoint, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addReviewer, setTelecom, setSystem"} **/
						, activitydefinition.getActvtDfntnRvwrCntctDtlTlcmCntctPntVlue() /** { "tree" :"ActivityDefinition.reviewer", "datatype" : "ContactDetail, ContactPoint, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addReviewer, setTelecom, setValue"} **/
						, activitydefinition.getActvtDfntnRvwrCntctDtlTlcmCntctPntSe() /** { "tree" :"ActivityDefinition.reviewer", "datatype" : "ContactDetail, ContactPoint, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addReviewer, setTelecom, setUse"} **/
						, activitydefinition.getActvtDfntnRvwrCntctDtlTlcmCntctPntRnk() /** { "tree" :"ActivityDefinition.reviewer", "datatype" : "ContactDetail, ContactPoint, positiveInt", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addReviewer, setTelecom, setRank"} **/
						, activitydefinition.getActvtDfntnRvwrCntctDtlNme() /** { "tree" :"ActivityDefinition.reviewer", "datatype" : "ContactDetail, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addReviewer, addName"} **/
						));
Activitydefinitionobj.addEndorser(HapiFHIRHelpers.createContactDetail(activitydefinition.getActvtDfntnNdrsrCntctDtlTlcmCntctPntPrdStrt() /** { "tree" :"ActivityDefinition.endorser", "datatype" : "ContactDetail, ContactPoint, Period, dateTime", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addEndorser, setTelecom, setPeriod, setStart"} **/
						, activitydefinition.getActvtDfntnNdrsrCntctDtlTlcmCntctPntPrdNd() /** { "tree" :"ActivityDefinition.endorser", "datatype" : "ContactDetail, ContactPoint, Period, dateTime", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addEndorser, setTelecom, setPeriod, setEnd"} **/
						, activitydefinition.getActvtDfntnNdrsrCntctDtlTlcmCntctPntSstm() /** { "tree" :"ActivityDefinition.endorser", "datatype" : "ContactDetail, ContactPoint, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addEndorser, setTelecom, setSystem"} **/
						, activitydefinition.getActvtDfntnNdrsrCntctDtlTlcmCntctPntVlue() /** { "tree" :"ActivityDefinition.endorser", "datatype" : "ContactDetail, ContactPoint, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addEndorser, setTelecom, setValue"} **/
						, activitydefinition.getActvtDfntnNdrsrCntctDtlTlcmCntctPntSe() /** { "tree" :"ActivityDefinition.endorser", "datatype" : "ContactDetail, ContactPoint, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addEndorser, setTelecom, setUse"} **/
						, activitydefinition.getActvtDfntnNdrsrCntctDtlTlcmCntctPntRnk() /** { "tree" :"ActivityDefinition.endorser", "datatype" : "ContactDetail, ContactPoint, positiveInt", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addEndorser, setTelecom, setRank"} **/
						, activitydefinition.getActvtDfntnNdrsrCntctDtlNme() /** { "tree" :"ActivityDefinition.endorser", "datatype" : "ContactDetail, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addEndorser, addName"} **/
						));
Activitydefinitionobj.addRelatedArtifact(HapiFHIRHelpers.createRelatedArtifact(activitydefinition.getActvtDfntnRltdrtfctRltdrtfctDcmntTtchmntCntntTpe() /** { "tree" :"ActivityDefinition.relatedArtifact", "datatype" : "RelatedArtifact, Attachment, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addRelatedArtifact, setDocument, setContentType"} **/
						, activitydefinition.getActvtDfntnRltdrtfctRltdrtfctDcmntTtchmntLngge() /** { "tree" :"ActivityDefinition.relatedArtifact", "datatype" : "RelatedArtifact, Attachment, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addRelatedArtifact, setDocument, setLanguage"} **/
						, activitydefinition.getActvtDfntnRltdrtfctRltdrtfctDcmntTtchmntDta() /** { "tree" :"ActivityDefinition.relatedArtifact", "datatype" : "RelatedArtifact, Attachment, base64Binary", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addRelatedArtifact, setDocument, setData"} **/
						, activitydefinition.getActvtDfntnRltdrtfctRltdrtfctDcmntTtchmntRl() /** { "tree" :"ActivityDefinition.relatedArtifact", "datatype" : "RelatedArtifact, Attachment, url", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addRelatedArtifact, setDocument, setUrl"} **/
						, activitydefinition.getActvtDfntnRltdrtfctRltdrtfctDcmntTtchmntSze() /** { "tree" :"ActivityDefinition.relatedArtifact", "datatype" : "RelatedArtifact, Attachment, unsignedInt", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addRelatedArtifact, setDocument, setSize"} **/
						, activitydefinition.getActvtDfntnRltdrtfctRltdrtfctDcmntTtchmntHsh() /** { "tree" :"ActivityDefinition.relatedArtifact", "datatype" : "RelatedArtifact, Attachment, base64Binary", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addRelatedArtifact, setDocument, setHash"} **/
						, activitydefinition.getActvtDfntnRltdrtfctRltdrtfctDcmntTtchmntTtle() /** { "tree" :"ActivityDefinition.relatedArtifact", "datatype" : "RelatedArtifact, Attachment, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addRelatedArtifact, setDocument, setTitle"} **/
						, activitydefinition.getActvtDfntnRltdrtfctRltdrtfctDcmntTtchmntCrtn() /** { "tree" :"ActivityDefinition.relatedArtifact", "datatype" : "RelatedArtifact, Attachment, dateTime", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addRelatedArtifact, setDocument, setCreation"} **/
						, activitydefinition.getActvtDfntnRltdrtfctRltdrtfctRsrce() /** { "tree" :"ActivityDefinition.relatedArtifact", "datatype" : "RelatedArtifact, canonical", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addRelatedArtifact, setResource"} **/
						, activitydefinition.getActvtDfntnRltdrtfctRltdrtfctTpe() /** { "tree" :"ActivityDefinition.relatedArtifact", "datatype" : "RelatedArtifact, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addRelatedArtifact, setType"} **/
						, activitydefinition.getActvtDfntnRltdrtfctRltdrtfctCttn() /** { "tree" :"ActivityDefinition.relatedArtifact", "datatype" : "RelatedArtifact, markdown", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addRelatedArtifact, setCitation"} **/
						, activitydefinition.getActvtDfntnRltdrtfctRltdrtfctLbl() /** { "tree" :"ActivityDefinition.relatedArtifact", "datatype" : "RelatedArtifact, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addRelatedArtifact, setLabel"} **/
						, activitydefinition.getActvtDfntnRltdrtfctRltdrtfctDsplay() /** { "tree" :"ActivityDefinition.relatedArtifact", "datatype" : "RelatedArtifact, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addRelatedArtifact, setDisplay"} **/
						, activitydefinition.getActvtDfntnRltdrtfctRltdrtfctRl() /** { "tree" :"ActivityDefinition.relatedArtifact", "datatype" : "RelatedArtifact, url", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addRelatedArtifact, setUrl"} **/
						));
Activitydefinitionobj.addLibrary(HapiFHIRHelpers.createcanonical(activitydefinition.getActvtDfntnLbrrCnncl() /** { "tree" :"ActivityDefinition.library", "datatype" : "canonical", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addLibrary"} **/
						));
Activitydefinitionobj.setKind(HapiFHIRHelpers.createcode(activitydefinition.getActivityDefinitionKindCode() /** { "tree" :"ActivityDefinition.kind", "datatype" : "code", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setKind"} **/
						));
Activitydefinitionobj.setProfile(HapiFHIRHelpers.createcanonical(activitydefinition.getActvtDfntnPrflCnncl() /** { "tree" :"ActivityDefinition.profile", "datatype" : "canonical", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setProfile"} **/
						));
Activitydefinitionobj.setCode(HapiFHIRHelpers.createCodeableConcept(activitydefinition.getActvtDfntnCdCcCdngCSstm() /** { "tree" :"ActivityDefinition.code", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setCode, addCoding, setSystem"} **/
						, activitydefinition.getActvtDfntnCdCcCdngCVrsn() /** { "tree" :"ActivityDefinition.code", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setCode, addCoding, setVersion"} **/
						, activitydefinition.getActvtDfntnCdCcCdngCCde() /** { "tree" :"ActivityDefinition.code", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setCode, addCoding, setCode"} **/
						, activitydefinition.getActvtDfntnCdCcCdngCDsplay() /** { "tree" :"ActivityDefinition.code", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setCode, addCoding, setDisplay"} **/
						, activitydefinition.getActvtDfntnCdCcCdngCSrSlctd() /** { "tree" :"ActivityDefinition.code", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setCode, addCoding, setUserSelected"} **/
						, activitydefinition.getActivityDefinitionCodeCcText() /** { "tree" :"ActivityDefinition.code", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setCode, setText"} **/
						));
Activitydefinitionobj.setIntent(HapiFHIRHelpers.createcode(activitydefinition.getActivityDefinitionIntentCode() /** { "tree" :"ActivityDefinition.intent", "datatype" : "code", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setIntent"} **/
						));
Activitydefinitionobj.setPriority(HapiFHIRHelpers.createcode(activitydefinition.getActivityDefinitionPriorityCode() /** { "tree" :"ActivityDefinition.priority", "datatype" : "code", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setPriority"} **/
						));
Activitydefinitionobj.setDoNotPerform(HapiFHIRHelpers.createboolean(activitydefinition.getActvtDfntnDNtPrfrmBln() /** { "tree" :"ActivityDefinition.doNotPerform", "datatype" : "boolean", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setDoNotPerform"} **/
						));
Activitydefinitionobj.setTimingTiming(HapiFHIRHelpers.createTiming(activitydefinition.getActvtDfntnTmngTmngTmngCdCcCSstm() /** { "tree" :"ActivityDefinition.timingTiming", "datatype" : "Timing, CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setTimingTiming, setCode, addCoding, setSystem"} **/
						, activitydefinition.getActvtDfntnTmngTmngTmngCdCcCVrsn() /** { "tree" :"ActivityDefinition.timingTiming", "datatype" : "Timing, CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setTimingTiming, setCode, addCoding, setVersion"} **/
						, activitydefinition.getActvtDfntnTmngTmngTmngCdCcCCde() /** { "tree" :"ActivityDefinition.timingTiming", "datatype" : "Timing, CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setTimingTiming, setCode, addCoding, setCode"} **/
						, activitydefinition.getActvtDfntnTmngTmngTmngCdCcCDsplay() /** { "tree" :"ActivityDefinition.timingTiming", "datatype" : "Timing, CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setTimingTiming, setCode, addCoding, setDisplay"} **/
						, activitydefinition.getActvtDfntnTmngTmngTmngCdCcCSrSlctd() /** { "tree" :"ActivityDefinition.timingTiming", "datatype" : "Timing, CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setTimingTiming, setCode, addCoding, setUserSelected"} **/
						, activitydefinition.getActvtDfntnTmngTmngTmngCdCcTxt() /** { "tree" :"ActivityDefinition.timingTiming", "datatype" : "Timing, CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setTimingTiming, setCode, setText"} **/
						, activitydefinition.getActvtDfntnTmngTmngTmngVnt() /** { "tree" :"ActivityDefinition.timingTiming", "datatype" : "Timing, dateTime", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setTimingTiming, addEvent"} **/
						, activitydefinition.getActvtDfntnTmngTmngTmngRptDrtnnt() /** { "tree" :"ActivityDefinition.timingTiming", "datatype" : "Timing, Element, code", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setTimingTiming, setRepeat, setDurationUnit"} **/
						, activitydefinition.getActvtDfntnTmngTmngTmngRptPrdnt() /** { "tree" :"ActivityDefinition.timingTiming", "datatype" : "Timing, Element, code", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setTimingTiming, setRepeat, setPeriodUnit"} **/
						, activitydefinition.getActvtDfntnTmngTmngTmngRptDfWk() /** { "tree" :"ActivityDefinition.timingTiming", "datatype" : "Timing, Element, code", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setTimingTiming, setRepeat, addDayOfWeek"} **/
						, activitydefinition.getActvtDfntnTmngTmngTmngRptWhn() /** { "tree" :"ActivityDefinition.timingTiming", "datatype" : "Timing, Element, code", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setTimingTiming, setRepeat, addWhen"} **/
						, activitydefinition.getActvtDfntnTmngTmngTmngRptDrtn() /** { "tree" :"ActivityDefinition.timingTiming", "datatype" : "Timing, Element, decimal", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setTimingTiming, setRepeat, setDuration"} **/
						, activitydefinition.getActvtDfntnTmngTmngTmngRptDrtnMx() /** { "tree" :"ActivityDefinition.timingTiming", "datatype" : "Timing, Element, decimal", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setTimingTiming, setRepeat, setDurationMax"} **/
						, activitydefinition.getActvtDfntnTmngTmngTmngRptPrd() /** { "tree" :"ActivityDefinition.timingTiming", "datatype" : "Timing, Element, decimal", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setTimingTiming, setRepeat, setPeriod"} **/
						, activitydefinition.getActvtDfntnTmngTmngTmngRptPrdMx() /** { "tree" :"ActivityDefinition.timingTiming", "datatype" : "Timing, Element, decimal", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setTimingTiming, setRepeat, setPeriodMax"} **/
						, activitydefinition.getActvtDfntnTmngTmngTmngRptBndsDrtn() /** { "tree" :"ActivityDefinition.timingTiming", "datatype" : "Timing, Element, Duration", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setTimingTiming, setRepeat, setBoundsDuration"} **/
						, activitydefinition.getActvtDfntnTmngTmngTmngRptBndsPrd() /** { "tree" :"ActivityDefinition.timingTiming", "datatype" : "Timing, Element, Period", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setTimingTiming, setRepeat, setBoundsPeriod"} **/
						, activitydefinition.getActvtDfntnTmngTmngTmngRptCnt() /** { "tree" :"ActivityDefinition.timingTiming", "datatype" : "Timing, Element, positiveInt", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setTimingTiming, setRepeat, setCount"} **/
						, activitydefinition.getActvtDfntnTmngTmngTmngRptCntMx() /** { "tree" :"ActivityDefinition.timingTiming", "datatype" : "Timing, Element, positiveInt", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setTimingTiming, setRepeat, setCountMax"} **/
						, activitydefinition.getActvtDfntnTmngTmngTmngRptFrqncy() /** { "tree" :"ActivityDefinition.timingTiming", "datatype" : "Timing, Element, positiveInt", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setTimingTiming, setRepeat, setFrequency"} **/
						, activitydefinition.getActvtDfntnTmngTmngTmngRptFrqncMx() /** { "tree" :"ActivityDefinition.timingTiming", "datatype" : "Timing, Element, positiveInt", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setTimingTiming, setRepeat, setFrequencyMax"} **/
						, activitydefinition.getActvtDfntnTmngTmngTmngRptBndsRnge() /** { "tree" :"ActivityDefinition.timingTiming", "datatype" : "Timing, Element, Range", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setTimingTiming, setRepeat, setBoundsRange"} **/
						, activitydefinition.getActvtDfntnTmngTmngTmngRptTmfDay() /** { "tree" :"ActivityDefinition.timingTiming", "datatype" : "Timing, Element, time", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setTimingTiming, setRepeat, addTimeOfDay"} **/
						, activitydefinition.getActvtDfntnTmngTmngTmngRptFfst() /** { "tree" :"ActivityDefinition.timingTiming", "datatype" : "Timing, Element, unsignedInt", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setTimingTiming, setRepeat, setOffset"} **/
						));
Activitydefinitionobj.setTiming(HapiFHIRHelpers.createdateTimetype(activitydefinition.getActvtDfntnTmngDttmDtTme() /** { "tree" :"ActivityDefinition.timingDatetime", "datatype" : "dateTime", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setTimingDatetime"} **/
						));
Activitydefinitionobj.setTimingAge(HapiFHIRHelpers.createAge(activitydefinition.getActivityDefinitionTimingAgeAge() /** { "tree" :"ActivityDefinition.timingAge", "datatype" : "Age", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setTimingAge"} **/
						));
Activitydefinitionobj.setTimingPeriod(HapiFHIRHelpers.createPeriod(activitydefinition.getActvtDfntnTmngPrdPrdStrt() /** { "tree" :"ActivityDefinition.timingPeriod", "datatype" : "Period, dateTime", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setTimingPeriod, setStart"} **/
						, activitydefinition.getActvtDfntnTmngPrdPrdNd() /** { "tree" :"ActivityDefinition.timingPeriod", "datatype" : "Period, dateTime", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setTimingPeriod, setEnd"} **/
						));
Activitydefinitionobj.setTimingRange(HapiFHIRHelpers.createRange(activitydefinition.getActvtDfntnTmngRngRngLw() /** { "tree" :"ActivityDefinition.timingRange", "datatype" : "Range, SimpleQuantity", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setTimingRange, setLow"} **/
						, activitydefinition.getActvtDfntnTmngRngRngHgh() /** { "tree" :"ActivityDefinition.timingRange", "datatype" : "Range, SimpleQuantity", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setTimingRange, setHigh"} **/
						));
Activitydefinitionobj.setTimingDuration(HapiFHIRHelpers.createDuration(activitydefinition.getActvtDfntnTmngDrtnDrtn() /** { "tree" :"ActivityDefinition.timingDuration", "datatype" : "Duration", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setTimingDuration"} **/
						));
Activitydefinitionobj.setLocation(HapiFHIRHelpers.createReference(activitydefinition.getActvtDfntnLctnRfrnce() /** { "tree" :"ActivityDefinition.location", "datatype" : "Reference", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setLocation"} **/
						));
Activitydefinitionobj.setType(HapiFHIRHelpers.createcode(activitydefinition.getActvtDfntnPrtcpntTpCde() /** { "tree" :"ActivityDefinition.participant.type", "datatype" : "code", "cardinality" : "Required", "elementtree" : ["addParticipant"] , "methodName" : "setType"} **/
						));
Activitydefinitionobj.setRole(HapiFHIRHelpers.createCodeableConcept(activitydefinition.getActvtDfntnPrtcpntRlCcCdngCSstm() /** { "tree" :"ActivityDefinition.participant.role", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : ["addParticipant"] , "methodName" : "setRole, addCoding, setSystem"} **/
						, activitydefinition.getActvtDfntnPrtcpntRlCcCdngCVrsn() /** { "tree" :"ActivityDefinition.participant.role", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addParticipant"] , "methodName" : "setRole, addCoding, setVersion"} **/
						, activitydefinition.getActvtDfntnPrtcpntRlCcCdngCCde() /** { "tree" :"ActivityDefinition.participant.role", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : ["addParticipant"] , "methodName" : "setRole, addCoding, setCode"} **/
						, activitydefinition.getActvtDfntnPrtcpntRlCcCdngCDsplay() /** { "tree" :"ActivityDefinition.participant.role", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addParticipant"] , "methodName" : "setRole, addCoding, setDisplay"} **/
						, activitydefinition.getActvtDfntnPrtcpntRlCcCdngCSrSlctd() /** { "tree" :"ActivityDefinition.participant.role", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : ["addParticipant"] , "methodName" : "setRole, addCoding, setUserSelected"} **/
						, activitydefinition.getActvtDfntnPrtcpntRlCcTxt() /** { "tree" :"ActivityDefinition.participant.role", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : ["addParticipant"] , "methodName" : "setRole, setText"} **/
						));
Activitydefinitionobj.setProductReference(medication | substance)(HapiFHIRHelpers.createReference(activitydefinition.getActvtDfntnPrdctRfrncRfrnce() /** { "tree" :"ActivityDefinition.productReference", "datatype" : "Reference", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setProductReference(medication | substance)"} **/
						));
Activitydefinitionobj.setProductCodeableconcept(HapiFHIRHelpers.createCodeableConcept(activitydefinition.getActvtDfntnPrdctCdblcncptCcCdngCSstm() /** { "tree" :"ActivityDefinition.productCodeableconcept", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setProductCodeableconcept, addCoding, setSystem"} **/
						, activitydefinition.getActvtDfntnPrdctCdblcncptCcCdngCVrsn() /** { "tree" :"ActivityDefinition.productCodeableconcept", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setProductCodeableconcept, addCoding, setVersion"} **/
						, activitydefinition.getActvtDfntnPrdctCdblcncptCcCdngCCde() /** { "tree" :"ActivityDefinition.productCodeableconcept", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setProductCodeableconcept, addCoding, setCode"} **/
						, activitydefinition.getActvtDfntnPrdctCdblcncptCcCdngCDsplay() /** { "tree" :"ActivityDefinition.productCodeableconcept", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setProductCodeableconcept, addCoding, setDisplay"} **/
						, activitydefinition.getActvtDfntnPrdctCdblcncptCcCdngCSrSlctd() /** { "tree" :"ActivityDefinition.productCodeableconcept", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setProductCodeableconcept, addCoding, setUserSelected"} **/
						, activitydefinition.getActvtDfntnPrdctCdblcncptCcTxt() /** { "tree" :"ActivityDefinition.productCodeableconcept", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setProductCodeableconcept, setText"} **/
						));
Activitydefinitionobj.setQuantity(HapiFHIRHelpers.createSimpleQuantity(activitydefinition.getActvtDfntnQnttSmplQntty() /** { "tree" :"ActivityDefinition.quantity", "datatype" : "SimpleQuantity", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setQuantity"} **/
						));
Activitydefinitionobj.addDosage(HapiFHIRHelpers.createDosage(activitydefinition.getActivityDefinitionDosageDosage() /** { "tree" :"ActivityDefinition.dosage", "datatype" : "Dosage", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addDosage"} **/
						));
Activitydefinitionobj.addBodySite(HapiFHIRHelpers.createCodeableConcept(activitydefinition.getActvtDfntnBdStCcCdngCSstm() /** { "tree" :"ActivityDefinition.bodySite", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addBodySite, addCoding, setSystem"} **/
						, activitydefinition.getActvtDfntnBdStCcCdngCVrsn() /** { "tree" :"ActivityDefinition.bodySite", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addBodySite, addCoding, setVersion"} **/
						, activitydefinition.getActvtDfntnBdStCcCdngCCde() /** { "tree" :"ActivityDefinition.bodySite", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addBodySite, addCoding, setCode"} **/
						, activitydefinition.getActvtDfntnBdStCcCdngCDsplay() /** { "tree" :"ActivityDefinition.bodySite", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addBodySite, addCoding, setDisplay"} **/
						, activitydefinition.getActvtDfntnBdStCcCdngCSrSlctd() /** { "tree" :"ActivityDefinition.bodySite", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addBodySite, addCoding, setUserSelected"} **/
						, activitydefinition.getActvtDfntnBdStCcTxt() /** { "tree" :"ActivityDefinition.bodySite", "datatype" : "CodeableConcept, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addBodySite, setText"} **/
						));
Activitydefinitionobj.addSpecimenRequirement(HapiFHIRHelpers.createReference(activitydefinition.getActvtDfntnSpcmnRqrmntRfrnce() /** { "tree" :"ActivityDefinition.specimenRequirement", "datatype" : "Reference", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addSpecimenRequirement"} **/
						));
Activitydefinitionobj.addObservationRequirement(HapiFHIRHelpers.createReference(activitydefinition.getActvtDfntnBsrvtnRqrmntRfrnce() /** { "tree" :"ActivityDefinition.observationRequirement", "datatype" : "Reference", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addObservationRequirement"} **/
						));
Activitydefinitionobj.addObservationResultRequirement(HapiFHIRHelpers.createReference(activitydefinition.getActvtDfntnBsrvtnRsltRqrmntRfrnce() /** { "tree" :"ActivityDefinition.observationResultRequirement", "datatype" : "Reference", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addObservationResultRequirement"} **/
						));
Activitydefinitionobj.setTransform(HapiFHIRHelpers.createcanonical(activitydefinition.getActvtDfntnTrnsfrmCnncl() /** { "tree" :"ActivityDefinition.transform", "datatype" : "canonical", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setTransform"} **/
						));
Activitydefinitionobj.setPath(HapiFHIRHelpers.createstring(activitydefinition.getActvtDfntnDnmcVlPthStrng() /** { "tree" :"ActivityDefinition.dynamicValue.path", "datatype" : "string", "cardinality" : "Required", "elementtree" : ["addDynamicValue"] , "methodName" : "setPath"} **/
						));
Activitydefinitionobj.setExpression(HapiFHIRHelpers.createExpression(activitydefinition.getActvtDfntnDnmcVlXprssnXprssnLngge() /** { "tree" :"ActivityDefinition.dynamicValue.expression", "datatype" : "Expression, code", "cardinality" : "Required", "elementtree" : ["addDynamicValue"] , "methodName" : "setExpression, setLanguage"} **/
						, activitydefinition.getActvtDfntnDnmcVlXprssnXprssnNme() /** { "tree" :"ActivityDefinition.dynamicValue.expression", "datatype" : "Expression, id", "cardinality" : "Required", "elementtree" : ["addDynamicValue"] , "methodName" : "setExpression, setName"} **/
						, activitydefinition.getActvtDfntnDnmcVlXprssnXprssnDscrptn() /** { "tree" :"ActivityDefinition.dynamicValue.expression", "datatype" : "Expression, string", "cardinality" : "Required", "elementtree" : ["addDynamicValue"] , "methodName" : "setExpression, setDescription"} **/
						, activitydefinition.getActvtDfntnDnmcVlXprssnXprssnXprssn() /** { "tree" :"ActivityDefinition.dynamicValue.expression", "datatype" : "Expression, string", "cardinality" : "Required", "elementtree" : ["addDynamicValue"] , "methodName" : "setExpression, setExpression"} **/
						, activitydefinition.getActvtDfntnDnmcVlXprssnXprssnRfrnce() /** { "tree" :"ActivityDefinition.dynamicValue.expression", "datatype" : "Expression, uri", "cardinality" : "Required", "elementtree" : ["addDynamicValue"] , "methodName" : "setExpression, setReference"} **/
		));
	}
}
