package main.templateoutput.Conversions;
// Generated on Jan 28, 2022, 8:02:40 AM 


import org.hl7.fhir.r4.model.Patient;

/**
 *  object for conversion model class Effectevidencesynthesis.
 * @see .Effectevidencesynthesis
 * @author Paul Kovach
 */
import main.java.com.campfhir.service.conversion.HapiFHIRHelpers;

public class EffectevidencesynthesisConversion 
{
	public Patient Effectevidencesynthesiss(main.templateoutput.Model.Effectevidencesynthesis effectevidencesynthesis) 
	{
			Patient  Effectevidencesynthesisobj = new Patient(); 

						Effectevidencesynthesisobj.setUrl(HapiFHIRHelpers.createuri(effectevidencesynthesis.getEffectEvidenceSynthesisUrlUri() /** { "tree" :"EffectEvidenceSynthesis.url", "datatype" : "uri", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setUrl"} **/
						));
Effectevidencesynthesisobj.addIdentifier(HapiFHIRHelpers.createIdentifier(effectevidencesynthesis.getEffctvdncSnthssDntfrDntfrSe() /** { "tree" :"EffectEvidenceSynthesis.identifier", "datatype" : "Identifier, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setUse"} **/
						, effectevidencesynthesis.getEffctvdncSnthssDntfrDntfrTpCcCSstm() /** { "tree" :"EffectEvidenceSynthesis.identifier", "datatype" : "Identifier, CodeableConcept, Coding, uri", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setType, addCoding, setSystem"} **/
						, effectevidencesynthesis.getEffctvdncSnthssDntfrDntfrTpCcCVrsn() /** { "tree" :"EffectEvidenceSynthesis.identifier", "datatype" : "Identifier, CodeableConcept, Coding, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setType, addCoding, setVersion"} **/
						, effectevidencesynthesis.getEffctvdncSnthssDntfrDntfrTpCcCCde() /** { "tree" :"EffectEvidenceSynthesis.identifier", "datatype" : "Identifier, CodeableConcept, Coding, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setType, addCoding, setCode"} **/
						, effectevidencesynthesis.getEffctvdncSnthssDntfrDntfrTpCcCDsplay() /** { "tree" :"EffectEvidenceSynthesis.identifier", "datatype" : "Identifier, CodeableConcept, Coding, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setType, addCoding, setDisplay"} **/
						, effectevidencesynthesis.getEffctvdncSnthssDntfrDntfrTpCcCSrSlctd() /** { "tree" :"EffectEvidenceSynthesis.identifier", "datatype" : "Identifier, CodeableConcept, Coding, boolean", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setType, addCoding, setUserSelected"} **/
						, effectevidencesynthesis.getEffctvdncSnthssDntfrDntfrTpCcTxt() /** { "tree" :"EffectEvidenceSynthesis.identifier", "datatype" : "Identifier, CodeableConcept, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setType, setText"} **/
						, effectevidencesynthesis.getEffctvdncSnthssDntfrDntfrPrdPrdStrt() /** { "tree" :"EffectEvidenceSynthesis.identifier", "datatype" : "Identifier, Period, dateTime", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setPeriod, setStart"} **/
						, effectevidencesynthesis.getEffctvdncSnthssDntfrDntfrPrdPrdNd() /** { "tree" :"EffectEvidenceSynthesis.identifier", "datatype" : "Identifier, Period, dateTime", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setPeriod, setEnd"} **/
						, effectevidencesynthesis.getEffctvdncSnthssDntfrDntfrSsgnr() /** { "tree" :"EffectEvidenceSynthesis.identifier", "datatype" : "Identifier, Reference", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setAssigner"} **/
						, effectevidencesynthesis.getEffctvdncSnthssDntfrDntfrVlue() /** { "tree" :"EffectEvidenceSynthesis.identifier", "datatype" : "Identifier, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setValue"} **/
						, effectevidencesynthesis.getEffctvdncSnthssDntfrDntfrSstm() /** { "tree" :"EffectEvidenceSynthesis.identifier", "datatype" : "Identifier, uri", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setSystem"} **/
						));
Effectevidencesynthesisobj.setVersion(HapiFHIRHelpers.createstring(effectevidencesynthesis.getEffctvdncSnthssVrsnStrng() /** { "tree" :"EffectEvidenceSynthesis.version", "datatype" : "string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setVersion"} **/
						));
Effectevidencesynthesisobj.setName(HapiFHIRHelpers.createstring(effectevidencesynthesis.getEffctvdncSnthssNmStrng() /** { "tree" :"EffectEvidenceSynthesis.name", "datatype" : "string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setName"} **/
						));
Effectevidencesynthesisobj.setTitle(HapiFHIRHelpers.createstring(effectevidencesynthesis.getEffctvdncSnthssTtlStrng() /** { "tree" :"EffectEvidenceSynthesis.title", "datatype" : "string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setTitle"} **/
						));
Effectevidencesynthesisobj.setStatus(HapiFHIRHelpers.createcode(effectevidencesynthesis.getEffctvdncSnthssSttsCde() /** { "tree" :"EffectEvidenceSynthesis.status", "datatype" : "code", "cardinality" : "Required", "elementtree" : [] , "methodName" : "setStatus"} **/
						));
Effectevidencesynthesisobj.setDate(HapiFHIRHelpers.createdateTime(effectevidencesynthesis.getEffctvdncSnthssDtDtTme() /** { "tree" :"EffectEvidenceSynthesis.date", "datatype" : "dateTime", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setDate"} **/
						));
Effectevidencesynthesisobj.setPublisher(HapiFHIRHelpers.createstring(effectevidencesynthesis.getEffctvdncSnthssPblshrStrng() /** { "tree" :"EffectEvidenceSynthesis.publisher", "datatype" : "string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setPublisher"} **/
						));
Effectevidencesynthesisobj.addContact(HapiFHIRHelpers.createContactDetail(effectevidencesynthesis.getEffctvdncSnthssCntctCntctDtlTlcmCntctPntPrdStrt() /** { "tree" :"EffectEvidenceSynthesis.contact", "datatype" : "ContactDetail, ContactPoint, Period, dateTime", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addContact, setTelecom, setPeriod, setStart"} **/
						, effectevidencesynthesis.getEffctvdncSnthssCntctCntctDtlTlcmCntctPntPrdNd() /** { "tree" :"EffectEvidenceSynthesis.contact", "datatype" : "ContactDetail, ContactPoint, Period, dateTime", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addContact, setTelecom, setPeriod, setEnd"} **/
						, effectevidencesynthesis.getEffctvdncSnthssCntctCntctDtlTlcmCntctPntSstm() /** { "tree" :"EffectEvidenceSynthesis.contact", "datatype" : "ContactDetail, ContactPoint, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addContact, setTelecom, setSystem"} **/
						, effectevidencesynthesis.getEffctvdncSnthssCntctCntctDtlTlcmCntctPntVlue() /** { "tree" :"EffectEvidenceSynthesis.contact", "datatype" : "ContactDetail, ContactPoint, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addContact, setTelecom, setValue"} **/
						, effectevidencesynthesis.getEffctvdncSnthssCntctCntctDtlTlcmCntctPntSe() /** { "tree" :"EffectEvidenceSynthesis.contact", "datatype" : "ContactDetail, ContactPoint, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addContact, setTelecom, setUse"} **/
						, effectevidencesynthesis.getEffctvdncSnthssCntctCntctDtlTlcmCntctPntRnk() /** { "tree" :"EffectEvidenceSynthesis.contact", "datatype" : "ContactDetail, ContactPoint, positiveInt", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addContact, setTelecom, setRank"} **/
						, effectevidencesynthesis.getEffctvdncSnthssCntctCntctDtlNme() /** { "tree" :"EffectEvidenceSynthesis.contact", "datatype" : "ContactDetail, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addContact, addName"} **/
						));
Effectevidencesynthesisobj.setDescription(HapiFHIRHelpers.createmarkdown(effectevidencesynthesis.getEffctvdncSnthssDscrptnMrkdwn() /** { "tree" :"EffectEvidenceSynthesis.description", "datatype" : "markdown", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setDescription"} **/
						));
Effectevidencesynthesisobj.addNote(HapiFHIRHelpers.createAnnotation(effectevidencesynthesis.getEffctvdncSnthssNtNnttnTme() /** { "tree" :"EffectEvidenceSynthesis.note", "datatype" : "Annotation, dateTime", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addNote, setTime"} **/
						, effectevidencesynthesis.getEffctvdncSnthssNtNnttnTxt() /** { "tree" :"EffectEvidenceSynthesis.note", "datatype" : "Annotation, markdown", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addNote, setText"} **/
						, effectevidencesynthesis.getEffctvdncSnthssNtNnttnThrRfrnce() /** { "tree" :"EffectEvidenceSynthesis.note", "datatype" : "Annotation, Reference", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addNote, setAuthorReference"} **/
						, effectevidencesynthesis.getEffctvdncSnthssNtNnttnThrStrng() /** { "tree" :"EffectEvidenceSynthesis.note", "datatype" : "Annotation, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addNote, setAuthorString"} **/
						));
Effectevidencesynthesisobj.addUseContext(HapiFHIRHelpers.createUsageContext(effectevidencesynthesis.getEffctvdncSnthssSCntxtSgCntxtVlCcCcCSstm() /** { "tree" :"EffectEvidenceSynthesis.useContext", "datatype" : "UsageContext, CodeableConcept, Coding, uri", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addUseContext, addValueCodeableConcept, addCoding, setSystem"} **/
						, effectevidencesynthesis.getEffctvdncSnthssSCntxtSgCntxtVlCcCcCVrsn() /** { "tree" :"EffectEvidenceSynthesis.useContext", "datatype" : "UsageContext, CodeableConcept, Coding, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addUseContext, addValueCodeableConcept, addCoding, setVersion"} **/
						, effectevidencesynthesis.getEffctvdncSnthssSCntxtSgCntxtVlCcCcCCde() /** { "tree" :"EffectEvidenceSynthesis.useContext", "datatype" : "UsageContext, CodeableConcept, Coding, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addUseContext, addValueCodeableConcept, addCoding, setCode"} **/
						, effectevidencesynthesis.getEffctvdncSnthssSCntxtSgCntxtVlCcCcCDsplay() /** { "tree" :"EffectEvidenceSynthesis.useContext", "datatype" : "UsageContext, CodeableConcept, Coding, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addUseContext, addValueCodeableConcept, addCoding, setDisplay"} **/
						, effectevidencesynthesis.getEffctvdncSnthssSCntxtSgCntxtVlCcCcCSrSlctd() /** { "tree" :"EffectEvidenceSynthesis.useContext", "datatype" : "UsageContext, CodeableConcept, Coding, boolean", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addUseContext, addValueCodeableConcept, addCoding, setUserSelected"} **/
						, effectevidencesynthesis.getEffctvdncSnthssSCntxtSgCntxtVlCcCcTxt() /** { "tree" :"EffectEvidenceSynthesis.useContext", "datatype" : "UsageContext, CodeableConcept, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addUseContext, addValueCodeableConcept, setText"} **/
						, effectevidencesynthesis.getEffctvdncSnthssSCntxtSgCntxtCdCSstm() /** { "tree" :"EffectEvidenceSynthesis.useContext", "datatype" : "UsageContext, Coding, uri", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addUseContext, addCode, setSystem"} **/
						, effectevidencesynthesis.getEffctvdncSnthssSCntxtSgCntxtCdCVrsn() /** { "tree" :"EffectEvidenceSynthesis.useContext", "datatype" : "UsageContext, Coding, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addUseContext, addCode, setVersion"} **/
						, effectevidencesynthesis.getEffctvdncSnthssSCntxtSgCntxtCdCCde() /** { "tree" :"EffectEvidenceSynthesis.useContext", "datatype" : "UsageContext, Coding, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addUseContext, addCode, setCode"} **/
						, effectevidencesynthesis.getEffctvdncSnthssSCntxtSgCntxtCdCDsplay() /** { "tree" :"EffectEvidenceSynthesis.useContext", "datatype" : "UsageContext, Coding, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addUseContext, addCode, setDisplay"} **/
						, effectevidencesynthesis.getEffctvdncSnthssSCntxtSgCntxtCdCSrSlctd() /** { "tree" :"EffectEvidenceSynthesis.useContext", "datatype" : "UsageContext, Coding, boolean", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addUseContext, addCode, setUserSelected"} **/
						, effectevidencesynthesis.getEffctvdncSnthssSCntxtSgCntxtVlQnttQnttVlue() /** { "tree" :"EffectEvidenceSynthesis.useContext", "datatype" : "UsageContext, Quantity, decimal", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addUseContext, addValueQuantity, setValue"} **/
						, effectevidencesynthesis.getEffctvdncSnthssSCntxtSgCntxtVlQnttQnttCmprtr() /** { "tree" :"EffectEvidenceSynthesis.useContext", "datatype" : "UsageContext, Quantity, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addUseContext, addValueQuantity, setComparator"} **/
						, effectevidencesynthesis.getEffctvdncSnthssSCntxtSgCntxtVlQnttQnttNt() /** { "tree" :"EffectEvidenceSynthesis.useContext", "datatype" : "UsageContext, Quantity, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addUseContext, addValueQuantity, setUnit"} **/
						, effectevidencesynthesis.getEffctvdncSnthssSCntxtSgCntxtVlQnttQnttSstm() /** { "tree" :"EffectEvidenceSynthesis.useContext", "datatype" : "UsageContext, Quantity, uri", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addUseContext, addValueQuantity, setSystem"} **/
						, effectevidencesynthesis.getEffctvdncSnthssSCntxtSgCntxtVlQnttQnttCde() /** { "tree" :"EffectEvidenceSynthesis.useContext", "datatype" : "UsageContext, Quantity, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addUseContext, addValueQuantity, setCode"} **/
						, effectevidencesynthesis.getEffctvdncSnthssSCntxtSgCntxtVlRngRngLw() /** { "tree" :"EffectEvidenceSynthesis.useContext", "datatype" : "UsageContext, Range, SimpleQuantity", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addUseContext, addValueRange, setLow"} **/
						, effectevidencesynthesis.getEffctvdncSnthssSCntxtSgCntxtVlRngRngHgh() /** { "tree" :"EffectEvidenceSynthesis.useContext", "datatype" : "UsageContext, Range, SimpleQuantity", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addUseContext, addValueRange, setHigh"} **/
						, effectevidencesynthesis.getEffctvdncSnthssSCntxtSgCntxtVlRfrnce() /** { "tree" :"EffectEvidenceSynthesis.useContext", "datatype" : "UsageContext, Reference", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addUseContext, addValueReference"} **/
						));
Effectevidencesynthesisobj.addJurisdiction(HapiFHIRHelpers.createCodeableConcept(effectevidencesynthesis.getEffctvdncSnthssJrsdctnCcCdngCSstm() /** { "tree" :"EffectEvidenceSynthesis.jurisdiction", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addJurisdiction, addCoding, setSystem"} **/
						, effectevidencesynthesis.getEffctvdncSnthssJrsdctnCcCdngCVrsn() /** { "tree" :"EffectEvidenceSynthesis.jurisdiction", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addJurisdiction, addCoding, setVersion"} **/
						, effectevidencesynthesis.getEffctvdncSnthssJrsdctnCcCdngCCde() /** { "tree" :"EffectEvidenceSynthesis.jurisdiction", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addJurisdiction, addCoding, setCode"} **/
						, effectevidencesynthesis.getEffctvdncSnthssJrsdctnCcCdngCDsplay() /** { "tree" :"EffectEvidenceSynthesis.jurisdiction", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addJurisdiction, addCoding, setDisplay"} **/
						, effectevidencesynthesis.getEffctvdncSnthssJrsdctnCcCdngCSrSlctd() /** { "tree" :"EffectEvidenceSynthesis.jurisdiction", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addJurisdiction, addCoding, setUserSelected"} **/
						, effectevidencesynthesis.getEffctvdncSnthssJrsdctnCcTxt() /** { "tree" :"EffectEvidenceSynthesis.jurisdiction", "datatype" : "CodeableConcept, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addJurisdiction, setText"} **/
						));
Effectevidencesynthesisobj.setCopyright(HapiFHIRHelpers.createmarkdown(effectevidencesynthesis.getEffctvdncSnthssCprghtMrkdwn() /** { "tree" :"EffectEvidenceSynthesis.copyright", "datatype" : "markdown", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setCopyright"} **/
						));
Effectevidencesynthesisobj.setApprovalDate(HapiFHIRHelpers.createdate(effectevidencesynthesis.getEffctvdncSnthssPprvlDtDte() /** { "tree" :"EffectEvidenceSynthesis.approvalDate", "datatype" : "date", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setApprovalDate"} **/
						));
Effectevidencesynthesisobj.setLastReviewDate(HapiFHIRHelpers.createdate(effectevidencesynthesis.getEffctvdncSnthssLstRvwDtDte() /** { "tree" :"EffectEvidenceSynthesis.lastReviewDate", "datatype" : "date", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setLastReviewDate"} **/
						));
Effectevidencesynthesisobj.setEffectivePeriod(HapiFHIRHelpers.createPeriod(effectevidencesynthesis.getEffctvdncSnthssFfctvPrdPrdStrt() /** { "tree" :"EffectEvidenceSynthesis.effectivePeriod", "datatype" : "Period, dateTime", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setEffectivePeriod, setStart"} **/
						, effectevidencesynthesis.getEffctvdncSnthssFfctvPrdPrdNd() /** { "tree" :"EffectEvidenceSynthesis.effectivePeriod", "datatype" : "Period, dateTime", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setEffectivePeriod, setEnd"} **/
						));
Effectevidencesynthesisobj.addTopic(HapiFHIRHelpers.createCodeableConcept(effectevidencesynthesis.getEffctvdncSnthssTpcCcCdngCSstm() /** { "tree" :"EffectEvidenceSynthesis.topic", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addTopic, addCoding, setSystem"} **/
						, effectevidencesynthesis.getEffctvdncSnthssTpcCcCdngCVrsn() /** { "tree" :"EffectEvidenceSynthesis.topic", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addTopic, addCoding, setVersion"} **/
						, effectevidencesynthesis.getEffctvdncSnthssTpcCcCdngCCde() /** { "tree" :"EffectEvidenceSynthesis.topic", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addTopic, addCoding, setCode"} **/
						, effectevidencesynthesis.getEffctvdncSnthssTpcCcCdngCDsplay() /** { "tree" :"EffectEvidenceSynthesis.topic", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addTopic, addCoding, setDisplay"} **/
						, effectevidencesynthesis.getEffctvdncSnthssTpcCcCdngCSrSlctd() /** { "tree" :"EffectEvidenceSynthesis.topic", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addTopic, addCoding, setUserSelected"} **/
						, effectevidencesynthesis.getEffctvdncSnthssTpcCcTxt() /** { "tree" :"EffectEvidenceSynthesis.topic", "datatype" : "CodeableConcept, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addTopic, setText"} **/
						));
Effectevidencesynthesisobj.addAuthor(HapiFHIRHelpers.createContactDetail(effectevidencesynthesis.getEffctvdncSnthssThrCntctDtlTlcmCntctPntPrdStrt() /** { "tree" :"EffectEvidenceSynthesis.author", "datatype" : "ContactDetail, ContactPoint, Period, dateTime", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addAuthor, setTelecom, setPeriod, setStart"} **/
						, effectevidencesynthesis.getEffctvdncSnthssThrCntctDtlTlcmCntctPntPrdNd() /** { "tree" :"EffectEvidenceSynthesis.author", "datatype" : "ContactDetail, ContactPoint, Period, dateTime", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addAuthor, setTelecom, setPeriod, setEnd"} **/
						, effectevidencesynthesis.getEffctvdncSnthssThrCntctDtlTlcmCntctPntSstm() /** { "tree" :"EffectEvidenceSynthesis.author", "datatype" : "ContactDetail, ContactPoint, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addAuthor, setTelecom, setSystem"} **/
						, effectevidencesynthesis.getEffctvdncSnthssThrCntctDtlTlcmCntctPntVlue() /** { "tree" :"EffectEvidenceSynthesis.author", "datatype" : "ContactDetail, ContactPoint, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addAuthor, setTelecom, setValue"} **/
						, effectevidencesynthesis.getEffctvdncSnthssThrCntctDtlTlcmCntctPntSe() /** { "tree" :"EffectEvidenceSynthesis.author", "datatype" : "ContactDetail, ContactPoint, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addAuthor, setTelecom, setUse"} **/
						, effectevidencesynthesis.getEffctvdncSnthssThrCntctDtlTlcmCntctPntRnk() /** { "tree" :"EffectEvidenceSynthesis.author", "datatype" : "ContactDetail, ContactPoint, positiveInt", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addAuthor, setTelecom, setRank"} **/
						, effectevidencesynthesis.getEffctvdncSnthssThrCntctDtlNme() /** { "tree" :"EffectEvidenceSynthesis.author", "datatype" : "ContactDetail, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addAuthor, addName"} **/
						));
Effectevidencesynthesisobj.addEditor(HapiFHIRHelpers.createContactDetail(effectevidencesynthesis.getEffctvdncSnthssDtrCntctDtlTlcmCntctPntPrdStrt() /** { "tree" :"EffectEvidenceSynthesis.editor", "datatype" : "ContactDetail, ContactPoint, Period, dateTime", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addEditor, setTelecom, setPeriod, setStart"} **/
						, effectevidencesynthesis.getEffctvdncSnthssDtrCntctDtlTlcmCntctPntPrdNd() /** { "tree" :"EffectEvidenceSynthesis.editor", "datatype" : "ContactDetail, ContactPoint, Period, dateTime", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addEditor, setTelecom, setPeriod, setEnd"} **/
						, effectevidencesynthesis.getEffctvdncSnthssDtrCntctDtlTlcmCntctPntSstm() /** { "tree" :"EffectEvidenceSynthesis.editor", "datatype" : "ContactDetail, ContactPoint, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addEditor, setTelecom, setSystem"} **/
						, effectevidencesynthesis.getEffctvdncSnthssDtrCntctDtlTlcmCntctPntVlue() /** { "tree" :"EffectEvidenceSynthesis.editor", "datatype" : "ContactDetail, ContactPoint, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addEditor, setTelecom, setValue"} **/
						, effectevidencesynthesis.getEffctvdncSnthssDtrCntctDtlTlcmCntctPntSe() /** { "tree" :"EffectEvidenceSynthesis.editor", "datatype" : "ContactDetail, ContactPoint, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addEditor, setTelecom, setUse"} **/
						, effectevidencesynthesis.getEffctvdncSnthssDtrCntctDtlTlcmCntctPntRnk() /** { "tree" :"EffectEvidenceSynthesis.editor", "datatype" : "ContactDetail, ContactPoint, positiveInt", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addEditor, setTelecom, setRank"} **/
						, effectevidencesynthesis.getEffctvdncSnthssDtrCntctDtlNme() /** { "tree" :"EffectEvidenceSynthesis.editor", "datatype" : "ContactDetail, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addEditor, addName"} **/
						));
Effectevidencesynthesisobj.addReviewer(HapiFHIRHelpers.createContactDetail(effectevidencesynthesis.getEffctvdncSnthssRvwrCntctDtlTlcmCntctPntPrdStrt() /** { "tree" :"EffectEvidenceSynthesis.reviewer", "datatype" : "ContactDetail, ContactPoint, Period, dateTime", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addReviewer, setTelecom, setPeriod, setStart"} **/
						, effectevidencesynthesis.getEffctvdncSnthssRvwrCntctDtlTlcmCntctPntPrdNd() /** { "tree" :"EffectEvidenceSynthesis.reviewer", "datatype" : "ContactDetail, ContactPoint, Period, dateTime", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addReviewer, setTelecom, setPeriod, setEnd"} **/
						, effectevidencesynthesis.getEffctvdncSnthssRvwrCntctDtlTlcmCntctPntSstm() /** { "tree" :"EffectEvidenceSynthesis.reviewer", "datatype" : "ContactDetail, ContactPoint, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addReviewer, setTelecom, setSystem"} **/
						, effectevidencesynthesis.getEffctvdncSnthssRvwrCntctDtlTlcmCntctPntVlue() /** { "tree" :"EffectEvidenceSynthesis.reviewer", "datatype" : "ContactDetail, ContactPoint, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addReviewer, setTelecom, setValue"} **/
						, effectevidencesynthesis.getEffctvdncSnthssRvwrCntctDtlTlcmCntctPntSe() /** { "tree" :"EffectEvidenceSynthesis.reviewer", "datatype" : "ContactDetail, ContactPoint, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addReviewer, setTelecom, setUse"} **/
						, effectevidencesynthesis.getEffctvdncSnthssRvwrCntctDtlTlcmCntctPntRnk() /** { "tree" :"EffectEvidenceSynthesis.reviewer", "datatype" : "ContactDetail, ContactPoint, positiveInt", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addReviewer, setTelecom, setRank"} **/
						, effectevidencesynthesis.getEffctvdncSnthssRvwrCntctDtlNme() /** { "tree" :"EffectEvidenceSynthesis.reviewer", "datatype" : "ContactDetail, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addReviewer, addName"} **/
						));
Effectevidencesynthesisobj.addEndorser(HapiFHIRHelpers.createContactDetail(effectevidencesynthesis.getEffctvdncSnthssNdrsrCntctDtlTlcmCntctPntPrdStrt() /** { "tree" :"EffectEvidenceSynthesis.endorser", "datatype" : "ContactDetail, ContactPoint, Period, dateTime", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addEndorser, setTelecom, setPeriod, setStart"} **/
						, effectevidencesynthesis.getEffctvdncSnthssNdrsrCntctDtlTlcmCntctPntPrdNd() /** { "tree" :"EffectEvidenceSynthesis.endorser", "datatype" : "ContactDetail, ContactPoint, Period, dateTime", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addEndorser, setTelecom, setPeriod, setEnd"} **/
						, effectevidencesynthesis.getEffctvdncSnthssNdrsrCntctDtlTlcmCntctPntSstm() /** { "tree" :"EffectEvidenceSynthesis.endorser", "datatype" : "ContactDetail, ContactPoint, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addEndorser, setTelecom, setSystem"} **/
						, effectevidencesynthesis.getEffctvdncSnthssNdrsrCntctDtlTlcmCntctPntVlue() /** { "tree" :"EffectEvidenceSynthesis.endorser", "datatype" : "ContactDetail, ContactPoint, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addEndorser, setTelecom, setValue"} **/
						, effectevidencesynthesis.getEffctvdncSnthssNdrsrCntctDtlTlcmCntctPntSe() /** { "tree" :"EffectEvidenceSynthesis.endorser", "datatype" : "ContactDetail, ContactPoint, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addEndorser, setTelecom, setUse"} **/
						, effectevidencesynthesis.getEffctvdncSnthssNdrsrCntctDtlTlcmCntctPntRnk() /** { "tree" :"EffectEvidenceSynthesis.endorser", "datatype" : "ContactDetail, ContactPoint, positiveInt", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addEndorser, setTelecom, setRank"} **/
						, effectevidencesynthesis.getEffctvdncSnthssNdrsrCntctDtlNme() /** { "tree" :"EffectEvidenceSynthesis.endorser", "datatype" : "ContactDetail, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addEndorser, addName"} **/
						));
Effectevidencesynthesisobj.addRelatedArtifact(HapiFHIRHelpers.createRelatedArtifact(effectevidencesynthesis.getEffctvdncSnthssRltdrtfctRltdrtfctDcmntTtchmntCntntTpe() /** { "tree" :"EffectEvidenceSynthesis.relatedArtifact", "datatype" : "RelatedArtifact, Attachment, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addRelatedArtifact, setDocument, setContentType"} **/
						, effectevidencesynthesis.getEffctvdncSnthssRltdrtfctRltdrtfctDcmntTtchmntLngge() /** { "tree" :"EffectEvidenceSynthesis.relatedArtifact", "datatype" : "RelatedArtifact, Attachment, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addRelatedArtifact, setDocument, setLanguage"} **/
						, effectevidencesynthesis.getEffctvdncSnthssRltdrtfctRltdrtfctDcmntTtchmntDta() /** { "tree" :"EffectEvidenceSynthesis.relatedArtifact", "datatype" : "RelatedArtifact, Attachment, base64Binary", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addRelatedArtifact, setDocument, setData"} **/
						, effectevidencesynthesis.getEffctvdncSnthssRltdrtfctRltdrtfctDcmntTtchmntRl() /** { "tree" :"EffectEvidenceSynthesis.relatedArtifact", "datatype" : "RelatedArtifact, Attachment, url", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addRelatedArtifact, setDocument, setUrl"} **/
						, effectevidencesynthesis.getEffctvdncSnthssRltdrtfctRltdrtfctDcmntTtchmntSze() /** { "tree" :"EffectEvidenceSynthesis.relatedArtifact", "datatype" : "RelatedArtifact, Attachment, unsignedInt", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addRelatedArtifact, setDocument, setSize"} **/
						, effectevidencesynthesis.getEffctvdncSnthssRltdrtfctRltdrtfctDcmntTtchmntHsh() /** { "tree" :"EffectEvidenceSynthesis.relatedArtifact", "datatype" : "RelatedArtifact, Attachment, base64Binary", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addRelatedArtifact, setDocument, setHash"} **/
						, effectevidencesynthesis.getEffctvdncSnthssRltdrtfctRltdrtfctDcmntTtchmntTtle() /** { "tree" :"EffectEvidenceSynthesis.relatedArtifact", "datatype" : "RelatedArtifact, Attachment, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addRelatedArtifact, setDocument, setTitle"} **/
						, effectevidencesynthesis.getEffctvdncSnthssRltdrtfctRltdrtfctDcmntTtchmntCrtn() /** { "tree" :"EffectEvidenceSynthesis.relatedArtifact", "datatype" : "RelatedArtifact, Attachment, dateTime", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addRelatedArtifact, setDocument, setCreation"} **/
						, effectevidencesynthesis.getEffctvdncSnthssRltdrtfctRltdrtfctRsrce() /** { "tree" :"EffectEvidenceSynthesis.relatedArtifact", "datatype" : "RelatedArtifact, canonical", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addRelatedArtifact, setResource"} **/
						, effectevidencesynthesis.getEffctvdncSnthssRltdrtfctRltdrtfctTpe() /** { "tree" :"EffectEvidenceSynthesis.relatedArtifact", "datatype" : "RelatedArtifact, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addRelatedArtifact, setType"} **/
						, effectevidencesynthesis.getEffctvdncSnthssRltdrtfctRltdrtfctCttn() /** { "tree" :"EffectEvidenceSynthesis.relatedArtifact", "datatype" : "RelatedArtifact, markdown", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addRelatedArtifact, setCitation"} **/
						, effectevidencesynthesis.getEffctvdncSnthssRltdrtfctRltdrtfctLbl() /** { "tree" :"EffectEvidenceSynthesis.relatedArtifact", "datatype" : "RelatedArtifact, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addRelatedArtifact, setLabel"} **/
						, effectevidencesynthesis.getEffctvdncSnthssRltdrtfctRltdrtfctDsplay() /** { "tree" :"EffectEvidenceSynthesis.relatedArtifact", "datatype" : "RelatedArtifact, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addRelatedArtifact, setDisplay"} **/
						, effectevidencesynthesis.getEffctvdncSnthssRltdrtfctRltdrtfctRl() /** { "tree" :"EffectEvidenceSynthesis.relatedArtifact", "datatype" : "RelatedArtifact, url", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addRelatedArtifact, setUrl"} **/
						));
Effectevidencesynthesisobj.setSynthesisType(HapiFHIRHelpers.createCodeableConcept(effectevidencesynthesis.getEffctvdncSnthssSnthssTpCcCdngCSstm() /** { "tree" :"EffectEvidenceSynthesis.synthesisType", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setSynthesisType, addCoding, setSystem"} **/
						, effectevidencesynthesis.getEffctvdncSnthssSnthssTpCcCdngCVrsn() /** { "tree" :"EffectEvidenceSynthesis.synthesisType", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setSynthesisType, addCoding, setVersion"} **/
						, effectevidencesynthesis.getEffctvdncSnthssSnthssTpCcCdngCCde() /** { "tree" :"EffectEvidenceSynthesis.synthesisType", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setSynthesisType, addCoding, setCode"} **/
						, effectevidencesynthesis.getEffctvdncSnthssSnthssTpCcCdngCDsplay() /** { "tree" :"EffectEvidenceSynthesis.synthesisType", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setSynthesisType, addCoding, setDisplay"} **/
						, effectevidencesynthesis.getEffctvdncSnthssSnthssTpCcCdngCSrSlctd() /** { "tree" :"EffectEvidenceSynthesis.synthesisType", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setSynthesisType, addCoding, setUserSelected"} **/
						, effectevidencesynthesis.getEffctvdncSnthssSnthssTpCcTxt() /** { "tree" :"EffectEvidenceSynthesis.synthesisType", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setSynthesisType, setText"} **/
						));
Effectevidencesynthesisobj.setStudyType(HapiFHIRHelpers.createCodeableConcept(effectevidencesynthesis.getEffctvdncSnthssStdTpCcCdngCSstm() /** { "tree" :"EffectEvidenceSynthesis.studyType", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setStudyType, addCoding, setSystem"} **/
						, effectevidencesynthesis.getEffctvdncSnthssStdTpCcCdngCVrsn() /** { "tree" :"EffectEvidenceSynthesis.studyType", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setStudyType, addCoding, setVersion"} **/
						, effectevidencesynthesis.getEffctvdncSnthssStdTpCcCdngCCde() /** { "tree" :"EffectEvidenceSynthesis.studyType", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setStudyType, addCoding, setCode"} **/
						, effectevidencesynthesis.getEffctvdncSnthssStdTpCcCdngCDsplay() /** { "tree" :"EffectEvidenceSynthesis.studyType", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setStudyType, addCoding, setDisplay"} **/
						, effectevidencesynthesis.getEffctvdncSnthssStdTpCcCdngCSrSlctd() /** { "tree" :"EffectEvidenceSynthesis.studyType", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setStudyType, addCoding, setUserSelected"} **/
						, effectevidencesynthesis.getEffctvdncSnthssStdTpCcTxt() /** { "tree" :"EffectEvidenceSynthesis.studyType", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setStudyType, setText"} **/
						));
Effectevidencesynthesisobj.setPopulation(HapiFHIRHelpers.createReference(effectevidencesynthesis.getEffctvdncSnthssPpltnRfrnce() /** { "tree" :"EffectEvidenceSynthesis.population", "datatype" : "Reference", "cardinality" : "Required", "elementtree" : [] , "methodName" : "setPopulation"} **/
						));
Effectevidencesynthesisobj.setExposure(HapiFHIRHelpers.createReference(effectevidencesynthesis.getEffctvdncSnthssXpsrRfrnce() /** { "tree" :"EffectEvidenceSynthesis.exposure", "datatype" : "Reference", "cardinality" : "Required", "elementtree" : [] , "methodName" : "setExposure"} **/
						));
Effectevidencesynthesisobj.setExposureAlternative(HapiFHIRHelpers.createReference(effectevidencesynthesis.getEffctvdncSnthssXpsrltrntvRfrnce() /** { "tree" :"EffectEvidenceSynthesis.exposureAlternative", "datatype" : "Reference", "cardinality" : "Required", "elementtree" : [] , "methodName" : "setExposureAlternative"} **/
						));
Effectevidencesynthesisobj.setOutcome(HapiFHIRHelpers.createReference(effectevidencesynthesis.getEffctvdncSnthssTcmRfrnce() /** { "tree" :"EffectEvidenceSynthesis.outcome", "datatype" : "Reference", "cardinality" : "Required", "elementtree" : [] , "methodName" : "setOutcome"} **/
						));
Effectevidencesynthesisobj.setDescription(HapiFHIRHelpers.createstring(effectevidencesynthesis.getEffctvdncSnthssSmplSzDscrptnStrng() /** { "tree" :"EffectEvidenceSynthesis.sampleSize.description", "datatype" : "string", "cardinality" : "ZeroOne", "elementtree" : ["setSampleSize"] , "methodName" : "setDescription"} **/
						));
Effectevidencesynthesisobj.setNumberOfStudies(HapiFHIRHelpers.createinteger(effectevidencesynthesis.getEffctvdncSnthssSmplSzNmbrfStdsNtgr() /** { "tree" :"EffectEvidenceSynthesis.sampleSize.numberOfStudies", "datatype" : "integer", "cardinality" : "ZeroOne", "elementtree" : ["setSampleSize"] , "methodName" : "setNumberOfStudies"} **/
						));
Effectevidencesynthesisobj.setNumberOfParticipants(HapiFHIRHelpers.createinteger(effectevidencesynthesis.getEffctvdncSnthssSmplSzNmbrfPrtcpntsNtgr() /** { "tree" :"EffectEvidenceSynthesis.sampleSize.numberOfParticipants", "datatype" : "integer", "cardinality" : "ZeroOne", "elementtree" : ["setSampleSize"] , "methodName" : "setNumberOfParticipants"} **/
						));
Effectevidencesynthesisobj.setDescription(HapiFHIRHelpers.createstring(effectevidencesynthesis.getEffctvdncSnthssRsltsBxpsrDscrptnStrng() /** { "tree" :"EffectEvidenceSynthesis.resultsByExposure.description", "datatype" : "string", "cardinality" : "ZeroOne", "elementtree" : ["addResultsByExposure"] , "methodName" : "setDescription"} **/
						));
Effectevidencesynthesisobj.setExposureState(HapiFHIRHelpers.createcode(effectevidencesynthesis.getEffctvdncSnthssRsltsBxpsrXpsrSttCde() /** { "tree" :"EffectEvidenceSynthesis.resultsByExposure.exposureState", "datatype" : "code", "cardinality" : "ZeroOne", "elementtree" : ["addResultsByExposure"] , "methodName" : "setExposureState"} **/
						));
Effectevidencesynthesisobj.setVariantState(HapiFHIRHelpers.createCodeableConcept(effectevidencesynthesis.getEffctvdncSnthssRsltsBxpsrVrntSttCcCdngCSstm() /** { "tree" :"EffectEvidenceSynthesis.resultsByExposure.variantState", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : ["addResultsByExposure"] , "methodName" : "setVariantState, addCoding, setSystem"} **/
						, effectevidencesynthesis.getEffctvdncSnthssRsltsBxpsrVrntSttCcCdngCVrsn() /** { "tree" :"EffectEvidenceSynthesis.resultsByExposure.variantState", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addResultsByExposure"] , "methodName" : "setVariantState, addCoding, setVersion"} **/
						, effectevidencesynthesis.getEffctvdncSnthssRsltsBxpsrVrntSttCcCdngCCde() /** { "tree" :"EffectEvidenceSynthesis.resultsByExposure.variantState", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : ["addResultsByExposure"] , "methodName" : "setVariantState, addCoding, setCode"} **/
						, effectevidencesynthesis.getEffctvdncSnthssRsltsBxpsrVrntSttCcCdngCDsplay() /** { "tree" :"EffectEvidenceSynthesis.resultsByExposure.variantState", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addResultsByExposure"] , "methodName" : "setVariantState, addCoding, setDisplay"} **/
						, effectevidencesynthesis.getEffctvdncSnthssRsltsBxpsrVrntSttCcCdngCSrSlctd() /** { "tree" :"EffectEvidenceSynthesis.resultsByExposure.variantState", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : ["addResultsByExposure"] , "methodName" : "setVariantState, addCoding, setUserSelected"} **/
						, effectevidencesynthesis.getEffctvdncSnthssRsltsBxpsrVrntSttCcTxt() /** { "tree" :"EffectEvidenceSynthesis.resultsByExposure.variantState", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : ["addResultsByExposure"] , "methodName" : "setVariantState, setText"} **/
						));
Effectevidencesynthesisobj.setRiskEvidenceSynthesis(HapiFHIRHelpers.createReference(effectevidencesynthesis.getEffctvdncSnthssRsltsBxpsrRskvdncSnthssRfrnce() /** { "tree" :"EffectEvidenceSynthesis.resultsByExposure.riskEvidenceSynthesis", "datatype" : "Reference", "cardinality" : "Required", "elementtree" : ["addResultsByExposure"] , "methodName" : "setRiskEvidenceSynthesis"} **/
						));
Effectevidencesynthesisobj.setDescription(HapiFHIRHelpers.createstring(effectevidencesynthesis.getEffctvdncSnthssFfctstmtDscrptnStrng() /** { "tree" :"EffectEvidenceSynthesis.effectEstimate.description", "datatype" : "string", "cardinality" : "ZeroOne", "elementtree" : ["addEffectEstimate"] , "methodName" : "setDescription"} **/
						));
Effectevidencesynthesisobj.setType(HapiFHIRHelpers.createCodeableConcept(effectevidencesynthesis.getEffctvdncSnthssFfctstmtTpCcCdngCSstm() /** { "tree" :"EffectEvidenceSynthesis.effectEstimate.type", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : ["addEffectEstimate"] , "methodName" : "setType, addCoding, setSystem"} **/
						, effectevidencesynthesis.getEffctvdncSnthssFfctstmtTpCcCdngCVrsn() /** { "tree" :"EffectEvidenceSynthesis.effectEstimate.type", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addEffectEstimate"] , "methodName" : "setType, addCoding, setVersion"} **/
						, effectevidencesynthesis.getEffctvdncSnthssFfctstmtTpCcCdngCCde() /** { "tree" :"EffectEvidenceSynthesis.effectEstimate.type", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : ["addEffectEstimate"] , "methodName" : "setType, addCoding, setCode"} **/
						, effectevidencesynthesis.getEffctvdncSnthssFfctstmtTpCcCdngCDsplay() /** { "tree" :"EffectEvidenceSynthesis.effectEstimate.type", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addEffectEstimate"] , "methodName" : "setType, addCoding, setDisplay"} **/
						, effectevidencesynthesis.getEffctvdncSnthssFfctstmtTpCcCdngCSrSlctd() /** { "tree" :"EffectEvidenceSynthesis.effectEstimate.type", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : ["addEffectEstimate"] , "methodName" : "setType, addCoding, setUserSelected"} **/
						, effectevidencesynthesis.getEffctvdncSnthssFfctstmtTpCcTxt() /** { "tree" :"EffectEvidenceSynthesis.effectEstimate.type", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : ["addEffectEstimate"] , "methodName" : "setType, setText"} **/
						));
Effectevidencesynthesisobj.setVariantState(HapiFHIRHelpers.createCodeableConcept(effectevidencesynthesis.getEffctvdncSnthssFfctstmtVrntSttCcCdngCSstm() /** { "tree" :"EffectEvidenceSynthesis.effectEstimate.variantState", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : ["addEffectEstimate"] , "methodName" : "setVariantState, addCoding, setSystem"} **/
						, effectevidencesynthesis.getEffctvdncSnthssFfctstmtVrntSttCcCdngCVrsn() /** { "tree" :"EffectEvidenceSynthesis.effectEstimate.variantState", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addEffectEstimate"] , "methodName" : "setVariantState, addCoding, setVersion"} **/
						, effectevidencesynthesis.getEffctvdncSnthssFfctstmtVrntSttCcCdngCCde() /** { "tree" :"EffectEvidenceSynthesis.effectEstimate.variantState", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : ["addEffectEstimate"] , "methodName" : "setVariantState, addCoding, setCode"} **/
						, effectevidencesynthesis.getEffctvdncSnthssFfctstmtVrntSttCcCdngCDsplay() /** { "tree" :"EffectEvidenceSynthesis.effectEstimate.variantState", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addEffectEstimate"] , "methodName" : "setVariantState, addCoding, setDisplay"} **/
						, effectevidencesynthesis.getEffctvdncSnthssFfctstmtVrntSttCcCdngCSrSlctd() /** { "tree" :"EffectEvidenceSynthesis.effectEstimate.variantState", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : ["addEffectEstimate"] , "methodName" : "setVariantState, addCoding, setUserSelected"} **/
						, effectevidencesynthesis.getEffctvdncSnthssFfctstmtVrntSttCcTxt() /** { "tree" :"EffectEvidenceSynthesis.effectEstimate.variantState", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : ["addEffectEstimate"] , "methodName" : "setVariantState, setText"} **/
						));
Effectevidencesynthesisobj.setValue(HapiFHIRHelpers.createdecimal(effectevidencesynthesis.getEffctvdncSnthssFfctstmtVlDcml() /** { "tree" :"EffectEvidenceSynthesis.effectEstimate.value", "datatype" : "decimal", "cardinality" : "ZeroOne", "elementtree" : ["addEffectEstimate"] , "methodName" : "setValue"} **/
						));
Effectevidencesynthesisobj.setUnitOfMeasure(HapiFHIRHelpers.createCodeableConcept(effectevidencesynthesis.getEffctvdncSnthssFfctstmtNtfMsrCcCdngCSstm() /** { "tree" :"EffectEvidenceSynthesis.effectEstimate.unitOfMeasure", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : ["addEffectEstimate"] , "methodName" : "setUnitOfMeasure, addCoding, setSystem"} **/
						, effectevidencesynthesis.getEffctvdncSnthssFfctstmtNtfMsrCcCdngCVrsn() /** { "tree" :"EffectEvidenceSynthesis.effectEstimate.unitOfMeasure", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addEffectEstimate"] , "methodName" : "setUnitOfMeasure, addCoding, setVersion"} **/
						, effectevidencesynthesis.getEffctvdncSnthssFfctstmtNtfMsrCcCdngCCde() /** { "tree" :"EffectEvidenceSynthesis.effectEstimate.unitOfMeasure", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : ["addEffectEstimate"] , "methodName" : "setUnitOfMeasure, addCoding, setCode"} **/
						, effectevidencesynthesis.getEffctvdncSnthssFfctstmtNtfMsrCcCdngCDsplay() /** { "tree" :"EffectEvidenceSynthesis.effectEstimate.unitOfMeasure", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addEffectEstimate"] , "methodName" : "setUnitOfMeasure, addCoding, setDisplay"} **/
						, effectevidencesynthesis.getEffctvdncSnthssFfctstmtNtfMsrCcCdngCSrSlctd() /** { "tree" :"EffectEvidenceSynthesis.effectEstimate.unitOfMeasure", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : ["addEffectEstimate"] , "methodName" : "setUnitOfMeasure, addCoding, setUserSelected"} **/
						, effectevidencesynthesis.getEffctvdncSnthssFfctstmtNtfMsrCcTxt() /** { "tree" :"EffectEvidenceSynthesis.effectEstimate.unitOfMeasure", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : ["addEffectEstimate"] , "methodName" : "setUnitOfMeasure, setText"} **/
						));
Effectevidencesynthesisobj.setType(HapiFHIRHelpers.createCodeableConcept(effectevidencesynthesis.getEffctvdncSnthssFfctstmtPrcsnstmtTpCcCdngCSstm() /** { "tree" :"EffectEvidenceSynthesis.effectEstimate.precisionEstimate.type", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : ["addEffectEstimate", "addPrecisionEstimate"] , "methodName" : "setType, addCoding, setSystem"} **/
						, effectevidencesynthesis.getEffctvdncSnthssFfctstmtPrcsnstmtTpCcCdngCVrsn() /** { "tree" :"EffectEvidenceSynthesis.effectEstimate.precisionEstimate.type", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addEffectEstimate", "addPrecisionEstimate"] , "methodName" : "setType, addCoding, setVersion"} **/
						, effectevidencesynthesis.getEffctvdncSnthssFfctstmtPrcsnstmtTpCcCdngCCde() /** { "tree" :"EffectEvidenceSynthesis.effectEstimate.precisionEstimate.type", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : ["addEffectEstimate", "addPrecisionEstimate"] , "methodName" : "setType, addCoding, setCode"} **/
						, effectevidencesynthesis.getEffctvdncSnthssFfctstmtPrcsnstmtTpCcCdngCDsplay() /** { "tree" :"EffectEvidenceSynthesis.effectEstimate.precisionEstimate.type", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addEffectEstimate", "addPrecisionEstimate"] , "methodName" : "setType, addCoding, setDisplay"} **/
						, effectevidencesynthesis.getEffctvdncSnthssFfctstmtPrcsnstmtTpCcCdngCSrSlctd() /** { "tree" :"EffectEvidenceSynthesis.effectEstimate.precisionEstimate.type", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : ["addEffectEstimate", "addPrecisionEstimate"] , "methodName" : "setType, addCoding, setUserSelected"} **/
						, effectevidencesynthesis.getEffctvdncSnthssFfctstmtPrcsnstmtTpCcTxt() /** { "tree" :"EffectEvidenceSynthesis.effectEstimate.precisionEstimate.type", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : ["addEffectEstimate", "addPrecisionEstimate"] , "methodName" : "setType, setText"} **/
						));
Effectevidencesynthesisobj.setLevel(HapiFHIRHelpers.createdecimal(effectevidencesynthesis.getEffctvdncSnthssFfctstmtPrcsnstmtLvlDcml() /** { "tree" :"EffectEvidenceSynthesis.effectEstimate.precisionEstimate.level", "datatype" : "decimal", "cardinality" : "ZeroOne", "elementtree" : ["addEffectEstimate", "addPrecisionEstimate"] , "methodName" : "setLevel"} **/
						));
Effectevidencesynthesisobj.setFrom(HapiFHIRHelpers.createdecimal(effectevidencesynthesis.getEffctvdncSnthssFfctstmtPrcsnstmtFrmDcml() /** { "tree" :"EffectEvidenceSynthesis.effectEstimate.precisionEstimate.from", "datatype" : "decimal", "cardinality" : "ZeroOne", "elementtree" : ["addEffectEstimate", "addPrecisionEstimate"] , "methodName" : "setFrom"} **/
						));
Effectevidencesynthesisobj.setTo(HapiFHIRHelpers.createdecimal(effectevidencesynthesis.getEffctvdncSnthssFfctstmtPrcsnstmtTDcml() /** { "tree" :"EffectEvidenceSynthesis.effectEstimate.precisionEstimate.to", "datatype" : "decimal", "cardinality" : "ZeroOne", "elementtree" : ["addEffectEstimate", "addPrecisionEstimate"] , "methodName" : "setTo"} **/
						));
Effectevidencesynthesisobj.addRating(HapiFHIRHelpers.createCodeableConcept(effectevidencesynthesis.getEffctvdncSnthssCrtntRtngCcCdngCSstm() /** { "tree" :"EffectEvidenceSynthesis.certainty.rating", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "Many", "elementtree" : ["addCertainty"] , "methodName" : "addRating, addCoding, setSystem"} **/
						, effectevidencesynthesis.getEffctvdncSnthssCrtntRtngCcCdngCVrsn() /** { "tree" :"EffectEvidenceSynthesis.certainty.rating", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Many", "elementtree" : ["addCertainty"] , "methodName" : "addRating, addCoding, setVersion"} **/
						, effectevidencesynthesis.getEffctvdncSnthssCrtntRtngCcCdngCCde() /** { "tree" :"EffectEvidenceSynthesis.certainty.rating", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "Many", "elementtree" : ["addCertainty"] , "methodName" : "addRating, addCoding, setCode"} **/
						, effectevidencesynthesis.getEffctvdncSnthssCrtntRtngCcCdngCDsplay() /** { "tree" :"EffectEvidenceSynthesis.certainty.rating", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Many", "elementtree" : ["addCertainty"] , "methodName" : "addRating, addCoding, setDisplay"} **/
						, effectevidencesynthesis.getEffctvdncSnthssCrtntRtngCcCdngCSrSlctd() /** { "tree" :"EffectEvidenceSynthesis.certainty.rating", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "Many", "elementtree" : ["addCertainty"] , "methodName" : "addRating, addCoding, setUserSelected"} **/
						, effectevidencesynthesis.getEffctvdncSnthssCrtntRtngCcTxt() /** { "tree" :"EffectEvidenceSynthesis.certainty.rating", "datatype" : "CodeableConcept, string", "cardinality" : "Many", "elementtree" : ["addCertainty"] , "methodName" : "addRating, setText"} **/
						));
Effectevidencesynthesisobj.addNote(HapiFHIRHelpers.createAnnotation(effectevidencesynthesis.getEffctvdncSnthssCrtntNtNnttnTme() /** { "tree" :"EffectEvidenceSynthesis.certainty.note", "datatype" : "Annotation, dateTime", "cardinality" : "Many", "elementtree" : ["addCertainty"] , "methodName" : "addNote, setTime"} **/
						, effectevidencesynthesis.getEffctvdncSnthssCrtntNtNnttnTxt() /** { "tree" :"EffectEvidenceSynthesis.certainty.note", "datatype" : "Annotation, markdown", "cardinality" : "Many", "elementtree" : ["addCertainty"] , "methodName" : "addNote, setText"} **/
						, effectevidencesynthesis.getEffctvdncSnthssCrtntNtNnttnThrRfrnce() /** { "tree" :"EffectEvidenceSynthesis.certainty.note", "datatype" : "Annotation, Reference", "cardinality" : "Many", "elementtree" : ["addCertainty"] , "methodName" : "addNote, setAuthorReference"} **/
						, effectevidencesynthesis.getEffctvdncSnthssCrtntNtNnttnThrStrng() /** { "tree" :"EffectEvidenceSynthesis.certainty.note", "datatype" : "Annotation, string", "cardinality" : "Many", "elementtree" : ["addCertainty"] , "methodName" : "addNote, setAuthorString"} **/
						));
Effectevidencesynthesisobj.setType(HapiFHIRHelpers.createCodeableConcept(effectevidencesynthesis.getEffctvdncSnthssCrtntCrtntSbcmpnntTpCcCdngCSstm() /** { "tree" :"EffectEvidenceSynthesis.certainty.certaintySubcomponent.type", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : ["addCertainty", "addCertaintySubcomponent"] , "methodName" : "setType, addCoding, setSystem"} **/
						, effectevidencesynthesis.getEffctvdncSnthssCrtntCrtntSbcmpnntTpCcCdngCVrsn() /** { "tree" :"EffectEvidenceSynthesis.certainty.certaintySubcomponent.type", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addCertainty", "addCertaintySubcomponent"] , "methodName" : "setType, addCoding, setVersion"} **/
						, effectevidencesynthesis.getEffctvdncSnthssCrtntCrtntSbcmpnntTpCcCdngCCde() /** { "tree" :"EffectEvidenceSynthesis.certainty.certaintySubcomponent.type", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : ["addCertainty", "addCertaintySubcomponent"] , "methodName" : "setType, addCoding, setCode"} **/
						, effectevidencesynthesis.getEffctvdncSnthssCrtntCrtntSbcmpnntTpCcCdngCDsplay() /** { "tree" :"EffectEvidenceSynthesis.certainty.certaintySubcomponent.type", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addCertainty", "addCertaintySubcomponent"] , "methodName" : "setType, addCoding, setDisplay"} **/
						, effectevidencesynthesis.getEffctvdncSnthssCrtntCrtntSbcmpnntTpCcCdngCSrSlctd() /** { "tree" :"EffectEvidenceSynthesis.certainty.certaintySubcomponent.type", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : ["addCertainty", "addCertaintySubcomponent"] , "methodName" : "setType, addCoding, setUserSelected"} **/
						, effectevidencesynthesis.getEffctvdncSnthssCrtntCrtntSbcmpnntTpCcTxt() /** { "tree" :"EffectEvidenceSynthesis.certainty.certaintySubcomponent.type", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : ["addCertainty", "addCertaintySubcomponent"] , "methodName" : "setType, setText"} **/
						));
Effectevidencesynthesisobj.addRating(HapiFHIRHelpers.createCodeableConcept(effectevidencesynthesis.getEffctvdncSnthssCrtntCrtntSbcmpnntRtngCcCdngCSstm() /** { "tree" :"EffectEvidenceSynthesis.certainty.certaintySubcomponent.rating", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "Many", "elementtree" : ["addCertainty", "addCertaintySubcomponent"] , "methodName" : "addRating, addCoding, setSystem"} **/
						, effectevidencesynthesis.getEffctvdncSnthssCrtntCrtntSbcmpnntRtngCcCdngCVrsn() /** { "tree" :"EffectEvidenceSynthesis.certainty.certaintySubcomponent.rating", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Many", "elementtree" : ["addCertainty", "addCertaintySubcomponent"] , "methodName" : "addRating, addCoding, setVersion"} **/
						, effectevidencesynthesis.getEffctvdncSnthssCrtntCrtntSbcmpnntRtngCcCdngCCde() /** { "tree" :"EffectEvidenceSynthesis.certainty.certaintySubcomponent.rating", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "Many", "elementtree" : ["addCertainty", "addCertaintySubcomponent"] , "methodName" : "addRating, addCoding, setCode"} **/
						, effectevidencesynthesis.getEffctvdncSnthssCrtntCrtntSbcmpnntRtngCcCdngCDsplay() /** { "tree" :"EffectEvidenceSynthesis.certainty.certaintySubcomponent.rating", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Many", "elementtree" : ["addCertainty", "addCertaintySubcomponent"] , "methodName" : "addRating, addCoding, setDisplay"} **/
						, effectevidencesynthesis.getEffctvdncSnthssCrtntCrtntSbcmpnntRtngCcCdngCSrSlctd() /** { "tree" :"EffectEvidenceSynthesis.certainty.certaintySubcomponent.rating", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "Many", "elementtree" : ["addCertainty", "addCertaintySubcomponent"] , "methodName" : "addRating, addCoding, setUserSelected"} **/
						, effectevidencesynthesis.getEffctvdncSnthssCrtntCrtntSbcmpnntRtngCcTxt() /** { "tree" :"EffectEvidenceSynthesis.certainty.certaintySubcomponent.rating", "datatype" : "CodeableConcept, string", "cardinality" : "Many", "elementtree" : ["addCertainty", "addCertaintySubcomponent"] , "methodName" : "addRating, setText"} **/
						));
Effectevidencesynthesisobj.addNote(HapiFHIRHelpers.createAnnotation(effectevidencesynthesis.getEffctvdncSnthssCrtntCrtntSbcmpnntNtNnttnTme() /** { "tree" :"EffectEvidenceSynthesis.certainty.certaintySubcomponent.note", "datatype" : "Annotation, dateTime", "cardinality" : "Many", "elementtree" : ["addCertainty", "addCertaintySubcomponent"] , "methodName" : "addNote, setTime"} **/
						, effectevidencesynthesis.getEffctvdncSnthssCrtntCrtntSbcmpnntNtNnttnTxt() /** { "tree" :"EffectEvidenceSynthesis.certainty.certaintySubcomponent.note", "datatype" : "Annotation, markdown", "cardinality" : "Many", "elementtree" : ["addCertainty", "addCertaintySubcomponent"] , "methodName" : "addNote, setText"} **/
						, effectevidencesynthesis.getEffctvdncSnthssCrtntCrtntSbcmpnntNtNnttnThrRfrnce() /** { "tree" :"EffectEvidenceSynthesis.certainty.certaintySubcomponent.note", "datatype" : "Annotation, Reference", "cardinality" : "Many", "elementtree" : ["addCertainty", "addCertaintySubcomponent"] , "methodName" : "addNote, setAuthorReference"} **/
						, effectevidencesynthesis.getEffctvdncSnthssCrtntCrtntSbcmpnntNtNnttnThrStrng() /** { "tree" :"EffectEvidenceSynthesis.certainty.certaintySubcomponent.note", "datatype" : "Annotation, string", "cardinality" : "Many", "elementtree" : ["addCertainty", "addCertaintySubcomponent"] , "methodName" : "addNote, setAuthorString"} **/
		));
	}
}
