package main.templateoutput.Conversions;
// Generated on Jan 28, 2022, 8:02:40 AM 


import org.hl7.fhir.r4.model.Patient;

/**
 *  object for conversion model class Evidencevariable.
 * @see .Evidencevariable
 * @author Paul Kovach
 */
import main.java.com.campfhir.service.conversion.HapiFHIRHelpers;

public class EvidencevariableConversion 
{
	public Patient Evidencevariables(main.templateoutput.Model.Evidencevariable evidencevariable) 
	{
			Patient  Evidencevariableobj = new Patient(); 

						Evidencevariableobj.setUrl(HapiFHIRHelpers.createuri(evidencevariable.getEvUrlUri() /** { "tree" :"EvidenceVariable.url", "datatype" : "uri", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setUrl"} **/
						));
Evidencevariableobj.addIdentifier(HapiFHIRHelpers.createIdentifier(evidencevariable.getEvIdentifierIdentifierUse() /** { "tree" :"EvidenceVariable.identifier", "datatype" : "Identifier, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setUse"} **/
						, evidencevariable.getEvDntfrDntfrTpCcCSstm() /** { "tree" :"EvidenceVariable.identifier", "datatype" : "Identifier, CodeableConcept, Coding, uri", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setType, addCoding, setSystem"} **/
						, evidencevariable.getEvDntfrDntfrTpCcCVrsn() /** { "tree" :"EvidenceVariable.identifier", "datatype" : "Identifier, CodeableConcept, Coding, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setType, addCoding, setVersion"} **/
						, evidencevariable.getEvDntfrDntfrTpCcCCde() /** { "tree" :"EvidenceVariable.identifier", "datatype" : "Identifier, CodeableConcept, Coding, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setType, addCoding, setCode"} **/
						, evidencevariable.getEvDntfrDntfrTpCcCDsplay() /** { "tree" :"EvidenceVariable.identifier", "datatype" : "Identifier, CodeableConcept, Coding, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setType, addCoding, setDisplay"} **/
						, evidencevariable.getEvDntfrDntfrTpCcCSrSlctd() /** { "tree" :"EvidenceVariable.identifier", "datatype" : "Identifier, CodeableConcept, Coding, boolean", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setType, addCoding, setUserSelected"} **/
						, evidencevariable.getEvDntfrDntfrTpCcTxt() /** { "tree" :"EvidenceVariable.identifier", "datatype" : "Identifier, CodeableConcept, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setType, setText"} **/
						, evidencevariable.getEvDntfrDntfrPrdPrdStrt() /** { "tree" :"EvidenceVariable.identifier", "datatype" : "Identifier, Period, dateTime", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setPeriod, setStart"} **/
						, evidencevariable.getEvDntfrDntfrPrdPrdNd() /** { "tree" :"EvidenceVariable.identifier", "datatype" : "Identifier, Period, dateTime", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setPeriod, setEnd"} **/
						, evidencevariable.getEvIdentifierIdentifierAssigner() /** { "tree" :"EvidenceVariable.identifier", "datatype" : "Identifier, Reference", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setAssigner"} **/
						, evidencevariable.getEvIdentifierIdentifierValue() /** { "tree" :"EvidenceVariable.identifier", "datatype" : "Identifier, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setValue"} **/
						, evidencevariable.getEvIdentifierIdentifierSystem() /** { "tree" :"EvidenceVariable.identifier", "datatype" : "Identifier, uri", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setSystem"} **/
						));
Evidencevariableobj.setVersion(HapiFHIRHelpers.createstring(evidencevariable.getEvVersionString() /** { "tree" :"EvidenceVariable.version", "datatype" : "string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setVersion"} **/
						));
Evidencevariableobj.setName(HapiFHIRHelpers.createstring(evidencevariable.getEvNameString() /** { "tree" :"EvidenceVariable.name", "datatype" : "string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setName"} **/
						));
Evidencevariableobj.setTitle(HapiFHIRHelpers.createstring(evidencevariable.getEvTitleString() /** { "tree" :"EvidenceVariable.title", "datatype" : "string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setTitle"} **/
						));
Evidencevariableobj.setShortTitle(HapiFHIRHelpers.createstring(evidencevariable.getEvShortTitleString() /** { "tree" :"EvidenceVariable.shortTitle", "datatype" : "string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setShortTitle"} **/
						));
Evidencevariableobj.setSubtitle(HapiFHIRHelpers.createstring(evidencevariable.getEvSubtitleString() /** { "tree" :"EvidenceVariable.subtitle", "datatype" : "string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setSubtitle"} **/
						));
Evidencevariableobj.setStatus(HapiFHIRHelpers.createcode(evidencevariable.getEvStatusCode() /** { "tree" :"EvidenceVariable.status", "datatype" : "code", "cardinality" : "Required", "elementtree" : [] , "methodName" : "setStatus"} **/
						));
Evidencevariableobj.setDate(HapiFHIRHelpers.createdateTime(evidencevariable.getEvDateDateTime() /** { "tree" :"EvidenceVariable.date", "datatype" : "dateTime", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setDate"} **/
						));
Evidencevariableobj.setPublisher(HapiFHIRHelpers.createstring(evidencevariable.getEvPublisherString() /** { "tree" :"EvidenceVariable.publisher", "datatype" : "string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setPublisher"} **/
						));
Evidencevariableobj.addContact(HapiFHIRHelpers.createContactDetail(evidencevariable.getEvCntctCntctDtlTlcmCntctPntPrdStrt() /** { "tree" :"EvidenceVariable.contact", "datatype" : "ContactDetail, ContactPoint, Period, dateTime", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addContact, setTelecom, setPeriod, setStart"} **/
						, evidencevariable.getEvCntctCntctDtlTlcmCntctPntPrdNd() /** { "tree" :"EvidenceVariable.contact", "datatype" : "ContactDetail, ContactPoint, Period, dateTime", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addContact, setTelecom, setPeriod, setEnd"} **/
						, evidencevariable.getEvCntctCntctDtlTlcmCntctPntSstm() /** { "tree" :"EvidenceVariable.contact", "datatype" : "ContactDetail, ContactPoint, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addContact, setTelecom, setSystem"} **/
						, evidencevariable.getEvCntctCntctDtlTlcmCntctPntVlue() /** { "tree" :"EvidenceVariable.contact", "datatype" : "ContactDetail, ContactPoint, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addContact, setTelecom, setValue"} **/
						, evidencevariable.getEvCntctCntctDtlTlcmCntctPntSe() /** { "tree" :"EvidenceVariable.contact", "datatype" : "ContactDetail, ContactPoint, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addContact, setTelecom, setUse"} **/
						, evidencevariable.getEvCntctCntctDtlTlcmCntctPntRnk() /** { "tree" :"EvidenceVariable.contact", "datatype" : "ContactDetail, ContactPoint, positiveInt", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addContact, setTelecom, setRank"} **/
						, evidencevariable.getEvContactContactDetailName() /** { "tree" :"EvidenceVariable.contact", "datatype" : "ContactDetail, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addContact, addName"} **/
						));
Evidencevariableobj.setDescription(HapiFHIRHelpers.createmarkdown(evidencevariable.getEvDescriptionMarkdown() /** { "tree" :"EvidenceVariable.description", "datatype" : "markdown", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setDescription"} **/
						));
Evidencevariableobj.addNote(HapiFHIRHelpers.createAnnotation(evidencevariable.getEvNoteAnnotationTime() /** { "tree" :"EvidenceVariable.note", "datatype" : "Annotation, dateTime", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addNote, setTime"} **/
						, evidencevariable.getEvNoteAnnotationText() /** { "tree" :"EvidenceVariable.note", "datatype" : "Annotation, markdown", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addNote, setText"} **/
						, evidencevariable.getEvNoteAnnotationAuthorReference() /** { "tree" :"EvidenceVariable.note", "datatype" : "Annotation, Reference", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addNote, setAuthorReference"} **/
						, evidencevariable.getEvNoteAnnotationAuthorString() /** { "tree" :"EvidenceVariable.note", "datatype" : "Annotation, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addNote, setAuthorString"} **/
						));
Evidencevariableobj.addUseContext(HapiFHIRHelpers.createUsageContext(evidencevariable.getEvSCntxtSgCntxtVlCcCcCSstm() /** { "tree" :"EvidenceVariable.useContext", "datatype" : "UsageContext, CodeableConcept, Coding, uri", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addUseContext, addValueCodeableConcept, addCoding, setSystem"} **/
						, evidencevariable.getEvSCntxtSgCntxtVlCcCcCVrsn() /** { "tree" :"EvidenceVariable.useContext", "datatype" : "UsageContext, CodeableConcept, Coding, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addUseContext, addValueCodeableConcept, addCoding, setVersion"} **/
						, evidencevariable.getEvSCntxtSgCntxtVlCcCcCCde() /** { "tree" :"EvidenceVariable.useContext", "datatype" : "UsageContext, CodeableConcept, Coding, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addUseContext, addValueCodeableConcept, addCoding, setCode"} **/
						, evidencevariable.getEvSCntxtSgCntxtVlCcCcCDsplay() /** { "tree" :"EvidenceVariable.useContext", "datatype" : "UsageContext, CodeableConcept, Coding, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addUseContext, addValueCodeableConcept, addCoding, setDisplay"} **/
						, evidencevariable.getEvSCntxtSgCntxtVlCcCcCSrSlctd() /** { "tree" :"EvidenceVariable.useContext", "datatype" : "UsageContext, CodeableConcept, Coding, boolean", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addUseContext, addValueCodeableConcept, addCoding, setUserSelected"} **/
						, evidencevariable.getEvSCntxtSgCntxtVlCcCcTxt() /** { "tree" :"EvidenceVariable.useContext", "datatype" : "UsageContext, CodeableConcept, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addUseContext, addValueCodeableConcept, setText"} **/
						, evidencevariable.getEvSCntxtSgCntxtCdCSstm() /** { "tree" :"EvidenceVariable.useContext", "datatype" : "UsageContext, Coding, uri", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addUseContext, addCode, setSystem"} **/
						, evidencevariable.getEvSCntxtSgCntxtCdCVrsn() /** { "tree" :"EvidenceVariable.useContext", "datatype" : "UsageContext, Coding, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addUseContext, addCode, setVersion"} **/
						, evidencevariable.getEvSCntxtSgCntxtCdCCde() /** { "tree" :"EvidenceVariable.useContext", "datatype" : "UsageContext, Coding, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addUseContext, addCode, setCode"} **/
						, evidencevariable.getEvSCntxtSgCntxtCdCDsplay() /** { "tree" :"EvidenceVariable.useContext", "datatype" : "UsageContext, Coding, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addUseContext, addCode, setDisplay"} **/
						, evidencevariable.getEvSCntxtSgCntxtCdCSrSlctd() /** { "tree" :"EvidenceVariable.useContext", "datatype" : "UsageContext, Coding, boolean", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addUseContext, addCode, setUserSelected"} **/
						, evidencevariable.getEvSCntxtSgCntxtVlQnttQnttVlue() /** { "tree" :"EvidenceVariable.useContext", "datatype" : "UsageContext, Quantity, decimal", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addUseContext, addValueQuantity, setValue"} **/
						, evidencevariable.getEvSCntxtSgCntxtVlQnttQnttCmprtr() /** { "tree" :"EvidenceVariable.useContext", "datatype" : "UsageContext, Quantity, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addUseContext, addValueQuantity, setComparator"} **/
						, evidencevariable.getEvSCntxtSgCntxtVlQnttQnttNt() /** { "tree" :"EvidenceVariable.useContext", "datatype" : "UsageContext, Quantity, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addUseContext, addValueQuantity, setUnit"} **/
						, evidencevariable.getEvSCntxtSgCntxtVlQnttQnttSstm() /** { "tree" :"EvidenceVariable.useContext", "datatype" : "UsageContext, Quantity, uri", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addUseContext, addValueQuantity, setSystem"} **/
						, evidencevariable.getEvSCntxtSgCntxtVlQnttQnttCde() /** { "tree" :"EvidenceVariable.useContext", "datatype" : "UsageContext, Quantity, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addUseContext, addValueQuantity, setCode"} **/
						, evidencevariable.getEvSCntxtSgCntxtVlRngRngLw() /** { "tree" :"EvidenceVariable.useContext", "datatype" : "UsageContext, Range, SimpleQuantity", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addUseContext, addValueRange, setLow"} **/
						, evidencevariable.getEvSCntxtSgCntxtVlRngRngHgh() /** { "tree" :"EvidenceVariable.useContext", "datatype" : "UsageContext, Range, SimpleQuantity", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addUseContext, addValueRange, setHigh"} **/
						, evidencevariable.getEvSCntxtSgCntxtVlRfrnce() /** { "tree" :"EvidenceVariable.useContext", "datatype" : "UsageContext, Reference", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addUseContext, addValueReference"} **/
						));
Evidencevariableobj.addJurisdiction(HapiFHIRHelpers.createCodeableConcept(evidencevariable.getEvJurisdictionCcCodingCSystem() /** { "tree" :"EvidenceVariable.jurisdiction", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addJurisdiction, addCoding, setSystem"} **/
						, evidencevariable.getEvJrsdctnCcCdngCVrsn() /** { "tree" :"EvidenceVariable.jurisdiction", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addJurisdiction, addCoding, setVersion"} **/
						, evidencevariable.getEvJurisdictionCcCodingCCode() /** { "tree" :"EvidenceVariable.jurisdiction", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addJurisdiction, addCoding, setCode"} **/
						, evidencevariable.getEvJrsdctnCcCdngCDsplay() /** { "tree" :"EvidenceVariable.jurisdiction", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addJurisdiction, addCoding, setDisplay"} **/
						, evidencevariable.getEvJrsdctnCcCdngCSrSlctd() /** { "tree" :"EvidenceVariable.jurisdiction", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addJurisdiction, addCoding, setUserSelected"} **/
						, evidencevariable.getEvJurisdictionCcText() /** { "tree" :"EvidenceVariable.jurisdiction", "datatype" : "CodeableConcept, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addJurisdiction, setText"} **/
						));
Evidencevariableobj.setCopyright(HapiFHIRHelpers.createmarkdown(evidencevariable.getEvCopyrightMarkdown() /** { "tree" :"EvidenceVariable.copyright", "datatype" : "markdown", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setCopyright"} **/
						));
Evidencevariableobj.setApprovalDate(HapiFHIRHelpers.createdate(evidencevariable.getEvApprovalDateDate() /** { "tree" :"EvidenceVariable.approvalDate", "datatype" : "date", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setApprovalDate"} **/
						));
Evidencevariableobj.setLastReviewDate(HapiFHIRHelpers.createdate(evidencevariable.getEvLastReviewDateDate() /** { "tree" :"EvidenceVariable.lastReviewDate", "datatype" : "date", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setLastReviewDate"} **/
						));
Evidencevariableobj.setEffectivePeriod(HapiFHIRHelpers.createPeriod(evidencevariable.getEvEffectivePeriodPeriodStart() /** { "tree" :"EvidenceVariable.effectivePeriod", "datatype" : "Period, dateTime", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setEffectivePeriod, setStart"} **/
						, evidencevariable.getEvEffectivePeriodPeriodEnd() /** { "tree" :"EvidenceVariable.effectivePeriod", "datatype" : "Period, dateTime", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setEffectivePeriod, setEnd"} **/
						));
Evidencevariableobj.addTopic(HapiFHIRHelpers.createCodeableConcept(evidencevariable.getEvTopicCcCodingCSystem() /** { "tree" :"EvidenceVariable.topic", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addTopic, addCoding, setSystem"} **/
						, evidencevariable.getEvTopicCcCodingCVersion() /** { "tree" :"EvidenceVariable.topic", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addTopic, addCoding, setVersion"} **/
						, evidencevariable.getEvTopicCcCodingCCode() /** { "tree" :"EvidenceVariable.topic", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addTopic, addCoding, setCode"} **/
						, evidencevariable.getEvTopicCcCodingCDisplay() /** { "tree" :"EvidenceVariable.topic", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addTopic, addCoding, setDisplay"} **/
						, evidencevariable.getEvTopicCcCodingCUserSelected() /** { "tree" :"EvidenceVariable.topic", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addTopic, addCoding, setUserSelected"} **/
						, evidencevariable.getEvTopicCcText() /** { "tree" :"EvidenceVariable.topic", "datatype" : "CodeableConcept, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addTopic, setText"} **/
						));
Evidencevariableobj.addAuthor(HapiFHIRHelpers.createContactDetail(evidencevariable.getEvThrCntctDtlTlcmCntctPntPrdStrt() /** { "tree" :"EvidenceVariable.author", "datatype" : "ContactDetail, ContactPoint, Period, dateTime", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addAuthor, setTelecom, setPeriod, setStart"} **/
						, evidencevariable.getEvThrCntctDtlTlcmCntctPntPrdNd() /** { "tree" :"EvidenceVariable.author", "datatype" : "ContactDetail, ContactPoint, Period, dateTime", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addAuthor, setTelecom, setPeriod, setEnd"} **/
						, evidencevariable.getEvThrCntctDtlTlcmCntctPntSstm() /** { "tree" :"EvidenceVariable.author", "datatype" : "ContactDetail, ContactPoint, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addAuthor, setTelecom, setSystem"} **/
						, evidencevariable.getEvThrCntctDtlTlcmCntctPntVlue() /** { "tree" :"EvidenceVariable.author", "datatype" : "ContactDetail, ContactPoint, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addAuthor, setTelecom, setValue"} **/
						, evidencevariable.getEvThrCntctDtlTlcmCntctPntSe() /** { "tree" :"EvidenceVariable.author", "datatype" : "ContactDetail, ContactPoint, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addAuthor, setTelecom, setUse"} **/
						, evidencevariable.getEvThrCntctDtlTlcmCntctPntRnk() /** { "tree" :"EvidenceVariable.author", "datatype" : "ContactDetail, ContactPoint, positiveInt", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addAuthor, setTelecom, setRank"} **/
						, evidencevariable.getEvAuthorContactDetailName() /** { "tree" :"EvidenceVariable.author", "datatype" : "ContactDetail, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addAuthor, addName"} **/
						));
Evidencevariableobj.addEditor(HapiFHIRHelpers.createContactDetail(evidencevariable.getEvDtrCntctDtlTlcmCntctPntPrdStrt() /** { "tree" :"EvidenceVariable.editor", "datatype" : "ContactDetail, ContactPoint, Period, dateTime", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addEditor, setTelecom, setPeriod, setStart"} **/
						, evidencevariable.getEvDtrCntctDtlTlcmCntctPntPrdNd() /** { "tree" :"EvidenceVariable.editor", "datatype" : "ContactDetail, ContactPoint, Period, dateTime", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addEditor, setTelecom, setPeriod, setEnd"} **/
						, evidencevariable.getEvDtrCntctDtlTlcmCntctPntSstm() /** { "tree" :"EvidenceVariable.editor", "datatype" : "ContactDetail, ContactPoint, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addEditor, setTelecom, setSystem"} **/
						, evidencevariable.getEvDtrCntctDtlTlcmCntctPntVlue() /** { "tree" :"EvidenceVariable.editor", "datatype" : "ContactDetail, ContactPoint, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addEditor, setTelecom, setValue"} **/
						, evidencevariable.getEvDtrCntctDtlTlcmCntctPntSe() /** { "tree" :"EvidenceVariable.editor", "datatype" : "ContactDetail, ContactPoint, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addEditor, setTelecom, setUse"} **/
						, evidencevariable.getEvDtrCntctDtlTlcmCntctPntRnk() /** { "tree" :"EvidenceVariable.editor", "datatype" : "ContactDetail, ContactPoint, positiveInt", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addEditor, setTelecom, setRank"} **/
						, evidencevariable.getEvEditorContactDetailName() /** { "tree" :"EvidenceVariable.editor", "datatype" : "ContactDetail, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addEditor, addName"} **/
						));
Evidencevariableobj.addReviewer(HapiFHIRHelpers.createContactDetail(evidencevariable.getEvRvwrCntctDtlTlcmCntctPntPrdStrt() /** { "tree" :"EvidenceVariable.reviewer", "datatype" : "ContactDetail, ContactPoint, Period, dateTime", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addReviewer, setTelecom, setPeriod, setStart"} **/
						, evidencevariable.getEvRvwrCntctDtlTlcmCntctPntPrdNd() /** { "tree" :"EvidenceVariable.reviewer", "datatype" : "ContactDetail, ContactPoint, Period, dateTime", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addReviewer, setTelecom, setPeriod, setEnd"} **/
						, evidencevariable.getEvRvwrCntctDtlTlcmCntctPntSstm() /** { "tree" :"EvidenceVariable.reviewer", "datatype" : "ContactDetail, ContactPoint, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addReviewer, setTelecom, setSystem"} **/
						, evidencevariable.getEvRvwrCntctDtlTlcmCntctPntVlue() /** { "tree" :"EvidenceVariable.reviewer", "datatype" : "ContactDetail, ContactPoint, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addReviewer, setTelecom, setValue"} **/
						, evidencevariable.getEvRvwrCntctDtlTlcmCntctPntSe() /** { "tree" :"EvidenceVariable.reviewer", "datatype" : "ContactDetail, ContactPoint, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addReviewer, setTelecom, setUse"} **/
						, evidencevariable.getEvRvwrCntctDtlTlcmCntctPntRnk() /** { "tree" :"EvidenceVariable.reviewer", "datatype" : "ContactDetail, ContactPoint, positiveInt", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addReviewer, setTelecom, setRank"} **/
						, evidencevariable.getEvReviewerContactDetailName() /** { "tree" :"EvidenceVariable.reviewer", "datatype" : "ContactDetail, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addReviewer, addName"} **/
						));
Evidencevariableobj.addEndorser(HapiFHIRHelpers.createContactDetail(evidencevariable.getEvNdrsrCntctDtlTlcmCntctPntPrdStrt() /** { "tree" :"EvidenceVariable.endorser", "datatype" : "ContactDetail, ContactPoint, Period, dateTime", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addEndorser, setTelecom, setPeriod, setStart"} **/
						, evidencevariable.getEvNdrsrCntctDtlTlcmCntctPntPrdNd() /** { "tree" :"EvidenceVariable.endorser", "datatype" : "ContactDetail, ContactPoint, Period, dateTime", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addEndorser, setTelecom, setPeriod, setEnd"} **/
						, evidencevariable.getEvNdrsrCntctDtlTlcmCntctPntSstm() /** { "tree" :"EvidenceVariable.endorser", "datatype" : "ContactDetail, ContactPoint, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addEndorser, setTelecom, setSystem"} **/
						, evidencevariable.getEvNdrsrCntctDtlTlcmCntctPntVlue() /** { "tree" :"EvidenceVariable.endorser", "datatype" : "ContactDetail, ContactPoint, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addEndorser, setTelecom, setValue"} **/
						, evidencevariable.getEvNdrsrCntctDtlTlcmCntctPntSe() /** { "tree" :"EvidenceVariable.endorser", "datatype" : "ContactDetail, ContactPoint, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addEndorser, setTelecom, setUse"} **/
						, evidencevariable.getEvNdrsrCntctDtlTlcmCntctPntRnk() /** { "tree" :"EvidenceVariable.endorser", "datatype" : "ContactDetail, ContactPoint, positiveInt", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addEndorser, setTelecom, setRank"} **/
						, evidencevariable.getEvEndorserContactDetailName() /** { "tree" :"EvidenceVariable.endorser", "datatype" : "ContactDetail, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addEndorser, addName"} **/
						));
Evidencevariableobj.addRelatedArtifact(HapiFHIRHelpers.createRelatedArtifact(evidencevariable.getEvRltdrtfctRltdrtfctDcmntTtchmntCntntTpe() /** { "tree" :"EvidenceVariable.relatedArtifact", "datatype" : "RelatedArtifact, Attachment, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addRelatedArtifact, setDocument, setContentType"} **/
						, evidencevariable.getEvRltdrtfctRltdrtfctDcmntTtchmntLngge() /** { "tree" :"EvidenceVariable.relatedArtifact", "datatype" : "RelatedArtifact, Attachment, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addRelatedArtifact, setDocument, setLanguage"} **/
						, evidencevariable.getEvRltdrtfctRltdrtfctDcmntTtchmntDta() /** { "tree" :"EvidenceVariable.relatedArtifact", "datatype" : "RelatedArtifact, Attachment, base64Binary", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addRelatedArtifact, setDocument, setData"} **/
						, evidencevariable.getEvRltdrtfctRltdrtfctDcmntTtchmntRl() /** { "tree" :"EvidenceVariable.relatedArtifact", "datatype" : "RelatedArtifact, Attachment, url", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addRelatedArtifact, setDocument, setUrl"} **/
						, evidencevariable.getEvRltdrtfctRltdrtfctDcmntTtchmntSze() /** { "tree" :"EvidenceVariable.relatedArtifact", "datatype" : "RelatedArtifact, Attachment, unsignedInt", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addRelatedArtifact, setDocument, setSize"} **/
						, evidencevariable.getEvRltdrtfctRltdrtfctDcmntTtchmntHsh() /** { "tree" :"EvidenceVariable.relatedArtifact", "datatype" : "RelatedArtifact, Attachment, base64Binary", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addRelatedArtifact, setDocument, setHash"} **/
						, evidencevariable.getEvRltdrtfctRltdrtfctDcmntTtchmntTtle() /** { "tree" :"EvidenceVariable.relatedArtifact", "datatype" : "RelatedArtifact, Attachment, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addRelatedArtifact, setDocument, setTitle"} **/
						, evidencevariable.getEvRltdrtfctRltdrtfctDcmntTtchmntCrtn() /** { "tree" :"EvidenceVariable.relatedArtifact", "datatype" : "RelatedArtifact, Attachment, dateTime", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addRelatedArtifact, setDocument, setCreation"} **/
						, evidencevariable.getEvRltdrtfctRltdrtfctRsrce() /** { "tree" :"EvidenceVariable.relatedArtifact", "datatype" : "RelatedArtifact, canonical", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addRelatedArtifact, setResource"} **/
						, evidencevariable.getEvRltdrtfctRltdrtfctTpe() /** { "tree" :"EvidenceVariable.relatedArtifact", "datatype" : "RelatedArtifact, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addRelatedArtifact, setType"} **/
						, evidencevariable.getEvRltdrtfctRltdrtfctCttn() /** { "tree" :"EvidenceVariable.relatedArtifact", "datatype" : "RelatedArtifact, markdown", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addRelatedArtifact, setCitation"} **/
						, evidencevariable.getEvRltdrtfctRltdrtfctLbl() /** { "tree" :"EvidenceVariable.relatedArtifact", "datatype" : "RelatedArtifact, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addRelatedArtifact, setLabel"} **/
						, evidencevariable.getEvRltdrtfctRltdrtfctDsplay() /** { "tree" :"EvidenceVariable.relatedArtifact", "datatype" : "RelatedArtifact, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addRelatedArtifact, setDisplay"} **/
						, evidencevariable.getEvRltdrtfctRltdrtfctRl() /** { "tree" :"EvidenceVariable.relatedArtifact", "datatype" : "RelatedArtifact, url", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addRelatedArtifact, setUrl"} **/
						));
Evidencevariableobj.setType(HapiFHIRHelpers.createcode(evidencevariable.getEvTypeCode() /** { "tree" :"EvidenceVariable.type", "datatype" : "code", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setType"} **/
						));
Evidencevariableobj.setDescription(HapiFHIRHelpers.createstring(evidencevariable.getEvChrctrDescriptionString() /** { "tree" :"EvidenceVariable.characteristic.description", "datatype" : "string", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setDescription"} **/
						));
Evidencevariableobj.setDefinitionReference(group)(HapiFHIRHelpers.createReference(evidencevariable.getEvChrctrDfntnRfrncRfrnce() /** { "tree" :"EvidenceVariable.characteristic.definitionReference", "datatype" : "Reference", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionReference(group)"} **/
						));
Evidencevariableobj.setDefinitionCanonical(activitydefinition)(HapiFHIRHelpers.createcanonical(evidencevariable.getEvChrctrDfntnCnnclCnncl() /** { "tree" :"EvidenceVariable.characteristic.definitionCanonical", "datatype" : "canonical", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionCanonical(activitydefinition)"} **/
						));
Evidencevariableobj.setDefinitionCodeableconcept(HapiFHIRHelpers.createCodeableConcept(evidencevariable.getEvChrctrDfntnCdblcncptCcCdngCSstm() /** { "tree" :"EvidenceVariable.characteristic.definitionCodeableconcept", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionCodeableconcept, addCoding, setSystem"} **/
						, evidencevariable.getEvChrctrDfntnCdblcncptCcCdngCVrsn() /** { "tree" :"EvidenceVariable.characteristic.definitionCodeableconcept", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionCodeableconcept, addCoding, setVersion"} **/
						, evidencevariable.getEvChrctrDfntnCdblcncptCcCdngCCde() /** { "tree" :"EvidenceVariable.characteristic.definitionCodeableconcept", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionCodeableconcept, addCoding, setCode"} **/
						, evidencevariable.getEvChrctrDfntnCdblcncptCcCdngCDsplay() /** { "tree" :"EvidenceVariable.characteristic.definitionCodeableconcept", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionCodeableconcept, addCoding, setDisplay"} **/
						, evidencevariable.getEvChrctrDfntnCdblcncptCcCdngCSrSlctd() /** { "tree" :"EvidenceVariable.characteristic.definitionCodeableconcept", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionCodeableconcept, addCoding, setUserSelected"} **/
						, evidencevariable.getEvChrctrDfntnCdblcncptCcTxt() /** { "tree" :"EvidenceVariable.characteristic.definitionCodeableconcept", "datatype" : "CodeableConcept, string", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionCodeableconcept, setText"} **/
						));
Evidencevariableobj.setDefinitionExpression(HapiFHIRHelpers.createExpression(evidencevariable.getEvChrctrDfntnxprssnXprssnLngge() /** { "tree" :"EvidenceVariable.characteristic.definitionExpression", "datatype" : "Expression, code", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionExpression, setLanguage"} **/
						, evidencevariable.getEvChrctrDfntnxprssnXprssnNme() /** { "tree" :"EvidenceVariable.characteristic.definitionExpression", "datatype" : "Expression, id", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionExpression, setName"} **/
						, evidencevariable.getEvChrctrDfntnxprssnXprssnDscrptn() /** { "tree" :"EvidenceVariable.characteristic.definitionExpression", "datatype" : "Expression, string", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionExpression, setDescription"} **/
						, evidencevariable.getEvChrctrDfntnxprssnXprssnXprssn() /** { "tree" :"EvidenceVariable.characteristic.definitionExpression", "datatype" : "Expression, string", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionExpression, setExpression"} **/
						, evidencevariable.getEvChrctrDfntnxprssnXprssnRfrnce() /** { "tree" :"EvidenceVariable.characteristic.definitionExpression", "datatype" : "Expression, uri", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionExpression, setReference"} **/
						));
Evidencevariableobj.setDefinitionDatarequirement(HapiFHIRHelpers.createDataRequirement(evidencevariable.getEvChrctrDfntnDtrqrmntDtRqrmntPrfle() /** { "tree" :"EvidenceVariable.characteristic.definitionDatarequirement", "datatype" : "DataRequirement, canonical", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionDatarequirement, addProfile"} **/
						, evidencevariable.getEvChrctrDfntnDtrqrmntDtRqrmntTpe() /** { "tree" :"EvidenceVariable.characteristic.definitionDatarequirement", "datatype" : "DataRequirement, code", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionDatarequirement, setType"} **/
						, evidencevariable.getEvChrctrDfntnDtrqrmntDtRqrmntSbjctCcCcCSstm() /** { "tree" :"EvidenceVariable.characteristic.definitionDatarequirement", "datatype" : "DataRequirement, CodeableConcept, Coding, uri", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionDatarequirement, setSubjectCodeableConcept, addCoding, setSystem"} **/
						, evidencevariable.getEvChrctrDfntnDtrqrmntDtRqrmntSbjctCcCcCVrsn() /** { "tree" :"EvidenceVariable.characteristic.definitionDatarequirement", "datatype" : "DataRequirement, CodeableConcept, Coding, string", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionDatarequirement, setSubjectCodeableConcept, addCoding, setVersion"} **/
						, evidencevariable.getEvChrctrDfntnDtrqrmntDtRqrmntSbjctCcCcCCde() /** { "tree" :"EvidenceVariable.characteristic.definitionDatarequirement", "datatype" : "DataRequirement, CodeableConcept, Coding, code", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionDatarequirement, setSubjectCodeableConcept, addCoding, setCode"} **/
						, evidencevariable.getEvChrctrDfntnDtrqrmntDtRqrmntSbjctCcCcCDsplay() /** { "tree" :"EvidenceVariable.characteristic.definitionDatarequirement", "datatype" : "DataRequirement, CodeableConcept, Coding, string", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionDatarequirement, setSubjectCodeableConcept, addCoding, setDisplay"} **/
						, evidencevariable.getEvChrctrDfntnDtrqrmntDtRqrmntSbjctCcCcCSrSlctd() /** { "tree" :"EvidenceVariable.characteristic.definitionDatarequirement", "datatype" : "DataRequirement, CodeableConcept, Coding, boolean", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionDatarequirement, setSubjectCodeableConcept, addCoding, setUserSelected"} **/
						, evidencevariable.getEvChrctrDfntnDtrqrmntDtRqrmntSbjctCcCcTxt() /** { "tree" :"EvidenceVariable.characteristic.definitionDatarequirement", "datatype" : "DataRequirement, CodeableConcept, string", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionDatarequirement, setSubjectCodeableConcept, setText"} **/
						, evidencevariable.getEvChrctrDfntnDtrqrmntDtRqrmntCdFltrVlSt() /** { "tree" :"EvidenceVariable.characteristic.definitionDatarequirement", "datatype" : "DataRequirement, Element, canonical", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionDatarequirement, addCodeFilter, setValueSet"} **/
						, evidencevariable.getEvChrctrDfntnDtrqrmntDtRqrmntSrtDrctn() /** { "tree" :"EvidenceVariable.characteristic.definitionDatarequirement", "datatype" : "DataRequirement, code", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionDatarequirement, addSort, setDirection"} **/
						, evidencevariable.getEvChrctrDfntnDtrqrmntDtRqrmntCdFltrCde() /** { "tree" :"EvidenceVariable.characteristic.definitionDatarequirement", "datatype" : "DataRequirement, Element, Coding", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionDatarequirement, addCodeFilter, addCode"} **/
						, evidencevariable.getEvChrctrDfntnDtrqrmntDtRqrmntDtFltrVlDtTme() /** { "tree" :"EvidenceVariable.characteristic.definitionDatarequirement", "datatype" : "DataRequirement, Element, dateTime", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionDatarequirement, addDateFilter, setValueDateTime"} **/
						, evidencevariable.getEvChrctrDfntnDtrqrmntDtRqrmntDtFltrVlDrtn() /** { "tree" :"EvidenceVariable.characteristic.definitionDatarequirement", "datatype" : "DataRequirement, Element, Duration", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionDatarequirement, addDateFilter, setValueDuration"} **/
						, evidencevariable.getEvChrctrDfntnDtrqrmntDtRqrmntDtFltrVlPrd() /** { "tree" :"EvidenceVariable.characteristic.definitionDatarequirement", "datatype" : "DataRequirement, Element, Period", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionDatarequirement, addDateFilter, setValuePeriod"} **/
						, evidencevariable.getEvChrctrDfntnDtrqrmntDtRqrmntCdFltrPth() /** { "tree" :"EvidenceVariable.characteristic.definitionDatarequirement", "datatype" : "DataRequirement, Element, string", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionDatarequirement, addCodeFilter, setPath"} **/
						, evidencevariable.getEvChrctrDfntnDtrqrmntDtRqrmntCdFltrSrchPrm() /** { "tree" :"EvidenceVariable.characteristic.definitionDatarequirement", "datatype" : "DataRequirement, Element, string", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionDatarequirement, addCodeFilter, setSearchParam"} **/
						, evidencevariable.getEvChrctrDfntnDtrqrmntDtRqrmntDtFltrPth() /** { "tree" :"EvidenceVariable.characteristic.definitionDatarequirement", "datatype" : "DataRequirement, Element, string", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionDatarequirement, addDateFilter, setPath"} **/
						, evidencevariable.getEvChrctrDfntnDtrqrmntDtRqrmntDtFltrSrchPrm() /** { "tree" :"EvidenceVariable.characteristic.definitionDatarequirement", "datatype" : "DataRequirement, Element, string", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionDatarequirement, addDateFilter, setSearchParam"} **/
						, evidencevariable.getEvChrctrDfntnDtrqrmntDtRqrmntSrtPth() /** { "tree" :"EvidenceVariable.characteristic.definitionDatarequirement", "datatype" : "DataRequirement, string", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionDatarequirement, addSort, setPath"} **/
						, evidencevariable.getEvChrctrDfntnDtrqrmntDtRqrmntLmt() /** { "tree" :"EvidenceVariable.characteristic.definitionDatarequirement", "datatype" : "DataRequirement, positiveInt", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionDatarequirement, setLimit"} **/
						, evidencevariable.getEvChrctrDfntnDtrqrmntDtRqrmntSbjctRfrnce() /** { "tree" :"EvidenceVariable.characteristic.definitionDatarequirement", "datatype" : "DataRequirement, Reference", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionDatarequirement, setSubjectReference"} **/
						, evidencevariable.getEvChrctrDfntnDtrqrmntDtRqrmntMstSpprt() /** { "tree" :"EvidenceVariable.characteristic.definitionDatarequirement", "datatype" : "DataRequirement, string", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionDatarequirement, addMustSupport"} **/
						));
Evidencevariableobj.setDefinitionTriggerdefinition(HapiFHIRHelpers.createTriggerDefinition(evidencevariable.getEvChrctrDfntnTrggrdfntnTrggrDfntnTpe() /** { "tree" :"EvidenceVariable.characteristic.definitionTriggerdefinition", "datatype" : "TriggerDefinition, code", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionTriggerdefinition, addType"} **/
						, evidencevariable.getEvChrctrDfntnTrggrdfntnTrggrDfntnDtDtRqrmntCcCdng() /** { "tree" :"EvidenceVariable.characteristic.definitionTriggerdefinition", "datatype" : "TriggerDefinition, DataRequirement, CodeableConcept, Coding", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionTriggerdefinition, setData, setSubjectCodeableConcept, addCoding"} **/
						, evidencevariable.getEvChrctrDfntnTrggrdfntnTrggrDfntnDtDtRqrmntCcTxt() /** { "tree" :"EvidenceVariable.characteristic.definitionTriggerdefinition", "datatype" : "TriggerDefinition, DataRequirement, CodeableConcept, string", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionTriggerdefinition, setData, setSubjectCodeableConcept, setText"} **/
						, evidencevariable.getEvChrctrDfntnTrggrdfntnTrggrDfntnDtDtRqrmntTpe() /** { "tree" :"EvidenceVariable.characteristic.definitionTriggerdefinition", "datatype" : "TriggerDefinition, DataRequirement, code", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionTriggerdefinition, setData, setType"} **/
						, evidencevariable.getEvChrctrDfntnTrggrdfntnTrggrDfntnDtDtRqrmntPrfle() /** { "tree" :"EvidenceVariable.characteristic.definitionTriggerdefinition", "datatype" : "TriggerDefinition, DataRequirement, canonical", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionTriggerdefinition, setData, addProfile"} **/
						, evidencevariable.getEvChrctrDfntnTrggrdfntnTrggrDfntnDtDtRqrmntSbjctRfrnce() /** { "tree" :"EvidenceVariable.characteristic.definitionTriggerdefinition", "datatype" : "TriggerDefinition, DataRequirement, Reference", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionTriggerdefinition, setData, setSubjectReference"} **/
						, evidencevariable.getEvChrctrDfntnTrggrdfntnTrggrDfntnDtDtRqrmntMstSpprt() /** { "tree" :"EvidenceVariable.characteristic.definitionTriggerdefinition", "datatype" : "TriggerDefinition, DataRequirement, string", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionTriggerdefinition, setData, addMustSupport"} **/
						, evidencevariable.getEvChrctrDfntnTrggrdfntnTrggrDfntnDtDtRqrmntCdFltrPth() /** { "tree" :"EvidenceVariable.characteristic.definitionTriggerdefinition", "datatype" : "TriggerDefinition, DataRequirement, Element, string", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionTriggerdefinition, setData, addCodeFilter, setPath"} **/
						, evidencevariable.getEvChrctrDfntnTrggrdfntnTrggrDfntnDtDtRqrmntCdFltrSrchPrm() /** { "tree" :"EvidenceVariable.characteristic.definitionTriggerdefinition", "datatype" : "TriggerDefinition, DataRequirement, Element, string", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionTriggerdefinition, setData, addCodeFilter, setSearchParam"} **/
						, evidencevariable.getEvChrctrDfntnTrggrdfntnTrggrDfntnDtDtRqrmntCdFltrVlSt() /** { "tree" :"EvidenceVariable.characteristic.definitionTriggerdefinition", "datatype" : "TriggerDefinition, DataRequirement, Element, canonical", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionTriggerdefinition, setData, addCodeFilter, setValueSet"} **/
						, evidencevariable.getEvChrctrDfntnTrggrdfntnTrggrDfntnDtDtRqrmntCdFltrCde() /** { "tree" :"EvidenceVariable.characteristic.definitionTriggerdefinition", "datatype" : "TriggerDefinition, DataRequirement, Element, Coding", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionTriggerdefinition, setData, addCodeFilter, addCode"} **/
						, evidencevariable.getEvChrctrDfntnTrggrdfntnTrggrDfntnDtDtRqrmntDtFltrPth() /** { "tree" :"EvidenceVariable.characteristic.definitionTriggerdefinition", "datatype" : "TriggerDefinition, DataRequirement, Element, string", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionTriggerdefinition, setData, addDateFilter, setPath"} **/
						, evidencevariable.getEvChrctrDfntnTrggrdfntnTrggrDfntnDtDtRqrmntDtFltrSrchPrm() /** { "tree" :"EvidenceVariable.characteristic.definitionTriggerdefinition", "datatype" : "TriggerDefinition, DataRequirement, Element, string", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionTriggerdefinition, setData, addDateFilter, setSearchParam"} **/
						, evidencevariable.getEvChrctrDfntnTrggrdfntnTrggrDfntnDtDtRqrmntDtFltrVlDtTme() /** { "tree" :"EvidenceVariable.characteristic.definitionTriggerdefinition", "datatype" : "TriggerDefinition, DataRequirement, Element, dateTime", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionTriggerdefinition, setData, addDateFilter, setValueDateTime"} **/
						, evidencevariable.getEvChrctrDfntnTrggrdfntnTrggrDfntnDtDtRqrmntDtFltrVlPrd() /** { "tree" :"EvidenceVariable.characteristic.definitionTriggerdefinition", "datatype" : "TriggerDefinition, DataRequirement, Element, Period", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionTriggerdefinition, setData, addDateFilter, setValuePeriod"} **/
						, evidencevariable.getEvChrctrDfntnTrggrdfntnTrggrDfntnDtDtRqrmntDtFltrVlDrtn() /** { "tree" :"EvidenceVariable.characteristic.definitionTriggerdefinition", "datatype" : "TriggerDefinition, DataRequirement, Element, Duration", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionTriggerdefinition, setData, addDateFilter, setValueDuration"} **/
						, evidencevariable.getEvChrctrDfntnTrggrdfntnTrggrDfntnDtDtRqrmntLmt() /** { "tree" :"EvidenceVariable.characteristic.definitionTriggerdefinition", "datatype" : "TriggerDefinition, DataRequirement, positiveInt", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionTriggerdefinition, setData, setLimit"} **/
						, evidencevariable.getEvChrctrDfntnTrggrdfntnTrggrDfntnDtDtRqrmntSrtPth() /** { "tree" :"EvidenceVariable.characteristic.definitionTriggerdefinition", "datatype" : "TriggerDefinition, DataRequirement, string", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionTriggerdefinition, setData, addSort, setPath"} **/
						, evidencevariable.getEvChrctrDfntnTrggrdfntnTrggrDfntnDtDtRqrmntSrtDrctn() /** { "tree" :"EvidenceVariable.characteristic.definitionTriggerdefinition", "datatype" : "TriggerDefinition, DataRequirement, code", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionTriggerdefinition, setData, addSort, setDirection"} **/
						, evidencevariable.getEvChrctrDfntnTrggrdfntnTrggrDfntnTmngDte() /** { "tree" :"EvidenceVariable.characteristic.definitionTriggerdefinition", "datatype" : "TriggerDefinition, date", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionTriggerdefinition, addTimingDate"} **/
						, evidencevariable.getEvChrctrDfntnTrggrdfntnTrggrDfntnTmngDtTme() /** { "tree" :"EvidenceVariable.characteristic.definitionTriggerdefinition", "datatype" : "TriggerDefinition, dateTime", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionTriggerdefinition, addTimingDateTime"} **/
						, evidencevariable.getEvChrctrDfntnTrggrdfntnTrggrDfntnCndtnXprssnDscrptn() /** { "tree" :"EvidenceVariable.characteristic.definitionTriggerdefinition", "datatype" : "TriggerDefinition, Expression, string", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionTriggerdefinition, addCondition, setDescription"} **/
						, evidencevariable.getEvChrctrDfntnTrggrdfntnTrggrDfntnCndtnXprssnNme() /** { "tree" :"EvidenceVariable.characteristic.definitionTriggerdefinition", "datatype" : "TriggerDefinition, Expression, id", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionTriggerdefinition, addCondition, setName"} **/
						, evidencevariable.getEvChrctrDfntnTrggrdfntnTrggrDfntnCndtnXprssnLngge() /** { "tree" :"EvidenceVariable.characteristic.definitionTriggerdefinition", "datatype" : "TriggerDefinition, Expression, code", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionTriggerdefinition, addCondition, setLanguage"} **/
						, evidencevariable.getEvChrctrDfntnTrggrdfntnTrggrDfntnCndtnXprssnXprssn() /** { "tree" :"EvidenceVariable.characteristic.definitionTriggerdefinition", "datatype" : "TriggerDefinition, Expression, string", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionTriggerdefinition, addCondition, setExpression"} **/
						, evidencevariable.getEvChrctrDfntnTrggrdfntnTrggrDfntnCndtnXprssnRfrnce() /** { "tree" :"EvidenceVariable.characteristic.definitionTriggerdefinition", "datatype" : "TriggerDefinition, Expression, uri", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionTriggerdefinition, addCondition, setReference"} **/
						, evidencevariable.getEvChrctrDfntnTrggrdfntnTrggrDfntnTmngRfrnce() /** { "tree" :"EvidenceVariable.characteristic.definitionTriggerdefinition", "datatype" : "TriggerDefinition, Reference", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionTriggerdefinition, addTimingReference"} **/
						, evidencevariable.getEvChrctrDfntnTrggrdfntnTrggrDfntnNme() /** { "tree" :"EvidenceVariable.characteristic.definitionTriggerdefinition", "datatype" : "TriggerDefinition, string", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionTriggerdefinition, addName"} **/
						, evidencevariable.getEvChrctrDfntnTrggrdfntnTrggrDfntnTmngTmngTmngCcCdng() /** { "tree" :"EvidenceVariable.characteristic.definitionTriggerdefinition", "datatype" : "TriggerDefinition, Timing, CodeableConcept, Coding", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionTriggerdefinition, addTimingTiming, setCode, addCoding"} **/
						, evidencevariable.getEvChrctrDfntnTrggrdfntnTrggrDfntnTmngTmngTmngCcTxt() /** { "tree" :"EvidenceVariable.characteristic.definitionTriggerdefinition", "datatype" : "TriggerDefinition, Timing, CodeableConcept, string", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionTriggerdefinition, addTimingTiming, setCode, setText"} **/
						, evidencevariable.getEvChrctrDfntnTrggrdfntnTrggrDfntnTmngTmngTmngVnt() /** { "tree" :"EvidenceVariable.characteristic.definitionTriggerdefinition", "datatype" : "TriggerDefinition, Timing, dateTime", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionTriggerdefinition, addTimingTiming, addEvent"} **/
						, evidencevariable.getEvChrctrDfntnTrggrdfntnTrggrDfntnTmngTmngTmngRptBndsDrtn() /** { "tree" :"EvidenceVariable.characteristic.definitionTriggerdefinition", "datatype" : "TriggerDefinition, Timing, Element, Duration", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionTriggerdefinition, addTimingTiming, setRepeat, setBoundsDuration"} **/
						, evidencevariable.getEvChrctrDfntnTrggrdfntnTrggrDfntnTmngTmngTmngRptBndsRnge() /** { "tree" :"EvidenceVariable.characteristic.definitionTriggerdefinition", "datatype" : "TriggerDefinition, Timing, Element, Range", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionTriggerdefinition, addTimingTiming, setRepeat, setBoundsRange"} **/
						, evidencevariable.getEvChrctrDfntnTrggrdfntnTrggrDfntnTmngTmngTmngRptBndsPrd() /** { "tree" :"EvidenceVariable.characteristic.definitionTriggerdefinition", "datatype" : "TriggerDefinition, Timing, Element, Period", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionTriggerdefinition, addTimingTiming, setRepeat, setBoundsPeriod"} **/
						, evidencevariable.getEvChrctrDfntnTrggrdfntnTrggrDfntnTmngTmngTmngRptCnt() /** { "tree" :"EvidenceVariable.characteristic.definitionTriggerdefinition", "datatype" : "TriggerDefinition, Timing, Element, positiveInt", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionTriggerdefinition, addTimingTiming, setRepeat, setCount"} **/
						, evidencevariable.getEvChrctrDfntnTrggrdfntnTrggrDfntnTmngTmngTmngRptCntMx() /** { "tree" :"EvidenceVariable.characteristic.definitionTriggerdefinition", "datatype" : "TriggerDefinition, Timing, Element, positiveInt", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionTriggerdefinition, addTimingTiming, setRepeat, setCountMax"} **/
						, evidencevariable.getEvChrctrDfntnTrggrdfntnTrggrDfntnTmngTmngTmngRptDrtn() /** { "tree" :"EvidenceVariable.characteristic.definitionTriggerdefinition", "datatype" : "TriggerDefinition, Timing, Element, decimal", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionTriggerdefinition, addTimingTiming, setRepeat, setDuration"} **/
						, evidencevariable.getEvChrctrDfntnTrggrdfntnTrggrDfntnTmngTmngTmngRptDrtnMx() /** { "tree" :"EvidenceVariable.characteristic.definitionTriggerdefinition", "datatype" : "TriggerDefinition, Timing, Element, decimal", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionTriggerdefinition, addTimingTiming, setRepeat, setDurationMax"} **/
						, evidencevariable.getEvChrctrDfntnTrggrdfntnTrggrDfntnTmngTmngTmngRptDrtnnt() /** { "tree" :"EvidenceVariable.characteristic.definitionTriggerdefinition", "datatype" : "TriggerDefinition, Timing, Element, code", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionTriggerdefinition, addTimingTiming, setRepeat, setDurationUnit"} **/
						, evidencevariable.getEvChrctrDfntnTrggrdfntnTrggrDfntnTmngTmngTmngRptFrqncy() /** { "tree" :"EvidenceVariable.characteristic.definitionTriggerdefinition", "datatype" : "TriggerDefinition, Timing, Element, positiveInt", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionTriggerdefinition, addTimingTiming, setRepeat, setFrequency"} **/
						, evidencevariable.getEvChrctrDfntnTrggrdfntnTrggrDfntnTmngTmngTmngRptFrqncMx() /** { "tree" :"EvidenceVariable.characteristic.definitionTriggerdefinition", "datatype" : "TriggerDefinition, Timing, Element, positiveInt", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionTriggerdefinition, addTimingTiming, setRepeat, setFrequencyMax"} **/
						, evidencevariable.getEvChrctrDfntnTrggrdfntnTrggrDfntnTmngTmngTmngRptPrd() /** { "tree" :"EvidenceVariable.characteristic.definitionTriggerdefinition", "datatype" : "TriggerDefinition, Timing, Element, decimal", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionTriggerdefinition, addTimingTiming, setRepeat, setPeriod"} **/
						, evidencevariable.getEvChrctrDfntnTrggrdfntnTrggrDfntnTmngTmngTmngRptPrdMx() /** { "tree" :"EvidenceVariable.characteristic.definitionTriggerdefinition", "datatype" : "TriggerDefinition, Timing, Element, decimal", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionTriggerdefinition, addTimingTiming, setRepeat, setPeriodMax"} **/
						, evidencevariable.getEvChrctrDfntnTrggrdfntnTrggrDfntnTmngTmngTmngRptPrdnt() /** { "tree" :"EvidenceVariable.characteristic.definitionTriggerdefinition", "datatype" : "TriggerDefinition, Timing, Element, code", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionTriggerdefinition, addTimingTiming, setRepeat, setPeriodUnit"} **/
						, evidencevariable.getEvChrctrDfntnTrggrdfntnTrggrDfntnTmngTmngTmngRptDfWk() /** { "tree" :"EvidenceVariable.characteristic.definitionTriggerdefinition", "datatype" : "TriggerDefinition, Timing, Element, code", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionTriggerdefinition, addTimingTiming, setRepeat, addDayOfWeek"} **/
						, evidencevariable.getEvChrctrDfntnTrggrdfntnTrggrDfntnTmngTmngTmngRptTmfDay() /** { "tree" :"EvidenceVariable.characteristic.definitionTriggerdefinition", "datatype" : "TriggerDefinition, Timing, Element, time", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionTriggerdefinition, addTimingTiming, setRepeat, addTimeOfDay"} **/
						, evidencevariable.getEvChrctrDfntnTrggrdfntnTrggrDfntnTmngTmngTmngRptWhn() /** { "tree" :"EvidenceVariable.characteristic.definitionTriggerdefinition", "datatype" : "TriggerDefinition, Timing, Element, code", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionTriggerdefinition, addTimingTiming, setRepeat, addWhen"} **/
						, evidencevariable.getEvChrctrDfntnTrggrdfntnTrggrDfntnTmngTmngTmngRptFfst() /** { "tree" :"EvidenceVariable.characteristic.definitionTriggerdefinition", "datatype" : "TriggerDefinition, Timing, Element, unsignedInt", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionTriggerdefinition, addTimingTiming, setRepeat, setOffset"} **/
						));
Evidencevariableobj.addUsageContext(HapiFHIRHelpers.createUsageContext(evidencevariable.getEvChrctrSgCntxtSgCntxtVlCcCcCSstm() /** { "tree" :"EvidenceVariable.characteristic.usageContext", "datatype" : "UsageContext, CodeableConcept, Coding, uri", "cardinality" : "Many", "elementtree" : ["setCharacteristic"] , "methodName" : "addUsageContext, addValueCodeableConcept, addCoding, setSystem"} **/
						, evidencevariable.getEvChrctrSgCntxtSgCntxtVlCcCcCVrsn() /** { "tree" :"EvidenceVariable.characteristic.usageContext", "datatype" : "UsageContext, CodeableConcept, Coding, string", "cardinality" : "Many", "elementtree" : ["setCharacteristic"] , "methodName" : "addUsageContext, addValueCodeableConcept, addCoding, setVersion"} **/
						, evidencevariable.getEvChrctrSgCntxtSgCntxtVlCcCcCCde() /** { "tree" :"EvidenceVariable.characteristic.usageContext", "datatype" : "UsageContext, CodeableConcept, Coding, code", "cardinality" : "Many", "elementtree" : ["setCharacteristic"] , "methodName" : "addUsageContext, addValueCodeableConcept, addCoding, setCode"} **/
						, evidencevariable.getEvChrctrSgCntxtSgCntxtVlCcCcCDsplay() /** { "tree" :"EvidenceVariable.characteristic.usageContext", "datatype" : "UsageContext, CodeableConcept, Coding, string", "cardinality" : "Many", "elementtree" : ["setCharacteristic"] , "methodName" : "addUsageContext, addValueCodeableConcept, addCoding, setDisplay"} **/
						, evidencevariable.getEvChrctrSgCntxtSgCntxtVlCcCcCSrSlctd() /** { "tree" :"EvidenceVariable.characteristic.usageContext", "datatype" : "UsageContext, CodeableConcept, Coding, boolean", "cardinality" : "Many", "elementtree" : ["setCharacteristic"] , "methodName" : "addUsageContext, addValueCodeableConcept, addCoding, setUserSelected"} **/
						, evidencevariable.getEvChrctrSgCntxtSgCntxtVlCcCcTxt() /** { "tree" :"EvidenceVariable.characteristic.usageContext", "datatype" : "UsageContext, CodeableConcept, string", "cardinality" : "Many", "elementtree" : ["setCharacteristic"] , "methodName" : "addUsageContext, addValueCodeableConcept, setText"} **/
						, evidencevariable.getEvChrctrSgCntxtSgCntxtCdCSstm() /** { "tree" :"EvidenceVariable.characteristic.usageContext", "datatype" : "UsageContext, Coding, uri", "cardinality" : "Many", "elementtree" : ["setCharacteristic"] , "methodName" : "addUsageContext, addCode, setSystem"} **/
						, evidencevariable.getEvChrctrSgCntxtSgCntxtCdCVrsn() /** { "tree" :"EvidenceVariable.characteristic.usageContext", "datatype" : "UsageContext, Coding, string", "cardinality" : "Many", "elementtree" : ["setCharacteristic"] , "methodName" : "addUsageContext, addCode, setVersion"} **/
						, evidencevariable.getEvChrctrSgCntxtSgCntxtCdCCde() /** { "tree" :"EvidenceVariable.characteristic.usageContext", "datatype" : "UsageContext, Coding, code", "cardinality" : "Many", "elementtree" : ["setCharacteristic"] , "methodName" : "addUsageContext, addCode, setCode"} **/
						, evidencevariable.getEvChrctrSgCntxtSgCntxtCdCDsplay() /** { "tree" :"EvidenceVariable.characteristic.usageContext", "datatype" : "UsageContext, Coding, string", "cardinality" : "Many", "elementtree" : ["setCharacteristic"] , "methodName" : "addUsageContext, addCode, setDisplay"} **/
						, evidencevariable.getEvChrctrSgCntxtSgCntxtCdCSrSlctd() /** { "tree" :"EvidenceVariable.characteristic.usageContext", "datatype" : "UsageContext, Coding, boolean", "cardinality" : "Many", "elementtree" : ["setCharacteristic"] , "methodName" : "addUsageContext, addCode, setUserSelected"} **/
						, evidencevariable.getEvChrctrSgCntxtSgCntxtVlQnttQnttVlue() /** { "tree" :"EvidenceVariable.characteristic.usageContext", "datatype" : "UsageContext, Quantity, decimal", "cardinality" : "Many", "elementtree" : ["setCharacteristic"] , "methodName" : "addUsageContext, addValueQuantity, setValue"} **/
						, evidencevariable.getEvChrctrSgCntxtSgCntxtVlQnttQnttCmprtr() /** { "tree" :"EvidenceVariable.characteristic.usageContext", "datatype" : "UsageContext, Quantity, code", "cardinality" : "Many", "elementtree" : ["setCharacteristic"] , "methodName" : "addUsageContext, addValueQuantity, setComparator"} **/
						, evidencevariable.getEvChrctrSgCntxtSgCntxtVlQnttQnttNt() /** { "tree" :"EvidenceVariable.characteristic.usageContext", "datatype" : "UsageContext, Quantity, string", "cardinality" : "Many", "elementtree" : ["setCharacteristic"] , "methodName" : "addUsageContext, addValueQuantity, setUnit"} **/
						, evidencevariable.getEvChrctrSgCntxtSgCntxtVlQnttQnttSstm() /** { "tree" :"EvidenceVariable.characteristic.usageContext", "datatype" : "UsageContext, Quantity, uri", "cardinality" : "Many", "elementtree" : ["setCharacteristic"] , "methodName" : "addUsageContext, addValueQuantity, setSystem"} **/
						, evidencevariable.getEvChrctrSgCntxtSgCntxtVlQnttQnttCde() /** { "tree" :"EvidenceVariable.characteristic.usageContext", "datatype" : "UsageContext, Quantity, code", "cardinality" : "Many", "elementtree" : ["setCharacteristic"] , "methodName" : "addUsageContext, addValueQuantity, setCode"} **/
						, evidencevariable.getEvChrctrSgCntxtSgCntxtVlRngRngLw() /** { "tree" :"EvidenceVariable.characteristic.usageContext", "datatype" : "UsageContext, Range, SimpleQuantity", "cardinality" : "Many", "elementtree" : ["setCharacteristic"] , "methodName" : "addUsageContext, addValueRange, setLow"} **/
						, evidencevariable.getEvChrctrSgCntxtSgCntxtVlRngRngHgh() /** { "tree" :"EvidenceVariable.characteristic.usageContext", "datatype" : "UsageContext, Range, SimpleQuantity", "cardinality" : "Many", "elementtree" : ["setCharacteristic"] , "methodName" : "addUsageContext, addValueRange, setHigh"} **/
						, evidencevariable.getEvChrctrSgCntxtSgCntxtVlRfrnce() /** { "tree" :"EvidenceVariable.characteristic.usageContext", "datatype" : "UsageContext, Reference", "cardinality" : "Many", "elementtree" : ["setCharacteristic"] , "methodName" : "addUsageContext, addValueReference"} **/
						));
Evidencevariableobj.setExclude(HapiFHIRHelpers.createboolean(evidencevariable.getEvChrctrExcludeBoolean() /** { "tree" :"EvidenceVariable.characteristic.exclude", "datatype" : "boolean", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setExclude"} **/
						));
Evidencevariableobj.setParticipantEffective(HapiFHIRHelpers.createdateTimetype(evidencevariable.getEvChrctrPrtcpntffctvDttmDtTme() /** { "tree" :"EvidenceVariable.characteristic.participantEffectiveDatetime", "datatype" : "dateTime", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setParticipantEffectiveDatetime"} **/
						));
Evidencevariableobj.setParticipantEffectivePeriod(HapiFHIRHelpers.createPeriod(evidencevariable.getEvChrctrPrtcpntffctvPrdPrdStrt() /** { "tree" :"EvidenceVariable.characteristic.participantEffectivePeriod", "datatype" : "Period, dateTime", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setParticipantEffectivePeriod, setStart"} **/
						, evidencevariable.getEvChrctrPrtcpntffctvPrdPrdNd() /** { "tree" :"EvidenceVariable.characteristic.participantEffectivePeriod", "datatype" : "Period, dateTime", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setParticipantEffectivePeriod, setEnd"} **/
						));
Evidencevariableobj.setParticipantEffectiveDuration(HapiFHIRHelpers.createDuration(evidencevariable.getEvChrctrPrtcpntffctvDrtnDrtn() /** { "tree" :"EvidenceVariable.characteristic.participantEffectiveDuration", "datatype" : "Duration", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setParticipantEffectiveDuration"} **/
						));
Evidencevariableobj.setParticipantEffectiveTiming(HapiFHIRHelpers.createTiming(evidencevariable.getEvChrctrPrtcpntffctvTmngTmngCdCcCSstm() /** { "tree" :"EvidenceVariable.characteristic.participantEffectiveTiming", "datatype" : "Timing, CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setParticipantEffectiveTiming, setCode, addCoding, setSystem"} **/
						, evidencevariable.getEvChrctrPrtcpntffctvTmngTmngCdCcCVrsn() /** { "tree" :"EvidenceVariable.characteristic.participantEffectiveTiming", "datatype" : "Timing, CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setParticipantEffectiveTiming, setCode, addCoding, setVersion"} **/
						, evidencevariable.getEvChrctrPrtcpntffctvTmngTmngCdCcCCde() /** { "tree" :"EvidenceVariable.characteristic.participantEffectiveTiming", "datatype" : "Timing, CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setParticipantEffectiveTiming, setCode, addCoding, setCode"} **/
						, evidencevariable.getEvChrctrPrtcpntffctvTmngTmngCdCcCDsplay() /** { "tree" :"EvidenceVariable.characteristic.participantEffectiveTiming", "datatype" : "Timing, CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setParticipantEffectiveTiming, setCode, addCoding, setDisplay"} **/
						, evidencevariable.getEvChrctrPrtcpntffctvTmngTmngCdCcCSrSlctd() /** { "tree" :"EvidenceVariable.characteristic.participantEffectiveTiming", "datatype" : "Timing, CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setParticipantEffectiveTiming, setCode, addCoding, setUserSelected"} **/
						, evidencevariable.getEvChrctrPrtcpntffctvTmngTmngCdCcTxt() /** { "tree" :"EvidenceVariable.characteristic.participantEffectiveTiming", "datatype" : "Timing, CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setParticipantEffectiveTiming, setCode, setText"} **/
						, evidencevariable.getEvChrctrPrtcpntffctvTmngTmngVnt() /** { "tree" :"EvidenceVariable.characteristic.participantEffectiveTiming", "datatype" : "Timing, dateTime", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setParticipantEffectiveTiming, addEvent"} **/
						, evidencevariable.getEvChrctrPrtcpntffctvTmngTmngRptDrtnnt() /** { "tree" :"EvidenceVariable.characteristic.participantEffectiveTiming", "datatype" : "Timing, Element, code", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setParticipantEffectiveTiming, setRepeat, setDurationUnit"} **/
						, evidencevariable.getEvChrctrPrtcpntffctvTmngTmngRptPrdnt() /** { "tree" :"EvidenceVariable.characteristic.participantEffectiveTiming", "datatype" : "Timing, Element, code", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setParticipantEffectiveTiming, setRepeat, setPeriodUnit"} **/
						, evidencevariable.getEvChrctrPrtcpntffctvTmngTmngRptDfWk() /** { "tree" :"EvidenceVariable.characteristic.participantEffectiveTiming", "datatype" : "Timing, Element, code", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setParticipantEffectiveTiming, setRepeat, addDayOfWeek"} **/
						, evidencevariable.getEvChrctrPrtcpntffctvTmngTmngRptWhn() /** { "tree" :"EvidenceVariable.characteristic.participantEffectiveTiming", "datatype" : "Timing, Element, code", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setParticipantEffectiveTiming, setRepeat, addWhen"} **/
						, evidencevariable.getEvChrctrPrtcpntffctvTmngTmngRptDrtn() /** { "tree" :"EvidenceVariable.characteristic.participantEffectiveTiming", "datatype" : "Timing, Element, decimal", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setParticipantEffectiveTiming, setRepeat, setDuration"} **/
						, evidencevariable.getEvChrctrPrtcpntffctvTmngTmngRptDrtnMx() /** { "tree" :"EvidenceVariable.characteristic.participantEffectiveTiming", "datatype" : "Timing, Element, decimal", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setParticipantEffectiveTiming, setRepeat, setDurationMax"} **/
						, evidencevariable.getEvChrctrPrtcpntffctvTmngTmngRptPrd() /** { "tree" :"EvidenceVariable.characteristic.participantEffectiveTiming", "datatype" : "Timing, Element, decimal", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setParticipantEffectiveTiming, setRepeat, setPeriod"} **/
						, evidencevariable.getEvChrctrPrtcpntffctvTmngTmngRptPrdMx() /** { "tree" :"EvidenceVariable.characteristic.participantEffectiveTiming", "datatype" : "Timing, Element, decimal", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setParticipantEffectiveTiming, setRepeat, setPeriodMax"} **/
						, evidencevariable.getEvChrctrPrtcpntffctvTmngTmngRptBndsDrtn() /** { "tree" :"EvidenceVariable.characteristic.participantEffectiveTiming", "datatype" : "Timing, Element, Duration", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setParticipantEffectiveTiming, setRepeat, setBoundsDuration"} **/
						, evidencevariable.getEvChrctrPrtcpntffctvTmngTmngRptBndsPrd() /** { "tree" :"EvidenceVariable.characteristic.participantEffectiveTiming", "datatype" : "Timing, Element, Period", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setParticipantEffectiveTiming, setRepeat, setBoundsPeriod"} **/
						, evidencevariable.getEvChrctrPrtcpntffctvTmngTmngRptCnt() /** { "tree" :"EvidenceVariable.characteristic.participantEffectiveTiming", "datatype" : "Timing, Element, positiveInt", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setParticipantEffectiveTiming, setRepeat, setCount"} **/
						, evidencevariable.getEvChrctrPrtcpntffctvTmngTmngRptCntMx() /** { "tree" :"EvidenceVariable.characteristic.participantEffectiveTiming", "datatype" : "Timing, Element, positiveInt", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setParticipantEffectiveTiming, setRepeat, setCountMax"} **/
						, evidencevariable.getEvChrctrPrtcpntffctvTmngTmngRptFrqncy() /** { "tree" :"EvidenceVariable.characteristic.participantEffectiveTiming", "datatype" : "Timing, Element, positiveInt", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setParticipantEffectiveTiming, setRepeat, setFrequency"} **/
						, evidencevariable.getEvChrctrPrtcpntffctvTmngTmngRptFrqncMx() /** { "tree" :"EvidenceVariable.characteristic.participantEffectiveTiming", "datatype" : "Timing, Element, positiveInt", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setParticipantEffectiveTiming, setRepeat, setFrequencyMax"} **/
						, evidencevariable.getEvChrctrPrtcpntffctvTmngTmngRptBndsRnge() /** { "tree" :"EvidenceVariable.characteristic.participantEffectiveTiming", "datatype" : "Timing, Element, Range", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setParticipantEffectiveTiming, setRepeat, setBoundsRange"} **/
						, evidencevariable.getEvChrctrPrtcpntffctvTmngTmngRptTmfDay() /** { "tree" :"EvidenceVariable.characteristic.participantEffectiveTiming", "datatype" : "Timing, Element, time", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setParticipantEffectiveTiming, setRepeat, addTimeOfDay"} **/
						, evidencevariable.getEvChrctrPrtcpntffctvTmngTmngRptFfst() /** { "tree" :"EvidenceVariable.characteristic.participantEffectiveTiming", "datatype" : "Timing, Element, unsignedInt", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setParticipantEffectiveTiming, setRepeat, setOffset"} **/
						));
Evidencevariableobj.setTimeFromStart(HapiFHIRHelpers.createDuration(evidencevariable.getEvChrctrTimeFromStartDuration() /** { "tree" :"EvidenceVariable.characteristic.timeFromStart", "datatype" : "Duration", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setTimeFromStart"} **/
						));
Evidencevariableobj.setGroupMeasure(HapiFHIRHelpers.createcode(evidencevariable.getEvChrctrGroupMeasureCode() /** { "tree" :"EvidenceVariable.characteristic.groupMeasure", "datatype" : "code", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setGroupMeasure"} **/
		));
	}
}
