package main.templateoutput.Conversions;
// Generated on Jan 28, 2022, 8:02:40 AM 


import org.hl7.fhir.r4.model.Patient;

/**
 *  object for conversion model class Immunizationrecommendation.
 * @see .Immunizationrecommendation
 * @author Paul Kovach
 */
import main.java.com.campfhir.service.conversion.HapiFHIRHelpers;

public class ImmunizationrecommendationConversion 
{
	public Patient Immunizationrecommendations(main.templateoutput.Model.Immunizationrecommendation immunizationrecommendation) 
	{
			Patient  Immunizationrecommendationobj = new Patient(); 

						Immunizationrecommendationobj.addIdentifier(HapiFHIRHelpers.createIdentifier(immunizationrecommendation.getIrIdentifierIdentifierUse() /** { "tree" :"ImmunizationRecommendation.identifier", "datatype" : "Identifier, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setUse"} **/
						, immunizationrecommendation.getIrDntfrDntfrTpCcCSstm() /** { "tree" :"ImmunizationRecommendation.identifier", "datatype" : "Identifier, CodeableConcept, Coding, uri", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setType, addCoding, setSystem"} **/
						, immunizationrecommendation.getIrDntfrDntfrTpCcCVrsn() /** { "tree" :"ImmunizationRecommendation.identifier", "datatype" : "Identifier, CodeableConcept, Coding, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setType, addCoding, setVersion"} **/
						, immunizationrecommendation.getIrDntfrDntfrTpCcCCde() /** { "tree" :"ImmunizationRecommendation.identifier", "datatype" : "Identifier, CodeableConcept, Coding, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setType, addCoding, setCode"} **/
						, immunizationrecommendation.getIrDntfrDntfrTpCcCDsplay() /** { "tree" :"ImmunizationRecommendation.identifier", "datatype" : "Identifier, CodeableConcept, Coding, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setType, addCoding, setDisplay"} **/
						, immunizationrecommendation.getIrDntfrDntfrTpCcCSrSlctd() /** { "tree" :"ImmunizationRecommendation.identifier", "datatype" : "Identifier, CodeableConcept, Coding, boolean", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setType, addCoding, setUserSelected"} **/
						, immunizationrecommendation.getIrDntfrDntfrTpCcTxt() /** { "tree" :"ImmunizationRecommendation.identifier", "datatype" : "Identifier, CodeableConcept, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setType, setText"} **/
						, immunizationrecommendation.getIrDntfrDntfrPrdPrdStrt() /** { "tree" :"ImmunizationRecommendation.identifier", "datatype" : "Identifier, Period, dateTime", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setPeriod, setStart"} **/
						, immunizationrecommendation.getIrDntfrDntfrPrdPrdNd() /** { "tree" :"ImmunizationRecommendation.identifier", "datatype" : "Identifier, Period, dateTime", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setPeriod, setEnd"} **/
						, immunizationrecommendation.getIrIdentifierIdentifierAssigner() /** { "tree" :"ImmunizationRecommendation.identifier", "datatype" : "Identifier, Reference", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setAssigner"} **/
						, immunizationrecommendation.getIrIdentifierIdentifierValue() /** { "tree" :"ImmunizationRecommendation.identifier", "datatype" : "Identifier, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setValue"} **/
						, immunizationrecommendation.getIrIdentifierIdentifierSystem() /** { "tree" :"ImmunizationRecommendation.identifier", "datatype" : "Identifier, uri", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setSystem"} **/
						));
Immunizationrecommendationobj.setPatient(HapiFHIRHelpers.createReference(immunizationrecommendation.getIrPntReference() /** { "tree" :"ImmunizationRecommendation.patient", "datatype" : "Reference", "cardinality" : "Required", "elementtree" : [] , "methodName" : "setPatient"} **/
						));
Immunizationrecommendationobj.setDate(HapiFHIRHelpers.createdateTime(immunizationrecommendation.getIrDateDateTime() /** { "tree" :"ImmunizationRecommendation.date", "datatype" : "dateTime", "cardinality" : "Required", "elementtree" : [] , "methodName" : "setDate"} **/
						));
Immunizationrecommendationobj.setAuthority(HapiFHIRHelpers.createReference(immunizationrecommendation.getIrAuthorityReference() /** { "tree" :"ImmunizationRecommendation.authority", "datatype" : "Reference", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setAuthority"} **/
						));
Immunizationrecommendationobj.addVaccineCode(HapiFHIRHelpers.createCodeableConcept(immunizationrecommendation.getIrRcmmndtnVccnCdCcCdngCSstm() /** { "tree" :"ImmunizationRecommendation.recommendation.vaccineCode", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "Many", "elementtree" : ["setRecommendation"] , "methodName" : "addVaccineCode, addCoding, setSystem"} **/
						, immunizationrecommendation.getIrRcmmndtnVccnCdCcCdngCVrsn() /** { "tree" :"ImmunizationRecommendation.recommendation.vaccineCode", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Many", "elementtree" : ["setRecommendation"] , "methodName" : "addVaccineCode, addCoding, setVersion"} **/
						, immunizationrecommendation.getIrRcmmndtnVccnCdCcCdngCCde() /** { "tree" :"ImmunizationRecommendation.recommendation.vaccineCode", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "Many", "elementtree" : ["setRecommendation"] , "methodName" : "addVaccineCode, addCoding, setCode"} **/
						, immunizationrecommendation.getIrRcmmndtnVccnCdCcCdngCDsplay() /** { "tree" :"ImmunizationRecommendation.recommendation.vaccineCode", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Many", "elementtree" : ["setRecommendation"] , "methodName" : "addVaccineCode, addCoding, setDisplay"} **/
						, immunizationrecommendation.getIrRcmmndtnVccnCdCcCdngCSrSlctd() /** { "tree" :"ImmunizationRecommendation.recommendation.vaccineCode", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "Many", "elementtree" : ["setRecommendation"] , "methodName" : "addVaccineCode, addCoding, setUserSelected"} **/
						, immunizationrecommendation.getIrRcmmndtnVccnCdCcTxt() /** { "tree" :"ImmunizationRecommendation.recommendation.vaccineCode", "datatype" : "CodeableConcept, string", "cardinality" : "Many", "elementtree" : ["setRecommendation"] , "methodName" : "addVaccineCode, setText"} **/
						));
Immunizationrecommendationobj.setTargetDisease(HapiFHIRHelpers.createCodeableConcept(immunizationrecommendation.getIrRcmmndtnTrgtDssCcCdngCSstm() /** { "tree" :"ImmunizationRecommendation.recommendation.targetDisease", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : ["setRecommendation"] , "methodName" : "setTargetDisease, addCoding, setSystem"} **/
						, immunizationrecommendation.getIrRcmmndtnTrgtDssCcCdngCVrsn() /** { "tree" :"ImmunizationRecommendation.recommendation.targetDisease", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["setRecommendation"] , "methodName" : "setTargetDisease, addCoding, setVersion"} **/
						, immunizationrecommendation.getIrRcmmndtnTrgtDssCcCdngCCde() /** { "tree" :"ImmunizationRecommendation.recommendation.targetDisease", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : ["setRecommendation"] , "methodName" : "setTargetDisease, addCoding, setCode"} **/
						, immunizationrecommendation.getIrRcmmndtnTrgtDssCcCdngCDsplay() /** { "tree" :"ImmunizationRecommendation.recommendation.targetDisease", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["setRecommendation"] , "methodName" : "setTargetDisease, addCoding, setDisplay"} **/
						, immunizationrecommendation.getIrRcmmndtnTrgtDssCcCdngCSrSlctd() /** { "tree" :"ImmunizationRecommendation.recommendation.targetDisease", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : ["setRecommendation"] , "methodName" : "setTargetDisease, addCoding, setUserSelected"} **/
						, immunizationrecommendation.getIrRcmmndtnTrgtDssCcTxt() /** { "tree" :"ImmunizationRecommendation.recommendation.targetDisease", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : ["setRecommendation"] , "methodName" : "setTargetDisease, setText"} **/
						));
Immunizationrecommendationobj.addContraindicatedVaccineCode(HapiFHIRHelpers.createCodeableConcept(immunizationrecommendation.getIrRcmmndtnCntrndctdVccnCdCcCdngCSstm() /** { "tree" :"ImmunizationRecommendation.recommendation.contraindicatedVaccineCode", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "Many", "elementtree" : ["setRecommendation"] , "methodName" : "addContraindicatedVaccineCode, addCoding, setSystem"} **/
						, immunizationrecommendation.getIrRcmmndtnCntrndctdVccnCdCcCdngCVrsn() /** { "tree" :"ImmunizationRecommendation.recommendation.contraindicatedVaccineCode", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Many", "elementtree" : ["setRecommendation"] , "methodName" : "addContraindicatedVaccineCode, addCoding, setVersion"} **/
						, immunizationrecommendation.getIrRcmmndtnCntrndctdVccnCdCcCdngCCde() /** { "tree" :"ImmunizationRecommendation.recommendation.contraindicatedVaccineCode", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "Many", "elementtree" : ["setRecommendation"] , "methodName" : "addContraindicatedVaccineCode, addCoding, setCode"} **/
						, immunizationrecommendation.getIrRcmmndtnCntrndctdVccnCdCcCdngCDsplay() /** { "tree" :"ImmunizationRecommendation.recommendation.contraindicatedVaccineCode", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Many", "elementtree" : ["setRecommendation"] , "methodName" : "addContraindicatedVaccineCode, addCoding, setDisplay"} **/
						, immunizationrecommendation.getIrRcmmndtnCntrndctdVccnCdCcCdngCSrSlctd() /** { "tree" :"ImmunizationRecommendation.recommendation.contraindicatedVaccineCode", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "Many", "elementtree" : ["setRecommendation"] , "methodName" : "addContraindicatedVaccineCode, addCoding, setUserSelected"} **/
						, immunizationrecommendation.getIrRcmmndtnCntrndctdVccnCdCcTxt() /** { "tree" :"ImmunizationRecommendation.recommendation.contraindicatedVaccineCode", "datatype" : "CodeableConcept, string", "cardinality" : "Many", "elementtree" : ["setRecommendation"] , "methodName" : "addContraindicatedVaccineCode, setText"} **/
						));
Immunizationrecommendationobj.setForecastStatus(HapiFHIRHelpers.createCodeableConcept(immunizationrecommendation.getIrRcmmndtnFrcstSttsCcCdngCSstm() /** { "tree" :"ImmunizationRecommendation.recommendation.forecastStatus", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "Required", "elementtree" : ["setRecommendation"] , "methodName" : "setForecastStatus, addCoding, setSystem"} **/
						, immunizationrecommendation.getIrRcmmndtnFrcstSttsCcCdngCVrsn() /** { "tree" :"ImmunizationRecommendation.recommendation.forecastStatus", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Required", "elementtree" : ["setRecommendation"] , "methodName" : "setForecastStatus, addCoding, setVersion"} **/
						, immunizationrecommendation.getIrRcmmndtnFrcstSttsCcCdngCCde() /** { "tree" :"ImmunizationRecommendation.recommendation.forecastStatus", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "Required", "elementtree" : ["setRecommendation"] , "methodName" : "setForecastStatus, addCoding, setCode"} **/
						, immunizationrecommendation.getIrRcmmndtnFrcstSttsCcCdngCDsplay() /** { "tree" :"ImmunizationRecommendation.recommendation.forecastStatus", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Required", "elementtree" : ["setRecommendation"] , "methodName" : "setForecastStatus, addCoding, setDisplay"} **/
						, immunizationrecommendation.getIrRcmmndtnFrcstSttsCcCdngCSrSlctd() /** { "tree" :"ImmunizationRecommendation.recommendation.forecastStatus", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "Required", "elementtree" : ["setRecommendation"] , "methodName" : "setForecastStatus, addCoding, setUserSelected"} **/
						, immunizationrecommendation.getIrRcmmndtnFrcstSttsCcTxt() /** { "tree" :"ImmunizationRecommendation.recommendation.forecastStatus", "datatype" : "CodeableConcept, string", "cardinality" : "Required", "elementtree" : ["setRecommendation"] , "methodName" : "setForecastStatus, setText"} **/
						));
Immunizationrecommendationobj.addForecastReason(HapiFHIRHelpers.createCodeableConcept(immunizationrecommendation.getIrRcmmndtnFrcstRsnCcCdngCSstm() /** { "tree" :"ImmunizationRecommendation.recommendation.forecastReason", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "Many", "elementtree" : ["setRecommendation"] , "methodName" : "addForecastReason, addCoding, setSystem"} **/
						, immunizationrecommendation.getIrRcmmndtnFrcstRsnCcCdngCVrsn() /** { "tree" :"ImmunizationRecommendation.recommendation.forecastReason", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Many", "elementtree" : ["setRecommendation"] , "methodName" : "addForecastReason, addCoding, setVersion"} **/
						, immunizationrecommendation.getIrRcmmndtnFrcstRsnCcCdngCCde() /** { "tree" :"ImmunizationRecommendation.recommendation.forecastReason", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "Many", "elementtree" : ["setRecommendation"] , "methodName" : "addForecastReason, addCoding, setCode"} **/
						, immunizationrecommendation.getIrRcmmndtnFrcstRsnCcCdngCDsplay() /** { "tree" :"ImmunizationRecommendation.recommendation.forecastReason", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Many", "elementtree" : ["setRecommendation"] , "methodName" : "addForecastReason, addCoding, setDisplay"} **/
						, immunizationrecommendation.getIrRcmmndtnFrcstRsnCcCdngCSrSlctd() /** { "tree" :"ImmunizationRecommendation.recommendation.forecastReason", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "Many", "elementtree" : ["setRecommendation"] , "methodName" : "addForecastReason, addCoding, setUserSelected"} **/
						, immunizationrecommendation.getIrRcmmndtnFrcstRsnCcTxt() /** { "tree" :"ImmunizationRecommendation.recommendation.forecastReason", "datatype" : "CodeableConcept, string", "cardinality" : "Many", "elementtree" : ["setRecommendation"] , "methodName" : "addForecastReason, setText"} **/
						));
Immunizationrecommendationobj.setCode(HapiFHIRHelpers.createCodeableConcept(immunizationrecommendation.getIrRcmmndtnDtCrtrnCdCcCdngCSstm() /** { "tree" :"ImmunizationRecommendation.recommendation.dateCriterion.code", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "Required", "elementtree" : ["setRecommendation", "addDateCriterion"] , "methodName" : "setCode, addCoding, setSystem"} **/
						, immunizationrecommendation.getIrRcmmndtnDtCrtrnCdCcCdngCVrsn() /** { "tree" :"ImmunizationRecommendation.recommendation.dateCriterion.code", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Required", "elementtree" : ["setRecommendation", "addDateCriterion"] , "methodName" : "setCode, addCoding, setVersion"} **/
						, immunizationrecommendation.getIrRcmmndtnDtCrtrnCdCcCdngCCde() /** { "tree" :"ImmunizationRecommendation.recommendation.dateCriterion.code", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "Required", "elementtree" : ["setRecommendation", "addDateCriterion"] , "methodName" : "setCode, addCoding, setCode"} **/
						, immunizationrecommendation.getIrRcmmndtnDtCrtrnCdCcCdngCDsplay() /** { "tree" :"ImmunizationRecommendation.recommendation.dateCriterion.code", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Required", "elementtree" : ["setRecommendation", "addDateCriterion"] , "methodName" : "setCode, addCoding, setDisplay"} **/
						, immunizationrecommendation.getIrRcmmndtnDtCrtrnCdCcCdngCSrSlctd() /** { "tree" :"ImmunizationRecommendation.recommendation.dateCriterion.code", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "Required", "elementtree" : ["setRecommendation", "addDateCriterion"] , "methodName" : "setCode, addCoding, setUserSelected"} **/
						, immunizationrecommendation.getIrRcmmndtnDtCrtrnCdCcTxt() /** { "tree" :"ImmunizationRecommendation.recommendation.dateCriterion.code", "datatype" : "CodeableConcept, string", "cardinality" : "Required", "elementtree" : ["setRecommendation", "addDateCriterion"] , "methodName" : "setCode, setText"} **/
						));
Immunizationrecommendationobj.setValue(HapiFHIRHelpers.createdateTime(immunizationrecommendation.getIrRcmmndtnDtCrtrnVlDtTme() /** { "tree" :"ImmunizationRecommendation.recommendation.dateCriterion.value", "datatype" : "dateTime", "cardinality" : "Required", "elementtree" : ["setRecommendation", "addDateCriterion"] , "methodName" : "setValue"} **/
						));
Immunizationrecommendationobj.setDescription(HapiFHIRHelpers.createstring(immunizationrecommendation.getIrRcmmndtnDscrptnStrng() /** { "tree" :"ImmunizationRecommendation.recommendation.description", "datatype" : "string", "cardinality" : "ZeroOne", "elementtree" : ["setRecommendation", "addDateCriterion"] , "methodName" : "setDescription"} **/
						));
Immunizationrecommendationobj.setSeries(HapiFHIRHelpers.createstring(immunizationrecommendation.getIrRecommendationSeriesString() /** { "tree" :"ImmunizationRecommendation.recommendation.series", "datatype" : "string", "cardinality" : "ZeroOne", "elementtree" : ["setRecommendation", "addDateCriterion"] , "methodName" : "setSeries"} **/
						));
Immunizationrecommendationobj.setDoseNumberPositiveint(HapiFHIRHelpers.createpositiveInt(immunizationrecommendation.getIrRcmmndtnDsNmbrPstvntPstvnt() /** { "tree" :"ImmunizationRecommendation.recommendation.doseNumberPositiveint", "datatype" : "positiveInt", "cardinality" : "ZeroOne", "elementtree" : ["setRecommendation", "addDateCriterion"] , "methodName" : "setDoseNumberPositiveint"} **/
						));
Immunizationrecommendationobj.setDoseNumberString(HapiFHIRHelpers.createstring(immunizationrecommendation.getIrRcmmndtnDsNmbrStrngStrng() /** { "tree" :"ImmunizationRecommendation.recommendation.doseNumberString", "datatype" : "string", "cardinality" : "ZeroOne", "elementtree" : ["setRecommendation", "addDateCriterion"] , "methodName" : "setDoseNumberString"} **/
						));
Immunizationrecommendationobj.setSeriesDosesPositiveint(HapiFHIRHelpers.createpositiveInt(immunizationrecommendation.getIrRcmmndtnSrsDssPstvntPstvnt() /** { "tree" :"ImmunizationRecommendation.recommendation.seriesDosesPositiveint", "datatype" : "positiveInt", "cardinality" : "ZeroOne", "elementtree" : ["setRecommendation", "addDateCriterion"] , "methodName" : "setSeriesDosesPositiveint"} **/
						));
Immunizationrecommendationobj.setSeriesDosesString(HapiFHIRHelpers.createstring(immunizationrecommendation.getIrRcmmndtnSrsDssStrngStrng() /** { "tree" :"ImmunizationRecommendation.recommendation.seriesDosesString", "datatype" : "string", "cardinality" : "ZeroOne", "elementtree" : ["setRecommendation", "addDateCriterion"] , "methodName" : "setSeriesDosesString"} **/
						));
Immunizationrecommendationobj.addSupportingImmunization(HapiFHIRHelpers.createReference(immunizationrecommendation.getIrRcmmndtnSpprtngmmRfrnce() /** { "tree" :"ImmunizationRecommendation.recommendation.supportingImmunization", "datatype" : "Reference", "cardinality" : "Many", "elementtree" : ["setRecommendation", "addDateCriterion"] , "methodName" : "addSupportingImmunization"} **/
						));
Immunizationrecommendationobj.addSupportingPatientInformation(HapiFHIRHelpers.createReference(immunizationrecommendation.getIrRcmmndtnSpprtngPtntnfrmtnRfrnce() /** { "tree" :"ImmunizationRecommendation.recommendation.supportingPatientInformation", "datatype" : "Reference", "cardinality" : "Many", "elementtree" : ["setRecommendation", "addDateCriterion"] , "methodName" : "addSupportingPatientInformation"} **/
		));
	}
}
