package main.templateoutput.Conversions;
// Generated on Jan 28, 2022, 8:02:40 AM 


import org.hl7.fhir.r4.model.Patient;

/**
 *  object for conversion model class Measurereport.
 * @see .Measurereport
 * @author Paul Kovach
 */
import main.java.com.campfhir.service.conversion.HapiFHIRHelpers;

public class MeasurereportConversion 
{
	public Patient Measurereports(main.templateoutput.Model.Measurereport measurereport) 
	{
			Patient  Measurereportobj = new Patient(); 

						Measurereportobj.addIdentifier(HapiFHIRHelpers.createIdentifier(measurereport.getMsrRprtDntfrDntfrSe() /** { "tree" :"MeasureReport.identifier", "datatype" : "Identifier, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setUse"} **/
						, measurereport.getMsrRprtDntfrDntfrTpCcCSstm() /** { "tree" :"MeasureReport.identifier", "datatype" : "Identifier, CodeableConcept, Coding, uri", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setType, addCoding, setSystem"} **/
						, measurereport.getMsrRprtDntfrDntfrTpCcCVrsn() /** { "tree" :"MeasureReport.identifier", "datatype" : "Identifier, CodeableConcept, Coding, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setType, addCoding, setVersion"} **/
						, measurereport.getMsrRprtDntfrDntfrTpCcCCde() /** { "tree" :"MeasureReport.identifier", "datatype" : "Identifier, CodeableConcept, Coding, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setType, addCoding, setCode"} **/
						, measurereport.getMsrRprtDntfrDntfrTpCcCDsplay() /** { "tree" :"MeasureReport.identifier", "datatype" : "Identifier, CodeableConcept, Coding, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setType, addCoding, setDisplay"} **/
						, measurereport.getMsrRprtDntfrDntfrTpCcCSrSlctd() /** { "tree" :"MeasureReport.identifier", "datatype" : "Identifier, CodeableConcept, Coding, boolean", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setType, addCoding, setUserSelected"} **/
						, measurereport.getMsrRprtDntfrDntfrTpCcTxt() /** { "tree" :"MeasureReport.identifier", "datatype" : "Identifier, CodeableConcept, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setType, setText"} **/
						, measurereport.getMsrRprtDntfrDntfrPrdPrdStrt() /** { "tree" :"MeasureReport.identifier", "datatype" : "Identifier, Period, dateTime", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setPeriod, setStart"} **/
						, measurereport.getMsrRprtDntfrDntfrPrdPrdNd() /** { "tree" :"MeasureReport.identifier", "datatype" : "Identifier, Period, dateTime", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setPeriod, setEnd"} **/
						, measurereport.getMsrRprtDntfrDntfrSsgnr() /** { "tree" :"MeasureReport.identifier", "datatype" : "Identifier, Reference", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setAssigner"} **/
						, measurereport.getMsrRprtDntfrDntfrVlue() /** { "tree" :"MeasureReport.identifier", "datatype" : "Identifier, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setValue"} **/
						, measurereport.getMsrRprtDntfrDntfrSstm() /** { "tree" :"MeasureReport.identifier", "datatype" : "Identifier, uri", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setSystem"} **/
						));
Measurereportobj.setStatus(HapiFHIRHelpers.createcode(measurereport.getMeasureReportStatusCode() /** { "tree" :"MeasureReport.status", "datatype" : "code", "cardinality" : "Required", "elementtree" : [] , "methodName" : "setStatus"} **/
						));
Measurereportobj.setType(HapiFHIRHelpers.createcode(measurereport.getMeasureReportTypeCode() /** { "tree" :"MeasureReport.type", "datatype" : "code", "cardinality" : "Required", "elementtree" : [] , "methodName" : "setType"} **/
						));
Measurereportobj.setMeasure(HapiFHIRHelpers.createcanonical(measurereport.getMeasureReportMeasureCanonical() /** { "tree" :"MeasureReport.measure", "datatype" : "canonical", "cardinality" : "Required", "elementtree" : [] , "methodName" : "setMeasure"} **/
						));
Measurereportobj.setSubject(HapiFHIRHelpers.createReference(measurereport.getMeasureReportSubjectReference() /** { "tree" :"MeasureReport.subject", "datatype" : "Reference", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setSubject"} **/
						));
Measurereportobj.setDate(HapiFHIRHelpers.createdateTime(measurereport.getMeasureReportDateDateTime() /** { "tree" :"MeasureReport.date", "datatype" : "dateTime", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setDate"} **/
						));
Measurereportobj.setReporter(HapiFHIRHelpers.createReference(measurereport.getMeasureReportReporterReference() /** { "tree" :"MeasureReport.reporter", "datatype" : "Reference", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setReporter"} **/
						));
Measurereportobj.setPeriod(HapiFHIRHelpers.createPeriod(measurereport.getMeasureReportPeriodPeriodStart() /** { "tree" :"MeasureReport.period", "datatype" : "Period, dateTime", "cardinality" : "Required", "elementtree" : [] , "methodName" : "setPeriod, setStart"} **/
						, measurereport.getMeasureReportPeriodPeriodEnd() /** { "tree" :"MeasureReport.period", "datatype" : "Period, dateTime", "cardinality" : "Required", "elementtree" : [] , "methodName" : "setPeriod, setEnd"} **/
						));
Measurereportobj.setImprovementNotation(HapiFHIRHelpers.createCodeableConcept(measurereport.getMsrRprtMprvmntNttnCcCdngCSstm() /** { "tree" :"MeasureReport.improvementNotation", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setImprovementNotation, addCoding, setSystem"} **/
						, measurereport.getMsrRprtMprvmntNttnCcCdngCVrsn() /** { "tree" :"MeasureReport.improvementNotation", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setImprovementNotation, addCoding, setVersion"} **/
						, measurereport.getMsrRprtMprvmntNttnCcCdngCCde() /** { "tree" :"MeasureReport.improvementNotation", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setImprovementNotation, addCoding, setCode"} **/
						, measurereport.getMsrRprtMprvmntNttnCcCdngCDsplay() /** { "tree" :"MeasureReport.improvementNotation", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setImprovementNotation, addCoding, setDisplay"} **/
						, measurereport.getMsrRprtMprvmntNttnCcCdngCSrSlctd() /** { "tree" :"MeasureReport.improvementNotation", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setImprovementNotation, addCoding, setUserSelected"} **/
						, measurereport.getMsrRprtMprvmntNttnCcTxt() /** { "tree" :"MeasureReport.improvementNotation", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setImprovementNotation, setText"} **/
						));
Measurereportobj.setCode(HapiFHIRHelpers.createCodeableConcept(measurereport.getMsrRprtGrpCdCcCdngCSstm() /** { "tree" :"MeasureReport.group.code", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : ["addGroup"] , "methodName" : "setCode, addCoding, setSystem"} **/
						, measurereport.getMsrRprtGrpCdCcCdngCVrsn() /** { "tree" :"MeasureReport.group.code", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addGroup"] , "methodName" : "setCode, addCoding, setVersion"} **/
						, measurereport.getMsrRprtGrpCdCcCdngCCde() /** { "tree" :"MeasureReport.group.code", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : ["addGroup"] , "methodName" : "setCode, addCoding, setCode"} **/
						, measurereport.getMsrRprtGrpCdCcCdngCDsplay() /** { "tree" :"MeasureReport.group.code", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addGroup"] , "methodName" : "setCode, addCoding, setDisplay"} **/
						, measurereport.getMsrRprtGrpCdCcCdngCSrSlctd() /** { "tree" :"MeasureReport.group.code", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : ["addGroup"] , "methodName" : "setCode, addCoding, setUserSelected"} **/
						, measurereport.getMeasureReportGroupCodeCcText() /** { "tree" :"MeasureReport.group.code", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : ["addGroup"] , "methodName" : "setCode, setText"} **/
						, measurereport.getMsrRprtGrpPpltnCdCcCdngCSstm() /** { "tree" :"MeasureReport.group.population.code", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : ["addGroup", "addPopulation"] , "methodName" : "setCode, addCoding, setSystem"} **/
						, measurereport.getMsrRprtGrpPpltnCdCcCdngCVrsn() /** { "tree" :"MeasureReport.group.population.code", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addGroup", "addPopulation"] , "methodName" : "setCode, addCoding, setVersion"} **/
						, measurereport.getMsrRprtGrpPpltnCdCcCdngCCde() /** { "tree" :"MeasureReport.group.population.code", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : ["addGroup", "addPopulation"] , "methodName" : "setCode, addCoding, setCode"} **/
						, measurereport.getMsrRprtGrpPpltnCdCcCdngCDsplay() /** { "tree" :"MeasureReport.group.population.code", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addGroup", "addPopulation"] , "methodName" : "setCode, addCoding, setDisplay"} **/
						, measurereport.getMsrRprtGrpPpltnCdCcCdngCSrSlctd() /** { "tree" :"MeasureReport.group.population.code", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : ["addGroup", "addPopulation"] , "methodName" : "setCode, addCoding, setUserSelected"} **/
						, measurereport.getMsrRprtGrpPpltnCdCcTxt() /** { "tree" :"MeasureReport.group.population.code", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : ["addGroup", "addPopulation"] , "methodName" : "setCode, setText"} **/
						));
Measurereportobj.setCount(HapiFHIRHelpers.createinteger(measurereport.getMsrRprtGrpPpltnCntNtgr() /** { "tree" :"MeasureReport.group.population.count", "datatype" : "integer", "cardinality" : "ZeroOne", "elementtree" : ["addGroup", "addPopulation"] , "methodName" : "setCount"} **/
						));
Measurereportobj.setSubjectResults(HapiFHIRHelpers.createReference(measurereport.getMsrRprtGrpPpltnSbjctRsltsRfrnce() /** { "tree" :"MeasureReport.group.population.subjectResults", "datatype" : "Reference", "cardinality" : "ZeroOne", "elementtree" : ["addGroup", "addPopulation"] , "methodName" : "setSubjectResults"} **/
						));
Measurereportobj.setMeasureScore(HapiFHIRHelpers.createQuantity(measurereport.getMsrRprtGrpMsrScrQnttCmprtr() /** { "tree" :"MeasureReport.group.measureScore", "datatype" : "Quantity, code", "cardinality" : "ZeroOne", "elementtree" : ["addGroup", "addPopulation"] , "methodName" : "setMeasureScore, setComparator"} **/
						, measurereport.getMsrRprtGrpMsrScrQnttCde() /** { "tree" :"MeasureReport.group.measureScore", "datatype" : "Quantity, code", "cardinality" : "ZeroOne", "elementtree" : ["addGroup", "addPopulation"] , "methodName" : "setMeasureScore, setCode"} **/
						, measurereport.getMsrRprtGrpMsrScrQnttVlue() /** { "tree" :"MeasureReport.group.measureScore", "datatype" : "Quantity, decimal", "cardinality" : "ZeroOne", "elementtree" : ["addGroup", "addPopulation"] , "methodName" : "setMeasureScore, setValue"} **/
						, measurereport.getMsrRprtGrpMsrScrQnttNt() /** { "tree" :"MeasureReport.group.measureScore", "datatype" : "Quantity, string", "cardinality" : "ZeroOne", "elementtree" : ["addGroup", "addPopulation"] , "methodName" : "setMeasureScore, setUnit"} **/
						, measurereport.getMsrRprtGrpMsrScrQnttSstm() /** { "tree" :"MeasureReport.group.measureScore", "datatype" : "Quantity, uri", "cardinality" : "ZeroOne", "elementtree" : ["addGroup", "addPopulation"] , "methodName" : "setMeasureScore, setSystem"} **/
						));
Measurereportobj.addCode(HapiFHIRHelpers.createCodeableConcept(measurereport.getMsrRprtGrpStrtfrCdCcCdngCSstm() /** { "tree" :"MeasureReport.group.stratifier.code", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "Many", "elementtree" : ["addGroup", "addPopulation", "addStratifier"] , "methodName" : "addCode, addCoding, setSystem"} **/
						, measurereport.getMsrRprtGrpStrtfrCdCcCdngCVrsn() /** { "tree" :"MeasureReport.group.stratifier.code", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Many", "elementtree" : ["addGroup", "addPopulation", "addStratifier"] , "methodName" : "addCode, addCoding, setVersion"} **/
						, measurereport.getMsrRprtGrpStrtfrCdCcCdngCCde() /** { "tree" :"MeasureReport.group.stratifier.code", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "Many", "elementtree" : ["addGroup", "addPopulation", "addStratifier"] , "methodName" : "addCode, addCoding, setCode"} **/
						, measurereport.getMsrRprtGrpStrtfrCdCcCdngCDsplay() /** { "tree" :"MeasureReport.group.stratifier.code", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Many", "elementtree" : ["addGroup", "addPopulation", "addStratifier"] , "methodName" : "addCode, addCoding, setDisplay"} **/
						, measurereport.getMsrRprtGrpStrtfrCdCcCdngCSrSlctd() /** { "tree" :"MeasureReport.group.stratifier.code", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "Many", "elementtree" : ["addGroup", "addPopulation", "addStratifier"] , "methodName" : "addCode, addCoding, setUserSelected"} **/
						, measurereport.getMsrRprtGrpStrtfrCdCcTxt() /** { "tree" :"MeasureReport.group.stratifier.code", "datatype" : "CodeableConcept, string", "cardinality" : "Many", "elementtree" : ["addGroup", "addPopulation", "addStratifier"] , "methodName" : "addCode, setText"} **/
						));
Measurereportobj.setValue(HapiFHIRHelpers.createCodeableConcept(measurereport.getMsrRprtGrpStrtfrStrtmVlCcCdngCSstm() /** { "tree" :"MeasureReport.group.stratifier.stratum.value", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : ["addGroup", "addPopulation", "addStratifier", "addStratum"] , "methodName" : "setValue, addCoding, setSystem"} **/
						, measurereport.getMsrRprtGrpStrtfrStrtmVlCcCdngCVrsn() /** { "tree" :"MeasureReport.group.stratifier.stratum.value", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addGroup", "addPopulation", "addStratifier", "addStratum"] , "methodName" : "setValue, addCoding, setVersion"} **/
						, measurereport.getMsrRprtGrpStrtfrStrtmVlCcCdngCCde() /** { "tree" :"MeasureReport.group.stratifier.stratum.value", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : ["addGroup", "addPopulation", "addStratifier", "addStratum"] , "methodName" : "setValue, addCoding, setCode"} **/
						, measurereport.getMsrRprtGrpStrtfrStrtmVlCcCdngCDsplay() /** { "tree" :"MeasureReport.group.stratifier.stratum.value", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addGroup", "addPopulation", "addStratifier", "addStratum"] , "methodName" : "setValue, addCoding, setDisplay"} **/
						, measurereport.getMsrRprtGrpStrtfrStrtmVlCcCdngCSrSlctd() /** { "tree" :"MeasureReport.group.stratifier.stratum.value", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : ["addGroup", "addPopulation", "addStratifier", "addStratum"] , "methodName" : "setValue, addCoding, setUserSelected"} **/
						, measurereport.getMsrRprtGrpStrtfrStrtmVlCcTxt() /** { "tree" :"MeasureReport.group.stratifier.stratum.value", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : ["addGroup", "addPopulation", "addStratifier", "addStratum"] , "methodName" : "setValue, setText"} **/
						));
Measurereportobj.setCode(HapiFHIRHelpers.createCodeableConcept(measurereport.getMsrRprtGrpStrtfrStrtmCmpnntCdCcCdngCSstm() /** { "tree" :"MeasureReport.group.stratifier.stratum.component.code", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "Required", "elementtree" : ["addGroup", "addPopulation", "addStratifier", "addStratum", "addComponent"] , "methodName" : "setCode, addCoding, setSystem"} **/
						, measurereport.getMsrRprtGrpStrtfrStrtmCmpnntCdCcCdngCVrsn() /** { "tree" :"MeasureReport.group.stratifier.stratum.component.code", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Required", "elementtree" : ["addGroup", "addPopulation", "addStratifier", "addStratum", "addComponent"] , "methodName" : "setCode, addCoding, setVersion"} **/
						, measurereport.getMsrRprtGrpStrtfrStrtmCmpnntCdCcCdngCCde() /** { "tree" :"MeasureReport.group.stratifier.stratum.component.code", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "Required", "elementtree" : ["addGroup", "addPopulation", "addStratifier", "addStratum", "addComponent"] , "methodName" : "setCode, addCoding, setCode"} **/
						, measurereport.getMsrRprtGrpStrtfrStrtmCmpnntCdCcCdngCDsplay() /** { "tree" :"MeasureReport.group.stratifier.stratum.component.code", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Required", "elementtree" : ["addGroup", "addPopulation", "addStratifier", "addStratum", "addComponent"] , "methodName" : "setCode, addCoding, setDisplay"} **/
						, measurereport.getMsrRprtGrpStrtfrStrtmCmpnntCdCcCdngCSrSlctd() /** { "tree" :"MeasureReport.group.stratifier.stratum.component.code", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "Required", "elementtree" : ["addGroup", "addPopulation", "addStratifier", "addStratum", "addComponent"] , "methodName" : "setCode, addCoding, setUserSelected"} **/
						, measurereport.getMsrRprtGrpStrtfrStrtmCmpnntCdCcTxt() /** { "tree" :"MeasureReport.group.stratifier.stratum.component.code", "datatype" : "CodeableConcept, string", "cardinality" : "Required", "elementtree" : ["addGroup", "addPopulation", "addStratifier", "addStratum", "addComponent"] , "methodName" : "setCode, setText"} **/
						));
Measurereportobj.setValue(HapiFHIRHelpers.createCodeableConcept(measurereport.getMsrRprtGrpStrtfrStrtmCmpnntVlCcCdngCSstm() /** { "tree" :"MeasureReport.group.stratifier.stratum.component.value", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "Required", "elementtree" : ["addGroup", "addPopulation", "addStratifier", "addStratum", "addComponent"] , "methodName" : "setValue, addCoding, setSystem"} **/
						, measurereport.getMsrRprtGrpStrtfrStrtmCmpnntVlCcCdngCVrsn() /** { "tree" :"MeasureReport.group.stratifier.stratum.component.value", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Required", "elementtree" : ["addGroup", "addPopulation", "addStratifier", "addStratum", "addComponent"] , "methodName" : "setValue, addCoding, setVersion"} **/
						, measurereport.getMsrRprtGrpStrtfrStrtmCmpnntVlCcCdngCCde() /** { "tree" :"MeasureReport.group.stratifier.stratum.component.value", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "Required", "elementtree" : ["addGroup", "addPopulation", "addStratifier", "addStratum", "addComponent"] , "methodName" : "setValue, addCoding, setCode"} **/
						, measurereport.getMsrRprtGrpStrtfrStrtmCmpnntVlCcCdngCDsplay() /** { "tree" :"MeasureReport.group.stratifier.stratum.component.value", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Required", "elementtree" : ["addGroup", "addPopulation", "addStratifier", "addStratum", "addComponent"] , "methodName" : "setValue, addCoding, setDisplay"} **/
						, measurereport.getMsrRprtGrpStrtfrStrtmCmpnntVlCcCdngCSrSlctd() /** { "tree" :"MeasureReport.group.stratifier.stratum.component.value", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "Required", "elementtree" : ["addGroup", "addPopulation", "addStratifier", "addStratum", "addComponent"] , "methodName" : "setValue, addCoding, setUserSelected"} **/
						, measurereport.getMsrRprtGrpStrtfrStrtmCmpnntVlCcTxt() /** { "tree" :"MeasureReport.group.stratifier.stratum.component.value", "datatype" : "CodeableConcept, string", "cardinality" : "Required", "elementtree" : ["addGroup", "addPopulation", "addStratifier", "addStratum", "addComponent"] , "methodName" : "setValue, setText"} **/
						));
Measurereportobj.setCode(HapiFHIRHelpers.createCodeableConcept(measurereport.getMsrRprtGrpStrtfrStrtmPpltnCdCcCdngCSstm() /** { "tree" :"MeasureReport.group.stratifier.stratum.population.code", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : ["addGroup", "addPopulation", "addStratifier", "addStratum", "addComponent", "addPopulation"] , "methodName" : "setCode, addCoding, setSystem"} **/
						, measurereport.getMsrRprtGrpStrtfrStrtmPpltnCdCcCdngCVrsn() /** { "tree" :"MeasureReport.group.stratifier.stratum.population.code", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addGroup", "addPopulation", "addStratifier", "addStratum", "addComponent", "addPopulation"] , "methodName" : "setCode, addCoding, setVersion"} **/
						, measurereport.getMsrRprtGrpStrtfrStrtmPpltnCdCcCdngCCde() /** { "tree" :"MeasureReport.group.stratifier.stratum.population.code", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : ["addGroup", "addPopulation", "addStratifier", "addStratum", "addComponent", "addPopulation"] , "methodName" : "setCode, addCoding, setCode"} **/
						, measurereport.getMsrRprtGrpStrtfrStrtmPpltnCdCcCdngCDsplay() /** { "tree" :"MeasureReport.group.stratifier.stratum.population.code", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addGroup", "addPopulation", "addStratifier", "addStratum", "addComponent", "addPopulation"] , "methodName" : "setCode, addCoding, setDisplay"} **/
						, measurereport.getMsrRprtGrpStrtfrStrtmPpltnCdCcCdngCSrSlctd() /** { "tree" :"MeasureReport.group.stratifier.stratum.population.code", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : ["addGroup", "addPopulation", "addStratifier", "addStratum", "addComponent", "addPopulation"] , "methodName" : "setCode, addCoding, setUserSelected"} **/
						, measurereport.getMsrRprtGrpStrtfrStrtmPpltnCdCcTxt() /** { "tree" :"MeasureReport.group.stratifier.stratum.population.code", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : ["addGroup", "addPopulation", "addStratifier", "addStratum", "addComponent", "addPopulation"] , "methodName" : "setCode, setText"} **/
						));
Measurereportobj.setCount(HapiFHIRHelpers.createinteger(measurereport.getMsrRprtGrpStrtfrStrtmPpltnCntNtgr() /** { "tree" :"MeasureReport.group.stratifier.stratum.population.count", "datatype" : "integer", "cardinality" : "ZeroOne", "elementtree" : ["addGroup", "addPopulation", "addStratifier", "addStratum", "addComponent", "addPopulation"] , "methodName" : "setCount"} **/
						));
Measurereportobj.setSubjectResults(HapiFHIRHelpers.createReference(measurereport.getMsrRprtGrpStrtfrStrtmPpltnSbjctRsltsRfrnce() /** { "tree" :"MeasureReport.group.stratifier.stratum.population.subjectResults", "datatype" : "Reference", "cardinality" : "ZeroOne", "elementtree" : ["addGroup", "addPopulation", "addStratifier", "addStratum", "addComponent", "addPopulation"] , "methodName" : "setSubjectResults"} **/
						));
Measurereportobj.setMeasureScore(HapiFHIRHelpers.createQuantity(measurereport.getMsrRprtGrpStrtfrStrtmMsrScrQnttCmprtr() /** { "tree" :"MeasureReport.group.stratifier.stratum.measureScore", "datatype" : "Quantity, code", "cardinality" : "ZeroOne", "elementtree" : ["addGroup", "addPopulation", "addStratifier", "addStratum", "addComponent", "addPopulation"] , "methodName" : "setMeasureScore, setComparator"} **/
						, measurereport.getMsrRprtGrpStrtfrStrtmMsrScrQnttCde() /** { "tree" :"MeasureReport.group.stratifier.stratum.measureScore", "datatype" : "Quantity, code", "cardinality" : "ZeroOne", "elementtree" : ["addGroup", "addPopulation", "addStratifier", "addStratum", "addComponent", "addPopulation"] , "methodName" : "setMeasureScore, setCode"} **/
						, measurereport.getMsrRprtGrpStrtfrStrtmMsrScrQnttVlue() /** { "tree" :"MeasureReport.group.stratifier.stratum.measureScore", "datatype" : "Quantity, decimal", "cardinality" : "ZeroOne", "elementtree" : ["addGroup", "addPopulation", "addStratifier", "addStratum", "addComponent", "addPopulation"] , "methodName" : "setMeasureScore, setValue"} **/
						, measurereport.getMsrRprtGrpStrtfrStrtmMsrScrQnttNt() /** { "tree" :"MeasureReport.group.stratifier.stratum.measureScore", "datatype" : "Quantity, string", "cardinality" : "ZeroOne", "elementtree" : ["addGroup", "addPopulation", "addStratifier", "addStratum", "addComponent", "addPopulation"] , "methodName" : "setMeasureScore, setUnit"} **/
						, measurereport.getMsrRprtGrpStrtfrStrtmMsrScrQnttSstm() /** { "tree" :"MeasureReport.group.stratifier.stratum.measureScore", "datatype" : "Quantity, uri", "cardinality" : "ZeroOne", "elementtree" : ["addGroup", "addPopulation", "addStratifier", "addStratum", "addComponent", "addPopulation"] , "methodName" : "setMeasureScore, setSystem"} **/
						));
Measurereportobj.addEvaluatedResource(HapiFHIRHelpers.createReference(measurereport.getMsrRprtVltdRsrcRfrnce() /** { "tree" :"MeasureReport.evaluatedResource", "datatype" : "Reference", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addEvaluatedResource"} **/
		));
	}
}
