package main.templateoutput.Conversions;
// Generated on Jan 28, 2022, 8:02:40 AM 


import org.hl7.fhir.r4.model.Patient;

/**
 *  object for conversion model class Medicationknowledge.
 * @see .Medicationknowledge
 * @author Paul Kovach
 */
import main.java.com.campfhir.service.conversion.HapiFHIRHelpers;

public class MedicationknowledgeConversion 
{
	public Patient Medicationknowledges(main.templateoutput.Model.Medicationknowledge medicationknowledge) 
	{
			Patient  Medicationknowledgeobj = new Patient(); 

						Medicationknowledgeobj.setCode(HapiFHIRHelpers.createCodeableConcept(medicationknowledge.getMkCodeCcCodingCSystem() /** { "tree" :"MedicationKnowledge.code", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setCode, addCoding, setSystem"} **/
						, medicationknowledge.getMkCodeCcCodingCVersion() /** { "tree" :"MedicationKnowledge.code", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setCode, addCoding, setVersion"} **/
						, medicationknowledge.getMkCodeCcCodingCCode() /** { "tree" :"MedicationKnowledge.code", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setCode, addCoding, setCode"} **/
						, medicationknowledge.getMkCodeCcCodingCDisplay() /** { "tree" :"MedicationKnowledge.code", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setCode, addCoding, setDisplay"} **/
						, medicationknowledge.getMkCodeCcCodingCUserSelected() /** { "tree" :"MedicationKnowledge.code", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setCode, addCoding, setUserSelected"} **/
						, medicationknowledge.getMkCodeCcText() /** { "tree" :"MedicationKnowledge.code", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setCode, setText"} **/
						));
Medicationknowledgeobj.setStatus(HapiFHIRHelpers.createcode(medicationknowledge.getMkStatusCode() /** { "tree" :"MedicationKnowledge.status", "datatype" : "code", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setStatus"} **/
						));
Medicationknowledgeobj.setManufacturer(HapiFHIRHelpers.createReference(medicationknowledge.getMkManufacturerReference() /** { "tree" :"MedicationKnowledge.manufacturer", "datatype" : "Reference", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setManufacturer"} **/
						));
Medicationknowledgeobj.setDoseForm(HapiFHIRHelpers.createCodeableConcept(medicationknowledge.getMkDoseFormCcCodingCSystem() /** { "tree" :"MedicationKnowledge.doseForm", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setDoseForm, addCoding, setSystem"} **/
						, medicationknowledge.getMkDoseFormCcCodingCVersion() /** { "tree" :"MedicationKnowledge.doseForm", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setDoseForm, addCoding, setVersion"} **/
						, medicationknowledge.getMkDoseFormCcCodingCCode() /** { "tree" :"MedicationKnowledge.doseForm", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setDoseForm, addCoding, setCode"} **/
						, medicationknowledge.getMkDoseFormCcCodingCDisplay() /** { "tree" :"MedicationKnowledge.doseForm", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setDoseForm, addCoding, setDisplay"} **/
						, medicationknowledge.getMkDsFrmCcCdngCSrSlctd() /** { "tree" :"MedicationKnowledge.doseForm", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setDoseForm, addCoding, setUserSelected"} **/
						, medicationknowledge.getMkDoseFormCcText() /** { "tree" :"MedicationKnowledge.doseForm", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setDoseForm, setText"} **/
						));
Medicationknowledgeobj.setAmount(HapiFHIRHelpers.createSimpleQuantity(medicationknowledge.getMkAmountSimpleQuantity() /** { "tree" :"MedicationKnowledge.amount", "datatype" : "SimpleQuantity", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setAmount"} **/
						));
Medicationknowledgeobj.addSynonym(HapiFHIRHelpers.createstring(medicationknowledge.getMkSynonymString() /** { "tree" :"MedicationKnowledge.synonym", "datatype" : "string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addSynonym"} **/
						));
Medicationknowledgeobj.setType(HapiFHIRHelpers.createCodeableConcept(medicationknowledge.getMkRltdMkTpCcCdngCSstm() /** { "tree" :"MedicationKnowledge.relatedMedicationKnowledge.type", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "Required", "elementtree" : ["addRelatedMedicationKnowledge"] , "methodName" : "setType, addCoding, setSystem"} **/
						, medicationknowledge.getMkRltdMkTpCcCdngCVrsn() /** { "tree" :"MedicationKnowledge.relatedMedicationKnowledge.type", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Required", "elementtree" : ["addRelatedMedicationKnowledge"] , "methodName" : "setType, addCoding, setVersion"} **/
						, medicationknowledge.getMkRelatedMkTypeCcCodingCCode() /** { "tree" :"MedicationKnowledge.relatedMedicationKnowledge.type", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "Required", "elementtree" : ["addRelatedMedicationKnowledge"] , "methodName" : "setType, addCoding, setCode"} **/
						, medicationknowledge.getMkRltdMkTpCcCdngCDsplay() /** { "tree" :"MedicationKnowledge.relatedMedicationKnowledge.type", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Required", "elementtree" : ["addRelatedMedicationKnowledge"] , "methodName" : "setType, addCoding, setDisplay"} **/
						, medicationknowledge.getMkRltdMkTpCcCdngCSrSlctd() /** { "tree" :"MedicationKnowledge.relatedMedicationKnowledge.type", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "Required", "elementtree" : ["addRelatedMedicationKnowledge"] , "methodName" : "setType, addCoding, setUserSelected"} **/
						, medicationknowledge.getMkRelatedMkTypeCcText() /** { "tree" :"MedicationKnowledge.relatedMedicationKnowledge.type", "datatype" : "CodeableConcept, string", "cardinality" : "Required", "elementtree" : ["addRelatedMedicationKnowledge"] , "methodName" : "setType, setText"} **/
						));
Medicationknowledgeobj.setReference(HapiFHIRHelpers.createReference(medicationknowledge.getMkRelatedMkReferenceReference() /** { "tree" :"MedicationKnowledge.relatedMedicationKnowledge.reference", "datatype" : "Reference", "cardinality" : "Required", "elementtree" : ["addRelatedMedicationKnowledge"] , "methodName" : "setReference"} **/
						));
Medicationknowledgeobj.addAssociatedMedication(HapiFHIRHelpers.createReference(medicationknowledge.getMkAssociatedMedReference() /** { "tree" :"MedicationKnowledge.associatedMedication", "datatype" : "Reference", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addAssociatedMedication"} **/
						));
Medicationknowledgeobj.addProductType(HapiFHIRHelpers.createCodeableConcept(medicationknowledge.getMkProductTypeCcCodingCSystem() /** { "tree" :"MedicationKnowledge.productType", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addProductType, addCoding, setSystem"} **/
						, medicationknowledge.getMkProductTypeCcCodingCVersion() /** { "tree" :"MedicationKnowledge.productType", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addProductType, addCoding, setVersion"} **/
						, medicationknowledge.getMkProductTypeCcCodingCCode() /** { "tree" :"MedicationKnowledge.productType", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addProductType, addCoding, setCode"} **/
						, medicationknowledge.getMkProductTypeCcCodingCDisplay() /** { "tree" :"MedicationKnowledge.productType", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addProductType, addCoding, setDisplay"} **/
						, medicationknowledge.getMkPrdctTpCcCdngCSrSlctd() /** { "tree" :"MedicationKnowledge.productType", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addProductType, addCoding, setUserSelected"} **/
						, medicationknowledge.getMkProductTypeCcText() /** { "tree" :"MedicationKnowledge.productType", "datatype" : "CodeableConcept, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addProductType, setText"} **/
						));
Medicationknowledgeobj.setType(HapiFHIRHelpers.createCodeableConcept(medicationknowledge.getMkMngrphTpCcCdngCSstm() /** { "tree" :"MedicationKnowledge.monograph.type", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : ["addMonograph"] , "methodName" : "setType, addCoding, setSystem"} **/
						, medicationknowledge.getMkMngrphTpCcCdngCVrsn() /** { "tree" :"MedicationKnowledge.monograph.type", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addMonograph"] , "methodName" : "setType, addCoding, setVersion"} **/
						, medicationknowledge.getMkMonographTypeCcCodingCCode() /** { "tree" :"MedicationKnowledge.monograph.type", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : ["addMonograph"] , "methodName" : "setType, addCoding, setCode"} **/
						, medicationknowledge.getMkMngrphTpCcCdngCDsplay() /** { "tree" :"MedicationKnowledge.monograph.type", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addMonograph"] , "methodName" : "setType, addCoding, setDisplay"} **/
						, medicationknowledge.getMkMngrphTpCcCdngCSrSlctd() /** { "tree" :"MedicationKnowledge.monograph.type", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : ["addMonograph"] , "methodName" : "setType, addCoding, setUserSelected"} **/
						, medicationknowledge.getMkMonographTypeCcText() /** { "tree" :"MedicationKnowledge.monograph.type", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : ["addMonograph"] , "methodName" : "setType, setText"} **/
						));
Medicationknowledgeobj.setSource(HapiFHIRHelpers.createReference(medicationknowledge.getMkMonographSourceReference() /** { "tree" :"MedicationKnowledge.monograph.source", "datatype" : "Reference", "cardinality" : "ZeroOne", "elementtree" : ["addMonograph"] , "methodName" : "setSource"} **/
						));
Medicationknowledgeobj.setItemCodeableconcept(HapiFHIRHelpers.createCodeableConcept(medicationknowledge.getMkNgrdntTmCdblcncptCcCdngCSstm() /** { "tree" :"MedicationKnowledge.ingredient.itemCodeableconcept", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "Required", "elementtree" : ["addIngredient"] , "methodName" : "setItemCodeableconcept, addCoding, setSystem"} **/
						, medicationknowledge.getMkNgrdntTmCdblcncptCcCdngCVrsn() /** { "tree" :"MedicationKnowledge.ingredient.itemCodeableconcept", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Required", "elementtree" : ["addIngredient"] , "methodName" : "setItemCodeableconcept, addCoding, setVersion"} **/
						, medicationknowledge.getMkNgrdntTmCdblcncptCcCdngCCde() /** { "tree" :"MedicationKnowledge.ingredient.itemCodeableconcept", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "Required", "elementtree" : ["addIngredient"] , "methodName" : "setItemCodeableconcept, addCoding, setCode"} **/
						, medicationknowledge.getMkNgrdntTmCdblcncptCcCdngCDsplay() /** { "tree" :"MedicationKnowledge.ingredient.itemCodeableconcept", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Required", "elementtree" : ["addIngredient"] , "methodName" : "setItemCodeableconcept, addCoding, setDisplay"} **/
						, medicationknowledge.getMkNgrdntTmCdblcncptCcCdngCSrSlctd() /** { "tree" :"MedicationKnowledge.ingredient.itemCodeableconcept", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "Required", "elementtree" : ["addIngredient"] , "methodName" : "setItemCodeableconcept, addCoding, setUserSelected"} **/
						, medicationknowledge.getMkNgrdntTmCdblcncptCcTxt() /** { "tree" :"MedicationKnowledge.ingredient.itemCodeableconcept", "datatype" : "CodeableConcept, string", "cardinality" : "Required", "elementtree" : ["addIngredient"] , "methodName" : "setItemCodeableconcept, setText"} **/
						));
Medicationknowledgeobj.setItemReference(substance)(HapiFHIRHelpers.createReference(medicationknowledge.getMkNgrdntTmRfrncRfrnce() /** { "tree" :"MedicationKnowledge.ingredient.itemReference", "datatype" : "Reference", "cardinality" : "Required", "elementtree" : ["addIngredient"] , "methodName" : "setItemReference(substance)"} **/
						));
Medicationknowledgeobj.setIsActive(HapiFHIRHelpers.createboolean(medicationknowledge.getMkIngredientIsActiveBoolean() /** { "tree" :"MedicationKnowledge.ingredient.isActive", "datatype" : "boolean", "cardinality" : "ZeroOne", "elementtree" : ["addIngredient"] , "methodName" : "setIsActive"} **/
						));
Medicationknowledgeobj.setStrength(HapiFHIRHelpers.createRatio(medicationknowledge.getMkNgrdntStrRtNmrtrQnttVlue() /** { "tree" :"MedicationKnowledge.ingredient.strength", "datatype" : "Ratio, Quantity, decimal", "cardinality" : "ZeroOne", "elementtree" : ["addIngredient"] , "methodName" : "setStrength, setNumerator, setValue"} **/
						, medicationknowledge.getMkNgrdntStrRtDnmntrQnttVlue() /** { "tree" :"MedicationKnowledge.ingredient.strength", "datatype" : "Ratio, Quantity, decimal", "cardinality" : "ZeroOne", "elementtree" : ["addIngredient"] , "methodName" : "setStrength, setDenominator, setValue"} **/
						, medicationknowledge.getMkNgrdntStrRtNmrtrQnttCmprtr() /** { "tree" :"MedicationKnowledge.ingredient.strength", "datatype" : "Ratio, Quantity, code", "cardinality" : "ZeroOne", "elementtree" : ["addIngredient"] , "methodName" : "setStrength, setNumerator, setComparator"} **/
						, medicationknowledge.getMkNgrdntStrRtDnmntrQnttCmprtr() /** { "tree" :"MedicationKnowledge.ingredient.strength", "datatype" : "Ratio, Quantity, code", "cardinality" : "ZeroOne", "elementtree" : ["addIngredient"] , "methodName" : "setStrength, setDenominator, setComparator"} **/
						, medicationknowledge.getMkNgrdntStrRtNmrtrQnttNt() /** { "tree" :"MedicationKnowledge.ingredient.strength", "datatype" : "Ratio, Quantity, string", "cardinality" : "ZeroOne", "elementtree" : ["addIngredient"] , "methodName" : "setStrength, setNumerator, setUnit"} **/
						, medicationknowledge.getMkNgrdntStrRtDnmntrQnttNt() /** { "tree" :"MedicationKnowledge.ingredient.strength", "datatype" : "Ratio, Quantity, string", "cardinality" : "ZeroOne", "elementtree" : ["addIngredient"] , "methodName" : "setStrength, setDenominator, setUnit"} **/
						, medicationknowledge.getMkNgrdntStrRtNmrtrQnttSstm() /** { "tree" :"MedicationKnowledge.ingredient.strength", "datatype" : "Ratio, Quantity, uri", "cardinality" : "ZeroOne", "elementtree" : ["addIngredient"] , "methodName" : "setStrength, setNumerator, setSystem"} **/
						, medicationknowledge.getMkNgrdntStrRtDnmntrQnttSstm() /** { "tree" :"MedicationKnowledge.ingredient.strength", "datatype" : "Ratio, Quantity, uri", "cardinality" : "ZeroOne", "elementtree" : ["addIngredient"] , "methodName" : "setStrength, setDenominator, setSystem"} **/
						, medicationknowledge.getMkNgrdntStrRtNmrtrQnttCde() /** { "tree" :"MedicationKnowledge.ingredient.strength", "datatype" : "Ratio, Quantity, code", "cardinality" : "ZeroOne", "elementtree" : ["addIngredient"] , "methodName" : "setStrength, setNumerator, setCode"} **/
						, medicationknowledge.getMkNgrdntStrRtDnmntrQnttCde() /** { "tree" :"MedicationKnowledge.ingredient.strength", "datatype" : "Ratio, Quantity, code", "cardinality" : "ZeroOne", "elementtree" : ["addIngredient"] , "methodName" : "setStrength, setDenominator, setCode"} **/
						));
Medicationknowledgeobj.setPreparationInstruction(HapiFHIRHelpers.createmarkdown(medicationknowledge.getMkPreparationInstructionMarkdown() /** { "tree" :"MedicationKnowledge.preparationInstruction", "datatype" : "markdown", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setPreparationInstruction"} **/
						));
Medicationknowledgeobj.addIntendedRoute(HapiFHIRHelpers.createCodeableConcept(medicationknowledge.getMkNtnddRtCcCdngCSstm() /** { "tree" :"MedicationKnowledge.intendedRoute", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIntendedRoute, addCoding, setSystem"} **/
						, medicationknowledge.getMkNtnddRtCcCdngCVrsn() /** { "tree" :"MedicationKnowledge.intendedRoute", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIntendedRoute, addCoding, setVersion"} **/
						, medicationknowledge.getMkIntendedRouteCcCodingCCode() /** { "tree" :"MedicationKnowledge.intendedRoute", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIntendedRoute, addCoding, setCode"} **/
						, medicationknowledge.getMkNtnddRtCcCdngCDsplay() /** { "tree" :"MedicationKnowledge.intendedRoute", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIntendedRoute, addCoding, setDisplay"} **/
						, medicationknowledge.getMkNtnddRtCcCdngCSrSlctd() /** { "tree" :"MedicationKnowledge.intendedRoute", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIntendedRoute, addCoding, setUserSelected"} **/
						, medicationknowledge.getMkIntendedRouteCcText() /** { "tree" :"MedicationKnowledge.intendedRoute", "datatype" : "CodeableConcept, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIntendedRoute, setText"} **/
						));
Medicationknowledgeobj.setType(HapiFHIRHelpers.createCodeableConcept(medicationknowledge.getMkCostTypeCcCodingCSystem() /** { "tree" :"MedicationKnowledge.cost.type", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "Required", "elementtree" : ["addCost"] , "methodName" : "setType, addCoding, setSystem"} **/
						, medicationknowledge.getMkCostTypeCcCodingCVersion() /** { "tree" :"MedicationKnowledge.cost.type", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Required", "elementtree" : ["addCost"] , "methodName" : "setType, addCoding, setVersion"} **/
						, medicationknowledge.getMkCostTypeCcCodingCCode() /** { "tree" :"MedicationKnowledge.cost.type", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "Required", "elementtree" : ["addCost"] , "methodName" : "setType, addCoding, setCode"} **/
						, medicationknowledge.getMkCostTypeCcCodingCDisplay() /** { "tree" :"MedicationKnowledge.cost.type", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Required", "elementtree" : ["addCost"] , "methodName" : "setType, addCoding, setDisplay"} **/
						, medicationknowledge.getMkCstTpCcCdngCSrSlctd() /** { "tree" :"MedicationKnowledge.cost.type", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "Required", "elementtree" : ["addCost"] , "methodName" : "setType, addCoding, setUserSelected"} **/
						, medicationknowledge.getMkCostTypeCcText() /** { "tree" :"MedicationKnowledge.cost.type", "datatype" : "CodeableConcept, string", "cardinality" : "Required", "elementtree" : ["addCost"] , "methodName" : "setType, setText"} **/
						));
Medicationknowledgeobj.setSource(HapiFHIRHelpers.createstring(medicationknowledge.getMkCostSourceString() /** { "tree" :"MedicationKnowledge.cost.source", "datatype" : "string", "cardinality" : "ZeroOne", "elementtree" : ["addCost"] , "methodName" : "setSource"} **/
						));
Medicationknowledgeobj.setCost(HapiFHIRHelpers.createMoney(medicationknowledge.getMkCostCostMoneyCurrency() /** { "tree" :"MedicationKnowledge.cost.cost", "datatype" : "Money, code", "cardinality" : "Required", "elementtree" : ["addCost"] , "methodName" : "setCost, setCurrency"} **/
						, medicationknowledge.getMkCostCostMoneyValue() /** { "tree" :"MedicationKnowledge.cost.cost", "datatype" : "Money, decimal", "cardinality" : "Required", "elementtree" : ["addCost"] , "methodName" : "setCost, setVal"} **/
						));
Medicationknowledgeobj.setType(HapiFHIRHelpers.createCodeableConcept(medicationknowledge.getMkMntrngPrgrmTpCcCdngCSstm() /** { "tree" :"MedicationKnowledge.monitoringProgram.type", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : ["addMonitoringProgram"] , "methodName" : "setType, addCoding, setSystem"} **/
						, medicationknowledge.getMkMntrngPrgrmTpCcCdngCVrsn() /** { "tree" :"MedicationKnowledge.monitoringProgram.type", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addMonitoringProgram"] , "methodName" : "setType, addCoding, setVersion"} **/
						, medicationknowledge.getMkMntrngPrgrmTpCcCdngCCde() /** { "tree" :"MedicationKnowledge.monitoringProgram.type", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : ["addMonitoringProgram"] , "methodName" : "setType, addCoding, setCode"} **/
						, medicationknowledge.getMkMntrngPrgrmTpCcCdngCDsplay() /** { "tree" :"MedicationKnowledge.monitoringProgram.type", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addMonitoringProgram"] , "methodName" : "setType, addCoding, setDisplay"} **/
						, medicationknowledge.getMkMntrngPrgrmTpCcCdngCSrSlctd() /** { "tree" :"MedicationKnowledge.monitoringProgram.type", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : ["addMonitoringProgram"] , "methodName" : "setType, addCoding, setUserSelected"} **/
						, medicationknowledge.getMkMonitoringProgramTypeCcText() /** { "tree" :"MedicationKnowledge.monitoringProgram.type", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : ["addMonitoringProgram"] , "methodName" : "setType, setText"} **/
						));
Medicationknowledgeobj.setName(HapiFHIRHelpers.createstring(medicationknowledge.getMkMonitoringProgramNameString() /** { "tree" :"MedicationKnowledge.monitoringProgram.name", "datatype" : "string", "cardinality" : "ZeroOne", "elementtree" : ["addMonitoringProgram"] , "methodName" : "setName"} **/
						));
Medicationknowledgeobj.setType(HapiFHIRHelpers.createCodeableConcept(medicationknowledge.getMkDmnGdlnsDsgTpCcCdngCSstm() /** { "tree" :"MedicationKnowledge.administrationGuidelines.dosage.type", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "Required", "elementtree" : ["addAdministrationGuidelines", "addDosage"] , "methodName" : "setType, addCoding, setSystem"} **/
						, medicationknowledge.getMkDmnGdlnsDsgTpCcCdngCVrsn() /** { "tree" :"MedicationKnowledge.administrationGuidelines.dosage.type", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Required", "elementtree" : ["addAdministrationGuidelines", "addDosage"] , "methodName" : "setType, addCoding, setVersion"} **/
						, medicationknowledge.getMkDmnGdlnsDsgTpCcCdngCCde() /** { "tree" :"MedicationKnowledge.administrationGuidelines.dosage.type", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "Required", "elementtree" : ["addAdministrationGuidelines", "addDosage"] , "methodName" : "setType, addCoding, setCode"} **/
						, medicationknowledge.getMkDmnGdlnsDsgTpCcCdngCDsplay() /** { "tree" :"MedicationKnowledge.administrationGuidelines.dosage.type", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Required", "elementtree" : ["addAdministrationGuidelines", "addDosage"] , "methodName" : "setType, addCoding, setDisplay"} **/
						, medicationknowledge.getMkDmnGdlnsDsgTpCcCdngCSrSlctd() /** { "tree" :"MedicationKnowledge.administrationGuidelines.dosage.type", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "Required", "elementtree" : ["addAdministrationGuidelines", "addDosage"] , "methodName" : "setType, addCoding, setUserSelected"} **/
						, medicationknowledge.getMkDmnGdlnsDsgTpCcTxt() /** { "tree" :"MedicationKnowledge.administrationGuidelines.dosage.type", "datatype" : "CodeableConcept, string", "cardinality" : "Required", "elementtree" : ["addAdministrationGuidelines", "addDosage"] , "methodName" : "setType, setText"} **/
						));
Medicationknowledgeobj.setDosage(HapiFHIRHelpers.createDosage(medicationknowledge.getMkDmnGdlnsDsgDsgDsge() /** { "tree" :"MedicationKnowledge.administrationGuidelines.dosage.dosage", "datatype" : "Dosage", "cardinality" : "Required", "elementtree" : ["addAdministrationGuidelines", "addDosage"] , "methodName" : "setDosage"} **/
						));
Medicationknowledgeobj.setIndicationCodeableconcept(HapiFHIRHelpers.createCodeableConcept(medicationknowledge.getMkDmnGdlnsNdctnCdblcncptCcCdngCSstm() /** { "tree" :"MedicationKnowledge.administrationGuidelines.indicationCodeableconcept", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : ["addAdministrationGuidelines", "addDosage"] , "methodName" : "setIndicationCodeableconcept, addCoding, setSystem"} **/
						, medicationknowledge.getMkDmnGdlnsNdctnCdblcncptCcCdngCVrsn() /** { "tree" :"MedicationKnowledge.administrationGuidelines.indicationCodeableconcept", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addAdministrationGuidelines", "addDosage"] , "methodName" : "setIndicationCodeableconcept, addCoding, setVersion"} **/
						, medicationknowledge.getMkDmnGdlnsNdctnCdblcncptCcCdngCCde() /** { "tree" :"MedicationKnowledge.administrationGuidelines.indicationCodeableconcept", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : ["addAdministrationGuidelines", "addDosage"] , "methodName" : "setIndicationCodeableconcept, addCoding, setCode"} **/
						, medicationknowledge.getMkDmnGdlnsNdctnCdblcncptCcCdngCDsplay() /** { "tree" :"MedicationKnowledge.administrationGuidelines.indicationCodeableconcept", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addAdministrationGuidelines", "addDosage"] , "methodName" : "setIndicationCodeableconcept, addCoding, setDisplay"} **/
						, medicationknowledge.getMkDmnGdlnsNdctnCdblcncptCcCdngCSrSlctd() /** { "tree" :"MedicationKnowledge.administrationGuidelines.indicationCodeableconcept", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : ["addAdministrationGuidelines", "addDosage"] , "methodName" : "setIndicationCodeableconcept, addCoding, setUserSelected"} **/
						, medicationknowledge.getMkDmnGdlnsNdctnCdblcncptCcTxt() /** { "tree" :"MedicationKnowledge.administrationGuidelines.indicationCodeableconcept", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : ["addAdministrationGuidelines", "addDosage"] , "methodName" : "setIndicationCodeableconcept, setText"} **/
						));
Medicationknowledgeobj.setIndicationReference(observationdefinition)(HapiFHIRHelpers.createReference(medicationknowledge.getMkDmnGdlnsNdctnRfrncRfrnce() /** { "tree" :"MedicationKnowledge.administrationGuidelines.indicationReference", "datatype" : "Reference", "cardinality" : "ZeroOne", "elementtree" : ["addAdministrationGuidelines", "addDosage"] , "methodName" : "setIndicationReference(observationdefinition)"} **/
						));
Medicationknowledgeobj.setCharacteristicCodeableconcept(HapiFHIRHelpers.createCodeableConcept(medicationknowledge.getMkDmnGdlnsPntchrctrsChrctrCdblcncptCcCdngCSstm() /** { "tree" :"MedicationKnowledge.administrationGuidelines.patientCharacteristics.characteristicCodeableconcept", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "Required", "elementtree" : ["addAdministrationGuidelines", "addDosage", "addPatientCharacteristics"] , "methodName" : "setCharacteristicCodeableconcept, addCoding, setSystem"} **/
						, medicationknowledge.getMkDmnGdlnsPntchrctrsChrctrCdblcncptCcCdngCVrsn() /** { "tree" :"MedicationKnowledge.administrationGuidelines.patientCharacteristics.characteristicCodeableconcept", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Required", "elementtree" : ["addAdministrationGuidelines", "addDosage", "addPatientCharacteristics"] , "methodName" : "setCharacteristicCodeableconcept, addCoding, setVersion"} **/
						, medicationknowledge.getMkDmnGdlnsPntchrctrsChrctrCdblcncptCcCdngCCde() /** { "tree" :"MedicationKnowledge.administrationGuidelines.patientCharacteristics.characteristicCodeableconcept", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "Required", "elementtree" : ["addAdministrationGuidelines", "addDosage", "addPatientCharacteristics"] , "methodName" : "setCharacteristicCodeableconcept, addCoding, setCode"} **/
						, medicationknowledge.getMkDmnGdlnsPntchrctrsChrctrCdblcncptCcCdngCDsplay() /** { "tree" :"MedicationKnowledge.administrationGuidelines.patientCharacteristics.characteristicCodeableconcept", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Required", "elementtree" : ["addAdministrationGuidelines", "addDosage", "addPatientCharacteristics"] , "methodName" : "setCharacteristicCodeableconcept, addCoding, setDisplay"} **/
						, medicationknowledge.getMkDmnGdlnsPntchrctrsChrctrCdblcncptCcCdngCSrSlctd() /** { "tree" :"MedicationKnowledge.administrationGuidelines.patientCharacteristics.characteristicCodeableconcept", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "Required", "elementtree" : ["addAdministrationGuidelines", "addDosage", "addPatientCharacteristics"] , "methodName" : "setCharacteristicCodeableconcept, addCoding, setUserSelected"} **/
						, medicationknowledge.getMkDmnGdlnsPntchrctrsChrctrCdblcncptCcTxt() /** { "tree" :"MedicationKnowledge.administrationGuidelines.patientCharacteristics.characteristicCodeableconcept", "datatype" : "CodeableConcept, string", "cardinality" : "Required", "elementtree" : ["addAdministrationGuidelines", "addDosage", "addPatientCharacteristics"] , "methodName" : "setCharacteristicCodeableconcept, setText"} **/
						));
Medicationknowledgeobj.setCharacteristicSimplequantity(HapiFHIRHelpers.createSimpleQuantity(medicationknowledge.getMkDmnGdlnsPntchrctrsChrctrSmplqnttSmplQntty() /** { "tree" :"MedicationKnowledge.administrationGuidelines.patientCharacteristics.characteristicSimplequantity", "datatype" : "SimpleQuantity", "cardinality" : "Required", "elementtree" : ["addAdministrationGuidelines", "addDosage", "addPatientCharacteristics"] , "methodName" : "setCharacteristicSimplequantity"} **/
						));
Medicationknowledgeobj.addValue(HapiFHIRHelpers.createstring(medicationknowledge.getMkDmnGdlnsPntchrctrsVlStrng() /** { "tree" :"MedicationKnowledge.administrationGuidelines.patientCharacteristics.value", "datatype" : "string", "cardinality" : "Many", "elementtree" : ["addAdministrationGuidelines", "addDosage", "addPatientCharacteristics"] , "methodName" : "addValue"} **/
						));
Medicationknowledgeobj.setType(HapiFHIRHelpers.createCodeableConcept(medicationknowledge.getMkMdcnClssfctnTpCcCdngCSstm() /** { "tree" :"MedicationKnowledge.medicineClassification.type", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "Required", "elementtree" : ["addMedicineClassification"] , "methodName" : "setType, addCoding, setSystem"} **/
						, medicationknowledge.getMkMdcnClssfctnTpCcCdngCVrsn() /** { "tree" :"MedicationKnowledge.medicineClassification.type", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Required", "elementtree" : ["addMedicineClassification"] , "methodName" : "setType, addCoding, setVersion"} **/
						, medicationknowledge.getMkMdcnClssfctnTpCcCdngCCde() /** { "tree" :"MedicationKnowledge.medicineClassification.type", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "Required", "elementtree" : ["addMedicineClassification"] , "methodName" : "setType, addCoding, setCode"} **/
						, medicationknowledge.getMkMdcnClssfctnTpCcCdngCDsplay() /** { "tree" :"MedicationKnowledge.medicineClassification.type", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Required", "elementtree" : ["addMedicineClassification"] , "methodName" : "setType, addCoding, setDisplay"} **/
						, medicationknowledge.getMkMdcnClssfctnTpCcCdngCSrSlctd() /** { "tree" :"MedicationKnowledge.medicineClassification.type", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "Required", "elementtree" : ["addMedicineClassification"] , "methodName" : "setType, addCoding, setUserSelected"} **/
						, medicationknowledge.getMkMdcnClssfctnTpCcTxt() /** { "tree" :"MedicationKnowledge.medicineClassification.type", "datatype" : "CodeableConcept, string", "cardinality" : "Required", "elementtree" : ["addMedicineClassification"] , "methodName" : "setType, setText"} **/
						));
Medicationknowledgeobj.addClassification(HapiFHIRHelpers.createCodeableConcept(medicationknowledge.getMkMdcnClssfctnClssfctnCcCdngCSstm() /** { "tree" :"MedicationKnowledge.medicineClassification.classification", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "Many", "elementtree" : ["addMedicineClassification"] , "methodName" : "addClassification, addCoding, setSystem"} **/
						, medicationknowledge.getMkMdcnClssfctnClssfctnCcCdngCVrsn() /** { "tree" :"MedicationKnowledge.medicineClassification.classification", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Many", "elementtree" : ["addMedicineClassification"] , "methodName" : "addClassification, addCoding, setVersion"} **/
						, medicationknowledge.getMkMdcnClssfctnClssfctnCcCdngCCde() /** { "tree" :"MedicationKnowledge.medicineClassification.classification", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "Many", "elementtree" : ["addMedicineClassification"] , "methodName" : "addClassification, addCoding, setCode"} **/
						, medicationknowledge.getMkMdcnClssfctnClssfctnCcCdngCDsplay() /** { "tree" :"MedicationKnowledge.medicineClassification.classification", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Many", "elementtree" : ["addMedicineClassification"] , "methodName" : "addClassification, addCoding, setDisplay"} **/
						, medicationknowledge.getMkMdcnClssfctnClssfctnCcCdngCSrSlctd() /** { "tree" :"MedicationKnowledge.medicineClassification.classification", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "Many", "elementtree" : ["addMedicineClassification"] , "methodName" : "addClassification, addCoding, setUserSelected"} **/
						, medicationknowledge.getMkMdcnClssfctnClssfctnCcTxt() /** { "tree" :"MedicationKnowledge.medicineClassification.classification", "datatype" : "CodeableConcept, string", "cardinality" : "Many", "elementtree" : ["addMedicineClassification"] , "methodName" : "addClassification, setText"} **/
						));
Medicationknowledgeobj.setType(HapiFHIRHelpers.createCodeableConcept(medicationknowledge.getMkPckgngTpCcCdngCSstm() /** { "tree" :"MedicationKnowledge.packaging.type", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : ["setPackaging"] , "methodName" : "setType, addCoding, setSystem"} **/
						, medicationknowledge.getMkPckgngTpCcCdngCVrsn() /** { "tree" :"MedicationKnowledge.packaging.type", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["setPackaging"] , "methodName" : "setType, addCoding, setVersion"} **/
						, medicationknowledge.getMkPackagingTypeCcCodingCCode() /** { "tree" :"MedicationKnowledge.packaging.type", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : ["setPackaging"] , "methodName" : "setType, addCoding, setCode"} **/
						, medicationknowledge.getMkPckgngTpCcCdngCDsplay() /** { "tree" :"MedicationKnowledge.packaging.type", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["setPackaging"] , "methodName" : "setType, addCoding, setDisplay"} **/
						, medicationknowledge.getMkPckgngTpCcCdngCSrSlctd() /** { "tree" :"MedicationKnowledge.packaging.type", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : ["setPackaging"] , "methodName" : "setType, addCoding, setUserSelected"} **/
						, medicationknowledge.getMkPackagingTypeCcText() /** { "tree" :"MedicationKnowledge.packaging.type", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : ["setPackaging"] , "methodName" : "setType, setText"} **/
						));
Medicationknowledgeobj.setQuantity(HapiFHIRHelpers.createSimpleQuantity(medicationknowledge.getMkPckgngQnttSmplQntty() /** { "tree" :"MedicationKnowledge.packaging.quantity", "datatype" : "SimpleQuantity", "cardinality" : "ZeroOne", "elementtree" : ["setPackaging"] , "methodName" : "setQuantity"} **/
						));
Medicationknowledgeobj.setType(HapiFHIRHelpers.createCodeableConcept(medicationknowledge.getMkDrgchrctrTpCcCdngCSstm() /** { "tree" :"MedicationKnowledge.drugCharacteristic.type", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : ["addDrugCharacteristic"] , "methodName" : "setType, addCoding, setSystem"} **/
						, medicationknowledge.getMkDrgchrctrTpCcCdngCVrsn() /** { "tree" :"MedicationKnowledge.drugCharacteristic.type", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addDrugCharacteristic"] , "methodName" : "setType, addCoding, setVersion"} **/
						, medicationknowledge.getMkDrgchrctrTpCcCdngCCde() /** { "tree" :"MedicationKnowledge.drugCharacteristic.type", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : ["addDrugCharacteristic"] , "methodName" : "setType, addCoding, setCode"} **/
						, medicationknowledge.getMkDrgchrctrTpCcCdngCDsplay() /** { "tree" :"MedicationKnowledge.drugCharacteristic.type", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addDrugCharacteristic"] , "methodName" : "setType, addCoding, setDisplay"} **/
						, medicationknowledge.getMkDrgchrctrTpCcCdngCSrSlctd() /** { "tree" :"MedicationKnowledge.drugCharacteristic.type", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : ["addDrugCharacteristic"] , "methodName" : "setType, addCoding, setUserSelected"} **/
						, medicationknowledge.getMkDrugchrctrTypeCcText() /** { "tree" :"MedicationKnowledge.drugCharacteristic.type", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : ["addDrugCharacteristic"] , "methodName" : "setType, setText"} **/
						));
Medicationknowledgeobj.setValueCodeableconcept(HapiFHIRHelpers.createCodeableConcept(medicationknowledge.getMkDrgchrctrVlCdblcncptCcCdngCSstm() /** { "tree" :"MedicationKnowledge.drugCharacteristic.valueCodeableconcept", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : ["addDrugCharacteristic"] , "methodName" : "setValueCodeableconcept, addCoding, setSystem"} **/
						, medicationknowledge.getMkDrgchrctrVlCdblcncptCcCdngCVrsn() /** { "tree" :"MedicationKnowledge.drugCharacteristic.valueCodeableconcept", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addDrugCharacteristic"] , "methodName" : "setValueCodeableconcept, addCoding, setVersion"} **/
						, medicationknowledge.getMkDrgchrctrVlCdblcncptCcCdngCCde() /** { "tree" :"MedicationKnowledge.drugCharacteristic.valueCodeableconcept", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : ["addDrugCharacteristic"] , "methodName" : "setValueCodeableconcept, addCoding, setCode"} **/
						, medicationknowledge.getMkDrgchrctrVlCdblcncptCcCdngCDsplay() /** { "tree" :"MedicationKnowledge.drugCharacteristic.valueCodeableconcept", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addDrugCharacteristic"] , "methodName" : "setValueCodeableconcept, addCoding, setDisplay"} **/
						, medicationknowledge.getMkDrgchrctrVlCdblcncptCcCdngCSrSlctd() /** { "tree" :"MedicationKnowledge.drugCharacteristic.valueCodeableconcept", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : ["addDrugCharacteristic"] , "methodName" : "setValueCodeableconcept, addCoding, setUserSelected"} **/
						, medicationknowledge.getMkDrgchrctrVlCdblcncptCcTxt() /** { "tree" :"MedicationKnowledge.drugCharacteristic.valueCodeableconcept", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : ["addDrugCharacteristic"] , "methodName" : "setValueCodeableconcept, setText"} **/
						));
Medicationknowledgeobj.setValueString(HapiFHIRHelpers.createstring(medicationknowledge.getMkDrugchrctrValueStringString() /** { "tree" :"MedicationKnowledge.drugCharacteristic.valueString", "datatype" : "string", "cardinality" : "ZeroOne", "elementtree" : ["addDrugCharacteristic"] , "methodName" : "setValueString"} **/
						));
Medicationknowledgeobj.setValueSimplequantity(HapiFHIRHelpers.createSimpleQuantity(medicationknowledge.getMkDrgchrctrVlSmplqnttSmplQntty() /** { "tree" :"MedicationKnowledge.drugCharacteristic.valueSimplequantity", "datatype" : "SimpleQuantity", "cardinality" : "ZeroOne", "elementtree" : ["addDrugCharacteristic"] , "methodName" : "setValueSimplequantity"} **/
						));
Medicationknowledgeobj.setValueBase64binary(HapiFHIRHelpers.createbase64Binary(medicationknowledge.getMkDrgchrctrVlBs64bnrBs64bnry() /** { "tree" :"MedicationKnowledge.drugCharacteristic.valueBase64binary", "datatype" : "base64Binary", "cardinality" : "ZeroOne", "elementtree" : ["addDrugCharacteristic"] , "methodName" : "setValueBase64binary"} **/
						));
Medicationknowledgeobj.addContraindication(HapiFHIRHelpers.createReference(medicationknowledge.getMkContraindicationReference() /** { "tree" :"MedicationKnowledge.contraindication", "datatype" : "Reference", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addContraindication"} **/
						));
Medicationknowledgeobj.setRegulatoryAuthority(HapiFHIRHelpers.createReference(medicationknowledge.getMkRgltrRgltrthrtRfrnce() /** { "tree" :"MedicationKnowledge.regulatory.regulatoryAuthority", "datatype" : "Reference", "cardinality" : "Required", "elementtree" : ["addRegulatory"] , "methodName" : "setRegulatoryAuthority"} **/
						));
Medicationknowledgeobj.setType(HapiFHIRHelpers.createCodeableConcept(medicationknowledge.getMkRgltrSbstttnTpCcCdngCSstm() /** { "tree" :"MedicationKnowledge.regulatory.substitution.type", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "Required", "elementtree" : ["addRegulatory", "addSubstitution"] , "methodName" : "setType, addCoding, setSystem"} **/
						, medicationknowledge.getMkRgltrSbstttnTpCcCdngCVrsn() /** { "tree" :"MedicationKnowledge.regulatory.substitution.type", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Required", "elementtree" : ["addRegulatory", "addSubstitution"] , "methodName" : "setType, addCoding, setVersion"} **/
						, medicationknowledge.getMkRgltrSbstttnTpCcCdngCCde() /** { "tree" :"MedicationKnowledge.regulatory.substitution.type", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "Required", "elementtree" : ["addRegulatory", "addSubstitution"] , "methodName" : "setType, addCoding, setCode"} **/
						, medicationknowledge.getMkRgltrSbstttnTpCcCdngCDsplay() /** { "tree" :"MedicationKnowledge.regulatory.substitution.type", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Required", "elementtree" : ["addRegulatory", "addSubstitution"] , "methodName" : "setType, addCoding, setDisplay"} **/
						, medicationknowledge.getMkRgltrSbstttnTpCcCdngCSrSlctd() /** { "tree" :"MedicationKnowledge.regulatory.substitution.type", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "Required", "elementtree" : ["addRegulatory", "addSubstitution"] , "methodName" : "setType, addCoding, setUserSelected"} **/
						, medicationknowledge.getMkRgltrSbstttnTpCcTxt() /** { "tree" :"MedicationKnowledge.regulatory.substitution.type", "datatype" : "CodeableConcept, string", "cardinality" : "Required", "elementtree" : ["addRegulatory", "addSubstitution"] , "methodName" : "setType, setText"} **/
						));
Medicationknowledgeobj.setAllowed(HapiFHIRHelpers.createboolean(medicationknowledge.getMkRgltrSbstttnLlwdBln() /** { "tree" :"MedicationKnowledge.regulatory.substitution.allowed", "datatype" : "boolean", "cardinality" : "Required", "elementtree" : ["addRegulatory", "addSubstitution"] , "methodName" : "setAllowed"} **/
						));
Medicationknowledgeobj.setSchedule(HapiFHIRHelpers.createCodeableConcept(medicationknowledge.getMkRgltrSchdlSchdlCcCdngCSstm() /** { "tree" :"MedicationKnowledge.regulatory.schedule.schedule", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "Required", "elementtree" : ["addRegulatory", "addSubstitution", "addSchedule"] , "methodName" : "setSchedule, addCoding, setSystem"} **/
						, medicationknowledge.getMkRgltrSchdlSchdlCcCdngCVrsn() /** { "tree" :"MedicationKnowledge.regulatory.schedule.schedule", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Required", "elementtree" : ["addRegulatory", "addSubstitution", "addSchedule"] , "methodName" : "setSchedule, addCoding, setVersion"} **/
						, medicationknowledge.getMkRgltrSchdlSchdlCcCdngCCde() /** { "tree" :"MedicationKnowledge.regulatory.schedule.schedule", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "Required", "elementtree" : ["addRegulatory", "addSubstitution", "addSchedule"] , "methodName" : "setSchedule, addCoding, setCode"} **/
						, medicationknowledge.getMkRgltrSchdlSchdlCcCdngCDsplay() /** { "tree" :"MedicationKnowledge.regulatory.schedule.schedule", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Required", "elementtree" : ["addRegulatory", "addSubstitution", "addSchedule"] , "methodName" : "setSchedule, addCoding, setDisplay"} **/
						, medicationknowledge.getMkRgltrSchdlSchdlCcCdngCSrSlctd() /** { "tree" :"MedicationKnowledge.regulatory.schedule.schedule", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "Required", "elementtree" : ["addRegulatory", "addSubstitution", "addSchedule"] , "methodName" : "setSchedule, addCoding, setUserSelected"} **/
						, medicationknowledge.getMkRgltrSchdlSchdlCcTxt() /** { "tree" :"MedicationKnowledge.regulatory.schedule.schedule", "datatype" : "CodeableConcept, string", "cardinality" : "Required", "elementtree" : ["addRegulatory", "addSubstitution", "addSchedule"] , "methodName" : "setSchedule, setText"} **/
						));
Medicationknowledgeobj.setQuantity(HapiFHIRHelpers.createSimpleQuantity(medicationknowledge.getMkRgltrMxDspnsQnttSmplQntty() /** { "tree" :"MedicationKnowledge.regulatory.maxDispense.quantity", "datatype" : "SimpleQuantity", "cardinality" : "Required", "elementtree" : ["addRegulatory", "addSubstitution", "addSchedule", "setMaxDispense"] , "methodName" : "setQuantity"} **/
						));
Medicationknowledgeobj.setPeriod(HapiFHIRHelpers.createDuration(medicationknowledge.getMkRgltrMxDspnsPrdDrtn() /** { "tree" :"MedicationKnowledge.regulatory.maxDispense.period", "datatype" : "Duration", "cardinality" : "ZeroOne", "elementtree" : ["addRegulatory", "addSubstitution", "addSchedule", "setMaxDispense"] , "methodName" : "setPeriod"} **/
						));
Medicationknowledgeobj.addAreaUnderCurve(HapiFHIRHelpers.createSimpleQuantity(medicationknowledge.getMkKntcsRndrCrvSmplQntty() /** { "tree" :"MedicationKnowledge.kinetics.areaUnderCurve", "datatype" : "SimpleQuantity", "cardinality" : "Many", "elementtree" : ["addKinetics"] , "methodName" : "addAreaUnderCurve"} **/
						));
Medicationknowledgeobj.addLethalDose50(HapiFHIRHelpers.createSimpleQuantity(medicationknowledge.getMkKntcsLthlDs50SmplQntty() /** { "tree" :"MedicationKnowledge.kinetics.lethalDose50", "datatype" : "SimpleQuantity", "cardinality" : "Many", "elementtree" : ["addKinetics"] , "methodName" : "addLethalDose50"} **/
						));
Medicationknowledgeobj.setHalfLifePeriod(HapiFHIRHelpers.createDuration(medicationknowledge.getMkKntcsHlfLfPrdDrtn() /** { "tree" :"MedicationKnowledge.kinetics.halfLifePeriod", "datatype" : "Duration", "cardinality" : "ZeroOne", "elementtree" : ["addKinetics"] , "methodName" : "setHalfLifePeriod"} **/
		));
	}
}
