package main.templateoutput.Conversions;
// Generated on Jan 28, 2022, 8:02:40 AM 


import org.hl7.fhir.r4.model.Patient;

/**
 *  object for conversion model class Medicinalproductpharmaceutical.
 * @see .Medicinalproductpharmaceutical
 * @author Paul Kovach
 */
import main.java.com.campfhir.service.conversion.HapiFHIRHelpers;

public class MedicinalproductpharmaceuticalConversion 
{
	public Patient Medicinalproductpharmaceuticals(main.templateoutput.Model.Medicinalproductpharmaceutical medicinalproductpharmaceutical) 
	{
			Patient  Medicinalproductpharmaceuticalobj = new Patient(); 

						Medicinalproductpharmaceuticalobj.addIdentifier(HapiFHIRHelpers.createIdentifier(medicinalproductpharmaceutical.getMpphrmctclDntfrDntfrSe() /** { "tree" :"MedicinalProductPharmaceutical.identifier", "datatype" : "Identifier, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setUse"} **/
						, medicinalproductpharmaceutical.getMpphrmctclDntfrDntfrTpCcCSstm() /** { "tree" :"MedicinalProductPharmaceutical.identifier", "datatype" : "Identifier, CodeableConcept, Coding, uri", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setType, addCoding, setSystem"} **/
						, medicinalproductpharmaceutical.getMpphrmctclDntfrDntfrTpCcCVrsn() /** { "tree" :"MedicinalProductPharmaceutical.identifier", "datatype" : "Identifier, CodeableConcept, Coding, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setType, addCoding, setVersion"} **/
						, medicinalproductpharmaceutical.getMpphrmctclDntfrDntfrTpCcCCde() /** { "tree" :"MedicinalProductPharmaceutical.identifier", "datatype" : "Identifier, CodeableConcept, Coding, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setType, addCoding, setCode"} **/
						, medicinalproductpharmaceutical.getMpphrmctclDntfrDntfrTpCcCDsplay() /** { "tree" :"MedicinalProductPharmaceutical.identifier", "datatype" : "Identifier, CodeableConcept, Coding, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setType, addCoding, setDisplay"} **/
						, medicinalproductpharmaceutical.getMpphrmctclDntfrDntfrTpCcCSrSlctd() /** { "tree" :"MedicinalProductPharmaceutical.identifier", "datatype" : "Identifier, CodeableConcept, Coding, boolean", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setType, addCoding, setUserSelected"} **/
						, medicinalproductpharmaceutical.getMpphrmctclDntfrDntfrTpCcTxt() /** { "tree" :"MedicinalProductPharmaceutical.identifier", "datatype" : "Identifier, CodeableConcept, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setType, setText"} **/
						, medicinalproductpharmaceutical.getMpphrmctclDntfrDntfrPrdPrdStrt() /** { "tree" :"MedicinalProductPharmaceutical.identifier", "datatype" : "Identifier, Period, dateTime", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setPeriod, setStart"} **/
						, medicinalproductpharmaceutical.getMpphrmctclDntfrDntfrPrdPrdNd() /** { "tree" :"MedicinalProductPharmaceutical.identifier", "datatype" : "Identifier, Period, dateTime", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setPeriod, setEnd"} **/
						, medicinalproductpharmaceutical.getMpphrmctclDntfrDntfrSsgnr() /** { "tree" :"MedicinalProductPharmaceutical.identifier", "datatype" : "Identifier, Reference", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setAssigner"} **/
						, medicinalproductpharmaceutical.getMpphrmctclDntfrDntfrVlue() /** { "tree" :"MedicinalProductPharmaceutical.identifier", "datatype" : "Identifier, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setValue"} **/
						, medicinalproductpharmaceutical.getMpphrmctclDntfrDntfrSstm() /** { "tree" :"MedicinalProductPharmaceutical.identifier", "datatype" : "Identifier, uri", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setSystem"} **/
						));
Medicinalproductpharmaceuticalobj.setAdministrableDoseForm(HapiFHIRHelpers.createCodeableConcept(medicinalproductpharmaceutical.getMpphrmctclDmnstrblDsFrmCcCdngCSstm() /** { "tree" :"MedicinalProductPharmaceutical.administrableDoseForm", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "Required", "elementtree" : [] , "methodName" : "setAdministrableDoseForm, addCoding, setSystem"} **/
						, medicinalproductpharmaceutical.getMpphrmctclDmnstrblDsFrmCcCdngCVrsn() /** { "tree" :"MedicinalProductPharmaceutical.administrableDoseForm", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Required", "elementtree" : [] , "methodName" : "setAdministrableDoseForm, addCoding, setVersion"} **/
						, medicinalproductpharmaceutical.getMpphrmctclDmnstrblDsFrmCcCdngCCde() /** { "tree" :"MedicinalProductPharmaceutical.administrableDoseForm", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "Required", "elementtree" : [] , "methodName" : "setAdministrableDoseForm, addCoding, setCode"} **/
						, medicinalproductpharmaceutical.getMpphrmctclDmnstrblDsFrmCcCdngCDsplay() /** { "tree" :"MedicinalProductPharmaceutical.administrableDoseForm", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Required", "elementtree" : [] , "methodName" : "setAdministrableDoseForm, addCoding, setDisplay"} **/
						, medicinalproductpharmaceutical.getMpphrmctclDmnstrblDsFrmCcCdngCSrSlctd() /** { "tree" :"MedicinalProductPharmaceutical.administrableDoseForm", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "Required", "elementtree" : [] , "methodName" : "setAdministrableDoseForm, addCoding, setUserSelected"} **/
						, medicinalproductpharmaceutical.getMpphrmctclDmnstrblDsFrmCcTxt() /** { "tree" :"MedicinalProductPharmaceutical.administrableDoseForm", "datatype" : "CodeableConcept, string", "cardinality" : "Required", "elementtree" : [] , "methodName" : "setAdministrableDoseForm, setText"} **/
						));
Medicinalproductpharmaceuticalobj.setUnitOfPresentation(HapiFHIRHelpers.createCodeableConcept(medicinalproductpharmaceutical.getMpphrmctclNtfPrsnttnCcCdngCSstm() /** { "tree" :"MedicinalProductPharmaceutical.unitOfPresentation", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setUnitOfPresentation, addCoding, setSystem"} **/
						, medicinalproductpharmaceutical.getMpphrmctclNtfPrsnttnCcCdngCVrsn() /** { "tree" :"MedicinalProductPharmaceutical.unitOfPresentation", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setUnitOfPresentation, addCoding, setVersion"} **/
						, medicinalproductpharmaceutical.getMpphrmctclNtfPrsnttnCcCdngCCde() /** { "tree" :"MedicinalProductPharmaceutical.unitOfPresentation", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setUnitOfPresentation, addCoding, setCode"} **/
						, medicinalproductpharmaceutical.getMpphrmctclNtfPrsnttnCcCdngCDsplay() /** { "tree" :"MedicinalProductPharmaceutical.unitOfPresentation", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setUnitOfPresentation, addCoding, setDisplay"} **/
						, medicinalproductpharmaceutical.getMpphrmctclNtfPrsnttnCcCdngCSrSlctd() /** { "tree" :"MedicinalProductPharmaceutical.unitOfPresentation", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setUnitOfPresentation, addCoding, setUserSelected"} **/
						, medicinalproductpharmaceutical.getMpphrmctclNtfPrsnttnCcTxt() /** { "tree" :"MedicinalProductPharmaceutical.unitOfPresentation", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setUnitOfPresentation, setText"} **/
						));
Medicinalproductpharmaceuticalobj.addIngredient(HapiFHIRHelpers.createReference(medicinalproductpharmaceutical.getMpphrmctclNgrdntRfrnce() /** { "tree" :"MedicinalProductPharmaceutical.ingredient", "datatype" : "Reference", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIngredient"} **/
						));
Medicinalproductpharmaceuticalobj.addDevice(HapiFHIRHelpers.createReference(medicinalproductpharmaceutical.getMppharmaceuticalDeviceReference() /** { "tree" :"MedicinalProductPharmaceutical.device", "datatype" : "Reference", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addDevice"} **/
						));
Medicinalproductpharmaceuticalobj.setCode(HapiFHIRHelpers.createCodeableConcept(medicinalproductpharmaceutical.getMpphrmctclChrctrsCdCcCdngCSstm() /** { "tree" :"MedicinalProductPharmaceutical.characteristics.code", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "Required", "elementtree" : ["addCharacteristics"] , "methodName" : "setCode, addCoding, setSystem"} **/
						, medicinalproductpharmaceutical.getMpphrmctclChrctrsCdCcCdngCVrsn() /** { "tree" :"MedicinalProductPharmaceutical.characteristics.code", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Required", "elementtree" : ["addCharacteristics"] , "methodName" : "setCode, addCoding, setVersion"} **/
						, medicinalproductpharmaceutical.getMpphrmctclChrctrsCdCcCdngCCde() /** { "tree" :"MedicinalProductPharmaceutical.characteristics.code", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "Required", "elementtree" : ["addCharacteristics"] , "methodName" : "setCode, addCoding, setCode"} **/
						, medicinalproductpharmaceutical.getMpphrmctclChrctrsCdCcCdngCDsplay() /** { "tree" :"MedicinalProductPharmaceutical.characteristics.code", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Required", "elementtree" : ["addCharacteristics"] , "methodName" : "setCode, addCoding, setDisplay"} **/
						, medicinalproductpharmaceutical.getMpphrmctclChrctrsCdCcCdngCSrSlctd() /** { "tree" :"MedicinalProductPharmaceutical.characteristics.code", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "Required", "elementtree" : ["addCharacteristics"] , "methodName" : "setCode, addCoding, setUserSelected"} **/
						, medicinalproductpharmaceutical.getMpphrmctclChrctrsCdCcTxt() /** { "tree" :"MedicinalProductPharmaceutical.characteristics.code", "datatype" : "CodeableConcept, string", "cardinality" : "Required", "elementtree" : ["addCharacteristics"] , "methodName" : "setCode, setText"} **/
						));
Medicinalproductpharmaceuticalobj.setStatus(HapiFHIRHelpers.createCodeableConcept(medicinalproductpharmaceutical.getMpphrmctclChrctrsSttsCcCdngCSstm() /** { "tree" :"MedicinalProductPharmaceutical.characteristics.status", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : ["addCharacteristics"] , "methodName" : "setStatus, addCoding, setSystem"} **/
						, medicinalproductpharmaceutical.getMpphrmctclChrctrsSttsCcCdngCVrsn() /** { "tree" :"MedicinalProductPharmaceutical.characteristics.status", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addCharacteristics"] , "methodName" : "setStatus, addCoding, setVersion"} **/
						, medicinalproductpharmaceutical.getMpphrmctclChrctrsSttsCcCdngCCde() /** { "tree" :"MedicinalProductPharmaceutical.characteristics.status", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : ["addCharacteristics"] , "methodName" : "setStatus, addCoding, setCode"} **/
						, medicinalproductpharmaceutical.getMpphrmctclChrctrsSttsCcCdngCDsplay() /** { "tree" :"MedicinalProductPharmaceutical.characteristics.status", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addCharacteristics"] , "methodName" : "setStatus, addCoding, setDisplay"} **/
						, medicinalproductpharmaceutical.getMpphrmctclChrctrsSttsCcCdngCSrSlctd() /** { "tree" :"MedicinalProductPharmaceutical.characteristics.status", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : ["addCharacteristics"] , "methodName" : "setStatus, addCoding, setUserSelected"} **/
						, medicinalproductpharmaceutical.getMpphrmctclChrctrsSttsCcTxt() /** { "tree" :"MedicinalProductPharmaceutical.characteristics.status", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : ["addCharacteristics"] , "methodName" : "setStatus, setText"} **/
						));
Medicinalproductpharmaceuticalobj.setCode(HapiFHIRHelpers.createCodeableConcept(medicinalproductpharmaceutical.getMpphrmctclRtfdmnCdCcCdngCSstm() /** { "tree" :"MedicinalProductPharmaceutical.routeOfAdministration.code", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "Required", "elementtree" : ["setRouteOfAdministration"] , "methodName" : "setCode, addCoding, setSystem"} **/
						, medicinalproductpharmaceutical.getMpphrmctclRtfdmnCdCcCdngCVrsn() /** { "tree" :"MedicinalProductPharmaceutical.routeOfAdministration.code", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Required", "elementtree" : ["setRouteOfAdministration"] , "methodName" : "setCode, addCoding, setVersion"} **/
						, medicinalproductpharmaceutical.getMpphrmctclRtfdmnCdCcCdngCCde() /** { "tree" :"MedicinalProductPharmaceutical.routeOfAdministration.code", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "Required", "elementtree" : ["setRouteOfAdministration"] , "methodName" : "setCode, addCoding, setCode"} **/
						, medicinalproductpharmaceutical.getMpphrmctclRtfdmnCdCcCdngCDsplay() /** { "tree" :"MedicinalProductPharmaceutical.routeOfAdministration.code", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Required", "elementtree" : ["setRouteOfAdministration"] , "methodName" : "setCode, addCoding, setDisplay"} **/
						, medicinalproductpharmaceutical.getMpphrmctclRtfdmnCdCcCdngCSrSlctd() /** { "tree" :"MedicinalProductPharmaceutical.routeOfAdministration.code", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "Required", "elementtree" : ["setRouteOfAdministration"] , "methodName" : "setCode, addCoding, setUserSelected"} **/
						, medicinalproductpharmaceutical.getMpphrmctclRtfdmnCdCcTxt() /** { "tree" :"MedicinalProductPharmaceutical.routeOfAdministration.code", "datatype" : "CodeableConcept, string", "cardinality" : "Required", "elementtree" : ["setRouteOfAdministration"] , "methodName" : "setCode, setText"} **/
						));
Medicinalproductpharmaceuticalobj.setFirstDose(HapiFHIRHelpers.createQuantity(medicinalproductpharmaceutical.getMpphrmctclRtfdmnFrstDsQnttCmprtr() /** { "tree" :"MedicinalProductPharmaceutical.routeOfAdministration.firstDose", "datatype" : "Quantity, code", "cardinality" : "ZeroOne", "elementtree" : ["setRouteOfAdministration"] , "methodName" : "setFirstDose, setComparator"} **/
						, medicinalproductpharmaceutical.getMpphrmctclRtfdmnFrstDsQnttCde() /** { "tree" :"MedicinalProductPharmaceutical.routeOfAdministration.firstDose", "datatype" : "Quantity, code", "cardinality" : "ZeroOne", "elementtree" : ["setRouteOfAdministration"] , "methodName" : "setFirstDose, setCode"} **/
						, medicinalproductpharmaceutical.getMpphrmctclRtfdmnFrstDsQnttVlue() /** { "tree" :"MedicinalProductPharmaceutical.routeOfAdministration.firstDose", "datatype" : "Quantity, decimal", "cardinality" : "ZeroOne", "elementtree" : ["setRouteOfAdministration"] , "methodName" : "setFirstDose, setValue"} **/
						, medicinalproductpharmaceutical.getMpphrmctclRtfdmnFrstDsQnttNt() /** { "tree" :"MedicinalProductPharmaceutical.routeOfAdministration.firstDose", "datatype" : "Quantity, string", "cardinality" : "ZeroOne", "elementtree" : ["setRouteOfAdministration"] , "methodName" : "setFirstDose, setUnit"} **/
						, medicinalproductpharmaceutical.getMpphrmctclRtfdmnFrstDsQnttSstm() /** { "tree" :"MedicinalProductPharmaceutical.routeOfAdministration.firstDose", "datatype" : "Quantity, uri", "cardinality" : "ZeroOne", "elementtree" : ["setRouteOfAdministration"] , "methodName" : "setFirstDose, setSystem"} **/
						));
Medicinalproductpharmaceuticalobj.setMaxSingleDose(HapiFHIRHelpers.createQuantity(medicinalproductpharmaceutical.getMpphrmctclRtfdmnMxSnglDsQnttCmprtr() /** { "tree" :"MedicinalProductPharmaceutical.routeOfAdministration.maxSingleDose", "datatype" : "Quantity, code", "cardinality" : "ZeroOne", "elementtree" : ["setRouteOfAdministration"] , "methodName" : "setMaxSingleDose, setComparator"} **/
						, medicinalproductpharmaceutical.getMpphrmctclRtfdmnMxSnglDsQnttCde() /** { "tree" :"MedicinalProductPharmaceutical.routeOfAdministration.maxSingleDose", "datatype" : "Quantity, code", "cardinality" : "ZeroOne", "elementtree" : ["setRouteOfAdministration"] , "methodName" : "setMaxSingleDose, setCode"} **/
						, medicinalproductpharmaceutical.getMpphrmctclRtfdmnMxSnglDsQnttVlue() /** { "tree" :"MedicinalProductPharmaceutical.routeOfAdministration.maxSingleDose", "datatype" : "Quantity, decimal", "cardinality" : "ZeroOne", "elementtree" : ["setRouteOfAdministration"] , "methodName" : "setMaxSingleDose, setValue"} **/
						, medicinalproductpharmaceutical.getMpphrmctclRtfdmnMxSnglDsQnttNt() /** { "tree" :"MedicinalProductPharmaceutical.routeOfAdministration.maxSingleDose", "datatype" : "Quantity, string", "cardinality" : "ZeroOne", "elementtree" : ["setRouteOfAdministration"] , "methodName" : "setMaxSingleDose, setUnit"} **/
						, medicinalproductpharmaceutical.getMpphrmctclRtfdmnMxSnglDsQnttSstm() /** { "tree" :"MedicinalProductPharmaceutical.routeOfAdministration.maxSingleDose", "datatype" : "Quantity, uri", "cardinality" : "ZeroOne", "elementtree" : ["setRouteOfAdministration"] , "methodName" : "setMaxSingleDose, setSystem"} **/
						));
Medicinalproductpharmaceuticalobj.setMaxDosePerDay(HapiFHIRHelpers.createQuantity(medicinalproductpharmaceutical.getMpphrmctclRtfdmnMxDsPrDQnttCmprtr() /** { "tree" :"MedicinalProductPharmaceutical.routeOfAdministration.maxDosePerDay", "datatype" : "Quantity, code", "cardinality" : "ZeroOne", "elementtree" : ["setRouteOfAdministration"] , "methodName" : "setMaxDosePerDay, setComparator"} **/
						, medicinalproductpharmaceutical.getMpphrmctclRtfdmnMxDsPrDQnttCde() /** { "tree" :"MedicinalProductPharmaceutical.routeOfAdministration.maxDosePerDay", "datatype" : "Quantity, code", "cardinality" : "ZeroOne", "elementtree" : ["setRouteOfAdministration"] , "methodName" : "setMaxDosePerDay, setCode"} **/
						, medicinalproductpharmaceutical.getMpphrmctclRtfdmnMxDsPrDQnttVlue() /** { "tree" :"MedicinalProductPharmaceutical.routeOfAdministration.maxDosePerDay", "datatype" : "Quantity, decimal", "cardinality" : "ZeroOne", "elementtree" : ["setRouteOfAdministration"] , "methodName" : "setMaxDosePerDay, setValue"} **/
						, medicinalproductpharmaceutical.getMpphrmctclRtfdmnMxDsPrDQnttNt() /** { "tree" :"MedicinalProductPharmaceutical.routeOfAdministration.maxDosePerDay", "datatype" : "Quantity, string", "cardinality" : "ZeroOne", "elementtree" : ["setRouteOfAdministration"] , "methodName" : "setMaxDosePerDay, setUnit"} **/
						, medicinalproductpharmaceutical.getMpphrmctclRtfdmnMxDsPrDQnttSstm() /** { "tree" :"MedicinalProductPharmaceutical.routeOfAdministration.maxDosePerDay", "datatype" : "Quantity, uri", "cardinality" : "ZeroOne", "elementtree" : ["setRouteOfAdministration"] , "methodName" : "setMaxDosePerDay, setSystem"} **/
						));
Medicinalproductpharmaceuticalobj.setMaxDosePerTreatmentPeriod(HapiFHIRHelpers.createRatio(medicinalproductpharmaceutical.getMpphrmctclRtfdmnMxDsPrTrtmntPrdRtNmrtrQnttVlue() /** { "tree" :"MedicinalProductPharmaceutical.routeOfAdministration.maxDosePerTreatmentPeriod", "datatype" : "Ratio, Quantity, decimal", "cardinality" : "ZeroOne", "elementtree" : ["setRouteOfAdministration"] , "methodName" : "setMaxDosePerTreatmentPeriod, setNumerator, setValue"} **/
						, medicinalproductpharmaceutical.getMpphrmctclRtfdmnMxDsPrTrtmntPrdRtDnmntrQnttVlue() /** { "tree" :"MedicinalProductPharmaceutical.routeOfAdministration.maxDosePerTreatmentPeriod", "datatype" : "Ratio, Quantity, decimal", "cardinality" : "ZeroOne", "elementtree" : ["setRouteOfAdministration"] , "methodName" : "setMaxDosePerTreatmentPeriod, setDenominator, setValue"} **/
						, medicinalproductpharmaceutical.getMpphrmctclRtfdmnMxDsPrTrtmntPrdRtNmrtrQnttCmprtr() /** { "tree" :"MedicinalProductPharmaceutical.routeOfAdministration.maxDosePerTreatmentPeriod", "datatype" : "Ratio, Quantity, code", "cardinality" : "ZeroOne", "elementtree" : ["setRouteOfAdministration"] , "methodName" : "setMaxDosePerTreatmentPeriod, setNumerator, setComparator"} **/
						, medicinalproductpharmaceutical.getMpphrmctclRtfdmnMxDsPrTrtmntPrdRtDnmntrQnttCmprtr() /** { "tree" :"MedicinalProductPharmaceutical.routeOfAdministration.maxDosePerTreatmentPeriod", "datatype" : "Ratio, Quantity, code", "cardinality" : "ZeroOne", "elementtree" : ["setRouteOfAdministration"] , "methodName" : "setMaxDosePerTreatmentPeriod, setDenominator, setComparator"} **/
						, medicinalproductpharmaceutical.getMpphrmctclRtfdmnMxDsPrTrtmntPrdRtNmrtrQnttNt() /** { "tree" :"MedicinalProductPharmaceutical.routeOfAdministration.maxDosePerTreatmentPeriod", "datatype" : "Ratio, Quantity, string", "cardinality" : "ZeroOne", "elementtree" : ["setRouteOfAdministration"] , "methodName" : "setMaxDosePerTreatmentPeriod, setNumerator, setUnit"} **/
						, medicinalproductpharmaceutical.getMpphrmctclRtfdmnMxDsPrTrtmntPrdRtDnmntrQnttNt() /** { "tree" :"MedicinalProductPharmaceutical.routeOfAdministration.maxDosePerTreatmentPeriod", "datatype" : "Ratio, Quantity, string", "cardinality" : "ZeroOne", "elementtree" : ["setRouteOfAdministration"] , "methodName" : "setMaxDosePerTreatmentPeriod, setDenominator, setUnit"} **/
						, medicinalproductpharmaceutical.getMpphrmctclRtfdmnMxDsPrTrtmntPrdRtNmrtrQnttSstm() /** { "tree" :"MedicinalProductPharmaceutical.routeOfAdministration.maxDosePerTreatmentPeriod", "datatype" : "Ratio, Quantity, uri", "cardinality" : "ZeroOne", "elementtree" : ["setRouteOfAdministration"] , "methodName" : "setMaxDosePerTreatmentPeriod, setNumerator, setSystem"} **/
						, medicinalproductpharmaceutical.getMpphrmctclRtfdmnMxDsPrTrtmntPrdRtDnmntrQnttSstm() /** { "tree" :"MedicinalProductPharmaceutical.routeOfAdministration.maxDosePerTreatmentPeriod", "datatype" : "Ratio, Quantity, uri", "cardinality" : "ZeroOne", "elementtree" : ["setRouteOfAdministration"] , "methodName" : "setMaxDosePerTreatmentPeriod, setDenominator, setSystem"} **/
						, medicinalproductpharmaceutical.getMpphrmctclRtfdmnMxDsPrTrtmntPrdRtNmrtrQnttCde() /** { "tree" :"MedicinalProductPharmaceutical.routeOfAdministration.maxDosePerTreatmentPeriod", "datatype" : "Ratio, Quantity, code", "cardinality" : "ZeroOne", "elementtree" : ["setRouteOfAdministration"] , "methodName" : "setMaxDosePerTreatmentPeriod, setNumerator, setCode"} **/
						, medicinalproductpharmaceutical.getMpphrmctclRtfdmnMxDsPrTrtmntPrdRtDnmntrQnttCde() /** { "tree" :"MedicinalProductPharmaceutical.routeOfAdministration.maxDosePerTreatmentPeriod", "datatype" : "Ratio, Quantity, code", "cardinality" : "ZeroOne", "elementtree" : ["setRouteOfAdministration"] , "methodName" : "setMaxDosePerTreatmentPeriod, setDenominator, setCode"} **/
						));
Medicinalproductpharmaceuticalobj.setMaxTreatmentPeriod(HapiFHIRHelpers.createDuration(medicinalproductpharmaceutical.getMpphrmctclRtfdmnMxTrtmntPrdDrtn() /** { "tree" :"MedicinalProductPharmaceutical.routeOfAdministration.maxTreatmentPeriod", "datatype" : "Duration", "cardinality" : "ZeroOne", "elementtree" : ["setRouteOfAdministration"] , "methodName" : "setMaxTreatmentPeriod"} **/
						));
Medicinalproductpharmaceuticalobj.setCode(HapiFHIRHelpers.createCodeableConcept(medicinalproductpharmaceutical.getMpphrmctclRtfdmnTrgtSpcsCdCcCdngCSstm() /** { "tree" :"MedicinalProductPharmaceutical.routeOfAdministration.targetSpecies.code", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "Required", "elementtree" : ["setRouteOfAdministration", "addTargetSpecies"] , "methodName" : "setCode, addCoding, setSystem"} **/
						, medicinalproductpharmaceutical.getMpphrmctclRtfdmnTrgtSpcsCdCcCdngCVrsn() /** { "tree" :"MedicinalProductPharmaceutical.routeOfAdministration.targetSpecies.code", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Required", "elementtree" : ["setRouteOfAdministration", "addTargetSpecies"] , "methodName" : "setCode, addCoding, setVersion"} **/
						, medicinalproductpharmaceutical.getMpphrmctclRtfdmnTrgtSpcsCdCcCdngCCde() /** { "tree" :"MedicinalProductPharmaceutical.routeOfAdministration.targetSpecies.code", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "Required", "elementtree" : ["setRouteOfAdministration", "addTargetSpecies"] , "methodName" : "setCode, addCoding, setCode"} **/
						, medicinalproductpharmaceutical.getMpphrmctclRtfdmnTrgtSpcsCdCcCdngCDsplay() /** { "tree" :"MedicinalProductPharmaceutical.routeOfAdministration.targetSpecies.code", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Required", "elementtree" : ["setRouteOfAdministration", "addTargetSpecies"] , "methodName" : "setCode, addCoding, setDisplay"} **/
						, medicinalproductpharmaceutical.getMpphrmctclRtfdmnTrgtSpcsCdCcCdngCSrSlctd() /** { "tree" :"MedicinalProductPharmaceutical.routeOfAdministration.targetSpecies.code", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "Required", "elementtree" : ["setRouteOfAdministration", "addTargetSpecies"] , "methodName" : "setCode, addCoding, setUserSelected"} **/
						, medicinalproductpharmaceutical.getMpphrmctclRtfdmnTrgtSpcsCdCcTxt() /** { "tree" :"MedicinalProductPharmaceutical.routeOfAdministration.targetSpecies.code", "datatype" : "CodeableConcept, string", "cardinality" : "Required", "elementtree" : ["setRouteOfAdministration", "addTargetSpecies"] , "methodName" : "setCode, setText"} **/
						));
Medicinalproductpharmaceuticalobj.setTissue(HapiFHIRHelpers.createCodeableConcept(medicinalproductpharmaceutical.getMpphrmctclRtfdmnTrgtSpcsWthdrwlPrdTssCcCdngCSstm() /** { "tree" :"MedicinalProductPharmaceutical.routeOfAdministration.targetSpecies.withdrawalPeriod.tissue", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "Required", "elementtree" : ["setRouteOfAdministration", "addTargetSpecies", "addWithdrawalPeriod"] , "methodName" : "setTissue, addCoding, setSystem"} **/
						, medicinalproductpharmaceutical.getMpphrmctclRtfdmnTrgtSpcsWthdrwlPrdTssCcCdngCVrsn() /** { "tree" :"MedicinalProductPharmaceutical.routeOfAdministration.targetSpecies.withdrawalPeriod.tissue", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Required", "elementtree" : ["setRouteOfAdministration", "addTargetSpecies", "addWithdrawalPeriod"] , "methodName" : "setTissue, addCoding, setVersion"} **/
						, medicinalproductpharmaceutical.getMpphrmctclRtfdmnTrgtSpcsWthdrwlPrdTssCcCdngCCde() /** { "tree" :"MedicinalProductPharmaceutical.routeOfAdministration.targetSpecies.withdrawalPeriod.tissue", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "Required", "elementtree" : ["setRouteOfAdministration", "addTargetSpecies", "addWithdrawalPeriod"] , "methodName" : "setTissue, addCoding, setCode"} **/
						, medicinalproductpharmaceutical.getMpphrmctclRtfdmnTrgtSpcsWthdrwlPrdTssCcCdngCDsplay() /** { "tree" :"MedicinalProductPharmaceutical.routeOfAdministration.targetSpecies.withdrawalPeriod.tissue", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Required", "elementtree" : ["setRouteOfAdministration", "addTargetSpecies", "addWithdrawalPeriod"] , "methodName" : "setTissue, addCoding, setDisplay"} **/
						, medicinalproductpharmaceutical.getMpphrmctclRtfdmnTrgtSpcsWthdrwlPrdTssCcCdngCSrSlctd() /** { "tree" :"MedicinalProductPharmaceutical.routeOfAdministration.targetSpecies.withdrawalPeriod.tissue", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "Required", "elementtree" : ["setRouteOfAdministration", "addTargetSpecies", "addWithdrawalPeriod"] , "methodName" : "setTissue, addCoding, setUserSelected"} **/
						, medicinalproductpharmaceutical.getMpphrmctclRtfdmnTrgtSpcsWthdrwlPrdTssCcTxt() /** { "tree" :"MedicinalProductPharmaceutical.routeOfAdministration.targetSpecies.withdrawalPeriod.tissue", "datatype" : "CodeableConcept, string", "cardinality" : "Required", "elementtree" : ["setRouteOfAdministration", "addTargetSpecies", "addWithdrawalPeriod"] , "methodName" : "setTissue, setText"} **/
						));
Medicinalproductpharmaceuticalobj.setValue(HapiFHIRHelpers.createQuantity(medicinalproductpharmaceutical.getMpphrmctclRtfdmnTrgtSpcsWthdrwlPrdVlQnttCmprtr() /** { "tree" :"MedicinalProductPharmaceutical.routeOfAdministration.targetSpecies.withdrawalPeriod.value", "datatype" : "Quantity, code", "cardinality" : "Required", "elementtree" : ["setRouteOfAdministration", "addTargetSpecies", "addWithdrawalPeriod"] , "methodName" : "setValue, setComparator"} **/
						, medicinalproductpharmaceutical.getMpphrmctclRtfdmnTrgtSpcsWthdrwlPrdVlQnttCde() /** { "tree" :"MedicinalProductPharmaceutical.routeOfAdministration.targetSpecies.withdrawalPeriod.value", "datatype" : "Quantity, code", "cardinality" : "Required", "elementtree" : ["setRouteOfAdministration", "addTargetSpecies", "addWithdrawalPeriod"] , "methodName" : "setValue, setCode"} **/
						, medicinalproductpharmaceutical.getMpphrmctclRtfdmnTrgtSpcsWthdrwlPrdVlQnttVlue() /** { "tree" :"MedicinalProductPharmaceutical.routeOfAdministration.targetSpecies.withdrawalPeriod.value", "datatype" : "Quantity, decimal", "cardinality" : "Required", "elementtree" : ["setRouteOfAdministration", "addTargetSpecies", "addWithdrawalPeriod"] , "methodName" : "setValue, setValue"} **/
						, medicinalproductpharmaceutical.getMpphrmctclRtfdmnTrgtSpcsWthdrwlPrdVlQnttNt() /** { "tree" :"MedicinalProductPharmaceutical.routeOfAdministration.targetSpecies.withdrawalPeriod.value", "datatype" : "Quantity, string", "cardinality" : "Required", "elementtree" : ["setRouteOfAdministration", "addTargetSpecies", "addWithdrawalPeriod"] , "methodName" : "setValue, setUnit"} **/
						, medicinalproductpharmaceutical.getMpphrmctclRtfdmnTrgtSpcsWthdrwlPrdVlQnttSstm() /** { "tree" :"MedicinalProductPharmaceutical.routeOfAdministration.targetSpecies.withdrawalPeriod.value", "datatype" : "Quantity, uri", "cardinality" : "Required", "elementtree" : ["setRouteOfAdministration", "addTargetSpecies", "addWithdrawalPeriod"] , "methodName" : "setValue, setSystem"} **/
						));
Medicinalproductpharmaceuticalobj.setSupportingInformation(HapiFHIRHelpers.createstring(medicinalproductpharmaceutical.getMpphrmctclRtfdmnTrgtSpcsWthdrwlPrdSpprtngnfrmtnStrng() /** { "tree" :"MedicinalProductPharmaceutical.routeOfAdministration.targetSpecies.withdrawalPeriod.supportingInformation", "datatype" : "string", "cardinality" : "ZeroOne", "elementtree" : ["setRouteOfAdministration", "addTargetSpecies", "addWithdrawalPeriod"] , "methodName" : "setSupportingInformation"} **/
		));
	}
}
