package main.templateoutput.Conversions;
// Generated on Jan 28, 2022, 8:02:40 AM 


import org.hl7.fhir.r4.model.Patient;

/**
 *  object for conversion model class Researchelementdefinition.
 * @see .Researchelementdefinition
 * @author Paul Kovach
 */
import main.java.com.campfhir.service.conversion.HapiFHIRHelpers;

public class ResearchelementdefinitionConversion 
{
	public Patient Researchelementdefinitions(main.templateoutput.Model.Researchelementdefinition researchelementdefinition) 
	{
			Patient  Researchelementdefinitionobj = new Patient(); 

						Researchelementdefinitionobj.setUrl(HapiFHIRHelpers.createuri(researchelementdefinition.getRedUrlUri() /** { "tree" :"ResearchElementDefinition.url", "datatype" : "uri", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setUrl"} **/
						));
Researchelementdefinitionobj.addIdentifier(HapiFHIRHelpers.createIdentifier(researchelementdefinition.getRedIdentifierIdentifierUse() /** { "tree" :"ResearchElementDefinition.identifier", "datatype" : "Identifier, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setUse"} **/
						, researchelementdefinition.getRdDntfrDntfrTpCcCSstm() /** { "tree" :"ResearchElementDefinition.identifier", "datatype" : "Identifier, CodeableConcept, Coding, uri", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setType, addCoding, setSystem"} **/
						, researchelementdefinition.getRdDntfrDntfrTpCcCVrsn() /** { "tree" :"ResearchElementDefinition.identifier", "datatype" : "Identifier, CodeableConcept, Coding, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setType, addCoding, setVersion"} **/
						, researchelementdefinition.getRdDntfrDntfrTpCcCCde() /** { "tree" :"ResearchElementDefinition.identifier", "datatype" : "Identifier, CodeableConcept, Coding, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setType, addCoding, setCode"} **/
						, researchelementdefinition.getRdDntfrDntfrTpCcCDsplay() /** { "tree" :"ResearchElementDefinition.identifier", "datatype" : "Identifier, CodeableConcept, Coding, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setType, addCoding, setDisplay"} **/
						, researchelementdefinition.getRdDntfrDntfrTpCcCSrSlctd() /** { "tree" :"ResearchElementDefinition.identifier", "datatype" : "Identifier, CodeableConcept, Coding, boolean", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setType, addCoding, setUserSelected"} **/
						, researchelementdefinition.getRdDntfrDntfrTpCcTxt() /** { "tree" :"ResearchElementDefinition.identifier", "datatype" : "Identifier, CodeableConcept, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setType, setText"} **/
						, researchelementdefinition.getRdDntfrDntfrPrdPrdStrt() /** { "tree" :"ResearchElementDefinition.identifier", "datatype" : "Identifier, Period, dateTime", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setPeriod, setStart"} **/
						, researchelementdefinition.getRdDntfrDntfrPrdPrdNd() /** { "tree" :"ResearchElementDefinition.identifier", "datatype" : "Identifier, Period, dateTime", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setPeriod, setEnd"} **/
						, researchelementdefinition.getRedIdentifierIdentifierAssigner() /** { "tree" :"ResearchElementDefinition.identifier", "datatype" : "Identifier, Reference", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setAssigner"} **/
						, researchelementdefinition.getRedIdentifierIdentifierValue() /** { "tree" :"ResearchElementDefinition.identifier", "datatype" : "Identifier, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setValue"} **/
						, researchelementdefinition.getRedIdentifierIdentifierSystem() /** { "tree" :"ResearchElementDefinition.identifier", "datatype" : "Identifier, uri", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addIdentifier, setSystem"} **/
						));
Researchelementdefinitionobj.setVersion(HapiFHIRHelpers.createstring(researchelementdefinition.getRedVersionString() /** { "tree" :"ResearchElementDefinition.version", "datatype" : "string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setVersion"} **/
						));
Researchelementdefinitionobj.setName(HapiFHIRHelpers.createstring(researchelementdefinition.getRedNameString() /** { "tree" :"ResearchElementDefinition.name", "datatype" : "string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setName"} **/
						));
Researchelementdefinitionobj.setTitle(HapiFHIRHelpers.createstring(researchelementdefinition.getRedTitleString() /** { "tree" :"ResearchElementDefinition.title", "datatype" : "string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setTitle"} **/
						));
Researchelementdefinitionobj.setShortTitle(HapiFHIRHelpers.createstring(researchelementdefinition.getRedShortTitleString() /** { "tree" :"ResearchElementDefinition.shortTitle", "datatype" : "string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setShortTitle"} **/
						));
Researchelementdefinitionobj.setSubtitle(HapiFHIRHelpers.createstring(researchelementdefinition.getRedSubtitleString() /** { "tree" :"ResearchElementDefinition.subtitle", "datatype" : "string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setSubtitle"} **/
						));
Researchelementdefinitionobj.setStatus(HapiFHIRHelpers.createcode(researchelementdefinition.getRedStatusCode() /** { "tree" :"ResearchElementDefinition.status", "datatype" : "code", "cardinality" : "Required", "elementtree" : [] , "methodName" : "setStatus"} **/
						));
Researchelementdefinitionobj.setExperimental(HapiFHIRHelpers.createboolean(researchelementdefinition.getRedExperimentalBoolean() /** { "tree" :"ResearchElementDefinition.experimental", "datatype" : "boolean", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setExperimental"} **/
						));
Researchelementdefinitionobj.setSubjectCodeableconcept(HapiFHIRHelpers.createCodeableConcept(researchelementdefinition.getRdSbjctCdblcncptCcCdngCSstm() /** { "tree" :"ResearchElementDefinition.subjectCodeableconcept", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setSubjectCodeableconcept, addCoding, setSystem"} **/
						, researchelementdefinition.getRdSbjctCdblcncptCcCdngCVrsn() /** { "tree" :"ResearchElementDefinition.subjectCodeableconcept", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setSubjectCodeableconcept, addCoding, setVersion"} **/
						, researchelementdefinition.getRdSbjctCdblcncptCcCdngCCde() /** { "tree" :"ResearchElementDefinition.subjectCodeableconcept", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setSubjectCodeableconcept, addCoding, setCode"} **/
						, researchelementdefinition.getRdSbjctCdblcncptCcCdngCDsplay() /** { "tree" :"ResearchElementDefinition.subjectCodeableconcept", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setSubjectCodeableconcept, addCoding, setDisplay"} **/
						, researchelementdefinition.getRdSbjctCdblcncptCcCdngCSrSlctd() /** { "tree" :"ResearchElementDefinition.subjectCodeableconcept", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setSubjectCodeableconcept, addCoding, setUserSelected"} **/
						, researchelementdefinition.getRedSubjectCodeableconceptCcText() /** { "tree" :"ResearchElementDefinition.subjectCodeableconcept", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setSubjectCodeableconcept, setText"} **/
						));
Researchelementdefinitionobj.setSubjectReference(group)(HapiFHIRHelpers.createReference(researchelementdefinition.getRedSubjectReferenceReference() /** { "tree" :"ResearchElementDefinition.subjectReference", "datatype" : "Reference", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setSubjectReference(group)"} **/
						));
Researchelementdefinitionobj.setDate(HapiFHIRHelpers.createdateTime(researchelementdefinition.getRedDateDateTime() /** { "tree" :"ResearchElementDefinition.date", "datatype" : "dateTime", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setDate"} **/
						));
Researchelementdefinitionobj.setPublisher(HapiFHIRHelpers.createstring(researchelementdefinition.getRedPublisherString() /** { "tree" :"ResearchElementDefinition.publisher", "datatype" : "string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setPublisher"} **/
						));
Researchelementdefinitionobj.addContact(HapiFHIRHelpers.createContactDetail(researchelementdefinition.getRdCntctCntctDtlTlcmCntctPntPrdStrt() /** { "tree" :"ResearchElementDefinition.contact", "datatype" : "ContactDetail, ContactPoint, Period, dateTime", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addContact, setTelecom, setPeriod, setStart"} **/
						, researchelementdefinition.getRdCntctCntctDtlTlcmCntctPntPrdNd() /** { "tree" :"ResearchElementDefinition.contact", "datatype" : "ContactDetail, ContactPoint, Period, dateTime", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addContact, setTelecom, setPeriod, setEnd"} **/
						, researchelementdefinition.getRdCntctCntctDtlTlcmCntctPntSstm() /** { "tree" :"ResearchElementDefinition.contact", "datatype" : "ContactDetail, ContactPoint, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addContact, setTelecom, setSystem"} **/
						, researchelementdefinition.getRdCntctCntctDtlTlcmCntctPntVlue() /** { "tree" :"ResearchElementDefinition.contact", "datatype" : "ContactDetail, ContactPoint, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addContact, setTelecom, setValue"} **/
						, researchelementdefinition.getRdCntctCntctDtlTlcmCntctPntSe() /** { "tree" :"ResearchElementDefinition.contact", "datatype" : "ContactDetail, ContactPoint, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addContact, setTelecom, setUse"} **/
						, researchelementdefinition.getRdCntctCntctDtlTlcmCntctPntRnk() /** { "tree" :"ResearchElementDefinition.contact", "datatype" : "ContactDetail, ContactPoint, positiveInt", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addContact, setTelecom, setRank"} **/
						, researchelementdefinition.getRedContactContactDetailName() /** { "tree" :"ResearchElementDefinition.contact", "datatype" : "ContactDetail, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addContact, addName"} **/
						));
Researchelementdefinitionobj.setDescription(HapiFHIRHelpers.createmarkdown(researchelementdefinition.getRedDescriptionMarkdown() /** { "tree" :"ResearchElementDefinition.description", "datatype" : "markdown", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setDescription"} **/
						));
Researchelementdefinitionobj.addComment(HapiFHIRHelpers.createstring(researchelementdefinition.getRedCommentString() /** { "tree" :"ResearchElementDefinition.comment", "datatype" : "string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addComment"} **/
						));
Researchelementdefinitionobj.addUseContext(HapiFHIRHelpers.createUsageContext(researchelementdefinition.getRdSCntxtSgCntxtVlCcCcCSstm() /** { "tree" :"ResearchElementDefinition.useContext", "datatype" : "UsageContext, CodeableConcept, Coding, uri", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addUseContext, addValueCodeableConcept, addCoding, setSystem"} **/
						, researchelementdefinition.getRdSCntxtSgCntxtVlCcCcCVrsn() /** { "tree" :"ResearchElementDefinition.useContext", "datatype" : "UsageContext, CodeableConcept, Coding, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addUseContext, addValueCodeableConcept, addCoding, setVersion"} **/
						, researchelementdefinition.getRdSCntxtSgCntxtVlCcCcCCde() /** { "tree" :"ResearchElementDefinition.useContext", "datatype" : "UsageContext, CodeableConcept, Coding, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addUseContext, addValueCodeableConcept, addCoding, setCode"} **/
						, researchelementdefinition.getRdSCntxtSgCntxtVlCcCcCDsplay() /** { "tree" :"ResearchElementDefinition.useContext", "datatype" : "UsageContext, CodeableConcept, Coding, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addUseContext, addValueCodeableConcept, addCoding, setDisplay"} **/
						, researchelementdefinition.getRdSCntxtSgCntxtVlCcCcCSrSlctd() /** { "tree" :"ResearchElementDefinition.useContext", "datatype" : "UsageContext, CodeableConcept, Coding, boolean", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addUseContext, addValueCodeableConcept, addCoding, setUserSelected"} **/
						, researchelementdefinition.getRdSCntxtSgCntxtVlCcCcTxt() /** { "tree" :"ResearchElementDefinition.useContext", "datatype" : "UsageContext, CodeableConcept, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addUseContext, addValueCodeableConcept, setText"} **/
						, researchelementdefinition.getRdSCntxtSgCntxtCdCSstm() /** { "tree" :"ResearchElementDefinition.useContext", "datatype" : "UsageContext, Coding, uri", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addUseContext, addCode, setSystem"} **/
						, researchelementdefinition.getRdSCntxtSgCntxtCdCVrsn() /** { "tree" :"ResearchElementDefinition.useContext", "datatype" : "UsageContext, Coding, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addUseContext, addCode, setVersion"} **/
						, researchelementdefinition.getRdSCntxtSgCntxtCdCCde() /** { "tree" :"ResearchElementDefinition.useContext", "datatype" : "UsageContext, Coding, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addUseContext, addCode, setCode"} **/
						, researchelementdefinition.getRdSCntxtSgCntxtCdCDsplay() /** { "tree" :"ResearchElementDefinition.useContext", "datatype" : "UsageContext, Coding, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addUseContext, addCode, setDisplay"} **/
						, researchelementdefinition.getRdSCntxtSgCntxtCdCSrSlctd() /** { "tree" :"ResearchElementDefinition.useContext", "datatype" : "UsageContext, Coding, boolean", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addUseContext, addCode, setUserSelected"} **/
						, researchelementdefinition.getRdSCntxtSgCntxtVlQnttQnttVlue() /** { "tree" :"ResearchElementDefinition.useContext", "datatype" : "UsageContext, Quantity, decimal", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addUseContext, addValueQuantity, setValue"} **/
						, researchelementdefinition.getRdSCntxtSgCntxtVlQnttQnttCmprtr() /** { "tree" :"ResearchElementDefinition.useContext", "datatype" : "UsageContext, Quantity, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addUseContext, addValueQuantity, setComparator"} **/
						, researchelementdefinition.getRdSCntxtSgCntxtVlQnttQnttNt() /** { "tree" :"ResearchElementDefinition.useContext", "datatype" : "UsageContext, Quantity, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addUseContext, addValueQuantity, setUnit"} **/
						, researchelementdefinition.getRdSCntxtSgCntxtVlQnttQnttSstm() /** { "tree" :"ResearchElementDefinition.useContext", "datatype" : "UsageContext, Quantity, uri", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addUseContext, addValueQuantity, setSystem"} **/
						, researchelementdefinition.getRdSCntxtSgCntxtVlQnttQnttCde() /** { "tree" :"ResearchElementDefinition.useContext", "datatype" : "UsageContext, Quantity, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addUseContext, addValueQuantity, setCode"} **/
						, researchelementdefinition.getRdSCntxtSgCntxtVlRngRngLw() /** { "tree" :"ResearchElementDefinition.useContext", "datatype" : "UsageContext, Range, SimpleQuantity", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addUseContext, addValueRange, setLow"} **/
						, researchelementdefinition.getRdSCntxtSgCntxtVlRngRngHgh() /** { "tree" :"ResearchElementDefinition.useContext", "datatype" : "UsageContext, Range, SimpleQuantity", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addUseContext, addValueRange, setHigh"} **/
						, researchelementdefinition.getRdSCntxtSgCntxtVlRfrnce() /** { "tree" :"ResearchElementDefinition.useContext", "datatype" : "UsageContext, Reference", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addUseContext, addValueReference"} **/
						));
Researchelementdefinitionobj.addJurisdiction(HapiFHIRHelpers.createCodeableConcept(researchelementdefinition.getRdJrsdctnCcCdngCSstm() /** { "tree" :"ResearchElementDefinition.jurisdiction", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addJurisdiction, addCoding, setSystem"} **/
						, researchelementdefinition.getRdJrsdctnCcCdngCVrsn() /** { "tree" :"ResearchElementDefinition.jurisdiction", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addJurisdiction, addCoding, setVersion"} **/
						, researchelementdefinition.getRedJurisdictionCcCodingCCode() /** { "tree" :"ResearchElementDefinition.jurisdiction", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addJurisdiction, addCoding, setCode"} **/
						, researchelementdefinition.getRdJrsdctnCcCdngCDsplay() /** { "tree" :"ResearchElementDefinition.jurisdiction", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addJurisdiction, addCoding, setDisplay"} **/
						, researchelementdefinition.getRdJrsdctnCcCdngCSrSlctd() /** { "tree" :"ResearchElementDefinition.jurisdiction", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addJurisdiction, addCoding, setUserSelected"} **/
						, researchelementdefinition.getRedJurisdictionCcText() /** { "tree" :"ResearchElementDefinition.jurisdiction", "datatype" : "CodeableConcept, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addJurisdiction, setText"} **/
						));
Researchelementdefinitionobj.setPurpose(HapiFHIRHelpers.createmarkdown(researchelementdefinition.getRedPurposeMarkdown() /** { "tree" :"ResearchElementDefinition.purpose", "datatype" : "markdown", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setPurpose"} **/
						));
Researchelementdefinitionobj.setUsage(HapiFHIRHelpers.createstring(researchelementdefinition.getRedUsageString() /** { "tree" :"ResearchElementDefinition.usage", "datatype" : "string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setUsage"} **/
						));
Researchelementdefinitionobj.setCopyright(HapiFHIRHelpers.createmarkdown(researchelementdefinition.getRedCopyrightMarkdown() /** { "tree" :"ResearchElementDefinition.copyright", "datatype" : "markdown", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setCopyright"} **/
						));
Researchelementdefinitionobj.setApprovalDate(HapiFHIRHelpers.createdate(researchelementdefinition.getRedApprovalDateDate() /** { "tree" :"ResearchElementDefinition.approvalDate", "datatype" : "date", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setApprovalDate"} **/
						));
Researchelementdefinitionobj.setLastReviewDate(HapiFHIRHelpers.createdate(researchelementdefinition.getRedLastReviewDateDate() /** { "tree" :"ResearchElementDefinition.lastReviewDate", "datatype" : "date", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setLastReviewDate"} **/
						));
Researchelementdefinitionobj.setEffectivePeriod(HapiFHIRHelpers.createPeriod(researchelementdefinition.getRedEffectivePeriodPeriodStart() /** { "tree" :"ResearchElementDefinition.effectivePeriod", "datatype" : "Period, dateTime", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setEffectivePeriod, setStart"} **/
						, researchelementdefinition.getRedEffectivePeriodPeriodEnd() /** { "tree" :"ResearchElementDefinition.effectivePeriod", "datatype" : "Period, dateTime", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setEffectivePeriod, setEnd"} **/
						));
Researchelementdefinitionobj.addTopic(HapiFHIRHelpers.createCodeableConcept(researchelementdefinition.getRedTopicCcCodingCSystem() /** { "tree" :"ResearchElementDefinition.topic", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addTopic, addCoding, setSystem"} **/
						, researchelementdefinition.getRedTopicCcCodingCVersion() /** { "tree" :"ResearchElementDefinition.topic", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addTopic, addCoding, setVersion"} **/
						, researchelementdefinition.getRedTopicCcCodingCCode() /** { "tree" :"ResearchElementDefinition.topic", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addTopic, addCoding, setCode"} **/
						, researchelementdefinition.getRedTopicCcCodingCDisplay() /** { "tree" :"ResearchElementDefinition.topic", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addTopic, addCoding, setDisplay"} **/
						, researchelementdefinition.getRedTopicCcCodingCUserSelected() /** { "tree" :"ResearchElementDefinition.topic", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addTopic, addCoding, setUserSelected"} **/
						, researchelementdefinition.getRedTopicCcText() /** { "tree" :"ResearchElementDefinition.topic", "datatype" : "CodeableConcept, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addTopic, setText"} **/
						));
Researchelementdefinitionobj.addAuthor(HapiFHIRHelpers.createContactDetail(researchelementdefinition.getRdThrCntctDtlTlcmCntctPntPrdStrt() /** { "tree" :"ResearchElementDefinition.author", "datatype" : "ContactDetail, ContactPoint, Period, dateTime", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addAuthor, setTelecom, setPeriod, setStart"} **/
						, researchelementdefinition.getRdThrCntctDtlTlcmCntctPntPrdNd() /** { "tree" :"ResearchElementDefinition.author", "datatype" : "ContactDetail, ContactPoint, Period, dateTime", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addAuthor, setTelecom, setPeriod, setEnd"} **/
						, researchelementdefinition.getRdThrCntctDtlTlcmCntctPntSstm() /** { "tree" :"ResearchElementDefinition.author", "datatype" : "ContactDetail, ContactPoint, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addAuthor, setTelecom, setSystem"} **/
						, researchelementdefinition.getRdThrCntctDtlTlcmCntctPntVlue() /** { "tree" :"ResearchElementDefinition.author", "datatype" : "ContactDetail, ContactPoint, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addAuthor, setTelecom, setValue"} **/
						, researchelementdefinition.getRdThrCntctDtlTlcmCntctPntSe() /** { "tree" :"ResearchElementDefinition.author", "datatype" : "ContactDetail, ContactPoint, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addAuthor, setTelecom, setUse"} **/
						, researchelementdefinition.getRdThrCntctDtlTlcmCntctPntRnk() /** { "tree" :"ResearchElementDefinition.author", "datatype" : "ContactDetail, ContactPoint, positiveInt", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addAuthor, setTelecom, setRank"} **/
						, researchelementdefinition.getRedAuthorContactDetailName() /** { "tree" :"ResearchElementDefinition.author", "datatype" : "ContactDetail, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addAuthor, addName"} **/
						));
Researchelementdefinitionobj.addEditor(HapiFHIRHelpers.createContactDetail(researchelementdefinition.getRdDtrCntctDtlTlcmCntctPntPrdStrt() /** { "tree" :"ResearchElementDefinition.editor", "datatype" : "ContactDetail, ContactPoint, Period, dateTime", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addEditor, setTelecom, setPeriod, setStart"} **/
						, researchelementdefinition.getRdDtrCntctDtlTlcmCntctPntPrdNd() /** { "tree" :"ResearchElementDefinition.editor", "datatype" : "ContactDetail, ContactPoint, Period, dateTime", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addEditor, setTelecom, setPeriod, setEnd"} **/
						, researchelementdefinition.getRdDtrCntctDtlTlcmCntctPntSstm() /** { "tree" :"ResearchElementDefinition.editor", "datatype" : "ContactDetail, ContactPoint, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addEditor, setTelecom, setSystem"} **/
						, researchelementdefinition.getRdDtrCntctDtlTlcmCntctPntVlue() /** { "tree" :"ResearchElementDefinition.editor", "datatype" : "ContactDetail, ContactPoint, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addEditor, setTelecom, setValue"} **/
						, researchelementdefinition.getRdDtrCntctDtlTlcmCntctPntSe() /** { "tree" :"ResearchElementDefinition.editor", "datatype" : "ContactDetail, ContactPoint, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addEditor, setTelecom, setUse"} **/
						, researchelementdefinition.getRdDtrCntctDtlTlcmCntctPntRnk() /** { "tree" :"ResearchElementDefinition.editor", "datatype" : "ContactDetail, ContactPoint, positiveInt", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addEditor, setTelecom, setRank"} **/
						, researchelementdefinition.getRedEditorContactDetailName() /** { "tree" :"ResearchElementDefinition.editor", "datatype" : "ContactDetail, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addEditor, addName"} **/
						));
Researchelementdefinitionobj.addReviewer(HapiFHIRHelpers.createContactDetail(researchelementdefinition.getRdRvwrCntctDtlTlcmCntctPntPrdStrt() /** { "tree" :"ResearchElementDefinition.reviewer", "datatype" : "ContactDetail, ContactPoint, Period, dateTime", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addReviewer, setTelecom, setPeriod, setStart"} **/
						, researchelementdefinition.getRdRvwrCntctDtlTlcmCntctPntPrdNd() /** { "tree" :"ResearchElementDefinition.reviewer", "datatype" : "ContactDetail, ContactPoint, Period, dateTime", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addReviewer, setTelecom, setPeriod, setEnd"} **/
						, researchelementdefinition.getRdRvwrCntctDtlTlcmCntctPntSstm() /** { "tree" :"ResearchElementDefinition.reviewer", "datatype" : "ContactDetail, ContactPoint, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addReviewer, setTelecom, setSystem"} **/
						, researchelementdefinition.getRdRvwrCntctDtlTlcmCntctPntVlue() /** { "tree" :"ResearchElementDefinition.reviewer", "datatype" : "ContactDetail, ContactPoint, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addReviewer, setTelecom, setValue"} **/
						, researchelementdefinition.getRdRvwrCntctDtlTlcmCntctPntSe() /** { "tree" :"ResearchElementDefinition.reviewer", "datatype" : "ContactDetail, ContactPoint, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addReviewer, setTelecom, setUse"} **/
						, researchelementdefinition.getRdRvwrCntctDtlTlcmCntctPntRnk() /** { "tree" :"ResearchElementDefinition.reviewer", "datatype" : "ContactDetail, ContactPoint, positiveInt", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addReviewer, setTelecom, setRank"} **/
						, researchelementdefinition.getRedReviewerContactDetailName() /** { "tree" :"ResearchElementDefinition.reviewer", "datatype" : "ContactDetail, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addReviewer, addName"} **/
						));
Researchelementdefinitionobj.addEndorser(HapiFHIRHelpers.createContactDetail(researchelementdefinition.getRdNdrsrCntctDtlTlcmCntctPntPrdStrt() /** { "tree" :"ResearchElementDefinition.endorser", "datatype" : "ContactDetail, ContactPoint, Period, dateTime", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addEndorser, setTelecom, setPeriod, setStart"} **/
						, researchelementdefinition.getRdNdrsrCntctDtlTlcmCntctPntPrdNd() /** { "tree" :"ResearchElementDefinition.endorser", "datatype" : "ContactDetail, ContactPoint, Period, dateTime", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addEndorser, setTelecom, setPeriod, setEnd"} **/
						, researchelementdefinition.getRdNdrsrCntctDtlTlcmCntctPntSstm() /** { "tree" :"ResearchElementDefinition.endorser", "datatype" : "ContactDetail, ContactPoint, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addEndorser, setTelecom, setSystem"} **/
						, researchelementdefinition.getRdNdrsrCntctDtlTlcmCntctPntVlue() /** { "tree" :"ResearchElementDefinition.endorser", "datatype" : "ContactDetail, ContactPoint, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addEndorser, setTelecom, setValue"} **/
						, researchelementdefinition.getRdNdrsrCntctDtlTlcmCntctPntSe() /** { "tree" :"ResearchElementDefinition.endorser", "datatype" : "ContactDetail, ContactPoint, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addEndorser, setTelecom, setUse"} **/
						, researchelementdefinition.getRdNdrsrCntctDtlTlcmCntctPntRnk() /** { "tree" :"ResearchElementDefinition.endorser", "datatype" : "ContactDetail, ContactPoint, positiveInt", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addEndorser, setTelecom, setRank"} **/
						, researchelementdefinition.getRedEndorserContactDetailName() /** { "tree" :"ResearchElementDefinition.endorser", "datatype" : "ContactDetail, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addEndorser, addName"} **/
						));
Researchelementdefinitionobj.addRelatedArtifact(HapiFHIRHelpers.createRelatedArtifact(researchelementdefinition.getRdRltdrtfctRltdrtfctDcmntTtchmntCntntTpe() /** { "tree" :"ResearchElementDefinition.relatedArtifact", "datatype" : "RelatedArtifact, Attachment, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addRelatedArtifact, setDocument, setContentType"} **/
						, researchelementdefinition.getRdRltdrtfctRltdrtfctDcmntTtchmntLngge() /** { "tree" :"ResearchElementDefinition.relatedArtifact", "datatype" : "RelatedArtifact, Attachment, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addRelatedArtifact, setDocument, setLanguage"} **/
						, researchelementdefinition.getRdRltdrtfctRltdrtfctDcmntTtchmntDta() /** { "tree" :"ResearchElementDefinition.relatedArtifact", "datatype" : "RelatedArtifact, Attachment, base64Binary", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addRelatedArtifact, setDocument, setData"} **/
						, researchelementdefinition.getRdRltdrtfctRltdrtfctDcmntTtchmntRl() /** { "tree" :"ResearchElementDefinition.relatedArtifact", "datatype" : "RelatedArtifact, Attachment, url", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addRelatedArtifact, setDocument, setUrl"} **/
						, researchelementdefinition.getRdRltdrtfctRltdrtfctDcmntTtchmntSze() /** { "tree" :"ResearchElementDefinition.relatedArtifact", "datatype" : "RelatedArtifact, Attachment, unsignedInt", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addRelatedArtifact, setDocument, setSize"} **/
						, researchelementdefinition.getRdRltdrtfctRltdrtfctDcmntTtchmntHsh() /** { "tree" :"ResearchElementDefinition.relatedArtifact", "datatype" : "RelatedArtifact, Attachment, base64Binary", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addRelatedArtifact, setDocument, setHash"} **/
						, researchelementdefinition.getRdRltdrtfctRltdrtfctDcmntTtchmntTtle() /** { "tree" :"ResearchElementDefinition.relatedArtifact", "datatype" : "RelatedArtifact, Attachment, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addRelatedArtifact, setDocument, setTitle"} **/
						, researchelementdefinition.getRdRltdrtfctRltdrtfctDcmntTtchmntCrtn() /** { "tree" :"ResearchElementDefinition.relatedArtifact", "datatype" : "RelatedArtifact, Attachment, dateTime", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addRelatedArtifact, setDocument, setCreation"} **/
						, researchelementdefinition.getRdRltdrtfctRltdrtfctRsrce() /** { "tree" :"ResearchElementDefinition.relatedArtifact", "datatype" : "RelatedArtifact, canonical", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addRelatedArtifact, setResource"} **/
						, researchelementdefinition.getRdRltdrtfctRltdrtfctTpe() /** { "tree" :"ResearchElementDefinition.relatedArtifact", "datatype" : "RelatedArtifact, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addRelatedArtifact, setType"} **/
						, researchelementdefinition.getRdRltdrtfctRltdrtfctCttn() /** { "tree" :"ResearchElementDefinition.relatedArtifact", "datatype" : "RelatedArtifact, markdown", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addRelatedArtifact, setCitation"} **/
						, researchelementdefinition.getRdRltdrtfctRltdrtfctLbl() /** { "tree" :"ResearchElementDefinition.relatedArtifact", "datatype" : "RelatedArtifact, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addRelatedArtifact, setLabel"} **/
						, researchelementdefinition.getRdRltdrtfctRltdrtfctDsplay() /** { "tree" :"ResearchElementDefinition.relatedArtifact", "datatype" : "RelatedArtifact, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addRelatedArtifact, setDisplay"} **/
						, researchelementdefinition.getRdRltdrtfctRltdrtfctRl() /** { "tree" :"ResearchElementDefinition.relatedArtifact", "datatype" : "RelatedArtifact, url", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addRelatedArtifact, setUrl"} **/
						));
Researchelementdefinitionobj.addLibrary(HapiFHIRHelpers.createcanonical(researchelementdefinition.getRedLibraryCanonical() /** { "tree" :"ResearchElementDefinition.library", "datatype" : "canonical", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addLibrary"} **/
						));
Researchelementdefinitionobj.setType(HapiFHIRHelpers.createcode(researchelementdefinition.getRedTypeCode() /** { "tree" :"ResearchElementDefinition.type", "datatype" : "code", "cardinality" : "Required", "elementtree" : [] , "methodName" : "setType"} **/
						));
Researchelementdefinitionobj.setVariableType(HapiFHIRHelpers.createcode(researchelementdefinition.getRedVariableTypeCode() /** { "tree" :"ResearchElementDefinition.variableType", "datatype" : "code", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setVariableType"} **/
						));
Researchelementdefinitionobj.setDefinitionCodeableconcept(HapiFHIRHelpers.createCodeableConcept(researchelementdefinition.getRdChrctrDfntnCdblcncptCcCdngCSstm() /** { "tree" :"ResearchElementDefinition.characteristic.definitionCodeableconcept", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionCodeableconcept, addCoding, setSystem"} **/
						, researchelementdefinition.getRdChrctrDfntnCdblcncptCcCdngCVrsn() /** { "tree" :"ResearchElementDefinition.characteristic.definitionCodeableconcept", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionCodeableconcept, addCoding, setVersion"} **/
						, researchelementdefinition.getRdChrctrDfntnCdblcncptCcCdngCCde() /** { "tree" :"ResearchElementDefinition.characteristic.definitionCodeableconcept", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionCodeableconcept, addCoding, setCode"} **/
						, researchelementdefinition.getRdChrctrDfntnCdblcncptCcCdngCDsplay() /** { "tree" :"ResearchElementDefinition.characteristic.definitionCodeableconcept", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionCodeableconcept, addCoding, setDisplay"} **/
						, researchelementdefinition.getRdChrctrDfntnCdblcncptCcCdngCSrSlctd() /** { "tree" :"ResearchElementDefinition.characteristic.definitionCodeableconcept", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionCodeableconcept, addCoding, setUserSelected"} **/
						, researchelementdefinition.getRdChrctrDfntnCdblcncptCcTxt() /** { "tree" :"ResearchElementDefinition.characteristic.definitionCodeableconcept", "datatype" : "CodeableConcept, string", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionCodeableconcept, setText"} **/
						));
Researchelementdefinitionobj.setDefinitionCanonical(valueset)(HapiFHIRHelpers.createcanonical(researchelementdefinition.getRdChrctrDfntnCnnclCnncl() /** { "tree" :"ResearchElementDefinition.characteristic.definitionCanonical", "datatype" : "canonical", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionCanonical(valueset)"} **/
						));
Researchelementdefinitionobj.setDefinitionExpression(HapiFHIRHelpers.createExpression(researchelementdefinition.getRdChrctrDfntnxprssnXprssnLngge() /** { "tree" :"ResearchElementDefinition.characteristic.definitionExpression", "datatype" : "Expression, code", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionExpression, setLanguage"} **/
						, researchelementdefinition.getRdChrctrDfntnxprssnXprssnNme() /** { "tree" :"ResearchElementDefinition.characteristic.definitionExpression", "datatype" : "Expression, id", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionExpression, setName"} **/
						, researchelementdefinition.getRdChrctrDfntnxprssnXprssnDscrptn() /** { "tree" :"ResearchElementDefinition.characteristic.definitionExpression", "datatype" : "Expression, string", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionExpression, setDescription"} **/
						, researchelementdefinition.getRdChrctrDfntnxprssnXprssnXprssn() /** { "tree" :"ResearchElementDefinition.characteristic.definitionExpression", "datatype" : "Expression, string", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionExpression, setExpression"} **/
						, researchelementdefinition.getRdChrctrDfntnxprssnXprssnRfrnce() /** { "tree" :"ResearchElementDefinition.characteristic.definitionExpression", "datatype" : "Expression, uri", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionExpression, setReference"} **/
						));
Researchelementdefinitionobj.setDefinitionDatarequirement(HapiFHIRHelpers.createDataRequirement(researchelementdefinition.getRdChrctrDfntnDtrqrmntDtRqrmntPrfle() /** { "tree" :"ResearchElementDefinition.characteristic.definitionDatarequirement", "datatype" : "DataRequirement, canonical", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionDatarequirement, addProfile"} **/
						, researchelementdefinition.getRdChrctrDfntnDtrqrmntDtRqrmntTpe() /** { "tree" :"ResearchElementDefinition.characteristic.definitionDatarequirement", "datatype" : "DataRequirement, code", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionDatarequirement, setType"} **/
						, researchelementdefinition.getRdChrctrDfntnDtrqrmntDtRqrmntSbjctCcCcCSstm() /** { "tree" :"ResearchElementDefinition.characteristic.definitionDatarequirement", "datatype" : "DataRequirement, CodeableConcept, Coding, uri", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionDatarequirement, setSubjectCodeableConcept, addCoding, setSystem"} **/
						, researchelementdefinition.getRdChrctrDfntnDtrqrmntDtRqrmntSbjctCcCcCVrsn() /** { "tree" :"ResearchElementDefinition.characteristic.definitionDatarequirement", "datatype" : "DataRequirement, CodeableConcept, Coding, string", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionDatarequirement, setSubjectCodeableConcept, addCoding, setVersion"} **/
						, researchelementdefinition.getRdChrctrDfntnDtrqrmntDtRqrmntSbjctCcCcCCde() /** { "tree" :"ResearchElementDefinition.characteristic.definitionDatarequirement", "datatype" : "DataRequirement, CodeableConcept, Coding, code", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionDatarequirement, setSubjectCodeableConcept, addCoding, setCode"} **/
						, researchelementdefinition.getRdChrctrDfntnDtrqrmntDtRqrmntSbjctCcCcCDsplay() /** { "tree" :"ResearchElementDefinition.characteristic.definitionDatarequirement", "datatype" : "DataRequirement, CodeableConcept, Coding, string", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionDatarequirement, setSubjectCodeableConcept, addCoding, setDisplay"} **/
						, researchelementdefinition.getRdChrctrDfntnDtrqrmntDtRqrmntSbjctCcCcCSrSlctd() /** { "tree" :"ResearchElementDefinition.characteristic.definitionDatarequirement", "datatype" : "DataRequirement, CodeableConcept, Coding, boolean", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionDatarequirement, setSubjectCodeableConcept, addCoding, setUserSelected"} **/
						, researchelementdefinition.getRdChrctrDfntnDtrqrmntDtRqrmntSbjctCcCcTxt() /** { "tree" :"ResearchElementDefinition.characteristic.definitionDatarequirement", "datatype" : "DataRequirement, CodeableConcept, string", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionDatarequirement, setSubjectCodeableConcept, setText"} **/
						, researchelementdefinition.getRdChrctrDfntnDtrqrmntDtRqrmntCdFltrVlSt() /** { "tree" :"ResearchElementDefinition.characteristic.definitionDatarequirement", "datatype" : "DataRequirement, Element, canonical", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionDatarequirement, addCodeFilter, setValueSet"} **/
						, researchelementdefinition.getRdChrctrDfntnDtrqrmntDtRqrmntSrtDrctn() /** { "tree" :"ResearchElementDefinition.characteristic.definitionDatarequirement", "datatype" : "DataRequirement, code", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionDatarequirement, addSort, setDirection"} **/
						, researchelementdefinition.getRdChrctrDfntnDtrqrmntDtRqrmntCdFltrCde() /** { "tree" :"ResearchElementDefinition.characteristic.definitionDatarequirement", "datatype" : "DataRequirement, Element, Coding", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionDatarequirement, addCodeFilter, addCode"} **/
						, researchelementdefinition.getRdChrctrDfntnDtrqrmntDtRqrmntDtFltrVlDtTme() /** { "tree" :"ResearchElementDefinition.characteristic.definitionDatarequirement", "datatype" : "DataRequirement, Element, dateTime", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionDatarequirement, addDateFilter, setValueDateTime"} **/
						, researchelementdefinition.getRdChrctrDfntnDtrqrmntDtRqrmntDtFltrVlDrtn() /** { "tree" :"ResearchElementDefinition.characteristic.definitionDatarequirement", "datatype" : "DataRequirement, Element, Duration", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionDatarequirement, addDateFilter, setValueDuration"} **/
						, researchelementdefinition.getRdChrctrDfntnDtrqrmntDtRqrmntDtFltrVlPrd() /** { "tree" :"ResearchElementDefinition.characteristic.definitionDatarequirement", "datatype" : "DataRequirement, Element, Period", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionDatarequirement, addDateFilter, setValuePeriod"} **/
						, researchelementdefinition.getRdChrctrDfntnDtrqrmntDtRqrmntCdFltrPth() /** { "tree" :"ResearchElementDefinition.characteristic.definitionDatarequirement", "datatype" : "DataRequirement, Element, string", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionDatarequirement, addCodeFilter, setPath"} **/
						, researchelementdefinition.getRdChrctrDfntnDtrqrmntDtRqrmntCdFltrSrchPrm() /** { "tree" :"ResearchElementDefinition.characteristic.definitionDatarequirement", "datatype" : "DataRequirement, Element, string", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionDatarequirement, addCodeFilter, setSearchParam"} **/
						, researchelementdefinition.getRdChrctrDfntnDtrqrmntDtRqrmntDtFltrPth() /** { "tree" :"ResearchElementDefinition.characteristic.definitionDatarequirement", "datatype" : "DataRequirement, Element, string", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionDatarequirement, addDateFilter, setPath"} **/
						, researchelementdefinition.getRdChrctrDfntnDtrqrmntDtRqrmntDtFltrSrchPrm() /** { "tree" :"ResearchElementDefinition.characteristic.definitionDatarequirement", "datatype" : "DataRequirement, Element, string", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionDatarequirement, addDateFilter, setSearchParam"} **/
						, researchelementdefinition.getRdChrctrDfntnDtrqrmntDtRqrmntSrtPth() /** { "tree" :"ResearchElementDefinition.characteristic.definitionDatarequirement", "datatype" : "DataRequirement, string", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionDatarequirement, addSort, setPath"} **/
						, researchelementdefinition.getRdChrctrDfntnDtrqrmntDtRqrmntLmt() /** { "tree" :"ResearchElementDefinition.characteristic.definitionDatarequirement", "datatype" : "DataRequirement, positiveInt", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionDatarequirement, setLimit"} **/
						, researchelementdefinition.getRdChrctrDfntnDtrqrmntDtRqrmntSbjctRfrnce() /** { "tree" :"ResearchElementDefinition.characteristic.definitionDatarequirement", "datatype" : "DataRequirement, Reference", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionDatarequirement, setSubjectReference"} **/
						, researchelementdefinition.getRdChrctrDfntnDtrqrmntDtRqrmntMstSpprt() /** { "tree" :"ResearchElementDefinition.characteristic.definitionDatarequirement", "datatype" : "DataRequirement, string", "cardinality" : "Required", "elementtree" : ["setCharacteristic"] , "methodName" : "setDefinitionDatarequirement, addMustSupport"} **/
						));
Researchelementdefinitionobj.addUsageContext(HapiFHIRHelpers.createUsageContext(researchelementdefinition.getRdChrctrSgCntxtSgCntxtVlCcCcCSstm() /** { "tree" :"ResearchElementDefinition.characteristic.usageContext", "datatype" : "UsageContext, CodeableConcept, Coding, uri", "cardinality" : "Many", "elementtree" : ["setCharacteristic"] , "methodName" : "addUsageContext, addValueCodeableConcept, addCoding, setSystem"} **/
						, researchelementdefinition.getRdChrctrSgCntxtSgCntxtVlCcCcCVrsn() /** { "tree" :"ResearchElementDefinition.characteristic.usageContext", "datatype" : "UsageContext, CodeableConcept, Coding, string", "cardinality" : "Many", "elementtree" : ["setCharacteristic"] , "methodName" : "addUsageContext, addValueCodeableConcept, addCoding, setVersion"} **/
						, researchelementdefinition.getRdChrctrSgCntxtSgCntxtVlCcCcCCde() /** { "tree" :"ResearchElementDefinition.characteristic.usageContext", "datatype" : "UsageContext, CodeableConcept, Coding, code", "cardinality" : "Many", "elementtree" : ["setCharacteristic"] , "methodName" : "addUsageContext, addValueCodeableConcept, addCoding, setCode"} **/
						, researchelementdefinition.getRdChrctrSgCntxtSgCntxtVlCcCcCDsplay() /** { "tree" :"ResearchElementDefinition.characteristic.usageContext", "datatype" : "UsageContext, CodeableConcept, Coding, string", "cardinality" : "Many", "elementtree" : ["setCharacteristic"] , "methodName" : "addUsageContext, addValueCodeableConcept, addCoding, setDisplay"} **/
						, researchelementdefinition.getRdChrctrSgCntxtSgCntxtVlCcCcCSrSlctd() /** { "tree" :"ResearchElementDefinition.characteristic.usageContext", "datatype" : "UsageContext, CodeableConcept, Coding, boolean", "cardinality" : "Many", "elementtree" : ["setCharacteristic"] , "methodName" : "addUsageContext, addValueCodeableConcept, addCoding, setUserSelected"} **/
						, researchelementdefinition.getRdChrctrSgCntxtSgCntxtVlCcCcTxt() /** { "tree" :"ResearchElementDefinition.characteristic.usageContext", "datatype" : "UsageContext, CodeableConcept, string", "cardinality" : "Many", "elementtree" : ["setCharacteristic"] , "methodName" : "addUsageContext, addValueCodeableConcept, setText"} **/
						, researchelementdefinition.getRdChrctrSgCntxtSgCntxtCdCSstm() /** { "tree" :"ResearchElementDefinition.characteristic.usageContext", "datatype" : "UsageContext, Coding, uri", "cardinality" : "Many", "elementtree" : ["setCharacteristic"] , "methodName" : "addUsageContext, addCode, setSystem"} **/
						, researchelementdefinition.getRdChrctrSgCntxtSgCntxtCdCVrsn() /** { "tree" :"ResearchElementDefinition.characteristic.usageContext", "datatype" : "UsageContext, Coding, string", "cardinality" : "Many", "elementtree" : ["setCharacteristic"] , "methodName" : "addUsageContext, addCode, setVersion"} **/
						, researchelementdefinition.getRdChrctrSgCntxtSgCntxtCdCCde() /** { "tree" :"ResearchElementDefinition.characteristic.usageContext", "datatype" : "UsageContext, Coding, code", "cardinality" : "Many", "elementtree" : ["setCharacteristic"] , "methodName" : "addUsageContext, addCode, setCode"} **/
						, researchelementdefinition.getRdChrctrSgCntxtSgCntxtCdCDsplay() /** { "tree" :"ResearchElementDefinition.characteristic.usageContext", "datatype" : "UsageContext, Coding, string", "cardinality" : "Many", "elementtree" : ["setCharacteristic"] , "methodName" : "addUsageContext, addCode, setDisplay"} **/
						, researchelementdefinition.getRdChrctrSgCntxtSgCntxtCdCSrSlctd() /** { "tree" :"ResearchElementDefinition.characteristic.usageContext", "datatype" : "UsageContext, Coding, boolean", "cardinality" : "Many", "elementtree" : ["setCharacteristic"] , "methodName" : "addUsageContext, addCode, setUserSelected"} **/
						, researchelementdefinition.getRdChrctrSgCntxtSgCntxtVlQnttQnttVlue() /** { "tree" :"ResearchElementDefinition.characteristic.usageContext", "datatype" : "UsageContext, Quantity, decimal", "cardinality" : "Many", "elementtree" : ["setCharacteristic"] , "methodName" : "addUsageContext, addValueQuantity, setValue"} **/
						, researchelementdefinition.getRdChrctrSgCntxtSgCntxtVlQnttQnttCmprtr() /** { "tree" :"ResearchElementDefinition.characteristic.usageContext", "datatype" : "UsageContext, Quantity, code", "cardinality" : "Many", "elementtree" : ["setCharacteristic"] , "methodName" : "addUsageContext, addValueQuantity, setComparator"} **/
						, researchelementdefinition.getRdChrctrSgCntxtSgCntxtVlQnttQnttNt() /** { "tree" :"ResearchElementDefinition.characteristic.usageContext", "datatype" : "UsageContext, Quantity, string", "cardinality" : "Many", "elementtree" : ["setCharacteristic"] , "methodName" : "addUsageContext, addValueQuantity, setUnit"} **/
						, researchelementdefinition.getRdChrctrSgCntxtSgCntxtVlQnttQnttSstm() /** { "tree" :"ResearchElementDefinition.characteristic.usageContext", "datatype" : "UsageContext, Quantity, uri", "cardinality" : "Many", "elementtree" : ["setCharacteristic"] , "methodName" : "addUsageContext, addValueQuantity, setSystem"} **/
						, researchelementdefinition.getRdChrctrSgCntxtSgCntxtVlQnttQnttCde() /** { "tree" :"ResearchElementDefinition.characteristic.usageContext", "datatype" : "UsageContext, Quantity, code", "cardinality" : "Many", "elementtree" : ["setCharacteristic"] , "methodName" : "addUsageContext, addValueQuantity, setCode"} **/
						, researchelementdefinition.getRdChrctrSgCntxtSgCntxtVlRngRngLw() /** { "tree" :"ResearchElementDefinition.characteristic.usageContext", "datatype" : "UsageContext, Range, SimpleQuantity", "cardinality" : "Many", "elementtree" : ["setCharacteristic"] , "methodName" : "addUsageContext, addValueRange, setLow"} **/
						, researchelementdefinition.getRdChrctrSgCntxtSgCntxtVlRngRngHgh() /** { "tree" :"ResearchElementDefinition.characteristic.usageContext", "datatype" : "UsageContext, Range, SimpleQuantity", "cardinality" : "Many", "elementtree" : ["setCharacteristic"] , "methodName" : "addUsageContext, addValueRange, setHigh"} **/
						, researchelementdefinition.getRdChrctrSgCntxtSgCntxtVlRfrnce() /** { "tree" :"ResearchElementDefinition.characteristic.usageContext", "datatype" : "UsageContext, Reference", "cardinality" : "Many", "elementtree" : ["setCharacteristic"] , "methodName" : "addUsageContext, addValueReference"} **/
						));
Researchelementdefinitionobj.setExclude(HapiFHIRHelpers.createboolean(researchelementdefinition.getRedChrctrExcludeBoolean() /** { "tree" :"ResearchElementDefinition.characteristic.exclude", "datatype" : "boolean", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setExclude"} **/
						));
Researchelementdefinitionobj.setUnitOfMeasure(HapiFHIRHelpers.createCodeableConcept(researchelementdefinition.getRdChrctrNtfMsrCcCdngCSstm() /** { "tree" :"ResearchElementDefinition.characteristic.unitOfMeasure", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setUnitOfMeasure, addCoding, setSystem"} **/
						, researchelementdefinition.getRdChrctrNtfMsrCcCdngCVrsn() /** { "tree" :"ResearchElementDefinition.characteristic.unitOfMeasure", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setUnitOfMeasure, addCoding, setVersion"} **/
						, researchelementdefinition.getRdChrctrNtfMsrCcCdngCCde() /** { "tree" :"ResearchElementDefinition.characteristic.unitOfMeasure", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setUnitOfMeasure, addCoding, setCode"} **/
						, researchelementdefinition.getRdChrctrNtfMsrCcCdngCDsplay() /** { "tree" :"ResearchElementDefinition.characteristic.unitOfMeasure", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setUnitOfMeasure, addCoding, setDisplay"} **/
						, researchelementdefinition.getRdChrctrNtfMsrCcCdngCSrSlctd() /** { "tree" :"ResearchElementDefinition.characteristic.unitOfMeasure", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setUnitOfMeasure, addCoding, setUserSelected"} **/
						, researchelementdefinition.getRedChrctrUnitOfMeasureCcText() /** { "tree" :"ResearchElementDefinition.characteristic.unitOfMeasure", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setUnitOfMeasure, setText"} **/
						));
Researchelementdefinitionobj.setStudyEffectiveDescription(HapiFHIRHelpers.createstring(researchelementdefinition.getRdChrctrStdffctvDscrptnStrng() /** { "tree" :"ResearchElementDefinition.characteristic.studyEffectiveDescription", "datatype" : "string", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setStudyEffectiveDescription"} **/
						));
Researchelementdefinitionobj.setStudyEffective(HapiFHIRHelpers.createdateTimetype(researchelementdefinition.getRdChrctrStdffctvDttmDtTme() /** { "tree" :"ResearchElementDefinition.characteristic.studyEffectiveDatetime", "datatype" : "dateTime", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setStudyEffectiveDatetime"} **/
						));
Researchelementdefinitionobj.setStudyEffectivePeriod(HapiFHIRHelpers.createPeriod(researchelementdefinition.getRdChrctrStdffctvPrdPrdStrt() /** { "tree" :"ResearchElementDefinition.characteristic.studyEffectivePeriod", "datatype" : "Period, dateTime", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setStudyEffectivePeriod, setStart"} **/
						, researchelementdefinition.getRdChrctrStdffctvPrdPrdNd() /** { "tree" :"ResearchElementDefinition.characteristic.studyEffectivePeriod", "datatype" : "Period, dateTime", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setStudyEffectivePeriod, setEnd"} **/
						));
Researchelementdefinitionobj.setStudyEffectiveDuration(HapiFHIRHelpers.createDuration(researchelementdefinition.getRdChrctrStdffctvDrtnDrtn() /** { "tree" :"ResearchElementDefinition.characteristic.studyEffectiveDuration", "datatype" : "Duration", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setStudyEffectiveDuration"} **/
						));
Researchelementdefinitionobj.setStudyEffectiveTiming(HapiFHIRHelpers.createTiming(researchelementdefinition.getRdChrctrStdffctvTmngTmngCdCcCSstm() /** { "tree" :"ResearchElementDefinition.characteristic.studyEffectiveTiming", "datatype" : "Timing, CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setStudyEffectiveTiming, setCode, addCoding, setSystem"} **/
						, researchelementdefinition.getRdChrctrStdffctvTmngTmngCdCcCVrsn() /** { "tree" :"ResearchElementDefinition.characteristic.studyEffectiveTiming", "datatype" : "Timing, CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setStudyEffectiveTiming, setCode, addCoding, setVersion"} **/
						, researchelementdefinition.getRdChrctrStdffctvTmngTmngCdCcCCde() /** { "tree" :"ResearchElementDefinition.characteristic.studyEffectiveTiming", "datatype" : "Timing, CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setStudyEffectiveTiming, setCode, addCoding, setCode"} **/
						, researchelementdefinition.getRdChrctrStdffctvTmngTmngCdCcCDsplay() /** { "tree" :"ResearchElementDefinition.characteristic.studyEffectiveTiming", "datatype" : "Timing, CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setStudyEffectiveTiming, setCode, addCoding, setDisplay"} **/
						, researchelementdefinition.getRdChrctrStdffctvTmngTmngCdCcCSrSlctd() /** { "tree" :"ResearchElementDefinition.characteristic.studyEffectiveTiming", "datatype" : "Timing, CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setStudyEffectiveTiming, setCode, addCoding, setUserSelected"} **/
						, researchelementdefinition.getRdChrctrStdffctvTmngTmngCdCcTxt() /** { "tree" :"ResearchElementDefinition.characteristic.studyEffectiveTiming", "datatype" : "Timing, CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setStudyEffectiveTiming, setCode, setText"} **/
						, researchelementdefinition.getRdChrctrStdffctvTmngTmngVnt() /** { "tree" :"ResearchElementDefinition.characteristic.studyEffectiveTiming", "datatype" : "Timing, dateTime", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setStudyEffectiveTiming, addEvent"} **/
						, researchelementdefinition.getRdChrctrStdffctvTmngTmngRptDrtnnt() /** { "tree" :"ResearchElementDefinition.characteristic.studyEffectiveTiming", "datatype" : "Timing, Element, code", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setStudyEffectiveTiming, setRepeat, setDurationUnit"} **/
						, researchelementdefinition.getRdChrctrStdffctvTmngTmngRptPrdnt() /** { "tree" :"ResearchElementDefinition.characteristic.studyEffectiveTiming", "datatype" : "Timing, Element, code", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setStudyEffectiveTiming, setRepeat, setPeriodUnit"} **/
						, researchelementdefinition.getRdChrctrStdffctvTmngTmngRptDfWk() /** { "tree" :"ResearchElementDefinition.characteristic.studyEffectiveTiming", "datatype" : "Timing, Element, code", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setStudyEffectiveTiming, setRepeat, addDayOfWeek"} **/
						, researchelementdefinition.getRdChrctrStdffctvTmngTmngRptWhn() /** { "tree" :"ResearchElementDefinition.characteristic.studyEffectiveTiming", "datatype" : "Timing, Element, code", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setStudyEffectiveTiming, setRepeat, addWhen"} **/
						, researchelementdefinition.getRdChrctrStdffctvTmngTmngRptDrtn() /** { "tree" :"ResearchElementDefinition.characteristic.studyEffectiveTiming", "datatype" : "Timing, Element, decimal", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setStudyEffectiveTiming, setRepeat, setDuration"} **/
						, researchelementdefinition.getRdChrctrStdffctvTmngTmngRptDrtnMx() /** { "tree" :"ResearchElementDefinition.characteristic.studyEffectiveTiming", "datatype" : "Timing, Element, decimal", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setStudyEffectiveTiming, setRepeat, setDurationMax"} **/
						, researchelementdefinition.getRdChrctrStdffctvTmngTmngRptPrd() /** { "tree" :"ResearchElementDefinition.characteristic.studyEffectiveTiming", "datatype" : "Timing, Element, decimal", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setStudyEffectiveTiming, setRepeat, setPeriod"} **/
						, researchelementdefinition.getRdChrctrStdffctvTmngTmngRptPrdMx() /** { "tree" :"ResearchElementDefinition.characteristic.studyEffectiveTiming", "datatype" : "Timing, Element, decimal", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setStudyEffectiveTiming, setRepeat, setPeriodMax"} **/
						, researchelementdefinition.getRdChrctrStdffctvTmngTmngRptBndsDrtn() /** { "tree" :"ResearchElementDefinition.characteristic.studyEffectiveTiming", "datatype" : "Timing, Element, Duration", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setStudyEffectiveTiming, setRepeat, setBoundsDuration"} **/
						, researchelementdefinition.getRdChrctrStdffctvTmngTmngRptBndsPrd() /** { "tree" :"ResearchElementDefinition.characteristic.studyEffectiveTiming", "datatype" : "Timing, Element, Period", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setStudyEffectiveTiming, setRepeat, setBoundsPeriod"} **/
						, researchelementdefinition.getRdChrctrStdffctvTmngTmngRptCnt() /** { "tree" :"ResearchElementDefinition.characteristic.studyEffectiveTiming", "datatype" : "Timing, Element, positiveInt", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setStudyEffectiveTiming, setRepeat, setCount"} **/
						, researchelementdefinition.getRdChrctrStdffctvTmngTmngRptCntMx() /** { "tree" :"ResearchElementDefinition.characteristic.studyEffectiveTiming", "datatype" : "Timing, Element, positiveInt", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setStudyEffectiveTiming, setRepeat, setCountMax"} **/
						, researchelementdefinition.getRdChrctrStdffctvTmngTmngRptFrqncy() /** { "tree" :"ResearchElementDefinition.characteristic.studyEffectiveTiming", "datatype" : "Timing, Element, positiveInt", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setStudyEffectiveTiming, setRepeat, setFrequency"} **/
						, researchelementdefinition.getRdChrctrStdffctvTmngTmngRptFrqncMx() /** { "tree" :"ResearchElementDefinition.characteristic.studyEffectiveTiming", "datatype" : "Timing, Element, positiveInt", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setStudyEffectiveTiming, setRepeat, setFrequencyMax"} **/
						, researchelementdefinition.getRdChrctrStdffctvTmngTmngRptBndsRnge() /** { "tree" :"ResearchElementDefinition.characteristic.studyEffectiveTiming", "datatype" : "Timing, Element, Range", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setStudyEffectiveTiming, setRepeat, setBoundsRange"} **/
						, researchelementdefinition.getRdChrctrStdffctvTmngTmngRptTmfDay() /** { "tree" :"ResearchElementDefinition.characteristic.studyEffectiveTiming", "datatype" : "Timing, Element, time", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setStudyEffectiveTiming, setRepeat, addTimeOfDay"} **/
						, researchelementdefinition.getRdChrctrStdffctvTmngTmngRptFfst() /** { "tree" :"ResearchElementDefinition.characteristic.studyEffectiveTiming", "datatype" : "Timing, Element, unsignedInt", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setStudyEffectiveTiming, setRepeat, setOffset"} **/
						));
Researchelementdefinitionobj.setStudyEffectiveTimeFromStart(HapiFHIRHelpers.createDuration(researchelementdefinition.getRdChrctrStdffctvTmFrmStrtDrtn() /** { "tree" :"ResearchElementDefinition.characteristic.studyEffectiveTimeFromStart", "datatype" : "Duration", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setStudyEffectiveTimeFromStart"} **/
						));
Researchelementdefinitionobj.setStudyEffectiveGroupMeasure(HapiFHIRHelpers.createcode(researchelementdefinition.getRdChrctrStdffctvGrpMsrCde() /** { "tree" :"ResearchElementDefinition.characteristic.studyEffectiveGroupMeasure", "datatype" : "code", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setStudyEffectiveGroupMeasure"} **/
						));
Researchelementdefinitionobj.setParticipantEffectiveDescription(HapiFHIRHelpers.createstring(researchelementdefinition.getRdChrctrPrtcpntffctvDscrptnStrng() /** { "tree" :"ResearchElementDefinition.characteristic.participantEffectiveDescription", "datatype" : "string", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setParticipantEffectiveDescription"} **/
						));
Researchelementdefinitionobj.setParticipantEffective(HapiFHIRHelpers.createdateTimetype(researchelementdefinition.getRdChrctrPrtcpntffctvDttmDtTme() /** { "tree" :"ResearchElementDefinition.characteristic.participantEffectiveDatetime", "datatype" : "dateTime", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setParticipantEffectiveDatetime"} **/
						));
Researchelementdefinitionobj.setParticipantEffectivePeriod(HapiFHIRHelpers.createPeriod(researchelementdefinition.getRdChrctrPrtcpntffctvPrdPrdStrt() /** { "tree" :"ResearchElementDefinition.characteristic.participantEffectivePeriod", "datatype" : "Period, dateTime", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setParticipantEffectivePeriod, setStart"} **/
						, researchelementdefinition.getRdChrctrPrtcpntffctvPrdPrdNd() /** { "tree" :"ResearchElementDefinition.characteristic.participantEffectivePeriod", "datatype" : "Period, dateTime", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setParticipantEffectivePeriod, setEnd"} **/
						));
Researchelementdefinitionobj.setParticipantEffectiveDuration(HapiFHIRHelpers.createDuration(researchelementdefinition.getRdChrctrPrtcpntffctvDrtnDrtn() /** { "tree" :"ResearchElementDefinition.characteristic.participantEffectiveDuration", "datatype" : "Duration", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setParticipantEffectiveDuration"} **/
						));
Researchelementdefinitionobj.setParticipantEffectiveTiming(HapiFHIRHelpers.createTiming(researchelementdefinition.getRdChrctrPrtcpntffctvTmngTmngCdCcCSstm() /** { "tree" :"ResearchElementDefinition.characteristic.participantEffectiveTiming", "datatype" : "Timing, CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setParticipantEffectiveTiming, setCode, addCoding, setSystem"} **/
						, researchelementdefinition.getRdChrctrPrtcpntffctvTmngTmngCdCcCVrsn() /** { "tree" :"ResearchElementDefinition.characteristic.participantEffectiveTiming", "datatype" : "Timing, CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setParticipantEffectiveTiming, setCode, addCoding, setVersion"} **/
						, researchelementdefinition.getRdChrctrPrtcpntffctvTmngTmngCdCcCCde() /** { "tree" :"ResearchElementDefinition.characteristic.participantEffectiveTiming", "datatype" : "Timing, CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setParticipantEffectiveTiming, setCode, addCoding, setCode"} **/
						, researchelementdefinition.getRdChrctrPrtcpntffctvTmngTmngCdCcCDsplay() /** { "tree" :"ResearchElementDefinition.characteristic.participantEffectiveTiming", "datatype" : "Timing, CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setParticipantEffectiveTiming, setCode, addCoding, setDisplay"} **/
						, researchelementdefinition.getRdChrctrPrtcpntffctvTmngTmngCdCcCSrSlctd() /** { "tree" :"ResearchElementDefinition.characteristic.participantEffectiveTiming", "datatype" : "Timing, CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setParticipantEffectiveTiming, setCode, addCoding, setUserSelected"} **/
						, researchelementdefinition.getRdChrctrPrtcpntffctvTmngTmngCdCcTxt() /** { "tree" :"ResearchElementDefinition.characteristic.participantEffectiveTiming", "datatype" : "Timing, CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setParticipantEffectiveTiming, setCode, setText"} **/
						, researchelementdefinition.getRdChrctrPrtcpntffctvTmngTmngVnt() /** { "tree" :"ResearchElementDefinition.characteristic.participantEffectiveTiming", "datatype" : "Timing, dateTime", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setParticipantEffectiveTiming, addEvent"} **/
						, researchelementdefinition.getRdChrctrPrtcpntffctvTmngTmngRptDrtnnt() /** { "tree" :"ResearchElementDefinition.characteristic.participantEffectiveTiming", "datatype" : "Timing, Element, code", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setParticipantEffectiveTiming, setRepeat, setDurationUnit"} **/
						, researchelementdefinition.getRdChrctrPrtcpntffctvTmngTmngRptPrdnt() /** { "tree" :"ResearchElementDefinition.characteristic.participantEffectiveTiming", "datatype" : "Timing, Element, code", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setParticipantEffectiveTiming, setRepeat, setPeriodUnit"} **/
						, researchelementdefinition.getRdChrctrPrtcpntffctvTmngTmngRptDfWk() /** { "tree" :"ResearchElementDefinition.characteristic.participantEffectiveTiming", "datatype" : "Timing, Element, code", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setParticipantEffectiveTiming, setRepeat, addDayOfWeek"} **/
						, researchelementdefinition.getRdChrctrPrtcpntffctvTmngTmngRptWhn() /** { "tree" :"ResearchElementDefinition.characteristic.participantEffectiveTiming", "datatype" : "Timing, Element, code", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setParticipantEffectiveTiming, setRepeat, addWhen"} **/
						, researchelementdefinition.getRdChrctrPrtcpntffctvTmngTmngRptDrtn() /** { "tree" :"ResearchElementDefinition.characteristic.participantEffectiveTiming", "datatype" : "Timing, Element, decimal", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setParticipantEffectiveTiming, setRepeat, setDuration"} **/
						, researchelementdefinition.getRdChrctrPrtcpntffctvTmngTmngRptDrtnMx() /** { "tree" :"ResearchElementDefinition.characteristic.participantEffectiveTiming", "datatype" : "Timing, Element, decimal", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setParticipantEffectiveTiming, setRepeat, setDurationMax"} **/
						, researchelementdefinition.getRdChrctrPrtcpntffctvTmngTmngRptPrd() /** { "tree" :"ResearchElementDefinition.characteristic.participantEffectiveTiming", "datatype" : "Timing, Element, decimal", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setParticipantEffectiveTiming, setRepeat, setPeriod"} **/
						, researchelementdefinition.getRdChrctrPrtcpntffctvTmngTmngRptPrdMx() /** { "tree" :"ResearchElementDefinition.characteristic.participantEffectiveTiming", "datatype" : "Timing, Element, decimal", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setParticipantEffectiveTiming, setRepeat, setPeriodMax"} **/
						, researchelementdefinition.getRdChrctrPrtcpntffctvTmngTmngRptBndsDrtn() /** { "tree" :"ResearchElementDefinition.characteristic.participantEffectiveTiming", "datatype" : "Timing, Element, Duration", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setParticipantEffectiveTiming, setRepeat, setBoundsDuration"} **/
						, researchelementdefinition.getRdChrctrPrtcpntffctvTmngTmngRptBndsPrd() /** { "tree" :"ResearchElementDefinition.characteristic.participantEffectiveTiming", "datatype" : "Timing, Element, Period", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setParticipantEffectiveTiming, setRepeat, setBoundsPeriod"} **/
						, researchelementdefinition.getRdChrctrPrtcpntffctvTmngTmngRptCnt() /** { "tree" :"ResearchElementDefinition.characteristic.participantEffectiveTiming", "datatype" : "Timing, Element, positiveInt", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setParticipantEffectiveTiming, setRepeat, setCount"} **/
						, researchelementdefinition.getRdChrctrPrtcpntffctvTmngTmngRptCntMx() /** { "tree" :"ResearchElementDefinition.characteristic.participantEffectiveTiming", "datatype" : "Timing, Element, positiveInt", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setParticipantEffectiveTiming, setRepeat, setCountMax"} **/
						, researchelementdefinition.getRdChrctrPrtcpntffctvTmngTmngRptFrqncy() /** { "tree" :"ResearchElementDefinition.characteristic.participantEffectiveTiming", "datatype" : "Timing, Element, positiveInt", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setParticipantEffectiveTiming, setRepeat, setFrequency"} **/
						, researchelementdefinition.getRdChrctrPrtcpntffctvTmngTmngRptFrqncMx() /** { "tree" :"ResearchElementDefinition.characteristic.participantEffectiveTiming", "datatype" : "Timing, Element, positiveInt", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setParticipantEffectiveTiming, setRepeat, setFrequencyMax"} **/
						, researchelementdefinition.getRdChrctrPrtcpntffctvTmngTmngRptBndsRnge() /** { "tree" :"ResearchElementDefinition.characteristic.participantEffectiveTiming", "datatype" : "Timing, Element, Range", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setParticipantEffectiveTiming, setRepeat, setBoundsRange"} **/
						, researchelementdefinition.getRdChrctrPrtcpntffctvTmngTmngRptTmfDay() /** { "tree" :"ResearchElementDefinition.characteristic.participantEffectiveTiming", "datatype" : "Timing, Element, time", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setParticipantEffectiveTiming, setRepeat, addTimeOfDay"} **/
						, researchelementdefinition.getRdChrctrPrtcpntffctvTmngTmngRptFfst() /** { "tree" :"ResearchElementDefinition.characteristic.participantEffectiveTiming", "datatype" : "Timing, Element, unsignedInt", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setParticipantEffectiveTiming, setRepeat, setOffset"} **/
						));
Researchelementdefinitionobj.setParticipantEffectiveTimeFromStart(HapiFHIRHelpers.createDuration(researchelementdefinition.getRdChrctrPrtcpntffctvTmFrmStrtDrtn() /** { "tree" :"ResearchElementDefinition.characteristic.participantEffectiveTimeFromStart", "datatype" : "Duration", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setParticipantEffectiveTimeFromStart"} **/
						));
Researchelementdefinitionobj.setParticipantEffectiveGroupMeasure(HapiFHIRHelpers.createcode(researchelementdefinition.getRdChrctrPrtcpntffctvGrpMsrCde() /** { "tree" :"ResearchElementDefinition.characteristic.participantEffectiveGroupMeasure", "datatype" : "code", "cardinality" : "ZeroOne", "elementtree" : ["setCharacteristic"] , "methodName" : "setParticipantEffectiveGroupMeasure"} **/
		));
	}
}
