package main.templateoutput.Conversions;
// Generated on Jan 28, 2022, 8:02:40 AM 


import org.hl7.fhir.r4.model.Patient;

/**
 *  object for conversion model class Substancespecification.
 * @see .Substancespecification
 * @author Paul Kovach
 */
import main.java.com.campfhir.service.conversion.HapiFHIRHelpers;

public class SubstancespecificationConversion 
{
	public Patient Substancespecifications(main.templateoutput.Model.Substancespecification substancespecification) 
	{
			Patient  Substancespecificationobj = new Patient(); 

						Substancespecificationobj.setIdentifier(HapiFHIRHelpers.createIdentifier(substancespecification.getSbstncSpcfctnDntfrDntfrSe() /** { "tree" :"SubstanceSpecification.identifier", "datatype" : "Identifier, code", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setIdentifier, setUse"} **/
						, substancespecification.getSbstncSpcfctnDntfrDntfrTpCcCSstm() /** { "tree" :"SubstanceSpecification.identifier", "datatype" : "Identifier, CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setIdentifier, setType, addCoding, setSystem"} **/
						, substancespecification.getSbstncSpcfctnDntfrDntfrTpCcCVrsn() /** { "tree" :"SubstanceSpecification.identifier", "datatype" : "Identifier, CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setIdentifier, setType, addCoding, setVersion"} **/
						, substancespecification.getSbstncSpcfctnDntfrDntfrTpCcCCde() /** { "tree" :"SubstanceSpecification.identifier", "datatype" : "Identifier, CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setIdentifier, setType, addCoding, setCode"} **/
						, substancespecification.getSbstncSpcfctnDntfrDntfrTpCcCDsplay() /** { "tree" :"SubstanceSpecification.identifier", "datatype" : "Identifier, CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setIdentifier, setType, addCoding, setDisplay"} **/
						, substancespecification.getSbstncSpcfctnDntfrDntfrTpCcCSrSlctd() /** { "tree" :"SubstanceSpecification.identifier", "datatype" : "Identifier, CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setIdentifier, setType, addCoding, setUserSelected"} **/
						, substancespecification.getSbstncSpcfctnDntfrDntfrTpCcTxt() /** { "tree" :"SubstanceSpecification.identifier", "datatype" : "Identifier, CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setIdentifier, setType, setText"} **/
						, substancespecification.getSbstncSpcfctnDntfrDntfrPrdPrdStrt() /** { "tree" :"SubstanceSpecification.identifier", "datatype" : "Identifier, Period, dateTime", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setIdentifier, setPeriod, setStart"} **/
						, substancespecification.getSbstncSpcfctnDntfrDntfrPrdPrdNd() /** { "tree" :"SubstanceSpecification.identifier", "datatype" : "Identifier, Period, dateTime", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setIdentifier, setPeriod, setEnd"} **/
						, substancespecification.getSbstncSpcfctnDntfrDntfrSsgnr() /** { "tree" :"SubstanceSpecification.identifier", "datatype" : "Identifier, Reference", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setIdentifier, setAssigner"} **/
						, substancespecification.getSbstncSpcfctnDntfrDntfrVlue() /** { "tree" :"SubstanceSpecification.identifier", "datatype" : "Identifier, string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setIdentifier, setValue"} **/
						, substancespecification.getSbstncSpcfctnDntfrDntfrSstm() /** { "tree" :"SubstanceSpecification.identifier", "datatype" : "Identifier, uri", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setIdentifier, setSystem"} **/
						));
Substancespecificationobj.setType(HapiFHIRHelpers.createCodeableConcept(substancespecification.getSbstncSpcfctnTpCcCdngCSstm() /** { "tree" :"SubstanceSpecification.type", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setType, addCoding, setSystem"} **/
						, substancespecification.getSbstncSpcfctnTpCcCdngCVrsn() /** { "tree" :"SubstanceSpecification.type", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setType, addCoding, setVersion"} **/
						, substancespecification.getSbstncSpcfctnTpCcCdngCCde() /** { "tree" :"SubstanceSpecification.type", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setType, addCoding, setCode"} **/
						, substancespecification.getSbstncSpcfctnTpCcCdngCDsplay() /** { "tree" :"SubstanceSpecification.type", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setType, addCoding, setDisplay"} **/
						, substancespecification.getSbstncSpcfctnTpCcCdngCSrSlctd() /** { "tree" :"SubstanceSpecification.type", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setType, addCoding, setUserSelected"} **/
						, substancespecification.getSbstncSpcfctnTpCcTxt() /** { "tree" :"SubstanceSpecification.type", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setType, setText"} **/
						));
Substancespecificationobj.setStatus(HapiFHIRHelpers.createCodeableConcept(substancespecification.getSbstncSpcfctnSttsCcCdngCSstm() /** { "tree" :"SubstanceSpecification.status", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setStatus, addCoding, setSystem"} **/
						, substancespecification.getSbstncSpcfctnSttsCcCdngCVrsn() /** { "tree" :"SubstanceSpecification.status", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setStatus, addCoding, setVersion"} **/
						, substancespecification.getSbstncSpcfctnSttsCcCdngCCde() /** { "tree" :"SubstanceSpecification.status", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setStatus, addCoding, setCode"} **/
						, substancespecification.getSbstncSpcfctnSttsCcCdngCDsplay() /** { "tree" :"SubstanceSpecification.status", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setStatus, addCoding, setDisplay"} **/
						, substancespecification.getSbstncSpcfctnSttsCcCdngCSrSlctd() /** { "tree" :"SubstanceSpecification.status", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setStatus, addCoding, setUserSelected"} **/
						, substancespecification.getSbstncSpcfctnSttsCcTxt() /** { "tree" :"SubstanceSpecification.status", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setStatus, setText"} **/
						));
Substancespecificationobj.setDomain(HapiFHIRHelpers.createCodeableConcept(substancespecification.getSbstncSpcfctnDmnCcCdngCSstm() /** { "tree" :"SubstanceSpecification.domain", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setDomain, addCoding, setSystem"} **/
						, substancespecification.getSbstncSpcfctnDmnCcCdngCVrsn() /** { "tree" :"SubstanceSpecification.domain", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setDomain, addCoding, setVersion"} **/
						, substancespecification.getSbstncSpcfctnDmnCcCdngCCde() /** { "tree" :"SubstanceSpecification.domain", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setDomain, addCoding, setCode"} **/
						, substancespecification.getSbstncSpcfctnDmnCcCdngCDsplay() /** { "tree" :"SubstanceSpecification.domain", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setDomain, addCoding, setDisplay"} **/
						, substancespecification.getSbstncSpcfctnDmnCcCdngCSrSlctd() /** { "tree" :"SubstanceSpecification.domain", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setDomain, addCoding, setUserSelected"} **/
						, substancespecification.getSbstncSpcfctnDmnCcTxt() /** { "tree" :"SubstanceSpecification.domain", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setDomain, setText"} **/
						));
Substancespecificationobj.setDescription(HapiFHIRHelpers.createstring(substancespecification.getSbstncSpcfctnDscrptnStrng() /** { "tree" :"SubstanceSpecification.description", "datatype" : "string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setDescription"} **/
						));
Substancespecificationobj.addSource(HapiFHIRHelpers.createReference(substancespecification.getSbstncSpcfctnSrcRfrnce() /** { "tree" :"SubstanceSpecification.source", "datatype" : "Reference", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addSource"} **/
						));
Substancespecificationobj.setComment(HapiFHIRHelpers.createstring(substancespecification.getSbstncSpcfctnCmmntStrng() /** { "tree" :"SubstanceSpecification.comment", "datatype" : "string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setComment"} **/
						));
Substancespecificationobj.setRole(HapiFHIRHelpers.createCodeableConcept(substancespecification.getSbstncSpcfctnMtRlCcCdngCSstm() /** { "tree" :"SubstanceSpecification.moiety.role", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : ["addMoiety"] , "methodName" : "setRole, addCoding, setSystem"} **/
						, substancespecification.getSbstncSpcfctnMtRlCcCdngCVrsn() /** { "tree" :"SubstanceSpecification.moiety.role", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addMoiety"] , "methodName" : "setRole, addCoding, setVersion"} **/
						, substancespecification.getSbstncSpcfctnMtRlCcCdngCCde() /** { "tree" :"SubstanceSpecification.moiety.role", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : ["addMoiety"] , "methodName" : "setRole, addCoding, setCode"} **/
						, substancespecification.getSbstncSpcfctnMtRlCcCdngCDsplay() /** { "tree" :"SubstanceSpecification.moiety.role", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addMoiety"] , "methodName" : "setRole, addCoding, setDisplay"} **/
						, substancespecification.getSbstncSpcfctnMtRlCcCdngCSrSlctd() /** { "tree" :"SubstanceSpecification.moiety.role", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : ["addMoiety"] , "methodName" : "setRole, addCoding, setUserSelected"} **/
						, substancespecification.getSbstncSpcfctnMtRlCcTxt() /** { "tree" :"SubstanceSpecification.moiety.role", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : ["addMoiety"] , "methodName" : "setRole, setText"} **/
						));
Substancespecificationobj.setIdentifier(HapiFHIRHelpers.createIdentifier(substancespecification.getSbstncSpcfctnMtDntfrDntfrSe() /** { "tree" :"SubstanceSpecification.moiety.identifier", "datatype" : "Identifier, code", "cardinality" : "ZeroOne", "elementtree" : ["addMoiety"] , "methodName" : "setIdentifier, setUse"} **/
						, substancespecification.getSbstncSpcfctnMtDntfrDntfrTpCcCSstm() /** { "tree" :"SubstanceSpecification.moiety.identifier", "datatype" : "Identifier, CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : ["addMoiety"] , "methodName" : "setIdentifier, setType, addCoding, setSystem"} **/
						, substancespecification.getSbstncSpcfctnMtDntfrDntfrTpCcCVrsn() /** { "tree" :"SubstanceSpecification.moiety.identifier", "datatype" : "Identifier, CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addMoiety"] , "methodName" : "setIdentifier, setType, addCoding, setVersion"} **/
						, substancespecification.getSbstncSpcfctnMtDntfrDntfrTpCcCCde() /** { "tree" :"SubstanceSpecification.moiety.identifier", "datatype" : "Identifier, CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : ["addMoiety"] , "methodName" : "setIdentifier, setType, addCoding, setCode"} **/
						, substancespecification.getSbstncSpcfctnMtDntfrDntfrTpCcCDsplay() /** { "tree" :"SubstanceSpecification.moiety.identifier", "datatype" : "Identifier, CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addMoiety"] , "methodName" : "setIdentifier, setType, addCoding, setDisplay"} **/
						, substancespecification.getSbstncSpcfctnMtDntfrDntfrTpCcCSrSlctd() /** { "tree" :"SubstanceSpecification.moiety.identifier", "datatype" : "Identifier, CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : ["addMoiety"] , "methodName" : "setIdentifier, setType, addCoding, setUserSelected"} **/
						, substancespecification.getSbstncSpcfctnMtDntfrDntfrTpCcTxt() /** { "tree" :"SubstanceSpecification.moiety.identifier", "datatype" : "Identifier, CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : ["addMoiety"] , "methodName" : "setIdentifier, setType, setText"} **/
						, substancespecification.getSbstncSpcfctnMtDntfrDntfrPrdPrdStrt() /** { "tree" :"SubstanceSpecification.moiety.identifier", "datatype" : "Identifier, Period, dateTime", "cardinality" : "ZeroOne", "elementtree" : ["addMoiety"] , "methodName" : "setIdentifier, setPeriod, setStart"} **/
						, substancespecification.getSbstncSpcfctnMtDntfrDntfrPrdPrdNd() /** { "tree" :"SubstanceSpecification.moiety.identifier", "datatype" : "Identifier, Period, dateTime", "cardinality" : "ZeroOne", "elementtree" : ["addMoiety"] , "methodName" : "setIdentifier, setPeriod, setEnd"} **/
						, substancespecification.getSbstncSpcfctnMtDntfrDntfrSsgnr() /** { "tree" :"SubstanceSpecification.moiety.identifier", "datatype" : "Identifier, Reference", "cardinality" : "ZeroOne", "elementtree" : ["addMoiety"] , "methodName" : "setIdentifier, setAssigner"} **/
						, substancespecification.getSbstncSpcfctnMtDntfrDntfrVlue() /** { "tree" :"SubstanceSpecification.moiety.identifier", "datatype" : "Identifier, string", "cardinality" : "ZeroOne", "elementtree" : ["addMoiety"] , "methodName" : "setIdentifier, setValue"} **/
						, substancespecification.getSbstncSpcfctnMtDntfrDntfrSstm() /** { "tree" :"SubstanceSpecification.moiety.identifier", "datatype" : "Identifier, uri", "cardinality" : "ZeroOne", "elementtree" : ["addMoiety"] , "methodName" : "setIdentifier, setSystem"} **/
						));
Substancespecificationobj.setName(HapiFHIRHelpers.createstring(substancespecification.getSbstncSpcfctnMtNmStrng() /** { "tree" :"SubstanceSpecification.moiety.name", "datatype" : "string", "cardinality" : "ZeroOne", "elementtree" : ["addMoiety"] , "methodName" : "setName"} **/
						));
Substancespecificationobj.setStereochemistry(HapiFHIRHelpers.createCodeableConcept(substancespecification.getSbstncSpcfctnMtStrchmstrCcCdngCSstm() /** { "tree" :"SubstanceSpecification.moiety.stereochemistry", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : ["addMoiety"] , "methodName" : "setStereochemistry, addCoding, setSystem"} **/
						, substancespecification.getSbstncSpcfctnMtStrchmstrCcCdngCVrsn() /** { "tree" :"SubstanceSpecification.moiety.stereochemistry", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addMoiety"] , "methodName" : "setStereochemistry, addCoding, setVersion"} **/
						, substancespecification.getSbstncSpcfctnMtStrchmstrCcCdngCCde() /** { "tree" :"SubstanceSpecification.moiety.stereochemistry", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : ["addMoiety"] , "methodName" : "setStereochemistry, addCoding, setCode"} **/
						, substancespecification.getSbstncSpcfctnMtStrchmstrCcCdngCDsplay() /** { "tree" :"SubstanceSpecification.moiety.stereochemistry", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addMoiety"] , "methodName" : "setStereochemistry, addCoding, setDisplay"} **/
						, substancespecification.getSbstncSpcfctnMtStrchmstrCcCdngCSrSlctd() /** { "tree" :"SubstanceSpecification.moiety.stereochemistry", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : ["addMoiety"] , "methodName" : "setStereochemistry, addCoding, setUserSelected"} **/
						, substancespecification.getSbstncSpcfctnMtStrchmstrCcTxt() /** { "tree" :"SubstanceSpecification.moiety.stereochemistry", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : ["addMoiety"] , "methodName" : "setStereochemistry, setText"} **/
						));
Substancespecificationobj.setOpticalActivity(HapiFHIRHelpers.createCodeableConcept(substancespecification.getSbstncSpcfctnMtPtclctvtCcCdngCSstm() /** { "tree" :"SubstanceSpecification.moiety.opticalActivity", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : ["addMoiety"] , "methodName" : "setOpticalActivity, addCoding, setSystem"} **/
						, substancespecification.getSbstncSpcfctnMtPtclctvtCcCdngCVrsn() /** { "tree" :"SubstanceSpecification.moiety.opticalActivity", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addMoiety"] , "methodName" : "setOpticalActivity, addCoding, setVersion"} **/
						, substancespecification.getSbstncSpcfctnMtPtclctvtCcCdngCCde() /** { "tree" :"SubstanceSpecification.moiety.opticalActivity", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : ["addMoiety"] , "methodName" : "setOpticalActivity, addCoding, setCode"} **/
						, substancespecification.getSbstncSpcfctnMtPtclctvtCcCdngCDsplay() /** { "tree" :"SubstanceSpecification.moiety.opticalActivity", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addMoiety"] , "methodName" : "setOpticalActivity, addCoding, setDisplay"} **/
						, substancespecification.getSbstncSpcfctnMtPtclctvtCcCdngCSrSlctd() /** { "tree" :"SubstanceSpecification.moiety.opticalActivity", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : ["addMoiety"] , "methodName" : "setOpticalActivity, addCoding, setUserSelected"} **/
						, substancespecification.getSbstncSpcfctnMtPtclctvtCcTxt() /** { "tree" :"SubstanceSpecification.moiety.opticalActivity", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : ["addMoiety"] , "methodName" : "setOpticalActivity, setText"} **/
						));
Substancespecificationobj.setMolecularFormula(HapiFHIRHelpers.createstring(substancespecification.getSbstncSpcfctnMtMlclrFrmlStrng() /** { "tree" :"SubstanceSpecification.moiety.molecularFormula", "datatype" : "string", "cardinality" : "ZeroOne", "elementtree" : ["addMoiety"] , "methodName" : "setMolecularFormula"} **/
						));
Substancespecificationobj.setAmountQuantity(HapiFHIRHelpers.createQuantity(substancespecification.getSbstncSpcfctnMtMntQnttQnttCmprtr() /** { "tree" :"SubstanceSpecification.moiety.amountQuantity", "datatype" : "Quantity, code", "cardinality" : "ZeroOne", "elementtree" : ["addMoiety"] , "methodName" : "setAmountQuantity, setComparator"} **/
						, substancespecification.getSbstncSpcfctnMtMntQnttQnttCde() /** { "tree" :"SubstanceSpecification.moiety.amountQuantity", "datatype" : "Quantity, code", "cardinality" : "ZeroOne", "elementtree" : ["addMoiety"] , "methodName" : "setAmountQuantity, setCode"} **/
						, substancespecification.getSbstncSpcfctnMtMntQnttQnttVlue() /** { "tree" :"SubstanceSpecification.moiety.amountQuantity", "datatype" : "Quantity, decimal", "cardinality" : "ZeroOne", "elementtree" : ["addMoiety"] , "methodName" : "setAmountQuantity, setValue"} **/
						, substancespecification.getSbstncSpcfctnMtMntQnttQnttNt() /** { "tree" :"SubstanceSpecification.moiety.amountQuantity", "datatype" : "Quantity, string", "cardinality" : "ZeroOne", "elementtree" : ["addMoiety"] , "methodName" : "setAmountQuantity, setUnit"} **/
						, substancespecification.getSbstncSpcfctnMtMntQnttQnttSstm() /** { "tree" :"SubstanceSpecification.moiety.amountQuantity", "datatype" : "Quantity, uri", "cardinality" : "ZeroOne", "elementtree" : ["addMoiety"] , "methodName" : "setAmountQuantity, setSystem"} **/
						));
Substancespecificationobj.setAmountString(HapiFHIRHelpers.createstring(substancespecification.getSbstncSpcfctnMtMntStrngStrng() /** { "tree" :"SubstanceSpecification.moiety.amountString", "datatype" : "string", "cardinality" : "ZeroOne", "elementtree" : ["addMoiety"] , "methodName" : "setAmountString"} **/
						));
Substancespecificationobj.setCategory(HapiFHIRHelpers.createCodeableConcept(substancespecification.getSbstncSpcfctnPrprtCtgrCcCdngCSstm() /** { "tree" :"SubstanceSpecification.property.category", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : ["addProperty"] , "methodName" : "setCategory, addCoding, setSystem"} **/
						, substancespecification.getSbstncSpcfctnPrprtCtgrCcCdngCVrsn() /** { "tree" :"SubstanceSpecification.property.category", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addProperty"] , "methodName" : "setCategory, addCoding, setVersion"} **/
						, substancespecification.getSbstncSpcfctnPrprtCtgrCcCdngCCde() /** { "tree" :"SubstanceSpecification.property.category", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : ["addProperty"] , "methodName" : "setCategory, addCoding, setCode"} **/
						, substancespecification.getSbstncSpcfctnPrprtCtgrCcCdngCDsplay() /** { "tree" :"SubstanceSpecification.property.category", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addProperty"] , "methodName" : "setCategory, addCoding, setDisplay"} **/
						, substancespecification.getSbstncSpcfctnPrprtCtgrCcCdngCSrSlctd() /** { "tree" :"SubstanceSpecification.property.category", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : ["addProperty"] , "methodName" : "setCategory, addCoding, setUserSelected"} **/
						, substancespecification.getSbstncSpcfctnPrprtCtgrCcTxt() /** { "tree" :"SubstanceSpecification.property.category", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : ["addProperty"] , "methodName" : "setCategory, setText"} **/
						));
Substancespecificationobj.setCode(HapiFHIRHelpers.createCodeableConcept(substancespecification.getSbstncSpcfctnPrprtCdCcCdngCSstm() /** { "tree" :"SubstanceSpecification.property.code", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : ["addProperty"] , "methodName" : "setCode, addCoding, setSystem"} **/
						, substancespecification.getSbstncSpcfctnPrprtCdCcCdngCVrsn() /** { "tree" :"SubstanceSpecification.property.code", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addProperty"] , "methodName" : "setCode, addCoding, setVersion"} **/
						, substancespecification.getSbstncSpcfctnPrprtCdCcCdngCCde() /** { "tree" :"SubstanceSpecification.property.code", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : ["addProperty"] , "methodName" : "setCode, addCoding, setCode"} **/
						, substancespecification.getSbstncSpcfctnPrprtCdCcCdngCDsplay() /** { "tree" :"SubstanceSpecification.property.code", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addProperty"] , "methodName" : "setCode, addCoding, setDisplay"} **/
						, substancespecification.getSbstncSpcfctnPrprtCdCcCdngCSrSlctd() /** { "tree" :"SubstanceSpecification.property.code", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : ["addProperty"] , "methodName" : "setCode, addCoding, setUserSelected"} **/
						, substancespecification.getSbstncSpcfctnPrprtCdCcTxt() /** { "tree" :"SubstanceSpecification.property.code", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : ["addProperty"] , "methodName" : "setCode, setText"} **/
						));
Substancespecificationobj.setParameters(HapiFHIRHelpers.createstring(substancespecification.getSbstncSpcfctnPrprtPrmtrsStrng() /** { "tree" :"SubstanceSpecification.property.parameters", "datatype" : "string", "cardinality" : "ZeroOne", "elementtree" : ["addProperty"] , "methodName" : "setParameters"} **/
						));
Substancespecificationobj.setDefiningSubstanceReference(substancespecification | substance)(HapiFHIRHelpers.createReference(substancespecification.getSbstncSpcfctnPrprtDfnngSbstncRfrncRfrnce() /** { "tree" :"SubstanceSpecification.property.definingSubstanceReference", "datatype" : "Reference", "cardinality" : "ZeroOne", "elementtree" : ["addProperty"] , "methodName" : "setDefiningSubstanceReference(substancespecification | substance)"} **/
						));
Substancespecificationobj.setDefiningSubstanceCodeableconcept(HapiFHIRHelpers.createCodeableConcept(substancespecification.getSbstncSpcfctnPrprtDfnngSbstncCdblcncptCcCdngCSstm() /** { "tree" :"SubstanceSpecification.property.definingSubstanceCodeableconcept", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : ["addProperty"] , "methodName" : "setDefiningSubstanceCodeableconcept, addCoding, setSystem"} **/
						, substancespecification.getSbstncSpcfctnPrprtDfnngSbstncCdblcncptCcCdngCVrsn() /** { "tree" :"SubstanceSpecification.property.definingSubstanceCodeableconcept", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addProperty"] , "methodName" : "setDefiningSubstanceCodeableconcept, addCoding, setVersion"} **/
						, substancespecification.getSbstncSpcfctnPrprtDfnngSbstncCdblcncptCcCdngCCde() /** { "tree" :"SubstanceSpecification.property.definingSubstanceCodeableconcept", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : ["addProperty"] , "methodName" : "setDefiningSubstanceCodeableconcept, addCoding, setCode"} **/
						, substancespecification.getSbstncSpcfctnPrprtDfnngSbstncCdblcncptCcCdngCDsplay() /** { "tree" :"SubstanceSpecification.property.definingSubstanceCodeableconcept", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addProperty"] , "methodName" : "setDefiningSubstanceCodeableconcept, addCoding, setDisplay"} **/
						, substancespecification.getSbstncSpcfctnPrprtDfnngSbstncCdblcncptCcCdngCSrSlctd() /** { "tree" :"SubstanceSpecification.property.definingSubstanceCodeableconcept", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : ["addProperty"] , "methodName" : "setDefiningSubstanceCodeableconcept, addCoding, setUserSelected"} **/
						, substancespecification.getSbstncSpcfctnPrprtDfnngSbstncCdblcncptCcTxt() /** { "tree" :"SubstanceSpecification.property.definingSubstanceCodeableconcept", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : ["addProperty"] , "methodName" : "setDefiningSubstanceCodeableconcept, setText"} **/
						));
Substancespecificationobj.setAmountQuantity(HapiFHIRHelpers.createQuantity(substancespecification.getSbstncSpcfctnPrprtMntQnttQnttCmprtr() /** { "tree" :"SubstanceSpecification.property.amountQuantity", "datatype" : "Quantity, code", "cardinality" : "ZeroOne", "elementtree" : ["addProperty"] , "methodName" : "setAmountQuantity, setComparator"} **/
						, substancespecification.getSbstncSpcfctnPrprtMntQnttQnttCde() /** { "tree" :"SubstanceSpecification.property.amountQuantity", "datatype" : "Quantity, code", "cardinality" : "ZeroOne", "elementtree" : ["addProperty"] , "methodName" : "setAmountQuantity, setCode"} **/
						, substancespecification.getSbstncSpcfctnPrprtMntQnttQnttVlue() /** { "tree" :"SubstanceSpecification.property.amountQuantity", "datatype" : "Quantity, decimal", "cardinality" : "ZeroOne", "elementtree" : ["addProperty"] , "methodName" : "setAmountQuantity, setValue"} **/
						, substancespecification.getSbstncSpcfctnPrprtMntQnttQnttNt() /** { "tree" :"SubstanceSpecification.property.amountQuantity", "datatype" : "Quantity, string", "cardinality" : "ZeroOne", "elementtree" : ["addProperty"] , "methodName" : "setAmountQuantity, setUnit"} **/
						, substancespecification.getSbstncSpcfctnPrprtMntQnttQnttSstm() /** { "tree" :"SubstanceSpecification.property.amountQuantity", "datatype" : "Quantity, uri", "cardinality" : "ZeroOne", "elementtree" : ["addProperty"] , "methodName" : "setAmountQuantity, setSystem"} **/
						));
Substancespecificationobj.setAmountString(HapiFHIRHelpers.createstring(substancespecification.getSbstncSpcfctnPrprtMntStrngStrng() /** { "tree" :"SubstanceSpecification.property.amountString", "datatype" : "string", "cardinality" : "ZeroOne", "elementtree" : ["addProperty"] , "methodName" : "setAmountString"} **/
						));
Substancespecificationobj.setReferenceInformation(HapiFHIRHelpers.createReference(substancespecification.getSbstncSpcfctnRfrncnfrmtnRfrnce() /** { "tree" :"SubstanceSpecification.referenceInformation", "datatype" : "Reference", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setReferenceInformation"} **/
						));
Substancespecificationobj.setStereochemistry(HapiFHIRHelpers.createCodeableConcept(substancespecification.getSbstncSpcfctnStrctrStrchmstrCcCdngCSstm() /** { "tree" :"SubstanceSpecification.structure.stereochemistry", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : ["setStructure"] , "methodName" : "setStereochemistry, addCoding, setSystem"} **/
						, substancespecification.getSbstncSpcfctnStrctrStrchmstrCcCdngCVrsn() /** { "tree" :"SubstanceSpecification.structure.stereochemistry", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["setStructure"] , "methodName" : "setStereochemistry, addCoding, setVersion"} **/
						, substancespecification.getSbstncSpcfctnStrctrStrchmstrCcCdngCCde() /** { "tree" :"SubstanceSpecification.structure.stereochemistry", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : ["setStructure"] , "methodName" : "setStereochemistry, addCoding, setCode"} **/
						, substancespecification.getSbstncSpcfctnStrctrStrchmstrCcCdngCDsplay() /** { "tree" :"SubstanceSpecification.structure.stereochemistry", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["setStructure"] , "methodName" : "setStereochemistry, addCoding, setDisplay"} **/
						, substancespecification.getSbstncSpcfctnStrctrStrchmstrCcCdngCSrSlctd() /** { "tree" :"SubstanceSpecification.structure.stereochemistry", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : ["setStructure"] , "methodName" : "setStereochemistry, addCoding, setUserSelected"} **/
						, substancespecification.getSbstncSpcfctnStrctrStrchmstrCcTxt() /** { "tree" :"SubstanceSpecification.structure.stereochemistry", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : ["setStructure"] , "methodName" : "setStereochemistry, setText"} **/
						));
Substancespecificationobj.setOpticalActivity(HapiFHIRHelpers.createCodeableConcept(substancespecification.getSbstncSpcfctnStrctrPtclctvtCcCdngCSstm() /** { "tree" :"SubstanceSpecification.structure.opticalActivity", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : ["setStructure"] , "methodName" : "setOpticalActivity, addCoding, setSystem"} **/
						, substancespecification.getSbstncSpcfctnStrctrPtclctvtCcCdngCVrsn() /** { "tree" :"SubstanceSpecification.structure.opticalActivity", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["setStructure"] , "methodName" : "setOpticalActivity, addCoding, setVersion"} **/
						, substancespecification.getSbstncSpcfctnStrctrPtclctvtCcCdngCCde() /** { "tree" :"SubstanceSpecification.structure.opticalActivity", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : ["setStructure"] , "methodName" : "setOpticalActivity, addCoding, setCode"} **/
						, substancespecification.getSbstncSpcfctnStrctrPtclctvtCcCdngCDsplay() /** { "tree" :"SubstanceSpecification.structure.opticalActivity", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["setStructure"] , "methodName" : "setOpticalActivity, addCoding, setDisplay"} **/
						, substancespecification.getSbstncSpcfctnStrctrPtclctvtCcCdngCSrSlctd() /** { "tree" :"SubstanceSpecification.structure.opticalActivity", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : ["setStructure"] , "methodName" : "setOpticalActivity, addCoding, setUserSelected"} **/
						, substancespecification.getSbstncSpcfctnStrctrPtclctvtCcTxt() /** { "tree" :"SubstanceSpecification.structure.opticalActivity", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : ["setStructure"] , "methodName" : "setOpticalActivity, setText"} **/
						));
Substancespecificationobj.setMolecularFormula(HapiFHIRHelpers.createstring(substancespecification.getSbstncSpcfctnStrctrMlclrFrmlStrng() /** { "tree" :"SubstanceSpecification.structure.molecularFormula", "datatype" : "string", "cardinality" : "ZeroOne", "elementtree" : ["setStructure"] , "methodName" : "setMolecularFormula"} **/
						));
Substancespecificationobj.setMolecularFormulaByMoiety(HapiFHIRHelpers.createstring(substancespecification.getSbstncSpcfctnStrctrMlclrFrmlBmtStrng() /** { "tree" :"SubstanceSpecification.structure.molecularFormulaByMoiety", "datatype" : "string", "cardinality" : "ZeroOne", "elementtree" : ["setStructure"] , "methodName" : "setMolecularFormulaByMoiety"} **/
						));
Substancespecificationobj.setIdentifier(HapiFHIRHelpers.createIdentifier(substancespecification.getSbstncSpcfctnStrctrStpDntfrDntfrSe() /** { "tree" :"SubstanceSpecification.structure.isotope.identifier", "datatype" : "Identifier, code", "cardinality" : "ZeroOne", "elementtree" : ["setStructure", "addIsotope"] , "methodName" : "setIdentifier, setUse"} **/
						, substancespecification.getSbstncSpcfctnStrctrStpDntfrDntfrTpCcCSstm() /** { "tree" :"SubstanceSpecification.structure.isotope.identifier", "datatype" : "Identifier, CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : ["setStructure", "addIsotope"] , "methodName" : "setIdentifier, setType, addCoding, setSystem"} **/
						, substancespecification.getSbstncSpcfctnStrctrStpDntfrDntfrTpCcCVrsn() /** { "tree" :"SubstanceSpecification.structure.isotope.identifier", "datatype" : "Identifier, CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["setStructure", "addIsotope"] , "methodName" : "setIdentifier, setType, addCoding, setVersion"} **/
						, substancespecification.getSbstncSpcfctnStrctrStpDntfrDntfrTpCcCCde() /** { "tree" :"SubstanceSpecification.structure.isotope.identifier", "datatype" : "Identifier, CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : ["setStructure", "addIsotope"] , "methodName" : "setIdentifier, setType, addCoding, setCode"} **/
						, substancespecification.getSbstncSpcfctnStrctrStpDntfrDntfrTpCcCDsplay() /** { "tree" :"SubstanceSpecification.structure.isotope.identifier", "datatype" : "Identifier, CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["setStructure", "addIsotope"] , "methodName" : "setIdentifier, setType, addCoding, setDisplay"} **/
						, substancespecification.getSbstncSpcfctnStrctrStpDntfrDntfrTpCcCSrSlctd() /** { "tree" :"SubstanceSpecification.structure.isotope.identifier", "datatype" : "Identifier, CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : ["setStructure", "addIsotope"] , "methodName" : "setIdentifier, setType, addCoding, setUserSelected"} **/
						, substancespecification.getSbstncSpcfctnStrctrStpDntfrDntfrTpCcTxt() /** { "tree" :"SubstanceSpecification.structure.isotope.identifier", "datatype" : "Identifier, CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : ["setStructure", "addIsotope"] , "methodName" : "setIdentifier, setType, setText"} **/
						, substancespecification.getSbstncSpcfctnStrctrStpDntfrDntfrPrdPrdStrt() /** { "tree" :"SubstanceSpecification.structure.isotope.identifier", "datatype" : "Identifier, Period, dateTime", "cardinality" : "ZeroOne", "elementtree" : ["setStructure", "addIsotope"] , "methodName" : "setIdentifier, setPeriod, setStart"} **/
						, substancespecification.getSbstncSpcfctnStrctrStpDntfrDntfrPrdPrdNd() /** { "tree" :"SubstanceSpecification.structure.isotope.identifier", "datatype" : "Identifier, Period, dateTime", "cardinality" : "ZeroOne", "elementtree" : ["setStructure", "addIsotope"] , "methodName" : "setIdentifier, setPeriod, setEnd"} **/
						, substancespecification.getSbstncSpcfctnStrctrStpDntfrDntfrSsgnr() /** { "tree" :"SubstanceSpecification.structure.isotope.identifier", "datatype" : "Identifier, Reference", "cardinality" : "ZeroOne", "elementtree" : ["setStructure", "addIsotope"] , "methodName" : "setIdentifier, setAssigner"} **/
						, substancespecification.getSbstncSpcfctnStrctrStpDntfrDntfrVlue() /** { "tree" :"SubstanceSpecification.structure.isotope.identifier", "datatype" : "Identifier, string", "cardinality" : "ZeroOne", "elementtree" : ["setStructure", "addIsotope"] , "methodName" : "setIdentifier, setValue"} **/
						, substancespecification.getSbstncSpcfctnStrctrStpDntfrDntfrSstm() /** { "tree" :"SubstanceSpecification.structure.isotope.identifier", "datatype" : "Identifier, uri", "cardinality" : "ZeroOne", "elementtree" : ["setStructure", "addIsotope"] , "methodName" : "setIdentifier, setSystem"} **/
						));
Substancespecificationobj.setName(HapiFHIRHelpers.createCodeableConcept(substancespecification.getSbstncSpcfctnStrctrStpNmCcCdngCSstm() /** { "tree" :"SubstanceSpecification.structure.isotope.name", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : ["setStructure", "addIsotope"] , "methodName" : "setName, addCoding, setSystem"} **/
						, substancespecification.getSbstncSpcfctnStrctrStpNmCcCdngCVrsn() /** { "tree" :"SubstanceSpecification.structure.isotope.name", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["setStructure", "addIsotope"] , "methodName" : "setName, addCoding, setVersion"} **/
						, substancespecification.getSbstncSpcfctnStrctrStpNmCcCdngCCde() /** { "tree" :"SubstanceSpecification.structure.isotope.name", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : ["setStructure", "addIsotope"] , "methodName" : "setName, addCoding, setCode"} **/
						, substancespecification.getSbstncSpcfctnStrctrStpNmCcCdngCDsplay() /** { "tree" :"SubstanceSpecification.structure.isotope.name", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["setStructure", "addIsotope"] , "methodName" : "setName, addCoding, setDisplay"} **/
						, substancespecification.getSbstncSpcfctnStrctrStpNmCcCdngCSrSlctd() /** { "tree" :"SubstanceSpecification.structure.isotope.name", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : ["setStructure", "addIsotope"] , "methodName" : "setName, addCoding, setUserSelected"} **/
						, substancespecification.getSbstncSpcfctnStrctrStpNmCcTxt() /** { "tree" :"SubstanceSpecification.structure.isotope.name", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : ["setStructure", "addIsotope"] , "methodName" : "setName, setText"} **/
						));
Substancespecificationobj.setSubstitution(HapiFHIRHelpers.createCodeableConcept(substancespecification.getSbstncSpcfctnStrctrStpSbstttnCcCdngCSstm() /** { "tree" :"SubstanceSpecification.structure.isotope.substitution", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : ["setStructure", "addIsotope"] , "methodName" : "setSubstitution, addCoding, setSystem"} **/
						, substancespecification.getSbstncSpcfctnStrctrStpSbstttnCcCdngCVrsn() /** { "tree" :"SubstanceSpecification.structure.isotope.substitution", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["setStructure", "addIsotope"] , "methodName" : "setSubstitution, addCoding, setVersion"} **/
						, substancespecification.getSbstncSpcfctnStrctrStpSbstttnCcCdngCCde() /** { "tree" :"SubstanceSpecification.structure.isotope.substitution", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : ["setStructure", "addIsotope"] , "methodName" : "setSubstitution, addCoding, setCode"} **/
						, substancespecification.getSbstncSpcfctnStrctrStpSbstttnCcCdngCDsplay() /** { "tree" :"SubstanceSpecification.structure.isotope.substitution", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["setStructure", "addIsotope"] , "methodName" : "setSubstitution, addCoding, setDisplay"} **/
						, substancespecification.getSbstncSpcfctnStrctrStpSbstttnCcCdngCSrSlctd() /** { "tree" :"SubstanceSpecification.structure.isotope.substitution", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : ["setStructure", "addIsotope"] , "methodName" : "setSubstitution, addCoding, setUserSelected"} **/
						, substancespecification.getSbstncSpcfctnStrctrStpSbstttnCcTxt() /** { "tree" :"SubstanceSpecification.structure.isotope.substitution", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : ["setStructure", "addIsotope"] , "methodName" : "setSubstitution, setText"} **/
						));
Substancespecificationobj.setHalfLife(HapiFHIRHelpers.createQuantity(substancespecification.getSbstncSpcfctnStrctrStpHlfLfQnttCmprtr() /** { "tree" :"SubstanceSpecification.structure.isotope.halfLife", "datatype" : "Quantity, code", "cardinality" : "ZeroOne", "elementtree" : ["setStructure", "addIsotope"] , "methodName" : "setHalfLife, setComparator"} **/
						, substancespecification.getSbstncSpcfctnStrctrStpHlfLfQnttCde() /** { "tree" :"SubstanceSpecification.structure.isotope.halfLife", "datatype" : "Quantity, code", "cardinality" : "ZeroOne", "elementtree" : ["setStructure", "addIsotope"] , "methodName" : "setHalfLife, setCode"} **/
						, substancespecification.getSbstncSpcfctnStrctrStpHlfLfQnttVlue() /** { "tree" :"SubstanceSpecification.structure.isotope.halfLife", "datatype" : "Quantity, decimal", "cardinality" : "ZeroOne", "elementtree" : ["setStructure", "addIsotope"] , "methodName" : "setHalfLife, setValue"} **/
						, substancespecification.getSbstncSpcfctnStrctrStpHlfLfQnttNt() /** { "tree" :"SubstanceSpecification.structure.isotope.halfLife", "datatype" : "Quantity, string", "cardinality" : "ZeroOne", "elementtree" : ["setStructure", "addIsotope"] , "methodName" : "setHalfLife, setUnit"} **/
						, substancespecification.getSbstncSpcfctnStrctrStpHlfLfQnttSstm() /** { "tree" :"SubstanceSpecification.structure.isotope.halfLife", "datatype" : "Quantity, uri", "cardinality" : "ZeroOne", "elementtree" : ["setStructure", "addIsotope"] , "methodName" : "setHalfLife, setSystem"} **/
						));
Substancespecificationobj.setMethod(HapiFHIRHelpers.createCodeableConcept(substancespecification.getSbstncSpcfctnStrctrStpMlclrWghtMthdCcCdngCSstm() /** { "tree" :"SubstanceSpecification.structure.isotope.molecularWeight.method", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : ["setStructure", "addIsotope", "setMolecularWeight"] , "methodName" : "setMethod, addCoding, setSystem"} **/
						, substancespecification.getSbstncSpcfctnStrctrStpMlclrWghtMthdCcCdngCVrsn() /** { "tree" :"SubstanceSpecification.structure.isotope.molecularWeight.method", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["setStructure", "addIsotope", "setMolecularWeight"] , "methodName" : "setMethod, addCoding, setVersion"} **/
						, substancespecification.getSbstncSpcfctnStrctrStpMlclrWghtMthdCcCdngCCde() /** { "tree" :"SubstanceSpecification.structure.isotope.molecularWeight.method", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : ["setStructure", "addIsotope", "setMolecularWeight"] , "methodName" : "setMethod, addCoding, setCode"} **/
						, substancespecification.getSbstncSpcfctnStrctrStpMlclrWghtMthdCcCdngCDsplay() /** { "tree" :"SubstanceSpecification.structure.isotope.molecularWeight.method", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["setStructure", "addIsotope", "setMolecularWeight"] , "methodName" : "setMethod, addCoding, setDisplay"} **/
						, substancespecification.getSbstncSpcfctnStrctrStpMlclrWghtMthdCcCdngCSrSlctd() /** { "tree" :"SubstanceSpecification.structure.isotope.molecularWeight.method", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : ["setStructure", "addIsotope", "setMolecularWeight"] , "methodName" : "setMethod, addCoding, setUserSelected"} **/
						, substancespecification.getSbstncSpcfctnStrctrStpMlclrWghtMthdCcTxt() /** { "tree" :"SubstanceSpecification.structure.isotope.molecularWeight.method", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : ["setStructure", "addIsotope", "setMolecularWeight"] , "methodName" : "setMethod, setText"} **/
						));
Substancespecificationobj.setType(HapiFHIRHelpers.createCodeableConcept(substancespecification.getSbstncSpcfctnStrctrStpMlclrWghtTpCcCdngCSstm() /** { "tree" :"SubstanceSpecification.structure.isotope.molecularWeight.type", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : ["setStructure", "addIsotope", "setMolecularWeight"] , "methodName" : "setType, addCoding, setSystem"} **/
						, substancespecification.getSbstncSpcfctnStrctrStpMlclrWghtTpCcCdngCVrsn() /** { "tree" :"SubstanceSpecification.structure.isotope.molecularWeight.type", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["setStructure", "addIsotope", "setMolecularWeight"] , "methodName" : "setType, addCoding, setVersion"} **/
						, substancespecification.getSbstncSpcfctnStrctrStpMlclrWghtTpCcCdngCCde() /** { "tree" :"SubstanceSpecification.structure.isotope.molecularWeight.type", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : ["setStructure", "addIsotope", "setMolecularWeight"] , "methodName" : "setType, addCoding, setCode"} **/
						, substancespecification.getSbstncSpcfctnStrctrStpMlclrWghtTpCcCdngCDsplay() /** { "tree" :"SubstanceSpecification.structure.isotope.molecularWeight.type", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["setStructure", "addIsotope", "setMolecularWeight"] , "methodName" : "setType, addCoding, setDisplay"} **/
						, substancespecification.getSbstncSpcfctnStrctrStpMlclrWghtTpCcCdngCSrSlctd() /** { "tree" :"SubstanceSpecification.structure.isotope.molecularWeight.type", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : ["setStructure", "addIsotope", "setMolecularWeight"] , "methodName" : "setType, addCoding, setUserSelected"} **/
						, substancespecification.getSbstncSpcfctnStrctrStpMlclrWghtTpCcTxt() /** { "tree" :"SubstanceSpecification.structure.isotope.molecularWeight.type", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : ["setStructure", "addIsotope", "setMolecularWeight"] , "methodName" : "setType, setText"} **/
						));
Substancespecificationobj.setAmount(HapiFHIRHelpers.createQuantity(substancespecification.getSbstncSpcfctnStrctrStpMlclrWghtMntQnttCmprtr() /** { "tree" :"SubstanceSpecification.structure.isotope.molecularWeight.amount", "datatype" : "Quantity, code", "cardinality" : "ZeroOne", "elementtree" : ["setStructure", "addIsotope", "setMolecularWeight"] , "methodName" : "setAmount, setComparator"} **/
						, substancespecification.getSbstncSpcfctnStrctrStpMlclrWghtMntQnttCde() /** { "tree" :"SubstanceSpecification.structure.isotope.molecularWeight.amount", "datatype" : "Quantity, code", "cardinality" : "ZeroOne", "elementtree" : ["setStructure", "addIsotope", "setMolecularWeight"] , "methodName" : "setAmount, setCode"} **/
						, substancespecification.getSbstncSpcfctnStrctrStpMlclrWghtMntQnttVlue() /** { "tree" :"SubstanceSpecification.structure.isotope.molecularWeight.amount", "datatype" : "Quantity, decimal", "cardinality" : "ZeroOne", "elementtree" : ["setStructure", "addIsotope", "setMolecularWeight"] , "methodName" : "setAmount, setValue"} **/
						, substancespecification.getSbstncSpcfctnStrctrStpMlclrWghtMntQnttNt() /** { "tree" :"SubstanceSpecification.structure.isotope.molecularWeight.amount", "datatype" : "Quantity, string", "cardinality" : "ZeroOne", "elementtree" : ["setStructure", "addIsotope", "setMolecularWeight"] , "methodName" : "setAmount, setUnit"} **/
						, substancespecification.getSbstncSpcfctnStrctrStpMlclrWghtMntQnttSstm() /** { "tree" :"SubstanceSpecification.structure.isotope.molecularWeight.amount", "datatype" : "Quantity, uri", "cardinality" : "ZeroOne", "elementtree" : ["setStructure", "addIsotope", "setMolecularWeight"] , "methodName" : "setAmount, setSystem"} **/
						));
Substancespecificationobj.setMolecularWeight(HapiFHIRHelpers.createmolecularWeight(substancespecification.getSbstncSpcfctnStrctrMlclrWghtMlclrWght() /** { "tree" :"SubstanceSpecification.structure.molecularWeight", "datatype" : "molecularWeight", "cardinality" : "ZeroOne", "elementtree" : ["setStructure", "addIsotope", "setMolecularWeight"] , "methodName" : "setMolecularWeight"} **/
						));
Substancespecificationobj.addSource(HapiFHIRHelpers.createReference(substancespecification.getSbstncSpcfctnStrctrSrcRfrnce() /** { "tree" :"SubstanceSpecification.structure.source", "datatype" : "Reference", "cardinality" : "Many", "elementtree" : ["setStructure", "addIsotope", "setMolecularWeight"] , "methodName" : "addSource"} **/
						));
Substancespecificationobj.setType(HapiFHIRHelpers.createCodeableConcept(substancespecification.getSbstncSpcfctnStrctrRprsnttnTpCcCdngCSstm() /** { "tree" :"SubstanceSpecification.structure.representation.type", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : ["setStructure", "addIsotope", "setMolecularWeight", "addRepresentation"] , "methodName" : "setType, addCoding, setSystem"} **/
						, substancespecification.getSbstncSpcfctnStrctrRprsnttnTpCcCdngCVrsn() /** { "tree" :"SubstanceSpecification.structure.representation.type", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["setStructure", "addIsotope", "setMolecularWeight", "addRepresentation"] , "methodName" : "setType, addCoding, setVersion"} **/
						, substancespecification.getSbstncSpcfctnStrctrRprsnttnTpCcCdngCCde() /** { "tree" :"SubstanceSpecification.structure.representation.type", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : ["setStructure", "addIsotope", "setMolecularWeight", "addRepresentation"] , "methodName" : "setType, addCoding, setCode"} **/
						, substancespecification.getSbstncSpcfctnStrctrRprsnttnTpCcCdngCDsplay() /** { "tree" :"SubstanceSpecification.structure.representation.type", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["setStructure", "addIsotope", "setMolecularWeight", "addRepresentation"] , "methodName" : "setType, addCoding, setDisplay"} **/
						, substancespecification.getSbstncSpcfctnStrctrRprsnttnTpCcCdngCSrSlctd() /** { "tree" :"SubstanceSpecification.structure.representation.type", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : ["setStructure", "addIsotope", "setMolecularWeight", "addRepresentation"] , "methodName" : "setType, addCoding, setUserSelected"} **/
						, substancespecification.getSbstncSpcfctnStrctrRprsnttnTpCcTxt() /** { "tree" :"SubstanceSpecification.structure.representation.type", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : ["setStructure", "addIsotope", "setMolecularWeight", "addRepresentation"] , "methodName" : "setType, setText"} **/
						));
Substancespecificationobj.setRepresentation(HapiFHIRHelpers.createstring(substancespecification.getSbstncSpcfctnStrctrRprsnttnRprsnttnStrng() /** { "tree" :"SubstanceSpecification.structure.representation.representation", "datatype" : "string", "cardinality" : "ZeroOne", "elementtree" : ["setStructure", "addIsotope", "setMolecularWeight", "addRepresentation"] , "methodName" : "setRepresentation"} **/
						));
Substancespecificationobj.setAttachment(HapiFHIRHelpers.createAttachment(substancespecification.getSbstncSpcfctnStrctrRprsnttnTmntTtchmntDta() /** { "tree" :"SubstanceSpecification.structure.representation.attachment", "datatype" : "Attachment, base64Binary", "cardinality" : "ZeroOne", "elementtree" : ["setStructure", "addIsotope", "setMolecularWeight", "addRepresentation"] , "methodName" : "setAttachment, setData"} **/
						, substancespecification.getSbstncSpcfctnStrctrRprsnttnTmntTtchmntHsh() /** { "tree" :"SubstanceSpecification.structure.representation.attachment", "datatype" : "Attachment, base64Binary", "cardinality" : "ZeroOne", "elementtree" : ["setStructure", "addIsotope", "setMolecularWeight", "addRepresentation"] , "methodName" : "setAttachment, setHash"} **/
						, substancespecification.getSbstncSpcfctnStrctrRprsnttnTmntTtchmntCntntTpe() /** { "tree" :"SubstanceSpecification.structure.representation.attachment", "datatype" : "Attachment, code", "cardinality" : "ZeroOne", "elementtree" : ["setStructure", "addIsotope", "setMolecularWeight", "addRepresentation"] , "methodName" : "setAttachment, setContentType"} **/
						, substancespecification.getSbstncSpcfctnStrctrRprsnttnTmntTtchmntLngge() /** { "tree" :"SubstanceSpecification.structure.representation.attachment", "datatype" : "Attachment, code", "cardinality" : "ZeroOne", "elementtree" : ["setStructure", "addIsotope", "setMolecularWeight", "addRepresentation"] , "methodName" : "setAttachment, setLanguage"} **/
						, substancespecification.getSbstncSpcfctnStrctrRprsnttnTmntTtchmntCrtn() /** { "tree" :"SubstanceSpecification.structure.representation.attachment", "datatype" : "Attachment, dateTime", "cardinality" : "ZeroOne", "elementtree" : ["setStructure", "addIsotope", "setMolecularWeight", "addRepresentation"] , "methodName" : "setAttachment, setCreation"} **/
						, substancespecification.getSbstncSpcfctnStrctrRprsnttnTmntTtchmntTtle() /** { "tree" :"SubstanceSpecification.structure.representation.attachment", "datatype" : "Attachment, string", "cardinality" : "ZeroOne", "elementtree" : ["setStructure", "addIsotope", "setMolecularWeight", "addRepresentation"] , "methodName" : "setAttachment, setTitle"} **/
						, substancespecification.getSbstncSpcfctnStrctrRprsnttnTmntTtchmntSze() /** { "tree" :"SubstanceSpecification.structure.representation.attachment", "datatype" : "Attachment, unsignedInt", "cardinality" : "ZeroOne", "elementtree" : ["setStructure", "addIsotope", "setMolecularWeight", "addRepresentation"] , "methodName" : "setAttachment, setSize"} **/
						, substancespecification.getSbstncSpcfctnStrctrRprsnttnTmntTtchmntRl() /** { "tree" :"SubstanceSpecification.structure.representation.attachment", "datatype" : "Attachment, url", "cardinality" : "ZeroOne", "elementtree" : ["setStructure", "addIsotope", "setMolecularWeight", "addRepresentation"] , "methodName" : "setAttachment, setUrl"} **/
						));
Substancespecificationobj.setCode(HapiFHIRHelpers.createCodeableConcept(substancespecification.getSbstncSpcfctnCdCdCcCdngCSstm() /** { "tree" :"SubstanceSpecification.code.code", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : ["addCode"] , "methodName" : "setCode, addCoding, setSystem"} **/
						, substancespecification.getSbstncSpcfctnCdCdCcCdngCVrsn() /** { "tree" :"SubstanceSpecification.code.code", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addCode"] , "methodName" : "setCode, addCoding, setVersion"} **/
						, substancespecification.getSbstncSpcfctnCdCdCcCdngCCde() /** { "tree" :"SubstanceSpecification.code.code", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : ["addCode"] , "methodName" : "setCode, addCoding, setCode"} **/
						, substancespecification.getSbstncSpcfctnCdCdCcCdngCDsplay() /** { "tree" :"SubstanceSpecification.code.code", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addCode"] , "methodName" : "setCode, addCoding, setDisplay"} **/
						, substancespecification.getSbstncSpcfctnCdCdCcCdngCSrSlctd() /** { "tree" :"SubstanceSpecification.code.code", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : ["addCode"] , "methodName" : "setCode, addCoding, setUserSelected"} **/
						, substancespecification.getSbstncSpcfctnCdCdCcTxt() /** { "tree" :"SubstanceSpecification.code.code", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : ["addCode"] , "methodName" : "setCode, setText"} **/
						));
Substancespecificationobj.setStatus(HapiFHIRHelpers.createCodeableConcept(substancespecification.getSbstncSpcfctnCdSttsCcCdngCSstm() /** { "tree" :"SubstanceSpecification.code.status", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : ["addCode"] , "methodName" : "setStatus, addCoding, setSystem"} **/
						, substancespecification.getSbstncSpcfctnCdSttsCcCdngCVrsn() /** { "tree" :"SubstanceSpecification.code.status", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addCode"] , "methodName" : "setStatus, addCoding, setVersion"} **/
						, substancespecification.getSbstncSpcfctnCdSttsCcCdngCCde() /** { "tree" :"SubstanceSpecification.code.status", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : ["addCode"] , "methodName" : "setStatus, addCoding, setCode"} **/
						, substancespecification.getSbstncSpcfctnCdSttsCcCdngCDsplay() /** { "tree" :"SubstanceSpecification.code.status", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addCode"] , "methodName" : "setStatus, addCoding, setDisplay"} **/
						, substancespecification.getSbstncSpcfctnCdSttsCcCdngCSrSlctd() /** { "tree" :"SubstanceSpecification.code.status", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : ["addCode"] , "methodName" : "setStatus, addCoding, setUserSelected"} **/
						, substancespecification.getSbstncSpcfctnCdSttsCcTxt() /** { "tree" :"SubstanceSpecification.code.status", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : ["addCode"] , "methodName" : "setStatus, setText"} **/
						));
Substancespecificationobj.setStatusDate(HapiFHIRHelpers.createdateTime(substancespecification.getSbstncSpcfctnCdSttsDtDtTme() /** { "tree" :"SubstanceSpecification.code.statusDate", "datatype" : "dateTime", "cardinality" : "ZeroOne", "elementtree" : ["addCode"] , "methodName" : "setStatusDate"} **/
						));
Substancespecificationobj.setComment(HapiFHIRHelpers.createstring(substancespecification.getSbstncSpcfctnCdCmmntStrng() /** { "tree" :"SubstanceSpecification.code.comment", "datatype" : "string", "cardinality" : "ZeroOne", "elementtree" : ["addCode"] , "methodName" : "setComment"} **/
						));
Substancespecificationobj.addSource(HapiFHIRHelpers.createReference(substancespecification.getSbstncSpcfctnCdSrcRfrnce() /** { "tree" :"SubstanceSpecification.code.source", "datatype" : "Reference", "cardinality" : "Many", "elementtree" : ["addCode"] , "methodName" : "addSource"} **/
						));
Substancespecificationobj.setName(HapiFHIRHelpers.createstring(substancespecification.getSbstncSpcfctnNmNmStrng() /** { "tree" :"SubstanceSpecification.name.name", "datatype" : "string", "cardinality" : "Required", "elementtree" : ["addName"] , "methodName" : "setName"} **/
						));
Substancespecificationobj.setType(HapiFHIRHelpers.createCodeableConcept(substancespecification.getSbstncSpcfctnNmTpCcCdngCSstm() /** { "tree" :"SubstanceSpecification.name.type", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : ["addName"] , "methodName" : "setType, addCoding, setSystem"} **/
						, substancespecification.getSbstncSpcfctnNmTpCcCdngCVrsn() /** { "tree" :"SubstanceSpecification.name.type", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addName"] , "methodName" : "setType, addCoding, setVersion"} **/
						, substancespecification.getSbstncSpcfctnNmTpCcCdngCCde() /** { "tree" :"SubstanceSpecification.name.type", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : ["addName"] , "methodName" : "setType, addCoding, setCode"} **/
						, substancespecification.getSbstncSpcfctnNmTpCcCdngCDsplay() /** { "tree" :"SubstanceSpecification.name.type", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addName"] , "methodName" : "setType, addCoding, setDisplay"} **/
						, substancespecification.getSbstncSpcfctnNmTpCcCdngCSrSlctd() /** { "tree" :"SubstanceSpecification.name.type", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : ["addName"] , "methodName" : "setType, addCoding, setUserSelected"} **/
						, substancespecification.getSbstncSpcfctnNmTpCcTxt() /** { "tree" :"SubstanceSpecification.name.type", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : ["addName"] , "methodName" : "setType, setText"} **/
						));
Substancespecificationobj.setStatus(HapiFHIRHelpers.createCodeableConcept(substancespecification.getSbstncSpcfctnNmSttsCcCdngCSstm() /** { "tree" :"SubstanceSpecification.name.status", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : ["addName"] , "methodName" : "setStatus, addCoding, setSystem"} **/
						, substancespecification.getSbstncSpcfctnNmSttsCcCdngCVrsn() /** { "tree" :"SubstanceSpecification.name.status", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addName"] , "methodName" : "setStatus, addCoding, setVersion"} **/
						, substancespecification.getSbstncSpcfctnNmSttsCcCdngCCde() /** { "tree" :"SubstanceSpecification.name.status", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : ["addName"] , "methodName" : "setStatus, addCoding, setCode"} **/
						, substancespecification.getSbstncSpcfctnNmSttsCcCdngCDsplay() /** { "tree" :"SubstanceSpecification.name.status", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addName"] , "methodName" : "setStatus, addCoding, setDisplay"} **/
						, substancespecification.getSbstncSpcfctnNmSttsCcCdngCSrSlctd() /** { "tree" :"SubstanceSpecification.name.status", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : ["addName"] , "methodName" : "setStatus, addCoding, setUserSelected"} **/
						, substancespecification.getSbstncSpcfctnNmSttsCcTxt() /** { "tree" :"SubstanceSpecification.name.status", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : ["addName"] , "methodName" : "setStatus, setText"} **/
						));
Substancespecificationobj.setPreferred(HapiFHIRHelpers.createboolean(substancespecification.getSbstncSpcfctnNmPrfrrdBln() /** { "tree" :"SubstanceSpecification.name.preferred", "datatype" : "boolean", "cardinality" : "ZeroOne", "elementtree" : ["addName"] , "methodName" : "setPreferred"} **/
						));
Substancespecificationobj.addLanguage(HapiFHIRHelpers.createCodeableConcept(substancespecification.getSbstncSpcfctnNmLnggCcCdngCSstm() /** { "tree" :"SubstanceSpecification.name.language", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "Many", "elementtree" : ["addName"] , "methodName" : "addLanguage, addCoding, setSystem"} **/
						, substancespecification.getSbstncSpcfctnNmLnggCcCdngCVrsn() /** { "tree" :"SubstanceSpecification.name.language", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Many", "elementtree" : ["addName"] , "methodName" : "addLanguage, addCoding, setVersion"} **/
						, substancespecification.getSbstncSpcfctnNmLnggCcCdngCCde() /** { "tree" :"SubstanceSpecification.name.language", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "Many", "elementtree" : ["addName"] , "methodName" : "addLanguage, addCoding, setCode"} **/
						, substancespecification.getSbstncSpcfctnNmLnggCcCdngCDsplay() /** { "tree" :"SubstanceSpecification.name.language", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Many", "elementtree" : ["addName"] , "methodName" : "addLanguage, addCoding, setDisplay"} **/
						, substancespecification.getSbstncSpcfctnNmLnggCcCdngCSrSlctd() /** { "tree" :"SubstanceSpecification.name.language", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "Many", "elementtree" : ["addName"] , "methodName" : "addLanguage, addCoding, setUserSelected"} **/
						, substancespecification.getSbstncSpcfctnNmLnggCcTxt() /** { "tree" :"SubstanceSpecification.name.language", "datatype" : "CodeableConcept, string", "cardinality" : "Many", "elementtree" : ["addName"] , "methodName" : "addLanguage, setText"} **/
						));
Substancespecificationobj.addDomain(HapiFHIRHelpers.createCodeableConcept(substancespecification.getSbstncSpcfctnNmDmnCcCdngCSstm() /** { "tree" :"SubstanceSpecification.name.domain", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "Many", "elementtree" : ["addName"] , "methodName" : "addDomain, addCoding, setSystem"} **/
						, substancespecification.getSbstncSpcfctnNmDmnCcCdngCVrsn() /** { "tree" :"SubstanceSpecification.name.domain", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Many", "elementtree" : ["addName"] , "methodName" : "addDomain, addCoding, setVersion"} **/
						, substancespecification.getSbstncSpcfctnNmDmnCcCdngCCde() /** { "tree" :"SubstanceSpecification.name.domain", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "Many", "elementtree" : ["addName"] , "methodName" : "addDomain, addCoding, setCode"} **/
						, substancespecification.getSbstncSpcfctnNmDmnCcCdngCDsplay() /** { "tree" :"SubstanceSpecification.name.domain", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Many", "elementtree" : ["addName"] , "methodName" : "addDomain, addCoding, setDisplay"} **/
						, substancespecification.getSbstncSpcfctnNmDmnCcCdngCSrSlctd() /** { "tree" :"SubstanceSpecification.name.domain", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "Many", "elementtree" : ["addName"] , "methodName" : "addDomain, addCoding, setUserSelected"} **/
						, substancespecification.getSbstncSpcfctnNmDmnCcTxt() /** { "tree" :"SubstanceSpecification.name.domain", "datatype" : "CodeableConcept, string", "cardinality" : "Many", "elementtree" : ["addName"] , "methodName" : "addDomain, setText"} **/
						));
Substancespecificationobj.addJurisdiction(HapiFHIRHelpers.createCodeableConcept(substancespecification.getSbstncSpcfctnNmJrsdctnCcCdngCSstm() /** { "tree" :"SubstanceSpecification.name.jurisdiction", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "Many", "elementtree" : ["addName"] , "methodName" : "addJurisdiction, addCoding, setSystem"} **/
						, substancespecification.getSbstncSpcfctnNmJrsdctnCcCdngCVrsn() /** { "tree" :"SubstanceSpecification.name.jurisdiction", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Many", "elementtree" : ["addName"] , "methodName" : "addJurisdiction, addCoding, setVersion"} **/
						, substancespecification.getSbstncSpcfctnNmJrsdctnCcCdngCCde() /** { "tree" :"SubstanceSpecification.name.jurisdiction", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "Many", "elementtree" : ["addName"] , "methodName" : "addJurisdiction, addCoding, setCode"} **/
						, substancespecification.getSbstncSpcfctnNmJrsdctnCcCdngCDsplay() /** { "tree" :"SubstanceSpecification.name.jurisdiction", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Many", "elementtree" : ["addName"] , "methodName" : "addJurisdiction, addCoding, setDisplay"} **/
						, substancespecification.getSbstncSpcfctnNmJrsdctnCcCdngCSrSlctd() /** { "tree" :"SubstanceSpecification.name.jurisdiction", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "Many", "elementtree" : ["addName"] , "methodName" : "addJurisdiction, addCoding, setUserSelected"} **/
						, substancespecification.getSbstncSpcfctnNmJrsdctnCcTxt() /** { "tree" :"SubstanceSpecification.name.jurisdiction", "datatype" : "CodeableConcept, string", "cardinality" : "Many", "elementtree" : ["addName"] , "methodName" : "addJurisdiction, setText"} **/
						));
Substancespecificationobj.addSynonym(HapiFHIRHelpers.createname(substancespecification.getSbstncSpcfctnNmSnnmNme() /** { "tree" :"SubstanceSpecification.name.synonym", "datatype" : "name", "cardinality" : "Many", "elementtree" : ["addName"] , "methodName" : "addSynonym"} **/
						));
Substancespecificationobj.addTranslation(HapiFHIRHelpers.createname(substancespecification.getSbstncSpcfctnNmTrnsltnNme() /** { "tree" :"SubstanceSpecification.name.translation", "datatype" : "name", "cardinality" : "Many", "elementtree" : ["addName"] , "methodName" : "addTranslation"} **/
						));
Substancespecificationobj.setAuthority(HapiFHIRHelpers.createCodeableConcept(substancespecification.getSbstncSpcfctnNmFfclThrtCcCdngCSstm() /** { "tree" :"SubstanceSpecification.name.official.authority", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : ["addName", "addOfficial"] , "methodName" : "setAuthority, addCoding, setSystem"} **/
						, substancespecification.getSbstncSpcfctnNmFfclThrtCcCdngCVrsn() /** { "tree" :"SubstanceSpecification.name.official.authority", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addName", "addOfficial"] , "methodName" : "setAuthority, addCoding, setVersion"} **/
						, substancespecification.getSbstncSpcfctnNmFfclThrtCcCdngCCde() /** { "tree" :"SubstanceSpecification.name.official.authority", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : ["addName", "addOfficial"] , "methodName" : "setAuthority, addCoding, setCode"} **/
						, substancespecification.getSbstncSpcfctnNmFfclThrtCcCdngCDsplay() /** { "tree" :"SubstanceSpecification.name.official.authority", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addName", "addOfficial"] , "methodName" : "setAuthority, addCoding, setDisplay"} **/
						, substancespecification.getSbstncSpcfctnNmFfclThrtCcCdngCSrSlctd() /** { "tree" :"SubstanceSpecification.name.official.authority", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : ["addName", "addOfficial"] , "methodName" : "setAuthority, addCoding, setUserSelected"} **/
						, substancespecification.getSbstncSpcfctnNmFfclThrtCcTxt() /** { "tree" :"SubstanceSpecification.name.official.authority", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : ["addName", "addOfficial"] , "methodName" : "setAuthority, setText"} **/
						));
Substancespecificationobj.setStatus(HapiFHIRHelpers.createCodeableConcept(substancespecification.getSbstncSpcfctnNmFfclSttsCcCdngCSstm() /** { "tree" :"SubstanceSpecification.name.official.status", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : ["addName", "addOfficial"] , "methodName" : "setStatus, addCoding, setSystem"} **/
						, substancespecification.getSbstncSpcfctnNmFfclSttsCcCdngCVrsn() /** { "tree" :"SubstanceSpecification.name.official.status", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addName", "addOfficial"] , "methodName" : "setStatus, addCoding, setVersion"} **/
						, substancespecification.getSbstncSpcfctnNmFfclSttsCcCdngCCde() /** { "tree" :"SubstanceSpecification.name.official.status", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : ["addName", "addOfficial"] , "methodName" : "setStatus, addCoding, setCode"} **/
						, substancespecification.getSbstncSpcfctnNmFfclSttsCcCdngCDsplay() /** { "tree" :"SubstanceSpecification.name.official.status", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addName", "addOfficial"] , "methodName" : "setStatus, addCoding, setDisplay"} **/
						, substancespecification.getSbstncSpcfctnNmFfclSttsCcCdngCSrSlctd() /** { "tree" :"SubstanceSpecification.name.official.status", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : ["addName", "addOfficial"] , "methodName" : "setStatus, addCoding, setUserSelected"} **/
						, substancespecification.getSbstncSpcfctnNmFfclSttsCcTxt() /** { "tree" :"SubstanceSpecification.name.official.status", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : ["addName", "addOfficial"] , "methodName" : "setStatus, setText"} **/
						));
Substancespecificationobj.setDate(HapiFHIRHelpers.createdateTime(substancespecification.getSbstncSpcfctnNmFfclDtDtTme() /** { "tree" :"SubstanceSpecification.name.official.date", "datatype" : "dateTime", "cardinality" : "ZeroOne", "elementtree" : ["addName", "addOfficial"] , "methodName" : "setDate"} **/
						));
Substancespecificationobj.addSource(HapiFHIRHelpers.createReference(substancespecification.getSbstncSpcfctnNmSrcRfrnce() /** { "tree" :"SubstanceSpecification.name.source", "datatype" : "Reference", "cardinality" : "Many", "elementtree" : ["addName", "addOfficial"] , "methodName" : "addSource"} **/
						));
Substancespecificationobj.addMolecularWeight(HapiFHIRHelpers.createmolecularWeight(substancespecification.getSbstncSpcfctnMlclrWghtMlclrWght() /** { "tree" :"SubstanceSpecification.molecularWeight", "datatype" : "molecularWeight", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addMolecularWeight"} **/
						));
Substancespecificationobj.setSubstanceReference(substancespecification)(HapiFHIRHelpers.createReference(substancespecification.getSbstncSpcfctnRltnshpSbstncRfrncRfrnce() /** { "tree" :"SubstanceSpecification.relationship.substanceReference", "datatype" : "Reference", "cardinality" : "ZeroOne", "elementtree" : ["addRelationship"] , "methodName" : "setSubstanceReference(substancespecification)"} **/
						));
Substancespecificationobj.setSubstanceCodeableconcept(HapiFHIRHelpers.createCodeableConcept(substancespecification.getSbstncSpcfctnRltnshpSbstncCdblcncptCcCdngCSstm() /** { "tree" :"SubstanceSpecification.relationship.substanceCodeableconcept", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : ["addRelationship"] , "methodName" : "setSubstanceCodeableconcept, addCoding, setSystem"} **/
						, substancespecification.getSbstncSpcfctnRltnshpSbstncCdblcncptCcCdngCVrsn() /** { "tree" :"SubstanceSpecification.relationship.substanceCodeableconcept", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addRelationship"] , "methodName" : "setSubstanceCodeableconcept, addCoding, setVersion"} **/
						, substancespecification.getSbstncSpcfctnRltnshpSbstncCdblcncptCcCdngCCde() /** { "tree" :"SubstanceSpecification.relationship.substanceCodeableconcept", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : ["addRelationship"] , "methodName" : "setSubstanceCodeableconcept, addCoding, setCode"} **/
						, substancespecification.getSbstncSpcfctnRltnshpSbstncCdblcncptCcCdngCDsplay() /** { "tree" :"SubstanceSpecification.relationship.substanceCodeableconcept", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addRelationship"] , "methodName" : "setSubstanceCodeableconcept, addCoding, setDisplay"} **/
						, substancespecification.getSbstncSpcfctnRltnshpSbstncCdblcncptCcCdngCSrSlctd() /** { "tree" :"SubstanceSpecification.relationship.substanceCodeableconcept", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : ["addRelationship"] , "methodName" : "setSubstanceCodeableconcept, addCoding, setUserSelected"} **/
						, substancespecification.getSbstncSpcfctnRltnshpSbstncCdblcncptCcTxt() /** { "tree" :"SubstanceSpecification.relationship.substanceCodeableconcept", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : ["addRelationship"] , "methodName" : "setSubstanceCodeableconcept, setText"} **/
						));
Substancespecificationobj.setRelationship(HapiFHIRHelpers.createCodeableConcept(substancespecification.getSbstncSpcfctnRltnshpRltnshpCcCdngCSstm() /** { "tree" :"SubstanceSpecification.relationship.relationship", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : ["addRelationship"] , "methodName" : "setRelationship, addCoding, setSystem"} **/
						, substancespecification.getSbstncSpcfctnRltnshpRltnshpCcCdngCVrsn() /** { "tree" :"SubstanceSpecification.relationship.relationship", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addRelationship"] , "methodName" : "setRelationship, addCoding, setVersion"} **/
						, substancespecification.getSbstncSpcfctnRltnshpRltnshpCcCdngCCde() /** { "tree" :"SubstanceSpecification.relationship.relationship", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : ["addRelationship"] , "methodName" : "setRelationship, addCoding, setCode"} **/
						, substancespecification.getSbstncSpcfctnRltnshpRltnshpCcCdngCDsplay() /** { "tree" :"SubstanceSpecification.relationship.relationship", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addRelationship"] , "methodName" : "setRelationship, addCoding, setDisplay"} **/
						, substancespecification.getSbstncSpcfctnRltnshpRltnshpCcCdngCSrSlctd() /** { "tree" :"SubstanceSpecification.relationship.relationship", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : ["addRelationship"] , "methodName" : "setRelationship, addCoding, setUserSelected"} **/
						, substancespecification.getSbstncSpcfctnRltnshpRltnshpCcTxt() /** { "tree" :"SubstanceSpecification.relationship.relationship", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : ["addRelationship"] , "methodName" : "setRelationship, setText"} **/
						));
Substancespecificationobj.setIsDefining(HapiFHIRHelpers.createboolean(substancespecification.getSbstncSpcfctnRltnshpSDfnngBln() /** { "tree" :"SubstanceSpecification.relationship.isDefining", "datatype" : "boolean", "cardinality" : "ZeroOne", "elementtree" : ["addRelationship"] , "methodName" : "setIsDefining"} **/
						));
Substancespecificationobj.setAmountQuantity(HapiFHIRHelpers.createQuantity(substancespecification.getSbstncSpcfctnRltnshpMntQnttQnttCmprtr() /** { "tree" :"SubstanceSpecification.relationship.amountQuantity", "datatype" : "Quantity, code", "cardinality" : "ZeroOne", "elementtree" : ["addRelationship"] , "methodName" : "setAmountQuantity, setComparator"} **/
						, substancespecification.getSbstncSpcfctnRltnshpMntQnttQnttCde() /** { "tree" :"SubstanceSpecification.relationship.amountQuantity", "datatype" : "Quantity, code", "cardinality" : "ZeroOne", "elementtree" : ["addRelationship"] , "methodName" : "setAmountQuantity, setCode"} **/
						, substancespecification.getSbstncSpcfctnRltnshpMntQnttQnttVlue() /** { "tree" :"SubstanceSpecification.relationship.amountQuantity", "datatype" : "Quantity, decimal", "cardinality" : "ZeroOne", "elementtree" : ["addRelationship"] , "methodName" : "setAmountQuantity, setValue"} **/
						, substancespecification.getSbstncSpcfctnRltnshpMntQnttQnttNt() /** { "tree" :"SubstanceSpecification.relationship.amountQuantity", "datatype" : "Quantity, string", "cardinality" : "ZeroOne", "elementtree" : ["addRelationship"] , "methodName" : "setAmountQuantity, setUnit"} **/
						, substancespecification.getSbstncSpcfctnRltnshpMntQnttQnttSstm() /** { "tree" :"SubstanceSpecification.relationship.amountQuantity", "datatype" : "Quantity, uri", "cardinality" : "ZeroOne", "elementtree" : ["addRelationship"] , "methodName" : "setAmountQuantity, setSystem"} **/
						));
Substancespecificationobj.setAmountRange(HapiFHIRHelpers.createRange(substancespecification.getSbstncSpcfctnRltnshpMntRngRngLw() /** { "tree" :"SubstanceSpecification.relationship.amountRange", "datatype" : "Range, SimpleQuantity", "cardinality" : "ZeroOne", "elementtree" : ["addRelationship"] , "methodName" : "setAmountRange, setLow"} **/
						, substancespecification.getSbstncSpcfctnRltnshpMntRngRngHgh() /** { "tree" :"SubstanceSpecification.relationship.amountRange", "datatype" : "Range, SimpleQuantity", "cardinality" : "ZeroOne", "elementtree" : ["addRelationship"] , "methodName" : "setAmountRange, setHigh"} **/
						));
Substancespecificationobj.setAmountRatio(HapiFHIRHelpers.createRatio(substancespecification.getSbstncSpcfctnRltnshpMntRtRtNmrtrQnttVlue() /** { "tree" :"SubstanceSpecification.relationship.amountRatio", "datatype" : "Ratio, Quantity, decimal", "cardinality" : "ZeroOne", "elementtree" : ["addRelationship"] , "methodName" : "setAmountRatio, setNumerator, setValue"} **/
						, substancespecification.getSbstncSpcfctnRltnshpMntRtRtDnmntrQnttVlue() /** { "tree" :"SubstanceSpecification.relationship.amountRatio", "datatype" : "Ratio, Quantity, decimal", "cardinality" : "ZeroOne", "elementtree" : ["addRelationship"] , "methodName" : "setAmountRatio, setDenominator, setValue"} **/
						, substancespecification.getSbstncSpcfctnRltnshpMntRtRtNmrtrQnttCmprtr() /** { "tree" :"SubstanceSpecification.relationship.amountRatio", "datatype" : "Ratio, Quantity, code", "cardinality" : "ZeroOne", "elementtree" : ["addRelationship"] , "methodName" : "setAmountRatio, setNumerator, setComparator"} **/
						, substancespecification.getSbstncSpcfctnRltnshpMntRtRtDnmntrQnttCmprtr() /** { "tree" :"SubstanceSpecification.relationship.amountRatio", "datatype" : "Ratio, Quantity, code", "cardinality" : "ZeroOne", "elementtree" : ["addRelationship"] , "methodName" : "setAmountRatio, setDenominator, setComparator"} **/
						, substancespecification.getSbstncSpcfctnRltnshpMntRtRtNmrtrQnttNt() /** { "tree" :"SubstanceSpecification.relationship.amountRatio", "datatype" : "Ratio, Quantity, string", "cardinality" : "ZeroOne", "elementtree" : ["addRelationship"] , "methodName" : "setAmountRatio, setNumerator, setUnit"} **/
						, substancespecification.getSbstncSpcfctnRltnshpMntRtRtDnmntrQnttNt() /** { "tree" :"SubstanceSpecification.relationship.amountRatio", "datatype" : "Ratio, Quantity, string", "cardinality" : "ZeroOne", "elementtree" : ["addRelationship"] , "methodName" : "setAmountRatio, setDenominator, setUnit"} **/
						, substancespecification.getSbstncSpcfctnRltnshpMntRtRtNmrtrQnttSstm() /** { "tree" :"SubstanceSpecification.relationship.amountRatio", "datatype" : "Ratio, Quantity, uri", "cardinality" : "ZeroOne", "elementtree" : ["addRelationship"] , "methodName" : "setAmountRatio, setNumerator, setSystem"} **/
						, substancespecification.getSbstncSpcfctnRltnshpMntRtRtDnmntrQnttSstm() /** { "tree" :"SubstanceSpecification.relationship.amountRatio", "datatype" : "Ratio, Quantity, uri", "cardinality" : "ZeroOne", "elementtree" : ["addRelationship"] , "methodName" : "setAmountRatio, setDenominator, setSystem"} **/
						, substancespecification.getSbstncSpcfctnRltnshpMntRtRtNmrtrQnttCde() /** { "tree" :"SubstanceSpecification.relationship.amountRatio", "datatype" : "Ratio, Quantity, code", "cardinality" : "ZeroOne", "elementtree" : ["addRelationship"] , "methodName" : "setAmountRatio, setNumerator, setCode"} **/
						, substancespecification.getSbstncSpcfctnRltnshpMntRtRtDnmntrQnttCde() /** { "tree" :"SubstanceSpecification.relationship.amountRatio", "datatype" : "Ratio, Quantity, code", "cardinality" : "ZeroOne", "elementtree" : ["addRelationship"] , "methodName" : "setAmountRatio, setDenominator, setCode"} **/
						));
Substancespecificationobj.setAmountString(HapiFHIRHelpers.createstring(substancespecification.getSbstncSpcfctnRltnshpMntStrngStrng() /** { "tree" :"SubstanceSpecification.relationship.amountString", "datatype" : "string", "cardinality" : "ZeroOne", "elementtree" : ["addRelationship"] , "methodName" : "setAmountString"} **/
						));
Substancespecificationobj.setAmountRatioLowLimit(HapiFHIRHelpers.createRatio(substancespecification.getSbstncSpcfctnRltnshpMntRtLwLmtRtNmrtrQnttVlue() /** { "tree" :"SubstanceSpecification.relationship.amountRatioLowLimit", "datatype" : "Ratio, Quantity, decimal", "cardinality" : "ZeroOne", "elementtree" : ["addRelationship"] , "methodName" : "setAmountRatioLowLimit, setNumerator, setValue"} **/
						, substancespecification.getSbstncSpcfctnRltnshpMntRtLwLmtRtDnmntrQnttVlue() /** { "tree" :"SubstanceSpecification.relationship.amountRatioLowLimit", "datatype" : "Ratio, Quantity, decimal", "cardinality" : "ZeroOne", "elementtree" : ["addRelationship"] , "methodName" : "setAmountRatioLowLimit, setDenominator, setValue"} **/
						, substancespecification.getSbstncSpcfctnRltnshpMntRtLwLmtRtNmrtrQnttCmprtr() /** { "tree" :"SubstanceSpecification.relationship.amountRatioLowLimit", "datatype" : "Ratio, Quantity, code", "cardinality" : "ZeroOne", "elementtree" : ["addRelationship"] , "methodName" : "setAmountRatioLowLimit, setNumerator, setComparator"} **/
						, substancespecification.getSbstncSpcfctnRltnshpMntRtLwLmtRtDnmntrQnttCmprtr() /** { "tree" :"SubstanceSpecification.relationship.amountRatioLowLimit", "datatype" : "Ratio, Quantity, code", "cardinality" : "ZeroOne", "elementtree" : ["addRelationship"] , "methodName" : "setAmountRatioLowLimit, setDenominator, setComparator"} **/
						, substancespecification.getSbstncSpcfctnRltnshpMntRtLwLmtRtNmrtrQnttNt() /** { "tree" :"SubstanceSpecification.relationship.amountRatioLowLimit", "datatype" : "Ratio, Quantity, string", "cardinality" : "ZeroOne", "elementtree" : ["addRelationship"] , "methodName" : "setAmountRatioLowLimit, setNumerator, setUnit"} **/
						, substancespecification.getSbstncSpcfctnRltnshpMntRtLwLmtRtDnmntrQnttNt() /** { "tree" :"SubstanceSpecification.relationship.amountRatioLowLimit", "datatype" : "Ratio, Quantity, string", "cardinality" : "ZeroOne", "elementtree" : ["addRelationship"] , "methodName" : "setAmountRatioLowLimit, setDenominator, setUnit"} **/
						, substancespecification.getSbstncSpcfctnRltnshpMntRtLwLmtRtNmrtrQnttSstm() /** { "tree" :"SubstanceSpecification.relationship.amountRatioLowLimit", "datatype" : "Ratio, Quantity, uri", "cardinality" : "ZeroOne", "elementtree" : ["addRelationship"] , "methodName" : "setAmountRatioLowLimit, setNumerator, setSystem"} **/
						, substancespecification.getSbstncSpcfctnRltnshpMntRtLwLmtRtDnmntrQnttSstm() /** { "tree" :"SubstanceSpecification.relationship.amountRatioLowLimit", "datatype" : "Ratio, Quantity, uri", "cardinality" : "ZeroOne", "elementtree" : ["addRelationship"] , "methodName" : "setAmountRatioLowLimit, setDenominator, setSystem"} **/
						, substancespecification.getSbstncSpcfctnRltnshpMntRtLwLmtRtNmrtrQnttCde() /** { "tree" :"SubstanceSpecification.relationship.amountRatioLowLimit", "datatype" : "Ratio, Quantity, code", "cardinality" : "ZeroOne", "elementtree" : ["addRelationship"] , "methodName" : "setAmountRatioLowLimit, setNumerator, setCode"} **/
						, substancespecification.getSbstncSpcfctnRltnshpMntRtLwLmtRtDnmntrQnttCde() /** { "tree" :"SubstanceSpecification.relationship.amountRatioLowLimit", "datatype" : "Ratio, Quantity, code", "cardinality" : "ZeroOne", "elementtree" : ["addRelationship"] , "methodName" : "setAmountRatioLowLimit, setDenominator, setCode"} **/
						));
Substancespecificationobj.setAmountType(HapiFHIRHelpers.createCodeableConcept(substancespecification.getSbstncSpcfctnRltnshpMntTpCcCdngCSstm() /** { "tree" :"SubstanceSpecification.relationship.amountType", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : ["addRelationship"] , "methodName" : "setAmountType, addCoding, setSystem"} **/
						, substancespecification.getSbstncSpcfctnRltnshpMntTpCcCdngCVrsn() /** { "tree" :"SubstanceSpecification.relationship.amountType", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addRelationship"] , "methodName" : "setAmountType, addCoding, setVersion"} **/
						, substancespecification.getSbstncSpcfctnRltnshpMntTpCcCdngCCde() /** { "tree" :"SubstanceSpecification.relationship.amountType", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : ["addRelationship"] , "methodName" : "setAmountType, addCoding, setCode"} **/
						, substancespecification.getSbstncSpcfctnRltnshpMntTpCcCdngCDsplay() /** { "tree" :"SubstanceSpecification.relationship.amountType", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addRelationship"] , "methodName" : "setAmountType, addCoding, setDisplay"} **/
						, substancespecification.getSbstncSpcfctnRltnshpMntTpCcCdngCSrSlctd() /** { "tree" :"SubstanceSpecification.relationship.amountType", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : ["addRelationship"] , "methodName" : "setAmountType, addCoding, setUserSelected"} **/
						, substancespecification.getSbstncSpcfctnRltnshpMntTpCcTxt() /** { "tree" :"SubstanceSpecification.relationship.amountType", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : ["addRelationship"] , "methodName" : "setAmountType, setText"} **/
						));
Substancespecificationobj.addSource(HapiFHIRHelpers.createReference(substancespecification.getSbstncSpcfctnRltnshpSrcRfrnce() /** { "tree" :"SubstanceSpecification.relationship.source", "datatype" : "Reference", "cardinality" : "Many", "elementtree" : ["addRelationship"] , "methodName" : "addSource"} **/
						));
Substancespecificationobj.setNucleicAcid(HapiFHIRHelpers.createReference(substancespecification.getSbstncSpcfctnNclccdRfrnce() /** { "tree" :"SubstanceSpecification.nucleicAcid", "datatype" : "Reference", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setNucleicAcid"} **/
						));
Substancespecificationobj.setPolymer(HapiFHIRHelpers.createReference(substancespecification.getSbstncSpcfctnPlmrRfrnce() /** { "tree" :"SubstanceSpecification.polymer", "datatype" : "Reference", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setPolymer"} **/
						));
Substancespecificationobj.setProtein(HapiFHIRHelpers.createReference(substancespecification.getSbstncSpcfctnPrtnRfrnce() /** { "tree" :"SubstanceSpecification.protein", "datatype" : "Reference", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setProtein"} **/
						));
Substancespecificationobj.setSourceMaterial(HapiFHIRHelpers.createReference(substancespecification.getSbstncSpcfctnSrcMtrlRfrnce() /** { "tree" :"SubstanceSpecification.sourceMaterial", "datatype" : "Reference", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setSourceMaterial"} **/
		));
	}
}
