package main.templateoutput.Conversions;
// Generated on Jan 28, 2022, 8:02:40 AM 


import org.hl7.fhir.r4.model.Patient;

/**
 *  object for conversion model class Substancereferenceinformation.
 * @see .Substancereferenceinformation
 * @author Paul Kovach
 */
import main.java.com.campfhir.service.conversion.HapiFHIRHelpers;

public class SubstancereferenceinformationConversion 
{
	public Patient Substancereferenceinformations(main.templateoutput.Model.Substancereferenceinformation substancereferenceinformation) 
	{
			Patient  Substancereferenceinformationobj = new Patient(); 

						Substancereferenceinformationobj.setComment(HapiFHIRHelpers.createstring(substancereferenceinformation.getSbstncRfrncnfrmtnCmmntStrng() /** { "tree" :"SubstanceReferenceInformation.comment", "datatype" : "string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setComment"} **/
						));
Substancereferenceinformationobj.setGeneSequenceOrigin(HapiFHIRHelpers.createCodeableConcept(substancereferenceinformation.getSbstncRfrncnfrmtnGnGnSqncrgnCcCdngCSstm() /** { "tree" :"SubstanceReferenceInformation.gene.geneSequenceOrigin", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : ["addGene"] , "methodName" : "setGeneSequenceOrigin, addCoding, setSystem"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnGnGnSqncrgnCcCdngCVrsn() /** { "tree" :"SubstanceReferenceInformation.gene.geneSequenceOrigin", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addGene"] , "methodName" : "setGeneSequenceOrigin, addCoding, setVersion"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnGnGnSqncrgnCcCdngCCde() /** { "tree" :"SubstanceReferenceInformation.gene.geneSequenceOrigin", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : ["addGene"] , "methodName" : "setGeneSequenceOrigin, addCoding, setCode"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnGnGnSqncrgnCcCdngCDsplay() /** { "tree" :"SubstanceReferenceInformation.gene.geneSequenceOrigin", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addGene"] , "methodName" : "setGeneSequenceOrigin, addCoding, setDisplay"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnGnGnSqncrgnCcCdngCSrSlctd() /** { "tree" :"SubstanceReferenceInformation.gene.geneSequenceOrigin", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : ["addGene"] , "methodName" : "setGeneSequenceOrigin, addCoding, setUserSelected"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnGnGnSqncrgnCcTxt() /** { "tree" :"SubstanceReferenceInformation.gene.geneSequenceOrigin", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : ["addGene"] , "methodName" : "setGeneSequenceOrigin, setText"} **/
						));
Substancereferenceinformationobj.setGene(HapiFHIRHelpers.createCodeableConcept(substancereferenceinformation.getSbstncRfrncnfrmtnGnGnCcCdngCSstm() /** { "tree" :"SubstanceReferenceInformation.gene.gene", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : ["addGene"] , "methodName" : "setGene, addCoding, setSystem"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnGnGnCcCdngCVrsn() /** { "tree" :"SubstanceReferenceInformation.gene.gene", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addGene"] , "methodName" : "setGene, addCoding, setVersion"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnGnGnCcCdngCCde() /** { "tree" :"SubstanceReferenceInformation.gene.gene", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : ["addGene"] , "methodName" : "setGene, addCoding, setCode"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnGnGnCcCdngCDsplay() /** { "tree" :"SubstanceReferenceInformation.gene.gene", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addGene"] , "methodName" : "setGene, addCoding, setDisplay"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnGnGnCcCdngCSrSlctd() /** { "tree" :"SubstanceReferenceInformation.gene.gene", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : ["addGene"] , "methodName" : "setGene, addCoding, setUserSelected"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnGnGnCcTxt() /** { "tree" :"SubstanceReferenceInformation.gene.gene", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : ["addGene"] , "methodName" : "setGene, setText"} **/
						));
Substancereferenceinformationobj.addSource(HapiFHIRHelpers.createReference(substancereferenceinformation.getSbstncRfrncnfrmtnGnSrcRfrnce() /** { "tree" :"SubstanceReferenceInformation.gene.source", "datatype" : "Reference", "cardinality" : "Many", "elementtree" : ["addGene"] , "methodName" : "addSource"} **/
						));
Substancereferenceinformationobj.setType(HapiFHIRHelpers.createCodeableConcept(substancereferenceinformation.getSbstncRfrncnfrmtnGnlmntTpCcCdngCSstm() /** { "tree" :"SubstanceReferenceInformation.geneElement.type", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : ["addGeneElement"] , "methodName" : "setType, addCoding, setSystem"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnGnlmntTpCcCdngCVrsn() /** { "tree" :"SubstanceReferenceInformation.geneElement.type", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addGeneElement"] , "methodName" : "setType, addCoding, setVersion"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnGnlmntTpCcCdngCCde() /** { "tree" :"SubstanceReferenceInformation.geneElement.type", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : ["addGeneElement"] , "methodName" : "setType, addCoding, setCode"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnGnlmntTpCcCdngCDsplay() /** { "tree" :"SubstanceReferenceInformation.geneElement.type", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addGeneElement"] , "methodName" : "setType, addCoding, setDisplay"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnGnlmntTpCcCdngCSrSlctd() /** { "tree" :"SubstanceReferenceInformation.geneElement.type", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : ["addGeneElement"] , "methodName" : "setType, addCoding, setUserSelected"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnGnlmntTpCcTxt() /** { "tree" :"SubstanceReferenceInformation.geneElement.type", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : ["addGeneElement"] , "methodName" : "setType, setText"} **/
						));
Substancereferenceinformationobj.setElement(HapiFHIRHelpers.createIdentifier(substancereferenceinformation.getSbstncRfrncnfrmtnGnlmntLmntDntfrSe() /** { "tree" :"SubstanceReferenceInformation.geneElement.element", "datatype" : "Identifier, code", "cardinality" : "ZeroOne", "elementtree" : ["addGeneElement"] , "methodName" : "setElement, setUse"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnGnlmntLmntDntfrTpCcCSstm() /** { "tree" :"SubstanceReferenceInformation.geneElement.element", "datatype" : "Identifier, CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : ["addGeneElement"] , "methodName" : "setElement, setType, addCoding, setSystem"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnGnlmntLmntDntfrTpCcCVrsn() /** { "tree" :"SubstanceReferenceInformation.geneElement.element", "datatype" : "Identifier, CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addGeneElement"] , "methodName" : "setElement, setType, addCoding, setVersion"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnGnlmntLmntDntfrTpCcCCde() /** { "tree" :"SubstanceReferenceInformation.geneElement.element", "datatype" : "Identifier, CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : ["addGeneElement"] , "methodName" : "setElement, setType, addCoding, setCode"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnGnlmntLmntDntfrTpCcCDsplay() /** { "tree" :"SubstanceReferenceInformation.geneElement.element", "datatype" : "Identifier, CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addGeneElement"] , "methodName" : "setElement, setType, addCoding, setDisplay"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnGnlmntLmntDntfrTpCcCSrSlctd() /** { "tree" :"SubstanceReferenceInformation.geneElement.element", "datatype" : "Identifier, CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : ["addGeneElement"] , "methodName" : "setElement, setType, addCoding, setUserSelected"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnGnlmntLmntDntfrTpCcTxt() /** { "tree" :"SubstanceReferenceInformation.geneElement.element", "datatype" : "Identifier, CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : ["addGeneElement"] , "methodName" : "setElement, setType, setText"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnGnlmntLmntDntfrPrdPrdStrt() /** { "tree" :"SubstanceReferenceInformation.geneElement.element", "datatype" : "Identifier, Period, dateTime", "cardinality" : "ZeroOne", "elementtree" : ["addGeneElement"] , "methodName" : "setElement, setPeriod, setStart"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnGnlmntLmntDntfrPrdPrdNd() /** { "tree" :"SubstanceReferenceInformation.geneElement.element", "datatype" : "Identifier, Period, dateTime", "cardinality" : "ZeroOne", "elementtree" : ["addGeneElement"] , "methodName" : "setElement, setPeriod, setEnd"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnGnlmntLmntDntfrSsgnr() /** { "tree" :"SubstanceReferenceInformation.geneElement.element", "datatype" : "Identifier, Reference", "cardinality" : "ZeroOne", "elementtree" : ["addGeneElement"] , "methodName" : "setElement, setAssigner"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnGnlmntLmntDntfrVlue() /** { "tree" :"SubstanceReferenceInformation.geneElement.element", "datatype" : "Identifier, string", "cardinality" : "ZeroOne", "elementtree" : ["addGeneElement"] , "methodName" : "setElement, setValue"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnGnlmntLmntDntfrSstm() /** { "tree" :"SubstanceReferenceInformation.geneElement.element", "datatype" : "Identifier, uri", "cardinality" : "ZeroOne", "elementtree" : ["addGeneElement"] , "methodName" : "setElement, setSystem"} **/
						));
Substancereferenceinformationobj.addSource(HapiFHIRHelpers.createReference(substancereferenceinformation.getSbstncRfrncnfrmtnGnlmntSrcRfrnce() /** { "tree" :"SubstanceReferenceInformation.geneElement.source", "datatype" : "Reference", "cardinality" : "Many", "elementtree" : ["addGeneElement"] , "methodName" : "addSource"} **/
						));
Substancereferenceinformationobj.setDomain(HapiFHIRHelpers.createCodeableConcept(substancereferenceinformation.getSbstncRfrncnfrmtnClssfctnDmnCcCdngCSstm() /** { "tree" :"SubstanceReferenceInformation.classification.domain", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : ["addClassification"] , "methodName" : "setDomain, addCoding, setSystem"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnClssfctnDmnCcCdngCVrsn() /** { "tree" :"SubstanceReferenceInformation.classification.domain", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addClassification"] , "methodName" : "setDomain, addCoding, setVersion"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnClssfctnDmnCcCdngCCde() /** { "tree" :"SubstanceReferenceInformation.classification.domain", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : ["addClassification"] , "methodName" : "setDomain, addCoding, setCode"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnClssfctnDmnCcCdngCDsplay() /** { "tree" :"SubstanceReferenceInformation.classification.domain", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addClassification"] , "methodName" : "setDomain, addCoding, setDisplay"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnClssfctnDmnCcCdngCSrSlctd() /** { "tree" :"SubstanceReferenceInformation.classification.domain", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : ["addClassification"] , "methodName" : "setDomain, addCoding, setUserSelected"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnClssfctnDmnCcTxt() /** { "tree" :"SubstanceReferenceInformation.classification.domain", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : ["addClassification"] , "methodName" : "setDomain, setText"} **/
						));
Substancereferenceinformationobj.setClassification(HapiFHIRHelpers.createCodeableConcept(substancereferenceinformation.getSbstncRfrncnfrmtnClssfctnClssfctnCcCdngCSstm() /** { "tree" :"SubstanceReferenceInformation.classification.classification", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : ["addClassification"] , "methodName" : "setClassification, addCoding, setSystem"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnClssfctnClssfctnCcCdngCVrsn() /** { "tree" :"SubstanceReferenceInformation.classification.classification", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addClassification"] , "methodName" : "setClassification, addCoding, setVersion"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnClssfctnClssfctnCcCdngCCde() /** { "tree" :"SubstanceReferenceInformation.classification.classification", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : ["addClassification"] , "methodName" : "setClassification, addCoding, setCode"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnClssfctnClssfctnCcCdngCDsplay() /** { "tree" :"SubstanceReferenceInformation.classification.classification", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addClassification"] , "methodName" : "setClassification, addCoding, setDisplay"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnClssfctnClssfctnCcCdngCSrSlctd() /** { "tree" :"SubstanceReferenceInformation.classification.classification", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : ["addClassification"] , "methodName" : "setClassification, addCoding, setUserSelected"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnClssfctnClssfctnCcTxt() /** { "tree" :"SubstanceReferenceInformation.classification.classification", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : ["addClassification"] , "methodName" : "setClassification, setText"} **/
						));
Substancereferenceinformationobj.addSubtype(HapiFHIRHelpers.createCodeableConcept(substancereferenceinformation.getSbstncRfrncnfrmtnClssfctnSbtpCcCdngCSstm() /** { "tree" :"SubstanceReferenceInformation.classification.subtype", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "Many", "elementtree" : ["addClassification"] , "methodName" : "addSubtype, addCoding, setSystem"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnClssfctnSbtpCcCdngCVrsn() /** { "tree" :"SubstanceReferenceInformation.classification.subtype", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Many", "elementtree" : ["addClassification"] , "methodName" : "addSubtype, addCoding, setVersion"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnClssfctnSbtpCcCdngCCde() /** { "tree" :"SubstanceReferenceInformation.classification.subtype", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "Many", "elementtree" : ["addClassification"] , "methodName" : "addSubtype, addCoding, setCode"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnClssfctnSbtpCcCdngCDsplay() /** { "tree" :"SubstanceReferenceInformation.classification.subtype", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Many", "elementtree" : ["addClassification"] , "methodName" : "addSubtype, addCoding, setDisplay"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnClssfctnSbtpCcCdngCSrSlctd() /** { "tree" :"SubstanceReferenceInformation.classification.subtype", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "Many", "elementtree" : ["addClassification"] , "methodName" : "addSubtype, addCoding, setUserSelected"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnClssfctnSbtpCcTxt() /** { "tree" :"SubstanceReferenceInformation.classification.subtype", "datatype" : "CodeableConcept, string", "cardinality" : "Many", "elementtree" : ["addClassification"] , "methodName" : "addSubtype, setText"} **/
						));
Substancereferenceinformationobj.addSource(HapiFHIRHelpers.createReference(substancereferenceinformation.getSbstncRfrncnfrmtnClssfctnSrcRfrnce() /** { "tree" :"SubstanceReferenceInformation.classification.source", "datatype" : "Reference", "cardinality" : "Many", "elementtree" : ["addClassification"] , "methodName" : "addSource"} **/
						));
Substancereferenceinformationobj.setTarget(HapiFHIRHelpers.createIdentifier(substancereferenceinformation.getSbstncRfrncnfrmtnTrgtTrgtDntfrSe() /** { "tree" :"SubstanceReferenceInformation.target.target", "datatype" : "Identifier, code", "cardinality" : "ZeroOne", "elementtree" : ["addTarget"] , "methodName" : "setTarget, setUse"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnTrgtTrgtDntfrTpCcCSstm() /** { "tree" :"SubstanceReferenceInformation.target.target", "datatype" : "Identifier, CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : ["addTarget"] , "methodName" : "setTarget, setType, addCoding, setSystem"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnTrgtTrgtDntfrTpCcCVrsn() /** { "tree" :"SubstanceReferenceInformation.target.target", "datatype" : "Identifier, CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addTarget"] , "methodName" : "setTarget, setType, addCoding, setVersion"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnTrgtTrgtDntfrTpCcCCde() /** { "tree" :"SubstanceReferenceInformation.target.target", "datatype" : "Identifier, CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : ["addTarget"] , "methodName" : "setTarget, setType, addCoding, setCode"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnTrgtTrgtDntfrTpCcCDsplay() /** { "tree" :"SubstanceReferenceInformation.target.target", "datatype" : "Identifier, CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addTarget"] , "methodName" : "setTarget, setType, addCoding, setDisplay"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnTrgtTrgtDntfrTpCcCSrSlctd() /** { "tree" :"SubstanceReferenceInformation.target.target", "datatype" : "Identifier, CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : ["addTarget"] , "methodName" : "setTarget, setType, addCoding, setUserSelected"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnTrgtTrgtDntfrTpCcTxt() /** { "tree" :"SubstanceReferenceInformation.target.target", "datatype" : "Identifier, CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : ["addTarget"] , "methodName" : "setTarget, setType, setText"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnTrgtTrgtDntfrPrdPrdStrt() /** { "tree" :"SubstanceReferenceInformation.target.target", "datatype" : "Identifier, Period, dateTime", "cardinality" : "ZeroOne", "elementtree" : ["addTarget"] , "methodName" : "setTarget, setPeriod, setStart"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnTrgtTrgtDntfrPrdPrdNd() /** { "tree" :"SubstanceReferenceInformation.target.target", "datatype" : "Identifier, Period, dateTime", "cardinality" : "ZeroOne", "elementtree" : ["addTarget"] , "methodName" : "setTarget, setPeriod, setEnd"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnTrgtTrgtDntfrSsgnr() /** { "tree" :"SubstanceReferenceInformation.target.target", "datatype" : "Identifier, Reference", "cardinality" : "ZeroOne", "elementtree" : ["addTarget"] , "methodName" : "setTarget, setAssigner"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnTrgtTrgtDntfrVlue() /** { "tree" :"SubstanceReferenceInformation.target.target", "datatype" : "Identifier, string", "cardinality" : "ZeroOne", "elementtree" : ["addTarget"] , "methodName" : "setTarget, setValue"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnTrgtTrgtDntfrSstm() /** { "tree" :"SubstanceReferenceInformation.target.target", "datatype" : "Identifier, uri", "cardinality" : "ZeroOne", "elementtree" : ["addTarget"] , "methodName" : "setTarget, setSystem"} **/
						));
Substancereferenceinformationobj.setType(HapiFHIRHelpers.createCodeableConcept(substancereferenceinformation.getSbstncRfrncnfrmtnTrgtTpCcCdngCSstm() /** { "tree" :"SubstanceReferenceInformation.target.type", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : ["addTarget"] , "methodName" : "setType, addCoding, setSystem"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnTrgtTpCcCdngCVrsn() /** { "tree" :"SubstanceReferenceInformation.target.type", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addTarget"] , "methodName" : "setType, addCoding, setVersion"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnTrgtTpCcCdngCCde() /** { "tree" :"SubstanceReferenceInformation.target.type", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : ["addTarget"] , "methodName" : "setType, addCoding, setCode"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnTrgtTpCcCdngCDsplay() /** { "tree" :"SubstanceReferenceInformation.target.type", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addTarget"] , "methodName" : "setType, addCoding, setDisplay"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnTrgtTpCcCdngCSrSlctd() /** { "tree" :"SubstanceReferenceInformation.target.type", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : ["addTarget"] , "methodName" : "setType, addCoding, setUserSelected"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnTrgtTpCcTxt() /** { "tree" :"SubstanceReferenceInformation.target.type", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : ["addTarget"] , "methodName" : "setType, setText"} **/
						));
Substancereferenceinformationobj.setInteraction(HapiFHIRHelpers.createCodeableConcept(substancereferenceinformation.getSbstncRfrncnfrmtnTrgtNtrctnCcCdngCSstm() /** { "tree" :"SubstanceReferenceInformation.target.interaction", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : ["addTarget"] , "methodName" : "setInteraction, addCoding, setSystem"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnTrgtNtrctnCcCdngCVrsn() /** { "tree" :"SubstanceReferenceInformation.target.interaction", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addTarget"] , "methodName" : "setInteraction, addCoding, setVersion"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnTrgtNtrctnCcCdngCCde() /** { "tree" :"SubstanceReferenceInformation.target.interaction", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : ["addTarget"] , "methodName" : "setInteraction, addCoding, setCode"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnTrgtNtrctnCcCdngCDsplay() /** { "tree" :"SubstanceReferenceInformation.target.interaction", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addTarget"] , "methodName" : "setInteraction, addCoding, setDisplay"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnTrgtNtrctnCcCdngCSrSlctd() /** { "tree" :"SubstanceReferenceInformation.target.interaction", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : ["addTarget"] , "methodName" : "setInteraction, addCoding, setUserSelected"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnTrgtNtrctnCcTxt() /** { "tree" :"SubstanceReferenceInformation.target.interaction", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : ["addTarget"] , "methodName" : "setInteraction, setText"} **/
						));
Substancereferenceinformationobj.setOrganism(HapiFHIRHelpers.createCodeableConcept(substancereferenceinformation.getSbstncRfrncnfrmtnTrgtRgnsmCcCdngCSstm() /** { "tree" :"SubstanceReferenceInformation.target.organism", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : ["addTarget"] , "methodName" : "setOrganism, addCoding, setSystem"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnTrgtRgnsmCcCdngCVrsn() /** { "tree" :"SubstanceReferenceInformation.target.organism", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addTarget"] , "methodName" : "setOrganism, addCoding, setVersion"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnTrgtRgnsmCcCdngCCde() /** { "tree" :"SubstanceReferenceInformation.target.organism", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : ["addTarget"] , "methodName" : "setOrganism, addCoding, setCode"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnTrgtRgnsmCcCdngCDsplay() /** { "tree" :"SubstanceReferenceInformation.target.organism", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addTarget"] , "methodName" : "setOrganism, addCoding, setDisplay"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnTrgtRgnsmCcCdngCSrSlctd() /** { "tree" :"SubstanceReferenceInformation.target.organism", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : ["addTarget"] , "methodName" : "setOrganism, addCoding, setUserSelected"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnTrgtRgnsmCcTxt() /** { "tree" :"SubstanceReferenceInformation.target.organism", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : ["addTarget"] , "methodName" : "setOrganism, setText"} **/
						));
Substancereferenceinformationobj.setOrganismType(HapiFHIRHelpers.createCodeableConcept(substancereferenceinformation.getSbstncRfrncnfrmtnTrgtRgnsmTpCcCdngCSstm() /** { "tree" :"SubstanceReferenceInformation.target.organismType", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : ["addTarget"] , "methodName" : "setOrganismType, addCoding, setSystem"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnTrgtRgnsmTpCcCdngCVrsn() /** { "tree" :"SubstanceReferenceInformation.target.organismType", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addTarget"] , "methodName" : "setOrganismType, addCoding, setVersion"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnTrgtRgnsmTpCcCdngCCde() /** { "tree" :"SubstanceReferenceInformation.target.organismType", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : ["addTarget"] , "methodName" : "setOrganismType, addCoding, setCode"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnTrgtRgnsmTpCcCdngCDsplay() /** { "tree" :"SubstanceReferenceInformation.target.organismType", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addTarget"] , "methodName" : "setOrganismType, addCoding, setDisplay"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnTrgtRgnsmTpCcCdngCSrSlctd() /** { "tree" :"SubstanceReferenceInformation.target.organismType", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : ["addTarget"] , "methodName" : "setOrganismType, addCoding, setUserSelected"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnTrgtRgnsmTpCcTxt() /** { "tree" :"SubstanceReferenceInformation.target.organismType", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : ["addTarget"] , "methodName" : "setOrganismType, setText"} **/
						));
Substancereferenceinformationobj.setAmountQuantity(HapiFHIRHelpers.createQuantity(substancereferenceinformation.getSbstncRfrncnfrmtnTrgtMntQnttQnttCmprtr() /** { "tree" :"SubstanceReferenceInformation.target.amountQuantity", "datatype" : "Quantity, code", "cardinality" : "ZeroOne", "elementtree" : ["addTarget"] , "methodName" : "setAmountQuantity, setComparator"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnTrgtMntQnttQnttCde() /** { "tree" :"SubstanceReferenceInformation.target.amountQuantity", "datatype" : "Quantity, code", "cardinality" : "ZeroOne", "elementtree" : ["addTarget"] , "methodName" : "setAmountQuantity, setCode"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnTrgtMntQnttQnttVlue() /** { "tree" :"SubstanceReferenceInformation.target.amountQuantity", "datatype" : "Quantity, decimal", "cardinality" : "ZeroOne", "elementtree" : ["addTarget"] , "methodName" : "setAmountQuantity, setValue"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnTrgtMntQnttQnttNt() /** { "tree" :"SubstanceReferenceInformation.target.amountQuantity", "datatype" : "Quantity, string", "cardinality" : "ZeroOne", "elementtree" : ["addTarget"] , "methodName" : "setAmountQuantity, setUnit"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnTrgtMntQnttQnttSstm() /** { "tree" :"SubstanceReferenceInformation.target.amountQuantity", "datatype" : "Quantity, uri", "cardinality" : "ZeroOne", "elementtree" : ["addTarget"] , "methodName" : "setAmountQuantity, setSystem"} **/
						));
Substancereferenceinformationobj.setAmountRange(HapiFHIRHelpers.createRange(substancereferenceinformation.getSbstncRfrncnfrmtnTrgtMntRngRngLw() /** { "tree" :"SubstanceReferenceInformation.target.amountRange", "datatype" : "Range, SimpleQuantity", "cardinality" : "ZeroOne", "elementtree" : ["addTarget"] , "methodName" : "setAmountRange, setLow"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnTrgtMntRngRngHgh() /** { "tree" :"SubstanceReferenceInformation.target.amountRange", "datatype" : "Range, SimpleQuantity", "cardinality" : "ZeroOne", "elementtree" : ["addTarget"] , "methodName" : "setAmountRange, setHigh"} **/
						));
Substancereferenceinformationobj.setAmountString(HapiFHIRHelpers.createstring(substancereferenceinformation.getSbstncRfrncnfrmtnTrgtMntStrngStrng() /** { "tree" :"SubstanceReferenceInformation.target.amountString", "datatype" : "string", "cardinality" : "ZeroOne", "elementtree" : ["addTarget"] , "methodName" : "setAmountString"} **/
						));
Substancereferenceinformationobj.setAmountType(HapiFHIRHelpers.createCodeableConcept(substancereferenceinformation.getSbstncRfrncnfrmtnTrgtMntTpCcCdngCSstm() /** { "tree" :"SubstanceReferenceInformation.target.amountType", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : ["addTarget"] , "methodName" : "setAmountType, addCoding, setSystem"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnTrgtMntTpCcCdngCVrsn() /** { "tree" :"SubstanceReferenceInformation.target.amountType", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addTarget"] , "methodName" : "setAmountType, addCoding, setVersion"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnTrgtMntTpCcCdngCCde() /** { "tree" :"SubstanceReferenceInformation.target.amountType", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : ["addTarget"] , "methodName" : "setAmountType, addCoding, setCode"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnTrgtMntTpCcCdngCDsplay() /** { "tree" :"SubstanceReferenceInformation.target.amountType", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addTarget"] , "methodName" : "setAmountType, addCoding, setDisplay"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnTrgtMntTpCcCdngCSrSlctd() /** { "tree" :"SubstanceReferenceInformation.target.amountType", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : ["addTarget"] , "methodName" : "setAmountType, addCoding, setUserSelected"} **/
						, substancereferenceinformation.getSbstncRfrncnfrmtnTrgtMntTpCcTxt() /** { "tree" :"SubstanceReferenceInformation.target.amountType", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : ["addTarget"] , "methodName" : "setAmountType, setText"} **/
						));
Substancereferenceinformationobj.addSource(HapiFHIRHelpers.createReference(substancereferenceinformation.getSbstncRfrncnfrmtnTrgtSrcRfrnce() /** { "tree" :"SubstanceReferenceInformation.target.source", "datatype" : "Reference", "cardinality" : "Many", "elementtree" : ["addTarget"] , "methodName" : "addSource"} **/
		));
	}
}
