package main.templateoutput.Conversions;
// Generated on Jan 28, 2022, 8:02:40 AM 


import org.hl7.fhir.r4.model.Patient;

/**
 *  object for conversion model class Substancenucleicacid.
 * @see .Substancenucleicacid
 * @author Paul Kovach
 */
import main.java.com.campfhir.service.conversion.HapiFHIRHelpers;

public class SubstancenucleicacidConversion 
{
	public Patient Substancenucleicacids(main.templateoutput.Model.Substancenucleicacid substancenucleicacid) 
	{
			Patient  Substancenucleicacidobj = new Patient(); 

						Substancenucleicacidobj.setSequenceType(HapiFHIRHelpers.createCodeableConcept(substancenucleicacid.getSbstncNclccdSqncTpCcCdngCSstm() /** { "tree" :"SubstanceNucleicAcid.sequenceType", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setSequenceType, addCoding, setSystem"} **/
						, substancenucleicacid.getSbstncNclccdSqncTpCcCdngCVrsn() /** { "tree" :"SubstanceNucleicAcid.sequenceType", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setSequenceType, addCoding, setVersion"} **/
						, substancenucleicacid.getSbstncNclccdSqncTpCcCdngCCde() /** { "tree" :"SubstanceNucleicAcid.sequenceType", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setSequenceType, addCoding, setCode"} **/
						, substancenucleicacid.getSbstncNclccdSqncTpCcCdngCDsplay() /** { "tree" :"SubstanceNucleicAcid.sequenceType", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setSequenceType, addCoding, setDisplay"} **/
						, substancenucleicacid.getSbstncNclccdSqncTpCcCdngCSrSlctd() /** { "tree" :"SubstanceNucleicAcid.sequenceType", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setSequenceType, addCoding, setUserSelected"} **/
						, substancenucleicacid.getSbstncNclccdSqncTpCcTxt() /** { "tree" :"SubstanceNucleicAcid.sequenceType", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setSequenceType, setText"} **/
						));
Substancenucleicacidobj.setNumberOfSubunits(HapiFHIRHelpers.createinteger(substancenucleicacid.getSbstncNclccdNmbrfSbntsNtgr() /** { "tree" :"SubstanceNucleicAcid.numberOfSubunits", "datatype" : "integer", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setNumberOfSubunits"} **/
						));
Substancenucleicacidobj.setAreaOfHybridisation(HapiFHIRHelpers.createstring(substancenucleicacid.getSbstncNclccdRfHbrdstnStrng() /** { "tree" :"SubstanceNucleicAcid.areaOfHybridisation", "datatype" : "string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setAreaOfHybridisation"} **/
						));
Substancenucleicacidobj.setOligoNucleotideType(HapiFHIRHelpers.createCodeableConcept(substancenucleicacid.getSbstncNclccdLgNcltdTpCcCdngCSstm() /** { "tree" :"SubstanceNucleicAcid.oligoNucleotideType", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setOligoNucleotideType, addCoding, setSystem"} **/
						, substancenucleicacid.getSbstncNclccdLgNcltdTpCcCdngCVrsn() /** { "tree" :"SubstanceNucleicAcid.oligoNucleotideType", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setOligoNucleotideType, addCoding, setVersion"} **/
						, substancenucleicacid.getSbstncNclccdLgNcltdTpCcCdngCCde() /** { "tree" :"SubstanceNucleicAcid.oligoNucleotideType", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setOligoNucleotideType, addCoding, setCode"} **/
						, substancenucleicacid.getSbstncNclccdLgNcltdTpCcCdngCDsplay() /** { "tree" :"SubstanceNucleicAcid.oligoNucleotideType", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setOligoNucleotideType, addCoding, setDisplay"} **/
						, substancenucleicacid.getSbstncNclccdLgNcltdTpCcCdngCSrSlctd() /** { "tree" :"SubstanceNucleicAcid.oligoNucleotideType", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setOligoNucleotideType, addCoding, setUserSelected"} **/
						, substancenucleicacid.getSbstncNclccdLgNcltdTpCcTxt() /** { "tree" :"SubstanceNucleicAcid.oligoNucleotideType", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setOligoNucleotideType, setText"} **/
						));
Substancenucleicacidobj.setSubunit(HapiFHIRHelpers.createinteger(substancenucleicacid.getSbstncNclccdSbntSbntNtgr() /** { "tree" :"SubstanceNucleicAcid.subunit.subunit", "datatype" : "integer", "cardinality" : "ZeroOne", "elementtree" : ["addSubunit"] , "methodName" : "setSubunit"} **/
						));
Substancenucleicacidobj.setSequence(HapiFHIRHelpers.createstring(substancenucleicacid.getSbstncNclccdSbntSqncStrng() /** { "tree" :"SubstanceNucleicAcid.subunit.sequence", "datatype" : "string", "cardinality" : "ZeroOne", "elementtree" : ["addSubunit"] , "methodName" : "setSequence"} **/
						));
Substancenucleicacidobj.setLength(HapiFHIRHelpers.createinteger(substancenucleicacid.getSbstncNclccdSbntLngthNtgr() /** { "tree" :"SubstanceNucleicAcid.subunit.length", "datatype" : "integer", "cardinality" : "ZeroOne", "elementtree" : ["addSubunit"] , "methodName" : "setLength"} **/
						));
Substancenucleicacidobj.setSequenceAttachment(HapiFHIRHelpers.createAttachment(substancenucleicacid.getSbstncNclccdSbntSqncttchmntTtchmntDta() /** { "tree" :"SubstanceNucleicAcid.subunit.sequenceAttachment", "datatype" : "Attachment, base64Binary", "cardinality" : "ZeroOne", "elementtree" : ["addSubunit"] , "methodName" : "setSequenceAttachment, setData"} **/
						, substancenucleicacid.getSbstncNclccdSbntSqncttchmntTtchmntHsh() /** { "tree" :"SubstanceNucleicAcid.subunit.sequenceAttachment", "datatype" : "Attachment, base64Binary", "cardinality" : "ZeroOne", "elementtree" : ["addSubunit"] , "methodName" : "setSequenceAttachment, setHash"} **/
						, substancenucleicacid.getSbstncNclccdSbntSqncttchmntTtchmntCntntTpe() /** { "tree" :"SubstanceNucleicAcid.subunit.sequenceAttachment", "datatype" : "Attachment, code", "cardinality" : "ZeroOne", "elementtree" : ["addSubunit"] , "methodName" : "setSequenceAttachment, setContentType"} **/
						, substancenucleicacid.getSbstncNclccdSbntSqncttchmntTtchmntLngge() /** { "tree" :"SubstanceNucleicAcid.subunit.sequenceAttachment", "datatype" : "Attachment, code", "cardinality" : "ZeroOne", "elementtree" : ["addSubunit"] , "methodName" : "setSequenceAttachment, setLanguage"} **/
						, substancenucleicacid.getSbstncNclccdSbntSqncttchmntTtchmntCrtn() /** { "tree" :"SubstanceNucleicAcid.subunit.sequenceAttachment", "datatype" : "Attachment, dateTime", "cardinality" : "ZeroOne", "elementtree" : ["addSubunit"] , "methodName" : "setSequenceAttachment, setCreation"} **/
						, substancenucleicacid.getSbstncNclccdSbntSqncttchmntTtchmntTtle() /** { "tree" :"SubstanceNucleicAcid.subunit.sequenceAttachment", "datatype" : "Attachment, string", "cardinality" : "ZeroOne", "elementtree" : ["addSubunit"] , "methodName" : "setSequenceAttachment, setTitle"} **/
						, substancenucleicacid.getSbstncNclccdSbntSqncttchmntTtchmntSze() /** { "tree" :"SubstanceNucleicAcid.subunit.sequenceAttachment", "datatype" : "Attachment, unsignedInt", "cardinality" : "ZeroOne", "elementtree" : ["addSubunit"] , "methodName" : "setSequenceAttachment, setSize"} **/
						, substancenucleicacid.getSbstncNclccdSbntSqncttchmntTtchmntRl() /** { "tree" :"SubstanceNucleicAcid.subunit.sequenceAttachment", "datatype" : "Attachment, url", "cardinality" : "ZeroOne", "elementtree" : ["addSubunit"] , "methodName" : "setSequenceAttachment, setUrl"} **/
						));
Substancenucleicacidobj.setFivePrime(HapiFHIRHelpers.createCodeableConcept(substancenucleicacid.getSbstncNclccdSbntFvPrmCcCdngCSstm() /** { "tree" :"SubstanceNucleicAcid.subunit.fivePrime", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : ["addSubunit"] , "methodName" : "setFivePrime, addCoding, setSystem"} **/
						, substancenucleicacid.getSbstncNclccdSbntFvPrmCcCdngCVrsn() /** { "tree" :"SubstanceNucleicAcid.subunit.fivePrime", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addSubunit"] , "methodName" : "setFivePrime, addCoding, setVersion"} **/
						, substancenucleicacid.getSbstncNclccdSbntFvPrmCcCdngCCde() /** { "tree" :"SubstanceNucleicAcid.subunit.fivePrime", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : ["addSubunit"] , "methodName" : "setFivePrime, addCoding, setCode"} **/
						, substancenucleicacid.getSbstncNclccdSbntFvPrmCcCdngCDsplay() /** { "tree" :"SubstanceNucleicAcid.subunit.fivePrime", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addSubunit"] , "methodName" : "setFivePrime, addCoding, setDisplay"} **/
						, substancenucleicacid.getSbstncNclccdSbntFvPrmCcCdngCSrSlctd() /** { "tree" :"SubstanceNucleicAcid.subunit.fivePrime", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : ["addSubunit"] , "methodName" : "setFivePrime, addCoding, setUserSelected"} **/
						, substancenucleicacid.getSbstncNclccdSbntFvPrmCcTxt() /** { "tree" :"SubstanceNucleicAcid.subunit.fivePrime", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : ["addSubunit"] , "methodName" : "setFivePrime, setText"} **/
						));
Substancenucleicacidobj.setThreePrime(HapiFHIRHelpers.createCodeableConcept(substancenucleicacid.getSbstncNclccdSbntThrPrmCcCdngCSstm() /** { "tree" :"SubstanceNucleicAcid.subunit.threePrime", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : ["addSubunit"] , "methodName" : "setThreePrime, addCoding, setSystem"} **/
						, substancenucleicacid.getSbstncNclccdSbntThrPrmCcCdngCVrsn() /** { "tree" :"SubstanceNucleicAcid.subunit.threePrime", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addSubunit"] , "methodName" : "setThreePrime, addCoding, setVersion"} **/
						, substancenucleicacid.getSbstncNclccdSbntThrPrmCcCdngCCde() /** { "tree" :"SubstanceNucleicAcid.subunit.threePrime", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : ["addSubunit"] , "methodName" : "setThreePrime, addCoding, setCode"} **/
						, substancenucleicacid.getSbstncNclccdSbntThrPrmCcCdngCDsplay() /** { "tree" :"SubstanceNucleicAcid.subunit.threePrime", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addSubunit"] , "methodName" : "setThreePrime, addCoding, setDisplay"} **/
						, substancenucleicacid.getSbstncNclccdSbntThrPrmCcCdngCSrSlctd() /** { "tree" :"SubstanceNucleicAcid.subunit.threePrime", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : ["addSubunit"] , "methodName" : "setThreePrime, addCoding, setUserSelected"} **/
						, substancenucleicacid.getSbstncNclccdSbntThrPrmCcTxt() /** { "tree" :"SubstanceNucleicAcid.subunit.threePrime", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : ["addSubunit"] , "methodName" : "setThreePrime, setText"} **/
						));
Substancenucleicacidobj.setConnectivity(HapiFHIRHelpers.createstring(substancenucleicacid.getSbstncNclccdSbntLnkgCnnctvtStrng() /** { "tree" :"SubstanceNucleicAcid.subunit.linkage.connectivity", "datatype" : "string", "cardinality" : "ZeroOne", "elementtree" : ["addSubunit", "addLinkage"] , "methodName" : "setConnectivity"} **/
						));
Substancenucleicacidobj.setIdentifier(HapiFHIRHelpers.createIdentifier(substancenucleicacid.getSbstncNclccdSbntLnkgDntfrDntfrSe() /** { "tree" :"SubstanceNucleicAcid.subunit.linkage.identifier", "datatype" : "Identifier, code", "cardinality" : "ZeroOne", "elementtree" : ["addSubunit", "addLinkage"] , "methodName" : "setIdentifier, setUse"} **/
						, substancenucleicacid.getSbstncNclccdSbntLnkgDntfrDntfrTpCcCSstm() /** { "tree" :"SubstanceNucleicAcid.subunit.linkage.identifier", "datatype" : "Identifier, CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : ["addSubunit", "addLinkage"] , "methodName" : "setIdentifier, setType, addCoding, setSystem"} **/
						, substancenucleicacid.getSbstncNclccdSbntLnkgDntfrDntfrTpCcCVrsn() /** { "tree" :"SubstanceNucleicAcid.subunit.linkage.identifier", "datatype" : "Identifier, CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addSubunit", "addLinkage"] , "methodName" : "setIdentifier, setType, addCoding, setVersion"} **/
						, substancenucleicacid.getSbstncNclccdSbntLnkgDntfrDntfrTpCcCCde() /** { "tree" :"SubstanceNucleicAcid.subunit.linkage.identifier", "datatype" : "Identifier, CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : ["addSubunit", "addLinkage"] , "methodName" : "setIdentifier, setType, addCoding, setCode"} **/
						, substancenucleicacid.getSbstncNclccdSbntLnkgDntfrDntfrTpCcCDsplay() /** { "tree" :"SubstanceNucleicAcid.subunit.linkage.identifier", "datatype" : "Identifier, CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addSubunit", "addLinkage"] , "methodName" : "setIdentifier, setType, addCoding, setDisplay"} **/
						, substancenucleicacid.getSbstncNclccdSbntLnkgDntfrDntfrTpCcCSrSlctd() /** { "tree" :"SubstanceNucleicAcid.subunit.linkage.identifier", "datatype" : "Identifier, CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : ["addSubunit", "addLinkage"] , "methodName" : "setIdentifier, setType, addCoding, setUserSelected"} **/
						, substancenucleicacid.getSbstncNclccdSbntLnkgDntfrDntfrTpCcTxt() /** { "tree" :"SubstanceNucleicAcid.subunit.linkage.identifier", "datatype" : "Identifier, CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : ["addSubunit", "addLinkage"] , "methodName" : "setIdentifier, setType, setText"} **/
						, substancenucleicacid.getSbstncNclccdSbntLnkgDntfrDntfrPrdPrdStrt() /** { "tree" :"SubstanceNucleicAcid.subunit.linkage.identifier", "datatype" : "Identifier, Period, dateTime", "cardinality" : "ZeroOne", "elementtree" : ["addSubunit", "addLinkage"] , "methodName" : "setIdentifier, setPeriod, setStart"} **/
						, substancenucleicacid.getSbstncNclccdSbntLnkgDntfrDntfrPrdPrdNd() /** { "tree" :"SubstanceNucleicAcid.subunit.linkage.identifier", "datatype" : "Identifier, Period, dateTime", "cardinality" : "ZeroOne", "elementtree" : ["addSubunit", "addLinkage"] , "methodName" : "setIdentifier, setPeriod, setEnd"} **/
						, substancenucleicacid.getSbstncNclccdSbntLnkgDntfrDntfrSsgnr() /** { "tree" :"SubstanceNucleicAcid.subunit.linkage.identifier", "datatype" : "Identifier, Reference", "cardinality" : "ZeroOne", "elementtree" : ["addSubunit", "addLinkage"] , "methodName" : "setIdentifier, setAssigner"} **/
						, substancenucleicacid.getSbstncNclccdSbntLnkgDntfrDntfrVlue() /** { "tree" :"SubstanceNucleicAcid.subunit.linkage.identifier", "datatype" : "Identifier, string", "cardinality" : "ZeroOne", "elementtree" : ["addSubunit", "addLinkage"] , "methodName" : "setIdentifier, setValue"} **/
						, substancenucleicacid.getSbstncNclccdSbntLnkgDntfrDntfrSstm() /** { "tree" :"SubstanceNucleicAcid.subunit.linkage.identifier", "datatype" : "Identifier, uri", "cardinality" : "ZeroOne", "elementtree" : ["addSubunit", "addLinkage"] , "methodName" : "setIdentifier, setSystem"} **/
						));
Substancenucleicacidobj.setName(HapiFHIRHelpers.createstring(substancenucleicacid.getSbstncNclccdSbntLnkgNmStrng() /** { "tree" :"SubstanceNucleicAcid.subunit.linkage.name", "datatype" : "string", "cardinality" : "ZeroOne", "elementtree" : ["addSubunit", "addLinkage"] , "methodName" : "setName"} **/
						));
Substancenucleicacidobj.setResidueSite(HapiFHIRHelpers.createstring(substancenucleicacid.getSbstncNclccdSbntLnkgRsdStStrng() /** { "tree" :"SubstanceNucleicAcid.subunit.linkage.residueSite", "datatype" : "string", "cardinality" : "ZeroOne", "elementtree" : ["addSubunit", "addLinkage"] , "methodName" : "setResidueSite"} **/
						));
Substancenucleicacidobj.setIdentifier(HapiFHIRHelpers.createIdentifier(substancenucleicacid.getSbstncNclccdSbntSgrDntfrDntfrSe() /** { "tree" :"SubstanceNucleicAcid.subunit.sugar.identifier", "datatype" : "Identifier, code", "cardinality" : "ZeroOne", "elementtree" : ["addSubunit", "addLinkage", "addSugar"] , "methodName" : "setIdentifier, setUse"} **/
						, substancenucleicacid.getSbstncNclccdSbntSgrDntfrDntfrTpCcCSstm() /** { "tree" :"SubstanceNucleicAcid.subunit.sugar.identifier", "datatype" : "Identifier, CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : ["addSubunit", "addLinkage", "addSugar"] , "methodName" : "setIdentifier, setType, addCoding, setSystem"} **/
						, substancenucleicacid.getSbstncNclccdSbntSgrDntfrDntfrTpCcCVrsn() /** { "tree" :"SubstanceNucleicAcid.subunit.sugar.identifier", "datatype" : "Identifier, CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addSubunit", "addLinkage", "addSugar"] , "methodName" : "setIdentifier, setType, addCoding, setVersion"} **/
						, substancenucleicacid.getSbstncNclccdSbntSgrDntfrDntfrTpCcCCde() /** { "tree" :"SubstanceNucleicAcid.subunit.sugar.identifier", "datatype" : "Identifier, CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : ["addSubunit", "addLinkage", "addSugar"] , "methodName" : "setIdentifier, setType, addCoding, setCode"} **/
						, substancenucleicacid.getSbstncNclccdSbntSgrDntfrDntfrTpCcCDsplay() /** { "tree" :"SubstanceNucleicAcid.subunit.sugar.identifier", "datatype" : "Identifier, CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addSubunit", "addLinkage", "addSugar"] , "methodName" : "setIdentifier, setType, addCoding, setDisplay"} **/
						, substancenucleicacid.getSbstncNclccdSbntSgrDntfrDntfrTpCcCSrSlctd() /** { "tree" :"SubstanceNucleicAcid.subunit.sugar.identifier", "datatype" : "Identifier, CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : ["addSubunit", "addLinkage", "addSugar"] , "methodName" : "setIdentifier, setType, addCoding, setUserSelected"} **/
						, substancenucleicacid.getSbstncNclccdSbntSgrDntfrDntfrTpCcTxt() /** { "tree" :"SubstanceNucleicAcid.subunit.sugar.identifier", "datatype" : "Identifier, CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : ["addSubunit", "addLinkage", "addSugar"] , "methodName" : "setIdentifier, setType, setText"} **/
						, substancenucleicacid.getSbstncNclccdSbntSgrDntfrDntfrPrdPrdStrt() /** { "tree" :"SubstanceNucleicAcid.subunit.sugar.identifier", "datatype" : "Identifier, Period, dateTime", "cardinality" : "ZeroOne", "elementtree" : ["addSubunit", "addLinkage", "addSugar"] , "methodName" : "setIdentifier, setPeriod, setStart"} **/
						, substancenucleicacid.getSbstncNclccdSbntSgrDntfrDntfrPrdPrdNd() /** { "tree" :"SubstanceNucleicAcid.subunit.sugar.identifier", "datatype" : "Identifier, Period, dateTime", "cardinality" : "ZeroOne", "elementtree" : ["addSubunit", "addLinkage", "addSugar"] , "methodName" : "setIdentifier, setPeriod, setEnd"} **/
						, substancenucleicacid.getSbstncNclccdSbntSgrDntfrDntfrSsgnr() /** { "tree" :"SubstanceNucleicAcid.subunit.sugar.identifier", "datatype" : "Identifier, Reference", "cardinality" : "ZeroOne", "elementtree" : ["addSubunit", "addLinkage", "addSugar"] , "methodName" : "setIdentifier, setAssigner"} **/
						, substancenucleicacid.getSbstncNclccdSbntSgrDntfrDntfrVlue() /** { "tree" :"SubstanceNucleicAcid.subunit.sugar.identifier", "datatype" : "Identifier, string", "cardinality" : "ZeroOne", "elementtree" : ["addSubunit", "addLinkage", "addSugar"] , "methodName" : "setIdentifier, setValue"} **/
						, substancenucleicacid.getSbstncNclccdSbntSgrDntfrDntfrSstm() /** { "tree" :"SubstanceNucleicAcid.subunit.sugar.identifier", "datatype" : "Identifier, uri", "cardinality" : "ZeroOne", "elementtree" : ["addSubunit", "addLinkage", "addSugar"] , "methodName" : "setIdentifier, setSystem"} **/
						));
Substancenucleicacidobj.setName(HapiFHIRHelpers.createstring(substancenucleicacid.getSbstncNclccdSbntSgrNmStrng() /** { "tree" :"SubstanceNucleicAcid.subunit.sugar.name", "datatype" : "string", "cardinality" : "ZeroOne", "elementtree" : ["addSubunit", "addLinkage", "addSugar"] , "methodName" : "setName"} **/
						));
Substancenucleicacidobj.setResidueSite(HapiFHIRHelpers.createstring(substancenucleicacid.getSbstncNclccdSbntSgrRsdStStrng() /** { "tree" :"SubstanceNucleicAcid.subunit.sugar.residueSite", "datatype" : "string", "cardinality" : "ZeroOne", "elementtree" : ["addSubunit", "addLinkage", "addSugar"] , "methodName" : "setResidueSite"} **/
		));
	}
}
