package main.templateoutput.Conversions;
// Generated on Jan 28, 2022, 8:02:40 AM 


import org.hl7.fhir.r4.model.Patient;

/**
 *  object for conversion model class Substancesourcematerial.
 * @see .Substancesourcematerial
 * @author Paul Kovach
 */
import main.java.com.campfhir.service.conversion.HapiFHIRHelpers;

public class SubstancesourcematerialConversion 
{
	public Patient Substancesourcematerials(main.templateoutput.Model.Substancesourcematerial substancesourcematerial) 
	{
			Patient  Substancesourcematerialobj = new Patient(); 

						Substancesourcematerialobj.setSourceMaterialClass(HapiFHIRHelpers.createCodeableConcept(substancesourcematerial.getSbstncSrcMtrlSrcMtrlClssCcCdngCSstm() /** { "tree" :"SubstanceSourceMaterial.sourceMaterialClass", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setSourceMaterialClass, addCoding, setSystem"} **/
						, substancesourcematerial.getSbstncSrcMtrlSrcMtrlClssCcCdngCVrsn() /** { "tree" :"SubstanceSourceMaterial.sourceMaterialClass", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setSourceMaterialClass, addCoding, setVersion"} **/
						, substancesourcematerial.getSbstncSrcMtrlSrcMtrlClssCcCdngCCde() /** { "tree" :"SubstanceSourceMaterial.sourceMaterialClass", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setSourceMaterialClass, addCoding, setCode"} **/
						, substancesourcematerial.getSbstncSrcMtrlSrcMtrlClssCcCdngCDsplay() /** { "tree" :"SubstanceSourceMaterial.sourceMaterialClass", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setSourceMaterialClass, addCoding, setDisplay"} **/
						, substancesourcematerial.getSbstncSrcMtrlSrcMtrlClssCcCdngCSrSlctd() /** { "tree" :"SubstanceSourceMaterial.sourceMaterialClass", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setSourceMaterialClass, addCoding, setUserSelected"} **/
						, substancesourcematerial.getSbstncSrcMtrlSrcMtrlClssCcTxt() /** { "tree" :"SubstanceSourceMaterial.sourceMaterialClass", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setSourceMaterialClass, setText"} **/
						));
Substancesourcematerialobj.setSourceMaterialType(HapiFHIRHelpers.createCodeableConcept(substancesourcematerial.getSbstncSrcMtrlSrcMtrlTpCcCdngCSstm() /** { "tree" :"SubstanceSourceMaterial.sourceMaterialType", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setSourceMaterialType, addCoding, setSystem"} **/
						, substancesourcematerial.getSbstncSrcMtrlSrcMtrlTpCcCdngCVrsn() /** { "tree" :"SubstanceSourceMaterial.sourceMaterialType", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setSourceMaterialType, addCoding, setVersion"} **/
						, substancesourcematerial.getSbstncSrcMtrlSrcMtrlTpCcCdngCCde() /** { "tree" :"SubstanceSourceMaterial.sourceMaterialType", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setSourceMaterialType, addCoding, setCode"} **/
						, substancesourcematerial.getSbstncSrcMtrlSrcMtrlTpCcCdngCDsplay() /** { "tree" :"SubstanceSourceMaterial.sourceMaterialType", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setSourceMaterialType, addCoding, setDisplay"} **/
						, substancesourcematerial.getSbstncSrcMtrlSrcMtrlTpCcCdngCSrSlctd() /** { "tree" :"SubstanceSourceMaterial.sourceMaterialType", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setSourceMaterialType, addCoding, setUserSelected"} **/
						, substancesourcematerial.getSbstncSrcMtrlSrcMtrlTpCcTxt() /** { "tree" :"SubstanceSourceMaterial.sourceMaterialType", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setSourceMaterialType, setText"} **/
						));
Substancesourcematerialobj.setSourceMaterialState(HapiFHIRHelpers.createCodeableConcept(substancesourcematerial.getSbstncSrcMtrlSrcMtrlSttCcCdngCSstm() /** { "tree" :"SubstanceSourceMaterial.sourceMaterialState", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setSourceMaterialState, addCoding, setSystem"} **/
						, substancesourcematerial.getSbstncSrcMtrlSrcMtrlSttCcCdngCVrsn() /** { "tree" :"SubstanceSourceMaterial.sourceMaterialState", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setSourceMaterialState, addCoding, setVersion"} **/
						, substancesourcematerial.getSbstncSrcMtrlSrcMtrlSttCcCdngCCde() /** { "tree" :"SubstanceSourceMaterial.sourceMaterialState", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setSourceMaterialState, addCoding, setCode"} **/
						, substancesourcematerial.getSbstncSrcMtrlSrcMtrlSttCcCdngCDsplay() /** { "tree" :"SubstanceSourceMaterial.sourceMaterialState", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setSourceMaterialState, addCoding, setDisplay"} **/
						, substancesourcematerial.getSbstncSrcMtrlSrcMtrlSttCcCdngCSrSlctd() /** { "tree" :"SubstanceSourceMaterial.sourceMaterialState", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setSourceMaterialState, addCoding, setUserSelected"} **/
						, substancesourcematerial.getSbstncSrcMtrlSrcMtrlSttCcTxt() /** { "tree" :"SubstanceSourceMaterial.sourceMaterialState", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setSourceMaterialState, setText"} **/
						));
Substancesourcematerialobj.setOrganismId(HapiFHIRHelpers.createIdentifier(substancesourcematerial.getSbstncSrcMtrlRgnsmdDntfrSe() /** { "tree" :"SubstanceSourceMaterial.organismId", "datatype" : "Identifier, code", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setOrganismId, setUse"} **/
						, substancesourcematerial.getSbstncSrcMtrlRgnsmdDntfrTpCcCSstm() /** { "tree" :"SubstanceSourceMaterial.organismId", "datatype" : "Identifier, CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setOrganismId, setType, addCoding, setSystem"} **/
						, substancesourcematerial.getSbstncSrcMtrlRgnsmdDntfrTpCcCVrsn() /** { "tree" :"SubstanceSourceMaterial.organismId", "datatype" : "Identifier, CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setOrganismId, setType, addCoding, setVersion"} **/
						, substancesourcematerial.getSbstncSrcMtrlRgnsmdDntfrTpCcCCde() /** { "tree" :"SubstanceSourceMaterial.organismId", "datatype" : "Identifier, CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setOrganismId, setType, addCoding, setCode"} **/
						, substancesourcematerial.getSbstncSrcMtrlRgnsmdDntfrTpCcCDsplay() /** { "tree" :"SubstanceSourceMaterial.organismId", "datatype" : "Identifier, CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setOrganismId, setType, addCoding, setDisplay"} **/
						, substancesourcematerial.getSbstncSrcMtrlRgnsmdDntfrTpCcCSrSlctd() /** { "tree" :"SubstanceSourceMaterial.organismId", "datatype" : "Identifier, CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setOrganismId, setType, addCoding, setUserSelected"} **/
						, substancesourcematerial.getSbstncSrcMtrlRgnsmdDntfrTpCcTxt() /** { "tree" :"SubstanceSourceMaterial.organismId", "datatype" : "Identifier, CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setOrganismId, setType, setText"} **/
						, substancesourcematerial.getSbstncSrcMtrlRgnsmdDntfrPrdPrdStrt() /** { "tree" :"SubstanceSourceMaterial.organismId", "datatype" : "Identifier, Period, dateTime", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setOrganismId, setPeriod, setStart"} **/
						, substancesourcematerial.getSbstncSrcMtrlRgnsmdDntfrPrdPrdNd() /** { "tree" :"SubstanceSourceMaterial.organismId", "datatype" : "Identifier, Period, dateTime", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setOrganismId, setPeriod, setEnd"} **/
						, substancesourcematerial.getSbstncSrcMtrlRgnsmdDntfrSsgnr() /** { "tree" :"SubstanceSourceMaterial.organismId", "datatype" : "Identifier, Reference", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setOrganismId, setAssigner"} **/
						, substancesourcematerial.getSbstncSrcMtrlRgnsmdDntfrVlue() /** { "tree" :"SubstanceSourceMaterial.organismId", "datatype" : "Identifier, string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setOrganismId, setValue"} **/
						, substancesourcematerial.getSbstncSrcMtrlRgnsmdDntfrSstm() /** { "tree" :"SubstanceSourceMaterial.organismId", "datatype" : "Identifier, uri", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setOrganismId, setSystem"} **/
						));
Substancesourcematerialobj.setOrganismName(HapiFHIRHelpers.createstring(substancesourcematerial.getSbstncSrcMtrlRgnsmNmStrng() /** { "tree" :"SubstanceSourceMaterial.organismName", "datatype" : "string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setOrganismName"} **/
						));
Substancesourcematerialobj.addParentSubstanceId(HapiFHIRHelpers.createIdentifier(substancesourcematerial.getSbstncSrcMtrlPrntSbstncdDntfrSe() /** { "tree" :"SubstanceSourceMaterial.parentSubstanceId", "datatype" : "Identifier, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addParentSubstanceId, setUse"} **/
						, substancesourcematerial.getSbstncSrcMtrlPrntSbstncdDntfrTpCcCSstm() /** { "tree" :"SubstanceSourceMaterial.parentSubstanceId", "datatype" : "Identifier, CodeableConcept, Coding, uri", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addParentSubstanceId, setType, addCoding, setSystem"} **/
						, substancesourcematerial.getSbstncSrcMtrlPrntSbstncdDntfrTpCcCVrsn() /** { "tree" :"SubstanceSourceMaterial.parentSubstanceId", "datatype" : "Identifier, CodeableConcept, Coding, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addParentSubstanceId, setType, addCoding, setVersion"} **/
						, substancesourcematerial.getSbstncSrcMtrlPrntSbstncdDntfrTpCcCCde() /** { "tree" :"SubstanceSourceMaterial.parentSubstanceId", "datatype" : "Identifier, CodeableConcept, Coding, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addParentSubstanceId, setType, addCoding, setCode"} **/
						, substancesourcematerial.getSbstncSrcMtrlPrntSbstncdDntfrTpCcCDsplay() /** { "tree" :"SubstanceSourceMaterial.parentSubstanceId", "datatype" : "Identifier, CodeableConcept, Coding, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addParentSubstanceId, setType, addCoding, setDisplay"} **/
						, substancesourcematerial.getSbstncSrcMtrlPrntSbstncdDntfrTpCcCSrSlctd() /** { "tree" :"SubstanceSourceMaterial.parentSubstanceId", "datatype" : "Identifier, CodeableConcept, Coding, boolean", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addParentSubstanceId, setType, addCoding, setUserSelected"} **/
						, substancesourcematerial.getSbstncSrcMtrlPrntSbstncdDntfrTpCcTxt() /** { "tree" :"SubstanceSourceMaterial.parentSubstanceId", "datatype" : "Identifier, CodeableConcept, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addParentSubstanceId, setType, setText"} **/
						, substancesourcematerial.getSbstncSrcMtrlPrntSbstncdDntfrPrdPrdStrt() /** { "tree" :"SubstanceSourceMaterial.parentSubstanceId", "datatype" : "Identifier, Period, dateTime", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addParentSubstanceId, setPeriod, setStart"} **/
						, substancesourcematerial.getSbstncSrcMtrlPrntSbstncdDntfrPrdPrdNd() /** { "tree" :"SubstanceSourceMaterial.parentSubstanceId", "datatype" : "Identifier, Period, dateTime", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addParentSubstanceId, setPeriod, setEnd"} **/
						, substancesourcematerial.getSbstncSrcMtrlPrntSbstncdDntfrSsgnr() /** { "tree" :"SubstanceSourceMaterial.parentSubstanceId", "datatype" : "Identifier, Reference", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addParentSubstanceId, setAssigner"} **/
						, substancesourcematerial.getSbstncSrcMtrlPrntSbstncdDntfrVlue() /** { "tree" :"SubstanceSourceMaterial.parentSubstanceId", "datatype" : "Identifier, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addParentSubstanceId, setValue"} **/
						, substancesourcematerial.getSbstncSrcMtrlPrntSbstncdDntfrSstm() /** { "tree" :"SubstanceSourceMaterial.parentSubstanceId", "datatype" : "Identifier, uri", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addParentSubstanceId, setSystem"} **/
						));
Substancesourcematerialobj.addParentSubstanceName(HapiFHIRHelpers.createstring(substancesourcematerial.getSbstncSrcMtrlPrntSbstncNmStrng() /** { "tree" :"SubstanceSourceMaterial.parentSubstanceName", "datatype" : "string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addParentSubstanceName"} **/
						));
Substancesourcematerialobj.addCountryOfOrigin(HapiFHIRHelpers.createCodeableConcept(substancesourcematerial.getSbstncSrcMtrlCntrfrgnCcCdngCSstm() /** { "tree" :"SubstanceSourceMaterial.countryOfOrigin", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addCountryOfOrigin, addCoding, setSystem"} **/
						, substancesourcematerial.getSbstncSrcMtrlCntrfrgnCcCdngCVrsn() /** { "tree" :"SubstanceSourceMaterial.countryOfOrigin", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addCountryOfOrigin, addCoding, setVersion"} **/
						, substancesourcematerial.getSbstncSrcMtrlCntrfrgnCcCdngCCde() /** { "tree" :"SubstanceSourceMaterial.countryOfOrigin", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addCountryOfOrigin, addCoding, setCode"} **/
						, substancesourcematerial.getSbstncSrcMtrlCntrfrgnCcCdngCDsplay() /** { "tree" :"SubstanceSourceMaterial.countryOfOrigin", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addCountryOfOrigin, addCoding, setDisplay"} **/
						, substancesourcematerial.getSbstncSrcMtrlCntrfrgnCcCdngCSrSlctd() /** { "tree" :"SubstanceSourceMaterial.countryOfOrigin", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addCountryOfOrigin, addCoding, setUserSelected"} **/
						, substancesourcematerial.getSbstncSrcMtrlCntrfrgnCcTxt() /** { "tree" :"SubstanceSourceMaterial.countryOfOrigin", "datatype" : "CodeableConcept, string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addCountryOfOrigin, setText"} **/
						));
Substancesourcematerialobj.addGeographicalLocation(HapiFHIRHelpers.createstring(substancesourcematerial.getSbstncSrcMtrlGgrphclLctnStrng() /** { "tree" :"SubstanceSourceMaterial.geographicalLocation", "datatype" : "string", "cardinality" : "Many", "elementtree" : [] , "methodName" : "addGeographicalLocation"} **/
						));
Substancesourcematerialobj.setDevelopmentStage(HapiFHIRHelpers.createCodeableConcept(substancesourcematerial.getSbstncSrcMtrlDvlpmntStgCcCdngCSstm() /** { "tree" :"SubstanceSourceMaterial.developmentStage", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setDevelopmentStage, addCoding, setSystem"} **/
						, substancesourcematerial.getSbstncSrcMtrlDvlpmntStgCcCdngCVrsn() /** { "tree" :"SubstanceSourceMaterial.developmentStage", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setDevelopmentStage, addCoding, setVersion"} **/
						, substancesourcematerial.getSbstncSrcMtrlDvlpmntStgCcCdngCCde() /** { "tree" :"SubstanceSourceMaterial.developmentStage", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setDevelopmentStage, addCoding, setCode"} **/
						, substancesourcematerial.getSbstncSrcMtrlDvlpmntStgCcCdngCDsplay() /** { "tree" :"SubstanceSourceMaterial.developmentStage", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setDevelopmentStage, addCoding, setDisplay"} **/
						, substancesourcematerial.getSbstncSrcMtrlDvlpmntStgCcCdngCSrSlctd() /** { "tree" :"SubstanceSourceMaterial.developmentStage", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setDevelopmentStage, addCoding, setUserSelected"} **/
						, substancesourcematerial.getSbstncSrcMtrlDvlpmntStgCcTxt() /** { "tree" :"SubstanceSourceMaterial.developmentStage", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : [] , "methodName" : "setDevelopmentStage, setText"} **/
						));
Substancesourcematerialobj.setFraction(HapiFHIRHelpers.createstring(substancesourcematerial.getSbstncSrcMtrlFrctnDscrptnFrctnStrng() /** { "tree" :"SubstanceSourceMaterial.fractionDescription.fraction", "datatype" : "string", "cardinality" : "ZeroOne", "elementtree" : ["addFractionDescription"] , "methodName" : "setFraction"} **/
						));
Substancesourcematerialobj.setMaterialType(HapiFHIRHelpers.createCodeableConcept(substancesourcematerial.getSbstncSrcMtrlFrctnDscrptnMtrlTpCcCdngCSstm() /** { "tree" :"SubstanceSourceMaterial.fractionDescription.materialType", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : ["addFractionDescription"] , "methodName" : "setMaterialType, addCoding, setSystem"} **/
						, substancesourcematerial.getSbstncSrcMtrlFrctnDscrptnMtrlTpCcCdngCVrsn() /** { "tree" :"SubstanceSourceMaterial.fractionDescription.materialType", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addFractionDescription"] , "methodName" : "setMaterialType, addCoding, setVersion"} **/
						, substancesourcematerial.getSbstncSrcMtrlFrctnDscrptnMtrlTpCcCdngCCde() /** { "tree" :"SubstanceSourceMaterial.fractionDescription.materialType", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : ["addFractionDescription"] , "methodName" : "setMaterialType, addCoding, setCode"} **/
						, substancesourcematerial.getSbstncSrcMtrlFrctnDscrptnMtrlTpCcCdngCDsplay() /** { "tree" :"SubstanceSourceMaterial.fractionDescription.materialType", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addFractionDescription"] , "methodName" : "setMaterialType, addCoding, setDisplay"} **/
						, substancesourcematerial.getSbstncSrcMtrlFrctnDscrptnMtrlTpCcCdngCSrSlctd() /** { "tree" :"SubstanceSourceMaterial.fractionDescription.materialType", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : ["addFractionDescription"] , "methodName" : "setMaterialType, addCoding, setUserSelected"} **/
						, substancesourcematerial.getSbstncSrcMtrlFrctnDscrptnMtrlTpCcTxt() /** { "tree" :"SubstanceSourceMaterial.fractionDescription.materialType", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : ["addFractionDescription"] , "methodName" : "setMaterialType, setText"} **/
						));
Substancesourcematerialobj.setFamily(HapiFHIRHelpers.createCodeableConcept(substancesourcematerial.getSbstncSrcMtrlRgnsmFmlCcCdngCSstm() /** { "tree" :"SubstanceSourceMaterial.organism.family", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : ["setOrganism"] , "methodName" : "setFamily, addCoding, setSystem"} **/
						, substancesourcematerial.getSbstncSrcMtrlRgnsmFmlCcCdngCVrsn() /** { "tree" :"SubstanceSourceMaterial.organism.family", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["setOrganism"] , "methodName" : "setFamily, addCoding, setVersion"} **/
						, substancesourcematerial.getSbstncSrcMtrlRgnsmFmlCcCdngCCde() /** { "tree" :"SubstanceSourceMaterial.organism.family", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : ["setOrganism"] , "methodName" : "setFamily, addCoding, setCode"} **/
						, substancesourcematerial.getSbstncSrcMtrlRgnsmFmlCcCdngCDsplay() /** { "tree" :"SubstanceSourceMaterial.organism.family", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["setOrganism"] , "methodName" : "setFamily, addCoding, setDisplay"} **/
						, substancesourcematerial.getSbstncSrcMtrlRgnsmFmlCcCdngCSrSlctd() /** { "tree" :"SubstanceSourceMaterial.organism.family", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : ["setOrganism"] , "methodName" : "setFamily, addCoding, setUserSelected"} **/
						, substancesourcematerial.getSbstncSrcMtrlRgnsmFmlCcTxt() /** { "tree" :"SubstanceSourceMaterial.organism.family", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : ["setOrganism"] , "methodName" : "setFamily, setText"} **/
						));
Substancesourcematerialobj.setGenus(HapiFHIRHelpers.createCodeableConcept(substancesourcematerial.getSbstncSrcMtrlRgnsmGnsCcCdngCSstm() /** { "tree" :"SubstanceSourceMaterial.organism.genus", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : ["setOrganism"] , "methodName" : "setGenus, addCoding, setSystem"} **/
						, substancesourcematerial.getSbstncSrcMtrlRgnsmGnsCcCdngCVrsn() /** { "tree" :"SubstanceSourceMaterial.organism.genus", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["setOrganism"] , "methodName" : "setGenus, addCoding, setVersion"} **/
						, substancesourcematerial.getSbstncSrcMtrlRgnsmGnsCcCdngCCde() /** { "tree" :"SubstanceSourceMaterial.organism.genus", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : ["setOrganism"] , "methodName" : "setGenus, addCoding, setCode"} **/
						, substancesourcematerial.getSbstncSrcMtrlRgnsmGnsCcCdngCDsplay() /** { "tree" :"SubstanceSourceMaterial.organism.genus", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["setOrganism"] , "methodName" : "setGenus, addCoding, setDisplay"} **/
						, substancesourcematerial.getSbstncSrcMtrlRgnsmGnsCcCdngCSrSlctd() /** { "tree" :"SubstanceSourceMaterial.organism.genus", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : ["setOrganism"] , "methodName" : "setGenus, addCoding, setUserSelected"} **/
						, substancesourcematerial.getSbstncSrcMtrlRgnsmGnsCcTxt() /** { "tree" :"SubstanceSourceMaterial.organism.genus", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : ["setOrganism"] , "methodName" : "setGenus, setText"} **/
						));
Substancesourcematerialobj.setSpecies(HapiFHIRHelpers.createCodeableConcept(substancesourcematerial.getSbstncSrcMtrlRgnsmSpcsCcCdngCSstm() /** { "tree" :"SubstanceSourceMaterial.organism.species", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : ["setOrganism"] , "methodName" : "setSpecies, addCoding, setSystem"} **/
						, substancesourcematerial.getSbstncSrcMtrlRgnsmSpcsCcCdngCVrsn() /** { "tree" :"SubstanceSourceMaterial.organism.species", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["setOrganism"] , "methodName" : "setSpecies, addCoding, setVersion"} **/
						, substancesourcematerial.getSbstncSrcMtrlRgnsmSpcsCcCdngCCde() /** { "tree" :"SubstanceSourceMaterial.organism.species", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : ["setOrganism"] , "methodName" : "setSpecies, addCoding, setCode"} **/
						, substancesourcematerial.getSbstncSrcMtrlRgnsmSpcsCcCdngCDsplay() /** { "tree" :"SubstanceSourceMaterial.organism.species", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["setOrganism"] , "methodName" : "setSpecies, addCoding, setDisplay"} **/
						, substancesourcematerial.getSbstncSrcMtrlRgnsmSpcsCcCdngCSrSlctd() /** { "tree" :"SubstanceSourceMaterial.organism.species", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : ["setOrganism"] , "methodName" : "setSpecies, addCoding, setUserSelected"} **/
						, substancesourcematerial.getSbstncSrcMtrlRgnsmSpcsCcTxt() /** { "tree" :"SubstanceSourceMaterial.organism.species", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : ["setOrganism"] , "methodName" : "setSpecies, setText"} **/
						));
Substancesourcematerialobj.setIntraspecificType(HapiFHIRHelpers.createCodeableConcept(substancesourcematerial.getSbstncSrcMtrlRgnsmNtrspcfcTpCcCdngCSstm() /** { "tree" :"SubstanceSourceMaterial.organism.intraspecificType", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : ["setOrganism"] , "methodName" : "setIntraspecificType, addCoding, setSystem"} **/
						, substancesourcematerial.getSbstncSrcMtrlRgnsmNtrspcfcTpCcCdngCVrsn() /** { "tree" :"SubstanceSourceMaterial.organism.intraspecificType", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["setOrganism"] , "methodName" : "setIntraspecificType, addCoding, setVersion"} **/
						, substancesourcematerial.getSbstncSrcMtrlRgnsmNtrspcfcTpCcCdngCCde() /** { "tree" :"SubstanceSourceMaterial.organism.intraspecificType", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : ["setOrganism"] , "methodName" : "setIntraspecificType, addCoding, setCode"} **/
						, substancesourcematerial.getSbstncSrcMtrlRgnsmNtrspcfcTpCcCdngCDsplay() /** { "tree" :"SubstanceSourceMaterial.organism.intraspecificType", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["setOrganism"] , "methodName" : "setIntraspecificType, addCoding, setDisplay"} **/
						, substancesourcematerial.getSbstncSrcMtrlRgnsmNtrspcfcTpCcCdngCSrSlctd() /** { "tree" :"SubstanceSourceMaterial.organism.intraspecificType", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : ["setOrganism"] , "methodName" : "setIntraspecificType, addCoding, setUserSelected"} **/
						, substancesourcematerial.getSbstncSrcMtrlRgnsmNtrspcfcTpCcTxt() /** { "tree" :"SubstanceSourceMaterial.organism.intraspecificType", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : ["setOrganism"] , "methodName" : "setIntraspecificType, setText"} **/
						));
Substancesourcematerialobj.setIntraspecificDescription(HapiFHIRHelpers.createstring(substancesourcematerial.getSbstncSrcMtrlRgnsmNtrspcfcDscrptnStrng() /** { "tree" :"SubstanceSourceMaterial.organism.intraspecificDescription", "datatype" : "string", "cardinality" : "ZeroOne", "elementtree" : ["setOrganism"] , "methodName" : "setIntraspecificDescription"} **/
						));
Substancesourcematerialobj.setAuthorType(HapiFHIRHelpers.createCodeableConcept(substancesourcematerial.getSbstncSrcMtrlRgnsmThrThrTpCcCdngCSstm() /** { "tree" :"SubstanceSourceMaterial.organism.author.authorType", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : ["setOrganism", "addAuthor"] , "methodName" : "setAuthorType, addCoding, setSystem"} **/
						, substancesourcematerial.getSbstncSrcMtrlRgnsmThrThrTpCcCdngCVrsn() /** { "tree" :"SubstanceSourceMaterial.organism.author.authorType", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["setOrganism", "addAuthor"] , "methodName" : "setAuthorType, addCoding, setVersion"} **/
						, substancesourcematerial.getSbstncSrcMtrlRgnsmThrThrTpCcCdngCCde() /** { "tree" :"SubstanceSourceMaterial.organism.author.authorType", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : ["setOrganism", "addAuthor"] , "methodName" : "setAuthorType, addCoding, setCode"} **/
						, substancesourcematerial.getSbstncSrcMtrlRgnsmThrThrTpCcCdngCDsplay() /** { "tree" :"SubstanceSourceMaterial.organism.author.authorType", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["setOrganism", "addAuthor"] , "methodName" : "setAuthorType, addCoding, setDisplay"} **/
						, substancesourcematerial.getSbstncSrcMtrlRgnsmThrThrTpCcCdngCSrSlctd() /** { "tree" :"SubstanceSourceMaterial.organism.author.authorType", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : ["setOrganism", "addAuthor"] , "methodName" : "setAuthorType, addCoding, setUserSelected"} **/
						, substancesourcematerial.getSbstncSrcMtrlRgnsmThrThrTpCcTxt() /** { "tree" :"SubstanceSourceMaterial.organism.author.authorType", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : ["setOrganism", "addAuthor"] , "methodName" : "setAuthorType, setText"} **/
						));
Substancesourcematerialobj.setAuthorDescription(HapiFHIRHelpers.createstring(substancesourcematerial.getSbstncSrcMtrlRgnsmThrThrDscrptnStrng() /** { "tree" :"SubstanceSourceMaterial.organism.author.authorDescription", "datatype" : "string", "cardinality" : "ZeroOne", "elementtree" : ["setOrganism", "addAuthor"] , "methodName" : "setAuthorDescription"} **/
						));
Substancesourcematerialobj.setMaternalOrganismId(HapiFHIRHelpers.createstring(substancesourcematerial.getSbstncSrcMtrlRgnsmHbrdMtrnlrgnsmdStrng() /** { "tree" :"SubstanceSourceMaterial.organism.hybrid.maternalOrganismId", "datatype" : "string", "cardinality" : "ZeroOne", "elementtree" : ["setOrganism", "addAuthor", "setHybrid"] , "methodName" : "setMaternalOrganismId"} **/
						));
Substancesourcematerialobj.setMaternalOrganismName(HapiFHIRHelpers.createstring(substancesourcematerial.getSbstncSrcMtrlRgnsmHbrdMtrnlrgnsmNmStrng() /** { "tree" :"SubstanceSourceMaterial.organism.hybrid.maternalOrganismName", "datatype" : "string", "cardinality" : "ZeroOne", "elementtree" : ["setOrganism", "addAuthor", "setHybrid"] , "methodName" : "setMaternalOrganismName"} **/
						));
Substancesourcematerialobj.setPaternalOrganismId(HapiFHIRHelpers.createstring(substancesourcematerial.getSbstncSrcMtrlRgnsmHbrdPtrnlrgnsmdStrng() /** { "tree" :"SubstanceSourceMaterial.organism.hybrid.paternalOrganismId", "datatype" : "string", "cardinality" : "ZeroOne", "elementtree" : ["setOrganism", "addAuthor", "setHybrid"] , "methodName" : "setPaternalOrganismId"} **/
						));
Substancesourcematerialobj.setPaternalOrganismName(HapiFHIRHelpers.createstring(substancesourcematerial.getSbstncSrcMtrlRgnsmHbrdPtrnlrgnsmNmStrng() /** { "tree" :"SubstanceSourceMaterial.organism.hybrid.paternalOrganismName", "datatype" : "string", "cardinality" : "ZeroOne", "elementtree" : ["setOrganism", "addAuthor", "setHybrid"] , "methodName" : "setPaternalOrganismName"} **/
						));
Substancesourcematerialobj.setHybridType(HapiFHIRHelpers.createCodeableConcept(substancesourcematerial.getSbstncSrcMtrlRgnsmHbrdHbrdTpCcCdngCSstm() /** { "tree" :"SubstanceSourceMaterial.organism.hybrid.hybridType", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : ["setOrganism", "addAuthor", "setHybrid"] , "methodName" : "setHybridType, addCoding, setSystem"} **/
						, substancesourcematerial.getSbstncSrcMtrlRgnsmHbrdHbrdTpCcCdngCVrsn() /** { "tree" :"SubstanceSourceMaterial.organism.hybrid.hybridType", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["setOrganism", "addAuthor", "setHybrid"] , "methodName" : "setHybridType, addCoding, setVersion"} **/
						, substancesourcematerial.getSbstncSrcMtrlRgnsmHbrdHbrdTpCcCdngCCde() /** { "tree" :"SubstanceSourceMaterial.organism.hybrid.hybridType", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : ["setOrganism", "addAuthor", "setHybrid"] , "methodName" : "setHybridType, addCoding, setCode"} **/
						, substancesourcematerial.getSbstncSrcMtrlRgnsmHbrdHbrdTpCcCdngCDsplay() /** { "tree" :"SubstanceSourceMaterial.organism.hybrid.hybridType", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["setOrganism", "addAuthor", "setHybrid"] , "methodName" : "setHybridType, addCoding, setDisplay"} **/
						, substancesourcematerial.getSbstncSrcMtrlRgnsmHbrdHbrdTpCcCdngCSrSlctd() /** { "tree" :"SubstanceSourceMaterial.organism.hybrid.hybridType", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : ["setOrganism", "addAuthor", "setHybrid"] , "methodName" : "setHybridType, addCoding, setUserSelected"} **/
						, substancesourcematerial.getSbstncSrcMtrlRgnsmHbrdHbrdTpCcTxt() /** { "tree" :"SubstanceSourceMaterial.organism.hybrid.hybridType", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : ["setOrganism", "addAuthor", "setHybrid"] , "methodName" : "setHybridType, setText"} **/
						));
Substancesourcematerialobj.setKingdom(HapiFHIRHelpers.createCodeableConcept(substancesourcematerial.getSbstncSrcMtrlRgnsmRgnsmGnrlKngdmCcCdngCSstm() /** { "tree" :"SubstanceSourceMaterial.organism.organismGeneral.kingdom", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : ["setOrganism", "addAuthor", "setHybrid", "setOrganismGeneral"] , "methodName" : "setKingdom, addCoding, setSystem"} **/
						, substancesourcematerial.getSbstncSrcMtrlRgnsmRgnsmGnrlKngdmCcCdngCVrsn() /** { "tree" :"SubstanceSourceMaterial.organism.organismGeneral.kingdom", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["setOrganism", "addAuthor", "setHybrid", "setOrganismGeneral"] , "methodName" : "setKingdom, addCoding, setVersion"} **/
						, substancesourcematerial.getSbstncSrcMtrlRgnsmRgnsmGnrlKngdmCcCdngCCde() /** { "tree" :"SubstanceSourceMaterial.organism.organismGeneral.kingdom", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : ["setOrganism", "addAuthor", "setHybrid", "setOrganismGeneral"] , "methodName" : "setKingdom, addCoding, setCode"} **/
						, substancesourcematerial.getSbstncSrcMtrlRgnsmRgnsmGnrlKngdmCcCdngCDsplay() /** { "tree" :"SubstanceSourceMaterial.organism.organismGeneral.kingdom", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["setOrganism", "addAuthor", "setHybrid", "setOrganismGeneral"] , "methodName" : "setKingdom, addCoding, setDisplay"} **/
						, substancesourcematerial.getSbstncSrcMtrlRgnsmRgnsmGnrlKngdmCcCdngCSrSlctd() /** { "tree" :"SubstanceSourceMaterial.organism.organismGeneral.kingdom", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : ["setOrganism", "addAuthor", "setHybrid", "setOrganismGeneral"] , "methodName" : "setKingdom, addCoding, setUserSelected"} **/
						, substancesourcematerial.getSbstncSrcMtrlRgnsmRgnsmGnrlKngdmCcTxt() /** { "tree" :"SubstanceSourceMaterial.organism.organismGeneral.kingdom", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : ["setOrganism", "addAuthor", "setHybrid", "setOrganismGeneral"] , "methodName" : "setKingdom, setText"} **/
						));
Substancesourcematerialobj.setPhylum(HapiFHIRHelpers.createCodeableConcept(substancesourcematerial.getSbstncSrcMtrlRgnsmRgnsmGnrlPhlmCcCdngCSstm() /** { "tree" :"SubstanceSourceMaterial.organism.organismGeneral.phylum", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : ["setOrganism", "addAuthor", "setHybrid", "setOrganismGeneral"] , "methodName" : "setPhylum, addCoding, setSystem"} **/
						, substancesourcematerial.getSbstncSrcMtrlRgnsmRgnsmGnrlPhlmCcCdngCVrsn() /** { "tree" :"SubstanceSourceMaterial.organism.organismGeneral.phylum", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["setOrganism", "addAuthor", "setHybrid", "setOrganismGeneral"] , "methodName" : "setPhylum, addCoding, setVersion"} **/
						, substancesourcematerial.getSbstncSrcMtrlRgnsmRgnsmGnrlPhlmCcCdngCCde() /** { "tree" :"SubstanceSourceMaterial.organism.organismGeneral.phylum", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : ["setOrganism", "addAuthor", "setHybrid", "setOrganismGeneral"] , "methodName" : "setPhylum, addCoding, setCode"} **/
						, substancesourcematerial.getSbstncSrcMtrlRgnsmRgnsmGnrlPhlmCcCdngCDsplay() /** { "tree" :"SubstanceSourceMaterial.organism.organismGeneral.phylum", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["setOrganism", "addAuthor", "setHybrid", "setOrganismGeneral"] , "methodName" : "setPhylum, addCoding, setDisplay"} **/
						, substancesourcematerial.getSbstncSrcMtrlRgnsmRgnsmGnrlPhlmCcCdngCSrSlctd() /** { "tree" :"SubstanceSourceMaterial.organism.organismGeneral.phylum", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : ["setOrganism", "addAuthor", "setHybrid", "setOrganismGeneral"] , "methodName" : "setPhylum, addCoding, setUserSelected"} **/
						, substancesourcematerial.getSbstncSrcMtrlRgnsmRgnsmGnrlPhlmCcTxt() /** { "tree" :"SubstanceSourceMaterial.organism.organismGeneral.phylum", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : ["setOrganism", "addAuthor", "setHybrid", "setOrganismGeneral"] , "methodName" : "setPhylum, setText"} **/
						));
Substancesourcematerialobj.setClass(HapiFHIRHelpers.createCodeableConcept(substancesourcematerial.getSbstncSrcMtrlRgnsmRgnsmGnrlClssCcCdngCSstm() /** { "tree" :"SubstanceSourceMaterial.organism.organismGeneral.class", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : ["setOrganism", "addAuthor", "setHybrid", "setOrganismGeneral"] , "methodName" : "setClass, addCoding, setSystem"} **/
						, substancesourcematerial.getSbstncSrcMtrlRgnsmRgnsmGnrlClssCcCdngCVrsn() /** { "tree" :"SubstanceSourceMaterial.organism.organismGeneral.class", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["setOrganism", "addAuthor", "setHybrid", "setOrganismGeneral"] , "methodName" : "setClass, addCoding, setVersion"} **/
						, substancesourcematerial.getSbstncSrcMtrlRgnsmRgnsmGnrlClssCcCdngCCde() /** { "tree" :"SubstanceSourceMaterial.organism.organismGeneral.class", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : ["setOrganism", "addAuthor", "setHybrid", "setOrganismGeneral"] , "methodName" : "setClass, addCoding, setCode"} **/
						, substancesourcematerial.getSbstncSrcMtrlRgnsmRgnsmGnrlClssCcCdngCDsplay() /** { "tree" :"SubstanceSourceMaterial.organism.organismGeneral.class", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["setOrganism", "addAuthor", "setHybrid", "setOrganismGeneral"] , "methodName" : "setClass, addCoding, setDisplay"} **/
						, substancesourcematerial.getSbstncSrcMtrlRgnsmRgnsmGnrlClssCcCdngCSrSlctd() /** { "tree" :"SubstanceSourceMaterial.organism.organismGeneral.class", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : ["setOrganism", "addAuthor", "setHybrid", "setOrganismGeneral"] , "methodName" : "setClass, addCoding, setUserSelected"} **/
						, substancesourcematerial.getSbstncSrcMtrlRgnsmRgnsmGnrlClssCcTxt() /** { "tree" :"SubstanceSourceMaterial.organism.organismGeneral.class", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : ["setOrganism", "addAuthor", "setHybrid", "setOrganismGeneral"] , "methodName" : "setClass, setText"} **/
						));
Substancesourcematerialobj.setOrder(HapiFHIRHelpers.createCodeableConcept(substancesourcematerial.getSbstncSrcMtrlRgnsmRgnsmGnrlRdrCcCdngCSstm() /** { "tree" :"SubstanceSourceMaterial.organism.organismGeneral.order", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : ["setOrganism", "addAuthor", "setHybrid", "setOrganismGeneral"] , "methodName" : "setOrder, addCoding, setSystem"} **/
						, substancesourcematerial.getSbstncSrcMtrlRgnsmRgnsmGnrlRdrCcCdngCVrsn() /** { "tree" :"SubstanceSourceMaterial.organism.organismGeneral.order", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["setOrganism", "addAuthor", "setHybrid", "setOrganismGeneral"] , "methodName" : "setOrder, addCoding, setVersion"} **/
						, substancesourcematerial.getSbstncSrcMtrlRgnsmRgnsmGnrlRdrCcCdngCCde() /** { "tree" :"SubstanceSourceMaterial.organism.organismGeneral.order", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : ["setOrganism", "addAuthor", "setHybrid", "setOrganismGeneral"] , "methodName" : "setOrder, addCoding, setCode"} **/
						, substancesourcematerial.getSbstncSrcMtrlRgnsmRgnsmGnrlRdrCcCdngCDsplay() /** { "tree" :"SubstanceSourceMaterial.organism.organismGeneral.order", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["setOrganism", "addAuthor", "setHybrid", "setOrganismGeneral"] , "methodName" : "setOrder, addCoding, setDisplay"} **/
						, substancesourcematerial.getSbstncSrcMtrlRgnsmRgnsmGnrlRdrCcCdngCSrSlctd() /** { "tree" :"SubstanceSourceMaterial.organism.organismGeneral.order", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : ["setOrganism", "addAuthor", "setHybrid", "setOrganismGeneral"] , "methodName" : "setOrder, addCoding, setUserSelected"} **/
						, substancesourcematerial.getSbstncSrcMtrlRgnsmRgnsmGnrlRdrCcTxt() /** { "tree" :"SubstanceSourceMaterial.organism.organismGeneral.order", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : ["setOrganism", "addAuthor", "setHybrid", "setOrganismGeneral"] , "methodName" : "setOrder, setText"} **/
						));
Substancesourcematerialobj.setPart(HapiFHIRHelpers.createCodeableConcept(substancesourcematerial.getSbstncSrcMtrlPrtDscrptnPrtCcCdngCSstm() /** { "tree" :"SubstanceSourceMaterial.partDescription.part", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : ["addPartDescription"] , "methodName" : "setPart, addCoding, setSystem"} **/
						, substancesourcematerial.getSbstncSrcMtrlPrtDscrptnPrtCcCdngCVrsn() /** { "tree" :"SubstanceSourceMaterial.partDescription.part", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addPartDescription"] , "methodName" : "setPart, addCoding, setVersion"} **/
						, substancesourcematerial.getSbstncSrcMtrlPrtDscrptnPrtCcCdngCCde() /** { "tree" :"SubstanceSourceMaterial.partDescription.part", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : ["addPartDescription"] , "methodName" : "setPart, addCoding, setCode"} **/
						, substancesourcematerial.getSbstncSrcMtrlPrtDscrptnPrtCcCdngCDsplay() /** { "tree" :"SubstanceSourceMaterial.partDescription.part", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addPartDescription"] , "methodName" : "setPart, addCoding, setDisplay"} **/
						, substancesourcematerial.getSbstncSrcMtrlPrtDscrptnPrtCcCdngCSrSlctd() /** { "tree" :"SubstanceSourceMaterial.partDescription.part", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : ["addPartDescription"] , "methodName" : "setPart, addCoding, setUserSelected"} **/
						, substancesourcematerial.getSbstncSrcMtrlPrtDscrptnPrtCcTxt() /** { "tree" :"SubstanceSourceMaterial.partDescription.part", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : ["addPartDescription"] , "methodName" : "setPart, setText"} **/
						));
Substancesourcematerialobj.setPartLocation(HapiFHIRHelpers.createCodeableConcept(substancesourcematerial.getSbstncSrcMtrlPrtDscrptnPrtLctnCcCdngCSstm() /** { "tree" :"SubstanceSourceMaterial.partDescription.partLocation", "datatype" : "CodeableConcept, Coding, uri", "cardinality" : "ZeroOne", "elementtree" : ["addPartDescription"] , "methodName" : "setPartLocation, addCoding, setSystem"} **/
						, substancesourcematerial.getSbstncSrcMtrlPrtDscrptnPrtLctnCcCdngCVrsn() /** { "tree" :"SubstanceSourceMaterial.partDescription.partLocation", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addPartDescription"] , "methodName" : "setPartLocation, addCoding, setVersion"} **/
						, substancesourcematerial.getSbstncSrcMtrlPrtDscrptnPrtLctnCcCdngCCde() /** { "tree" :"SubstanceSourceMaterial.partDescription.partLocation", "datatype" : "CodeableConcept, Coding, code", "cardinality" : "ZeroOne", "elementtree" : ["addPartDescription"] , "methodName" : "setPartLocation, addCoding, setCode"} **/
						, substancesourcematerial.getSbstncSrcMtrlPrtDscrptnPrtLctnCcCdngCDsplay() /** { "tree" :"SubstanceSourceMaterial.partDescription.partLocation", "datatype" : "CodeableConcept, Coding, string", "cardinality" : "ZeroOne", "elementtree" : ["addPartDescription"] , "methodName" : "setPartLocation, addCoding, setDisplay"} **/
						, substancesourcematerial.getSbstncSrcMtrlPrtDscrptnPrtLctnCcCdngCSrSlctd() /** { "tree" :"SubstanceSourceMaterial.partDescription.partLocation", "datatype" : "CodeableConcept, Coding, boolean", "cardinality" : "ZeroOne", "elementtree" : ["addPartDescription"] , "methodName" : "setPartLocation, addCoding, setUserSelected"} **/
						, substancesourcematerial.getSbstncSrcMtrlPrtDscrptnPrtLctnCcTxt() /** { "tree" :"SubstanceSourceMaterial.partDescription.partLocation", "datatype" : "CodeableConcept, string", "cardinality" : "ZeroOne", "elementtree" : ["addPartDescription"] , "methodName" : "setPartLocation, setText"} **/
		));
	}
}
