drop table if exists `Account`;
CREATE TABLE `Account` (
 id varchar(64),
Account_Cvg_Cvg TEXT COMMENT 'Account.Coverage.Coverage',
Account_Cvg_Priority TEXT COMMENT 'Account.Coverage.Priority',
Account_Dscrptn TEXT COMMENT 'Account.Description',
Account_Guarantor_OnHold TEXT COMMENT 'Account.Guarantor.OnHold',
Account_Guarantor_Party TEXT COMMENT 'Account.Guarantor.Party',
Account_Guarantor_Prd_End TEXT COMMENT 'Account.Guarantor.Period.End',
Account_Guarantor_Prd_Strt TEXT COMMENT 'Account.Guarantor.Period.Start',
Account_Id_Assigner TEXT COMMENT 'Account.Identifier.Assigner',
Account_Id_Prd_End TEXT COMMENT 'Account.Identifier.Period.End',
Account_Id_Prd_Strt TEXT COMMENT 'Account.Identifier.Period.Start',
Account_Id_Sys TEXT COMMENT 'Account.Identifier.System',
Account_Id_Typ_Cdg_Cd TEXT COMMENT 'Account.Identifier.Type.Coding.Code',
Account_Id_Typ_Cdg_Dsply TEXT COMMENT 'Account.Identifier.Type.Coding.Display',
Account_Id_Typ_Cdg_Sys TEXT COMMENT 'Account.Identifier.Type.Coding.System',
Account_Id_Typ_Cdg_UsrSltd TEXT COMMENT 'Account.Identifier.Type.Coding.UserSelected',
Account_Id_Typ_Cdg_Vrsn TEXT COMMENT 'Account.Identifier.Type.Coding.Version',
Account_Id_Typ_Txt TEXT COMMENT 'Account.Identifier.Type.Text',
Account_Id_Use TEXT COMMENT 'Account.Identifier.Use',
Account_Id_Vl TEXT COMMENT 'Account.Identifier.Value',
Account_Nm TEXT COMMENT 'Account.Name',
Account_Owner TEXT COMMENT 'Account.Owner',
Account_PartOf TEXT COMMENT 'Account.PartOf',
Account_SrvPrd_End TEXT COMMENT 'Account.ServicePeriod.End',
Account_SrvPrd_Strt TEXT COMMENT 'Account.ServicePeriod.Start',
Account_Sts TEXT COMMENT 'Account.Status',
Account_Sbjct TEXT COMMENT 'Account.Subject',
Account_Typ_Cdg_Cd TEXT COMMENT 'Account.Type.Coding.Code',
Account_Typ_Cdg_Dsply TEXT COMMENT 'Account.Type.Coding.Display',
Account_Typ_Cdg_Sys TEXT COMMENT 'Account.Type.Coding.System',
Account_Typ_Cdg_UsrSltd TEXT COMMENT 'Account.Type.Coding.UserSelected',
Account_Typ_Cdg_Vrsn TEXT COMMENT 'Account.Type.Coding.Version',
Account_Typ_Txt TEXT COMMENT 'Account.Type.Text',
PRIMARY KEY(id)) ENGINE=MyISAM
    ROW_FORMAT=COMPRESSED 
    KEY_BLOCK_SIZE=8;