drop table if exists `BodyStructure`;
CREATE TABLE `BodyStructure` (
 id varchar(64),
BodyStrctr_Active TEXT COMMENT 'BodyStructure.Active',
BodyStrctr_Dscrptn TEXT COMMENT 'BodyStructure.Description',
BodyStrctr_Id_Assigner TEXT COMMENT 'BodyStructure.Identifier.Assigner',
BodyStrctr_Id_Prd_End TEXT COMMENT 'BodyStructure.Identifier.Period.End',
BodyStrctr_Id_Prd_Strt TEXT COMMENT 'BodyStructure.Identifier.Period.Start',
BodyStrctr_Id_Sys TEXT COMMENT 'BodyStructure.Identifier.System',
BodyStrctr_Id_Typ_Cdg_Cd TEXT COMMENT 'BodyStructure.Identifier.Type.Coding.Code',
BodyStrctr_Id_Typ_Cdg_Dsply TEXT COMMENT 'BodyStructure.Identifier.Type.Coding.Display',
BodyStrctr_Id_Typ_Cdg_Sys TEXT COMMENT 'BodyStructure.Identifier.Type.Coding.System',
BodyStrctr_Id_Typ_Cdg_UsrSltd TEXT COMMENT 'BodyStructure.Identifier.Type.Coding.UserSelected',
BodyStrctr_Id_Typ_Cdg_Vrsn TEXT COMMENT 'BodyStructure.Identifier.Type.Coding.Version',
BodyStrctr_Id_Typ_Txt TEXT COMMENT 'BodyStructure.Identifier.Type.Text',
BodyStrctr_Id_Use TEXT COMMENT 'BodyStructure.Identifier.Use',
BodyStrctr_Id_Vl TEXT COMMENT 'BodyStructure.Identifier.Value',
BodyStrctr_Image_CntntTyp TEXT COMMENT 'BodyStructure.Image.ContentType',
BodyStrctr_Image_Creation TEXT COMMENT 'BodyStructure.Image.Creation',
BodyStrctr_Image_Data TEXT COMMENT 'BodyStructure.Image.Data',
BodyStrctr_Image_Hash TEXT COMMENT 'BodyStructure.Image.Hash',
BodyStrctr_Image_Lnguage TEXT COMMENT 'BodyStructure.Image.Language',
BodyStrctr_Image_Sz TEXT COMMENT 'BodyStructure.Image.Size',
BodyStrctr_Image_Ttl TEXT COMMENT 'BodyStructure.Image.Title',
BodyStrctr_Image_Url TEXT COMMENT 'BodyStructure.Image.Url',
BodyStrctr_Lctn_Cdg_Cd TEXT COMMENT 'BodyStructure.Location.Coding.Code',
BodyStrctr_Lctn_Cdg_Dsply TEXT COMMENT 'BodyStructure.Location.Coding.Display',
BodyStrctr_Lctn_Cdg_Sys TEXT COMMENT 'BodyStructure.Location.Coding.System',
BodyStrctr_Lctn_Cdg_UsrSltd TEXT COMMENT 'BodyStructure.Location.Coding.UserSelected',
BodyStrctr_Lctn_Cdg_Vrsn TEXT COMMENT 'BodyStructure.Location.Coding.Version',
BodyStrctr_Lctn_Txt TEXT COMMENT 'BodyStructure.Location.Text',
BodyStrctr_LctnQualifier_Cdg_Cd TEXT COMMENT 'BodyStructure.LocationQualifier.Coding.Code',
BodyStrctr_LctnQualifier_Cdg_Dsply TEXT COMMENT 'BodyStructure.LocationQualifier.Coding.Display',
BodyStrctr_LctnQualifier_Cdg_Sys TEXT COMMENT 'BodyStructure.LocationQualifier.Coding.System',
BodyStrctr_LctnQualifier_Cdg_UsrSltd TEXT COMMENT 'BodyStructure.LocationQualifier.Coding.UserSelected',
BodyStrctr_LctnQualifier_Cdg_Vrsn TEXT COMMENT 'BodyStructure.LocationQualifier.Coding.Version',
BodyStrctr_LctnQualifier_Txt TEXT COMMENT 'BodyStructure.LocationQualifier.Text',
BodyStrctr_Morphology_Cdg_Cd TEXT COMMENT 'BodyStructure.Morphology.Coding.Code',
BodyStrctr_Morphology_Cdg_Dsply TEXT COMMENT 'BodyStructure.Morphology.Coding.Display',
BodyStrctr_Morphology_Cdg_Sys TEXT COMMENT 'BodyStructure.Morphology.Coding.System',
BodyStrctr_Morphology_Cdg_UsrSltd TEXT COMMENT 'BodyStructure.Morphology.Coding.UserSelected',
BodyStrctr_Morphology_Cdg_Vrsn TEXT COMMENT 'BodyStructure.Morphology.Coding.Version',
BodyStrctr_Morphology_Txt TEXT COMMENT 'BodyStructure.Morphology.Text',
BodyStrctr_Pnt TEXT COMMENT 'BodyStructure.Patient',
PRIMARY KEY(id)) ENGINE=MyISAM
    ROW_FORMAT=COMPRESSED 
    KEY_BLOCK_SIZE=8;