drop table if exists `CareTeam`;
CREATE TABLE `CareTeam` (
 id varchar(64),
CareTeam_Ctgry_Cdg_Cd TEXT COMMENT 'CareTeam.Category.Coding.Code',
CareTeam_Ctgry_Cdg_Dsply TEXT COMMENT 'CareTeam.Category.Coding.Display',
CareTeam_Ctgry_Cdg_Sys TEXT COMMENT 'CareTeam.Category.Coding.System',
CareTeam_Ctgry_Cdg_UsrSltd TEXT COMMENT 'CareTeam.Category.Coding.UserSelected',
CareTeam_Ctgry_Cdg_Vrsn TEXT COMMENT 'CareTeam.Category.Coding.Version',
CareTeam_Ctgry_Txt TEXT COMMENT 'CareTeam.Category.Text',
CareTeam_Enc TEXT COMMENT 'CareTeam.Encounter',
CareTeam_Id_Assigner TEXT COMMENT 'CareTeam.Identifier.Assigner',
CareTeam_Id_Prd_End TEXT COMMENT 'CareTeam.Identifier.Period.End',
CareTeam_Id_Prd_Strt TEXT COMMENT 'CareTeam.Identifier.Period.Start',
CareTeam_Id_Sys TEXT COMMENT 'CareTeam.Identifier.System',
CareTeam_Id_Typ_Cdg_Cd TEXT COMMENT 'CareTeam.Identifier.Type.Coding.Code',
CareTeam_Id_Typ_Cdg_Dsply TEXT COMMENT 'CareTeam.Identifier.Type.Coding.Display',
CareTeam_Id_Typ_Cdg_Sys TEXT COMMENT 'CareTeam.Identifier.Type.Coding.System',
CareTeam_Id_Typ_Cdg_UsrSltd TEXT COMMENT 'CareTeam.Identifier.Type.Coding.UserSelected',
CareTeam_Id_Typ_Cdg_Vrsn TEXT COMMENT 'CareTeam.Identifier.Type.Coding.Version',
CareTeam_Id_Typ_Txt TEXT COMMENT 'CareTeam.Identifier.Type.Text',
CareTeam_Id_Use TEXT COMMENT 'CareTeam.Identifier.Use',
CareTeam_Id_Vl TEXT COMMENT 'CareTeam.Identifier.Value',
CareTeam_ManagingOrgnztn TEXT COMMENT 'CareTeam.ManagingOrganization',
CareTeam_Nm TEXT COMMENT 'CareTeam.Name',
CareTeam_Nt_AthrRfrnc TEXT COMMENT 'CareTeam.Note.AuthorReference',
CareTeam_Nt_AthrStrgTyp TEXT COMMENT 'CareTeam.Note.AuthorStringType',
CareTeam_Nt_Txt TEXT COMMENT 'CareTeam.Note.Text',
CareTeam_Nt_Time TEXT COMMENT 'CareTeam.Note.Time',
CareTeam_Prtcpnt_Mmbr TEXT COMMENT 'CareTeam.Participant.Member',
CareTeam_Prtcpnt_OnBehalfOf TEXT COMMENT 'CareTeam.Participant.OnBehalfOf',
CareTeam_Prtcpnt_Prd_End TEXT COMMENT 'CareTeam.Participant.Period.End',
CareTeam_Prtcpnt_Prd_Strt TEXT COMMENT 'CareTeam.Participant.Period.Start',
CareTeam_Prtcpnt_Role_Cdg_Cd TEXT COMMENT 'CareTeam.Participant.Role.Coding.Code',
CareTeam_Prtcpnt_Role_Cdg_Dsply TEXT COMMENT 'CareTeam.Participant.Role.Coding.Display',
CareTeam_Prtcpnt_Role_Cdg_Sys TEXT COMMENT 'CareTeam.Participant.Role.Coding.System',
CareTeam_Prtcpnt_Role_Cdg_UsrSltd TEXT COMMENT 'CareTeam.Participant.Role.Coding.UserSelected',
CareTeam_Prtcpnt_Role_Cdg_Vrsn TEXT COMMENT 'CareTeam.Participant.Role.Coding.Version',
CareTeam_Prtcpnt_Role_Txt TEXT COMMENT 'CareTeam.Participant.Role.Text',
CareTeam_Prd_End TEXT COMMENT 'CareTeam.Period.End',
CareTeam_Prd_Strt TEXT COMMENT 'CareTeam.Period.Start',
CareTeam_RsnCd_Cdg_Cd TEXT COMMENT 'CareTeam.ReasonCode.Coding.Code',
CareTeam_RsnCd_Cdg_Dsply TEXT COMMENT 'CareTeam.ReasonCode.Coding.Display',
CareTeam_RsnCd_Cdg_Sys TEXT COMMENT 'CareTeam.ReasonCode.Coding.System',
CareTeam_RsnCd_Cdg_UsrSltd TEXT COMMENT 'CareTeam.ReasonCode.Coding.UserSelected',
CareTeam_RsnCd_Cdg_Vrsn TEXT COMMENT 'CareTeam.ReasonCode.Coding.Version',
CareTeam_RsnCd_Txt TEXT COMMENT 'CareTeam.ReasonCode.Text',
CareTeam_RsnRfrnc TEXT COMMENT 'CareTeam.ReasonReference',
CareTeam_Sts TEXT COMMENT 'CareTeam.Status',
CareTeam_Sbjct TEXT COMMENT 'CareTeam.Subject',
CareTeam_Tlcm_Prd_End TEXT COMMENT 'CareTeam.Telecom.Period.End',
CareTeam_Tlcm_Prd_Strt TEXT COMMENT 'CareTeam.Telecom.Period.Start',
CareTeam_Tlcm_Rnk TEXT COMMENT 'CareTeam.Telecom.Rank',
CareTeam_Tlcm_Sys TEXT COMMENT 'CareTeam.Telecom.System',
CareTeam_Tlcm_Use TEXT COMMENT 'CareTeam.Telecom.Use',
CareTeam_Tlcm_Vl TEXT COMMENT 'CareTeam.Telecom.Value',
PRIMARY KEY(id)) ENGINE=MyISAM
    ROW_FORMAT=COMPRESSED 
    KEY_BLOCK_SIZE=8;