drop table if exists `CompartmentDefinition`;
CREATE TABLE `CompartmentDefinition` (
 id varchar(64),
CmprtmntDfn_Cd TEXT COMMENT 'CompartmentDefinition.Code',
CmprtmntDfn_Cntct_Nm TEXT COMMENT 'CompartmentDefinition.Contact.Name',
CmprtmntDfn_Cntct_Tlcm_Prd_End TEXT COMMENT 'CompartmentDefinition.Contact.Telecom.Period.End',
CmprtmntDfn_Cntct_Tlcm_Prd_Strt TEXT COMMENT 'CompartmentDefinition.Contact.Telecom.Period.Start',
CmprtmntDfn_Cntct_Tlcm_Rnk TEXT COMMENT 'CompartmentDefinition.Contact.Telecom.Rank',
CmprtmntDfn_Cntct_Tlcm_Sys TEXT COMMENT 'CompartmentDefinition.Contact.Telecom.System',
CmprtmntDfn_Cntct_Tlcm_Use TEXT COMMENT 'CompartmentDefinition.Contact.Telecom.Use',
CmprtmntDfn_Cntct_Tlcm_Vl TEXT COMMENT 'CompartmentDefinition.Contact.Telecom.Value',
CmprtmntDfn_Dt TEXT COMMENT 'CompartmentDefinition.Date',
CmprtmntDfn_Dscrptn TEXT COMMENT 'CompartmentDefinition.Description',
CmprtmntDfn_Exprmtl TEXT COMMENT 'CompartmentDefinition.Experimental',
CmprtmntDfn_Nm TEXT COMMENT 'CompartmentDefinition.Name',
CmprtmntDfn_Pblshr TEXT COMMENT 'CompartmentDefinition.Publisher',
CmprtmntDfn_Prpse TEXT COMMENT 'CompartmentDefinition.Purpose',
CmprtmntDfn_Rsrc_Cd TEXT COMMENT 'CompartmentDefinition.Resource.Code',
CmprtmntDfn_Rsrc_Docation TEXT COMMENT 'CompartmentDefinition.Resource.Documentation',
CmprtmntDfn_Rsrc_Param TEXT COMMENT 'CompartmentDefinition.Resource.Param',
CmprtmntDfn_Srch TEXT COMMENT 'CompartmentDefinition.Search',
CmprtmntDfn_Sts TEXT COMMENT 'CompartmentDefinition.Status',
CmprtmntDfn_Url TEXT COMMENT 'CompartmentDefinition.Url',
CmprtmntDfn_UseCntxt_Cd_Cd TEXT COMMENT 'CompartmentDefinition.UseContext.Code.Code',
CmprtmntDfn_UseCntxt_Cd_Dsply TEXT COMMENT 'CompartmentDefinition.UseContext.Code.Display',
CmprtmntDfn_UseCntxt_Cd_Sys TEXT COMMENT 'CompartmentDefinition.UseContext.Code.System',
CmprtmntDfn_UseCntxt_Cd_UsrSltd TEXT COMMENT 'CompartmentDefinition.UseContext.Code.UserSelected',
CmprtmntDfn_UseCntxt_Cd_Vrsn TEXT COMMENT 'CompartmentDefinition.UseContext.Code.Version',
CmprtmntDfn_UseCntxt_VlCdbleCncpt_Cdg_Cd TEXT COMMENT 'CompartmentDefinition.UseContext.ValueCodeableConcept.Coding.Code',
CmprtmntDfn_UseCntxt_VlCdbleCncpt_Cdg_Dsply TEXT COMMENT 'CompartmentDefinition.UseContext.ValueCodeableConcept.Coding.Display',
CmprtmntDfn_UseCntxt_VlCdbleCncpt_Cdg_Sys TEXT COMMENT 'CompartmentDefinition.UseContext.ValueCodeableConcept.Coding.System',
CmprtmntDfn_UseCntxt_VlCdbleCncpt_Cdg_UsrSltd TEXT COMMENT 'CompartmentDefinition.UseContext.ValueCodeableConcept.Coding.UserSelected',
CmprtmntDfn_UseCntxt_VlCdbleCncpt_Cdg_Vrsn TEXT COMMENT 'CompartmentDefinition.UseContext.ValueCodeableConcept.Coding.Version',
CmprtmntDfn_UseCntxt_VlCdbleCncpt_Txt TEXT COMMENT 'CompartmentDefinition.UseContext.ValueCodeableConcept.Text',
CmprtmntDfn_UseCntxt_VlQnty_Cd TEXT COMMENT 'CompartmentDefinition.UseContext.ValueQuantity.Code',
CmprtmntDfn_UseCntxt_VlQnty_Cmprtr TEXT COMMENT 'CompartmentDefinition.UseContext.ValueQuantity.Comparator',
CmprtmntDfn_UseCntxt_VlQnty_Sys TEXT COMMENT 'CompartmentDefinition.UseContext.ValueQuantity.System',
CmprtmntDfn_UseCntxt_VlQnty_Unt TEXT COMMENT 'CompartmentDefinition.UseContext.ValueQuantity.Unit',
CmprtmntDfn_UseCntxt_VlQnty_Vl TEXT COMMENT 'CompartmentDefinition.UseContext.ValueQuantity.Value',
CmprtmntDfn_UseCntxt_VlRng_Hi_Cd TEXT COMMENT 'CompartmentDefinition.UseContext.ValueRange.High.Code',
CmprtmntDfn_UseCntxt_VlRng_Hi_Cmprtr TEXT COMMENT 'CompartmentDefinition.UseContext.ValueRange.High.Comparator',
CmprtmntDfn_UseCntxt_VlRng_Hi_Sys TEXT COMMENT 'CompartmentDefinition.UseContext.ValueRange.High.System',
CmprtmntDfn_UseCntxt_VlRng_Hi_Unt TEXT COMMENT 'CompartmentDefinition.UseContext.ValueRange.High.Unit',
CmprtmntDfn_UseCntxt_VlRng_Hi_Vl TEXT COMMENT 'CompartmentDefinition.UseContext.ValueRange.High.Value',
CmprtmntDfn_UseCntxt_VlRng_Lw_Cd TEXT COMMENT 'CompartmentDefinition.UseContext.ValueRange.Low.Code',
CmprtmntDfn_UseCntxt_VlRng_Lw_Cmprtr TEXT COMMENT 'CompartmentDefinition.UseContext.ValueRange.Low.Comparator',
CmprtmntDfn_UseCntxt_VlRng_Lw_Sys TEXT COMMENT 'CompartmentDefinition.UseContext.ValueRange.Low.System',
CmprtmntDfn_UseCntxt_VlRng_Lw_Unt TEXT COMMENT 'CompartmentDefinition.UseContext.ValueRange.Low.Unit',
CmprtmntDfn_UseCntxt_VlRng_Lw_Vl TEXT COMMENT 'CompartmentDefinition.UseContext.ValueRange.Low.Value',
CmprtmntDfn_UseCntxt_VlRfrnc TEXT COMMENT 'CompartmentDefinition.UseContext.ValueReference',
CmprtmntDfn_Vrsn TEXT COMMENT 'CompartmentDefinition.Version',
PRIMARY KEY(id)) ENGINE=MyISAM
    ROW_FORMAT=COMPRESSED 
    KEY_BLOCK_SIZE=8;