drop table if exists `DetectedIssue`;
CREATE TABLE `DetectedIssue` (
 id varchar(64),
DetectedIssue_Athr TEXT COMMENT 'DetectedIssue.Author',
DetectedIssue_Cd_Cdg_Cd TEXT COMMENT 'DetectedIssue.Code.Coding.Code',
DetectedIssue_Cd_Cdg_Dsply TEXT COMMENT 'DetectedIssue.Code.Coding.Display',
DetectedIssue_Cd_Cdg_Sys TEXT COMMENT 'DetectedIssue.Code.Coding.System',
DetectedIssue_Cd_Cdg_UsrSltd TEXT COMMENT 'DetectedIssue.Code.Coding.UserSelected',
DetectedIssue_Cd_Cdg_Vrsn TEXT COMMENT 'DetectedIssue.Code.Coding.Version',
DetectedIssue_Cd_Txt TEXT COMMENT 'DetectedIssue.Code.Text',
DetectedIssue_Dtl TEXT COMMENT 'DetectedIssue.Detail',
DetectedIssue_Evdnce_Cd_Cdg_Cd TEXT COMMENT 'DetectedIssue.Evidence.Code.Coding.Code',
DetectedIssue_Evdnce_Cd_Cdg_Dsply TEXT COMMENT 'DetectedIssue.Evidence.Code.Coding.Display',
DetectedIssue_Evdnce_Cd_Cdg_Sys TEXT COMMENT 'DetectedIssue.Evidence.Code.Coding.System',
DetectedIssue_Evdnce_Cd_Cdg_UsrSltd TEXT COMMENT 'DetectedIssue.Evidence.Code.Coding.UserSelected',
DetectedIssue_Evdnce_Cd_Cdg_Vrsn TEXT COMMENT 'DetectedIssue.Evidence.Code.Coding.Version',
DetectedIssue_Evdnce_Cd_Txt TEXT COMMENT 'DetectedIssue.Evidence.Code.Text',
DetectedIssue_Evdnce_Dtl TEXT COMMENT 'DetectedIssue.Evidence.Detail',
DetectedIssue_IdentifiedDtTimeTyp TEXT COMMENT 'DetectedIssue.IdentifiedDateTimeType',
DetectedIssue_IdentifiedPrd_End TEXT COMMENT 'DetectedIssue.IdentifiedPeriod.End',
DetectedIssue_IdentifiedPrd_Strt TEXT COMMENT 'DetectedIssue.IdentifiedPeriod.Start',
DetectedIssue_Id_Assigner TEXT COMMENT 'DetectedIssue.Identifier.Assigner',
DetectedIssue_Id_Prd_End TEXT COMMENT 'DetectedIssue.Identifier.Period.End',
DetectedIssue_Id_Prd_Strt TEXT COMMENT 'DetectedIssue.Identifier.Period.Start',
DetectedIssue_Id_Sys TEXT COMMENT 'DetectedIssue.Identifier.System',
DetectedIssue_Id_Typ_Cdg_Cd TEXT COMMENT 'DetectedIssue.Identifier.Type.Coding.Code',
DetectedIssue_Id_Typ_Cdg_Dsply TEXT COMMENT 'DetectedIssue.Identifier.Type.Coding.Display',
DetectedIssue_Id_Typ_Cdg_Sys TEXT COMMENT 'DetectedIssue.Identifier.Type.Coding.System',
DetectedIssue_Id_Typ_Cdg_UsrSltd TEXT COMMENT 'DetectedIssue.Identifier.Type.Coding.UserSelected',
DetectedIssue_Id_Typ_Cdg_Vrsn TEXT COMMENT 'DetectedIssue.Identifier.Type.Coding.Version',
DetectedIssue_Id_Typ_Txt TEXT COMMENT 'DetectedIssue.Identifier.Type.Text',
DetectedIssue_Id_Use TEXT COMMENT 'DetectedIssue.Identifier.Use',
DetectedIssue_Id_Vl TEXT COMMENT 'DetectedIssue.Identifier.Value',
DetectedIssue_Implicated TEXT COMMENT 'DetectedIssue.Implicated',
DetectedIssue_Mitigation_Actn_Cdg_Cd TEXT COMMENT 'DetectedIssue.Mitigation.Action.Coding.Code',
DetectedIssue_Mitigation_Actn_Cdg_Dsply TEXT COMMENT 'DetectedIssue.Mitigation.Action.Coding.Display',
DetectedIssue_Mitigation_Actn_Cdg_Sys TEXT COMMENT 'DetectedIssue.Mitigation.Action.Coding.System',
DetectedIssue_Mitigation_Actn_Cdg_UsrSltd TEXT COMMENT 'DetectedIssue.Mitigation.Action.Coding.UserSelected',
DetectedIssue_Mitigation_Actn_Cdg_Vrsn TEXT COMMENT 'DetectedIssue.Mitigation.Action.Coding.Version',
DetectedIssue_Mitigation_Actn_Txt TEXT COMMENT 'DetectedIssue.Mitigation.Action.Text',
DetectedIssue_Mitigation_Athr TEXT COMMENT 'DetectedIssue.Mitigation.Author',
DetectedIssue_Mitigation_Dt TEXT COMMENT 'DetectedIssue.Mitigation.Date',
DetectedIssue_Pnt TEXT COMMENT 'DetectedIssue.Patient',
DetectedIssue_Rfrnc TEXT COMMENT 'DetectedIssue.Reference',
DetectedIssue_Severity TEXT COMMENT 'DetectedIssue.Severity',
DetectedIssue_Sts TEXT COMMENT 'DetectedIssue.Status',
PRIMARY KEY(id)) ENGINE=MyISAM
    ROW_FORMAT=COMPRESSED 
    KEY_BLOCK_SIZE=8;