drop table if exists `DocumentManifest`;
CREATE TABLE `DocumentManifest` (
 id varchar(64),
DocManifest_Athr TEXT COMMENT 'DocumentManifest.Author',
DocManifest_Cntnt TEXT COMMENT 'DocumentManifest.Content',
DocManifest_Created TEXT COMMENT 'DocumentManifest.Created',
DocManifest_Dscrptn TEXT COMMENT 'DocumentManifest.Description',
DocManifest_Id_Assigner TEXT COMMENT 'DocumentManifest.Identifier.Assigner',
DocManifest_Id_Prd_End TEXT COMMENT 'DocumentManifest.Identifier.Period.End',
DocManifest_Id_Prd_Strt TEXT COMMENT 'DocumentManifest.Identifier.Period.Start',
DocManifest_Id_Sys TEXT COMMENT 'DocumentManifest.Identifier.System',
DocManifest_Id_Typ_Cdg_Cd TEXT COMMENT 'DocumentManifest.Identifier.Type.Coding.Code',
DocManifest_Id_Typ_Cdg_Dsply TEXT COMMENT 'DocumentManifest.Identifier.Type.Coding.Display',
DocManifest_Id_Typ_Cdg_Sys TEXT COMMENT 'DocumentManifest.Identifier.Type.Coding.System',
DocManifest_Id_Typ_Cdg_UsrSltd TEXT COMMENT 'DocumentManifest.Identifier.Type.Coding.UserSelected',
DocManifest_Id_Typ_Cdg_Vrsn TEXT COMMENT 'DocumentManifest.Identifier.Type.Coding.Version',
DocManifest_Id_Typ_Txt TEXT COMMENT 'DocumentManifest.Identifier.Type.Text',
DocManifest_Id_Use TEXT COMMENT 'DocumentManifest.Identifier.Use',
DocManifest_Id_Vl TEXT COMMENT 'DocumentManifest.Identifier.Value',
DocManifest_MasterId_Assigner TEXT COMMENT 'DocumentManifest.MasterIdentifier.Assigner',
DocManifest_MasterId_Prd_End TEXT COMMENT 'DocumentManifest.MasterIdentifier.Period.End',
DocManifest_MasterId_Prd_Strt TEXT COMMENT 'DocumentManifest.MasterIdentifier.Period.Start',
DocManifest_MasterId_Sys TEXT COMMENT 'DocumentManifest.MasterIdentifier.System',
DocManifest_MasterId_Typ_Cdg_Cd TEXT COMMENT 'DocumentManifest.MasterIdentifier.Type.Coding.Code',
DocManifest_MasterId_Typ_Cdg_Dsply TEXT COMMENT 'DocumentManifest.MasterIdentifier.Type.Coding.Display',
DocManifest_MasterId_Typ_Cdg_Sys TEXT COMMENT 'DocumentManifest.MasterIdentifier.Type.Coding.System',
DocManifest_MasterId_Typ_Cdg_UsrSltd TEXT COMMENT 'DocumentManifest.MasterIdentifier.Type.Coding.UserSelected',
DocManifest_MasterId_Typ_Cdg_Vrsn TEXT COMMENT 'DocumentManifest.MasterIdentifier.Type.Coding.Version',
DocManifest_MasterId_Typ_Txt TEXT COMMENT 'DocumentManifest.MasterIdentifier.Type.Text',
DocManifest_MasterId_Use TEXT COMMENT 'DocumentManifest.MasterIdentifier.Use',
DocManifest_MasterId_Vl TEXT COMMENT 'DocumentManifest.MasterIdentifier.Value',
DocManifest_Recipient TEXT COMMENT 'DocumentManifest.Recipient',
DocManifest_Rlted_Id_Assigner TEXT COMMENT 'DocumentManifest.Related.Identifier.Assigner',
DocManifest_Rlted_Id_Prd_End TEXT COMMENT 'DocumentManifest.Related.Identifier.Period.End',
DocManifest_Rlted_Id_Prd_Strt TEXT COMMENT 'DocumentManifest.Related.Identifier.Period.Start',
DocManifest_Rlted_Id_Sys TEXT COMMENT 'DocumentManifest.Related.Identifier.System',
DocManifest_Rlted_Id_Typ_Cdg_Cd TEXT COMMENT 'DocumentManifest.Related.Identifier.Type.Coding.Code',
DocManifest_Rlted_Id_Typ_Cdg_Dsply TEXT COMMENT 'DocumentManifest.Related.Identifier.Type.Coding.Display',
DocManifest_Rlted_Id_Typ_Cdg_Sys TEXT COMMENT 'DocumentManifest.Related.Identifier.Type.Coding.System',
DocManifest_Rlted_Id_Typ_Cdg_UsrSltd TEXT COMMENT 'DocumentManifest.Related.Identifier.Type.Coding.UserSelected',
DocManifest_Rlted_Id_Typ_Cdg_Vrsn TEXT COMMENT 'DocumentManifest.Related.Identifier.Type.Coding.Version',
DocManifest_Rlted_Id_Typ_Txt TEXT COMMENT 'DocumentManifest.Related.Identifier.Type.Text',
DocManifest_Rlted_Id_Use TEXT COMMENT 'DocumentManifest.Related.Identifier.Use',
DocManifest_Rlted_Id_Vl TEXT COMMENT 'DocumentManifest.Related.Identifier.Value',
DocManifest_Rlted_Ref TEXT COMMENT 'DocumentManifest.Related.Ref',
DocManifest_Src TEXT COMMENT 'DocumentManifest.Source',
DocManifest_Sts TEXT COMMENT 'DocumentManifest.Status',
DocManifest_Sbjct TEXT COMMENT 'DocumentManifest.Subject',
DocManifest_Typ_Cdg_Cd TEXT COMMENT 'DocumentManifest.Type.Coding.Code',
DocManifest_Typ_Cdg_Dsply TEXT COMMENT 'DocumentManifest.Type.Coding.Display',
DocManifest_Typ_Cdg_Sys TEXT COMMENT 'DocumentManifest.Type.Coding.System',
DocManifest_Typ_Cdg_UsrSltd TEXT COMMENT 'DocumentManifest.Type.Coding.UserSelected',
DocManifest_Typ_Cdg_Vrsn TEXT COMMENT 'DocumentManifest.Type.Coding.Version',
DocManifest_Typ_Txt TEXT COMMENT 'DocumentManifest.Type.Text',
PRIMARY KEY(id)) ENGINE=MyISAM
    ROW_FORMAT=COMPRESSED 
    KEY_BLOCK_SIZE=8;