drop table if exists `Endpoint`;
CREATE TABLE `Endpoint` (
 id varchar(64),
Endpoint_Addr TEXT COMMENT 'Endpoint.Address',
Endpoint_ConnectionTyp_Cd TEXT COMMENT 'Endpoint.ConnectionType.Code',
Endpoint_ConnectionTyp_Dsply TEXT COMMENT 'Endpoint.ConnectionType.Display',
Endpoint_ConnectionTyp_Sys TEXT COMMENT 'Endpoint.ConnectionType.System',
Endpoint_ConnectionTyp_UsrSltd TEXT COMMENT 'Endpoint.ConnectionType.UserSelected',
Endpoint_ConnectionTyp_Vrsn TEXT COMMENT 'Endpoint.ConnectionType.Version',
Endpoint_Cntct_Prd_End TEXT COMMENT 'Endpoint.Contact.Period.End',
Endpoint_Cntct_Prd_Strt TEXT COMMENT 'Endpoint.Contact.Period.Start',
Endpoint_Cntct_Rnk TEXT COMMENT 'Endpoint.Contact.Rank',
Endpoint_Cntct_Sys TEXT COMMENT 'Endpoint.Contact.System',
Endpoint_Cntct_Use TEXT COMMENT 'Endpoint.Contact.Use',
Endpoint_Cntct_Vl TEXT COMMENT 'Endpoint.Contact.Value',
Endpoint_Header TEXT COMMENT 'Endpoint.Header',
Endpoint_Id_Assigner TEXT COMMENT 'Endpoint.Identifier.Assigner',
Endpoint_Id_Prd_End TEXT COMMENT 'Endpoint.Identifier.Period.End',
Endpoint_Id_Prd_Strt TEXT COMMENT 'Endpoint.Identifier.Period.Start',
Endpoint_Id_Sys TEXT COMMENT 'Endpoint.Identifier.System',
Endpoint_Id_Typ_Cdg_Cd TEXT COMMENT 'Endpoint.Identifier.Type.Coding.Code',
Endpoint_Id_Typ_Cdg_Dsply TEXT COMMENT 'Endpoint.Identifier.Type.Coding.Display',
Endpoint_Id_Typ_Cdg_Sys TEXT COMMENT 'Endpoint.Identifier.Type.Coding.System',
Endpoint_Id_Typ_Cdg_UsrSltd TEXT COMMENT 'Endpoint.Identifier.Type.Coding.UserSelected',
Endpoint_Id_Typ_Cdg_Vrsn TEXT COMMENT 'Endpoint.Identifier.Type.Coding.Version',
Endpoint_Id_Typ_Txt TEXT COMMENT 'Endpoint.Identifier.Type.Text',
Endpoint_Id_Use TEXT COMMENT 'Endpoint.Identifier.Use',
Endpoint_Id_Vl TEXT COMMENT 'Endpoint.Identifier.Value',
Endpoint_ManagingOrgnztn TEXT COMMENT 'Endpoint.ManagingOrganization',
Endpoint_Nm TEXT COMMENT 'Endpoint.Name',
Endpoint_PayloadMimeTyp TEXT COMMENT 'Endpoint.PayloadMimeType',
Endpoint_PayloadTyp_Cdg_Cd TEXT COMMENT 'Endpoint.PayloadType.Coding.Code',
Endpoint_PayloadTyp_Cdg_Dsply TEXT COMMENT 'Endpoint.PayloadType.Coding.Display',
Endpoint_PayloadTyp_Cdg_Sys TEXT COMMENT 'Endpoint.PayloadType.Coding.System',
Endpoint_PayloadTyp_Cdg_UsrSltd TEXT COMMENT 'Endpoint.PayloadType.Coding.UserSelected',
Endpoint_PayloadTyp_Cdg_Vrsn TEXT COMMENT 'Endpoint.PayloadType.Coding.Version',
Endpoint_PayloadTyp_Txt TEXT COMMENT 'Endpoint.PayloadType.Text',
Endpoint_Prd_End TEXT COMMENT 'Endpoint.Period.End',
Endpoint_Prd_Strt TEXT COMMENT 'Endpoint.Period.Start',
Endpoint_Sts TEXT COMMENT 'Endpoint.Status',
PRIMARY KEY(id)) ENGINE=MyISAM
    ROW_FORMAT=COMPRESSED 
    KEY_BLOCK_SIZE=8;