drop table if exists `Endpoint`;
CREATE TABLE `Endpoint` (
 id varchar(64),
Endpoint_Addr TEXT,
Endpoint_ConnectionTyp_Cd TEXT,
Endpoint_ConnectionTyp_Dsply TEXT,
Endpoint_ConnectionTyp_Sys TEXT,
Endpoint_ConnectionTyp_UsrSltd TEXT,
Endpoint_ConnectionTyp_Vrsn TEXT,
Endpoint_Cntct_Prd_End TEXT,
Endpoint_Cntct_Prd_Strt TEXT,
Endpoint_Cntct_Rnk TEXT,
Endpoint_Cntct_Sys TEXT,
Endpoint_Cntct_Use TEXT,
Endpoint_Cntct_Vl TEXT,
Endpoint_Header TEXT,
Endpoint_Id_Assigner TEXT,
Endpoint_Id_Prd_End TEXT,
Endpoint_Id_Prd_Strt TEXT,
Endpoint_Id_Sys TEXT,
Endpoint_Id_Typ_Cdg_Cd TEXT,
Endpoint_Id_Typ_Cdg_Dsply TEXT,
Endpoint_Id_Typ_Cdg_Sys TEXT,
Endpoint_Id_Typ_Cdg_UsrSltd TEXT,
Endpoint_Id_Typ_Cdg_Vrsn TEXT,
Endpoint_Id_Typ_Txt TEXT,
Endpoint_Id_Use TEXT,
Endpoint_Id_Vl TEXT,
Endpoint_ManagingOrgnztn TEXT,
Endpoint_Nm TEXT,
Endpoint_PayloadMimeTyp TEXT,
Endpoint_PayloadTyp_Cdg_Cd TEXT,
Endpoint_PayloadTyp_Cdg_Dsply TEXT,
Endpoint_PayloadTyp_Cdg_Sys TEXT,
Endpoint_PayloadTyp_Cdg_UsrSltd TEXT,
Endpoint_PayloadTyp_Cdg_Vrsn TEXT,
Endpoint_PayloadTyp_Txt TEXT,
Endpoint_Prd_End TEXT,
Endpoint_Prd_Strt TEXT,
Endpoint_Sts TEXT,
PRIMARY KEY(id)) ENGINE=MyISAM
    ROW_FORMAT=COMPRESSED 
    KEY_BLOCK_SIZE=8;