drop table if exists `EpisodeOfCare`;
CREATE TABLE `EpisodeOfCare` (
 id varchar(64),
EpisodeOfCare_Account TEXT COMMENT 'EpisodeOfCare.Account',
EpisodeOfCare_CareManager TEXT COMMENT 'EpisodeOfCare.CareManager',
EpisodeOfCare_Dgnsis_Cndtn TEXT COMMENT 'EpisodeOfCare.Diagnosis.Condition',
EpisodeOfCare_Dgnsis_Rnk TEXT COMMENT 'EpisodeOfCare.Diagnosis.Rank',
EpisodeOfCare_Dgnsis_Role_Cdg_Cd TEXT COMMENT 'EpisodeOfCare.Diagnosis.Role.Coding.Code',
EpisodeOfCare_Dgnsis_Role_Cdg_Dsply TEXT COMMENT 'EpisodeOfCare.Diagnosis.Role.Coding.Display',
EpisodeOfCare_Dgnsis_Role_Cdg_Sys TEXT COMMENT 'EpisodeOfCare.Diagnosis.Role.Coding.System',
EpisodeOfCare_Dgnsis_Role_Cdg_UsrSltd TEXT COMMENT 'EpisodeOfCare.Diagnosis.Role.Coding.UserSelected',
EpisodeOfCare_Dgnsis_Role_Cdg_Vrsn TEXT COMMENT 'EpisodeOfCare.Diagnosis.Role.Coding.Version',
EpisodeOfCare_Dgnsis_Role_Txt TEXT COMMENT 'EpisodeOfCare.Diagnosis.Role.Text',
EpisodeOfCare_Id_Assigner TEXT COMMENT 'EpisodeOfCare.Identifier.Assigner',
EpisodeOfCare_Id_Prd_End TEXT COMMENT 'EpisodeOfCare.Identifier.Period.End',
EpisodeOfCare_Id_Prd_Strt TEXT COMMENT 'EpisodeOfCare.Identifier.Period.Start',
EpisodeOfCare_Id_Sys TEXT COMMENT 'EpisodeOfCare.Identifier.System',
EpisodeOfCare_Id_Typ_Cdg_Cd TEXT COMMENT 'EpisodeOfCare.Identifier.Type.Coding.Code',
EpisodeOfCare_Id_Typ_Cdg_Dsply TEXT COMMENT 'EpisodeOfCare.Identifier.Type.Coding.Display',
EpisodeOfCare_Id_Typ_Cdg_Sys TEXT COMMENT 'EpisodeOfCare.Identifier.Type.Coding.System',
EpisodeOfCare_Id_Typ_Cdg_UsrSltd TEXT COMMENT 'EpisodeOfCare.Identifier.Type.Coding.UserSelected',
EpisodeOfCare_Id_Typ_Cdg_Vrsn TEXT COMMENT 'EpisodeOfCare.Identifier.Type.Coding.Version',
EpisodeOfCare_Id_Typ_Txt TEXT COMMENT 'EpisodeOfCare.Identifier.Type.Text',
EpisodeOfCare_Id_Use TEXT COMMENT 'EpisodeOfCare.Identifier.Use',
EpisodeOfCare_Id_Vl TEXT COMMENT 'EpisodeOfCare.Identifier.Value',
EpisodeOfCare_ManagingOrgnztn TEXT COMMENT 'EpisodeOfCare.ManagingOrganization',
EpisodeOfCare_Pnt TEXT COMMENT 'EpisodeOfCare.Patient',
EpisodeOfCare_Prd_End TEXT COMMENT 'EpisodeOfCare.Period.End',
EpisodeOfCare_Prd_Strt TEXT COMMENT 'EpisodeOfCare.Period.Start',
EpisodeOfCare_ReferralRqst TEXT COMMENT 'EpisodeOfCare.ReferralRequest',
EpisodeOfCare_Sts TEXT COMMENT 'EpisodeOfCare.Status',
EpisodeOfCare_StsHis_Prd_End TEXT COMMENT 'EpisodeOfCare.StatusHistory.Period.End',
EpisodeOfCare_StsHis_Prd_Strt TEXT COMMENT 'EpisodeOfCare.StatusHistory.Period.Start',
EpisodeOfCare_StsHis_Sts TEXT COMMENT 'EpisodeOfCare.StatusHistory.Status',
EpisodeOfCare_Team TEXT COMMENT 'EpisodeOfCare.Team',
EpisodeOfCare_Typ_Cdg_Cd TEXT COMMENT 'EpisodeOfCare.Type.Coding.Code',
EpisodeOfCare_Typ_Cdg_Dsply TEXT COMMENT 'EpisodeOfCare.Type.Coding.Display',
EpisodeOfCare_Typ_Cdg_Sys TEXT COMMENT 'EpisodeOfCare.Type.Coding.System',
EpisodeOfCare_Typ_Cdg_UsrSltd TEXT COMMENT 'EpisodeOfCare.Type.Coding.UserSelected',
EpisodeOfCare_Typ_Cdg_Vrsn TEXT COMMENT 'EpisodeOfCare.Type.Coding.Version',
EpisodeOfCare_Typ_Txt TEXT COMMENT 'EpisodeOfCare.Type.Text',
PRIMARY KEY(id)) ENGINE=MyISAM
    ROW_FORMAT=COMPRESSED 
    KEY_BLOCK_SIZE=8;