drop table if exists `Flag`;
CREATE TABLE `Flag` (
 id varchar(64),
Flag_Athr TEXT COMMENT 'Flag.Author',
Flag_Ctgry_Cdg_Cd TEXT COMMENT 'Flag.Category.Coding.Code',
Flag_Ctgry_Cdg_Dsply TEXT COMMENT 'Flag.Category.Coding.Display',
Flag_Ctgry_Cdg_Sys TEXT COMMENT 'Flag.Category.Coding.System',
Flag_Ctgry_Cdg_UsrSltd TEXT COMMENT 'Flag.Category.Coding.UserSelected',
Flag_Ctgry_Cdg_Vrsn TEXT COMMENT 'Flag.Category.Coding.Version',
Flag_Ctgry_Txt TEXT COMMENT 'Flag.Category.Text',
Flag_Cd_Cdg_Cd TEXT COMMENT 'Flag.Code.Coding.Code',
Flag_Cd_Cdg_Dsply TEXT COMMENT 'Flag.Code.Coding.Display',
Flag_Cd_Cdg_Sys TEXT COMMENT 'Flag.Code.Coding.System',
Flag_Cd_Cdg_UsrSltd TEXT COMMENT 'Flag.Code.Coding.UserSelected',
Flag_Cd_Cdg_Vrsn TEXT COMMENT 'Flag.Code.Coding.Version',
Flag_Cd_Txt TEXT COMMENT 'Flag.Code.Text',
Flag_Enc TEXT COMMENT 'Flag.Encounter',
Flag_Id_Assigner TEXT COMMENT 'Flag.Identifier.Assigner',
Flag_Id_Prd_End TEXT COMMENT 'Flag.Identifier.Period.End',
Flag_Id_Prd_Strt TEXT COMMENT 'Flag.Identifier.Period.Start',
Flag_Id_Sys TEXT COMMENT 'Flag.Identifier.System',
Flag_Id_Typ_Cdg_Cd TEXT COMMENT 'Flag.Identifier.Type.Coding.Code',
Flag_Id_Typ_Cdg_Dsply TEXT COMMENT 'Flag.Identifier.Type.Coding.Display',
Flag_Id_Typ_Cdg_Sys TEXT COMMENT 'Flag.Identifier.Type.Coding.System',
Flag_Id_Typ_Cdg_UsrSltd TEXT COMMENT 'Flag.Identifier.Type.Coding.UserSelected',
Flag_Id_Typ_Cdg_Vrsn TEXT COMMENT 'Flag.Identifier.Type.Coding.Version',
Flag_Id_Typ_Txt TEXT COMMENT 'Flag.Identifier.Type.Text',
Flag_Id_Use TEXT COMMENT 'Flag.Identifier.Use',
Flag_Id_Vl TEXT COMMENT 'Flag.Identifier.Value',
Flag_Prd_End TEXT COMMENT 'Flag.Period.End',
Flag_Prd_Strt TEXT COMMENT 'Flag.Period.Start',
Flag_Sts TEXT COMMENT 'Flag.Status',
Flag_Sbjct TEXT COMMENT 'Flag.Subject',
PRIMARY KEY(id)) ENGINE=MyISAM
    ROW_FORMAT=COMPRESSED 
    KEY_BLOCK_SIZE=8;