drop table if exists `ImmunizationEvaluation`;
CREATE TABLE `ImmunizationEvaluation` (
 id varchar(64),
ImmnztnEvaluation_Athrity TEXT COMMENT 'ImmunizationEvaluation.Authority',
ImmnztnEvaluation_Dt TEXT COMMENT 'ImmunizationEvaluation.Date',
ImmnztnEvaluation_Dscrptn TEXT COMMENT 'ImmunizationEvaluation.Description',
ImmnztnEvaluation_DoseNmbrPositiveIntTyp TEXT COMMENT 'ImmunizationEvaluation.DoseNumberPositiveIntType',
ImmnztnEvaluation_DoseNmbrStrgTyp TEXT COMMENT 'ImmunizationEvaluation.DoseNumberStringType',
ImmnztnEvaluation_DoseSts_Cdg_Cd TEXT COMMENT 'ImmunizationEvaluation.DoseStatus.Coding.Code',
ImmnztnEvaluation_DoseSts_Cdg_Dsply TEXT COMMENT 'ImmunizationEvaluation.DoseStatus.Coding.Display',
ImmnztnEvaluation_DoseSts_Cdg_Sys TEXT COMMENT 'ImmunizationEvaluation.DoseStatus.Coding.System',
ImmnztnEvaluation_DoseSts_Cdg_UsrSltd TEXT COMMENT 'ImmunizationEvaluation.DoseStatus.Coding.UserSelected',
ImmnztnEvaluation_DoseSts_Cdg_Vrsn TEXT COMMENT 'ImmunizationEvaluation.DoseStatus.Coding.Version',
ImmnztnEvaluation_DoseSts_Txt TEXT COMMENT 'ImmunizationEvaluation.DoseStatus.Text',
ImmnztnEvaluation_DoseStsRsn_Cdg_Cd TEXT COMMENT 'ImmunizationEvaluation.DoseStatusReason.Coding.Code',
ImmnztnEvaluation_DoseStsRsn_Cdg_Dsply TEXT COMMENT 'ImmunizationEvaluation.DoseStatusReason.Coding.Display',
ImmnztnEvaluation_DoseStsRsn_Cdg_Sys TEXT COMMENT 'ImmunizationEvaluation.DoseStatusReason.Coding.System',
ImmnztnEvaluation_DoseStsRsn_Cdg_UsrSltd TEXT COMMENT 'ImmunizationEvaluation.DoseStatusReason.Coding.UserSelected',
ImmnztnEvaluation_DoseStsRsn_Cdg_Vrsn TEXT COMMENT 'ImmunizationEvaluation.DoseStatusReason.Coding.Version',
ImmnztnEvaluation_DoseStsRsn_Txt TEXT COMMENT 'ImmunizationEvaluation.DoseStatusReason.Text',
ImmnztnEvaluation_Id_Assigner TEXT COMMENT 'ImmunizationEvaluation.Identifier.Assigner',
ImmnztnEvaluation_Id_Prd_End TEXT COMMENT 'ImmunizationEvaluation.Identifier.Period.End',
ImmnztnEvaluation_Id_Prd_Strt TEXT COMMENT 'ImmunizationEvaluation.Identifier.Period.Start',
ImmnztnEvaluation_Id_Sys TEXT COMMENT 'ImmunizationEvaluation.Identifier.System',
ImmnztnEvaluation_Id_Typ_Cdg_Cd TEXT COMMENT 'ImmunizationEvaluation.Identifier.Type.Coding.Code',
ImmnztnEvaluation_Id_Typ_Cdg_Dsply TEXT COMMENT 'ImmunizationEvaluation.Identifier.Type.Coding.Display',
ImmnztnEvaluation_Id_Typ_Cdg_Sys TEXT COMMENT 'ImmunizationEvaluation.Identifier.Type.Coding.System',
ImmnztnEvaluation_Id_Typ_Cdg_UsrSltd TEXT COMMENT 'ImmunizationEvaluation.Identifier.Type.Coding.UserSelected',
ImmnztnEvaluation_Id_Typ_Cdg_Vrsn TEXT COMMENT 'ImmunizationEvaluation.Identifier.Type.Coding.Version',
ImmnztnEvaluation_Id_Typ_Txt TEXT COMMENT 'ImmunizationEvaluation.Identifier.Type.Text',
ImmnztnEvaluation_Id_Use TEXT COMMENT 'ImmunizationEvaluation.Identifier.Use',
ImmnztnEvaluation_Id_Vl TEXT COMMENT 'ImmunizationEvaluation.Identifier.Value',
ImmnztnEvaluation_ImmnztnEvnt TEXT COMMENT 'ImmunizationEvaluation.ImmunizationEvent',
ImmnztnEvaluation_Pnt TEXT COMMENT 'ImmunizationEvaluation.Patient',
ImmnztnEvaluation_Series TEXT COMMENT 'ImmunizationEvaluation.Series',
ImmnztnEvaluation_SeriesDosesPositiveIntTyp TEXT COMMENT 'ImmunizationEvaluation.SeriesDosesPositiveIntType',
ImmnztnEvaluation_SeriesDosesStrgTyp TEXT COMMENT 'ImmunizationEvaluation.SeriesDosesStringType',
ImmnztnEvaluation_Sts TEXT COMMENT 'ImmunizationEvaluation.Status',
ImmnztnEvaluation_TarDisease_Cdg_Cd TEXT COMMENT 'ImmunizationEvaluation.TarDisease.Coding.Code',
ImmnztnEvaluation_TarDisease_Cdg_Dsply TEXT COMMENT 'ImmunizationEvaluation.TarDisease.Coding.Display',
ImmnztnEvaluation_TarDisease_Cdg_Sys TEXT COMMENT 'ImmunizationEvaluation.TarDisease.Coding.System',
ImmnztnEvaluation_TarDisease_Cdg_UsrSltd TEXT COMMENT 'ImmunizationEvaluation.TarDisease.Coding.UserSelected',
ImmnztnEvaluation_TarDisease_Cdg_Vrsn TEXT COMMENT 'ImmunizationEvaluation.TarDisease.Coding.Version',
ImmnztnEvaluation_TarDisease_Txt TEXT COMMENT 'ImmunizationEvaluation.TarDisease.Text',
PRIMARY KEY(id)) ENGINE=MyISAM
    ROW_FORMAT=COMPRESSED 
    KEY_BLOCK_SIZE=8;