drop table if exists `ListResource`;
CREATE TABLE `ListResource` (
 id varchar(64),
ListRsrc_Cd_Cdg_Cd TEXT,
ListRsrc_Cd_Cdg_Dsply TEXT,
ListRsrc_Cd_Cdg_Sys TEXT,
ListRsrc_Cd_Cdg_UsrSltd TEXT,
ListRsrc_Cd_Cdg_Vrsn TEXT,
ListRsrc_Cd_Txt TEXT,
ListRsrc_Dt TEXT,
ListRsrc_EmptyRsn_Cdg_Cd TEXT,
ListRsrc_EmptyRsn_Cdg_Dsply TEXT,
ListRsrc_EmptyRsn_Cdg_Sys TEXT,
ListRsrc_EmptyRsn_Cdg_UsrSltd TEXT,
ListRsrc_EmptyRsn_Cdg_Vrsn TEXT,
ListRsrc_EmptyRsn_Txt TEXT,
ListRsrc_Enc TEXT,
ListRsrc_Entry_Dt TEXT,
ListRsrc_Entry_Deleted TEXT,
ListRsrc_Entry_Flag_Cdg_Cd TEXT,
ListRsrc_Entry_Flag_Cdg_Dsply TEXT,
ListRsrc_Entry_Flag_Cdg_Sys TEXT,
ListRsrc_Entry_Flag_Cdg_UsrSltd TEXT,
ListRsrc_Entry_Flag_Cdg_Vrsn TEXT,
ListRsrc_Entry_Flag_Txt TEXT,
ListRsrc_Entry_Itm TEXT,
ListRsrc_Id_Assigner TEXT,
ListRsrc_Id_Prd_End TEXT,
ListRsrc_Id_Prd_Strt TEXT,
ListRsrc_Id_Sys TEXT,
ListRsrc_Id_Typ_Cdg_Cd TEXT,
ListRsrc_Id_Typ_Cdg_Dsply TEXT,
ListRsrc_Id_Typ_Cdg_Sys TEXT,
ListRsrc_Id_Typ_Cdg_UsrSltd TEXT,
ListRsrc_Id_Typ_Cdg_Vrsn TEXT,
ListRsrc_Id_Typ_Txt TEXT,
ListRsrc_Id_Use TEXT,
ListRsrc_Id_Vl TEXT,
ListRsrc_Mode TEXT,
ListRsrc_Nt_AthrRfrnc TEXT,
ListRsrc_Nt_AthrStrgTyp TEXT,
ListRsrc_Nt_Txt TEXT,
ListRsrc_Nt_Time TEXT,
ListRsrc_OrdredBy_Cdg_Cd TEXT,
ListRsrc_OrdredBy_Cdg_Dsply TEXT,
ListRsrc_OrdredBy_Cdg_Sys TEXT,
ListRsrc_OrdredBy_Cdg_UsrSltd TEXT,
ListRsrc_OrdredBy_Cdg_Vrsn TEXT,
ListRsrc_OrdredBy_Txt TEXT,
ListRsrc_Src TEXT,
ListRsrc_Sts TEXT,
ListRsrc_Sbjct TEXT,
ListRsrc_Ttl TEXT,
PRIMARY KEY(id)) ENGINE=MyISAM
    ROW_FORMAT=COMPRESSED 
    KEY_BLOCK_SIZE=8;