drop table if exists `ListResource`;
CREATE TABLE `ListResource` (
 id varchar(64),
ListRsrc_Cd_Cdg_Cd TEXT COMMENT 'ListResource.Code.Coding.Code',
ListRsrc_Cd_Cdg_Dsply TEXT COMMENT 'ListResource.Code.Coding.Display',
ListRsrc_Cd_Cdg_Sys TEXT COMMENT 'ListResource.Code.Coding.System',
ListRsrc_Cd_Cdg_UsrSltd TEXT COMMENT 'ListResource.Code.Coding.UserSelected',
ListRsrc_Cd_Cdg_Vrsn TEXT COMMENT 'ListResource.Code.Coding.Version',
ListRsrc_Cd_Txt TEXT COMMENT 'ListResource.Code.Text',
ListRsrc_Dt TEXT COMMENT 'ListResource.Date',
ListRsrc_EmptyRsn_Cdg_Cd TEXT COMMENT 'ListResource.EmptyReason.Coding.Code',
ListRsrc_EmptyRsn_Cdg_Dsply TEXT COMMENT 'ListResource.EmptyReason.Coding.Display',
ListRsrc_EmptyRsn_Cdg_Sys TEXT COMMENT 'ListResource.EmptyReason.Coding.System',
ListRsrc_EmptyRsn_Cdg_UsrSltd TEXT COMMENT 'ListResource.EmptyReason.Coding.UserSelected',
ListRsrc_EmptyRsn_Cdg_Vrsn TEXT COMMENT 'ListResource.EmptyReason.Coding.Version',
ListRsrc_EmptyRsn_Txt TEXT COMMENT 'ListResource.EmptyReason.Text',
ListRsrc_Enc TEXT COMMENT 'ListResource.Encounter',
ListRsrc_Entry_Dt TEXT COMMENT 'ListResource.Entry.Date',
ListRsrc_Entry_Deleted TEXT COMMENT 'ListResource.Entry.Deleted',
ListRsrc_Entry_Flag_Cdg_Cd TEXT COMMENT 'ListResource.Entry.Flag.Coding.Code',
ListRsrc_Entry_Flag_Cdg_Dsply TEXT COMMENT 'ListResource.Entry.Flag.Coding.Display',
ListRsrc_Entry_Flag_Cdg_Sys TEXT COMMENT 'ListResource.Entry.Flag.Coding.System',
ListRsrc_Entry_Flag_Cdg_UsrSltd TEXT COMMENT 'ListResource.Entry.Flag.Coding.UserSelected',
ListRsrc_Entry_Flag_Cdg_Vrsn TEXT COMMENT 'ListResource.Entry.Flag.Coding.Version',
ListRsrc_Entry_Flag_Txt TEXT COMMENT 'ListResource.Entry.Flag.Text',
ListRsrc_Entry_Itm TEXT COMMENT 'ListResource.Entry.Item',
ListRsrc_Id_Assigner TEXT COMMENT 'ListResource.Identifier.Assigner',
ListRsrc_Id_Prd_End TEXT COMMENT 'ListResource.Identifier.Period.End',
ListRsrc_Id_Prd_Strt TEXT COMMENT 'ListResource.Identifier.Period.Start',
ListRsrc_Id_Sys TEXT COMMENT 'ListResource.Identifier.System',
ListRsrc_Id_Typ_Cdg_Cd TEXT COMMENT 'ListResource.Identifier.Type.Coding.Code',
ListRsrc_Id_Typ_Cdg_Dsply TEXT COMMENT 'ListResource.Identifier.Type.Coding.Display',
ListRsrc_Id_Typ_Cdg_Sys TEXT COMMENT 'ListResource.Identifier.Type.Coding.System',
ListRsrc_Id_Typ_Cdg_UsrSltd TEXT COMMENT 'ListResource.Identifier.Type.Coding.UserSelected',
ListRsrc_Id_Typ_Cdg_Vrsn TEXT COMMENT 'ListResource.Identifier.Type.Coding.Version',
ListRsrc_Id_Typ_Txt TEXT COMMENT 'ListResource.Identifier.Type.Text',
ListRsrc_Id_Use TEXT COMMENT 'ListResource.Identifier.Use',
ListRsrc_Id_Vl TEXT COMMENT 'ListResource.Identifier.Value',
ListRsrc_Mode TEXT COMMENT 'ListResource.Mode',
ListRsrc_Nt_AthrRfrnc TEXT COMMENT 'ListResource.Note.AuthorReference',
ListRsrc_Nt_AthrStrgTyp TEXT COMMENT 'ListResource.Note.AuthorStringType',
ListRsrc_Nt_Txt TEXT COMMENT 'ListResource.Note.Text',
ListRsrc_Nt_Time TEXT COMMENT 'ListResource.Note.Time',
ListRsrc_OrdredBy_Cdg_Cd TEXT COMMENT 'ListResource.OrderedBy.Coding.Code',
ListRsrc_OrdredBy_Cdg_Dsply TEXT COMMENT 'ListResource.OrderedBy.Coding.Display',
ListRsrc_OrdredBy_Cdg_Sys TEXT COMMENT 'ListResource.OrderedBy.Coding.System',
ListRsrc_OrdredBy_Cdg_UsrSltd TEXT COMMENT 'ListResource.OrderedBy.Coding.UserSelected',
ListRsrc_OrdredBy_Cdg_Vrsn TEXT COMMENT 'ListResource.OrderedBy.Coding.Version',
ListRsrc_OrdredBy_Txt TEXT COMMENT 'ListResource.OrderedBy.Text',
ListRsrc_Src TEXT COMMENT 'ListResource.Source',
ListRsrc_Sts TEXT COMMENT 'ListResource.Status',
ListRsrc_Sbjct TEXT COMMENT 'ListResource.Subject',
ListRsrc_Ttl TEXT COMMENT 'ListResource.Title',
PRIMARY KEY(id)) ENGINE=MyISAM
    ROW_FORMAT=COMPRESSED 
    KEY_BLOCK_SIZE=8;