drop table if exists `MessageHeader`;
CREATE TABLE `MessageHeader` (
 id varchar(64),
MsgHeader_Athr TEXT COMMENT 'MessageHeader.Author',
MsgHeader_Dfn TEXT COMMENT 'MessageHeader.Definition',
MsgHeader_Destination_Endpoint TEXT COMMENT 'MessageHeader.Destination.Endpoint',
MsgHeader_Destination_Nm TEXT COMMENT 'MessageHeader.Destination.Name',
MsgHeader_Destination_Receiver TEXT COMMENT 'MessageHeader.Destination.Receiver',
MsgHeader_Enterer TEXT COMMENT 'MessageHeader.Enterer',
MsgHeader_EvntCdg_Cd TEXT COMMENT 'MessageHeader.EventCoding.Code',
MsgHeader_EvntCdg_Dsply TEXT COMMENT 'MessageHeader.EventCoding.Display',
MsgHeader_EvntCdg_Sys TEXT COMMENT 'MessageHeader.EventCoding.System',
MsgHeader_EvntCdg_UsrSltd TEXT COMMENT 'MessageHeader.EventCoding.UserSelected',
MsgHeader_EvntCdg_Vrsn TEXT COMMENT 'MessageHeader.EventCoding.Version',
MsgHeader_EvntUriTyp TEXT COMMENT 'MessageHeader.EventUriType',
MsgHeader_Focus TEXT COMMENT 'MessageHeader.Focus',
MsgHeader_Rsn_Cdg_Cd TEXT COMMENT 'MessageHeader.Reason.Coding.Code',
MsgHeader_Rsn_Cdg_Dsply TEXT COMMENT 'MessageHeader.Reason.Coding.Display',
MsgHeader_Rsn_Cdg_Sys TEXT COMMENT 'MessageHeader.Reason.Coding.System',
MsgHeader_Rsn_Cdg_UsrSltd TEXT COMMENT 'MessageHeader.Reason.Coding.UserSelected',
MsgHeader_Rsn_Cdg_Vrsn TEXT COMMENT 'MessageHeader.Reason.Coding.Version',
MsgHeader_Rsn_Txt TEXT COMMENT 'MessageHeader.Reason.Text',
MsgHeader_Rsps_Cd TEXT COMMENT 'MessageHeader.Response.Code',
MsgHeader_Rsps_Dtls TEXT COMMENT 'MessageHeader.Response.Details',
MsgHeader_Rsps_Id TEXT COMMENT 'MessageHeader.Response.Identifier',
MsgHeader_Responsible TEXT COMMENT 'MessageHeader.Responsible',
MsgHeader_Sender TEXT COMMENT 'MessageHeader.Sender',
MsgHeader_Src_Cntct_Prd_End TEXT COMMENT 'MessageHeader.Source.Contact.Period.End',
MsgHeader_Src_Cntct_Prd_Strt TEXT COMMENT 'MessageHeader.Source.Contact.Period.Start',
MsgHeader_Src_Cntct_Rnk TEXT COMMENT 'MessageHeader.Source.Contact.Rank',
MsgHeader_Src_Cntct_Sys TEXT COMMENT 'MessageHeader.Source.Contact.System',
MsgHeader_Src_Cntct_Use TEXT COMMENT 'MessageHeader.Source.Contact.Use',
MsgHeader_Src_Cntct_Vl TEXT COMMENT 'MessageHeader.Source.Contact.Value',
MsgHeader_Src_Endpoint TEXT COMMENT 'MessageHeader.Source.Endpoint',
MsgHeader_Src_Nm TEXT COMMENT 'MessageHeader.Source.Name',
MsgHeader_Src_Software TEXT COMMENT 'MessageHeader.Source.Software',
MsgHeader_Src_Vrsn TEXT COMMENT 'MessageHeader.Source.Version',
PRIMARY KEY(id)) ENGINE=MyISAM
    ROW_FORMAT=COMPRESSED 
    KEY_BLOCK_SIZE=8;