drop table if exists `MessageHeader`;
CREATE TABLE `MessageHeader` (
 id varchar(64),
MsgHeader_Athr TEXT,
MsgHeader_Dfn TEXT,
MsgHeader_Destination_Endpoint TEXT,
MsgHeader_Destination_Nm TEXT,
MsgHeader_Destination_Receiver TEXT,
MsgHeader_Enterer TEXT,
MsgHeader_EvntCdg_Cd TEXT,
MsgHeader_EvntCdg_Dsply TEXT,
MsgHeader_EvntCdg_Sys TEXT,
MsgHeader_EvntCdg_UsrSltd TEXT,
MsgHeader_EvntCdg_Vrsn TEXT,
MsgHeader_EvntUriTyp TEXT,
MsgHeader_Focus TEXT,
MsgHeader_Rsn_Cdg_Cd TEXT,
MsgHeader_Rsn_Cdg_Dsply TEXT,
MsgHeader_Rsn_Cdg_Sys TEXT,
MsgHeader_Rsn_Cdg_UsrSltd TEXT,
MsgHeader_Rsn_Cdg_Vrsn TEXT,
MsgHeader_Rsn_Txt TEXT,
MsgHeader_Rsps_Cd TEXT,
MsgHeader_Rsps_Dtls TEXT,
MsgHeader_Rsps_Id TEXT,
MsgHeader_Responsible TEXT,
MsgHeader_Sender TEXT,
MsgHeader_Src_Cntct_Prd_End TEXT,
MsgHeader_Src_Cntct_Prd_Strt TEXT,
MsgHeader_Src_Cntct_Rnk TEXT,
MsgHeader_Src_Cntct_Sys TEXT,
MsgHeader_Src_Cntct_Use TEXT,
MsgHeader_Src_Cntct_Vl TEXT,
MsgHeader_Src_Endpoint TEXT,
MsgHeader_Src_Nm TEXT,
MsgHeader_Src_Software TEXT,
MsgHeader_Src_Vrsn TEXT,
PRIMARY KEY(id)) ENGINE=MyISAM
    ROW_FORMAT=COMPRESSED 
    KEY_BLOCK_SIZE=8;