drop table if exists `OrganizationAffiliation`;
CREATE TABLE `OrganizationAffiliation` (
 id varchar(64),
OrgnztnAffiliation_Active TEXT COMMENT 'OrganizationAffiliation.Active',
OrgnztnAffiliation_Cd_Cdg_Cd TEXT COMMENT 'OrganizationAffiliation.Code.Coding.Code',
OrgnztnAffiliation_Cd_Cdg_Dsply TEXT COMMENT 'OrganizationAffiliation.Code.Coding.Display',
OrgnztnAffiliation_Cd_Cdg_Sys TEXT COMMENT 'OrganizationAffiliation.Code.Coding.System',
OrgnztnAffiliation_Cd_Cdg_UsrSltd TEXT COMMENT 'OrganizationAffiliation.Code.Coding.UserSelected',
OrgnztnAffiliation_Cd_Cdg_Vrsn TEXT COMMENT 'OrganizationAffiliation.Code.Coding.Version',
OrgnztnAffiliation_Cd_Txt TEXT COMMENT 'OrganizationAffiliation.Code.Text',
OrgnztnAffiliation_Endpoint TEXT COMMENT 'OrganizationAffiliation.Endpoint',
OrgnztnAffiliation_HlthcrSrv TEXT COMMENT 'OrganizationAffiliation.HealthcareService',
OrgnztnAffiliation_Id_Assigner TEXT COMMENT 'OrganizationAffiliation.Identifier.Assigner',
OrgnztnAffiliation_Id_Prd_End TEXT COMMENT 'OrganizationAffiliation.Identifier.Period.End',
OrgnztnAffiliation_Id_Prd_Strt TEXT COMMENT 'OrganizationAffiliation.Identifier.Period.Start',
OrgnztnAffiliation_Id_Sys TEXT COMMENT 'OrganizationAffiliation.Identifier.System',
OrgnztnAffiliation_Id_Typ_Cdg_Cd TEXT COMMENT 'OrganizationAffiliation.Identifier.Type.Coding.Code',
OrgnztnAffiliation_Id_Typ_Cdg_Dsply TEXT COMMENT 'OrganizationAffiliation.Identifier.Type.Coding.Display',
OrgnztnAffiliation_Id_Typ_Cdg_Sys TEXT COMMENT 'OrganizationAffiliation.Identifier.Type.Coding.System',
OrgnztnAffiliation_Id_Typ_Cdg_UsrSltd TEXT COMMENT 'OrganizationAffiliation.Identifier.Type.Coding.UserSelected',
OrgnztnAffiliation_Id_Typ_Cdg_Vrsn TEXT COMMENT 'OrganizationAffiliation.Identifier.Type.Coding.Version',
OrgnztnAffiliation_Id_Typ_Txt TEXT COMMENT 'OrganizationAffiliation.Identifier.Type.Text',
OrgnztnAffiliation_Id_Use TEXT COMMENT 'OrganizationAffiliation.Identifier.Use',
OrgnztnAffiliation_Id_Vl TEXT COMMENT 'OrganizationAffiliation.Identifier.Value',
OrgnztnAffiliation_Lctn TEXT COMMENT 'OrganizationAffiliation.Location',
OrgnztnAffiliation_Network TEXT COMMENT 'OrganizationAffiliation.Network',
OrgnztnAffiliation_Orgnztn TEXT COMMENT 'OrganizationAffiliation.Organization',
OrgnztnAffiliation_ParticipatingOrgnztn TEXT COMMENT 'OrganizationAffiliation.ParticipatingOrganization',
OrgnztnAffiliation_Prd_End TEXT COMMENT 'OrganizationAffiliation.Period.End',
OrgnztnAffiliation_Prd_Strt TEXT COMMENT 'OrganizationAffiliation.Period.Start',
OrgnztnAffiliation_Spclty_Cdg_Cd TEXT COMMENT 'OrganizationAffiliation.Specialty.Coding.Code',
OrgnztnAffiliation_Spclty_Cdg_Dsply TEXT COMMENT 'OrganizationAffiliation.Specialty.Coding.Display',
OrgnztnAffiliation_Spclty_Cdg_Sys TEXT COMMENT 'OrganizationAffiliation.Specialty.Coding.System',
OrgnztnAffiliation_Spclty_Cdg_UsrSltd TEXT COMMENT 'OrganizationAffiliation.Specialty.Coding.UserSelected',
OrgnztnAffiliation_Spclty_Cdg_Vrsn TEXT COMMENT 'OrganizationAffiliation.Specialty.Coding.Version',
OrgnztnAffiliation_Spclty_Txt TEXT COMMENT 'OrganizationAffiliation.Specialty.Text',
OrgnztnAffiliation_Tlcm_Prd_End TEXT COMMENT 'OrganizationAffiliation.Telecom.Period.End',
OrgnztnAffiliation_Tlcm_Prd_Strt TEXT COMMENT 'OrganizationAffiliation.Telecom.Period.Start',
OrgnztnAffiliation_Tlcm_Rnk TEXT COMMENT 'OrganizationAffiliation.Telecom.Rank',
OrgnztnAffiliation_Tlcm_Sys TEXT COMMENT 'OrganizationAffiliation.Telecom.System',
OrgnztnAffiliation_Tlcm_Use TEXT COMMENT 'OrganizationAffiliation.Telecom.Use',
OrgnztnAffiliation_Tlcm_Vl TEXT COMMENT 'OrganizationAffiliation.Telecom.Value',
PRIMARY KEY(id)) ENGINE=MyISAM
    ROW_FORMAT=COMPRESSED 
    KEY_BLOCK_SIZE=8;