drop table if exists `PaymentNotice`;
CREATE TABLE `PaymentNotice` (
 id varchar(64),
PymntNotice_Amnt_Crncy TEXT COMMENT 'PaymentNotice.Amount.Currency',
PymntNotice_Amnt_Vl TEXT COMMENT 'PaymentNotice.Amount.Value',
PymntNotice_Created TEXT COMMENT 'PaymentNotice.Created',
PymntNotice_Id_Assigner TEXT COMMENT 'PaymentNotice.Identifier.Assigner',
PymntNotice_Id_Prd_End TEXT COMMENT 'PaymentNotice.Identifier.Period.End',
PymntNotice_Id_Prd_Strt TEXT COMMENT 'PaymentNotice.Identifier.Period.Start',
PymntNotice_Id_Sys TEXT COMMENT 'PaymentNotice.Identifier.System',
PymntNotice_Id_Typ_Cdg_Cd TEXT COMMENT 'PaymentNotice.Identifier.Type.Coding.Code',
PymntNotice_Id_Typ_Cdg_Dsply TEXT COMMENT 'PaymentNotice.Identifier.Type.Coding.Display',
PymntNotice_Id_Typ_Cdg_Sys TEXT COMMENT 'PaymentNotice.Identifier.Type.Coding.System',
PymntNotice_Id_Typ_Cdg_UsrSltd TEXT COMMENT 'PaymentNotice.Identifier.Type.Coding.UserSelected',
PymntNotice_Id_Typ_Cdg_Vrsn TEXT COMMENT 'PaymentNotice.Identifier.Type.Coding.Version',
PymntNotice_Id_Typ_Txt TEXT COMMENT 'PaymentNotice.Identifier.Type.Text',
PymntNotice_Id_Use TEXT COMMENT 'PaymentNotice.Identifier.Use',
PymntNotice_Id_Vl TEXT COMMENT 'PaymentNotice.Identifier.Value',
PymntNotice_Payee TEXT COMMENT 'PaymentNotice.Payee',
PymntNotice_Pymnt TEXT COMMENT 'PaymentNotice.Payment',
PymntNotice_PymntDt TEXT COMMENT 'PaymentNotice.PaymentDate',
PymntNotice_PymntSts_Cdg_Cd TEXT COMMENT 'PaymentNotice.PaymentStatus.Coding.Code',
PymntNotice_PymntSts_Cdg_Dsply TEXT COMMENT 'PaymentNotice.PaymentStatus.Coding.Display',
PymntNotice_PymntSts_Cdg_Sys TEXT COMMENT 'PaymentNotice.PaymentStatus.Coding.System',
PymntNotice_PymntSts_Cdg_UsrSltd TEXT COMMENT 'PaymentNotice.PaymentStatus.Coding.UserSelected',
PymntNotice_PymntSts_Cdg_Vrsn TEXT COMMENT 'PaymentNotice.PaymentStatus.Coding.Version',
PymntNotice_PymntSts_Txt TEXT COMMENT 'PaymentNotice.PaymentStatus.Text',
PymntNotice_Provider TEXT COMMENT 'PaymentNotice.Provider',
PymntNotice_Recipient TEXT COMMENT 'PaymentNotice.Recipient',
PymntNotice_Rqst TEXT COMMENT 'PaymentNotice.Request',
PymntNotice_Rsps TEXT COMMENT 'PaymentNotice.Response',
PymntNotice_Sts TEXT COMMENT 'PaymentNotice.Status',
PRIMARY KEY(id)) ENGINE=MyISAM
    ROW_FORMAT=COMPRESSED 
    KEY_BLOCK_SIZE=8;