drop table if exists `PaymentNotice`;
CREATE TABLE `PaymentNotice` (
 id varchar(64),
PymntNotice_Amnt_Crncy TEXT,
PymntNotice_Amnt_Vl TEXT,
PymntNotice_Created TEXT,
PymntNotice_Id_Assigner TEXT,
PymntNotice_Id_Prd_End TEXT,
PymntNotice_Id_Prd_Strt TEXT,
PymntNotice_Id_Sys TEXT,
PymntNotice_Id_Typ_Cdg_Cd TEXT,
PymntNotice_Id_Typ_Cdg_Dsply TEXT,
PymntNotice_Id_Typ_Cdg_Sys TEXT,
PymntNotice_Id_Typ_Cdg_UsrSltd TEXT,
PymntNotice_Id_Typ_Cdg_Vrsn TEXT,
PymntNotice_Id_Typ_Txt TEXT,
PymntNotice_Id_Use TEXT,
PymntNotice_Id_Vl TEXT,
PymntNotice_Payee TEXT,
PymntNotice_Pymnt TEXT,
PymntNotice_PymntDt TEXT,
PymntNotice_PymntSts_Cdg_Cd TEXT,
PymntNotice_PymntSts_Cdg_Dsply TEXT,
PymntNotice_PymntSts_Cdg_Sys TEXT,
PymntNotice_PymntSts_Cdg_UsrSltd TEXT,
PymntNotice_PymntSts_Cdg_Vrsn TEXT,
PymntNotice_PymntSts_Txt TEXT,
PymntNotice_Provider TEXT,
PymntNotice_Recipient TEXT,
PymntNotice_Rqst TEXT,
PymntNotice_Rsps TEXT,
PymntNotice_Sts TEXT,
PRIMARY KEY(id)) ENGINE=MyISAM
    ROW_FORMAT=COMPRESSED 
    KEY_BLOCK_SIZE=8;