drop table if exists `Person`;
CREATE TABLE `Person` (
 id varchar(64),
Prsn_Active TEXT,
Prsn_Addr_City TEXT,
Prsn_Addr_Cntry TEXT,
Prsn_Addr_District TEXT,
Prsn_Addr_Line TEXT,
Prsn_Addr_Prd_End TEXT,
Prsn_Addr_Prd_Strt TEXT,
Prsn_Addr_PostalCd TEXT,
Prsn_Addr_State TEXT,
Prsn_Addr_Txt TEXT,
Prsn_Addr_Typ TEXT,
Prsn_Addr_Use TEXT,
Prsn_BirthDt TEXT,
Prsn_Gender TEXT,
Prsn_Id_Assigner TEXT,
Prsn_Id_Prd_End TEXT,
Prsn_Id_Prd_Strt TEXT,
Prsn_Id_Sys TEXT,
Prsn_Id_Typ_Cdg_Cd TEXT,
Prsn_Id_Typ_Cdg_Dsply TEXT,
Prsn_Id_Typ_Cdg_Sys TEXT,
Prsn_Id_Typ_Cdg_UsrSltd TEXT,
Prsn_Id_Typ_Cdg_Vrsn TEXT,
Prsn_Id_Typ_Txt TEXT,
Prsn_Id_Use TEXT,
Prsn_Id_Vl TEXT,
Prsn_Link_Assurance TEXT,
Prsn_ManagingOrgnztn TEXT,
Prsn_Nm_Fmly TEXT,
Prsn_Nm_Given TEXT,
Prsn_Nm_Prd_End TEXT,
Prsn_Nm_Prd_Strt TEXT,
Prsn_Nm_Prefix TEXT,
Prsn_Nm_Suffix TEXT,
Prsn_Nm_Txt TEXT,
Prsn_Nm_Use TEXT,
Prsn_Photo_CntntTyp TEXT,
Prsn_Photo_Creation TEXT,
Prsn_Photo_Data TEXT,
Prsn_Photo_Hash TEXT,
Prsn_Photo_Lnguage TEXT,
Prsn_Photo_Sz TEXT,
Prsn_Photo_Ttl TEXT,
Prsn_Photo_Url TEXT,
Prsn_Tlcm_Prd_End TEXT,
Prsn_Tlcm_Prd_Strt TEXT,
Prsn_Tlcm_Rnk TEXT,
Prsn_Tlcm_Sys TEXT,
Prsn_Tlcm_Use TEXT,
Prsn_Tlcm_Vl TEXT,
PRIMARY KEY(id)) ENGINE=MyISAM
    ROW_FORMAT=COMPRESSED 
    KEY_BLOCK_SIZE=8;