drop table if exists `Person`;
CREATE TABLE `Person` (
 id varchar(64),
Prsn_Active TEXT COMMENT 'Person.Active',
Prsn_Addr_City TEXT COMMENT 'Person.Address.City',
Prsn_Addr_Cntry TEXT COMMENT 'Person.Address.Country',
Prsn_Addr_District TEXT COMMENT 'Person.Address.District',
Prsn_Addr_Line TEXT COMMENT 'Person.Address.Line',
Prsn_Addr_Prd_End TEXT COMMENT 'Person.Address.Period.End',
Prsn_Addr_Prd_Strt TEXT COMMENT 'Person.Address.Period.Start',
Prsn_Addr_PostalCd TEXT COMMENT 'Person.Address.PostalCode',
Prsn_Addr_State TEXT COMMENT 'Person.Address.State',
Prsn_Addr_Txt TEXT COMMENT 'Person.Address.Text',
Prsn_Addr_Typ TEXT COMMENT 'Person.Address.Type',
Prsn_Addr_Use TEXT COMMENT 'Person.Address.Use',
Prsn_BirthDt TEXT COMMENT 'Person.BirthDate',
Prsn_Gender TEXT COMMENT 'Person.Gender',
Prsn_Id_Assigner TEXT COMMENT 'Person.Identifier.Assigner',
Prsn_Id_Prd_End TEXT COMMENT 'Person.Identifier.Period.End',
Prsn_Id_Prd_Strt TEXT COMMENT 'Person.Identifier.Period.Start',
Prsn_Id_Sys TEXT COMMENT 'Person.Identifier.System',
Prsn_Id_Typ_Cdg_Cd TEXT COMMENT 'Person.Identifier.Type.Coding.Code',
Prsn_Id_Typ_Cdg_Dsply TEXT COMMENT 'Person.Identifier.Type.Coding.Display',
Prsn_Id_Typ_Cdg_Sys TEXT COMMENT 'Person.Identifier.Type.Coding.System',
Prsn_Id_Typ_Cdg_UsrSltd TEXT COMMENT 'Person.Identifier.Type.Coding.UserSelected',
Prsn_Id_Typ_Cdg_Vrsn TEXT COMMENT 'Person.Identifier.Type.Coding.Version',
Prsn_Id_Typ_Txt TEXT COMMENT 'Person.Identifier.Type.Text',
Prsn_Id_Use TEXT COMMENT 'Person.Identifier.Use',
Prsn_Id_Vl TEXT COMMENT 'Person.Identifier.Value',
Prsn_Link_Assurance TEXT COMMENT 'Person.Link.Assurance',
Prsn_ManagingOrgnztn TEXT COMMENT 'Person.ManagingOrganization',
Prsn_Nm_Fmly TEXT COMMENT 'Person.Name.Family',
Prsn_Nm_Given TEXT COMMENT 'Person.Name.Given',
Prsn_Nm_Prd_End TEXT COMMENT 'Person.Name.Period.End',
Prsn_Nm_Prd_Strt TEXT COMMENT 'Person.Name.Period.Start',
Prsn_Nm_Prefix TEXT COMMENT 'Person.Name.Prefix',
Prsn_Nm_Suffix TEXT COMMENT 'Person.Name.Suffix',
Prsn_Nm_Txt TEXT COMMENT 'Person.Name.Text',
Prsn_Nm_Use TEXT COMMENT 'Person.Name.Use',
Prsn_Photo_CntntTyp TEXT COMMENT 'Person.Photo.ContentType',
Prsn_Photo_Creation TEXT COMMENT 'Person.Photo.Creation',
Prsn_Photo_Data TEXT COMMENT 'Person.Photo.Data',
Prsn_Photo_Hash TEXT COMMENT 'Person.Photo.Hash',
Prsn_Photo_Lnguage TEXT COMMENT 'Person.Photo.Language',
Prsn_Photo_Sz TEXT COMMENT 'Person.Photo.Size',
Prsn_Photo_Ttl TEXT COMMENT 'Person.Photo.Title',
Prsn_Photo_Url TEXT COMMENT 'Person.Photo.Url',
Prsn_Tlcm_Prd_End TEXT COMMENT 'Person.Telecom.Period.End',
Prsn_Tlcm_Prd_Strt TEXT COMMENT 'Person.Telecom.Period.Start',
Prsn_Tlcm_Rnk TEXT COMMENT 'Person.Telecom.Rank',
Prsn_Tlcm_Sys TEXT COMMENT 'Person.Telecom.System',
Prsn_Tlcm_Use TEXT COMMENT 'Person.Telecom.Use',
Prsn_Tlcm_Vl TEXT COMMENT 'Person.Telecom.Value',
PRIMARY KEY(id)) ENGINE=MyISAM
    ROW_FORMAT=COMPRESSED 
    KEY_BLOCK_SIZE=8;