drop table if exists `PractitionerRole`;
CREATE TABLE `PractitionerRole` (
 id varchar(64),
PrctitnrRole_Active TEXT COMMENT 'PractitionerRole.Active',
PrctitnrRole_AvailabilityExceptions TEXT COMMENT 'PractitionerRole.AvailabilityExceptions',
PrctitnrRole_AvailableTime_AllDay TEXT COMMENT 'PractitionerRole.AvailableTime.AllDay',
PrctitnrRole_AvailableTime_AvailableEndTime TEXT COMMENT 'PractitionerRole.AvailableTime.AvailableEndTime',
PrctitnrRole_AvailableTime_AvailableStrtTime TEXT COMMENT 'PractitionerRole.AvailableTime.AvailableStartTime',
PrctitnrRole_Cd_Cdg_Cd TEXT COMMENT 'PractitionerRole.Code.Coding.Code',
PrctitnrRole_Cd_Cdg_Dsply TEXT COMMENT 'PractitionerRole.Code.Coding.Display',
PrctitnrRole_Cd_Cdg_Sys TEXT COMMENT 'PractitionerRole.Code.Coding.System',
PrctitnrRole_Cd_Cdg_UsrSltd TEXT COMMENT 'PractitionerRole.Code.Coding.UserSelected',
PrctitnrRole_Cd_Cdg_Vrsn TEXT COMMENT 'PractitionerRole.Code.Coding.Version',
PrctitnrRole_Cd_Txt TEXT COMMENT 'PractitionerRole.Code.Text',
PrctitnrRole_Endpoint TEXT COMMENT 'PractitionerRole.Endpoint',
PrctitnrRole_HlthcrSrv TEXT COMMENT 'PractitionerRole.HealthcareService',
PrctitnrRole_Id_Assigner TEXT COMMENT 'PractitionerRole.Identifier.Assigner',
PrctitnrRole_Id_Prd_End TEXT COMMENT 'PractitionerRole.Identifier.Period.End',
PrctitnrRole_Id_Prd_Strt TEXT COMMENT 'PractitionerRole.Identifier.Period.Start',
PrctitnrRole_Id_Sys TEXT COMMENT 'PractitionerRole.Identifier.System',
PrctitnrRole_Id_Typ_Cdg_Cd TEXT COMMENT 'PractitionerRole.Identifier.Type.Coding.Code',
PrctitnrRole_Id_Typ_Cdg_Dsply TEXT COMMENT 'PractitionerRole.Identifier.Type.Coding.Display',
PrctitnrRole_Id_Typ_Cdg_Sys TEXT COMMENT 'PractitionerRole.Identifier.Type.Coding.System',
PrctitnrRole_Id_Typ_Cdg_UsrSltd TEXT COMMENT 'PractitionerRole.Identifier.Type.Coding.UserSelected',
PrctitnrRole_Id_Typ_Cdg_Vrsn TEXT COMMENT 'PractitionerRole.Identifier.Type.Coding.Version',
PrctitnrRole_Id_Typ_Txt TEXT COMMENT 'PractitionerRole.Identifier.Type.Text',
PrctitnrRole_Id_Use TEXT COMMENT 'PractitionerRole.Identifier.Use',
PrctitnrRole_Id_Vl TEXT COMMENT 'PractitionerRole.Identifier.Value',
PrctitnrRole_Lctn TEXT COMMENT 'PractitionerRole.Location',
PrctitnrRole_NotAvailable_Dscrptn TEXT COMMENT 'PractitionerRole.NotAvailable.Description',
PrctitnrRole_NotAvailable_During_End TEXT COMMENT 'PractitionerRole.NotAvailable.During.End',
PrctitnrRole_NotAvailable_During_Strt TEXT COMMENT 'PractitionerRole.NotAvailable.During.Start',
PrctitnrRole_Orgnztn TEXT COMMENT 'PractitionerRole.Organization',
PrctitnrRole_Prd_End TEXT COMMENT 'PractitionerRole.Period.End',
PrctitnrRole_Prd_Strt TEXT COMMENT 'PractitionerRole.Period.Start',
PrctitnrRole_Prctitnr TEXT COMMENT 'PractitionerRole.Practitioner',
PrctitnrRole_Spclty_Cdg_Cd TEXT COMMENT 'PractitionerRole.Specialty.Coding.Code',
PrctitnrRole_Spclty_Cdg_Dsply TEXT COMMENT 'PractitionerRole.Specialty.Coding.Display',
PrctitnrRole_Spclty_Cdg_Sys TEXT COMMENT 'PractitionerRole.Specialty.Coding.System',
PrctitnrRole_Spclty_Cdg_UsrSltd TEXT COMMENT 'PractitionerRole.Specialty.Coding.UserSelected',
PrctitnrRole_Spclty_Cdg_Vrsn TEXT COMMENT 'PractitionerRole.Specialty.Coding.Version',
PrctitnrRole_Spclty_Txt TEXT COMMENT 'PractitionerRole.Specialty.Text',
PrctitnrRole_Tlcm_Prd_End TEXT COMMENT 'PractitionerRole.Telecom.Period.End',
PrctitnrRole_Tlcm_Prd_Strt TEXT COMMENT 'PractitionerRole.Telecom.Period.Start',
PrctitnrRole_Tlcm_Rnk TEXT COMMENT 'PractitionerRole.Telecom.Rank',
PrctitnrRole_Tlcm_Sys TEXT COMMENT 'PractitionerRole.Telecom.System',
PrctitnrRole_Tlcm_Use TEXT COMMENT 'PractitionerRole.Telecom.Use',
PrctitnrRole_Tlcm_Vl TEXT COMMENT 'PractitionerRole.Telecom.Value',
PRIMARY KEY(id)) ENGINE=MyISAM
    ROW_FORMAT=COMPRESSED 
    KEY_BLOCK_SIZE=8;