drop table if exists `PractitionerRole`;
CREATE TABLE `PractitionerRole` (
 id varchar(64),
PrctitnrRole_Active TEXT,
PrctitnrRole_AvailabilityExceptions TEXT,
PrctitnrRole_AvailableTime_AllDay TEXT,
PrctitnrRole_AvailableTime_AvailableEndTime TEXT,
PrctitnrRole_AvailableTime_AvailableStrtTime TEXT,
PrctitnrRole_AvailableTime_DaysOfWeek TEXT,
PrctitnrRole_Cd_Cdg_Cd TEXT,
PrctitnrRole_Cd_Cdg_Dsply TEXT,
PrctitnrRole_Cd_Cdg_Sys TEXT,
PrctitnrRole_Cd_Cdg_UsrSltd TEXT,
PrctitnrRole_Cd_Cdg_Vrsn TEXT,
PrctitnrRole_Cd_Txt TEXT,
PrctitnrRole_Endpoint TEXT,
PrctitnrRole_HlthcrSrv TEXT,
PrctitnrRole_Id_Assigner TEXT,
PrctitnrRole_Id_Prd_End TEXT,
PrctitnrRole_Id_Prd_Strt TEXT,
PrctitnrRole_Id_Sys TEXT,
PrctitnrRole_Id_Typ_Cdg_Cd TEXT,
PrctitnrRole_Id_Typ_Cdg_Dsply TEXT,
PrctitnrRole_Id_Typ_Cdg_Sys TEXT,
PrctitnrRole_Id_Typ_Cdg_UsrSltd TEXT,
PrctitnrRole_Id_Typ_Cdg_Vrsn TEXT,
PrctitnrRole_Id_Typ_Txt TEXT,
PrctitnrRole_Id_Use TEXT,
PrctitnrRole_Id_Vl TEXT,
PrctitnrRole_Lctn TEXT,
PrctitnrRole_NotAvailable_Dscrptn TEXT,
PrctitnrRole_NotAvailable_During_End TEXT,
PrctitnrRole_NotAvailable_During_Strt TEXT,
PrctitnrRole_Orgnztn TEXT,
PrctitnrRole_Prd_End TEXT,
PrctitnrRole_Prd_Strt TEXT,
PrctitnrRole_Prctitnr TEXT,
PrctitnrRole_Spclty_Cdg_Cd TEXT,
PrctitnrRole_Spclty_Cdg_Dsply TEXT,
PrctitnrRole_Spclty_Cdg_Sys TEXT,
PrctitnrRole_Spclty_Cdg_UsrSltd TEXT,
PrctitnrRole_Spclty_Cdg_Vrsn TEXT,
PrctitnrRole_Spclty_Txt TEXT,
PrctitnrRole_Tlcm_Prd_End TEXT,
PrctitnrRole_Tlcm_Prd_Strt TEXT,
PrctitnrRole_Tlcm_Rnk TEXT,
PrctitnrRole_Tlcm_Sys TEXT,
PrctitnrRole_Tlcm_Use TEXT,
PrctitnrRole_Tlcm_Vl TEXT,
PRIMARY KEY(id)) ENGINE=MyISAM
    ROW_FORMAT=COMPRESSED 
    KEY_BLOCK_SIZE=8;