drop table if exists `QuestionnaireResponse`;
CREATE TABLE `QuestionnaireResponse` (
 id varchar(64),
QstnaireRsps_Athr TEXT,
QstnaireRsps_Athred TEXT,
QstnaireRsps_BasedOn TEXT,
QstnaireRsps_Enc TEXT,
QstnaireRsps_Id_Assigner TEXT,
QstnaireRsps_Id_Prd_End TEXT,
QstnaireRsps_Id_Prd_Strt TEXT,
QstnaireRsps_Id_Sys TEXT,
QstnaireRsps_Id_Typ_Cdg_Cd TEXT,
QstnaireRsps_Id_Typ_Cdg_Dsply TEXT,
QstnaireRsps_Id_Typ_Cdg_Sys TEXT,
QstnaireRsps_Id_Typ_Cdg_UsrSltd TEXT,
QstnaireRsps_Id_Typ_Cdg_Vrsn TEXT,
QstnaireRsps_Id_Typ_Txt TEXT,
QstnaireRsps_Id_Use TEXT,
QstnaireRsps_Id_Vl TEXT,
QstnaireRsps_Itm_Ans_VlAttchmnt_CntntTyp TEXT,
QstnaireRsps_Itm_Ans_VlAttchmnt_Creation TEXT,
QstnaireRsps_Itm_Ans_VlAttchmnt_Data TEXT,
QstnaireRsps_Itm_Ans_VlAttchmnt_Hash TEXT,
QstnaireRsps_Itm_Ans_VlAttchmnt_Lnguage TEXT,
QstnaireRsps_Itm_Ans_VlAttchmnt_Sz TEXT,
QstnaireRsps_Itm_Ans_VlAttchmnt_Ttl TEXT,
QstnaireRsps_Itm_Ans_VlAttchmnt_Url TEXT,
QstnaireRsps_Itm_Ans_VlBooleanTyp TEXT,
QstnaireRsps_Itm_Ans_VlCdg_Cd TEXT,
QstnaireRsps_Itm_Ans_VlCdg_Dsply TEXT,
QstnaireRsps_Itm_Ans_VlCdg_Sys TEXT,
QstnaireRsps_Itm_Ans_VlCdg_UsrSltd TEXT,
QstnaireRsps_Itm_Ans_VlCdg_Vrsn TEXT,
QstnaireRsps_Itm_Ans_VlDtTimeTyp TEXT,
QstnaireRsps_Itm_Ans_VlDtTyp TEXT,
QstnaireRsps_Itm_Ans_VlDecimalTyp TEXT,
QstnaireRsps_Itm_Ans_VlIntegerTyp TEXT,
QstnaireRsps_Itm_Ans_VlQnty_Cd TEXT,
QstnaireRsps_Itm_Ans_VlQnty_Cmprtr TEXT,
QstnaireRsps_Itm_Ans_VlQnty_Sys TEXT,
QstnaireRsps_Itm_Ans_VlQnty_Unt TEXT,
QstnaireRsps_Itm_Ans_VlQnty_Vl TEXT,
QstnaireRsps_Itm_Ans_VlRfrnc TEXT,
QstnaireRsps_Itm_Ans_VlStrgTyp TEXT,
QstnaireRsps_Itm_Ans_VlTimeTyp TEXT,
QstnaireRsps_Itm_Ans_VlUriTyp TEXT,
QstnaireRsps_Itm_Dfn TEXT,
QstnaireRsps_Itm_LinkId TEXT,
QstnaireRsps_Itm_Txt TEXT,
QstnaireRsps_PartOf TEXT,
QstnaireRsps_Qstnaire TEXT,
QstnaireRsps_Src TEXT,
QstnaireRsps_Sts TEXT,
QstnaireRsps_Sbjct TEXT,
PRIMARY KEY(id)) ENGINE=MyISAM
    ROW_FORMAT=COMPRESSED 
    KEY_BLOCK_SIZE=8;