drop table if exists `Schedule`;
CREATE TABLE `Schedule` (
 id varchar(64),
Schdl_Active TEXT COMMENT 'Schedule.Active',
Schdl_Actor TEXT COMMENT 'Schedule.Actor',
Schdl_Comment TEXT COMMENT 'Schedule.Comment',
Schdl_Id_Assigner TEXT COMMENT 'Schedule.Identifier.Assigner',
Schdl_Id_Prd_End TEXT COMMENT 'Schedule.Identifier.Period.End',
Schdl_Id_Prd_Strt TEXT COMMENT 'Schedule.Identifier.Period.Start',
Schdl_Id_Sys TEXT COMMENT 'Schedule.Identifier.System',
Schdl_Id_Typ_Cdg_Cd TEXT COMMENT 'Schedule.Identifier.Type.Coding.Code',
Schdl_Id_Typ_Cdg_Dsply TEXT COMMENT 'Schedule.Identifier.Type.Coding.Display',
Schdl_Id_Typ_Cdg_Sys TEXT COMMENT 'Schedule.Identifier.Type.Coding.System',
Schdl_Id_Typ_Cdg_UsrSltd TEXT COMMENT 'Schedule.Identifier.Type.Coding.UserSelected',
Schdl_Id_Typ_Cdg_Vrsn TEXT COMMENT 'Schedule.Identifier.Type.Coding.Version',
Schdl_Id_Typ_Txt TEXT COMMENT 'Schedule.Identifier.Type.Text',
Schdl_Id_Use TEXT COMMENT 'Schedule.Identifier.Use',
Schdl_Id_Vl TEXT COMMENT 'Schedule.Identifier.Value',
Schdl_PlnningHorizon_End TEXT COMMENT 'Schedule.PlanningHorizon.End',
Schdl_PlnningHorizon_Strt TEXT COMMENT 'Schedule.PlanningHorizon.Start',
Schdl_SrvCtgry_Cdg_Cd TEXT COMMENT 'Schedule.ServiceCategory.Coding.Code',
Schdl_SrvCtgry_Cdg_Dsply TEXT COMMENT 'Schedule.ServiceCategory.Coding.Display',
Schdl_SrvCtgry_Cdg_Sys TEXT COMMENT 'Schedule.ServiceCategory.Coding.System',
Schdl_SrvCtgry_Cdg_UsrSltd TEXT COMMENT 'Schedule.ServiceCategory.Coding.UserSelected',
Schdl_SrvCtgry_Cdg_Vrsn TEXT COMMENT 'Schedule.ServiceCategory.Coding.Version',
Schdl_SrvCtgry_Txt TEXT COMMENT 'Schedule.ServiceCategory.Text',
Schdl_SrvTyp_Cdg_Cd TEXT COMMENT 'Schedule.ServiceType.Coding.Code',
Schdl_SrvTyp_Cdg_Dsply TEXT COMMENT 'Schedule.ServiceType.Coding.Display',
Schdl_SrvTyp_Cdg_Sys TEXT COMMENT 'Schedule.ServiceType.Coding.System',
Schdl_SrvTyp_Cdg_UsrSltd TEXT COMMENT 'Schedule.ServiceType.Coding.UserSelected',
Schdl_SrvTyp_Cdg_Vrsn TEXT COMMENT 'Schedule.ServiceType.Coding.Version',
Schdl_SrvTyp_Txt TEXT COMMENT 'Schedule.ServiceType.Text',
Schdl_Spclty_Cdg_Cd TEXT COMMENT 'Schedule.Specialty.Coding.Code',
Schdl_Spclty_Cdg_Dsply TEXT COMMENT 'Schedule.Specialty.Coding.Display',
Schdl_Spclty_Cdg_Sys TEXT COMMENT 'Schedule.Specialty.Coding.System',
Schdl_Spclty_Cdg_UsrSltd TEXT COMMENT 'Schedule.Specialty.Coding.UserSelected',
Schdl_Spclty_Cdg_Vrsn TEXT COMMENT 'Schedule.Specialty.Coding.Version',
Schdl_Spclty_Txt TEXT COMMENT 'Schedule.Specialty.Text',
PRIMARY KEY(id)) ENGINE=MyISAM
    ROW_FORMAT=COMPRESSED 
    KEY_BLOCK_SIZE=8;