drop table if exists `Slot`;
CREATE TABLE `Slot` (
 id varchar(64),
Slot_AppmntTyp_Cdg_Cd TEXT COMMENT 'Slot.AppointmentType.Coding.Code',
Slot_AppmntTyp_Cdg_Dsply TEXT COMMENT 'Slot.AppointmentType.Coding.Display',
Slot_AppmntTyp_Cdg_Sys TEXT COMMENT 'Slot.AppointmentType.Coding.System',
Slot_AppmntTyp_Cdg_UsrSltd TEXT COMMENT 'Slot.AppointmentType.Coding.UserSelected',
Slot_AppmntTyp_Cdg_Vrsn TEXT COMMENT 'Slot.AppointmentType.Coding.Version',
Slot_AppmntTyp_Txt TEXT COMMENT 'Slot.AppointmentType.Text',
Slot_Comment TEXT COMMENT 'Slot.Comment',
Slot_End TEXT COMMENT 'Slot.End',
Slot_Id_Assigner TEXT COMMENT 'Slot.Identifier.Assigner',
Slot_Id_Prd_End TEXT COMMENT 'Slot.Identifier.Period.End',
Slot_Id_Prd_Strt TEXT COMMENT 'Slot.Identifier.Period.Start',
Slot_Id_Sys TEXT COMMENT 'Slot.Identifier.System',
Slot_Id_Typ_Cdg_Cd TEXT COMMENT 'Slot.Identifier.Type.Coding.Code',
Slot_Id_Typ_Cdg_Dsply TEXT COMMENT 'Slot.Identifier.Type.Coding.Display',
Slot_Id_Typ_Cdg_Sys TEXT COMMENT 'Slot.Identifier.Type.Coding.System',
Slot_Id_Typ_Cdg_UsrSltd TEXT COMMENT 'Slot.Identifier.Type.Coding.UserSelected',
Slot_Id_Typ_Cdg_Vrsn TEXT COMMENT 'Slot.Identifier.Type.Coding.Version',
Slot_Id_Typ_Txt TEXT COMMENT 'Slot.Identifier.Type.Text',
Slot_Id_Use TEXT COMMENT 'Slot.Identifier.Use',
Slot_Id_Vl TEXT COMMENT 'Slot.Identifier.Value',
Slot_Overbooked TEXT COMMENT 'Slot.Overbooked',
Slot_Schdl TEXT COMMENT 'Slot.Schedule',
Slot_SrvCtgry_Cdg_Cd TEXT COMMENT 'Slot.ServiceCategory.Coding.Code',
Slot_SrvCtgry_Cdg_Dsply TEXT COMMENT 'Slot.ServiceCategory.Coding.Display',
Slot_SrvCtgry_Cdg_Sys TEXT COMMENT 'Slot.ServiceCategory.Coding.System',
Slot_SrvCtgry_Cdg_UsrSltd TEXT COMMENT 'Slot.ServiceCategory.Coding.UserSelected',
Slot_SrvCtgry_Cdg_Vrsn TEXT COMMENT 'Slot.ServiceCategory.Coding.Version',
Slot_SrvCtgry_Txt TEXT COMMENT 'Slot.ServiceCategory.Text',
Slot_SrvTyp_Cdg_Cd TEXT COMMENT 'Slot.ServiceType.Coding.Code',
Slot_SrvTyp_Cdg_Dsply TEXT COMMENT 'Slot.ServiceType.Coding.Display',
Slot_SrvTyp_Cdg_Sys TEXT COMMENT 'Slot.ServiceType.Coding.System',
Slot_SrvTyp_Cdg_UsrSltd TEXT COMMENT 'Slot.ServiceType.Coding.UserSelected',
Slot_SrvTyp_Cdg_Vrsn TEXT COMMENT 'Slot.ServiceType.Coding.Version',
Slot_SrvTyp_Txt TEXT COMMENT 'Slot.ServiceType.Text',
Slot_Spclty_Cdg_Cd TEXT COMMENT 'Slot.Specialty.Coding.Code',
Slot_Spclty_Cdg_Dsply TEXT COMMENT 'Slot.Specialty.Coding.Display',
Slot_Spclty_Cdg_Sys TEXT COMMENT 'Slot.Specialty.Coding.System',
Slot_Spclty_Cdg_UsrSltd TEXT COMMENT 'Slot.Specialty.Coding.UserSelected',
Slot_Spclty_Cdg_Vrsn TEXT COMMENT 'Slot.Specialty.Coding.Version',
Slot_Spclty_Txt TEXT COMMENT 'Slot.Specialty.Text',
Slot_Strt TEXT COMMENT 'Slot.Start',
Slot_Sts TEXT COMMENT 'Slot.Status',
PRIMARY KEY(id)) ENGINE=MyISAM
    ROW_FORMAT=COMPRESSED 
    KEY_BLOCK_SIZE=8;