drop table if exists `Slot`;
CREATE TABLE `Slot` (
 id varchar(64),
Slot_AppmntTyp_Cdg_Cd TEXT,
Slot_AppmntTyp_Cdg_Dsply TEXT,
Slot_AppmntTyp_Cdg_Sys TEXT,
Slot_AppmntTyp_Cdg_UsrSltd TEXT,
Slot_AppmntTyp_Cdg_Vrsn TEXT,
Slot_AppmntTyp_Txt TEXT,
Slot_Comment TEXT,
Slot_End TEXT,
Slot_Id_Assigner TEXT,
Slot_Id_Prd_End TEXT,
Slot_Id_Prd_Strt TEXT,
Slot_Id_Sys TEXT,
Slot_Id_Typ_Cdg_Cd TEXT,
Slot_Id_Typ_Cdg_Dsply TEXT,
Slot_Id_Typ_Cdg_Sys TEXT,
Slot_Id_Typ_Cdg_UsrSltd TEXT,
Slot_Id_Typ_Cdg_Vrsn TEXT,
Slot_Id_Typ_Txt TEXT,
Slot_Id_Use TEXT,
Slot_Id_Vl TEXT,
Slot_Overbooked TEXT,
Slot_Schdl TEXT,
Slot_SrvCtgry_Cdg_Cd TEXT,
Slot_SrvCtgry_Cdg_Dsply TEXT,
Slot_SrvCtgry_Cdg_Sys TEXT,
Slot_SrvCtgry_Cdg_UsrSltd TEXT,
Slot_SrvCtgry_Cdg_Vrsn TEXT,
Slot_SrvCtgry_Txt TEXT,
Slot_SrvTyp_Cdg_Cd TEXT,
Slot_SrvTyp_Cdg_Dsply TEXT,
Slot_SrvTyp_Cdg_Sys TEXT,
Slot_SrvTyp_Cdg_UsrSltd TEXT,
Slot_SrvTyp_Cdg_Vrsn TEXT,
Slot_SrvTyp_Txt TEXT,
Slot_Spclty_Cdg_Cd TEXT,
Slot_Spclty_Cdg_Dsply TEXT,
Slot_Spclty_Cdg_Sys TEXT,
Slot_Spclty_Cdg_UsrSltd TEXT,
Slot_Spclty_Cdg_Vrsn TEXT,
Slot_Spclty_Txt TEXT,
Slot_Strt TEXT,
Slot_Sts TEXT,
PRIMARY KEY(id)) ENGINE=MyISAM
    ROW_FORMAT=COMPRESSED 
    KEY_BLOCK_SIZE=8;