drop table if exists `VisionPrescription`;
CREATE TABLE `VisionPrescription` (
 id varchar(64),
VisionPrescription_Created TEXT COMMENT 'VisionPrescription.Created',
VisionPrescription_DtWritten TEXT COMMENT 'VisionPrescription.DateWritten',
VisionPrescription_Enc TEXT COMMENT 'VisionPrescription.Encounter',
VisionPrescription_Id_Assigner TEXT COMMENT 'VisionPrescription.Identifier.Assigner',
VisionPrescription_Id_Prd_End TEXT COMMENT 'VisionPrescription.Identifier.Period.End',
VisionPrescription_Id_Prd_Strt TEXT COMMENT 'VisionPrescription.Identifier.Period.Start',
VisionPrescription_Id_Sys TEXT COMMENT 'VisionPrescription.Identifier.System',
VisionPrescription_Id_Typ_Cdg_Cd TEXT COMMENT 'VisionPrescription.Identifier.Type.Coding.Code',
VisionPrescription_Id_Typ_Cdg_Dsply TEXT COMMENT 'VisionPrescription.Identifier.Type.Coding.Display',
VisionPrescription_Id_Typ_Cdg_Sys TEXT COMMENT 'VisionPrescription.Identifier.Type.Coding.System',
VisionPrescription_Id_Typ_Cdg_UsrSltd TEXT COMMENT 'VisionPrescription.Identifier.Type.Coding.UserSelected',
VisionPrescription_Id_Typ_Cdg_Vrsn TEXT COMMENT 'VisionPrescription.Identifier.Type.Coding.Version',
VisionPrescription_Id_Typ_Txt TEXT COMMENT 'VisionPrescription.Identifier.Type.Text',
VisionPrescription_Id_Use TEXT COMMENT 'VisionPrescription.Identifier.Use',
VisionPrescription_Id_Vl TEXT COMMENT 'VisionPrescription.Identifier.Value',
VisionPrescription_LensSpcfctn_Add TEXT COMMENT 'VisionPrescription.LensSpecification.Add',
VisionPrescription_LensSpcfctn_Axis TEXT COMMENT 'VisionPrescription.LensSpecification.Axis',
VisionPrescription_LensSpcfctn_BackCurve TEXT COMMENT 'VisionPrescription.LensSpecification.BackCurve',
VisionPrescription_LensSpcfctn_Brand TEXT COMMENT 'VisionPrescription.LensSpecification.Brand',
VisionPrescription_LensSpcfctn_Color TEXT COMMENT 'VisionPrescription.LensSpecification.Color',
VisionPrescription_LensSpcfctn_Cylinder TEXT COMMENT 'VisionPrescription.LensSpecification.Cylinder',
VisionPrescription_LensSpcfctn_Diameter TEXT COMMENT 'VisionPrescription.LensSpecification.Diameter',
VisionPrescription_LensSpcfctn_Duration_Cd TEXT COMMENT 'VisionPrescription.LensSpecification.Duration.Code',
VisionPrescription_LensSpcfctn_Duration_Cmprtr TEXT COMMENT 'VisionPrescription.LensSpecification.Duration.Comparator',
VisionPrescription_LensSpcfctn_Duration_Sys TEXT COMMENT 'VisionPrescription.LensSpecification.Duration.System',
VisionPrescription_LensSpcfctn_Duration_Unt TEXT COMMENT 'VisionPrescription.LensSpecification.Duration.Unit',
VisionPrescription_LensSpcfctn_Duration_Vl TEXT COMMENT 'VisionPrescription.LensSpecification.Duration.Value',
VisionPrescription_LensSpcfctn_Eye TEXT COMMENT 'VisionPrescription.LensSpecification.Eye',
VisionPrescription_LensSpcfctn_Nt_AthrRfrnc TEXT COMMENT 'VisionPrescription.LensSpecification.Note.AuthorReference',
VisionPrescription_LensSpcfctn_Nt_AthrStrgTyp TEXT COMMENT 'VisionPrescription.LensSpecification.Note.AuthorStringType',
VisionPrescription_LensSpcfctn_Nt_Txt TEXT COMMENT 'VisionPrescription.LensSpecification.Note.Text',
VisionPrescription_LensSpcfctn_Nt_Time TEXT COMMENT 'VisionPrescription.LensSpecification.Note.Time',
VisionPrescription_LensSpcfctn_Power TEXT COMMENT 'VisionPrescription.LensSpecification.Power',
VisionPrescription_LensSpcfctn_Prism_Amnt TEXT COMMENT 'VisionPrescription.LensSpecification.Prism.Amount',
VisionPrescription_LensSpcfctn_Prism_Base TEXT COMMENT 'VisionPrescription.LensSpecification.Prism.Base',
VisionPrescription_LensSpcfctn_Prdct_Cdg_Cd TEXT COMMENT 'VisionPrescription.LensSpecification.Product.Coding.Code',
VisionPrescription_LensSpcfctn_Prdct_Cdg_Dsply TEXT COMMENT 'VisionPrescription.LensSpecification.Product.Coding.Display',
VisionPrescription_LensSpcfctn_Prdct_Cdg_Sys TEXT COMMENT 'VisionPrescription.LensSpecification.Product.Coding.System',
VisionPrescription_LensSpcfctn_Prdct_Cdg_UsrSltd TEXT COMMENT 'VisionPrescription.LensSpecification.Product.Coding.UserSelected',
VisionPrescription_LensSpcfctn_Prdct_Cdg_Vrsn TEXT COMMENT 'VisionPrescription.LensSpecification.Product.Coding.Version',
VisionPrescription_LensSpcfctn_Prdct_Txt TEXT COMMENT 'VisionPrescription.LensSpecification.Product.Text',
VisionPrescription_LensSpcfctn_Sphere TEXT COMMENT 'VisionPrescription.LensSpecification.Sphere',
VisionPrescription_Pnt TEXT COMMENT 'VisionPrescription.Patient',
VisionPrescription_Prescriber TEXT COMMENT 'VisionPrescription.Prescriber',
VisionPrescription_Sts TEXT COMMENT 'VisionPrescription.Status',
PRIMARY KEY(id)) ENGINE=MyISAM
    ROW_FORMAT=COMPRESSED 
    KEY_BLOCK_SIZE=8;