// // default package
package main.templateoutput.Model;
// Generated Nov 18, 2021, 1:47:20 PM by Hibernate Tools 5.6.1.Final



/**
 * Account generated by hbm2java
 */
public class Account  implements java.io.Serializable {


     private String accountIdentifierCodingCode;
     private String accntDntfrCdngSrSlctd;
     private String accountIdentifierCodingDisplay;
     private String accountIdentifierCodingVersion;
     private String accountIdentifierCodingSystem;
     private String accountStatus;
     private String accountTypeCodingUserSelected;
     private String accountTypeCodingCode;
     private String accountTypeCodingDisplay;
     private String accountTypeCodingVersion;
     private String accountTypeCodingSystem;
     private String accountName;
     private String accountSubject;
     private String accntSrvcPrdCdngSrSlctd;
     private String accountServicePeriodCodingCode;
     private String accntSrvcPrdCdngDsplay;
     private String accntSrvcPrdCdngVrsn;
     private String accntSrvcPrdCdngSstm;
     private String accountCoverage;
     private String accountCoverageCoverage;
     private String accountCoveragePriority;
     private String accountOwner;
     private String accountDescription;
     private String accountGuarantor;
     private String accountGuarantorParty;
     private String accountGuarantorOnHold;
     private String accntGrntrPrdCdngSrSlctd;
     private String accntGrntrPrdCdngCde;
     private String accntGrntrPrdCdngDsplay;
     private String accntGrntrPrdCdngVrsn;
     private String accntGrntrPrdCdngSstm;
     private String accountPartOf;

    public Account() {
    }

	
    public Account(String accountIdentifierCodingCode) {
        this.accountIdentifierCodingCode = accountIdentifierCodingCode;
    }
    public Account(String accountIdentifierCodingCode, String accntDntfrCdngSrSlctd, String accountIdentifierCodingDisplay, String accountIdentifierCodingVersion, String accountIdentifierCodingSystem, String accountStatus, String accountTypeCodingUserSelected, String accountTypeCodingCode, String accountTypeCodingDisplay, String accountTypeCodingVersion, String accountTypeCodingSystem, String accountName, String accountSubject, String accntSrvcPrdCdngSrSlctd, String accountServicePeriodCodingCode, String accntSrvcPrdCdngDsplay, String accntSrvcPrdCdngVrsn, String accntSrvcPrdCdngSstm, String accountCoverage, String accountCoverageCoverage, String accountCoveragePriority, String accountOwner, String accountDescription, String accountGuarantor, String accountGuarantorParty, String accountGuarantorOnHold, String accntGrntrPrdCdngSrSlctd, String accntGrntrPrdCdngCde, String accntGrntrPrdCdngDsplay, String accntGrntrPrdCdngVrsn, String accntGrntrPrdCdngSstm, String accountPartOf) {
       this.accountIdentifierCodingCode = accountIdentifierCodingCode;
       this.accntDntfrCdngSrSlctd = accntDntfrCdngSrSlctd;
       this.accountIdentifierCodingDisplay = accountIdentifierCodingDisplay;
       this.accountIdentifierCodingVersion = accountIdentifierCodingVersion;
       this.accountIdentifierCodingSystem = accountIdentifierCodingSystem;
       this.accountStatus = accountStatus;
       this.accountTypeCodingUserSelected = accountTypeCodingUserSelected;
       this.accountTypeCodingCode = accountTypeCodingCode;
       this.accountTypeCodingDisplay = accountTypeCodingDisplay;
       this.accountTypeCodingVersion = accountTypeCodingVersion;
       this.accountTypeCodingSystem = accountTypeCodingSystem;
       this.accountName = accountName;
       this.accountSubject = accountSubject;
       this.accntSrvcPrdCdngSrSlctd = accntSrvcPrdCdngSrSlctd;
       this.accountServicePeriodCodingCode = accountServicePeriodCodingCode;
       this.accntSrvcPrdCdngDsplay = accntSrvcPrdCdngDsplay;
       this.accntSrvcPrdCdngVrsn = accntSrvcPrdCdngVrsn;
       this.accntSrvcPrdCdngSstm = accntSrvcPrdCdngSstm;
       this.accountCoverage = accountCoverage;
       this.accountCoverageCoverage = accountCoverageCoverage;
       this.accountCoveragePriority = accountCoveragePriority;
       this.accountOwner = accountOwner;
       this.accountDescription = accountDescription;
       this.accountGuarantor = accountGuarantor;
       this.accountGuarantorParty = accountGuarantorParty;
       this.accountGuarantorOnHold = accountGuarantorOnHold;
       this.accntGrntrPrdCdngSrSlctd = accntGrntrPrdCdngSrSlctd;
       this.accntGrntrPrdCdngCde = accntGrntrPrdCdngCde;
       this.accntGrntrPrdCdngDsplay = accntGrntrPrdCdngDsplay;
       this.accntGrntrPrdCdngVrsn = accntGrntrPrdCdngVrsn;
       this.accntGrntrPrdCdngSstm = accntGrntrPrdCdngSstm;
       this.accountPartOf = accountPartOf;
    }
   
    public String getAccountIdentifierCodingCode() {
        return this.accountIdentifierCodingCode;
    }
    
    public void setAccountIdentifierCodingCode(String accountIdentifierCodingCode) {
        this.accountIdentifierCodingCode = accountIdentifierCodingCode;
    }
    
    
    
    public String getAccntDntfrCdngSrSlctd() {
        return this.accntDntfrCdngSrSlctd;
    }
    
    public void setAccntDntfrCdngSrSlctd(String accntDntfrCdngSrSlctd) {
        this.accntDntfrCdngSrSlctd = accntDntfrCdngSrSlctd;
    }
    
    
    
    public String getAccountIdentifierCodingDisplay() {
        return this.accountIdentifierCodingDisplay;
    }
    
    public void setAccountIdentifierCodingDisplay(String accountIdentifierCodingDisplay) {
        this.accountIdentifierCodingDisplay = accountIdentifierCodingDisplay;
    }
    
    
    
    public String getAccountIdentifierCodingVersion() {
        return this.accountIdentifierCodingVersion;
    }
    
    public void setAccountIdentifierCodingVersion(String accountIdentifierCodingVersion) {
        this.accountIdentifierCodingVersion = accountIdentifierCodingVersion;
    }
    
    
    
    public String getAccountIdentifierCodingSystem() {
        return this.accountIdentifierCodingSystem;
    }
    
    public void setAccountIdentifierCodingSystem(String accountIdentifierCodingSystem) {
        this.accountIdentifierCodingSystem = accountIdentifierCodingSystem;
    }
    
    
    
    public String getAccountStatus() {
        return this.accountStatus;
    }
    
    public void setAccountStatus(String accountStatus) {
        this.accountStatus = accountStatus;
    }
    
    
    
    public String getAccountTypeCodingUserSelected() {
        return this.accountTypeCodingUserSelected;
    }
    
    public void setAccountTypeCodingUserSelected(String accountTypeCodingUserSelected) {
        this.accountTypeCodingUserSelected = accountTypeCodingUserSelected;
    }
    
    
    
    public String getAccountTypeCodingCode() {
        return this.accountTypeCodingCode;
    }
    
    public void setAccountTypeCodingCode(String accountTypeCodingCode) {
        this.accountTypeCodingCode = accountTypeCodingCode;
    }
    
    
    
    public String getAccountTypeCodingDisplay() {
        return this.accountTypeCodingDisplay;
    }
    
    public void setAccountTypeCodingDisplay(String accountTypeCodingDisplay) {
        this.accountTypeCodingDisplay = accountTypeCodingDisplay;
    }
    
    
    
    public String getAccountTypeCodingVersion() {
        return this.accountTypeCodingVersion;
    }
    
    public void setAccountTypeCodingVersion(String accountTypeCodingVersion) {
        this.accountTypeCodingVersion = accountTypeCodingVersion;
    }
    
    
    
    public String getAccountTypeCodingSystem() {
        return this.accountTypeCodingSystem;
    }
    
    public void setAccountTypeCodingSystem(String accountTypeCodingSystem) {
        this.accountTypeCodingSystem = accountTypeCodingSystem;
    }
    
    
    
    public String getAccountName() {
        return this.accountName;
    }
    
    public void setAccountName(String accountName) {
        this.accountName = accountName;
    }
    
    
    
    public String getAccountSubject() {
        return this.accountSubject;
    }
    
    public void setAccountSubject(String accountSubject) {
        this.accountSubject = accountSubject;
    }
    
    
    
    public String getAccntSrvcPrdCdngSrSlctd() {
        return this.accntSrvcPrdCdngSrSlctd;
    }
    
    public void setAccntSrvcPrdCdngSrSlctd(String accntSrvcPrdCdngSrSlctd) {
        this.accntSrvcPrdCdngSrSlctd = accntSrvcPrdCdngSrSlctd;
    }
    
    
    
    public String getAccountServicePeriodCodingCode() {
        return this.accountServicePeriodCodingCode;
    }
    
    public void setAccountServicePeriodCodingCode(String accountServicePeriodCodingCode) {
        this.accountServicePeriodCodingCode = accountServicePeriodCodingCode;
    }
    
    
    
    public String getAccntSrvcPrdCdngDsplay() {
        return this.accntSrvcPrdCdngDsplay;
    }
    
    public void setAccntSrvcPrdCdngDsplay(String accntSrvcPrdCdngDsplay) {
        this.accntSrvcPrdCdngDsplay = accntSrvcPrdCdngDsplay;
    }
    
    
    
    public String getAccntSrvcPrdCdngVrsn() {
        return this.accntSrvcPrdCdngVrsn;
    }
    
    public void setAccntSrvcPrdCdngVrsn(String accntSrvcPrdCdngVrsn) {
        this.accntSrvcPrdCdngVrsn = accntSrvcPrdCdngVrsn;
    }
    
    
    
    public String getAccntSrvcPrdCdngSstm() {
        return this.accntSrvcPrdCdngSstm;
    }
    
    public void setAccntSrvcPrdCdngSstm(String accntSrvcPrdCdngSstm) {
        this.accntSrvcPrdCdngSstm = accntSrvcPrdCdngSstm;
    }
    
    
    
    public String getAccountCoverage() {
        return this.accountCoverage;
    }
    
    public void setAccountCoverage(String accountCoverage) {
        this.accountCoverage = accountCoverage;
    }
    
    
    
    public String getAccountCoverageCoverage() {
        return this.accountCoverageCoverage;
    }
    
    public void setAccountCoverageCoverage(String accountCoverageCoverage) {
        this.accountCoverageCoverage = accountCoverageCoverage;
    }
    
    
    
    public String getAccountCoveragePriority() {
        return this.accountCoveragePriority;
    }
    
    public void setAccountCoveragePriority(String accountCoveragePriority) {
        this.accountCoveragePriority = accountCoveragePriority;
    }
    
    
    
    public String getAccountOwner() {
        return this.accountOwner;
    }
    
    public void setAccountOwner(String accountOwner) {
        this.accountOwner = accountOwner;
    }
    
    
    
    public String getAccountDescription() {
        return this.accountDescription;
    }
    
    public void setAccountDescription(String accountDescription) {
        this.accountDescription = accountDescription;
    }
    
    
    
    public String getAccountGuarantor() {
        return this.accountGuarantor;
    }
    
    public void setAccountGuarantor(String accountGuarantor) {
        this.accountGuarantor = accountGuarantor;
    }
    
    
    
    public String getAccountGuarantorParty() {
        return this.accountGuarantorParty;
    }
    
    public void setAccountGuarantorParty(String accountGuarantorParty) {
        this.accountGuarantorParty = accountGuarantorParty;
    }
    
    
    
    public String getAccountGuarantorOnHold() {
        return this.accountGuarantorOnHold;
    }
    
    public void setAccountGuarantorOnHold(String accountGuarantorOnHold) {
        this.accountGuarantorOnHold = accountGuarantorOnHold;
    }
    
    
    
    public String getAccntGrntrPrdCdngSrSlctd() {
        return this.accntGrntrPrdCdngSrSlctd;
    }
    
    public void setAccntGrntrPrdCdngSrSlctd(String accntGrntrPrdCdngSrSlctd) {
        this.accntGrntrPrdCdngSrSlctd = accntGrntrPrdCdngSrSlctd;
    }
    
    
    
    public String getAccntGrntrPrdCdngCde() {
        return this.accntGrntrPrdCdngCde;
    }
    
    public void setAccntGrntrPrdCdngCde(String accntGrntrPrdCdngCde) {
        this.accntGrntrPrdCdngCde = accntGrntrPrdCdngCde;
    }
    
    
    
    public String getAccntGrntrPrdCdngDsplay() {
        return this.accntGrntrPrdCdngDsplay;
    }
    
    public void setAccntGrntrPrdCdngDsplay(String accntGrntrPrdCdngDsplay) {
        this.accntGrntrPrdCdngDsplay = accntGrntrPrdCdngDsplay;
    }
    
    
    
    public String getAccntGrntrPrdCdngVrsn() {
        return this.accntGrntrPrdCdngVrsn;
    }
    
    public void setAccntGrntrPrdCdngVrsn(String accntGrntrPrdCdngVrsn) {
        this.accntGrntrPrdCdngVrsn = accntGrntrPrdCdngVrsn;
    }
    
    
    
    public String getAccntGrntrPrdCdngSstm() {
        return this.accntGrntrPrdCdngSstm;
    }
    
    public void setAccntGrntrPrdCdngSstm(String accntGrntrPrdCdngSstm) {
        this.accntGrntrPrdCdngSstm = accntGrntrPrdCdngSstm;
    }
    
    
    
    public String getAccountPartOf() {
        return this.accountPartOf;
    }
    
    public void setAccountPartOf(String accountPartOf) {
        this.accountPartOf = accountPartOf;
    }
    
    
    




}


