// // default package
package main.templateoutput.Model;
// Generated Nov 18, 2021, 1:47:20 PM by Hibernate Tools 5.6.1.Final



/**
 * Medicinalproductmanufactured generated by hbm2java
 */
public class Medicinalproductmanufactured  implements java.io.Serializable {


     private String mpmnfctrdMnfctrdDsFrmCdngCde;
     private String mpmnfctrdMnfctrdDsFrmCdngSrSlctd;
     private String mpmnfctrdMnfctrdDsFrmCdngDsplay;
     private String mpmnfctrdMnfctrdDsFrmCdngVrsn;
     private String mpmnfctrdMnfctrdDsFrmCdngSstm;
     private String mpmnfctrdNtfPrsnttnCdngSrSlctd;
     private String mpmnfctrdNtfPrsnttnCdngCde;
     private String mpmnfctrdNtfPrsnttnCdngDsplay;
     private String mpmnfctrdNtfPrsnttnCdngVrsn;
     private String mpmnfctrdNtfPrsnttnCdngSstm;
     private String mpmnfctrdQnttCdngSrSlctd;
     private String mpmnfctrdQnttCdngCde;
     private String mpmnfctrdQnttCdngDsplay;
     private String mpmnfctrdQnttCdngVrsn;
     private String mpmnfctrdQnttCdngSstm;
     private String mpmanufacturedManufacturer;
     private String mpmanufacturedIngredient;
     private String mpmanufacturedPhysicalchrctrs;
     private String mpmnfctrdThrchrctrsCdngSrSlctd;
     private String mpmnfctrdThrchrctrsCdngCde;
     private String mpmnfctrdThrchrctrsCdngDsplay;
     private String mpmnfctrdThrchrctrsCdngVrsn;
     private String mpmnfctrdThrchrctrsCdngSstm;

    public Medicinalproductmanufactured() {
    }

	
    public Medicinalproductmanufactured(String mpmnfctrdMnfctrdDsFrmCdngCde) {
        this.mpmnfctrdMnfctrdDsFrmCdngCde = mpmnfctrdMnfctrdDsFrmCdngCde;
    }
    public Medicinalproductmanufactured(String mpmnfctrdMnfctrdDsFrmCdngCde, String mpmnfctrdMnfctrdDsFrmCdngSrSlctd, String mpmnfctrdMnfctrdDsFrmCdngDsplay, String mpmnfctrdMnfctrdDsFrmCdngVrsn, String mpmnfctrdMnfctrdDsFrmCdngSstm, String mpmnfctrdNtfPrsnttnCdngSrSlctd, String mpmnfctrdNtfPrsnttnCdngCde, String mpmnfctrdNtfPrsnttnCdngDsplay, String mpmnfctrdNtfPrsnttnCdngVrsn, String mpmnfctrdNtfPrsnttnCdngSstm, String mpmnfctrdQnttCdngSrSlctd, String mpmnfctrdQnttCdngCde, String mpmnfctrdQnttCdngDsplay, String mpmnfctrdQnttCdngVrsn, String mpmnfctrdQnttCdngSstm, String mpmanufacturedManufacturer, String mpmanufacturedIngredient, String mpmanufacturedPhysicalchrctrs, String mpmnfctrdThrchrctrsCdngSrSlctd, String mpmnfctrdThrchrctrsCdngCde, String mpmnfctrdThrchrctrsCdngDsplay, String mpmnfctrdThrchrctrsCdngVrsn, String mpmnfctrdThrchrctrsCdngSstm) {
       this.mpmnfctrdMnfctrdDsFrmCdngCde = mpmnfctrdMnfctrdDsFrmCdngCde;
       this.mpmnfctrdMnfctrdDsFrmCdngSrSlctd = mpmnfctrdMnfctrdDsFrmCdngSrSlctd;
       this.mpmnfctrdMnfctrdDsFrmCdngDsplay = mpmnfctrdMnfctrdDsFrmCdngDsplay;
       this.mpmnfctrdMnfctrdDsFrmCdngVrsn = mpmnfctrdMnfctrdDsFrmCdngVrsn;
       this.mpmnfctrdMnfctrdDsFrmCdngSstm = mpmnfctrdMnfctrdDsFrmCdngSstm;
       this.mpmnfctrdNtfPrsnttnCdngSrSlctd = mpmnfctrdNtfPrsnttnCdngSrSlctd;
       this.mpmnfctrdNtfPrsnttnCdngCde = mpmnfctrdNtfPrsnttnCdngCde;
       this.mpmnfctrdNtfPrsnttnCdngDsplay = mpmnfctrdNtfPrsnttnCdngDsplay;
       this.mpmnfctrdNtfPrsnttnCdngVrsn = mpmnfctrdNtfPrsnttnCdngVrsn;
       this.mpmnfctrdNtfPrsnttnCdngSstm = mpmnfctrdNtfPrsnttnCdngSstm;
       this.mpmnfctrdQnttCdngSrSlctd = mpmnfctrdQnttCdngSrSlctd;
       this.mpmnfctrdQnttCdngCde = mpmnfctrdQnttCdngCde;
       this.mpmnfctrdQnttCdngDsplay = mpmnfctrdQnttCdngDsplay;
       this.mpmnfctrdQnttCdngVrsn = mpmnfctrdQnttCdngVrsn;
       this.mpmnfctrdQnttCdngSstm = mpmnfctrdQnttCdngSstm;
       this.mpmanufacturedManufacturer = mpmanufacturedManufacturer;
       this.mpmanufacturedIngredient = mpmanufacturedIngredient;
       this.mpmanufacturedPhysicalchrctrs = mpmanufacturedPhysicalchrctrs;
       this.mpmnfctrdThrchrctrsCdngSrSlctd = mpmnfctrdThrchrctrsCdngSrSlctd;
       this.mpmnfctrdThrchrctrsCdngCde = mpmnfctrdThrchrctrsCdngCde;
       this.mpmnfctrdThrchrctrsCdngDsplay = mpmnfctrdThrchrctrsCdngDsplay;
       this.mpmnfctrdThrchrctrsCdngVrsn = mpmnfctrdThrchrctrsCdngVrsn;
       this.mpmnfctrdThrchrctrsCdngSstm = mpmnfctrdThrchrctrsCdngSstm;
    }
   
    public String getMpmnfctrdMnfctrdDsFrmCdngCde() {
        return this.mpmnfctrdMnfctrdDsFrmCdngCde;
    }
    
    public void setMpmnfctrdMnfctrdDsFrmCdngCde(String mpmnfctrdMnfctrdDsFrmCdngCde) {
        this.mpmnfctrdMnfctrdDsFrmCdngCde = mpmnfctrdMnfctrdDsFrmCdngCde;
    }
    
    
    
    public String getMpmnfctrdMnfctrdDsFrmCdngSrSlctd() {
        return this.mpmnfctrdMnfctrdDsFrmCdngSrSlctd;
    }
    
    public void setMpmnfctrdMnfctrdDsFrmCdngSrSlctd(String mpmnfctrdMnfctrdDsFrmCdngSrSlctd) {
        this.mpmnfctrdMnfctrdDsFrmCdngSrSlctd = mpmnfctrdMnfctrdDsFrmCdngSrSlctd;
    }
    
    
    
    public String getMpmnfctrdMnfctrdDsFrmCdngDsplay() {
        return this.mpmnfctrdMnfctrdDsFrmCdngDsplay;
    }
    
    public void setMpmnfctrdMnfctrdDsFrmCdngDsplay(String mpmnfctrdMnfctrdDsFrmCdngDsplay) {
        this.mpmnfctrdMnfctrdDsFrmCdngDsplay = mpmnfctrdMnfctrdDsFrmCdngDsplay;
    }
    
    
    
    public String getMpmnfctrdMnfctrdDsFrmCdngVrsn() {
        return this.mpmnfctrdMnfctrdDsFrmCdngVrsn;
    }
    
    public void setMpmnfctrdMnfctrdDsFrmCdngVrsn(String mpmnfctrdMnfctrdDsFrmCdngVrsn) {
        this.mpmnfctrdMnfctrdDsFrmCdngVrsn = mpmnfctrdMnfctrdDsFrmCdngVrsn;
    }
    
    
    
    public String getMpmnfctrdMnfctrdDsFrmCdngSstm() {
        return this.mpmnfctrdMnfctrdDsFrmCdngSstm;
    }
    
    public void setMpmnfctrdMnfctrdDsFrmCdngSstm(String mpmnfctrdMnfctrdDsFrmCdngSstm) {
        this.mpmnfctrdMnfctrdDsFrmCdngSstm = mpmnfctrdMnfctrdDsFrmCdngSstm;
    }
    
    
    
    public String getMpmnfctrdNtfPrsnttnCdngSrSlctd() {
        return this.mpmnfctrdNtfPrsnttnCdngSrSlctd;
    }
    
    public void setMpmnfctrdNtfPrsnttnCdngSrSlctd(String mpmnfctrdNtfPrsnttnCdngSrSlctd) {
        this.mpmnfctrdNtfPrsnttnCdngSrSlctd = mpmnfctrdNtfPrsnttnCdngSrSlctd;
    }
    
    
    
    public String getMpmnfctrdNtfPrsnttnCdngCde() {
        return this.mpmnfctrdNtfPrsnttnCdngCde;
    }
    
    public void setMpmnfctrdNtfPrsnttnCdngCde(String mpmnfctrdNtfPrsnttnCdngCde) {
        this.mpmnfctrdNtfPrsnttnCdngCde = mpmnfctrdNtfPrsnttnCdngCde;
    }
    
    
    
    public String getMpmnfctrdNtfPrsnttnCdngDsplay() {
        return this.mpmnfctrdNtfPrsnttnCdngDsplay;
    }
    
    public void setMpmnfctrdNtfPrsnttnCdngDsplay(String mpmnfctrdNtfPrsnttnCdngDsplay) {
        this.mpmnfctrdNtfPrsnttnCdngDsplay = mpmnfctrdNtfPrsnttnCdngDsplay;
    }
    
    
    
    public String getMpmnfctrdNtfPrsnttnCdngVrsn() {
        return this.mpmnfctrdNtfPrsnttnCdngVrsn;
    }
    
    public void setMpmnfctrdNtfPrsnttnCdngVrsn(String mpmnfctrdNtfPrsnttnCdngVrsn) {
        this.mpmnfctrdNtfPrsnttnCdngVrsn = mpmnfctrdNtfPrsnttnCdngVrsn;
    }
    
    
    
    public String getMpmnfctrdNtfPrsnttnCdngSstm() {
        return this.mpmnfctrdNtfPrsnttnCdngSstm;
    }
    
    public void setMpmnfctrdNtfPrsnttnCdngSstm(String mpmnfctrdNtfPrsnttnCdngSstm) {
        this.mpmnfctrdNtfPrsnttnCdngSstm = mpmnfctrdNtfPrsnttnCdngSstm;
    }
    
    
    
    public String getMpmnfctrdQnttCdngSrSlctd() {
        return this.mpmnfctrdQnttCdngSrSlctd;
    }
    
    public void setMpmnfctrdQnttCdngSrSlctd(String mpmnfctrdQnttCdngSrSlctd) {
        this.mpmnfctrdQnttCdngSrSlctd = mpmnfctrdQnttCdngSrSlctd;
    }
    
    
    
    public String getMpmnfctrdQnttCdngCde() {
        return this.mpmnfctrdQnttCdngCde;
    }
    
    public void setMpmnfctrdQnttCdngCde(String mpmnfctrdQnttCdngCde) {
        this.mpmnfctrdQnttCdngCde = mpmnfctrdQnttCdngCde;
    }
    
    
    
    public String getMpmnfctrdQnttCdngDsplay() {
        return this.mpmnfctrdQnttCdngDsplay;
    }
    
    public void setMpmnfctrdQnttCdngDsplay(String mpmnfctrdQnttCdngDsplay) {
        this.mpmnfctrdQnttCdngDsplay = mpmnfctrdQnttCdngDsplay;
    }
    
    
    
    public String getMpmnfctrdQnttCdngVrsn() {
        return this.mpmnfctrdQnttCdngVrsn;
    }
    
    public void setMpmnfctrdQnttCdngVrsn(String mpmnfctrdQnttCdngVrsn) {
        this.mpmnfctrdQnttCdngVrsn = mpmnfctrdQnttCdngVrsn;
    }
    
    
    
    public String getMpmnfctrdQnttCdngSstm() {
        return this.mpmnfctrdQnttCdngSstm;
    }
    
    public void setMpmnfctrdQnttCdngSstm(String mpmnfctrdQnttCdngSstm) {
        this.mpmnfctrdQnttCdngSstm = mpmnfctrdQnttCdngSstm;
    }
    
    
    
    public String getMpmanufacturedManufacturer() {
        return this.mpmanufacturedManufacturer;
    }
    
    public void setMpmanufacturedManufacturer(String mpmanufacturedManufacturer) {
        this.mpmanufacturedManufacturer = mpmanufacturedManufacturer;
    }
    
    
    
    public String getMpmanufacturedIngredient() {
        return this.mpmanufacturedIngredient;
    }
    
    public void setMpmanufacturedIngredient(String mpmanufacturedIngredient) {
        this.mpmanufacturedIngredient = mpmanufacturedIngredient;
    }
    
    
    
    public String getMpmanufacturedPhysicalchrctrs() {
        return this.mpmanufacturedPhysicalchrctrs;
    }
    
    public void setMpmanufacturedPhysicalchrctrs(String mpmanufacturedPhysicalchrctrs) {
        this.mpmanufacturedPhysicalchrctrs = mpmanufacturedPhysicalchrctrs;
    }
    
    
    
    public String getMpmnfctrdThrchrctrsCdngSrSlctd() {
        return this.mpmnfctrdThrchrctrsCdngSrSlctd;
    }
    
    public void setMpmnfctrdThrchrctrsCdngSrSlctd(String mpmnfctrdThrchrctrsCdngSrSlctd) {
        this.mpmnfctrdThrchrctrsCdngSrSlctd = mpmnfctrdThrchrctrsCdngSrSlctd;
    }
    
    
    
    public String getMpmnfctrdThrchrctrsCdngCde() {
        return this.mpmnfctrdThrchrctrsCdngCde;
    }
    
    public void setMpmnfctrdThrchrctrsCdngCde(String mpmnfctrdThrchrctrsCdngCde) {
        this.mpmnfctrdThrchrctrsCdngCde = mpmnfctrdThrchrctrsCdngCde;
    }
    
    
    
    public String getMpmnfctrdThrchrctrsCdngDsplay() {
        return this.mpmnfctrdThrchrctrsCdngDsplay;
    }
    
    public void setMpmnfctrdThrchrctrsCdngDsplay(String mpmnfctrdThrchrctrsCdngDsplay) {
        this.mpmnfctrdThrchrctrsCdngDsplay = mpmnfctrdThrchrctrsCdngDsplay;
    }
    
    
    
    public String getMpmnfctrdThrchrctrsCdngVrsn() {
        return this.mpmnfctrdThrchrctrsCdngVrsn;
    }
    
    public void setMpmnfctrdThrchrctrsCdngVrsn(String mpmnfctrdThrchrctrsCdngVrsn) {
        this.mpmnfctrdThrchrctrsCdngVrsn = mpmnfctrdThrchrctrsCdngVrsn;
    }
    
    
    
    public String getMpmnfctrdThrchrctrsCdngSstm() {
        return this.mpmnfctrdThrchrctrsCdngSstm;
    }
    
    public void setMpmnfctrdThrchrctrsCdngSstm(String mpmnfctrdThrchrctrsCdngSstm) {
        this.mpmnfctrdThrchrctrsCdngSstm = mpmnfctrdThrchrctrsCdngSstm;
    }
    
    
    




}


