// // default package
package main.templateoutput.Model;
// Generated Nov 18, 2021, 1:47:20 PM by Hibernate Tools 5.6.1.Final



/**
 * Terminologycapabilities generated by hbm2java
 */
public class Terminologycapabilities  implements java.io.Serializable {


     private String terminologyCapabilitiesUrl;
     private String terminologyCapabilitiesVersion;
     private String terminologyCapabilitiesName;
     private String terminologyCapabilitiesTitle;
     private String terminologyCapabilitiesStatus;
     private String trmnlgCpbltsXprmntl;
     private String terminologyCapabilitiesDate;
     private String terminologyCapabilitiesPublisher;
     private String terminologyCapabilitiesContact;
     private String trmnlgCpbltsDscrptn;
     private String terminologyCapabilitiesUseContext;
     private String trmnlgCpbltsJrsdctnCdblCncptCdngSstm;
     private String trmnlgCpbltsJrsdctnCdblCncptCdngVrsn;
     private String trmnlgCpbltsJrsdctnCdblCncptCdngCde;
     private String trmnlgCpbltsJrsdctnCdblCncptCdngDsplay;
     private String trmnlgCpbltsJrsdctnCdblCncptCdngSrSlctd;
     private String trmnlgCpbltsJrsdctnCdblCncptTxtStrng;
     private String terminologyCapabilitiesPurpose;
     private String terminologyCapabilitiesCopyright;
     private String terminologyCapabilitiesKind;
     private String trmnlgCpbltsSftwrNme;
     private String trmnlgCpbltsSftwrVrsn;
     private String trmnlgCpbltsMplmnttnDscrptn;
     private String trmnlgCpbltsMplmnttnRl;
     private String terminologyCapabilitiesLockedDate;
     private String trmnlgCpbltsCdSstmRi;
     private String trmnlgCpbltsCdSstmVrsnCde;
     private String trmnlgCpbltsCdSstmVrsnSDflt;
     private String trmnlgCpbltsCdSstmVrsnCmpstnl;
     private String trmnlgCpbltsCdSstmVrsnLngge;
     private String trmnlgCpbltsCdSstmVrsnFltrCde;
     private String trmnlgCpbltsCdSstmVrsnFltrP;
     private String trmnlgCpbltsCdSstmVrsnPrprty;
     private String trmnlgCpbltsCdSstmSbsmptn;
     private String trmnlgCpbltsXpnsnHrrchcl;
     private String trmnlgCpbltsXpnsnPgng;
     private String trmnlgCpbltsXpnsnNcmplte;
     private String trmnlgCpbltsXpnsnPrmtrNme;
     private String trmnlgCpbltsXpnsnPrmtrDcmnttn;
     private String trmnlgCpbltsXpnsnTxtFltr;
     private String terminologyCapabilitiesCodeSearch;
     private String trmnlgCpbltsVldtCdTrnsltns;
     private String trmnlgCpbltsTrnsltnNdsMp;
     private String trmnlgCpbltsClsrTrnsltn;

    public Terminologycapabilities() {
    }

	
    public Terminologycapabilities(String terminologyCapabilitiesUrl) {
        this.terminologyCapabilitiesUrl = terminologyCapabilitiesUrl;
    }
    public Terminologycapabilities(String terminologyCapabilitiesUrl, String terminologyCapabilitiesVersion, String terminologyCapabilitiesName, String terminologyCapabilitiesTitle, String terminologyCapabilitiesStatus, String trmnlgCpbltsXprmntl, String terminologyCapabilitiesDate, String terminologyCapabilitiesPublisher, String terminologyCapabilitiesContact, String trmnlgCpbltsDscrptn, String terminologyCapabilitiesUseContext, String trmnlgCpbltsJrsdctnCdblCncptCdngSstm, String trmnlgCpbltsJrsdctnCdblCncptCdngVrsn, String trmnlgCpbltsJrsdctnCdblCncptCdngCde, String trmnlgCpbltsJrsdctnCdblCncptCdngDsplay, String trmnlgCpbltsJrsdctnCdblCncptCdngSrSlctd, String trmnlgCpbltsJrsdctnCdblCncptTxtStrng, String terminologyCapabilitiesPurpose, String terminologyCapabilitiesCopyright, String terminologyCapabilitiesKind, String trmnlgCpbltsSftwrNme, String trmnlgCpbltsSftwrVrsn, String trmnlgCpbltsMplmnttnDscrptn, String trmnlgCpbltsMplmnttnRl, String terminologyCapabilitiesLockedDate, String trmnlgCpbltsCdSstmRi, String trmnlgCpbltsCdSstmVrsnCde, String trmnlgCpbltsCdSstmVrsnSDflt, String trmnlgCpbltsCdSstmVrsnCmpstnl, String trmnlgCpbltsCdSstmVrsnLngge, String trmnlgCpbltsCdSstmVrsnFltrCde, String trmnlgCpbltsCdSstmVrsnFltrP, String trmnlgCpbltsCdSstmVrsnPrprty, String trmnlgCpbltsCdSstmSbsmptn, String trmnlgCpbltsXpnsnHrrchcl, String trmnlgCpbltsXpnsnPgng, String trmnlgCpbltsXpnsnNcmplte, String trmnlgCpbltsXpnsnPrmtrNme, String trmnlgCpbltsXpnsnPrmtrDcmnttn, String trmnlgCpbltsXpnsnTxtFltr, String terminologyCapabilitiesCodeSearch, String trmnlgCpbltsVldtCdTrnsltns, String trmnlgCpbltsTrnsltnNdsMp, String trmnlgCpbltsClsrTrnsltn) {
       this.terminologyCapabilitiesUrl = terminologyCapabilitiesUrl;
       this.terminologyCapabilitiesVersion = terminologyCapabilitiesVersion;
       this.terminologyCapabilitiesName = terminologyCapabilitiesName;
       this.terminologyCapabilitiesTitle = terminologyCapabilitiesTitle;
       this.terminologyCapabilitiesStatus = terminologyCapabilitiesStatus;
       this.trmnlgCpbltsXprmntl = trmnlgCpbltsXprmntl;
       this.terminologyCapabilitiesDate = terminologyCapabilitiesDate;
       this.terminologyCapabilitiesPublisher = terminologyCapabilitiesPublisher;
       this.terminologyCapabilitiesContact = terminologyCapabilitiesContact;
       this.trmnlgCpbltsDscrptn = trmnlgCpbltsDscrptn;
       this.terminologyCapabilitiesUseContext = terminologyCapabilitiesUseContext;
       this.trmnlgCpbltsJrsdctnCdblCncptCdngSstm = trmnlgCpbltsJrsdctnCdblCncptCdngSstm;
       this.trmnlgCpbltsJrsdctnCdblCncptCdngVrsn = trmnlgCpbltsJrsdctnCdblCncptCdngVrsn;
       this.trmnlgCpbltsJrsdctnCdblCncptCdngCde = trmnlgCpbltsJrsdctnCdblCncptCdngCde;
       this.trmnlgCpbltsJrsdctnCdblCncptCdngDsplay = trmnlgCpbltsJrsdctnCdblCncptCdngDsplay;
       this.trmnlgCpbltsJrsdctnCdblCncptCdngSrSlctd = trmnlgCpbltsJrsdctnCdblCncptCdngSrSlctd;
       this.trmnlgCpbltsJrsdctnCdblCncptTxtStrng = trmnlgCpbltsJrsdctnCdblCncptTxtStrng;
       this.terminologyCapabilitiesPurpose = terminologyCapabilitiesPurpose;
       this.terminologyCapabilitiesCopyright = terminologyCapabilitiesCopyright;
       this.terminologyCapabilitiesKind = terminologyCapabilitiesKind;
       this.trmnlgCpbltsSftwrNme = trmnlgCpbltsSftwrNme;
       this.trmnlgCpbltsSftwrVrsn = trmnlgCpbltsSftwrVrsn;
       this.trmnlgCpbltsMplmnttnDscrptn = trmnlgCpbltsMplmnttnDscrptn;
       this.trmnlgCpbltsMplmnttnRl = trmnlgCpbltsMplmnttnRl;
       this.terminologyCapabilitiesLockedDate = terminologyCapabilitiesLockedDate;
       this.trmnlgCpbltsCdSstmRi = trmnlgCpbltsCdSstmRi;
       this.trmnlgCpbltsCdSstmVrsnCde = trmnlgCpbltsCdSstmVrsnCde;
       this.trmnlgCpbltsCdSstmVrsnSDflt = trmnlgCpbltsCdSstmVrsnSDflt;
       this.trmnlgCpbltsCdSstmVrsnCmpstnl = trmnlgCpbltsCdSstmVrsnCmpstnl;
       this.trmnlgCpbltsCdSstmVrsnLngge = trmnlgCpbltsCdSstmVrsnLngge;
       this.trmnlgCpbltsCdSstmVrsnFltrCde = trmnlgCpbltsCdSstmVrsnFltrCde;
       this.trmnlgCpbltsCdSstmVrsnFltrP = trmnlgCpbltsCdSstmVrsnFltrP;
       this.trmnlgCpbltsCdSstmVrsnPrprty = trmnlgCpbltsCdSstmVrsnPrprty;
       this.trmnlgCpbltsCdSstmSbsmptn = trmnlgCpbltsCdSstmSbsmptn;
       this.trmnlgCpbltsXpnsnHrrchcl = trmnlgCpbltsXpnsnHrrchcl;
       this.trmnlgCpbltsXpnsnPgng = trmnlgCpbltsXpnsnPgng;
       this.trmnlgCpbltsXpnsnNcmplte = trmnlgCpbltsXpnsnNcmplte;
       this.trmnlgCpbltsXpnsnPrmtrNme = trmnlgCpbltsXpnsnPrmtrNme;
       this.trmnlgCpbltsXpnsnPrmtrDcmnttn = trmnlgCpbltsXpnsnPrmtrDcmnttn;
       this.trmnlgCpbltsXpnsnTxtFltr = trmnlgCpbltsXpnsnTxtFltr;
       this.terminologyCapabilitiesCodeSearch = terminologyCapabilitiesCodeSearch;
       this.trmnlgCpbltsVldtCdTrnsltns = trmnlgCpbltsVldtCdTrnsltns;
       this.trmnlgCpbltsTrnsltnNdsMp = trmnlgCpbltsTrnsltnNdsMp;
       this.trmnlgCpbltsClsrTrnsltn = trmnlgCpbltsClsrTrnsltn;
    }
   
    public String getTerminologyCapabilitiesUrl() {
        return this.terminologyCapabilitiesUrl;
    }
    
    public void setTerminologyCapabilitiesUrl(String terminologyCapabilitiesUrl) {
        this.terminologyCapabilitiesUrl = terminologyCapabilitiesUrl;
    }
    
    
    
    public String getTerminologyCapabilitiesVersion() {
        return this.terminologyCapabilitiesVersion;
    }
    
    public void setTerminologyCapabilitiesVersion(String terminologyCapabilitiesVersion) {
        this.terminologyCapabilitiesVersion = terminologyCapabilitiesVersion;
    }
    
    
    
    public String getTerminologyCapabilitiesName() {
        return this.terminologyCapabilitiesName;
    }
    
    public void setTerminologyCapabilitiesName(String terminologyCapabilitiesName) {
        this.terminologyCapabilitiesName = terminologyCapabilitiesName;
    }
    
    
    
    public String getTerminologyCapabilitiesTitle() {
        return this.terminologyCapabilitiesTitle;
    }
    
    public void setTerminologyCapabilitiesTitle(String terminologyCapabilitiesTitle) {
        this.terminologyCapabilitiesTitle = terminologyCapabilitiesTitle;
    }
    
    
    
    public String getTerminologyCapabilitiesStatus() {
        return this.terminologyCapabilitiesStatus;
    }
    
    public void setTerminologyCapabilitiesStatus(String terminologyCapabilitiesStatus) {
        this.terminologyCapabilitiesStatus = terminologyCapabilitiesStatus;
    }
    
    
    
    public String getTrmnlgCpbltsXprmntl() {
        return this.trmnlgCpbltsXprmntl;
    }
    
    public void setTrmnlgCpbltsXprmntl(String trmnlgCpbltsXprmntl) {
        this.trmnlgCpbltsXprmntl = trmnlgCpbltsXprmntl;
    }
    
    
    
    public String getTerminologyCapabilitiesDate() {
        return this.terminologyCapabilitiesDate;
    }
    
    public void setTerminologyCapabilitiesDate(String terminologyCapabilitiesDate) {
        this.terminologyCapabilitiesDate = terminologyCapabilitiesDate;
    }
    
    
    
    public String getTerminologyCapabilitiesPublisher() {
        return this.terminologyCapabilitiesPublisher;
    }
    
    public void setTerminologyCapabilitiesPublisher(String terminologyCapabilitiesPublisher) {
        this.terminologyCapabilitiesPublisher = terminologyCapabilitiesPublisher;
    }
    
    
    
    public String getTerminologyCapabilitiesContact() {
        return this.terminologyCapabilitiesContact;
    }
    
    public void setTerminologyCapabilitiesContact(String terminologyCapabilitiesContact) {
        this.terminologyCapabilitiesContact = terminologyCapabilitiesContact;
    }
    
    
    
    public String getTrmnlgCpbltsDscrptn() {
        return this.trmnlgCpbltsDscrptn;
    }
    
    public void setTrmnlgCpbltsDscrptn(String trmnlgCpbltsDscrptn) {
        this.trmnlgCpbltsDscrptn = trmnlgCpbltsDscrptn;
    }
    
    
    
    public String getTerminologyCapabilitiesUseContext() {
        return this.terminologyCapabilitiesUseContext;
    }
    
    public void setTerminologyCapabilitiesUseContext(String terminologyCapabilitiesUseContext) {
        this.terminologyCapabilitiesUseContext = terminologyCapabilitiesUseContext;
    }
    
    
    
    public String getTrmnlgCpbltsJrsdctnCdblCncptCdngSstm() {
        return this.trmnlgCpbltsJrsdctnCdblCncptCdngSstm;
    }
    
    public void setTrmnlgCpbltsJrsdctnCdblCncptCdngSstm(String trmnlgCpbltsJrsdctnCdblCncptCdngSstm) {
        this.trmnlgCpbltsJrsdctnCdblCncptCdngSstm = trmnlgCpbltsJrsdctnCdblCncptCdngSstm;
    }
    
    
    
    public String getTrmnlgCpbltsJrsdctnCdblCncptCdngVrsn() {
        return this.trmnlgCpbltsJrsdctnCdblCncptCdngVrsn;
    }
    
    public void setTrmnlgCpbltsJrsdctnCdblCncptCdngVrsn(String trmnlgCpbltsJrsdctnCdblCncptCdngVrsn) {
        this.trmnlgCpbltsJrsdctnCdblCncptCdngVrsn = trmnlgCpbltsJrsdctnCdblCncptCdngVrsn;
    }
    
    
    
    public String getTrmnlgCpbltsJrsdctnCdblCncptCdngCde() {
        return this.trmnlgCpbltsJrsdctnCdblCncptCdngCde;
    }
    
    public void setTrmnlgCpbltsJrsdctnCdblCncptCdngCde(String trmnlgCpbltsJrsdctnCdblCncptCdngCde) {
        this.trmnlgCpbltsJrsdctnCdblCncptCdngCde = trmnlgCpbltsJrsdctnCdblCncptCdngCde;
    }
    
    
    
    public String getTrmnlgCpbltsJrsdctnCdblCncptCdngDsplay() {
        return this.trmnlgCpbltsJrsdctnCdblCncptCdngDsplay;
    }
    
    public void setTrmnlgCpbltsJrsdctnCdblCncptCdngDsplay(String trmnlgCpbltsJrsdctnCdblCncptCdngDsplay) {
        this.trmnlgCpbltsJrsdctnCdblCncptCdngDsplay = trmnlgCpbltsJrsdctnCdblCncptCdngDsplay;
    }
    
    
    
    public String getTrmnlgCpbltsJrsdctnCdblCncptCdngSrSlctd() {
        return this.trmnlgCpbltsJrsdctnCdblCncptCdngSrSlctd;
    }
    
    public void setTrmnlgCpbltsJrsdctnCdblCncptCdngSrSlctd(String trmnlgCpbltsJrsdctnCdblCncptCdngSrSlctd) {
        this.trmnlgCpbltsJrsdctnCdblCncptCdngSrSlctd = trmnlgCpbltsJrsdctnCdblCncptCdngSrSlctd;
    }
    
    
    
    public String getTrmnlgCpbltsJrsdctnCdblCncptTxtStrng() {
        return this.trmnlgCpbltsJrsdctnCdblCncptTxtStrng;
    }
    
    public void setTrmnlgCpbltsJrsdctnCdblCncptTxtStrng(String trmnlgCpbltsJrsdctnCdblCncptTxtStrng) {
        this.trmnlgCpbltsJrsdctnCdblCncptTxtStrng = trmnlgCpbltsJrsdctnCdblCncptTxtStrng;
    }
    
    
    
    public String getTerminologyCapabilitiesPurpose() {
        return this.terminologyCapabilitiesPurpose;
    }
    
    public void setTerminologyCapabilitiesPurpose(String terminologyCapabilitiesPurpose) {
        this.terminologyCapabilitiesPurpose = terminologyCapabilitiesPurpose;
    }
    
    
    
    public String getTerminologyCapabilitiesCopyright() {
        return this.terminologyCapabilitiesCopyright;
    }
    
    public void setTerminologyCapabilitiesCopyright(String terminologyCapabilitiesCopyright) {
        this.terminologyCapabilitiesCopyright = terminologyCapabilitiesCopyright;
    }
    
    
    
    public String getTerminologyCapabilitiesKind() {
        return this.terminologyCapabilitiesKind;
    }
    
    public void setTerminologyCapabilitiesKind(String terminologyCapabilitiesKind) {
        this.terminologyCapabilitiesKind = terminologyCapabilitiesKind;
    }
    
    
    
    public String getTrmnlgCpbltsSftwrNme() {
        return this.trmnlgCpbltsSftwrNme;
    }
    
    public void setTrmnlgCpbltsSftwrNme(String trmnlgCpbltsSftwrNme) {
        this.trmnlgCpbltsSftwrNme = trmnlgCpbltsSftwrNme;
    }
    
    
    
    public String getTrmnlgCpbltsSftwrVrsn() {
        return this.trmnlgCpbltsSftwrVrsn;
    }
    
    public void setTrmnlgCpbltsSftwrVrsn(String trmnlgCpbltsSftwrVrsn) {
        this.trmnlgCpbltsSftwrVrsn = trmnlgCpbltsSftwrVrsn;
    }
    
    
    
    public String getTrmnlgCpbltsMplmnttnDscrptn() {
        return this.trmnlgCpbltsMplmnttnDscrptn;
    }
    
    public void setTrmnlgCpbltsMplmnttnDscrptn(String trmnlgCpbltsMplmnttnDscrptn) {
        this.trmnlgCpbltsMplmnttnDscrptn = trmnlgCpbltsMplmnttnDscrptn;
    }
    
    
    
    public String getTrmnlgCpbltsMplmnttnRl() {
        return this.trmnlgCpbltsMplmnttnRl;
    }
    
    public void setTrmnlgCpbltsMplmnttnRl(String trmnlgCpbltsMplmnttnRl) {
        this.trmnlgCpbltsMplmnttnRl = trmnlgCpbltsMplmnttnRl;
    }
    
    
    
    public String getTerminologyCapabilitiesLockedDate() {
        return this.terminologyCapabilitiesLockedDate;
    }
    
    public void setTerminologyCapabilitiesLockedDate(String terminologyCapabilitiesLockedDate) {
        this.terminologyCapabilitiesLockedDate = terminologyCapabilitiesLockedDate;
    }
    
    
    
    public String getTrmnlgCpbltsCdSstmRi() {
        return this.trmnlgCpbltsCdSstmRi;
    }
    
    public void setTrmnlgCpbltsCdSstmRi(String trmnlgCpbltsCdSstmRi) {
        this.trmnlgCpbltsCdSstmRi = trmnlgCpbltsCdSstmRi;
    }
    
    
    
    public String getTrmnlgCpbltsCdSstmVrsnCde() {
        return this.trmnlgCpbltsCdSstmVrsnCde;
    }
    
    public void setTrmnlgCpbltsCdSstmVrsnCde(String trmnlgCpbltsCdSstmVrsnCde) {
        this.trmnlgCpbltsCdSstmVrsnCde = trmnlgCpbltsCdSstmVrsnCde;
    }
    
    
    
    public String getTrmnlgCpbltsCdSstmVrsnSDflt() {
        return this.trmnlgCpbltsCdSstmVrsnSDflt;
    }
    
    public void setTrmnlgCpbltsCdSstmVrsnSDflt(String trmnlgCpbltsCdSstmVrsnSDflt) {
        this.trmnlgCpbltsCdSstmVrsnSDflt = trmnlgCpbltsCdSstmVrsnSDflt;
    }
    
    
    
    public String getTrmnlgCpbltsCdSstmVrsnCmpstnl() {
        return this.trmnlgCpbltsCdSstmVrsnCmpstnl;
    }
    
    public void setTrmnlgCpbltsCdSstmVrsnCmpstnl(String trmnlgCpbltsCdSstmVrsnCmpstnl) {
        this.trmnlgCpbltsCdSstmVrsnCmpstnl = trmnlgCpbltsCdSstmVrsnCmpstnl;
    }
    
    
    
    public String getTrmnlgCpbltsCdSstmVrsnLngge() {
        return this.trmnlgCpbltsCdSstmVrsnLngge;
    }
    
    public void setTrmnlgCpbltsCdSstmVrsnLngge(String trmnlgCpbltsCdSstmVrsnLngge) {
        this.trmnlgCpbltsCdSstmVrsnLngge = trmnlgCpbltsCdSstmVrsnLngge;
    }
    
    
    
    public String getTrmnlgCpbltsCdSstmVrsnFltrCde() {
        return this.trmnlgCpbltsCdSstmVrsnFltrCde;
    }
    
    public void setTrmnlgCpbltsCdSstmVrsnFltrCde(String trmnlgCpbltsCdSstmVrsnFltrCde) {
        this.trmnlgCpbltsCdSstmVrsnFltrCde = trmnlgCpbltsCdSstmVrsnFltrCde;
    }
    
    
    
    public String getTrmnlgCpbltsCdSstmVrsnFltrP() {
        return this.trmnlgCpbltsCdSstmVrsnFltrP;
    }
    
    public void setTrmnlgCpbltsCdSstmVrsnFltrP(String trmnlgCpbltsCdSstmVrsnFltrP) {
        this.trmnlgCpbltsCdSstmVrsnFltrP = trmnlgCpbltsCdSstmVrsnFltrP;
    }
    
    
    
    public String getTrmnlgCpbltsCdSstmVrsnPrprty() {
        return this.trmnlgCpbltsCdSstmVrsnPrprty;
    }
    
    public void setTrmnlgCpbltsCdSstmVrsnPrprty(String trmnlgCpbltsCdSstmVrsnPrprty) {
        this.trmnlgCpbltsCdSstmVrsnPrprty = trmnlgCpbltsCdSstmVrsnPrprty;
    }
    
    
    
    public String getTrmnlgCpbltsCdSstmSbsmptn() {
        return this.trmnlgCpbltsCdSstmSbsmptn;
    }
    
    public void setTrmnlgCpbltsCdSstmSbsmptn(String trmnlgCpbltsCdSstmSbsmptn) {
        this.trmnlgCpbltsCdSstmSbsmptn = trmnlgCpbltsCdSstmSbsmptn;
    }
    
    
    
    public String getTrmnlgCpbltsXpnsnHrrchcl() {
        return this.trmnlgCpbltsXpnsnHrrchcl;
    }
    
    public void setTrmnlgCpbltsXpnsnHrrchcl(String trmnlgCpbltsXpnsnHrrchcl) {
        this.trmnlgCpbltsXpnsnHrrchcl = trmnlgCpbltsXpnsnHrrchcl;
    }
    
    
    
    public String getTrmnlgCpbltsXpnsnPgng() {
        return this.trmnlgCpbltsXpnsnPgng;
    }
    
    public void setTrmnlgCpbltsXpnsnPgng(String trmnlgCpbltsXpnsnPgng) {
        this.trmnlgCpbltsXpnsnPgng = trmnlgCpbltsXpnsnPgng;
    }
    
    
    
    public String getTrmnlgCpbltsXpnsnNcmplte() {
        return this.trmnlgCpbltsXpnsnNcmplte;
    }
    
    public void setTrmnlgCpbltsXpnsnNcmplte(String trmnlgCpbltsXpnsnNcmplte) {
        this.trmnlgCpbltsXpnsnNcmplte = trmnlgCpbltsXpnsnNcmplte;
    }
    
    
    
    public String getTrmnlgCpbltsXpnsnPrmtrNme() {
        return this.trmnlgCpbltsXpnsnPrmtrNme;
    }
    
    public void setTrmnlgCpbltsXpnsnPrmtrNme(String trmnlgCpbltsXpnsnPrmtrNme) {
        this.trmnlgCpbltsXpnsnPrmtrNme = trmnlgCpbltsXpnsnPrmtrNme;
    }
    
    
    
    public String getTrmnlgCpbltsXpnsnPrmtrDcmnttn() {
        return this.trmnlgCpbltsXpnsnPrmtrDcmnttn;
    }
    
    public void setTrmnlgCpbltsXpnsnPrmtrDcmnttn(String trmnlgCpbltsXpnsnPrmtrDcmnttn) {
        this.trmnlgCpbltsXpnsnPrmtrDcmnttn = trmnlgCpbltsXpnsnPrmtrDcmnttn;
    }
    
    
    
    public String getTrmnlgCpbltsXpnsnTxtFltr() {
        return this.trmnlgCpbltsXpnsnTxtFltr;
    }
    
    public void setTrmnlgCpbltsXpnsnTxtFltr(String trmnlgCpbltsXpnsnTxtFltr) {
        this.trmnlgCpbltsXpnsnTxtFltr = trmnlgCpbltsXpnsnTxtFltr;
    }
    
    
    
    public String getTerminologyCapabilitiesCodeSearch() {
        return this.terminologyCapabilitiesCodeSearch;
    }
    
    public void setTerminologyCapabilitiesCodeSearch(String terminologyCapabilitiesCodeSearch) {
        this.terminologyCapabilitiesCodeSearch = terminologyCapabilitiesCodeSearch;
    }
    
    
    
    public String getTrmnlgCpbltsVldtCdTrnsltns() {
        return this.trmnlgCpbltsVldtCdTrnsltns;
    }
    
    public void setTrmnlgCpbltsVldtCdTrnsltns(String trmnlgCpbltsVldtCdTrnsltns) {
        this.trmnlgCpbltsVldtCdTrnsltns = trmnlgCpbltsVldtCdTrnsltns;
    }
    
    
    
    public String getTrmnlgCpbltsTrnsltnNdsMp() {
        return this.trmnlgCpbltsTrnsltnNdsMp;
    }
    
    public void setTrmnlgCpbltsTrnsltnNdsMp(String trmnlgCpbltsTrnsltnNdsMp) {
        this.trmnlgCpbltsTrnsltnNdsMp = trmnlgCpbltsTrnsltnNdsMp;
    }
    
    
    
    public String getTrmnlgCpbltsClsrTrnsltn() {
        return this.trmnlgCpbltsClsrTrnsltn;
    }
    
    public void setTrmnlgCpbltsClsrTrnsltn(String trmnlgCpbltsClsrTrnsltn) {
        this.trmnlgCpbltsClsrTrnsltn = trmnlgCpbltsClsrTrnsltn;
    }
    
    
    




}


