hibernate.connection.driver_class=oracle.jdbc.OracleDriver
hibernate.connection.url=jdbc:oracle:thin:@
hibernate.connection.username=
hibernate.connection.password=
hibernate.connection.pool_size=10
hibernate.dialect=org.hibernate.dialect.Oracle10gDialect
hibernate.default_schema=
show_sql=false
