CREATE VIEW PCORNET_CDM.CAMPFHIR_VIEW_CONDITION ( CON_ID, CON_SUBJECT_REF, CON_ENCOUNTER_REF, CON_ASSERTER_REFERENCE, CON_CODE_CODING_SYST, CON_CODE, CON_CATEGORY_CODING_SYST, CON_CATEGORY_CODING_CODE, CON_ASSERT_DATE, CON_CLINICALSTATUS, CON_ABATEDATE, CON_ONSETDATE, CON_VERIFICAIONSTATUS, CON_CATEGORY, CON_SEVERITY, CON_BODYSITE, CON_ONSET_X, CON_ONSETDATETIME, CON_ONSETAGE, CON_ONSETPERIOD_ST, CON_ONSETRANGE, CON_ONSETSTRING, CON_ABATEMENT_X, CON_ABATEMENTDATETIME, CON_ABATEMENTAGE, CON_ABATEMENTPERIOD, CON_ABATEMENTRANGE, CON_ABATEMENTSTRING, CON_RECORDEDDATE, CON_RECORDER_REF, CON_ASSERTER_REF, CON_STAGE, CON_STAGE_SUMMARY, CON_STAGE_ASSESSMENT_REF, CON_TYPE, CON_EVIDENCE, CON_EVIDENCE_CODE, CON_EVIDENCE_DETAIL_REF, CON_NOTE )
BEQUEATH DEFINER AS
(

select distinct
    conditionid as CON_ID,
    -- Patient who has the condition
    cond.PATID as CON_SUBJECT_REF,
    -- Encounter associated with the condition
	case
	    when cond.ENCOUNTERID is null then null
	    else 'Encounter/' || cond.ENCOUNTERID
	end as CON_ENCOUNTER_REF,
	null as CON_ASSERTER_REFERENCE,
	case
		when cond.CONDITION_TYPE = '09' then 'http://hl7.org/fhir/sid/icd-9-cm'
		when cond.CONDITION_TYPE = '10' then 'http://hl7.org/fhir/sid/icd-10-cm'
		when cond.CONDITION_TYPE = '11' then 'http://hl7.org/fhir/sid/icd-11-cm'
		when cond.CONDITION_TYPE = 'SM' then 'http://snomed.info/sct'
		when cond.CONDITION_TYPE = 'HP' then 'https://hpo.jax.org/app/'
	end as CON_CODE_CODING_SYST,
	cond.CONDITION as CON_CODE,
	'https://www.hl7.org/fhir/valueset-condition-category' as CON_CATEGORY_CODING_SYST,
	null as CON_CATEGORY_CODING_CODE,
	to_char(cond.REPORT_DATE, 'YYYY-MM-DD') as CON_ASSERT_DATE,
    -- Connects to mapping table. Will be ACTIVE, RESOLVED, INACTIVE, or NULL
    nvl(tcc1.fhir_out_cd, null) as CON_CLINICALSTATUS,
    null as CON_ABATEDATE,
    null as CON_ONSETDATE,
    null as CON_VERIFICAIONSTATUS,
    null as CON_CATEGORY,
    null as CON_SEVERITY,
    null as CON_BODYSITE,
    -- This section is a requirement for the NESTcc request. THey are interested in the start of the condition.
    -- FHIR resources treat the '_x' as a choice, so the date time will go into the CON_ONSET_X json node.
    null as CON_ONSET_X,
    to_char(cond.ONSET_DATE, 'YYYY-MM-DD') as CON_ONSETDATETIME,
    null as CON_ONSETAGE,
    null as CON_ONSETPERIOD_ST,
    null as CON_ONSETRANGE,
    null as CON_ONSETSTRING,
    -- This section is a requirement for the NESTcc request. They are interested in the stop of the condition.
    -- FHIR resources treat the '_x' as a choice, so the date time will go into the CON_ABATEMENT_X json node.
    null as CON_ABATEMENT_X,
    to_char(cond.RESOLVE_DATE, 'YYYY-MM-DD') as CON_ABATEMENTDATETIME,
    null as CON_ABATEMENTAGE,
    null as CON_ABATEMENTPERIOD,
    null as CON_ABATEMENTRANGE,
    null as CON_ABATEMENTSTRING,
    null as CON_RECORDEDDATE,
    null as CON_RECORDER_REF,
    null as CON_ASSERTER_REF,
    null as CON_STAGE,
    null as CON_STAGE_SUMMARY,
    null as CON_STAGE_ASSESSMENT_REF,
    null as CON_TYPE,
    null as CON_EVIDENCE,
    null as CON_EVIDENCE_CODE,
    null as CON_EVIDENCE_DETAIL_REF,
    -- NESTcc is interested in a 'description' of the condition.
    'Note: ' || cond.RAW_CONDITION as CON_NOTE

from
	PCORNET_CDM.condition cond
	left join CF_FHIR_MAPPING tcc1 on tcc1.column_cd='CONDITION_STATUS' and cond.CONDITION_STATUS=tcc1.local_in_cd

UNION

 select distinct
    dx.DIAGNOSISID as CON_ID,
    'Patient/' || dx.PATID as CON_SUBJECT_REF,
	'Encounter/' || dx.ENCOUNTERID as CON_ENCOUNTER_REF,
	case when dx.PROVIDERID is null then null else 'Practitioner/'||dx.PROVIDERID end as CON_ASSERTER_REFERENCE,
	case
		when dx.DX_TYPE = '09' then	'http://hl7.org/fhir/sid/icd-9-cm'
		when dx.DX_TYPE = '10' then 'http://hl7.org/fhir/sid/icd-10-cm'
		when dx.DX_TYPE = '11' then 'http://hl7.org/fhir/sid/icd-11-cm'
		when dx.DX_TYPE = 'SM' then 'http://snomed.info/sct'
	end as CON_CODE_CODING_SYST,
	dx.DX as CON_CODE,
	'https://www.hl7.org/fhir/valueset-condition-category' as CON_CATEGORY_CODING_SYST,
	'encounter-diagnosis' as CON_CATEGORY_CODING_CODE,
	to_char(dx.admit_date, 'YYYY-MM-DD') as CON_ASSERT_DATE,
    null as CON_CLINICALSTATUS,
    null as CON_ABATEDATE,
    null as CON_ONSETDATE,
    null as CON_VERIFICAIONSTATUS,
    null as CON_CATEGORY,
    null as CON_SEVERITY,
    null as CON_BODYSITE,
    null as CON_ONSET_X,
    null as CON_ONSETDATETIME,
    null as CON_ONSETAGE,
    null as CON_ONSETPERIOD_ST,
    null as CON_ONSETRANGE,
    null as CON_ONSETSTRING,
    null as CON_ABATEMENT_X,
    null as CON_ABATEMENTDATETIME,
    null as CON_ABATEMENTAGE,
    null as CON_ABATEMENTPERIOD,
    null as CON_ABATEMENTRANGE,
    null as CON_ABATEMENTSTRING,
    null as CON_RECORDEDDATE,
    null as CON_RECORDER_REF,
    null as CON_ASSERTER_REF,
    null as CON_STAGE,
    null as CON_STAGE_SUMMARY,
    null as CON_STAGE_ASSESSMENT_REF,
    null as CON_TYPE,
    null as CON_EVIDENCE,
    null as CON_EVIDENCE_CODE,
    null as CON_EVIDENCE_DETAIL_REF,
    'Note: ' || dx.RAW_DX as CON_NOTE

from PCORNET_CDM.DIAGNOSIS  dx
)
/
CREATE VIEW PCORNET_CDM.CAMPFHIR_VIEW_DEVICE ( DEV_ID, DEV_DEFINITION_REF, DEV_UDICARRIER, DEV_UDICARRIER_ID, DEV_UDICARRIER_ISSUER, DEV_UDICARRIER_JURISDICTION, DEV_UDICARRIER_CARRIERAIDC, DEV_UDICARRIER_CARRIERHRF, DEV_UDICARRIER_ENTRYTYPE, DEV_STATUS, DEV_STATUSREASON, DEV_DISTINCTIDENTIFIER, DEV_MANUFACTURER, DEV_MANUFACTUREDATE, DEV_EXPIRATIONDATE, DEV_LOTNUMBER, DEV_SERIALNUMBER, DEV_DEVICENAME, DEV_DEVICENAME_NAME, DEV_DEVICENAME_TYPE, DEV_MODELNUMBER, DEV_PARTNUMBER, DEV_TYPE, DEV_SPECIALIZATION, DEV_SPECIALIZATION_SYSTEMTYPE, DEV_SPECIALIZATION_VERSION, DEV_VERSION, DEV_VERSION_TYPE, DEV_VERSION_COMPONENT, DEV_VERSION_VALUE, DEV_PROPERTY, DEV_PROPERTY_TYPE, DEV_PROPERTY_VALUEQUANTITY, DEV_PROPERTY_VALUECODE, DEV_PATIENT_REF, DEV_OWNER_REF, DEV_CONTACT, DEV_LOCATION_REF, DEV_URL, DEV_NOTE, DEV_SAFETY, DEV_PARENT_REF )
BEQUEATH DEFINER AS
select
-- NESTcc request
null as DEV_ID,
null as DEV_DEFINITION_REF,
-- NESTcc request
null as DEV_UDICARRIER,
-- Mandatory string located on each device
null as DEV_UDICARRIER_ID,
null as DEV_UDICARRIER_ISSUER,
null as DEV_UDICARRIER_JURISDICTION,
null as DEV_UDICARRIER_CARRIERAIDC,
null as DEV_UDICARRIER_CARRIERHRF,
null as DEV_UDICARRIER_ENTRYTYPE,
-- NESTcc request
-- placeholder case for consistency purposes. Codebase concept
case
    when dual.DUMMY = 'active' then 'Active'
    when dual.DUMMY = 'inactive' then 'Inactive'
    when dual.DUMMY = 'entered-in-error' then 'Entered in Error'
    when dual.DUMMY = 'unknown' then 'Unknown'
    else null
end as DEV_STATUS,
null as DEV_STATUSREASON,
null as DEV_DISTINCTIDENTIFIER,
-- NESTcc request
null as DEV_MANUFACTURER,
-- NESTcc request
null as DEV_MANUFACTUREDATE,
null as DEV_EXPIRATIONDATE,
-- NESTcc request
null as DEV_LOTNUMBER,
-- NESTcc request
null as DEV_SERIALNUMBER,
-- NESTcc request
null as DEV_DEVICENAME,
null as DEV_DEVICENAME_NAME,
null as DEV_DEVICENAME_TYPE,
-- NESTcc request
null as DEV_MODELNUMBER,
null as DEV_PARTNUMBER,
-- NESTcc request
null as DEV_TYPE,
null as DEV_SPECIALIZATION,
null as DEV_SPECIALIZATION_SYSTEMTYPE,
null as DEV_SPECIALIZATION_VERSION,
null as DEV_VERSION,
null as DEV_VERSION_TYPE,
null as DEV_VERSION_COMPONENT,
null as DEV_VERSION_VALUE,
null as DEV_PROPERTY,
null as DEV_PROPERTY_TYPE,
null as DEV_PROPERTY_VALUEQUANTITY,
null as DEV_PROPERTY_VALUECODE,
null as DEV_PATIENT_REF,
null as DEV_OWNER_REF,
null as DEV_CONTACT,
null as DEV_LOCATION_REF,
null as DEV_URL,
null as DEV_NOTE,
null as DEV_SAFETY,
null as DEV_PARENT_REF

from dual
/
CREATE VIEW PCORNET_CDM.CAMPFHIR_VIEW_DEVICEDEFINITION ( DEVDEF_ID, DEVDEF_UDIDEVICEIDENTIFIER, DEVDEF_UDIID_DEVICEIDENTIFIER, DEVDEF_UDIID_ISSUER, DEVDEF_UDIID_JURISDICTION, DEVDEF_MANUFACTURER_X, DEVDEF_MANUFACTURERSTRING, DEVDEF_MANUFACTURERREFERENCE, DEVDEF_DEVICENAME, DEVDEF_DEVICENAME_NAME, DEVDEF_DEVICENAME_TYPE, DEVDEF_MODELNUMBER, DEVDEF_TYPE, DEVDEF_SPECIALIZATION, DEVDEF_SPECIALIZATION_SYSTEMTP, DEVDEF_SPECIALIZATION_VERSION, DEVDEF_VERSION, DEVDEF_SAFETY, DEVDEF_SHELFLIFESTORAGE, DEVDEF_PHYSICALCHARACTERISTICS, DEVDEF_LANGUAGECODE, DEVDEF_CAPABILITY, DEVDEF_CAPABILITY_TYPE, DEVDEF_CAPABILITY_DESCRIPTION, DEVDEF_PROPERTY, DEVDEF_PROPERTY_TYPE, DEVDEF_PROPERTY_VALUEQUANTITY, DEVDEF_PROPERTY_VALUECODE, DEVDEF_OWNER_REF, DEVDEF_CONTACT, DEVDEF_URL, DEVDEF_ONLINEINFORMATION, DEVDEF_NOTE, DEVDEF_QUANTITY, DEVDEF_PARENTDEVICE, DEVDEF_MATERIAL, DEVDEF_MATERIAL_SUBSTANCE, DEVDEF_MATERIAL_ALTERNATE, DEVDEF_MATERIAL_ALLERGININDIC )
BEQUEATH DEFINER AS
select
null as DEVDEF_ID,
null as DEVDEF_UDIDEVICEIDENTIFIER,
null as DEVDEF_UDIID_DEVICEIDENTIFIER,
null as DEVDEF_UDIID_ISSUER,
null as DEVDEF_UDIID_JURISDICTION,
null as DEVDEF_MANUFACTURER_X,
null as DEVDEF_MANUFACTURERSTRING,
null as DEVDEF_MANUFACTURERREFERENCE,
null as DEVDEF_DEVICENAME,
null as DEVDEF_DEVICENAME_NAME,
null as DEVDEF_DEVICENAME_TYPE,
null as DEVDEF_MODELNUMBER,
null as DEVDEF_TYPE,
null as DEVDEF_SPECIALIZATION,
null as DEVDEF_SPECIALIZATION_SYSTEMTP,
null as DEVDEF_SPECIALIZATION_VERSION,
null as DEVDEF_VERSION,
null as DEVDEF_SAFETY,
null as DEVDEF_SHELFLIFESTORAGE,
null as DEVDEF_PHYSICALCHARACTERISTICS,
null as DEVDEF_LANGUAGECODE,
null as DEVDEF_CAPABILITY,
null as DEVDEF_CAPABILITY_TYPE,
null as DEVDEF_CAPABILITY_DESCRIPTION,
null as DEVDEF_PROPERTY,
null as DEVDEF_PROPERTY_TYPE,
null as DEVDEF_PROPERTY_VALUEQUANTITY,
null as DEVDEF_PROPERTY_VALUECODE,
null as DEVDEF_OWNER_REF,
null as DEVDEF_CONTACT,
null as DEVDEF_URL,
null as DEVDEF_ONLINEINFORMATION,
null as DEVDEF_NOTE,
null as DEVDEF_QUANTITY,
null as DEVDEF_PARENTDEVICE,
null as DEVDEF_MATERIAL,
null as DEVDEF_MATERIAL_SUBSTANCE,
null as DEVDEF_MATERIAL_ALTERNATE,
null as DEVDEF_MATERIAL_ALLERGININDIC

from dual
/
CREATE VIEW PCORNET_CDM.CAMPFHIR_VIEW_DEVICEMETRIC ( DEVMET_ID, DEVMET_TYPE, DEVMET_UNIT, DEVMET_SOURCE_REF, DEVMET_PARENT_REF, DEVMET_OPERATIONALSTATUS, DEVMET_COLOR, DEVMET_CATEGORY, DEVMET_MEASUREMENTPERIOD, DEVMET_CALIBRATION, DEVMET_CALIBRATION_TYPE, DEVMET_CALIBRATION_STATE, DEVMET_CALIBRATION_TIME )
BEQUEATH DEFINER AS
SELECT
-- Can be used as a foreign key to connect to 'Device'
null as DEVMET_ID,
null as DEVMET_TYPE,
null as DEVMET_UNIT,
null as DEVMET_SOURCE_REF,
-- Allows for a hierarchy to be created.
null as DEVMET_PARENT_REF,
null as DEVMET_OPERATIONALSTATUS,
null as DEVMET_COLOR,
null as DEVMET_CATEGORY,
null as DEVMET_MEASUREMENTPERIOD,
null as DEVMET_CALIBRATION,
null as DEVMET_CALIBRATION_TYPE,
null as DEVMET_CALIBRATION_STATE,
null as DEVMET_CALIBRATION_TIME
from dual
/
CREATE VIEW PCORNET_CDM.CAMPFHIR_VIEW_ENCOUNTER ( ENC_ID, ENC_STATUS, ENC_STATUSHISTORY, ENC_STATUSHISTORY_STATUS, ENC_STATUSHISTORY_PERIOD, ENC_CLASS, ENC_CLASSHISTORY, ENC_CLASSHISTORY_CLASS, ENC_CLASSHISTORY_PERIOD, ENC_TYPE, ENC_SERVICETYPE, ENC_SUBJECT_REF, ENC_EPISODEOFCARE_REF, ENC_BASEDON_REF, ENC_PARTICIPANT, ENC_PARTICIPANT_TYPE, ENC_PARTICIPANT_PERIOD_ST, ENC_PARTICIPANT_PERIOD_END, ENC_PARTICIPANT_INDIVIDUAL_REF, ENC_PARTICIPANT_APPT_REF, ENC_PERIOD, ENC_LENGTH, ENC_REASONCODE, ENC_REASONREFERENCE, ENC_DIAGNOSIS, ENC_DIAGNOSIS_CONDITION_REF, ENC_DIAGNOSIS_USE, ENC_DIAGNOSIS_RANK, ENC_HSPTLZTN, ENC_HSPTLZTN_PREADMISSION_ID, ENC_HSPTLZTN_ORIGIN_REF, ENC_HSPTLZTN_ADMITSOURCE_REF, ENC_HSPTLZTN_READMISSION_REF, ENC_HSPTLZTN_DIETPREF_REF, ENC_HSPTLZTN_SPCLCOURTESY_REF, ENC_HSPTLZTN_SPCLARRNGMNT_REF, ENC_HSPTLZTN_DESTINATION_REF, ENC_HSPTLZTN_DISCHRGEDDISP_REF, ENC_LOCATION, ENC_LOCATION_STATUS, ENC_LOCATION_PHYSICALTYPE, ENC_LOCATION_PERIOD, ENC_SERVICEPROVIDER_REF, ENC_PARTOF_REF )
BEQUEATH DEFINER AS
select distinct
enc.ENCOUNTERID as ENC_ID,
null as ENC_STATUS,
null as ENC_STATUSHISTORY,
null as ENC_STATUSHISTORY_STATUS,
null as ENC_STATUSHISTORY_PERIOD,
-- NESTcc request
-- this can be linked to mapping table, links PCORNET codes to FHIR codes, not display. can be added.
-- case
--     when enc.ENC_TYPE = 'AV' then 'AMB'
--     when enc.ENC_TYPE = 'ED' then 'EMER'
--     when enc.ENC_TYPE = 'EI' then 'IMP'
--     when enc.ENC_TYPE = 'IP' then 'IMP'
--     when enc.ENC_TYPE = 'IS' then 'NONAC'
--     when enc.ENC_TYPE = 'OS' then 'SS'
--     when enc.ENC_TYPE = 'IC' then 'IMP'
--     when enc.ENC_TYPE = 'OA' then 'AMB'
--     else null
-- end as ENC_CLASS,
nvl(tcc1.fhir_out_cd, null) as ENC_CLASS,
null as ENC_CLASSHISTORY,
null as ENC_CLASSHISTORY_CLASS,
null as ENC_CLASSHISTORY_PERIOD,
-- This is a codeable concept that needs to be examined when dummy data is available. FHIR only has 4 options,
-- curious what is listed in PCORnet, or if more data points are allowed.
enc.ENC_TYPE as ENC_TYPE,
-- NESTcc request
-- Codeable concept
null as ENC_SERVICETYPE,
-- NESTcc request
-- Codeable concept
--case
   -- when lr.PRIORITY = 'R' then 'R - routine'
  --  when lr.PRIORITY = 'S' then 'S - stat'
   -- when lr.PRIORITY = 'E' then 'RR - rush reporting'
   -- else null
--end as ENC_PRIORITY,
-- NESTcc request
'Subject: ' || enc.PATID as ENC_SUBJECT_REF,
null as ENC_EPISODEOFCARE_REF,
null as ENC_BASEDON_REF,
null as ENC_PARTICIPANT,
null as ENC_PARTICIPANT_TYPE,
-- NESTcc Request
-- to_char(enc.ADMIT_DATE, 'YYYY-MM-DD') || '-' || to_char(enc.DISCHARGE_DATE, 'YYYY-MM-DD') as ENC_PARTICIPANT_PERIOD,
-- Extra JSON nodes! FHIR uses a period, PCORNET uses admit date and discharge date, these can be deleted
-- if above solution is acceptable
to_char(enc.ADMIT_DATE, 'YYYY-MM-DD') as ENC_PARTICIPANT_PERIOD_ST,
to_char(enc.DISCHARGE_DATE, 'YYYY-MM-DD') as ENC_PARTICIPANT_PERIOD_END,
null as ENC_PARTICIPANT_INDIVIDUAL_REF,
null as ENC_PARTICIPANT_APPT_REF,
null as ENC_PERIOD,
null as ENC_LENGTH,
-- NESTcc request
-- Codeable concept, uses SNOMED. 4000 concepts
null as ENC_REASONCODE,
null as ENC_REASONREFERENCE,
--NESTcc request
-- work on this, it references condition.
-- join diagnosis on ENCOUNTER ID!
-- This might be a stretch and not feasible, especially considering datatypes. 
dx.DX as ENC_DIAGNOSIS,
con.ENCOUNTERID as ENC_DIAGNOSIS_CONDITION_REF,
null as ENC_DIAGNOSIS_USE,
null as ENC_DIAGNOSIS_RANK,
-- not sure if this is appropriate, need dummy data to determine if correct mapping.
--enc.PAYER_TYPE_PRIMARY || 'and' || enc.PAYER_TYPE_SECONDARY as ENC_ACCOUNT_REF,
null as ENC_HSPTLZTN,
null as ENC_HSPTLZTN_PREADMISSION_ID,
null as ENC_HSPTLZTN_ORIGIN_REF,
null as ENC_HSPTLZTN_ADMITSOURCE_REF,
null as ENC_HSPTLZTN_READMISSION_REF,
null as ENC_HSPTLZTN_DIETPREF_REF,
null as ENC_HSPTLZTN_SPCLCOURTESY_REF,
null as ENC_HSPTLZTN_SPCLARRNGMNT_REF,
null as ENC_HSPTLZTN_DESTINATION_REF,
-- examine with dummy data when available.
-- can be linked to the mapping table. good example of multiple PCORnet values mapping to a single FHIR code.
case
    when enc.DISCHARGE_DISPOSITION = 'AF' then 'oth'
    when enc.DISCHARGE_DISPOSITION = 'AL' then 'oth'
    when enc.DISCHARGE_DISPOSITION = 'AM' then 'aadvice'
    when enc.DISCHARGE_DISPOSITION = 'AW' then 'oth'
    when enc.DISCHARGE_DISPOSITION = 'EX' then 'exp'
    when enc.DISCHARGE_DISPOSITION = 'HH' then 'oth'
    when enc.DISCHARGE_DISPOSITION = 'HO' then 'home'
    when enc.DISCHARGE_DISPOSITION = 'HS' then 'hosp'
    when enc.DISCHARGE_DISPOSITION = 'AF' then 'oth'
    when enc.DISCHARGE_DISPOSITION = 'IP' then 'other-HCF'
    when enc.DISCHARGE_DISPOSITION = 'NH' then 'long'
    when enc.DISCHARGE_DISPOSITION = 'RH' then 'rehab'
    when enc.DISCHARGE_DISPOSITION = 'RS' then 'long'
    when enc.DISCHARGE_DISPOSITION = 'SH' then 'oth'
    when enc.DISCHARGE_DISPOSITION = 'SN' then 'snf'
    when enc.DISCHARGE_DISPOSITION = 'OT' then 'oth'
    else null
end as ENC_HSPTLZTN_DISCHRGEDDISP_REF,
null as ENC_LOCATION,
-- 'Facility Location: ' || enc.FACILITY_LOCATION as ENC_LOCATION_LOCATION_REF,
null as ENC_LOCATION_STATUS,
null as ENC_LOCATION_PHYSICALTYPE,
null as ENC_LOCATION_PERIOD,
'Service Provider (Facility) ID: ' || enc.FACILITYID as ENC_SERVICEPROVIDER_REF,
null as ENC_PARTOF_REF
from encounter enc
left join DIAGNOSIS dx on enc.ENCOUNTERID = dx.ENCOUNTERID
left join CONDITION con on enc.ENCOUNTERID = con.ENCOUNTERID
left join CF_FHIR_MAPPING tcc1 on tcc1.column_cd='ENC_TYPE' and enc.ENC_TYPE=tcc1.local_in_cd
/
CREATE VIEW PCORNET_CDM.CAMPFHIR_VIEW_OBSERVATION ( OBS_SUBJECT_REF, CON_BASEDON_REF, OBS_PARTOF_REF, OBS_STATUS, OBS_CATEGORY, OBS_CODE, OBS_FOCUS_REF, OBS_ENCOUNTER_REF, OBS_EFFECTIVE_X, OBS_EFFECTIVEDATETIME, OBS_EFFECTIVEPERIOD, OBS_EFFECTIVETIMING, OBS_EFFECTIVEINSTANT, OBS_ISSUED, OBS_PERFORMER_REF, OBS_VALUE_X, OBS_VALUEQUANTITY, OBS_VALUECODEABLECONCEPT, OBS_VALUESTRING, OBS_VALUEBOOLEAN, OBS_VALUEINTEGER, OBS_VALUERANGE, OBS_VALUERATIO, OBS_VALUESAMPLEDDATA, OBS_VALUETIME, OBS_VALUEDATETIME, OBS_VALUEPERIOD, OBS_DATAABSENTREASON, OBS_INTERPRETATION, OBS_NOTE, OBS_BODYSITE, OBS_METHOD, OBS_SPECIMEN_REF, OBS_DEVICE_REF, OBS_REFERENCERANGE, OBS_REFERENCERANGE_LOW, OBS_REFERENCERANGE_HIGH, OBS_REFERENCERANGE_TYPE, OBS_REFERENCERANGE_APPLIESTO, OBS_REFERENCERANGE_AGE, OBS_REFERENCERANGE_TEXT, OBS_HASMEMBER_REF, OBS_DERIVEDFROM_REF, OBS_COMPONENT, OBS_COMPONENT_CODE, OBS_COMPONENT_VALUE_X, OBS_COMPONENT_VALUEQUANTITY, OBS_COMPONENT_VALUECODE, OBS_COMPONENT_VALUESTRING, OBS_COMPONENT_VALUEBOOLEAN, OBS_COMPONENT_VALUEINTEGER, OBS_COMPONENT_VALUERANGE, OBS_COMPONENT_VALUERATIO, OBS_COMPONENT_VALUESAMPLEDDATA, OBS_COMPONENT_VALUETIME, OBS_COMPONENT_VALUEDATETIME, OBS_COMPONENT_VALUEPERIOD, OBS_COMPONENT_DATAABSENTREASON, OBS_COMPONENT_INTERPRETATION, OBS_COMPONENT_REFERENCERANGE )
BEQUEATH DEFINER AS
(
select distinct
    -- The patient involved in the observation
    'Patient: ' || enc.PATID as OBS_SUBJECT_REF,
    null as CON_BASEDON_REF,
    null as OBS_PARTOF_REF,
    null as OBS_STATUS,
    null as OBS_CATEGORY,
    null as OBS_CODE,
    null as OBS_FOCUS_REF,
    'Encounter: ' || enc.ENCOUNTERID as OBS_ENCOUNTER_REF,
    -- The date of the observation
    -- FHIR resources treat the next as a choice, will eventually go into the OBS_EFFECTIVE_X json node.
    null as OBS_EFFECTIVE_X,
    to_char(enc.ADMIT_DATE, 'YYYY-MM-DD') as OBS_EFFECTIVEDATETIME,
    null as OBS_EFFECTIVEPERIOD,
    null as OBS_EFFECTIVETIMING,
    null as OBS_EFFECTIVEINSTANT,
    null as OBS_ISSUED,
    'Performer: ' || enc.PROVIDERID as OBS_PERFORMER_REF,
    null as OBS_VALUE_X,
    null as OBS_VALUEQUANTITY,
    null as OBS_VALUECODEABLECONCEPT,
    null as OBS_VALUESTRING,
    null as OBS_VALUEBOOLEAN,
    null as OBS_VALUEINTEGER,
    null as OBS_VALUERANGE,
    null as OBS_VALUERATIO,
    null as OBS_VALUESAMPLEDDATA,
    null as OBS_VALUETIME,
    null as OBS_VALUEDATETIME,
    null as OBS_VALUEPERIOD,
    null as OBS_DATAABSENTREASON,
    null as OBS_INTERPRETATION,
    null as OBS_NOTE,
    null as OBS_BODYSITE,
    null as OBS_METHOD,
    null as OBS_SPECIMEN_REF,
    null as OBS_DEVICE_REF,
    null as OBS_REFERENCERANGE,
    null as OBS_REFERENCERANGE_LOW,
    null as OBS_REFERENCERANGE_HIGH,
    null as OBS_REFERENCERANGE_TYPE,
    null as OBS_REFERENCERANGE_APPLIESTO,
    null as OBS_REFERENCERANGE_AGE,
    null as OBS_REFERENCERANGE_TEXT,
    null as OBS_HASMEMBER_REF,
    null as OBS_DERIVEDFROM_REF,
    null as OBS_COMPONENT,
    null as OBS_COMPONENT_CODE,
    null as OBS_COMPONENT_VALUE_X,
    null as OBS_COMPONENT_VALUEQUANTITY,
    null as OBS_COMPONENT_VALUECODE,
    null as OBS_COMPONENT_VALUESTRING,
    null as OBS_COMPONENT_VALUEBOOLEAN,
    null as OBS_COMPONENT_VALUEINTEGER,
    null as OBS_COMPONENT_VALUERANGE,
    null as OBS_COMPONENT_VALUERATIO,
    null as OBS_COMPONENT_VALUESAMPLEDDATA,
    null as OBS_COMPONENT_VALUETIME,
    null as OBS_COMPONENT_VALUEDATETIME,
    null as OBS_COMPONENT_VALUEPERIOD,
    null as OBS_COMPONENT_DATAABSENTREASON,
    null as OBS_COMPONENT_INTERPRETATION,
    null as OBS_COMPONENT_REFERENCERANGE

from ENCOUNTER enc
        )
/
CREATE FORCE VIEW PCORNET_CDM.CAMPFHIR_VIEW_MEDICATION ( MED_ID, MED_CODE, MED_STATUS, MED_MANUFACTURER_REF, MED_FORM, MED_AMOUNT, MED_INGREDIENT, MED_INGREDIENT_ITEM_X, MED_INGREDIENT_ITEMCODEABLECONCEPT, MED_INGREDIENT_ITEMREFERENCE_REF, MED_INGREDIENT_ISACTIVE, MED_INGREDIENT_STRENGTH, MED_BATCH, MED_BATCH_LOTNUMBER, MED_BATCH_EXPIRATIONDATE )
BEQUEATH DEFINER AS
select
--NESTcc Request
-- This appears to be the name of the drug, might need to be split in order to fit the FHIR spec.
-- this might split to form, amount, ingredient, etc.
rx.RXNORM_CUI as MED_ID,
--NESTcc Request
null as MED_CODE,
null as MED_STATUS,
--NESTcc Request
null as MED_MANUFACTURER_REF,
--NESTcc Request
null as MED_FORM,
null as MED_AMOUNT,
null as MED_INGREDIENT,
null as MED_INGREDIENT_ITEM_X,
null as MED_INGREDIENT_ITEMCODEABLECONCEPT,
null as MED_INGREDIENT_ITEMREFERENCE_REF,
null as MED_INGREDIENT_ISACTIVE,
null as MED_INGREDIENT_STRENGTH,
null as MED_BATCH,
null as MED_BATCH_LOTNUMBER,
null as MED_BATCH_EXPIRATIONDATE
from 
    PCORNET_CDM.PRESCRIBING med
    left join CF_FHIR_MAPPING tcc1 on tcc1.column_cd='RX_FREQUENCY' and med.RX_FREQUENCY=tcc1.local_in_cd
    left join CF_FHIR_MAPPING tcc2 on tcc2.column_cd='RX_PRN_FLAG' and med.RX_PRN_FLAG=tcc2.local_in_cd
    left join CF_FHIR_MAPPING tcc3 on tcc3.column_cd='RX_DISPENSE_AS_WRITTEN' and med.RX_DISPENSE_AS_WRITTEN=tcc3.local_in_cd

UNION

select
--NESTcc Request
null as MED_ID,
--NESTcc Request
ma.MEDADMIN_CODE as MED_CODE,
null as MED_STATUS,
--NESTcc Request
null as MED_MANUFACTURER_REF,
--NESTcc Request
null as MED_FORM,
null as MED_AMOUNT,
null as MED_INGREDIENT,
null as MED_INGREDIENT_ITEM_X,
null as MED_INGREDIENT_ITEMCODEABLECONCEPT,
null as MED_INGREDIENT_ITEMREFERENCE_REF,
null as MED_INGREDIENT_ISACTIVE,
null as MED_INGREDIENT_STRENGTH,
null as MED_BATCH,
null as MED_BATCH_LOTNUMBER,
null as MED_BATCH_EXPIRATIONDATE
from MED_ADMIN ma

UNION

select
--NESTcc Request
null as MED_ID,
--NESTcc Request
'NDC CODE: ' || ds.NDC as MED_CODE,
null as MED_STATUS,
--NESTcc Request
null as MED_MANUFACTURER_REF,
--NESTcc Request
null as MED_FORM,
null as MED_AMOUNT,
null as MED_INGREDIENT,
null as MED_INGREDIENT_ITEM_X,
null as MED_INGREDIENT_ITEMCODEABLECONCEPT,
null as MED_INGREDIENT_ITEMREFERENCE_REF,
null as MED_INGREDIENT_ISACTIVE,
null as MED_INGREDIENT_STRENGTH,
null as MED_BATCH,
null as MED_BATCH_LOTNUMBER,
null as MED_BATCH_EXPIRATIONDATE
from DISPENSING ds
/
CREATE VIEW PCORNET_CDM.CAMPFHIR_VIEW_PATIENT ( PAT_ID, PAT_ACTIVE, PAT_NAME, PAT_TELECOM, PAT_GENDER, PAT_BIRTHDATE, PAT_RACE, PAT_ETHNICITY, PAT_DECEASED_X, PAT_DECEASEDBOOLEAN, PAT_DECEASEDDATETIME, PAT_ADDRESS, PAT_MARITALSTATUS, PAT_MULTIPLEBIRTH_X, PAT_MULTIPLEBIRTHBOOLEAN, PAT_MULTIPLEBIRTHINTEGER, PAT_PHOTO, PAT_CONTACT, PAT_CONTACT_RELATIONSHIP, PAT_CONTACT_NAME, PAT_CONTACT_TELECOM, PAT_CONTACT_ADDRESS, PAT_CONTACT_GENDER, PAT_CONTACT_ORGANIZATION, PAT_CONTACT_PERIOD, PAT_COMMUNICATION, PAT_COMMUNICATION_LANGUAGE, PAT_COMMUNICATION_PREFERRED, PAT_GENERALPRACTITIONER_REF, PAT_MANAGINGORGANIZATION_REF, PAT_LINK, PAT_LINK_OTHER_REF, PAT_LINK_TYPE )
BEQUEATH DEFINER AS
select distinct
    -- Client requests patient ID
    dem.PATID as PAT_ID,
    null as PAT_ACTIVE,
    null as PAT_NAME,
    null as PAT_TELECOM,
    -- Client requests patient gender
    -- Could utilize mapping table
    nvl(tcc1.fhir_out_cd, null) as PAT_GENDER,
    -- Client requests patient birthdate
    dem.BIRTH_DATE as PAT_BIRTHDATE,
    nvl(tcc3.fhir_out_cd, null) as PAT_RACE,
    nvl(tcc4.fhir_out_cd, null) as PAT_ETHNICITY,
    null as PAT_DECEASED_X,
    null as PAT_DECEASEDBOOLEAN,
    d.DEATH_DATE as PAT_DECEASEDDATETIME,
    null as PAT_ADDRESS,
    null as PAT_MARITALSTATUS,
    null as PAT_MULTIPLEBIRTH_X,
    null as PAT_MULTIPLEBIRTHBOOLEAN,
    null as PAT_MULTIPLEBIRTHINTEGER,
    null as PAT_PHOTO,
    null as PAT_CONTACT,
    null as PAT_CONTACT_RELATIONSHIP,
    null as PAT_CONTACT_NAME,
    null as PAT_CONTACT_TELECOM,
    null as PAT_CONTACT_ADDRESS,
    null as PAT_CONTACT_GENDER,
    null as PAT_CONTACT_ORGANIZATION,
    null as PAT_CONTACT_PERIOD,
    null as PAT_COMMUNICATION,
    null as PAT_COMMUNICATION_LANGUAGE,
    null as PAT_COMMUNICATION_PREFERRED,
    null as PAT_GENERALPRACTITIONER_REF,
    null as PAT_MANAGINGORGANIZATION_REF,
    null as PAT_LINK,
    null as PAT_LINK_OTHER_REF,
    null as PAT_LINK_TYPE
from DEMOGRAPHIC dem
left join DEATH D on dem.PATID = D.PATID
left join CF_FHIR_MAPPING tcc1 on tcc1.column_cd='SEX' and dem.SEX=tcc1.local_in_cd
left join CF_FHIR_MAPPING tcc3 on tcc3.column_cd='RACE' and dem.RACE=tcc3.local_in_cd
left join CF_FHIR_MAPPING tcc4 on tcc4.column_cd='HISPANIC' and dem.HISPANIC=tcc4.local_in_cd
/
CREATE VIEW PCORNET_CDM.CAMPFHIR_VIEW_PROCEDURE ( PRO_ID, PRO_INSTANTIATESCANONICAL, PRO_INSTANTIATESURI, PRO_BASEDON_REF, PRO_PARTOF_REF, PRO_STATUS, PRO_STATUSREASON, PRO_CATEGORY, PRO_CODE, PRO_SUBJECT_REF, PRO_ENCOUNTER_REF, PRO_PERFORMED_X, PRO_PERFORMEDDATETIME, PRO_PERFORMEDPERIOD, PRO_PERFORMEDSTRING, PRO_PERFORMEDAGE, PRO_PERFORMEDRANGE, PRO_RECORDER_REF, PRO_ASSERTER_REF, PRO_PERFORMER, PRO_PERFORMER_FUNCTION, PRO_PERFORMER_ACTOR_REF, PRO_PERFORMER_ONBEHALFOF_REF, PRO_LOCATION_REF, PRO_REASONCODE, PRO_REASONREFERENCE_REF, PRO_BODYSITE, PRO_OUTCOME, PRO_REPORT_REF, PRO_COMPLICATION, PRO_COMPLICATIONDETAIL_REF, PRO_FOLLOWUP, PRO_NOTE, PRO_FOCALDEVICE, PRO_FOCALDEVICE_ACTION, PRO_FOCALDEVICE_MNPLTD_REF, PRO_USEDREFERENCE_REF, PRO_USEDCODE )
BEQUEATH DEFINER AS
select
-- NESTcc Request
'Procedure ID: ' || px.PROCEDURESID as PRO_ID,
null as PRO_INSTANTIATESCANONICAL,
null as PRO_INSTANTIATESURI,
null as PRO_BASEDON_REF,
null as PRO_PARTOF_REF,
null as PRO_STATUS,
null as PRO_STATUSREASON,
-- NESTcc Request
--not a perfect match. FHIR only has a few options
px.ENC_TYPE as PRO_CATEGORY,
--NESTcc request
-- Uses >1000 SNOMED codes.
px.PX as PRO_CODE,
-- NESTcc Request
'Patient: ' || px.PATID as PRO_SUBJECT_REF,
-- NESTcc request
'Encounter: ' || px.ENCOUNTERID as PRO_ENCOUNTER_REF,
null as PRO_PERFORMED_X,
-- NESTcc request
to_char(px.ADMIT_DATE, 'YYYY-MM-DD') as PRO_PERFORMEDDATETIME,
null as PRO_PERFORMEDPERIOD,
null as PRO_PERFORMEDSTRING,
null as PRO_PERFORMEDAGE,
null as PRO_PERFORMEDRANGE,
null as PRO_RECORDER_REF,
null as PRO_ASSERTER_REF,
null as PRO_PERFORMER,
null as PRO_PERFORMER_FUNCTION,
'Performer: ' || px.PROVIDERID as PRO_PERFORMER_ACTOR_REF,
null as PRO_PERFORMER_ONBEHALFOF_REF,
null as PRO_LOCATION_REF,
-- NESTcc Request
-- Uess >2000 SNOMED codes
null as PRO_REASONCODE,
null as PRO_REASONREFERENCE_REF,
-- NESTcc Request
-- This is mappable, but nothing in the PCORNET_Procedures table is a direct match. 
-- Might need to add a join to include encounter.
null as PRO_BODYSITE,
-- NESTcc Request
-- Codeable concept with 'Successful, Unsuccessful, and Partrially Successful.' no direct match in PCORNET_Procedures
-- Might need to incorporate PRO_CM (patient-reported-outcomes) table for this.
case
    when LOWER(pro.PRO_RESPONSE_TEXT) = 'successful' then 'Successful'
    when LOWER(pro.PRO_RESPONSE_TEXT) = 'unsuccessful' then 'Unsuccessful'
    when LOWER(pro.PRO_RESPONSE_TEXT) = 'partially successful' then 'Partially Successful'
    else null
    end as PRO_OUTCOME,
pro.PRO_CM_ID as PRO_REPORT_REF,
-- 1000+ snomed codes
con.CONDITION as PRO_COMPLICATION,
null as PRO_COMPLICATIONDETAIL_REF,
null as PRO_FOLLOWUP,
null as PRO_NOTE,
null as PRO_FOCALDEVICE,
null as PRO_FOCALDEVICE_ACTION,
null as PRO_FOCALDEVICE_MNPLTD_REF,
null as PRO_USEDREFERENCE_REF,
null as PRO_USEDCODE
from PROCEDURES px
left join PRO_CM pro on px.ENCOUNTERID = pro.ENCOUNTERID
left join CONDITION con on px.ENCOUNTERID = con.ENCOUNTERID
/
