
CREATE OR REPLACE VIEW PCORNET_CDM.CAMPFHIR_VIEW_PATIENT ( PAT_ID, PAT_ACTIVE, PAT_NAME, PAT_TELECOM, PAT_GENDER, PAT_BIRTHDATE, PAT_RACE, PAT_ETHNICITY, PAT_DECEASED_X, PAT_DECEASEDBOOLEAN, PAT_DECEASEDDATETIME, PAT_ADDRESS, PAT_MARITALSTATUS, PAT_MULTIPLEBIRTH_X, PAT_MULTIPLEBIRTHBOOLEAN, PAT_MULTIPLEBIRTHINTEGER, PAT_PHOTO, PAT_CONTACT, PAT_CONTACT_RELATIONSHIP, PAT_CONTACT_NAME, PAT_CONTACT_TELECOM, PAT_CONTACT_ADDRESS, PAT_CONTACT_GENDER, PAT_CONTACT_ORGANIZATION, PAT_CONTACT_PERIOD, PAT_COMMUNICATION, PAT_COMMUNICATION_LANGUAGE, PAT_COMMUNICATION_PREFERRED, PAT_GENERALPRACTITIONER_REF, PAT_MANAGINGORGANIZATION_REF, PAT_LINK, PAT_LINK_OTHER_REF, PAT_LINK_TYPE )
BEQUEATH DEFINER AS
select distinct
    -- Client requests patient ID
    dem.PATID as PAT_ID,
    null as PAT_ACTIVE,
    null as PAT_NAME,
    null as PAT_TELECOM,
    -- Client requests patient gender
    -- Could utilize mapping table
    nvl(tcc1.fhir_out_cd, null) as PAT_GENDER,
    -- Client requests patient birthdate
    dem.BIRTH_DATE as PAT_BIRTHDATE,
    nvl(tcc3.fhir_out_cd, null) as PAT_RACE,
    nvl(tcc4.fhir_out_cd, null) as PAT_ETHNICITY,
    null as PAT_DECEASED_X,
    null as PAT_DECEASEDBOOLEAN,
    d.DEATH_DATE as PAT_DECEASEDDATETIME,
    null as PAT_ADDRESS,
    null as PAT_MARITALSTATUS,
    null as PAT_MULTIPLEBIRTH_X,
    null as PAT_MULTIPLEBIRTHBOOLEAN,
    null as PAT_MULTIPLEBIRTHINTEGER,
    null as PAT_PHOTO,
    null as PAT_CONTACT,
    null as PAT_CONTACT_RELATIONSHIP,
    null as PAT_CONTACT_NAME,
    null as PAT_CONTACT_TELECOM,
    null as PAT_CONTACT_ADDRESS,
    null as PAT_CONTACT_GENDER,
    null as PAT_CONTACT_ORGANIZATION,
    null as PAT_CONTACT_PERIOD,
    null as PAT_COMMUNICATION,
    null as PAT_COMMUNICATION_LANGUAGE,
    null as PAT_COMMUNICATION_PREFERRED,
    null as PAT_GENERALPRACTITIONER_REF,
    null as PAT_MANAGINGORGANIZATION_REF,
    null as PAT_LINK,
    null as PAT_LINK_OTHER_REF,
    null as PAT_LINK_TYPE
from DEMOGRAPHIC dem
left join DEATH D on dem.PATID = D.PATID
left join CF_FHIR_MAPPING tcc1 on tcc1.column_cd='SEX' and dem.SEX=tcc1.local_in_cd
left join CF_FHIR_MAPPING tcc3 on tcc3.column_cd='RACE' and dem.RACE=tcc3.local_in_cd
left join CF_FHIR_MAPPING tcc4 on tcc4.column_cd='HISPANIC' and dem.HISPANIC=tcc4.local_in_cd
/
