-- Creates a RDBMS view of the 'Device Definition' FHIR resource
-- PCORNET does not have data for medical devices, so this is a work in progress.

create or replace view FHIR_VIEW_DEVICEDEFINITION as
select distinct
-- can be used as a foreign key to create a relationship
null as DEVDEF_ID,
null as DEVDEF_UDIDEVICEIDENTIFIER,
null as DEVDEF_UDIID_DEVICEIDENTIFIER,
null as DEVDEF_UDIID_ISSUER,
null as DEVDEF_UDIID_JURISDICTION,
null as DEVDEF_MANUFACTURER_X,
null as DEVDEF_MANUFACTURERSTRING,
null as DEVDEF_MANUFACTURERREFERENCE,
null as DEVDEF_DEVICENAME,
null as DEVDEF_DEVICENAME_NAME,
null as DEVDEF_DEVICENAME_TYPE,
null as DEVDEF_MODELNUMBER,
null as DEVDEF_TYPE,
null as DEVDEF_SPECIALIZATION,
null as DEVDEF_SPECIALIZATION_SYSTEMTP,
null as DEVDEF_SPECIALIZATION_VERSION,
null as DEVDEF_VERSION,
null as DEVDEF_SAFETY,
null as DEVDEF_SHELFLIFESTORAGE,
null as DEVDEF_PHYSICALCHARACTERISTICS,
null as DEVDEF_LANGUAGECODE,
null as DEVDEF_CAPABILITY,
null as DEVDEF_CAPABILITY_TYPE,
null as DEVDEF_CAPABILITY_DESCRIPTION,
null as DEVDEF_PROPERTY,
null as DEVDEF_PROPERTY_TYPE,
null as DEVDEF_PROPERTY_VALUEQUANTITY,
null as DEVDEF_PROPERTY_VALUECODE,
null as DEVDEF_OWNER_REF,
null as DEVDEF_CONTACT,
null as DEVDEF_URL,
null as DEVDEF_ONLINEINFORMATION,
null as DEVDEF_NOTE,
null as DEVDEF_QUANTITY,
null as DEVDEF_PARENTDEVICE,
null as DEVDEF_MATERIAL,
null as DEVDEF_MATERIAL_SUBSTANCE,
null as DEVDEF_MATERIAL_ALTERNATE,
null as DEVDEF_MATERIAL_ALLERGININDIC

-- oracle dummy table
from dual
/
