// // default package
package main.java.com.campfhir.model;
// Generated Jun 6, 2022, 11:02:30 AM by Hibernate Tools 5.6.1.Final



/**
 * EpisodeOfCare generated by hbm2java
 */
public class EpisodeOfCare  implements java.io.Serializable {


     private String id;
     private String episodeOfCareAccount;
     private String episodeOfCareCareManager;
     private String episodeOfCareDgnsisCndtn;
     private String episodeOfCareDgnsisRnk;
     private String episodeOfCareDgnsisRoleCdgCd;
     private String episodeOfCareDgnsisRoleCdgDsply;
     private String episodeOfCareDgnsisRoleCdgSys;
     private String episodeOfCareDgnsisRoleCdgUsrSltd;
     private String episodeOfCareDgnsisRoleCdgVrsn;
     private String episodeOfCareDgnsisRoleTxt;
     private String episodeOfCareIdAssigner;
     private String episodeOfCareIdPrdEnd;
     private String episodeOfCareIdPrdStrt;
     private String episodeOfCareIdSys;
     private String episodeOfCareIdTypCdgCd;
     private String episodeOfCareIdTypCdgDsply;
     private String episodeOfCareIdTypCdgSys;
     private String episodeOfCareIdTypCdgUsrSltd;
     private String episodeOfCareIdTypCdgVrsn;
     private String episodeOfCareIdTypTxt;
     private String episodeOfCareIdUse;
     private String episodeOfCareIdVl;
     private String episodeOfCareManagingOrgnztn;
     private String episodeOfCarePnt;
     private String episodeOfCarePrdEnd;
     private String episodeOfCarePrdStrt;
     private String episodeOfCareReferralRqst;
     private String episodeOfCareSts;
     private String episodeOfCareStsHisPrdEnd;
     private String episodeOfCareStsHisPrdStrt;
     private String episodeOfCareStsHisSts;
     private String episodeOfCareTeam;
     private String episodeOfCareTypCdgCd;
     private String episodeOfCareTypCdgDsply;
     private String episodeOfCareTypCdgSys;
     private String episodeOfCareTypCdgUsrSltd;
     private String episodeOfCareTypCdgVrsn;
     private String episodeOfCareTypTxt;

    public EpisodeOfCare() {
    }

   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    
    
    
    public String getEpisodeOfCareAccount() {
        return this.episodeOfCareAccount;
    }
    
    public void setEpisodeOfCareAccount(String episodeOfCareAccount) {
        this.episodeOfCareAccount = episodeOfCareAccount;
    }
    
    
    
    public String getEpisodeOfCareCareManager() {
        return this.episodeOfCareCareManager;
    }
    
    public void setEpisodeOfCareCareManager(String episodeOfCareCareManager) {
        this.episodeOfCareCareManager = episodeOfCareCareManager;
    }
    
    
    
    public String getEpisodeOfCareDgnsisCndtn() {
        return this.episodeOfCareDgnsisCndtn;
    }
    
    public void setEpisodeOfCareDgnsisCndtn(String episodeOfCareDgnsisCndtn) {
        this.episodeOfCareDgnsisCndtn = episodeOfCareDgnsisCndtn;
    }
    
    
    
    public String getEpisodeOfCareDgnsisRnk() {
        return this.episodeOfCareDgnsisRnk;
    }
    
    public void setEpisodeOfCareDgnsisRnk(String episodeOfCareDgnsisRnk) {
        this.episodeOfCareDgnsisRnk = episodeOfCareDgnsisRnk;
    }
    
    
    
    public String getEpisodeOfCareDgnsisRoleCdgCd() {
        return this.episodeOfCareDgnsisRoleCdgCd;
    }
    
    public void setEpisodeOfCareDgnsisRoleCdgCd(String episodeOfCareDgnsisRoleCdgCd) {
        this.episodeOfCareDgnsisRoleCdgCd = episodeOfCareDgnsisRoleCdgCd;
    }
    
    
    
    public String getEpisodeOfCareDgnsisRoleCdgDsply() {
        return this.episodeOfCareDgnsisRoleCdgDsply;
    }
    
    public void setEpisodeOfCareDgnsisRoleCdgDsply(String episodeOfCareDgnsisRoleCdgDsply) {
        this.episodeOfCareDgnsisRoleCdgDsply = episodeOfCareDgnsisRoleCdgDsply;
    }
    
    
    
    public String getEpisodeOfCareDgnsisRoleCdgSys() {
        return this.episodeOfCareDgnsisRoleCdgSys;
    }
    
    public void setEpisodeOfCareDgnsisRoleCdgSys(String episodeOfCareDgnsisRoleCdgSys) {
        this.episodeOfCareDgnsisRoleCdgSys = episodeOfCareDgnsisRoleCdgSys;
    }
    
    
    
    public String getEpisodeOfCareDgnsisRoleCdgUsrSltd() {
        return this.episodeOfCareDgnsisRoleCdgUsrSltd;
    }
    
    public void setEpisodeOfCareDgnsisRoleCdgUsrSltd(String episodeOfCareDgnsisRoleCdgUsrSltd) {
        this.episodeOfCareDgnsisRoleCdgUsrSltd = episodeOfCareDgnsisRoleCdgUsrSltd;
    }
    
    
    
    public String getEpisodeOfCareDgnsisRoleCdgVrsn() {
        return this.episodeOfCareDgnsisRoleCdgVrsn;
    }
    
    public void setEpisodeOfCareDgnsisRoleCdgVrsn(String episodeOfCareDgnsisRoleCdgVrsn) {
        this.episodeOfCareDgnsisRoleCdgVrsn = episodeOfCareDgnsisRoleCdgVrsn;
    }
    
    
    
    public String getEpisodeOfCareDgnsisRoleTxt() {
        return this.episodeOfCareDgnsisRoleTxt;
    }
    
    public void setEpisodeOfCareDgnsisRoleTxt(String episodeOfCareDgnsisRoleTxt) {
        this.episodeOfCareDgnsisRoleTxt = episodeOfCareDgnsisRoleTxt;
    }
    
    
    
    public String getEpisodeOfCareIdAssigner() {
        return this.episodeOfCareIdAssigner;
    }
    
    public void setEpisodeOfCareIdAssigner(String episodeOfCareIdAssigner) {
        this.episodeOfCareIdAssigner = episodeOfCareIdAssigner;
    }
    
    
    
    public String getEpisodeOfCareIdPrdEnd() {
        return this.episodeOfCareIdPrdEnd;
    }
    
    public void setEpisodeOfCareIdPrdEnd(String episodeOfCareIdPrdEnd) {
        this.episodeOfCareIdPrdEnd = episodeOfCareIdPrdEnd;
    }
    
    
    
    public String getEpisodeOfCareIdPrdStrt() {
        return this.episodeOfCareIdPrdStrt;
    }
    
    public void setEpisodeOfCareIdPrdStrt(String episodeOfCareIdPrdStrt) {
        this.episodeOfCareIdPrdStrt = episodeOfCareIdPrdStrt;
    }
    
    
    
    public String getEpisodeOfCareIdSys() {
        return this.episodeOfCareIdSys;
    }
    
    public void setEpisodeOfCareIdSys(String episodeOfCareIdSys) {
        this.episodeOfCareIdSys = episodeOfCareIdSys;
    }
    
    
    
    public String getEpisodeOfCareIdTypCdgCd() {
        return this.episodeOfCareIdTypCdgCd;
    }
    
    public void setEpisodeOfCareIdTypCdgCd(String episodeOfCareIdTypCdgCd) {
        this.episodeOfCareIdTypCdgCd = episodeOfCareIdTypCdgCd;
    }
    
    
    
    public String getEpisodeOfCareIdTypCdgDsply() {
        return this.episodeOfCareIdTypCdgDsply;
    }
    
    public void setEpisodeOfCareIdTypCdgDsply(String episodeOfCareIdTypCdgDsply) {
        this.episodeOfCareIdTypCdgDsply = episodeOfCareIdTypCdgDsply;
    }
    
    
    
    public String getEpisodeOfCareIdTypCdgSys() {
        return this.episodeOfCareIdTypCdgSys;
    }
    
    public void setEpisodeOfCareIdTypCdgSys(String episodeOfCareIdTypCdgSys) {
        this.episodeOfCareIdTypCdgSys = episodeOfCareIdTypCdgSys;
    }
    
    
    
    public String getEpisodeOfCareIdTypCdgUsrSltd() {
        return this.episodeOfCareIdTypCdgUsrSltd;
    }
    
    public void setEpisodeOfCareIdTypCdgUsrSltd(String episodeOfCareIdTypCdgUsrSltd) {
        this.episodeOfCareIdTypCdgUsrSltd = episodeOfCareIdTypCdgUsrSltd;
    }
    
    
    
    public String getEpisodeOfCareIdTypCdgVrsn() {
        return this.episodeOfCareIdTypCdgVrsn;
    }
    
    public void setEpisodeOfCareIdTypCdgVrsn(String episodeOfCareIdTypCdgVrsn) {
        this.episodeOfCareIdTypCdgVrsn = episodeOfCareIdTypCdgVrsn;
    }
    
    
    
    public String getEpisodeOfCareIdTypTxt() {
        return this.episodeOfCareIdTypTxt;
    }
    
    public void setEpisodeOfCareIdTypTxt(String episodeOfCareIdTypTxt) {
        this.episodeOfCareIdTypTxt = episodeOfCareIdTypTxt;
    }
    
    
    
    public String getEpisodeOfCareIdUse() {
        return this.episodeOfCareIdUse;
    }
    
    public void setEpisodeOfCareIdUse(String episodeOfCareIdUse) {
        this.episodeOfCareIdUse = episodeOfCareIdUse;
    }
    
    
    
    public String getEpisodeOfCareIdVl() {
        return this.episodeOfCareIdVl;
    }
    
    public void setEpisodeOfCareIdVl(String episodeOfCareIdVl) {
        this.episodeOfCareIdVl = episodeOfCareIdVl;
    }
    
    
    
    public String getEpisodeOfCareManagingOrgnztn() {
        return this.episodeOfCareManagingOrgnztn;
    }
    
    public void setEpisodeOfCareManagingOrgnztn(String episodeOfCareManagingOrgnztn) {
        this.episodeOfCareManagingOrgnztn = episodeOfCareManagingOrgnztn;
    }
    
    
    
    public String getEpisodeOfCarePnt() {
        return this.episodeOfCarePnt;
    }
    
    public void setEpisodeOfCarePnt(String episodeOfCarePnt) {
        this.episodeOfCarePnt = episodeOfCarePnt;
    }
    
    
    
    public String getEpisodeOfCarePrdEnd() {
        return this.episodeOfCarePrdEnd;
    }
    
    public void setEpisodeOfCarePrdEnd(String episodeOfCarePrdEnd) {
        this.episodeOfCarePrdEnd = episodeOfCarePrdEnd;
    }
    
    
    
    public String getEpisodeOfCarePrdStrt() {
        return this.episodeOfCarePrdStrt;
    }
    
    public void setEpisodeOfCarePrdStrt(String episodeOfCarePrdStrt) {
        this.episodeOfCarePrdStrt = episodeOfCarePrdStrt;
    }
    
    
    
    public String getEpisodeOfCareReferralRqst() {
        return this.episodeOfCareReferralRqst;
    }
    
    public void setEpisodeOfCareReferralRqst(String episodeOfCareReferralRqst) {
        this.episodeOfCareReferralRqst = episodeOfCareReferralRqst;
    }
    
    
    
    public String getEpisodeOfCareSts() {
        return this.episodeOfCareSts;
    }
    
    public void setEpisodeOfCareSts(String episodeOfCareSts) {
        this.episodeOfCareSts = episodeOfCareSts;
    }
    
    
    
    public String getEpisodeOfCareStsHisPrdEnd() {
        return this.episodeOfCareStsHisPrdEnd;
    }
    
    public void setEpisodeOfCareStsHisPrdEnd(String episodeOfCareStsHisPrdEnd) {
        this.episodeOfCareStsHisPrdEnd = episodeOfCareStsHisPrdEnd;
    }
    
    
    
    public String getEpisodeOfCareStsHisPrdStrt() {
        return this.episodeOfCareStsHisPrdStrt;
    }
    
    public void setEpisodeOfCareStsHisPrdStrt(String episodeOfCareStsHisPrdStrt) {
        this.episodeOfCareStsHisPrdStrt = episodeOfCareStsHisPrdStrt;
    }
    
    
    
    public String getEpisodeOfCareStsHisSts() {
        return this.episodeOfCareStsHisSts;
    }
    
    public void setEpisodeOfCareStsHisSts(String episodeOfCareStsHisSts) {
        this.episodeOfCareStsHisSts = episodeOfCareStsHisSts;
    }
    
    
    
    public String getEpisodeOfCareTeam() {
        return this.episodeOfCareTeam;
    }
    
    public void setEpisodeOfCareTeam(String episodeOfCareTeam) {
        this.episodeOfCareTeam = episodeOfCareTeam;
    }
    
    
    
    public String getEpisodeOfCareTypCdgCd() {
        return this.episodeOfCareTypCdgCd;
    }
    
    public void setEpisodeOfCareTypCdgCd(String episodeOfCareTypCdgCd) {
        this.episodeOfCareTypCdgCd = episodeOfCareTypCdgCd;
    }
    
    
    
    public String getEpisodeOfCareTypCdgDsply() {
        return this.episodeOfCareTypCdgDsply;
    }
    
    public void setEpisodeOfCareTypCdgDsply(String episodeOfCareTypCdgDsply) {
        this.episodeOfCareTypCdgDsply = episodeOfCareTypCdgDsply;
    }
    
    
    
    public String getEpisodeOfCareTypCdgSys() {
        return this.episodeOfCareTypCdgSys;
    }
    
    public void setEpisodeOfCareTypCdgSys(String episodeOfCareTypCdgSys) {
        this.episodeOfCareTypCdgSys = episodeOfCareTypCdgSys;
    }
    
    
    
    public String getEpisodeOfCareTypCdgUsrSltd() {
        return this.episodeOfCareTypCdgUsrSltd;
    }
    
    public void setEpisodeOfCareTypCdgUsrSltd(String episodeOfCareTypCdgUsrSltd) {
        this.episodeOfCareTypCdgUsrSltd = episodeOfCareTypCdgUsrSltd;
    }
    
    
    
    public String getEpisodeOfCareTypCdgVrsn() {
        return this.episodeOfCareTypCdgVrsn;
    }
    
    public void setEpisodeOfCareTypCdgVrsn(String episodeOfCareTypCdgVrsn) {
        this.episodeOfCareTypCdgVrsn = episodeOfCareTypCdgVrsn;
    }
    
    
    
    public String getEpisodeOfCareTypTxt() {
        return this.episodeOfCareTypTxt;
    }
    
    public void setEpisodeOfCareTypTxt(String episodeOfCareTypTxt) {
        this.episodeOfCareTypTxt = episodeOfCareTypTxt;
    }
    
    
    




}


