// // default package
package main.java.com.campfhir.model;
// Generated Jun 27, 2022, 10:40:10 AM by Hibernate Tools 5.6.1.Final



/**
 * SubstancePolymer generated by hbm2java
 */
public class SubstancePolymer  implements java.io.Serializable {


     private String id;
     private String sbstncPlymrClsCdgCd;
     private String sbstncPlymrClsCdgDsply;
     private String sbstncPlymrClsCdgSys;
     private String sbstncPlymrClsCdgUsrSltd;
     private String sbstncPlymrClsCdgVrsn;
     private String sbstncPlymrClsTxt;
     private String sbstncPlymrCopolymerConnectivityCdgCd;
     private String sbstncPlymrCopolymerConnectivityCdgDsply;
     private String sbstncPlymrCopolymerConnectivityCdgSys;
     private String sbstncPlymrCopolymerConnectivityCdgUsrSltd;
     private String sbstncPlymrCopolymerConnectivityCdgVrsn;
     private String sbstncPlymrCopolymerConnectivityTxt;
     private String sbstncPlymrGeometryCdgCd;
     private String sbstncPlymrGeometryCdgDsply;
     private String sbstncPlymrGeometryCdgSys;
     private String sbstncPlymrGeometryCdgUsrSltd;
     private String sbstncPlymrGeometryCdgVrsn;
     private String sbstncPlymrGeometryTxt;
     private String sbstncPlymrModification;
     private String sbstncPlymrMonomerStRtioTypCdgCd;
     private String sbstncPlymrMonomerStRtioTypCdgDsply;
     private String sbstncPlymrMonomerStRtioTypCdgSys;
     private String sbstncPlymrMonomerStRtioTypCdgUsrSltd;
     private String sbstncPlymrMonomerStRtioTypCdgVrsn;
     private String sbstncPlymrMonomerStRtioTypTxt;
     private String sbstncPlymrMonomerStStrtingMtrlAmntAmntQntyCd;
     private String sbstncPlymrMonomerStStrtingMtrlAmntAmntQntyCmprtr;
     private String sbstncPlymrMonomerStStrtingMtrlAmntAmntQntySys;
     private String sbstncPlymrMonomerStStrtingMtrlAmntAmntQntyUnt;
     private String sbstncPlymrMonomerStStrtingMtrlAmntAmntQntyVl;
     private String sbstncPlymrMonomerStStrtingMtrlAmntAmntRngHiCd;
     private String sbstncPlymrMonomerStStrtingMtrlAmntAmntRngHiCmprtr;
     private String sbstncPlymrMonomerStStrtingMtrlAmntAmntRngHiSys;
     private String sbstncPlymrMonomerStStrtingMtrlAmntAmntRngHiUnt;
     private String sbstncPlymrMonomerStStrtingMtrlAmntAmntRngHiVl;
     private String sbstncPlymrMonomerStStrtingMtrlAmntAmntRngLwCd;
     private String sbstncPlymrMonomerStStrtingMtrlAmntAmntRngLwCmprtr;
     private String sbstncPlymrMonomerStStrtingMtrlAmntAmntRngLwSys;
     private String sbstncPlymrMonomerStStrtingMtrlAmntAmntRngLwUnt;
     private String sbstncPlymrMonomerStStrtingMtrlAmntAmntRngLwVl;
     private String sbstncPlymrMonomerStStrtingMtrlAmntAmntStrgTyp;
     private String sbstncPlymrMonomerStStrtingMtrlAmntAmntTxt;
     private String sbstncPlymrMonomerStStrtingMtrlAmntAmntTxtElmnt;
     private String sbstncPlymrMonomerStStrtingMtrlAmntAmntTypCdgCd;
     private String sbstncPlymrMonomerStStrtingMtrlAmntAmntTypCdgDsply;
     private String sbstncPlymrMonomerStStrtingMtrlAmntAmntTypCdgSys;
     private String sbstncPlymrMonomerStStrtingMtrlAmntAmntTypCdgUsrSltd;
     private String sbstncPlymrMonomerStStrtingMtrlAmntAmntTypCdgVrsn;
     private String sbstncPlymrMonomerStStrtingMtrlAmntAmntTypTxt;
     private String sbstncPlymrMonomerStStrtingMtrlAmntRfrncRngHiLmtCd;
     private String sbstncPlymrMonomerStStrtingMtrlAmntRfrncRngHiLmtCmprtr;
     private String sbstncPlymrMonomerStStrtingMtrlAmntRfrncRngHiLmtSys;
     private String sbstncPlymrMonomerStStrtingMtrlAmntRfrncRngHiLmtUnt;
     private String sbstncPlymrMonomerStStrtingMtrlAmntRfrncRngHiLmtVl;
     private String sbstncPlymrMonomerStStrtingMtrlAmntRfrncRngLwLmtCd;
     private String sbstncPlymrMonomerStStrtingMtrlAmntRfrncRngLwLmtCmprtr;
     private String sbstncPlymrMonomerStStrtingMtrlAmntRfrncRngLwLmtSys;
     private String sbstncPlymrMonomerStStrtingMtrlAmntRfrncRngLwLmtUnt;
     private String sbstncPlymrMonomerStStrtingMtrlAmntRfrncRngLwLmtVl;
     private String sbstncPlymrMonomerStStrtingMtrlIsDefining;
     private String sbstncPlymrMonomerStStrtingMtrlMtrlCdgCd;
     private String sbstncPlymrMonomerStStrtingMtrlMtrlCdgDsply;
     private String sbstncPlymrMonomerStStrtingMtrlMtrlCdgSys;
     private String sbstncPlymrMonomerStStrtingMtrlMtrlCdgUsrSltd;
     private String sbstncPlymrMonomerStStrtingMtrlMtrlCdgVrsn;
     private String sbstncPlymrMonomerStStrtingMtrlMtrlTxt;
     private String sbstncPlymrMonomerStStrtingMtrlTypCdgCd;
     private String sbstncPlymrMonomerStStrtingMtrlTypCdgDsply;
     private String sbstncPlymrMonomerStStrtingMtrlTypCdgSys;
     private String sbstncPlymrMonomerStStrtingMtrlTypCdgUsrSltd;
     private String sbstncPlymrMonomerStStrtingMtrlTypCdgVrsn;
     private String sbstncPlymrMonomerStStrtingMtrlTypTxt;
     private String sbstncPlymrRptAverageMoleclrFrmula;
     private String sbstncPlymrRptNmbrOfUnts;
     private String sbstncPlymrRptRptUntAmntAmntQntyCd;
     private String sbstncPlymrRptRptUntAmntAmntQntyCmprtr;
     private String sbstncPlymrRptRptUntAmntAmntQntySys;
     private String sbstncPlymrRptRptUntAmntAmntQntyUnt;
     private String sbstncPlymrRptRptUntAmntAmntQntyVl;
     private String sbstncPlymrRptRptUntAmntAmntRngHiCd;
     private String sbstncPlymrRptRptUntAmntAmntRngHiCmprtr;
     private String sbstncPlymrRptRptUntAmntAmntRngHiSys;
     private String sbstncPlymrRptRptUntAmntAmntRngHiUnt;
     private String sbstncPlymrRptRptUntAmntAmntRngHiVl;
     private String sbstncPlymrRptRptUntAmntAmntRngLwCd;
     private String sbstncPlymrRptRptUntAmntAmntRngLwCmprtr;
     private String sbstncPlymrRptRptUntAmntAmntRngLwSys;
     private String sbstncPlymrRptRptUntAmntAmntRngLwUnt;
     private String sbstncPlymrRptRptUntAmntAmntRngLwVl;
     private String sbstncPlymrRptRptUntAmntAmntStrgTyp;
     private String sbstncPlymrRptRptUntAmntAmntTxt;
     private String sbstncPlymrRptRptUntAmntAmntTxtElmnt;
     private String sbstncPlymrRptRptUntAmntAmntTypCdgCd;
     private String sbstncPlymrRptRptUntAmntAmntTypCdgDsply;
     private String sbstncPlymrRptRptUntAmntAmntTypCdgSys;
     private String sbstncPlymrRptRptUntAmntAmntTypCdgUsrSltd;
     private String sbstncPlymrRptRptUntAmntAmntTypCdgVrsn;
     private String sbstncPlymrRptRptUntAmntAmntTypTxt;
     private String sbstncPlymrRptRptUntAmntRfrncRngHiLmtCd;
     private String sbstncPlymrRptRptUntAmntRfrncRngHiLmtCmprtr;
     private String sbstncPlymrRptRptUntAmntRfrncRngHiLmtSys;
     private String sbstncPlymrRptRptUntAmntRfrncRngHiLmtUnt;
     private String sbstncPlymrRptRptUntAmntRfrncRngHiLmtVl;
     private String sbstncPlymrRptRptUntAmntRfrncRngLwLmtCd;
     private String sbstncPlymrRptRptUntAmntRfrncRngLwLmtCmprtr;
     private String sbstncPlymrRptRptUntAmntRfrncRngLwLmtSys;
     private String sbstncPlymrRptRptUntAmntRfrncRngLwLmtUnt;
     private String sbstncPlymrRptRptUntAmntRfrncRngLwLmtVl;
     private String sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntQntyCd;
     private String sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntQntyCmprtr;
     private String sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntQntySys;
     private String sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntQntyUnt;
     private String sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntQntyVl;
     private String sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntRngHiCd;
     private String sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntRngHiCmprtr;
     private String sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntRngHiSys;
     private String sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntRngHiUnt;
     private String sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntRngHiVl;
     private String sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntRngLwCd;
     private String sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntRngLwCmprtr;
     private String sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntRngLwSys;
     private String sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntRngLwUnt;
     private String sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntRngLwVl;
     private String sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntStrgTyp;
     private String sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntTxt;
     private String sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntTxtElmnt;
     private String sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntTypCdgCd;
     private String sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntTypCdgDsply;
     private String sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntTypCdgSys;
     private String sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntTypCdgUsrSltd;
     private String sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntTypCdgVrsn;
     private String sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntTypTxt;
     private String sbstncPlymrRptRptUntDgrOfPlymrstnAmntRfrncRngHiLmtCd;
     private String sbstncPlymrRptRptUntDgrOfPlymrstnAmntRfrncRngHiLmtCmprtr;
     private String sbstncPlymrRptRptUntDgrOfPlymrstnAmntRfrncRngHiLmtSys;
     private String sbstncPlymrRptRptUntDgrOfPlymrstnAmntRfrncRngHiLmtUnt;
     private String sbstncPlymrRptRptUntDgrOfPlymrstnAmntRfrncRngHiLmtVl;
     private String sbstncPlymrRptRptUntDgrOfPlymrstnAmntRfrncRngLwLmtCd;
     private String sbstncPlymrRptRptUntDgrOfPlymrstnAmntRfrncRngLwLmtCmprtr;
     private String sbstncPlymrRptRptUntDgrOfPlymrstnAmntRfrncRngLwLmtSys;
     private String sbstncPlymrRptRptUntDgrOfPlymrstnAmntRfrncRngLwLmtUnt;
     private String sbstncPlymrRptRptUntDgrOfPlymrstnAmntRfrncRngLwLmtVl;
     private String sbstncPlymrRptRptUntDgrOfPlymrstnDegreeCdgCd;
     private String sbstncPlymrRptRptUntDgrOfPlymrstnDegreeCdgDsply;
     private String sbstncPlymrRptRptUntDgrOfPlymrstnDegreeCdgSys;
     private String sbstncPlymrRptRptUntDgrOfPlymrstnDegreeCdgUsrSltd;
     private String sbstncPlymrRptRptUntDgrOfPlymrstnDegreeCdgVrsn;
     private String sbstncPlymrRptRptUntDgrOfPlymrstnDegreeTxt;
     private String sbstncPlymrRptRptUntOrientationOfPlymrisationCdgCd;
     private String sbstncPlymrRptRptUntOrientationOfPlymrisationCdgDsply;
     private String sbstncPlymrRptRptUntOrientationOfPlymrisationCdgSys;
     private String sbstncPlymrRptRptUntOrientationOfPlymrisationCdgUsrSltd;
     private String sbstncPlymrRptRptUntOrientationOfPlymrisationCdgVrsn;
     private String sbstncPlymrRptRptUntOrientationOfPlymrisationTxt;
     private String sbstncPlymrRptRptUntRptUnt;
     private String sbstncPlymrRptRptUntStrctrlRprsnttnAttchmntCntntTyp;
     private String sbstncPlymrRptRptUntStrctrlRprsnttnAttchmntCreation;
     private String sbstncPlymrRptRptUntStrctrlRprsnttnAttchmntData;
     private String sbstncPlymrRptRptUntStrctrlRprsnttnAttchmntHash;
     private String sbstncPlymrRptRptUntStrctrlRprsnttnAttchmntLnguage;
     private String sbstncPlymrRptRptUntStrctrlRprsnttnAttchmntSz;
     private String sbstncPlymrRptRptUntStrctrlRprsnttnAttchmntTtl;
     private String sbstncPlymrRptRptUntStrctrlRprsnttnAttchmntUrl;
     private String sbstncPlymrRptRptUntStrctrlRprsnttnRepresentation;
     private String sbstncPlymrRptRptUntStrctrlRprsnttnTypCdgCd;
     private String sbstncPlymrRptRptUntStrctrlRprsnttnTypCdgDsply;
     private String sbstncPlymrRptRptUntStrctrlRprsnttnTypCdgSys;
     private String sbstncPlymrRptRptUntStrctrlRprsnttnTypCdgUsrSltd;
     private String sbstncPlymrRptRptUntStrctrlRprsnttnTypCdgVrsn;
     private String sbstncPlymrRptRptUntStrctrlRprsnttnTypTxt;
     private String sbstncPlymrRptRptUntAmntTypCdgCd;
     private String sbstncPlymrRptRptUntAmntTypCdgDsply;
     private String sbstncPlymrRptRptUntAmntTypCdgSys;
     private String sbstncPlymrRptRptUntAmntTypCdgUsrSltd;
     private String sbstncPlymrRptRptUntAmntTypCdgVrsn;
     private String sbstncPlymrRptRptUntAmntTypTxt;

    public SubstancePolymer() {
    }

   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    
    
    
    public String getSbstncPlymrClsCdgCd() {
        return this.sbstncPlymrClsCdgCd;
    }
    
    public void setSbstncPlymrClsCdgCd(String sbstncPlymrClsCdgCd) {
        this.sbstncPlymrClsCdgCd = sbstncPlymrClsCdgCd;
    }
    
    
    
    public String getSbstncPlymrClsCdgDsply() {
        return this.sbstncPlymrClsCdgDsply;
    }
    
    public void setSbstncPlymrClsCdgDsply(String sbstncPlymrClsCdgDsply) {
        this.sbstncPlymrClsCdgDsply = sbstncPlymrClsCdgDsply;
    }
    
    
    
    public String getSbstncPlymrClsCdgSys() {
        return this.sbstncPlymrClsCdgSys;
    }
    
    public void setSbstncPlymrClsCdgSys(String sbstncPlymrClsCdgSys) {
        this.sbstncPlymrClsCdgSys = sbstncPlymrClsCdgSys;
    }
    
    
    
    public String getSbstncPlymrClsCdgUsrSltd() {
        return this.sbstncPlymrClsCdgUsrSltd;
    }
    
    public void setSbstncPlymrClsCdgUsrSltd(String sbstncPlymrClsCdgUsrSltd) {
        this.sbstncPlymrClsCdgUsrSltd = sbstncPlymrClsCdgUsrSltd;
    }
    
    
    
    public String getSbstncPlymrClsCdgVrsn() {
        return this.sbstncPlymrClsCdgVrsn;
    }
    
    public void setSbstncPlymrClsCdgVrsn(String sbstncPlymrClsCdgVrsn) {
        this.sbstncPlymrClsCdgVrsn = sbstncPlymrClsCdgVrsn;
    }
    
    
    
    public String getSbstncPlymrClsTxt() {
        return this.sbstncPlymrClsTxt;
    }
    
    public void setSbstncPlymrClsTxt(String sbstncPlymrClsTxt) {
        this.sbstncPlymrClsTxt = sbstncPlymrClsTxt;
    }
    
    
    
    public String getSbstncPlymrCopolymerConnectivityCdgCd() {
        return this.sbstncPlymrCopolymerConnectivityCdgCd;
    }
    
    public void setSbstncPlymrCopolymerConnectivityCdgCd(String sbstncPlymrCopolymerConnectivityCdgCd) {
        this.sbstncPlymrCopolymerConnectivityCdgCd = sbstncPlymrCopolymerConnectivityCdgCd;
    }
    
    
    
    public String getSbstncPlymrCopolymerConnectivityCdgDsply() {
        return this.sbstncPlymrCopolymerConnectivityCdgDsply;
    }
    
    public void setSbstncPlymrCopolymerConnectivityCdgDsply(String sbstncPlymrCopolymerConnectivityCdgDsply) {
        this.sbstncPlymrCopolymerConnectivityCdgDsply = sbstncPlymrCopolymerConnectivityCdgDsply;
    }
    
    
    
    public String getSbstncPlymrCopolymerConnectivityCdgSys() {
        return this.sbstncPlymrCopolymerConnectivityCdgSys;
    }
    
    public void setSbstncPlymrCopolymerConnectivityCdgSys(String sbstncPlymrCopolymerConnectivityCdgSys) {
        this.sbstncPlymrCopolymerConnectivityCdgSys = sbstncPlymrCopolymerConnectivityCdgSys;
    }
    
    
    
    public String getSbstncPlymrCopolymerConnectivityCdgUsrSltd() {
        return this.sbstncPlymrCopolymerConnectivityCdgUsrSltd;
    }
    
    public void setSbstncPlymrCopolymerConnectivityCdgUsrSltd(String sbstncPlymrCopolymerConnectivityCdgUsrSltd) {
        this.sbstncPlymrCopolymerConnectivityCdgUsrSltd = sbstncPlymrCopolymerConnectivityCdgUsrSltd;
    }
    
    
    
    public String getSbstncPlymrCopolymerConnectivityCdgVrsn() {
        return this.sbstncPlymrCopolymerConnectivityCdgVrsn;
    }
    
    public void setSbstncPlymrCopolymerConnectivityCdgVrsn(String sbstncPlymrCopolymerConnectivityCdgVrsn) {
        this.sbstncPlymrCopolymerConnectivityCdgVrsn = sbstncPlymrCopolymerConnectivityCdgVrsn;
    }
    
    
    
    public String getSbstncPlymrCopolymerConnectivityTxt() {
        return this.sbstncPlymrCopolymerConnectivityTxt;
    }
    
    public void setSbstncPlymrCopolymerConnectivityTxt(String sbstncPlymrCopolymerConnectivityTxt) {
        this.sbstncPlymrCopolymerConnectivityTxt = sbstncPlymrCopolymerConnectivityTxt;
    }
    
    
    
    public String getSbstncPlymrGeometryCdgCd() {
        return this.sbstncPlymrGeometryCdgCd;
    }
    
    public void setSbstncPlymrGeometryCdgCd(String sbstncPlymrGeometryCdgCd) {
        this.sbstncPlymrGeometryCdgCd = sbstncPlymrGeometryCdgCd;
    }
    
    
    
    public String getSbstncPlymrGeometryCdgDsply() {
        return this.sbstncPlymrGeometryCdgDsply;
    }
    
    public void setSbstncPlymrGeometryCdgDsply(String sbstncPlymrGeometryCdgDsply) {
        this.sbstncPlymrGeometryCdgDsply = sbstncPlymrGeometryCdgDsply;
    }
    
    
    
    public String getSbstncPlymrGeometryCdgSys() {
        return this.sbstncPlymrGeometryCdgSys;
    }
    
    public void setSbstncPlymrGeometryCdgSys(String sbstncPlymrGeometryCdgSys) {
        this.sbstncPlymrGeometryCdgSys = sbstncPlymrGeometryCdgSys;
    }
    
    
    
    public String getSbstncPlymrGeometryCdgUsrSltd() {
        return this.sbstncPlymrGeometryCdgUsrSltd;
    }
    
    public void setSbstncPlymrGeometryCdgUsrSltd(String sbstncPlymrGeometryCdgUsrSltd) {
        this.sbstncPlymrGeometryCdgUsrSltd = sbstncPlymrGeometryCdgUsrSltd;
    }
    
    
    
    public String getSbstncPlymrGeometryCdgVrsn() {
        return this.sbstncPlymrGeometryCdgVrsn;
    }
    
    public void setSbstncPlymrGeometryCdgVrsn(String sbstncPlymrGeometryCdgVrsn) {
        this.sbstncPlymrGeometryCdgVrsn = sbstncPlymrGeometryCdgVrsn;
    }
    
    
    
    public String getSbstncPlymrGeometryTxt() {
        return this.sbstncPlymrGeometryTxt;
    }
    
    public void setSbstncPlymrGeometryTxt(String sbstncPlymrGeometryTxt) {
        this.sbstncPlymrGeometryTxt = sbstncPlymrGeometryTxt;
    }
    
    
    
    public String getSbstncPlymrModification() {
        return this.sbstncPlymrModification;
    }
    
    public void setSbstncPlymrModification(String sbstncPlymrModification) {
        this.sbstncPlymrModification = sbstncPlymrModification;
    }
    
    
    
    public String getSbstncPlymrMonomerStRtioTypCdgCd() {
        return this.sbstncPlymrMonomerStRtioTypCdgCd;
    }
    
    public void setSbstncPlymrMonomerStRtioTypCdgCd(String sbstncPlymrMonomerStRtioTypCdgCd) {
        this.sbstncPlymrMonomerStRtioTypCdgCd = sbstncPlymrMonomerStRtioTypCdgCd;
    }
    
    
    
    public String getSbstncPlymrMonomerStRtioTypCdgDsply() {
        return this.sbstncPlymrMonomerStRtioTypCdgDsply;
    }
    
    public void setSbstncPlymrMonomerStRtioTypCdgDsply(String sbstncPlymrMonomerStRtioTypCdgDsply) {
        this.sbstncPlymrMonomerStRtioTypCdgDsply = sbstncPlymrMonomerStRtioTypCdgDsply;
    }
    
    
    
    public String getSbstncPlymrMonomerStRtioTypCdgSys() {
        return this.sbstncPlymrMonomerStRtioTypCdgSys;
    }
    
    public void setSbstncPlymrMonomerStRtioTypCdgSys(String sbstncPlymrMonomerStRtioTypCdgSys) {
        this.sbstncPlymrMonomerStRtioTypCdgSys = sbstncPlymrMonomerStRtioTypCdgSys;
    }
    
    
    
    public String getSbstncPlymrMonomerStRtioTypCdgUsrSltd() {
        return this.sbstncPlymrMonomerStRtioTypCdgUsrSltd;
    }
    
    public void setSbstncPlymrMonomerStRtioTypCdgUsrSltd(String sbstncPlymrMonomerStRtioTypCdgUsrSltd) {
        this.sbstncPlymrMonomerStRtioTypCdgUsrSltd = sbstncPlymrMonomerStRtioTypCdgUsrSltd;
    }
    
    
    
    public String getSbstncPlymrMonomerStRtioTypCdgVrsn() {
        return this.sbstncPlymrMonomerStRtioTypCdgVrsn;
    }
    
    public void setSbstncPlymrMonomerStRtioTypCdgVrsn(String sbstncPlymrMonomerStRtioTypCdgVrsn) {
        this.sbstncPlymrMonomerStRtioTypCdgVrsn = sbstncPlymrMonomerStRtioTypCdgVrsn;
    }
    
    
    
    public String getSbstncPlymrMonomerStRtioTypTxt() {
        return this.sbstncPlymrMonomerStRtioTypTxt;
    }
    
    public void setSbstncPlymrMonomerStRtioTypTxt(String sbstncPlymrMonomerStRtioTypTxt) {
        this.sbstncPlymrMonomerStRtioTypTxt = sbstncPlymrMonomerStRtioTypTxt;
    }
    
    
    
    public String getSbstncPlymrMonomerStStrtingMtrlAmntAmntQntyCd() {
        return this.sbstncPlymrMonomerStStrtingMtrlAmntAmntQntyCd;
    }
    
    public void setSbstncPlymrMonomerStStrtingMtrlAmntAmntQntyCd(String sbstncPlymrMonomerStStrtingMtrlAmntAmntQntyCd) {
        this.sbstncPlymrMonomerStStrtingMtrlAmntAmntQntyCd = sbstncPlymrMonomerStStrtingMtrlAmntAmntQntyCd;
    }
    
    
    
    public String getSbstncPlymrMonomerStStrtingMtrlAmntAmntQntyCmprtr() {
        return this.sbstncPlymrMonomerStStrtingMtrlAmntAmntQntyCmprtr;
    }
    
    public void setSbstncPlymrMonomerStStrtingMtrlAmntAmntQntyCmprtr(String sbstncPlymrMonomerStStrtingMtrlAmntAmntQntyCmprtr) {
        this.sbstncPlymrMonomerStStrtingMtrlAmntAmntQntyCmprtr = sbstncPlymrMonomerStStrtingMtrlAmntAmntQntyCmprtr;
    }
    
    
    
    public String getSbstncPlymrMonomerStStrtingMtrlAmntAmntQntySys() {
        return this.sbstncPlymrMonomerStStrtingMtrlAmntAmntQntySys;
    }
    
    public void setSbstncPlymrMonomerStStrtingMtrlAmntAmntQntySys(String sbstncPlymrMonomerStStrtingMtrlAmntAmntQntySys) {
        this.sbstncPlymrMonomerStStrtingMtrlAmntAmntQntySys = sbstncPlymrMonomerStStrtingMtrlAmntAmntQntySys;
    }
    
    
    
    public String getSbstncPlymrMonomerStStrtingMtrlAmntAmntQntyUnt() {
        return this.sbstncPlymrMonomerStStrtingMtrlAmntAmntQntyUnt;
    }
    
    public void setSbstncPlymrMonomerStStrtingMtrlAmntAmntQntyUnt(String sbstncPlymrMonomerStStrtingMtrlAmntAmntQntyUnt) {
        this.sbstncPlymrMonomerStStrtingMtrlAmntAmntQntyUnt = sbstncPlymrMonomerStStrtingMtrlAmntAmntQntyUnt;
    }
    
    
    
    public String getSbstncPlymrMonomerStStrtingMtrlAmntAmntQntyVl() {
        return this.sbstncPlymrMonomerStStrtingMtrlAmntAmntQntyVl;
    }
    
    public void setSbstncPlymrMonomerStStrtingMtrlAmntAmntQntyVl(String sbstncPlymrMonomerStStrtingMtrlAmntAmntQntyVl) {
        this.sbstncPlymrMonomerStStrtingMtrlAmntAmntQntyVl = sbstncPlymrMonomerStStrtingMtrlAmntAmntQntyVl;
    }
    
    
    
    public String getSbstncPlymrMonomerStStrtingMtrlAmntAmntRngHiCd() {
        return this.sbstncPlymrMonomerStStrtingMtrlAmntAmntRngHiCd;
    }
    
    public void setSbstncPlymrMonomerStStrtingMtrlAmntAmntRngHiCd(String sbstncPlymrMonomerStStrtingMtrlAmntAmntRngHiCd) {
        this.sbstncPlymrMonomerStStrtingMtrlAmntAmntRngHiCd = sbstncPlymrMonomerStStrtingMtrlAmntAmntRngHiCd;
    }
    
    
    
    public String getSbstncPlymrMonomerStStrtingMtrlAmntAmntRngHiCmprtr() {
        return this.sbstncPlymrMonomerStStrtingMtrlAmntAmntRngHiCmprtr;
    }
    
    public void setSbstncPlymrMonomerStStrtingMtrlAmntAmntRngHiCmprtr(String sbstncPlymrMonomerStStrtingMtrlAmntAmntRngHiCmprtr) {
        this.sbstncPlymrMonomerStStrtingMtrlAmntAmntRngHiCmprtr = sbstncPlymrMonomerStStrtingMtrlAmntAmntRngHiCmprtr;
    }
    
    
    
    public String getSbstncPlymrMonomerStStrtingMtrlAmntAmntRngHiSys() {
        return this.sbstncPlymrMonomerStStrtingMtrlAmntAmntRngHiSys;
    }
    
    public void setSbstncPlymrMonomerStStrtingMtrlAmntAmntRngHiSys(String sbstncPlymrMonomerStStrtingMtrlAmntAmntRngHiSys) {
        this.sbstncPlymrMonomerStStrtingMtrlAmntAmntRngHiSys = sbstncPlymrMonomerStStrtingMtrlAmntAmntRngHiSys;
    }
    
    
    
    public String getSbstncPlymrMonomerStStrtingMtrlAmntAmntRngHiUnt() {
        return this.sbstncPlymrMonomerStStrtingMtrlAmntAmntRngHiUnt;
    }
    
    public void setSbstncPlymrMonomerStStrtingMtrlAmntAmntRngHiUnt(String sbstncPlymrMonomerStStrtingMtrlAmntAmntRngHiUnt) {
        this.sbstncPlymrMonomerStStrtingMtrlAmntAmntRngHiUnt = sbstncPlymrMonomerStStrtingMtrlAmntAmntRngHiUnt;
    }
    
    
    
    public String getSbstncPlymrMonomerStStrtingMtrlAmntAmntRngHiVl() {
        return this.sbstncPlymrMonomerStStrtingMtrlAmntAmntRngHiVl;
    }
    
    public void setSbstncPlymrMonomerStStrtingMtrlAmntAmntRngHiVl(String sbstncPlymrMonomerStStrtingMtrlAmntAmntRngHiVl) {
        this.sbstncPlymrMonomerStStrtingMtrlAmntAmntRngHiVl = sbstncPlymrMonomerStStrtingMtrlAmntAmntRngHiVl;
    }
    
    
    
    public String getSbstncPlymrMonomerStStrtingMtrlAmntAmntRngLwCd() {
        return this.sbstncPlymrMonomerStStrtingMtrlAmntAmntRngLwCd;
    }
    
    public void setSbstncPlymrMonomerStStrtingMtrlAmntAmntRngLwCd(String sbstncPlymrMonomerStStrtingMtrlAmntAmntRngLwCd) {
        this.sbstncPlymrMonomerStStrtingMtrlAmntAmntRngLwCd = sbstncPlymrMonomerStStrtingMtrlAmntAmntRngLwCd;
    }
    
    
    
    public String getSbstncPlymrMonomerStStrtingMtrlAmntAmntRngLwCmprtr() {
        return this.sbstncPlymrMonomerStStrtingMtrlAmntAmntRngLwCmprtr;
    }
    
    public void setSbstncPlymrMonomerStStrtingMtrlAmntAmntRngLwCmprtr(String sbstncPlymrMonomerStStrtingMtrlAmntAmntRngLwCmprtr) {
        this.sbstncPlymrMonomerStStrtingMtrlAmntAmntRngLwCmprtr = sbstncPlymrMonomerStStrtingMtrlAmntAmntRngLwCmprtr;
    }
    
    
    
    public String getSbstncPlymrMonomerStStrtingMtrlAmntAmntRngLwSys() {
        return this.sbstncPlymrMonomerStStrtingMtrlAmntAmntRngLwSys;
    }
    
    public void setSbstncPlymrMonomerStStrtingMtrlAmntAmntRngLwSys(String sbstncPlymrMonomerStStrtingMtrlAmntAmntRngLwSys) {
        this.sbstncPlymrMonomerStStrtingMtrlAmntAmntRngLwSys = sbstncPlymrMonomerStStrtingMtrlAmntAmntRngLwSys;
    }
    
    
    
    public String getSbstncPlymrMonomerStStrtingMtrlAmntAmntRngLwUnt() {
        return this.sbstncPlymrMonomerStStrtingMtrlAmntAmntRngLwUnt;
    }
    
    public void setSbstncPlymrMonomerStStrtingMtrlAmntAmntRngLwUnt(String sbstncPlymrMonomerStStrtingMtrlAmntAmntRngLwUnt) {
        this.sbstncPlymrMonomerStStrtingMtrlAmntAmntRngLwUnt = sbstncPlymrMonomerStStrtingMtrlAmntAmntRngLwUnt;
    }
    
    
    
    public String getSbstncPlymrMonomerStStrtingMtrlAmntAmntRngLwVl() {
        return this.sbstncPlymrMonomerStStrtingMtrlAmntAmntRngLwVl;
    }
    
    public void setSbstncPlymrMonomerStStrtingMtrlAmntAmntRngLwVl(String sbstncPlymrMonomerStStrtingMtrlAmntAmntRngLwVl) {
        this.sbstncPlymrMonomerStStrtingMtrlAmntAmntRngLwVl = sbstncPlymrMonomerStStrtingMtrlAmntAmntRngLwVl;
    }
    
    
    
    public String getSbstncPlymrMonomerStStrtingMtrlAmntAmntStrgTyp() {
        return this.sbstncPlymrMonomerStStrtingMtrlAmntAmntStrgTyp;
    }
    
    public void setSbstncPlymrMonomerStStrtingMtrlAmntAmntStrgTyp(String sbstncPlymrMonomerStStrtingMtrlAmntAmntStrgTyp) {
        this.sbstncPlymrMonomerStStrtingMtrlAmntAmntStrgTyp = sbstncPlymrMonomerStStrtingMtrlAmntAmntStrgTyp;
    }
    
    
    
    public String getSbstncPlymrMonomerStStrtingMtrlAmntAmntTxt() {
        return this.sbstncPlymrMonomerStStrtingMtrlAmntAmntTxt;
    }
    
    public void setSbstncPlymrMonomerStStrtingMtrlAmntAmntTxt(String sbstncPlymrMonomerStStrtingMtrlAmntAmntTxt) {
        this.sbstncPlymrMonomerStStrtingMtrlAmntAmntTxt = sbstncPlymrMonomerStStrtingMtrlAmntAmntTxt;
    }
    
    
    
    public String getSbstncPlymrMonomerStStrtingMtrlAmntAmntTxtElmnt() {
        return this.sbstncPlymrMonomerStStrtingMtrlAmntAmntTxtElmnt;
    }
    
    public void setSbstncPlymrMonomerStStrtingMtrlAmntAmntTxtElmnt(String sbstncPlymrMonomerStStrtingMtrlAmntAmntTxtElmnt) {
        this.sbstncPlymrMonomerStStrtingMtrlAmntAmntTxtElmnt = sbstncPlymrMonomerStStrtingMtrlAmntAmntTxtElmnt;
    }
    
    
    
    public String getSbstncPlymrMonomerStStrtingMtrlAmntAmntTypCdgCd() {
        return this.sbstncPlymrMonomerStStrtingMtrlAmntAmntTypCdgCd;
    }
    
    public void setSbstncPlymrMonomerStStrtingMtrlAmntAmntTypCdgCd(String sbstncPlymrMonomerStStrtingMtrlAmntAmntTypCdgCd) {
        this.sbstncPlymrMonomerStStrtingMtrlAmntAmntTypCdgCd = sbstncPlymrMonomerStStrtingMtrlAmntAmntTypCdgCd;
    }
    
    
    
    public String getSbstncPlymrMonomerStStrtingMtrlAmntAmntTypCdgDsply() {
        return this.sbstncPlymrMonomerStStrtingMtrlAmntAmntTypCdgDsply;
    }
    
    public void setSbstncPlymrMonomerStStrtingMtrlAmntAmntTypCdgDsply(String sbstncPlymrMonomerStStrtingMtrlAmntAmntTypCdgDsply) {
        this.sbstncPlymrMonomerStStrtingMtrlAmntAmntTypCdgDsply = sbstncPlymrMonomerStStrtingMtrlAmntAmntTypCdgDsply;
    }
    
    
    
    public String getSbstncPlymrMonomerStStrtingMtrlAmntAmntTypCdgSys() {
        return this.sbstncPlymrMonomerStStrtingMtrlAmntAmntTypCdgSys;
    }
    
    public void setSbstncPlymrMonomerStStrtingMtrlAmntAmntTypCdgSys(String sbstncPlymrMonomerStStrtingMtrlAmntAmntTypCdgSys) {
        this.sbstncPlymrMonomerStStrtingMtrlAmntAmntTypCdgSys = sbstncPlymrMonomerStStrtingMtrlAmntAmntTypCdgSys;
    }
    
    
    
    public String getSbstncPlymrMonomerStStrtingMtrlAmntAmntTypCdgUsrSltd() {
        return this.sbstncPlymrMonomerStStrtingMtrlAmntAmntTypCdgUsrSltd;
    }
    
    public void setSbstncPlymrMonomerStStrtingMtrlAmntAmntTypCdgUsrSltd(String sbstncPlymrMonomerStStrtingMtrlAmntAmntTypCdgUsrSltd) {
        this.sbstncPlymrMonomerStStrtingMtrlAmntAmntTypCdgUsrSltd = sbstncPlymrMonomerStStrtingMtrlAmntAmntTypCdgUsrSltd;
    }
    
    
    
    public String getSbstncPlymrMonomerStStrtingMtrlAmntAmntTypCdgVrsn() {
        return this.sbstncPlymrMonomerStStrtingMtrlAmntAmntTypCdgVrsn;
    }
    
    public void setSbstncPlymrMonomerStStrtingMtrlAmntAmntTypCdgVrsn(String sbstncPlymrMonomerStStrtingMtrlAmntAmntTypCdgVrsn) {
        this.sbstncPlymrMonomerStStrtingMtrlAmntAmntTypCdgVrsn = sbstncPlymrMonomerStStrtingMtrlAmntAmntTypCdgVrsn;
    }
    
    
    
    public String getSbstncPlymrMonomerStStrtingMtrlAmntAmntTypTxt() {
        return this.sbstncPlymrMonomerStStrtingMtrlAmntAmntTypTxt;
    }
    
    public void setSbstncPlymrMonomerStStrtingMtrlAmntAmntTypTxt(String sbstncPlymrMonomerStStrtingMtrlAmntAmntTypTxt) {
        this.sbstncPlymrMonomerStStrtingMtrlAmntAmntTypTxt = sbstncPlymrMonomerStStrtingMtrlAmntAmntTypTxt;
    }
    
    
    
    public String getSbstncPlymrMonomerStStrtingMtrlAmntRfrncRngHiLmtCd() {
        return this.sbstncPlymrMonomerStStrtingMtrlAmntRfrncRngHiLmtCd;
    }
    
    public void setSbstncPlymrMonomerStStrtingMtrlAmntRfrncRngHiLmtCd(String sbstncPlymrMonomerStStrtingMtrlAmntRfrncRngHiLmtCd) {
        this.sbstncPlymrMonomerStStrtingMtrlAmntRfrncRngHiLmtCd = sbstncPlymrMonomerStStrtingMtrlAmntRfrncRngHiLmtCd;
    }
    
    
    
    public String getSbstncPlymrMonomerStStrtingMtrlAmntRfrncRngHiLmtCmprtr() {
        return this.sbstncPlymrMonomerStStrtingMtrlAmntRfrncRngHiLmtCmprtr;
    }
    
    public void setSbstncPlymrMonomerStStrtingMtrlAmntRfrncRngHiLmtCmprtr(String sbstncPlymrMonomerStStrtingMtrlAmntRfrncRngHiLmtCmprtr) {
        this.sbstncPlymrMonomerStStrtingMtrlAmntRfrncRngHiLmtCmprtr = sbstncPlymrMonomerStStrtingMtrlAmntRfrncRngHiLmtCmprtr;
    }
    
    
    
    public String getSbstncPlymrMonomerStStrtingMtrlAmntRfrncRngHiLmtSys() {
        return this.sbstncPlymrMonomerStStrtingMtrlAmntRfrncRngHiLmtSys;
    }
    
    public void setSbstncPlymrMonomerStStrtingMtrlAmntRfrncRngHiLmtSys(String sbstncPlymrMonomerStStrtingMtrlAmntRfrncRngHiLmtSys) {
        this.sbstncPlymrMonomerStStrtingMtrlAmntRfrncRngHiLmtSys = sbstncPlymrMonomerStStrtingMtrlAmntRfrncRngHiLmtSys;
    }
    
    
    
    public String getSbstncPlymrMonomerStStrtingMtrlAmntRfrncRngHiLmtUnt() {
        return this.sbstncPlymrMonomerStStrtingMtrlAmntRfrncRngHiLmtUnt;
    }
    
    public void setSbstncPlymrMonomerStStrtingMtrlAmntRfrncRngHiLmtUnt(String sbstncPlymrMonomerStStrtingMtrlAmntRfrncRngHiLmtUnt) {
        this.sbstncPlymrMonomerStStrtingMtrlAmntRfrncRngHiLmtUnt = sbstncPlymrMonomerStStrtingMtrlAmntRfrncRngHiLmtUnt;
    }
    
    
    
    public String getSbstncPlymrMonomerStStrtingMtrlAmntRfrncRngHiLmtVl() {
        return this.sbstncPlymrMonomerStStrtingMtrlAmntRfrncRngHiLmtVl;
    }
    
    public void setSbstncPlymrMonomerStStrtingMtrlAmntRfrncRngHiLmtVl(String sbstncPlymrMonomerStStrtingMtrlAmntRfrncRngHiLmtVl) {
        this.sbstncPlymrMonomerStStrtingMtrlAmntRfrncRngHiLmtVl = sbstncPlymrMonomerStStrtingMtrlAmntRfrncRngHiLmtVl;
    }
    
    
    
    public String getSbstncPlymrMonomerStStrtingMtrlAmntRfrncRngLwLmtCd() {
        return this.sbstncPlymrMonomerStStrtingMtrlAmntRfrncRngLwLmtCd;
    }
    
    public void setSbstncPlymrMonomerStStrtingMtrlAmntRfrncRngLwLmtCd(String sbstncPlymrMonomerStStrtingMtrlAmntRfrncRngLwLmtCd) {
        this.sbstncPlymrMonomerStStrtingMtrlAmntRfrncRngLwLmtCd = sbstncPlymrMonomerStStrtingMtrlAmntRfrncRngLwLmtCd;
    }
    
    
    
    public String getSbstncPlymrMonomerStStrtingMtrlAmntRfrncRngLwLmtCmprtr() {
        return this.sbstncPlymrMonomerStStrtingMtrlAmntRfrncRngLwLmtCmprtr;
    }
    
    public void setSbstncPlymrMonomerStStrtingMtrlAmntRfrncRngLwLmtCmprtr(String sbstncPlymrMonomerStStrtingMtrlAmntRfrncRngLwLmtCmprtr) {
        this.sbstncPlymrMonomerStStrtingMtrlAmntRfrncRngLwLmtCmprtr = sbstncPlymrMonomerStStrtingMtrlAmntRfrncRngLwLmtCmprtr;
    }
    
    
    
    public String getSbstncPlymrMonomerStStrtingMtrlAmntRfrncRngLwLmtSys() {
        return this.sbstncPlymrMonomerStStrtingMtrlAmntRfrncRngLwLmtSys;
    }
    
    public void setSbstncPlymrMonomerStStrtingMtrlAmntRfrncRngLwLmtSys(String sbstncPlymrMonomerStStrtingMtrlAmntRfrncRngLwLmtSys) {
        this.sbstncPlymrMonomerStStrtingMtrlAmntRfrncRngLwLmtSys = sbstncPlymrMonomerStStrtingMtrlAmntRfrncRngLwLmtSys;
    }
    
    
    
    public String getSbstncPlymrMonomerStStrtingMtrlAmntRfrncRngLwLmtUnt() {
        return this.sbstncPlymrMonomerStStrtingMtrlAmntRfrncRngLwLmtUnt;
    }
    
    public void setSbstncPlymrMonomerStStrtingMtrlAmntRfrncRngLwLmtUnt(String sbstncPlymrMonomerStStrtingMtrlAmntRfrncRngLwLmtUnt) {
        this.sbstncPlymrMonomerStStrtingMtrlAmntRfrncRngLwLmtUnt = sbstncPlymrMonomerStStrtingMtrlAmntRfrncRngLwLmtUnt;
    }
    
    
    
    public String getSbstncPlymrMonomerStStrtingMtrlAmntRfrncRngLwLmtVl() {
        return this.sbstncPlymrMonomerStStrtingMtrlAmntRfrncRngLwLmtVl;
    }
    
    public void setSbstncPlymrMonomerStStrtingMtrlAmntRfrncRngLwLmtVl(String sbstncPlymrMonomerStStrtingMtrlAmntRfrncRngLwLmtVl) {
        this.sbstncPlymrMonomerStStrtingMtrlAmntRfrncRngLwLmtVl = sbstncPlymrMonomerStStrtingMtrlAmntRfrncRngLwLmtVl;
    }
    
    
    
    public String getSbstncPlymrMonomerStStrtingMtrlIsDefining() {
        return this.sbstncPlymrMonomerStStrtingMtrlIsDefining;
    }
    
    public void setSbstncPlymrMonomerStStrtingMtrlIsDefining(String sbstncPlymrMonomerStStrtingMtrlIsDefining) {
        this.sbstncPlymrMonomerStStrtingMtrlIsDefining = sbstncPlymrMonomerStStrtingMtrlIsDefining;
    }
    
    
    
    public String getSbstncPlymrMonomerStStrtingMtrlMtrlCdgCd() {
        return this.sbstncPlymrMonomerStStrtingMtrlMtrlCdgCd;
    }
    
    public void setSbstncPlymrMonomerStStrtingMtrlMtrlCdgCd(String sbstncPlymrMonomerStStrtingMtrlMtrlCdgCd) {
        this.sbstncPlymrMonomerStStrtingMtrlMtrlCdgCd = sbstncPlymrMonomerStStrtingMtrlMtrlCdgCd;
    }
    
    
    
    public String getSbstncPlymrMonomerStStrtingMtrlMtrlCdgDsply() {
        return this.sbstncPlymrMonomerStStrtingMtrlMtrlCdgDsply;
    }
    
    public void setSbstncPlymrMonomerStStrtingMtrlMtrlCdgDsply(String sbstncPlymrMonomerStStrtingMtrlMtrlCdgDsply) {
        this.sbstncPlymrMonomerStStrtingMtrlMtrlCdgDsply = sbstncPlymrMonomerStStrtingMtrlMtrlCdgDsply;
    }
    
    
    
    public String getSbstncPlymrMonomerStStrtingMtrlMtrlCdgSys() {
        return this.sbstncPlymrMonomerStStrtingMtrlMtrlCdgSys;
    }
    
    public void setSbstncPlymrMonomerStStrtingMtrlMtrlCdgSys(String sbstncPlymrMonomerStStrtingMtrlMtrlCdgSys) {
        this.sbstncPlymrMonomerStStrtingMtrlMtrlCdgSys = sbstncPlymrMonomerStStrtingMtrlMtrlCdgSys;
    }
    
    
    
    public String getSbstncPlymrMonomerStStrtingMtrlMtrlCdgUsrSltd() {
        return this.sbstncPlymrMonomerStStrtingMtrlMtrlCdgUsrSltd;
    }
    
    public void setSbstncPlymrMonomerStStrtingMtrlMtrlCdgUsrSltd(String sbstncPlymrMonomerStStrtingMtrlMtrlCdgUsrSltd) {
        this.sbstncPlymrMonomerStStrtingMtrlMtrlCdgUsrSltd = sbstncPlymrMonomerStStrtingMtrlMtrlCdgUsrSltd;
    }
    
    
    
    public String getSbstncPlymrMonomerStStrtingMtrlMtrlCdgVrsn() {
        return this.sbstncPlymrMonomerStStrtingMtrlMtrlCdgVrsn;
    }
    
    public void setSbstncPlymrMonomerStStrtingMtrlMtrlCdgVrsn(String sbstncPlymrMonomerStStrtingMtrlMtrlCdgVrsn) {
        this.sbstncPlymrMonomerStStrtingMtrlMtrlCdgVrsn = sbstncPlymrMonomerStStrtingMtrlMtrlCdgVrsn;
    }
    
    
    
    public String getSbstncPlymrMonomerStStrtingMtrlMtrlTxt() {
        return this.sbstncPlymrMonomerStStrtingMtrlMtrlTxt;
    }
    
    public void setSbstncPlymrMonomerStStrtingMtrlMtrlTxt(String sbstncPlymrMonomerStStrtingMtrlMtrlTxt) {
        this.sbstncPlymrMonomerStStrtingMtrlMtrlTxt = sbstncPlymrMonomerStStrtingMtrlMtrlTxt;
    }
    
    
    
    public String getSbstncPlymrMonomerStStrtingMtrlTypCdgCd() {
        return this.sbstncPlymrMonomerStStrtingMtrlTypCdgCd;
    }
    
    public void setSbstncPlymrMonomerStStrtingMtrlTypCdgCd(String sbstncPlymrMonomerStStrtingMtrlTypCdgCd) {
        this.sbstncPlymrMonomerStStrtingMtrlTypCdgCd = sbstncPlymrMonomerStStrtingMtrlTypCdgCd;
    }
    
    
    
    public String getSbstncPlymrMonomerStStrtingMtrlTypCdgDsply() {
        return this.sbstncPlymrMonomerStStrtingMtrlTypCdgDsply;
    }
    
    public void setSbstncPlymrMonomerStStrtingMtrlTypCdgDsply(String sbstncPlymrMonomerStStrtingMtrlTypCdgDsply) {
        this.sbstncPlymrMonomerStStrtingMtrlTypCdgDsply = sbstncPlymrMonomerStStrtingMtrlTypCdgDsply;
    }
    
    
    
    public String getSbstncPlymrMonomerStStrtingMtrlTypCdgSys() {
        return this.sbstncPlymrMonomerStStrtingMtrlTypCdgSys;
    }
    
    public void setSbstncPlymrMonomerStStrtingMtrlTypCdgSys(String sbstncPlymrMonomerStStrtingMtrlTypCdgSys) {
        this.sbstncPlymrMonomerStStrtingMtrlTypCdgSys = sbstncPlymrMonomerStStrtingMtrlTypCdgSys;
    }
    
    
    
    public String getSbstncPlymrMonomerStStrtingMtrlTypCdgUsrSltd() {
        return this.sbstncPlymrMonomerStStrtingMtrlTypCdgUsrSltd;
    }
    
    public void setSbstncPlymrMonomerStStrtingMtrlTypCdgUsrSltd(String sbstncPlymrMonomerStStrtingMtrlTypCdgUsrSltd) {
        this.sbstncPlymrMonomerStStrtingMtrlTypCdgUsrSltd = sbstncPlymrMonomerStStrtingMtrlTypCdgUsrSltd;
    }
    
    
    
    public String getSbstncPlymrMonomerStStrtingMtrlTypCdgVrsn() {
        return this.sbstncPlymrMonomerStStrtingMtrlTypCdgVrsn;
    }
    
    public void setSbstncPlymrMonomerStStrtingMtrlTypCdgVrsn(String sbstncPlymrMonomerStStrtingMtrlTypCdgVrsn) {
        this.sbstncPlymrMonomerStStrtingMtrlTypCdgVrsn = sbstncPlymrMonomerStStrtingMtrlTypCdgVrsn;
    }
    
    
    
    public String getSbstncPlymrMonomerStStrtingMtrlTypTxt() {
        return this.sbstncPlymrMonomerStStrtingMtrlTypTxt;
    }
    
    public void setSbstncPlymrMonomerStStrtingMtrlTypTxt(String sbstncPlymrMonomerStStrtingMtrlTypTxt) {
        this.sbstncPlymrMonomerStStrtingMtrlTypTxt = sbstncPlymrMonomerStStrtingMtrlTypTxt;
    }
    
    
    
    public String getSbstncPlymrRptAverageMoleclrFrmula() {
        return this.sbstncPlymrRptAverageMoleclrFrmula;
    }
    
    public void setSbstncPlymrRptAverageMoleclrFrmula(String sbstncPlymrRptAverageMoleclrFrmula) {
        this.sbstncPlymrRptAverageMoleclrFrmula = sbstncPlymrRptAverageMoleclrFrmula;
    }
    
    
    
    public String getSbstncPlymrRptNmbrOfUnts() {
        return this.sbstncPlymrRptNmbrOfUnts;
    }
    
    public void setSbstncPlymrRptNmbrOfUnts(String sbstncPlymrRptNmbrOfUnts) {
        this.sbstncPlymrRptNmbrOfUnts = sbstncPlymrRptNmbrOfUnts;
    }
    
    
    
    public String getSbstncPlymrRptRptUntAmntAmntQntyCd() {
        return this.sbstncPlymrRptRptUntAmntAmntQntyCd;
    }
    
    public void setSbstncPlymrRptRptUntAmntAmntQntyCd(String sbstncPlymrRptRptUntAmntAmntQntyCd) {
        this.sbstncPlymrRptRptUntAmntAmntQntyCd = sbstncPlymrRptRptUntAmntAmntQntyCd;
    }
    
    
    
    public String getSbstncPlymrRptRptUntAmntAmntQntyCmprtr() {
        return this.sbstncPlymrRptRptUntAmntAmntQntyCmprtr;
    }
    
    public void setSbstncPlymrRptRptUntAmntAmntQntyCmprtr(String sbstncPlymrRptRptUntAmntAmntQntyCmprtr) {
        this.sbstncPlymrRptRptUntAmntAmntQntyCmprtr = sbstncPlymrRptRptUntAmntAmntQntyCmprtr;
    }
    
    
    
    public String getSbstncPlymrRptRptUntAmntAmntQntySys() {
        return this.sbstncPlymrRptRptUntAmntAmntQntySys;
    }
    
    public void setSbstncPlymrRptRptUntAmntAmntQntySys(String sbstncPlymrRptRptUntAmntAmntQntySys) {
        this.sbstncPlymrRptRptUntAmntAmntQntySys = sbstncPlymrRptRptUntAmntAmntQntySys;
    }
    
    
    
    public String getSbstncPlymrRptRptUntAmntAmntQntyUnt() {
        return this.sbstncPlymrRptRptUntAmntAmntQntyUnt;
    }
    
    public void setSbstncPlymrRptRptUntAmntAmntQntyUnt(String sbstncPlymrRptRptUntAmntAmntQntyUnt) {
        this.sbstncPlymrRptRptUntAmntAmntQntyUnt = sbstncPlymrRptRptUntAmntAmntQntyUnt;
    }
    
    
    
    public String getSbstncPlymrRptRptUntAmntAmntQntyVl() {
        return this.sbstncPlymrRptRptUntAmntAmntQntyVl;
    }
    
    public void setSbstncPlymrRptRptUntAmntAmntQntyVl(String sbstncPlymrRptRptUntAmntAmntQntyVl) {
        this.sbstncPlymrRptRptUntAmntAmntQntyVl = sbstncPlymrRptRptUntAmntAmntQntyVl;
    }
    
    
    
    public String getSbstncPlymrRptRptUntAmntAmntRngHiCd() {
        return this.sbstncPlymrRptRptUntAmntAmntRngHiCd;
    }
    
    public void setSbstncPlymrRptRptUntAmntAmntRngHiCd(String sbstncPlymrRptRptUntAmntAmntRngHiCd) {
        this.sbstncPlymrRptRptUntAmntAmntRngHiCd = sbstncPlymrRptRptUntAmntAmntRngHiCd;
    }
    
    
    
    public String getSbstncPlymrRptRptUntAmntAmntRngHiCmprtr() {
        return this.sbstncPlymrRptRptUntAmntAmntRngHiCmprtr;
    }
    
    public void setSbstncPlymrRptRptUntAmntAmntRngHiCmprtr(String sbstncPlymrRptRptUntAmntAmntRngHiCmprtr) {
        this.sbstncPlymrRptRptUntAmntAmntRngHiCmprtr = sbstncPlymrRptRptUntAmntAmntRngHiCmprtr;
    }
    
    
    
    public String getSbstncPlymrRptRptUntAmntAmntRngHiSys() {
        return this.sbstncPlymrRptRptUntAmntAmntRngHiSys;
    }
    
    public void setSbstncPlymrRptRptUntAmntAmntRngHiSys(String sbstncPlymrRptRptUntAmntAmntRngHiSys) {
        this.sbstncPlymrRptRptUntAmntAmntRngHiSys = sbstncPlymrRptRptUntAmntAmntRngHiSys;
    }
    
    
    
    public String getSbstncPlymrRptRptUntAmntAmntRngHiUnt() {
        return this.sbstncPlymrRptRptUntAmntAmntRngHiUnt;
    }
    
    public void setSbstncPlymrRptRptUntAmntAmntRngHiUnt(String sbstncPlymrRptRptUntAmntAmntRngHiUnt) {
        this.sbstncPlymrRptRptUntAmntAmntRngHiUnt = sbstncPlymrRptRptUntAmntAmntRngHiUnt;
    }
    
    
    
    public String getSbstncPlymrRptRptUntAmntAmntRngHiVl() {
        return this.sbstncPlymrRptRptUntAmntAmntRngHiVl;
    }
    
    public void setSbstncPlymrRptRptUntAmntAmntRngHiVl(String sbstncPlymrRptRptUntAmntAmntRngHiVl) {
        this.sbstncPlymrRptRptUntAmntAmntRngHiVl = sbstncPlymrRptRptUntAmntAmntRngHiVl;
    }
    
    
    
    public String getSbstncPlymrRptRptUntAmntAmntRngLwCd() {
        return this.sbstncPlymrRptRptUntAmntAmntRngLwCd;
    }
    
    public void setSbstncPlymrRptRptUntAmntAmntRngLwCd(String sbstncPlymrRptRptUntAmntAmntRngLwCd) {
        this.sbstncPlymrRptRptUntAmntAmntRngLwCd = sbstncPlymrRptRptUntAmntAmntRngLwCd;
    }
    
    
    
    public String getSbstncPlymrRptRptUntAmntAmntRngLwCmprtr() {
        return this.sbstncPlymrRptRptUntAmntAmntRngLwCmprtr;
    }
    
    public void setSbstncPlymrRptRptUntAmntAmntRngLwCmprtr(String sbstncPlymrRptRptUntAmntAmntRngLwCmprtr) {
        this.sbstncPlymrRptRptUntAmntAmntRngLwCmprtr = sbstncPlymrRptRptUntAmntAmntRngLwCmprtr;
    }
    
    
    
    public String getSbstncPlymrRptRptUntAmntAmntRngLwSys() {
        return this.sbstncPlymrRptRptUntAmntAmntRngLwSys;
    }
    
    public void setSbstncPlymrRptRptUntAmntAmntRngLwSys(String sbstncPlymrRptRptUntAmntAmntRngLwSys) {
        this.sbstncPlymrRptRptUntAmntAmntRngLwSys = sbstncPlymrRptRptUntAmntAmntRngLwSys;
    }
    
    
    
    public String getSbstncPlymrRptRptUntAmntAmntRngLwUnt() {
        return this.sbstncPlymrRptRptUntAmntAmntRngLwUnt;
    }
    
    public void setSbstncPlymrRptRptUntAmntAmntRngLwUnt(String sbstncPlymrRptRptUntAmntAmntRngLwUnt) {
        this.sbstncPlymrRptRptUntAmntAmntRngLwUnt = sbstncPlymrRptRptUntAmntAmntRngLwUnt;
    }
    
    
    
    public String getSbstncPlymrRptRptUntAmntAmntRngLwVl() {
        return this.sbstncPlymrRptRptUntAmntAmntRngLwVl;
    }
    
    public void setSbstncPlymrRptRptUntAmntAmntRngLwVl(String sbstncPlymrRptRptUntAmntAmntRngLwVl) {
        this.sbstncPlymrRptRptUntAmntAmntRngLwVl = sbstncPlymrRptRptUntAmntAmntRngLwVl;
    }
    
    
    
    public String getSbstncPlymrRptRptUntAmntAmntStrgTyp() {
        return this.sbstncPlymrRptRptUntAmntAmntStrgTyp;
    }
    
    public void setSbstncPlymrRptRptUntAmntAmntStrgTyp(String sbstncPlymrRptRptUntAmntAmntStrgTyp) {
        this.sbstncPlymrRptRptUntAmntAmntStrgTyp = sbstncPlymrRptRptUntAmntAmntStrgTyp;
    }
    
    
    
    public String getSbstncPlymrRptRptUntAmntAmntTxt() {
        return this.sbstncPlymrRptRptUntAmntAmntTxt;
    }
    
    public void setSbstncPlymrRptRptUntAmntAmntTxt(String sbstncPlymrRptRptUntAmntAmntTxt) {
        this.sbstncPlymrRptRptUntAmntAmntTxt = sbstncPlymrRptRptUntAmntAmntTxt;
    }
    
    
    
    public String getSbstncPlymrRptRptUntAmntAmntTxtElmnt() {
        return this.sbstncPlymrRptRptUntAmntAmntTxtElmnt;
    }
    
    public void setSbstncPlymrRptRptUntAmntAmntTxtElmnt(String sbstncPlymrRptRptUntAmntAmntTxtElmnt) {
        this.sbstncPlymrRptRptUntAmntAmntTxtElmnt = sbstncPlymrRptRptUntAmntAmntTxtElmnt;
    }
    
    
    
    public String getSbstncPlymrRptRptUntAmntAmntTypCdgCd() {
        return this.sbstncPlymrRptRptUntAmntAmntTypCdgCd;
    }
    
    public void setSbstncPlymrRptRptUntAmntAmntTypCdgCd(String sbstncPlymrRptRptUntAmntAmntTypCdgCd) {
        this.sbstncPlymrRptRptUntAmntAmntTypCdgCd = sbstncPlymrRptRptUntAmntAmntTypCdgCd;
    }
    
    
    
    public String getSbstncPlymrRptRptUntAmntAmntTypCdgDsply() {
        return this.sbstncPlymrRptRptUntAmntAmntTypCdgDsply;
    }
    
    public void setSbstncPlymrRptRptUntAmntAmntTypCdgDsply(String sbstncPlymrRptRptUntAmntAmntTypCdgDsply) {
        this.sbstncPlymrRptRptUntAmntAmntTypCdgDsply = sbstncPlymrRptRptUntAmntAmntTypCdgDsply;
    }
    
    
    
    public String getSbstncPlymrRptRptUntAmntAmntTypCdgSys() {
        return this.sbstncPlymrRptRptUntAmntAmntTypCdgSys;
    }
    
    public void setSbstncPlymrRptRptUntAmntAmntTypCdgSys(String sbstncPlymrRptRptUntAmntAmntTypCdgSys) {
        this.sbstncPlymrRptRptUntAmntAmntTypCdgSys = sbstncPlymrRptRptUntAmntAmntTypCdgSys;
    }
    
    
    
    public String getSbstncPlymrRptRptUntAmntAmntTypCdgUsrSltd() {
        return this.sbstncPlymrRptRptUntAmntAmntTypCdgUsrSltd;
    }
    
    public void setSbstncPlymrRptRptUntAmntAmntTypCdgUsrSltd(String sbstncPlymrRptRptUntAmntAmntTypCdgUsrSltd) {
        this.sbstncPlymrRptRptUntAmntAmntTypCdgUsrSltd = sbstncPlymrRptRptUntAmntAmntTypCdgUsrSltd;
    }
    
    
    
    public String getSbstncPlymrRptRptUntAmntAmntTypCdgVrsn() {
        return this.sbstncPlymrRptRptUntAmntAmntTypCdgVrsn;
    }
    
    public void setSbstncPlymrRptRptUntAmntAmntTypCdgVrsn(String sbstncPlymrRptRptUntAmntAmntTypCdgVrsn) {
        this.sbstncPlymrRptRptUntAmntAmntTypCdgVrsn = sbstncPlymrRptRptUntAmntAmntTypCdgVrsn;
    }
    
    
    
    public String getSbstncPlymrRptRptUntAmntAmntTypTxt() {
        return this.sbstncPlymrRptRptUntAmntAmntTypTxt;
    }
    
    public void setSbstncPlymrRptRptUntAmntAmntTypTxt(String sbstncPlymrRptRptUntAmntAmntTypTxt) {
        this.sbstncPlymrRptRptUntAmntAmntTypTxt = sbstncPlymrRptRptUntAmntAmntTypTxt;
    }
    
    
    
    public String getSbstncPlymrRptRptUntAmntRfrncRngHiLmtCd() {
        return this.sbstncPlymrRptRptUntAmntRfrncRngHiLmtCd;
    }
    
    public void setSbstncPlymrRptRptUntAmntRfrncRngHiLmtCd(String sbstncPlymrRptRptUntAmntRfrncRngHiLmtCd) {
        this.sbstncPlymrRptRptUntAmntRfrncRngHiLmtCd = sbstncPlymrRptRptUntAmntRfrncRngHiLmtCd;
    }
    
    
    
    public String getSbstncPlymrRptRptUntAmntRfrncRngHiLmtCmprtr() {
        return this.sbstncPlymrRptRptUntAmntRfrncRngHiLmtCmprtr;
    }
    
    public void setSbstncPlymrRptRptUntAmntRfrncRngHiLmtCmprtr(String sbstncPlymrRptRptUntAmntRfrncRngHiLmtCmprtr) {
        this.sbstncPlymrRptRptUntAmntRfrncRngHiLmtCmprtr = sbstncPlymrRptRptUntAmntRfrncRngHiLmtCmprtr;
    }
    
    
    
    public String getSbstncPlymrRptRptUntAmntRfrncRngHiLmtSys() {
        return this.sbstncPlymrRptRptUntAmntRfrncRngHiLmtSys;
    }
    
    public void setSbstncPlymrRptRptUntAmntRfrncRngHiLmtSys(String sbstncPlymrRptRptUntAmntRfrncRngHiLmtSys) {
        this.sbstncPlymrRptRptUntAmntRfrncRngHiLmtSys = sbstncPlymrRptRptUntAmntRfrncRngHiLmtSys;
    }
    
    
    
    public String getSbstncPlymrRptRptUntAmntRfrncRngHiLmtUnt() {
        return this.sbstncPlymrRptRptUntAmntRfrncRngHiLmtUnt;
    }
    
    public void setSbstncPlymrRptRptUntAmntRfrncRngHiLmtUnt(String sbstncPlymrRptRptUntAmntRfrncRngHiLmtUnt) {
        this.sbstncPlymrRptRptUntAmntRfrncRngHiLmtUnt = sbstncPlymrRptRptUntAmntRfrncRngHiLmtUnt;
    }
    
    
    
    public String getSbstncPlymrRptRptUntAmntRfrncRngHiLmtVl() {
        return this.sbstncPlymrRptRptUntAmntRfrncRngHiLmtVl;
    }
    
    public void setSbstncPlymrRptRptUntAmntRfrncRngHiLmtVl(String sbstncPlymrRptRptUntAmntRfrncRngHiLmtVl) {
        this.sbstncPlymrRptRptUntAmntRfrncRngHiLmtVl = sbstncPlymrRptRptUntAmntRfrncRngHiLmtVl;
    }
    
    
    
    public String getSbstncPlymrRptRptUntAmntRfrncRngLwLmtCd() {
        return this.sbstncPlymrRptRptUntAmntRfrncRngLwLmtCd;
    }
    
    public void setSbstncPlymrRptRptUntAmntRfrncRngLwLmtCd(String sbstncPlymrRptRptUntAmntRfrncRngLwLmtCd) {
        this.sbstncPlymrRptRptUntAmntRfrncRngLwLmtCd = sbstncPlymrRptRptUntAmntRfrncRngLwLmtCd;
    }
    
    
    
    public String getSbstncPlymrRptRptUntAmntRfrncRngLwLmtCmprtr() {
        return this.sbstncPlymrRptRptUntAmntRfrncRngLwLmtCmprtr;
    }
    
    public void setSbstncPlymrRptRptUntAmntRfrncRngLwLmtCmprtr(String sbstncPlymrRptRptUntAmntRfrncRngLwLmtCmprtr) {
        this.sbstncPlymrRptRptUntAmntRfrncRngLwLmtCmprtr = sbstncPlymrRptRptUntAmntRfrncRngLwLmtCmprtr;
    }
    
    
    
    public String getSbstncPlymrRptRptUntAmntRfrncRngLwLmtSys() {
        return this.sbstncPlymrRptRptUntAmntRfrncRngLwLmtSys;
    }
    
    public void setSbstncPlymrRptRptUntAmntRfrncRngLwLmtSys(String sbstncPlymrRptRptUntAmntRfrncRngLwLmtSys) {
        this.sbstncPlymrRptRptUntAmntRfrncRngLwLmtSys = sbstncPlymrRptRptUntAmntRfrncRngLwLmtSys;
    }
    
    
    
    public String getSbstncPlymrRptRptUntAmntRfrncRngLwLmtUnt() {
        return this.sbstncPlymrRptRptUntAmntRfrncRngLwLmtUnt;
    }
    
    public void setSbstncPlymrRptRptUntAmntRfrncRngLwLmtUnt(String sbstncPlymrRptRptUntAmntRfrncRngLwLmtUnt) {
        this.sbstncPlymrRptRptUntAmntRfrncRngLwLmtUnt = sbstncPlymrRptRptUntAmntRfrncRngLwLmtUnt;
    }
    
    
    
    public String getSbstncPlymrRptRptUntAmntRfrncRngLwLmtVl() {
        return this.sbstncPlymrRptRptUntAmntRfrncRngLwLmtVl;
    }
    
    public void setSbstncPlymrRptRptUntAmntRfrncRngLwLmtVl(String sbstncPlymrRptRptUntAmntRfrncRngLwLmtVl) {
        this.sbstncPlymrRptRptUntAmntRfrncRngLwLmtVl = sbstncPlymrRptRptUntAmntRfrncRngLwLmtVl;
    }
    
    
    
    public String getSbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntQntyCd() {
        return this.sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntQntyCd;
    }
    
    public void setSbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntQntyCd(String sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntQntyCd) {
        this.sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntQntyCd = sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntQntyCd;
    }
    
    
    
    public String getSbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntQntyCmprtr() {
        return this.sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntQntyCmprtr;
    }
    
    public void setSbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntQntyCmprtr(String sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntQntyCmprtr) {
        this.sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntQntyCmprtr = sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntQntyCmprtr;
    }
    
    
    
    public String getSbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntQntySys() {
        return this.sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntQntySys;
    }
    
    public void setSbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntQntySys(String sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntQntySys) {
        this.sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntQntySys = sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntQntySys;
    }
    
    
    
    public String getSbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntQntyUnt() {
        return this.sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntQntyUnt;
    }
    
    public void setSbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntQntyUnt(String sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntQntyUnt) {
        this.sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntQntyUnt = sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntQntyUnt;
    }
    
    
    
    public String getSbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntQntyVl() {
        return this.sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntQntyVl;
    }
    
    public void setSbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntQntyVl(String sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntQntyVl) {
        this.sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntQntyVl = sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntQntyVl;
    }
    
    
    
    public String getSbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntRngHiCd() {
        return this.sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntRngHiCd;
    }
    
    public void setSbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntRngHiCd(String sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntRngHiCd) {
        this.sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntRngHiCd = sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntRngHiCd;
    }
    
    
    
    public String getSbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntRngHiCmprtr() {
        return this.sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntRngHiCmprtr;
    }
    
    public void setSbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntRngHiCmprtr(String sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntRngHiCmprtr) {
        this.sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntRngHiCmprtr = sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntRngHiCmprtr;
    }
    
    
    
    public String getSbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntRngHiSys() {
        return this.sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntRngHiSys;
    }
    
    public void setSbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntRngHiSys(String sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntRngHiSys) {
        this.sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntRngHiSys = sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntRngHiSys;
    }
    
    
    
    public String getSbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntRngHiUnt() {
        return this.sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntRngHiUnt;
    }
    
    public void setSbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntRngHiUnt(String sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntRngHiUnt) {
        this.sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntRngHiUnt = sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntRngHiUnt;
    }
    
    
    
    public String getSbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntRngHiVl() {
        return this.sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntRngHiVl;
    }
    
    public void setSbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntRngHiVl(String sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntRngHiVl) {
        this.sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntRngHiVl = sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntRngHiVl;
    }
    
    
    
    public String getSbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntRngLwCd() {
        return this.sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntRngLwCd;
    }
    
    public void setSbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntRngLwCd(String sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntRngLwCd) {
        this.sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntRngLwCd = sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntRngLwCd;
    }
    
    
    
    public String getSbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntRngLwCmprtr() {
        return this.sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntRngLwCmprtr;
    }
    
    public void setSbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntRngLwCmprtr(String sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntRngLwCmprtr) {
        this.sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntRngLwCmprtr = sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntRngLwCmprtr;
    }
    
    
    
    public String getSbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntRngLwSys() {
        return this.sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntRngLwSys;
    }
    
    public void setSbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntRngLwSys(String sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntRngLwSys) {
        this.sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntRngLwSys = sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntRngLwSys;
    }
    
    
    
    public String getSbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntRngLwUnt() {
        return this.sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntRngLwUnt;
    }
    
    public void setSbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntRngLwUnt(String sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntRngLwUnt) {
        this.sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntRngLwUnt = sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntRngLwUnt;
    }
    
    
    
    public String getSbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntRngLwVl() {
        return this.sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntRngLwVl;
    }
    
    public void setSbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntRngLwVl(String sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntRngLwVl) {
        this.sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntRngLwVl = sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntRngLwVl;
    }
    
    
    
    public String getSbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntStrgTyp() {
        return this.sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntStrgTyp;
    }
    
    public void setSbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntStrgTyp(String sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntStrgTyp) {
        this.sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntStrgTyp = sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntStrgTyp;
    }
    
    
    
    public String getSbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntTxt() {
        return this.sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntTxt;
    }
    
    public void setSbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntTxt(String sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntTxt) {
        this.sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntTxt = sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntTxt;
    }
    
    
    
    public String getSbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntTxtElmnt() {
        return this.sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntTxtElmnt;
    }
    
    public void setSbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntTxtElmnt(String sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntTxtElmnt) {
        this.sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntTxtElmnt = sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntTxtElmnt;
    }
    
    
    
    public String getSbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntTypCdgCd() {
        return this.sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntTypCdgCd;
    }
    
    public void setSbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntTypCdgCd(String sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntTypCdgCd) {
        this.sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntTypCdgCd = sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntTypCdgCd;
    }
    
    
    
    public String getSbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntTypCdgDsply() {
        return this.sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntTypCdgDsply;
    }
    
    public void setSbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntTypCdgDsply(String sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntTypCdgDsply) {
        this.sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntTypCdgDsply = sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntTypCdgDsply;
    }
    
    
    
    public String getSbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntTypCdgSys() {
        return this.sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntTypCdgSys;
    }
    
    public void setSbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntTypCdgSys(String sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntTypCdgSys) {
        this.sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntTypCdgSys = sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntTypCdgSys;
    }
    
    
    
    public String getSbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntTypCdgUsrSltd() {
        return this.sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntTypCdgUsrSltd;
    }
    
    public void setSbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntTypCdgUsrSltd(String sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntTypCdgUsrSltd) {
        this.sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntTypCdgUsrSltd = sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntTypCdgUsrSltd;
    }
    
    
    
    public String getSbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntTypCdgVrsn() {
        return this.sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntTypCdgVrsn;
    }
    
    public void setSbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntTypCdgVrsn(String sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntTypCdgVrsn) {
        this.sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntTypCdgVrsn = sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntTypCdgVrsn;
    }
    
    
    
    public String getSbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntTypTxt() {
        return this.sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntTypTxt;
    }
    
    public void setSbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntTypTxt(String sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntTypTxt) {
        this.sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntTypTxt = sbstncPlymrRptRptUntDgrOfPlymrstnAmntAmntTypTxt;
    }
    
    
    
    public String getSbstncPlymrRptRptUntDgrOfPlymrstnAmntRfrncRngHiLmtCd() {
        return this.sbstncPlymrRptRptUntDgrOfPlymrstnAmntRfrncRngHiLmtCd;
    }
    
    public void setSbstncPlymrRptRptUntDgrOfPlymrstnAmntRfrncRngHiLmtCd(String sbstncPlymrRptRptUntDgrOfPlymrstnAmntRfrncRngHiLmtCd) {
        this.sbstncPlymrRptRptUntDgrOfPlymrstnAmntRfrncRngHiLmtCd = sbstncPlymrRptRptUntDgrOfPlymrstnAmntRfrncRngHiLmtCd;
    }
    
    
    
    public String getSbstncPlymrRptRptUntDgrOfPlymrstnAmntRfrncRngHiLmtCmprtr() {
        return this.sbstncPlymrRptRptUntDgrOfPlymrstnAmntRfrncRngHiLmtCmprtr;
    }
    
    public void setSbstncPlymrRptRptUntDgrOfPlymrstnAmntRfrncRngHiLmtCmprtr(String sbstncPlymrRptRptUntDgrOfPlymrstnAmntRfrncRngHiLmtCmprtr) {
        this.sbstncPlymrRptRptUntDgrOfPlymrstnAmntRfrncRngHiLmtCmprtr = sbstncPlymrRptRptUntDgrOfPlymrstnAmntRfrncRngHiLmtCmprtr;
    }
    
    
    
    public String getSbstncPlymrRptRptUntDgrOfPlymrstnAmntRfrncRngHiLmtSys() {
        return this.sbstncPlymrRptRptUntDgrOfPlymrstnAmntRfrncRngHiLmtSys;
    }
    
    public void setSbstncPlymrRptRptUntDgrOfPlymrstnAmntRfrncRngHiLmtSys(String sbstncPlymrRptRptUntDgrOfPlymrstnAmntRfrncRngHiLmtSys) {
        this.sbstncPlymrRptRptUntDgrOfPlymrstnAmntRfrncRngHiLmtSys = sbstncPlymrRptRptUntDgrOfPlymrstnAmntRfrncRngHiLmtSys;
    }
    
    
    
    public String getSbstncPlymrRptRptUntDgrOfPlymrstnAmntRfrncRngHiLmtUnt() {
        return this.sbstncPlymrRptRptUntDgrOfPlymrstnAmntRfrncRngHiLmtUnt;
    }
    
    public void setSbstncPlymrRptRptUntDgrOfPlymrstnAmntRfrncRngHiLmtUnt(String sbstncPlymrRptRptUntDgrOfPlymrstnAmntRfrncRngHiLmtUnt) {
        this.sbstncPlymrRptRptUntDgrOfPlymrstnAmntRfrncRngHiLmtUnt = sbstncPlymrRptRptUntDgrOfPlymrstnAmntRfrncRngHiLmtUnt;
    }
    
    
    
    public String getSbstncPlymrRptRptUntDgrOfPlymrstnAmntRfrncRngHiLmtVl() {
        return this.sbstncPlymrRptRptUntDgrOfPlymrstnAmntRfrncRngHiLmtVl;
    }
    
    public void setSbstncPlymrRptRptUntDgrOfPlymrstnAmntRfrncRngHiLmtVl(String sbstncPlymrRptRptUntDgrOfPlymrstnAmntRfrncRngHiLmtVl) {
        this.sbstncPlymrRptRptUntDgrOfPlymrstnAmntRfrncRngHiLmtVl = sbstncPlymrRptRptUntDgrOfPlymrstnAmntRfrncRngHiLmtVl;
    }
    
    
    
    public String getSbstncPlymrRptRptUntDgrOfPlymrstnAmntRfrncRngLwLmtCd() {
        return this.sbstncPlymrRptRptUntDgrOfPlymrstnAmntRfrncRngLwLmtCd;
    }
    
    public void setSbstncPlymrRptRptUntDgrOfPlymrstnAmntRfrncRngLwLmtCd(String sbstncPlymrRptRptUntDgrOfPlymrstnAmntRfrncRngLwLmtCd) {
        this.sbstncPlymrRptRptUntDgrOfPlymrstnAmntRfrncRngLwLmtCd = sbstncPlymrRptRptUntDgrOfPlymrstnAmntRfrncRngLwLmtCd;
    }
    
    
    
    public String getSbstncPlymrRptRptUntDgrOfPlymrstnAmntRfrncRngLwLmtCmprtr() {
        return this.sbstncPlymrRptRptUntDgrOfPlymrstnAmntRfrncRngLwLmtCmprtr;
    }
    
    public void setSbstncPlymrRptRptUntDgrOfPlymrstnAmntRfrncRngLwLmtCmprtr(String sbstncPlymrRptRptUntDgrOfPlymrstnAmntRfrncRngLwLmtCmprtr) {
        this.sbstncPlymrRptRptUntDgrOfPlymrstnAmntRfrncRngLwLmtCmprtr = sbstncPlymrRptRptUntDgrOfPlymrstnAmntRfrncRngLwLmtCmprtr;
    }
    
    
    
    public String getSbstncPlymrRptRptUntDgrOfPlymrstnAmntRfrncRngLwLmtSys() {
        return this.sbstncPlymrRptRptUntDgrOfPlymrstnAmntRfrncRngLwLmtSys;
    }
    
    public void setSbstncPlymrRptRptUntDgrOfPlymrstnAmntRfrncRngLwLmtSys(String sbstncPlymrRptRptUntDgrOfPlymrstnAmntRfrncRngLwLmtSys) {
        this.sbstncPlymrRptRptUntDgrOfPlymrstnAmntRfrncRngLwLmtSys = sbstncPlymrRptRptUntDgrOfPlymrstnAmntRfrncRngLwLmtSys;
    }
    
    
    
    public String getSbstncPlymrRptRptUntDgrOfPlymrstnAmntRfrncRngLwLmtUnt() {
        return this.sbstncPlymrRptRptUntDgrOfPlymrstnAmntRfrncRngLwLmtUnt;
    }
    
    public void setSbstncPlymrRptRptUntDgrOfPlymrstnAmntRfrncRngLwLmtUnt(String sbstncPlymrRptRptUntDgrOfPlymrstnAmntRfrncRngLwLmtUnt) {
        this.sbstncPlymrRptRptUntDgrOfPlymrstnAmntRfrncRngLwLmtUnt = sbstncPlymrRptRptUntDgrOfPlymrstnAmntRfrncRngLwLmtUnt;
    }
    
    
    
    public String getSbstncPlymrRptRptUntDgrOfPlymrstnAmntRfrncRngLwLmtVl() {
        return this.sbstncPlymrRptRptUntDgrOfPlymrstnAmntRfrncRngLwLmtVl;
    }
    
    public void setSbstncPlymrRptRptUntDgrOfPlymrstnAmntRfrncRngLwLmtVl(String sbstncPlymrRptRptUntDgrOfPlymrstnAmntRfrncRngLwLmtVl) {
        this.sbstncPlymrRptRptUntDgrOfPlymrstnAmntRfrncRngLwLmtVl = sbstncPlymrRptRptUntDgrOfPlymrstnAmntRfrncRngLwLmtVl;
    }
    
    
    
    public String getSbstncPlymrRptRptUntDgrOfPlymrstnDegreeCdgCd() {
        return this.sbstncPlymrRptRptUntDgrOfPlymrstnDegreeCdgCd;
    }
    
    public void setSbstncPlymrRptRptUntDgrOfPlymrstnDegreeCdgCd(String sbstncPlymrRptRptUntDgrOfPlymrstnDegreeCdgCd) {
        this.sbstncPlymrRptRptUntDgrOfPlymrstnDegreeCdgCd = sbstncPlymrRptRptUntDgrOfPlymrstnDegreeCdgCd;
    }
    
    
    
    public String getSbstncPlymrRptRptUntDgrOfPlymrstnDegreeCdgDsply() {
        return this.sbstncPlymrRptRptUntDgrOfPlymrstnDegreeCdgDsply;
    }
    
    public void setSbstncPlymrRptRptUntDgrOfPlymrstnDegreeCdgDsply(String sbstncPlymrRptRptUntDgrOfPlymrstnDegreeCdgDsply) {
        this.sbstncPlymrRptRptUntDgrOfPlymrstnDegreeCdgDsply = sbstncPlymrRptRptUntDgrOfPlymrstnDegreeCdgDsply;
    }
    
    
    
    public String getSbstncPlymrRptRptUntDgrOfPlymrstnDegreeCdgSys() {
        return this.sbstncPlymrRptRptUntDgrOfPlymrstnDegreeCdgSys;
    }
    
    public void setSbstncPlymrRptRptUntDgrOfPlymrstnDegreeCdgSys(String sbstncPlymrRptRptUntDgrOfPlymrstnDegreeCdgSys) {
        this.sbstncPlymrRptRptUntDgrOfPlymrstnDegreeCdgSys = sbstncPlymrRptRptUntDgrOfPlymrstnDegreeCdgSys;
    }
    
    
    
    public String getSbstncPlymrRptRptUntDgrOfPlymrstnDegreeCdgUsrSltd() {
        return this.sbstncPlymrRptRptUntDgrOfPlymrstnDegreeCdgUsrSltd;
    }
    
    public void setSbstncPlymrRptRptUntDgrOfPlymrstnDegreeCdgUsrSltd(String sbstncPlymrRptRptUntDgrOfPlymrstnDegreeCdgUsrSltd) {
        this.sbstncPlymrRptRptUntDgrOfPlymrstnDegreeCdgUsrSltd = sbstncPlymrRptRptUntDgrOfPlymrstnDegreeCdgUsrSltd;
    }
    
    
    
    public String getSbstncPlymrRptRptUntDgrOfPlymrstnDegreeCdgVrsn() {
        return this.sbstncPlymrRptRptUntDgrOfPlymrstnDegreeCdgVrsn;
    }
    
    public void setSbstncPlymrRptRptUntDgrOfPlymrstnDegreeCdgVrsn(String sbstncPlymrRptRptUntDgrOfPlymrstnDegreeCdgVrsn) {
        this.sbstncPlymrRptRptUntDgrOfPlymrstnDegreeCdgVrsn = sbstncPlymrRptRptUntDgrOfPlymrstnDegreeCdgVrsn;
    }
    
    
    
    public String getSbstncPlymrRptRptUntDgrOfPlymrstnDegreeTxt() {
        return this.sbstncPlymrRptRptUntDgrOfPlymrstnDegreeTxt;
    }
    
    public void setSbstncPlymrRptRptUntDgrOfPlymrstnDegreeTxt(String sbstncPlymrRptRptUntDgrOfPlymrstnDegreeTxt) {
        this.sbstncPlymrRptRptUntDgrOfPlymrstnDegreeTxt = sbstncPlymrRptRptUntDgrOfPlymrstnDegreeTxt;
    }
    
    
    
    public String getSbstncPlymrRptRptUntOrientationOfPlymrisationCdgCd() {
        return this.sbstncPlymrRptRptUntOrientationOfPlymrisationCdgCd;
    }
    
    public void setSbstncPlymrRptRptUntOrientationOfPlymrisationCdgCd(String sbstncPlymrRptRptUntOrientationOfPlymrisationCdgCd) {
        this.sbstncPlymrRptRptUntOrientationOfPlymrisationCdgCd = sbstncPlymrRptRptUntOrientationOfPlymrisationCdgCd;
    }
    
    
    
    public String getSbstncPlymrRptRptUntOrientationOfPlymrisationCdgDsply() {
        return this.sbstncPlymrRptRptUntOrientationOfPlymrisationCdgDsply;
    }
    
    public void setSbstncPlymrRptRptUntOrientationOfPlymrisationCdgDsply(String sbstncPlymrRptRptUntOrientationOfPlymrisationCdgDsply) {
        this.sbstncPlymrRptRptUntOrientationOfPlymrisationCdgDsply = sbstncPlymrRptRptUntOrientationOfPlymrisationCdgDsply;
    }
    
    
    
    public String getSbstncPlymrRptRptUntOrientationOfPlymrisationCdgSys() {
        return this.sbstncPlymrRptRptUntOrientationOfPlymrisationCdgSys;
    }
    
    public void setSbstncPlymrRptRptUntOrientationOfPlymrisationCdgSys(String sbstncPlymrRptRptUntOrientationOfPlymrisationCdgSys) {
        this.sbstncPlymrRptRptUntOrientationOfPlymrisationCdgSys = sbstncPlymrRptRptUntOrientationOfPlymrisationCdgSys;
    }
    
    
    
    public String getSbstncPlymrRptRptUntOrientationOfPlymrisationCdgUsrSltd() {
        return this.sbstncPlymrRptRptUntOrientationOfPlymrisationCdgUsrSltd;
    }
    
    public void setSbstncPlymrRptRptUntOrientationOfPlymrisationCdgUsrSltd(String sbstncPlymrRptRptUntOrientationOfPlymrisationCdgUsrSltd) {
        this.sbstncPlymrRptRptUntOrientationOfPlymrisationCdgUsrSltd = sbstncPlymrRptRptUntOrientationOfPlymrisationCdgUsrSltd;
    }
    
    
    
    public String getSbstncPlymrRptRptUntOrientationOfPlymrisationCdgVrsn() {
        return this.sbstncPlymrRptRptUntOrientationOfPlymrisationCdgVrsn;
    }
    
    public void setSbstncPlymrRptRptUntOrientationOfPlymrisationCdgVrsn(String sbstncPlymrRptRptUntOrientationOfPlymrisationCdgVrsn) {
        this.sbstncPlymrRptRptUntOrientationOfPlymrisationCdgVrsn = sbstncPlymrRptRptUntOrientationOfPlymrisationCdgVrsn;
    }
    
    
    
    public String getSbstncPlymrRptRptUntOrientationOfPlymrisationTxt() {
        return this.sbstncPlymrRptRptUntOrientationOfPlymrisationTxt;
    }
    
    public void setSbstncPlymrRptRptUntOrientationOfPlymrisationTxt(String sbstncPlymrRptRptUntOrientationOfPlymrisationTxt) {
        this.sbstncPlymrRptRptUntOrientationOfPlymrisationTxt = sbstncPlymrRptRptUntOrientationOfPlymrisationTxt;
    }
    
    
    
    public String getSbstncPlymrRptRptUntRptUnt() {
        return this.sbstncPlymrRptRptUntRptUnt;
    }
    
    public void setSbstncPlymrRptRptUntRptUnt(String sbstncPlymrRptRptUntRptUnt) {
        this.sbstncPlymrRptRptUntRptUnt = sbstncPlymrRptRptUntRptUnt;
    }
    
    
    
    public String getSbstncPlymrRptRptUntStrctrlRprsnttnAttchmntCntntTyp() {
        return this.sbstncPlymrRptRptUntStrctrlRprsnttnAttchmntCntntTyp;
    }
    
    public void setSbstncPlymrRptRptUntStrctrlRprsnttnAttchmntCntntTyp(String sbstncPlymrRptRptUntStrctrlRprsnttnAttchmntCntntTyp) {
        this.sbstncPlymrRptRptUntStrctrlRprsnttnAttchmntCntntTyp = sbstncPlymrRptRptUntStrctrlRprsnttnAttchmntCntntTyp;
    }
    
    
    
    public String getSbstncPlymrRptRptUntStrctrlRprsnttnAttchmntCreation() {
        return this.sbstncPlymrRptRptUntStrctrlRprsnttnAttchmntCreation;
    }
    
    public void setSbstncPlymrRptRptUntStrctrlRprsnttnAttchmntCreation(String sbstncPlymrRptRptUntStrctrlRprsnttnAttchmntCreation) {
        this.sbstncPlymrRptRptUntStrctrlRprsnttnAttchmntCreation = sbstncPlymrRptRptUntStrctrlRprsnttnAttchmntCreation;
    }
    
    
    
    public String getSbstncPlymrRptRptUntStrctrlRprsnttnAttchmntData() {
        return this.sbstncPlymrRptRptUntStrctrlRprsnttnAttchmntData;
    }
    
    public void setSbstncPlymrRptRptUntStrctrlRprsnttnAttchmntData(String sbstncPlymrRptRptUntStrctrlRprsnttnAttchmntData) {
        this.sbstncPlymrRptRptUntStrctrlRprsnttnAttchmntData = sbstncPlymrRptRptUntStrctrlRprsnttnAttchmntData;
    }
    
    
    
    public String getSbstncPlymrRptRptUntStrctrlRprsnttnAttchmntHash() {
        return this.sbstncPlymrRptRptUntStrctrlRprsnttnAttchmntHash;
    }
    
    public void setSbstncPlymrRptRptUntStrctrlRprsnttnAttchmntHash(String sbstncPlymrRptRptUntStrctrlRprsnttnAttchmntHash) {
        this.sbstncPlymrRptRptUntStrctrlRprsnttnAttchmntHash = sbstncPlymrRptRptUntStrctrlRprsnttnAttchmntHash;
    }
    
    
    
    public String getSbstncPlymrRptRptUntStrctrlRprsnttnAttchmntLnguage() {
        return this.sbstncPlymrRptRptUntStrctrlRprsnttnAttchmntLnguage;
    }
    
    public void setSbstncPlymrRptRptUntStrctrlRprsnttnAttchmntLnguage(String sbstncPlymrRptRptUntStrctrlRprsnttnAttchmntLnguage) {
        this.sbstncPlymrRptRptUntStrctrlRprsnttnAttchmntLnguage = sbstncPlymrRptRptUntStrctrlRprsnttnAttchmntLnguage;
    }
    
    
    
    public String getSbstncPlymrRptRptUntStrctrlRprsnttnAttchmntSz() {
        return this.sbstncPlymrRptRptUntStrctrlRprsnttnAttchmntSz;
    }
    
    public void setSbstncPlymrRptRptUntStrctrlRprsnttnAttchmntSz(String sbstncPlymrRptRptUntStrctrlRprsnttnAttchmntSz) {
        this.sbstncPlymrRptRptUntStrctrlRprsnttnAttchmntSz = sbstncPlymrRptRptUntStrctrlRprsnttnAttchmntSz;
    }
    
    
    
    public String getSbstncPlymrRptRptUntStrctrlRprsnttnAttchmntTtl() {
        return this.sbstncPlymrRptRptUntStrctrlRprsnttnAttchmntTtl;
    }
    
    public void setSbstncPlymrRptRptUntStrctrlRprsnttnAttchmntTtl(String sbstncPlymrRptRptUntStrctrlRprsnttnAttchmntTtl) {
        this.sbstncPlymrRptRptUntStrctrlRprsnttnAttchmntTtl = sbstncPlymrRptRptUntStrctrlRprsnttnAttchmntTtl;
    }
    
    
    
    public String getSbstncPlymrRptRptUntStrctrlRprsnttnAttchmntUrl() {
        return this.sbstncPlymrRptRptUntStrctrlRprsnttnAttchmntUrl;
    }
    
    public void setSbstncPlymrRptRptUntStrctrlRprsnttnAttchmntUrl(String sbstncPlymrRptRptUntStrctrlRprsnttnAttchmntUrl) {
        this.sbstncPlymrRptRptUntStrctrlRprsnttnAttchmntUrl = sbstncPlymrRptRptUntStrctrlRprsnttnAttchmntUrl;
    }
    
    
    
    public String getSbstncPlymrRptRptUntStrctrlRprsnttnRepresentation() {
        return this.sbstncPlymrRptRptUntStrctrlRprsnttnRepresentation;
    }
    
    public void setSbstncPlymrRptRptUntStrctrlRprsnttnRepresentation(String sbstncPlymrRptRptUntStrctrlRprsnttnRepresentation) {
        this.sbstncPlymrRptRptUntStrctrlRprsnttnRepresentation = sbstncPlymrRptRptUntStrctrlRprsnttnRepresentation;
    }
    
    
    
    public String getSbstncPlymrRptRptUntStrctrlRprsnttnTypCdgCd() {
        return this.sbstncPlymrRptRptUntStrctrlRprsnttnTypCdgCd;
    }
    
    public void setSbstncPlymrRptRptUntStrctrlRprsnttnTypCdgCd(String sbstncPlymrRptRptUntStrctrlRprsnttnTypCdgCd) {
        this.sbstncPlymrRptRptUntStrctrlRprsnttnTypCdgCd = sbstncPlymrRptRptUntStrctrlRprsnttnTypCdgCd;
    }
    
    
    
    public String getSbstncPlymrRptRptUntStrctrlRprsnttnTypCdgDsply() {
        return this.sbstncPlymrRptRptUntStrctrlRprsnttnTypCdgDsply;
    }
    
    public void setSbstncPlymrRptRptUntStrctrlRprsnttnTypCdgDsply(String sbstncPlymrRptRptUntStrctrlRprsnttnTypCdgDsply) {
        this.sbstncPlymrRptRptUntStrctrlRprsnttnTypCdgDsply = sbstncPlymrRptRptUntStrctrlRprsnttnTypCdgDsply;
    }
    
    
    
    public String getSbstncPlymrRptRptUntStrctrlRprsnttnTypCdgSys() {
        return this.sbstncPlymrRptRptUntStrctrlRprsnttnTypCdgSys;
    }
    
    public void setSbstncPlymrRptRptUntStrctrlRprsnttnTypCdgSys(String sbstncPlymrRptRptUntStrctrlRprsnttnTypCdgSys) {
        this.sbstncPlymrRptRptUntStrctrlRprsnttnTypCdgSys = sbstncPlymrRptRptUntStrctrlRprsnttnTypCdgSys;
    }
    
    
    
    public String getSbstncPlymrRptRptUntStrctrlRprsnttnTypCdgUsrSltd() {
        return this.sbstncPlymrRptRptUntStrctrlRprsnttnTypCdgUsrSltd;
    }
    
    public void setSbstncPlymrRptRptUntStrctrlRprsnttnTypCdgUsrSltd(String sbstncPlymrRptRptUntStrctrlRprsnttnTypCdgUsrSltd) {
        this.sbstncPlymrRptRptUntStrctrlRprsnttnTypCdgUsrSltd = sbstncPlymrRptRptUntStrctrlRprsnttnTypCdgUsrSltd;
    }
    
    
    
    public String getSbstncPlymrRptRptUntStrctrlRprsnttnTypCdgVrsn() {
        return this.sbstncPlymrRptRptUntStrctrlRprsnttnTypCdgVrsn;
    }
    
    public void setSbstncPlymrRptRptUntStrctrlRprsnttnTypCdgVrsn(String sbstncPlymrRptRptUntStrctrlRprsnttnTypCdgVrsn) {
        this.sbstncPlymrRptRptUntStrctrlRprsnttnTypCdgVrsn = sbstncPlymrRptRptUntStrctrlRprsnttnTypCdgVrsn;
    }
    
    
    
    public String getSbstncPlymrRptRptUntStrctrlRprsnttnTypTxt() {
        return this.sbstncPlymrRptRptUntStrctrlRprsnttnTypTxt;
    }
    
    public void setSbstncPlymrRptRptUntStrctrlRprsnttnTypTxt(String sbstncPlymrRptRptUntStrctrlRprsnttnTypTxt) {
        this.sbstncPlymrRptRptUntStrctrlRprsnttnTypTxt = sbstncPlymrRptRptUntStrctrlRprsnttnTypTxt;
    }
    
    
    
    public String getSbstncPlymrRptRptUntAmntTypCdgCd() {
        return this.sbstncPlymrRptRptUntAmntTypCdgCd;
    }
    
    public void setSbstncPlymrRptRptUntAmntTypCdgCd(String sbstncPlymrRptRptUntAmntTypCdgCd) {
        this.sbstncPlymrRptRptUntAmntTypCdgCd = sbstncPlymrRptRptUntAmntTypCdgCd;
    }
    
    
    
    public String getSbstncPlymrRptRptUntAmntTypCdgDsply() {
        return this.sbstncPlymrRptRptUntAmntTypCdgDsply;
    }
    
    public void setSbstncPlymrRptRptUntAmntTypCdgDsply(String sbstncPlymrRptRptUntAmntTypCdgDsply) {
        this.sbstncPlymrRptRptUntAmntTypCdgDsply = sbstncPlymrRptRptUntAmntTypCdgDsply;
    }
    
    
    
    public String getSbstncPlymrRptRptUntAmntTypCdgSys() {
        return this.sbstncPlymrRptRptUntAmntTypCdgSys;
    }
    
    public void setSbstncPlymrRptRptUntAmntTypCdgSys(String sbstncPlymrRptRptUntAmntTypCdgSys) {
        this.sbstncPlymrRptRptUntAmntTypCdgSys = sbstncPlymrRptRptUntAmntTypCdgSys;
    }
    
    
    
    public String getSbstncPlymrRptRptUntAmntTypCdgUsrSltd() {
        return this.sbstncPlymrRptRptUntAmntTypCdgUsrSltd;
    }
    
    public void setSbstncPlymrRptRptUntAmntTypCdgUsrSltd(String sbstncPlymrRptRptUntAmntTypCdgUsrSltd) {
        this.sbstncPlymrRptRptUntAmntTypCdgUsrSltd = sbstncPlymrRptRptUntAmntTypCdgUsrSltd;
    }
    
    
    
    public String getSbstncPlymrRptRptUntAmntTypCdgVrsn() {
        return this.sbstncPlymrRptRptUntAmntTypCdgVrsn;
    }
    
    public void setSbstncPlymrRptRptUntAmntTypCdgVrsn(String sbstncPlymrRptRptUntAmntTypCdgVrsn) {
        this.sbstncPlymrRptRptUntAmntTypCdgVrsn = sbstncPlymrRptRptUntAmntTypCdgVrsn;
    }
    
    
    
    public String getSbstncPlymrRptRptUntAmntTypTxt() {
        return this.sbstncPlymrRptRptUntAmntTypTxt;
    }
    
    public void setSbstncPlymrRptRptUntAmntTypTxt(String sbstncPlymrRptRptUntAmntTypTxt) {
        this.sbstncPlymrRptRptUntAmntTypTxt = sbstncPlymrRptRptUntAmntTypTxt;
    }
    
    
    




}


