
CREATE OR REPLACE VIEW public.campfhir_view_patient
AS
 SELECT DISTINCT dem.patid AS id,
    NULL::text AS patient_active,
    NULL::text AS patient_address_city,
    NULL::text AS patient_address_country,
    NULL::text AS patient_address_district,
    NULL::text AS patient_address_line,
    NULL::text AS patient_address_period_end,
    NULL::text AS patient_address_period_start,
    NULL::text AS patient_address_postalcode,
    NULL::text AS patient_address_state,
    NULL::text AS patient_address_text,
    NULL::text AS patient_address_type_code,
    NULL::text AS patient_address_use_code,
    NULL::text AS patient_address_extension_longitude_value,
    NULL::text AS patient_address_extension_latitude_value,
    to_char(dem.birth_date, 'YYYY-MM-DD'::text) AS patient_birthdate,
    COALESCE(cmv5.fhir_out_code, NULL::character varying) AS patient_commn_lang_coding_code,
    COALESCE(cmv5.fhir_out_char, NULL::character varying) AS patient_commn_lang_coding_display,
    COALESCE(cmv5.fhir_system, NULL::character varying) AS patient_commn_lang_coding_system,
    NULL::text AS patient_commn_lang_coding_usrslt,
    NULL::text AS patient_commn_lang_coding_version,
    NULL::text AS patient_commn_lang_text,
    NULL::text AS patient_commn_preferred,
    NULL::text AS patient_contact_address_city,
    NULL::text AS patient_contact_address_country,
    NULL::text AS patient_contact_address_district,
    NULL::text AS patient_contact_address_line,
    NULL::text AS patient_contact_address_period_end,
    NULL::text AS patient_contact_address_period_start,
    NULL::text AS patient_contact_address_postalcode,
    NULL::text AS patient_contact_address_state,
    NULL::text AS patient_contact_address_text,
    NULL::text AS patient_contact_address_type_code,
    NULL::text AS patient_contact_address_use_code,
    NULL::text AS patient_contact_gender_code,
    NULL::text AS patient_contact_name_family,
    NULL::text AS patient_contact_name_given,
    NULL::text AS patient_contact_name_period_end,
    NULL::text AS patient_contact_name_period_start,
    NULL::text AS patient_contact_name_prefix,
    NULL::text AS patient_contact_name_suffix,
    NULL::text AS patient_contact_name_text,
    NULL::text AS patient_contact_name_use_code,
    NULL::text AS patient_contact_organization,
    NULL::text AS patient_contact_period_end,
    NULL::text AS patient_contact_period_start,
    NULL::text AS patient_contact_relationship_coding_code,
    NULL::text AS patient_contact_relationship_coding_display,
    NULL::text AS patient_contact_relationship_coding_system,
    NULL::text AS patient_contact_relationship_coding_usrslt,
    NULL::text AS patient_contact_relationship_coding_version,
    NULL::text AS patient_contact_relationship_text,
    NULL::text AS patient_contact_telecom_period_end,
    NULL::text AS patient_contact_telecom_period_start,
    NULL::text AS patient_contact_telecom_rank,
    NULL::text AS patient_contact_telecom_system_code,
    NULL::text AS patient_contact_telecom_use_code,
    NULL::text AS patient_contact_telecom_value,
        CASE
            WHEN ((d.patid IS NOT NULL) AND (d.death_date IS NULL)) THEN 'true'::text
            ELSE NULL::text
        END AS patient_deceasedboolean,
    to_char(d.death_date, 'YYYY-MM-DD'::text) AS patient_deceaseddatetime,
    COALESCE(cmv1.fhir_out_code, NULL::character varying) AS patient_gender_code,
    NULL::text AS patient_generalpract,
    NULL::text AS patient_id_assigner,
    NULL::text AS patient_id_period_end,
    NULL::text AS patient_id_period_start,
    NULL::text AS patient_id_system,
    NULL::text AS patient_id_type_coding_code,
    NULL::text AS patient_id_type_coding_display,
    NULL::text AS patient_id_type_coding_system,
    NULL::text AS patient_id_type_coding_usrslt,
    NULL::text AS patient_id_type_coding_version,
    NULL::text AS patient_id_type_text,
    'secondary'::text AS patient_id_use_code,
    dem.patid AS patient_id_value,
    NULL::text AS patient_link_other,
    NULL::text AS patient_link_type_code,
    NULL::text AS patient_managingorganization,
    NULL::text AS patient_maritalstatus_coding_code,
    NULL::text AS patient_maritalstatus_coding_display,
    NULL::text AS patient_maritalstatus_coding_system,
    NULL::text AS patient_maritalstatus_coding_usrslt,
    NULL::text AS patient_maritalstatus_coding_version,
    NULL::text AS patient_maritalstatus_text,
    NULL::text AS patient_multiplebirthboolean,
    NULL::text AS patient_multiplebirthinteger,
    NULL::text AS patient_name_family,
    NULL::text AS patient_name_given,
    NULL::text AS patient_name_period_end,
    NULL::text AS patient_name_period_start,
    NULL::text AS patient_name_prefix,
    NULL::text AS patient_name_suffix,
    NULL::text AS patient_name_text,
    NULL::text AS patient_name_use_code,
    NULL::text AS patient_photo_contenttype,
    NULL::text AS patient_photo_creation,
    NULL::text AS patient_photo_data,
    NULL::text AS patient_photo_hash,
    NULL::text AS patient_photo_lang,
    NULL::text AS patient_photo_size,
    NULL::text AS patient_photo_title,
    NULL::text AS patient_photo_url,
    NULL::text AS patient_telecom_period_end,
    NULL::text AS patient_telecom_period_start,
    NULL::text AS patient_telecom_rank,
    NULL::text AS patient_telecom_system_code,
    NULL::text AS patient_telecom_use_code,
    NULL::text AS patient_telecom_value,
    COALESCE(cmv3.fhir_out_code, NULL::character varying) AS patient_race_code,
    COALESCE(cmv3.fhir_urn_oid_system, NULL::character varying) AS patient_race_system,
    COALESCE(cmv3.fhir_out_char, NULL::character varying) AS patient_race_display,
    COALESCE(cmv3.fhir_out_char, NULL::character varying) AS patient_race_value,
    COALESCE(cmv4.fhir_out_code, NULL::character varying) AS patient_ethnicity_code,
    COALESCE(cmv4.fhir_urn_oid_system, NULL::character varying) AS patient_ethnicity_system,
    COALESCE(cmv4.fhir_out_char, NULL::character varying) AS patient_ethnicity_display,
    COALESCE(cmv4.fhir_out_char, NULL::character varying) AS patient_ethnicity_value
   FROM (((((demographic dem
     LEFT JOIN death d ON (((dem.patid)::text = (d.patid)::text)))
     LEFT JOIN campfhir_mapping_valueset cmv1 ON ((((cmv1.local_column)::text = 'SEX'::text) AND ((dem.sex)::text = (cmv1.local_in_code)::text))))
     LEFT JOIN campfhir_mapping_valueset cmv3 ON ((((cmv3.local_column)::text = 'RACE'::text) AND ((dem.race)::text = (cmv3.local_in_code)::text))))
     LEFT JOIN campfhir_mapping_valueset cmv4 ON ((((cmv4.local_column)::text = 'HISPANIC'::text) AND ((dem.hispanic)::text = (cmv4.local_in_code)::text))))
     LEFT JOIN campfhir_mapping_valueset cmv5 ON ((((cmv5.local_column)::text = 'PAT_PREF_LANGUAGE_SPOKEN'::text) AND ((dem.pat_pref_language_spoken)::text = (cmv5.local_in_code)::text))));
/
